import type Database from 'better-sqlite3';
import {Employment,Person,EmploymentHistory,PersonHistory} from '../../../contracts/employment/schema';
export function validateCandidate(db:Database.Database):void {
 const employments=new Map<string,Employment>();const persons=new Map<string,Person>();
 for(const row of db.prepare('SELECT id,revision,value_json FROM employment_current').all() as {id:string;revision:number;value_json:string}[]){const value=Employment.parse(JSON.parse(row.value_json));if(value.id!==row.id||value.revision!==row.revision)throw Error('invalid_candidate');employments.set(value.id,value);}
 for(const row of db.prepare('SELECT employment_id,revision,value_json FROM employment_history').all() as {employment_id:string;revision:number;value_json:string}[]){const value=EmploymentHistory.parse(JSON.parse(row.value_json));const current=employments.get(row.employment_id);if(!current||value.employment.id!==row.employment_id||value.revision!==row.revision||value.employment.revision!==row.revision||row.revision>current.revision)throw Error('invalid_candidate');}
 for(const row of db.prepare('SELECT id,employment_id,revision,value_json FROM employment_person').all() as {id:string;employment_id:string;revision:number;value_json:string}[]){const value=Person.parse(JSON.parse(row.value_json));if(value.id!==row.id||value.employmentId!==row.employment_id||value.revision!==row.revision||!employments.has(value.employmentId))throw Error('invalid_candidate');persons.set(value.id,value);}
 for(const row of db.prepare('SELECT person_id,revision,value_json FROM employment_person_history').all() as {person_id:string;revision:number;value_json:string}[]){const value=PersonHistory.parse(JSON.parse(row.value_json));const current=persons.get(row.person_id);if(!current||value.person.id!==row.person_id||value.revision!==row.revision||value.person.revision!==row.revision||value.person.employmentId!==current.employmentId||row.revision>current.revision)throw Error('invalid_candidate');}
}
/** Employment/Person relations are contained and validated within this owner. */
export function candidateRelations(_db:Database.Database):{owner:string;objectId:string;kind:'object'|'source'}[]{return [];}
