import {test,expect} from 'vitest';import{chromium}from'playwright';import{createServer}from'vite';import{mkdir,writeFile,rm}from'node:fs/promises';import path from'node:path';
async function fixture(mode='normal'){
 const root=path.resolve('out/f3b-validation/UI-TEST');await mkdir(root,{recursive:true});await writeFile(path.join(root,'index.html'),'<div id="root"></div><script type="module" src="/main.tsx"></script>');
 await writeFile(path.join(root,'main.tsx'),`import React from'react';import{createRoot}from'react-dom/client';import{BitableRecordPreview}from'../../../packages/frontend/features/materials/BitableRecordPreview';import'../../../packages/frontend/app/style.css';import'../../../packages/frontend/design-system/aura-approved.css';import'../../../packages/frontend/features/materials/feishu-materials.css';window.calls=[];window.careerFeishuBitablePreview={selectBitablePreview:async input=>{window.calls.push('select');return{kind:'selection',table:{ref:input.tableRef,name:'TEST Table'},view:{ref:input.viewRef,name:'TEST View'}}},previewBitableRecords:async input=>{window.calls.push(input);return ${JSON.stringify(mode)}==='denied'?{kind:'failure',reason:'permission_required'}:{kind:'records',columns:[{name:'任务名称',type:'text'},{name:'目标图片数量',type:'number'},{name:'附件',type:'attachment'},{name:'商品',type:'link'}],items:${JSON.stringify(mode)}==='zero'?[]:Array.from({length:5},(_,i)=>({ref:crypto.randomUUID(),cells:[{kind:'text',value:'TEST task '+i},{kind:'number',value:3},{kind:'summary',category:'attachment',count:2,present:true},{kind:'summary',category:'linked_record',count:1,present:true}]})),hasMore:true}}};createRoot(document.getElementById('root')).render(<BitableRecordPreview table={{ref:'11111111-1111-4111-8111-111111111111',name:'TEST Table'}} view={{ref:'22222222-2222-4222-8222-222222222222',name:'TEST View'}} onAttempt={()=>{}}/>);`);
 const server=await createServer({configFile:false,root,cacheDir:path.resolve('out/f3b-validation/vite-cache'),server:{watch:null,host:'127.0.0.1',port:0,fs:{allow:[process.cwd()]}}});await server.listen();const a=server.httpServer!.address();if(!a||typeof a==='string')throw Error();const browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage({viewport:{width:600,height:820}});page.setDefaultTimeout(3000);await page.goto('http://127.0.0.1:'+a.port);return{page,close:async()=>{await browser.close();await server.close();await rm(root,{recursive:true,force:true});}};
}
test('explicit preview shows five compact rows at 600px; selection does not fetch or import, complex fields are counts',async()=>{
 const{page,close}=await fixture();try{await page.getByRole('button',{name:'预览最多 5 条记录',exact:true}).waitFor();expect(await page.evaluate(()=>(window as any).calls)).toEqual([]);await page.getByRole('button',{name:'预览最多 5 条记录',exact:true}).click();await page.getByText('TEST task 0',{exact:true}).waitFor();expect(await page.getByRole('button',{name:/选择记录：TEST task/}).count()).toBe(5);await page.getByRole('button',{name:'选择记录：TEST task 0',exact:true}).click();expect(await page.getByRole('status').innerText()).toContain('已选择记录：TEST task 0');expect(await page.evaluate(()=>(window as any).calls.length)).toBe(2);expect(await page.locator('body').innerText()).toContain('附件：2 个');expect(await page.locator('body').innerText()).toContain('关联记录：1 项');expect(await page.locator('body').innerText()).toContain('还有其他记录，本轮不继续读取');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}finally{await close();}
},20000);
test('zero records and permission failure do not offer retry or import',async()=>{
 for(const mode of ['zero','denied']){const{page,close}=await fixture(mode);try{await page.getByRole('button',{name:'预览最多 5 条记录',exact:true}).click();await page.getByText(mode==='zero'?'这个视图暂时没有记录。':'预览记录需要只读权限，请先检查飞书授权。',{exact:true}).waitFor();expect(await page.getByRole('button',{name:'预览最多 5 条记录',exact:true}).isEnabled()).toBe(false);expect(await page.evaluate(()=>(window as any).calls.length)).toBe(2);}finally{await close();}}
},20000);
