import {test,expect} from 'vitest';
import {chromium} from 'playwright';
import {createServer} from 'vite';
import {mkdir,writeFile,rm} from 'node:fs/promises';
import path from 'node:path';

async function fixture(mode='normal'){
 const root=path.resolve('out/delivery-validation/document-UI-TEST');await mkdir(root,{recursive:true});
 await writeFile(path.join(root,'index.html'),'<div id="root"></div><script type="module" src="/main.tsx"></script>');
 await writeFile(path.join(root,'main.tsx'),`import React from'react';import{createRoot}from'react-dom/client';import{FeishuDocumentPreview}from'../../../packages/frontend/features/materials/FeishuDocumentPreview';import'../../../packages/frontend/app/style.css';import'../../../packages/frontend/features/materials/feishu-materials.css';const id='11111111-1111-4111-8111-111111111111',materialId='22222222-2222-4222-8222-222222222222';const source={owner:'materials',objectId:materialId,revision:1,locator:'whole',scope:'personal'};const p={kind:'document_preview',ref:id,title:'TEST 项目复盘',text:'# TEST 项目复盘\\n测试正文\\n[附件未下载]',blocks:[{kind:'heading',text:'# TEST 项目复盘',depth:0},{kind:'paragraph',text:'测试正文',depth:0},{kind:'attachment',text:'[附件未下载]',depth:0}],source:{documentIdentity:'a'.repeat(64),type:'docx',accountIdentity:null,sourceUrl:null,displayTitle:'TEST 项目复盘'},provenance:{revision:7,retrievedAt:'2026-10-09T01:00:00.000Z',contentDigest:'b'.repeat(64),previewDigest:'c'.repeat(64),complete:true},limitations:['attachments_not_downloaded','connection_identity_unavailable'],readBoundary:{maxPages:5,pageSize:100,maxBlocks:500,maxTextBytes:184320,metadataRequests:2,requestsMade:3}};let saved=false;window.calls=[];window.careerMaterials={request:async input=>{window.calls.push(input.operation);if(input.operation==='receipt')return {kind:'receipt',receipt:{status:'committed',commandId:input.commandId,materialId,source}};return{kind:'raw',raw:{id:materialId,name:p.title,size:56,scope:'personal',lifecycle:'evidence-original',revision:1,source,recordedAt:'2026-10-09',text:p.text,digest:p.provenance.contentDigest}};}};const bridge=window.careerFeishuDocument={preview:async()=>{window.calls.push('preview');return p;},cancel:async()=>{window.calls.push('cancel');return{kind:'cancelled'};},importPreview:async input=>{window.calls.push('import');saved=true;if('${mode}'==='unknown')throw Error('lost response');return{kind:'raw_saved',materialId,commandId:input.commandId,source,previewDigest:p.provenance.previewDigest,duplicate:false};}};createRoot(document.getElementById('root')).render(<FeishuDocumentPreview selected={{ref:id,title:p.title,type:'docx',updatedAt:null,url:null}} bridge={bridge} onUse={()=>window.calls.push('use')}/>);`);
 const server=await createServer({configFile:false,root,cacheDir:path.join(root,'.vite'),server:{watch:null,host:'127.0.0.1',port:0,fs:{allow:[process.cwd()]}}});await server.listen();const a=server.httpServer!.address();if(!a||typeof a==='string')throw Error();const browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage({viewport:{width:600,height:820}});page.setDefaultTimeout(5000);await page.goto('http://127.0.0.1:'+a.port,{waitUntil:'domcontentloaded'});return{page,close:async()=>{await browser.close();await server.close();await rm(root,{recursive:true,force:true});}};
}
test('explicit document reading and confirmation preserve the preview and formal readback without exposing identity or automatic task use',async()=>{
 const{page,close}=await fixture();try{await page.getByRole('button',{name:'查看内容',exact:true}).waitFor();expect(await page.evaluate(()=>(window as any).calls)).toEqual([]);await page.getByRole('button',{name:'查看内容',exact:true}).click();await page.getByRole('heading',{name:'TEST 项目复盘',exact:true}).first().waitFor();expect(await page.locator('[aria-label="资料内容"]').innerText()).toContain('测试正文');expect(await page.locator('body').innerText()).not.toMatch(/11111111|cccccccc|token|provenance/);await page.getByRole('button',{name:'保存资料',exact:true}).click();await page.getByText('已保存，内容与预览一致。',{exact:true}).waitFor();expect(await page.evaluate(()=>(window as any).calls)).toEqual(['preview','import','read']);await page.getByRole('button',{name:'用这份资料整理知识',exact:true}).click();expect(await page.evaluate(()=>(window as any).calls)).toEqual(['preview','import','read','use']);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}finally{await close();}
},60000);
test('a lost save response is checked against its original receipt, without a second import or network read',async()=>{
 const{page,close}=await fixture('unknown');try{await page.getByRole('button',{name:'查看内容',exact:true}).click();await page.getByRole('button',{name:'保存资料',exact:true}).click();await page.getByRole('button',{name:'检查是否已保存',exact:true}).click();await page.getByText('已保存，内容与预览一致。',{exact:true}).waitFor();expect(await page.evaluate(()=>(window as any).calls)).toEqual(['preview','import','receipt','read']);}finally{await close();}
},60000);
test('permanent eviction closes saved document text and its task action while unrelated eviction preserves it',async()=>{
 const {page,close}=await fixture();try{
  await page.getByRole('button',{name:'查看内容',exact:true}).click();await page.getByRole('button',{name:'保存资料',exact:true}).click();await page.getByRole('button',{name:'用这份资料整理知识',exact:true}).waitFor();
  await page.evaluate(()=>window.dispatchEvent(new CustomEvent('career-feishu-cache-evicted',{detail:{kind:'feishu_cache_evicted',materialIds:['33333333-3333-4333-8333-333333333333'],previewRefs:[],recordRefs:[],all:false}})));
  expect(await page.locator('[aria-label="资料内容"]').innerText()).toContain('测试正文');
  await page.evaluate(()=>window.dispatchEvent(new CustomEvent('career-feishu-cache-evicted',{detail:{kind:'feishu_cache_evicted',materialIds:['22222222-2222-4222-8222-222222222222'],previewRefs:[],recordRefs:[],all:false}})));
  await expect.poll(()=>page.locator('[aria-label="资料内容"]').count()).toBe(0);expect(await page.getByRole('button',{name:'用这份资料整理知识',exact:true}).count()).toBe(0);expect(await page.locator('body').innerText()).not.toContain('测试正文');
 }finally{await close();}
},60000);
test('eviction cancels an in-flight document read and prevents its late text from returning',async()=>{
 const {page,close}=await fixture();try{
  await page.getByRole('button',{name:'查看内容',exact:true}).waitFor();await page.evaluate(()=>{const w=window as any,bridge=w.careerFeishuDocument,original=bridge.preview;bridge.preview=(input:any)=>new Promise(resolve=>{w.finishRead=async()=>resolve(await original(input));});});
  await page.getByRole('button',{name:'查看内容',exact:true}).click();await expect.poll(()=>page.evaluate(()=>typeof (window as any).finishRead)).toBe('function');
  await page.evaluate(()=>window.dispatchEvent(new CustomEvent('career-feishu-cache-evicted',{detail:{kind:'feishu_cache_evicted',materialIds:[],previewRefs:['11111111-1111-4111-8111-111111111111'],recordRefs:[],all:false}})));
  await page.evaluate(()=>(window as any).finishRead());await page.getByText('相关内容已永久清除，旧预览已关闭。',{exact:true}).waitFor();expect(await page.locator('[aria-label="资料内容"]').count()).toBe(0);expect(await page.evaluate(()=>(window as any).calls)).toContain('cancel');
 }finally{await close();}
},60000);
