import{test,expect,vi}from'vitest';import{mkdtemp,rm}from'node:fs/promises';import path from'node:path';import{tmpdir}from'node:os';import{createFeishuConnector,type FeishuAuthState}from'../packages/backend/platform/connectors/feishu/connector';
async function fixture(){const root=await mkdtemp(path.join(tmpdir(),'career-feishu-continuity-'));let auth:FeishuAuthState='ready';const reader=vi.fn(async()=>{auth='ready';return{displayName:'TEST nickname',avatarUrl:'https://s3-imfile.feishucdn.com/avatar.png'};});const avatar=vi.fn(async()=>({bytes:Buffer.from('TEST IMAGE'),mime:'image/png'}));const connector=createFeishuConnector({profileRoot:root,authState:async()=>auth,readCurrentUser:reader,downloadAvatar:avatar});return{root,reader,avatar,connector,setAuth:(s:FeishuAuthState)=>{auth=s;},close:()=>rm(root,{recursive:true,force:true})};}
test('short-lived credential expiry refreshes the existing user session instead of falsely disconnecting',async()=>{const f=await fixture();try{await f.connector.connect();f.setAuth('needs_refresh');expect(await f.connector.getConnectionStatus()).toEqual({provider:'feishu',state:'connected'});expect(await f.connector.getCurrentIdentity()).toMatchObject({displayName:'TEST nickname'});expect(f.reader).toHaveBeenCalledTimes(2);}finally{await f.close();}});
test('click connect can resolve refreshable credentials even when Career has no prior display cache',async()=>{const f=await fixture();try{f.setAuth('needs_refresh');expect(await f.connector.connect()).toEqual({provider:'feishu',state:'connected'});expect(f.reader).toHaveBeenCalledTimes(1);}finally{await f.close();}});
test('simultaneous status, identity and avatar checks share one refresh without redundant identity or avatar requests',async()=>{const f=await fixture();try{await f.connector.connect();f.setAuth('needs_refresh');await Promise.all([f.connector.getConnectionStatus(),f.connector.getCurrentIdentity(),f.connector.readAvatar()]);expect(f.reader).toHaveBeenCalledTimes(2);expect(f.avatar).toHaveBeenCalledTimes(2);}finally{await f.close();}});
test('actual refresh rejection asks for authorization, suppresses automatic loops, and never claims connected',async()=>{const f=await fixture();try{await f.connector.connect();f.setAuth('needs_refresh');f.reader.mockRejectedValueOnce(Error('feishu_authorization_required'));expect(await f.connector.getConnectionStatus()).toMatchObject({state:'reauthorization_required'});expect(await f.connector.getConnectionStatus()).toMatchObject({state:'reauthorization_required'});expect(f.reader).toHaveBeenCalledTimes(2);}finally{await f.close();}});

test('failed renewal does not poll the identity API later; only an explicit connect starts a new attempt',async()=>{const f=await fixture();try{await f.connector.connect();f.setAuth('needs_refresh');f.reader.mockRejectedValueOnce(Error('feishu_authorization_required'));await f.connector.getConnectionStatus();const clock=vi.spyOn(Date,'now').mockReturnValue(Date.now()+120_000);try{expect(await f.connector.getConnectionStatus()).toMatchObject({state:'reauthorization_required'});expect(f.reader).toHaveBeenCalledTimes(2);}finally{clock.mockRestore();}expect(await f.connector.connect()).toMatchObject({state:'connected'});expect(f.reader).toHaveBeenCalledTimes(3);}finally{await f.close();}});
test('backend account identity exposes only the cached trustworthy hash without auth or Contact requests',async()=>{
 const root=await mkdtemp(path.join(tmpdir(),'career-feishu-account-TEST-')),auth=vi.fn(async()=> 'ready' as const),contact=vi.fn(async()=>({displayName:'TEST nickname'}));let hash='a'.repeat(64);const connector=createFeishuConnector({profileRoot:root,authState:auth,readCurrentUser:contact,downloadAvatar:async()=>{throw Error('TEST IMAGE NOT REQUESTED');},currentAccountIdentity:()=>hash});
 try{await connector.connect();expect(await connector.getConnectionStatus()).toMatchObject({state:'connected'});const calls=auth.mock.calls.length,contacts=contact.mock.calls.length;expect(await connector.getAccountIdentity()).toBe(hash);expect(auth).toHaveBeenCalledTimes(calls);expect(contact).toHaveBeenCalledTimes(contacts);const visible=await connector.getCurrentIdentity();expect(visible).toEqual({connected:true,provider:'feishu',displayName:'TEST nickname',avatar:null});expect(JSON.stringify(visible)).not.toContain(hash);hash='not-a-trustworthy-identity';expect(await connector.getAccountIdentity()).toBeNull();
 }finally{await rm(root,{recursive:true,force:true});}
});
