import {test,expect} from 'vitest';
import {createBitableRawPreview} from '../packages/backend/platform/connectors/feishu/raw-preview';
const ids={bitable:'11111111-1111-4111-8111-111111111111',table:'22222222-2222-4222-8222-222222222222',view:'33333333-3333-4333-8333-333333333333',record:'44444444-4444-4444-8444-444444444444'};
function snapshot(){return {source:{bitableRef:ids.bitable,bitableTitle:'TEST Base',tableRef:ids.table,tableName:'TEST Table',viewRef:ids.view,viewName:'TEST View'},recordRef:ids.record,retrievedAt:'2026-10-07T01:00:00.000Z',selectedAt:'2026-10-07T01:01:00.000Z',upstreamUpdatedAt:null,columns:[{name:'TEST Text',type:'text'},{name:'TEST Number',type:'number'},{name:'TEST Choice',type:'select'},{name:'TEST Date',type:'date'},{name:'TEST False',type:'checkbox'},{name:'TEST Empty',type:'text'},{name:'TEST Attachment',type:'attachment'},{name:'TEST Linked',type:'link'},{name:'TEST User',type:'user'},{name:'TEST Formula',type:'formula'}],cells:[{kind:'text',value:'TEST content'},{kind:'number',value:0},{kind:'choice',value:['TEST A','TEST B']},{kind:'date',value:'2026-10-07T09:00:00+08:00'},{kind:'boolean',value:false},{kind:'empty'},{kind:'summary',category:'attachment',count:2,present:true},{kind:'summary',category:'linked_record',count:1,present:true},{kind:'summary',category:'user',present:true},{kind:'summary',category:'formula',present:true}]};}
test('selected cached snapshot converts actual values in source order with stable digest and opaque provenance',()=>{
 const service=createBitableRawPreview({readSelectedRecord:snapshot});const result=service.prepare({recordRef:ids.record});expect(result.kind).toBe('raw_preview');if(result.kind!=='raw_preview')throw Error();
 expect(result.text).toBe('来源：飞书多维表格\n多维表格：TEST Base\n表：TEST Table\n视图：TEST View\n\nTEST Text：TEST content\nTEST Number：0\nTEST Choice：TEST A、TEST B\nTEST Date：2026-10-07T01:00:00.000Z\nTEST False：否\nTEST Attachment：附件：2 个（未读取）\nTEST Linked：关联记录：1 项（未展开）');
 expect(result.provenance).toMatchObject({source_type:'feishu_bitable_record',bitable_ref:ids.bitable,table_ref:ids.table,view_ref:ids.view,record_ref:ids.record,retrieved_at:'2026-10-07T01:00:00.000Z',selected_at:'2026-10-07T01:01:00.000Z',upstream_updated_at:null});expect(result.includedFields).toHaveLength(7);expect(result.excludedComplexFields).toHaveLength(4);expect(result.provenance.preview_digest).toMatch(/^[a-f0-9]{64}$/);expect(service.prepare({recordRef:ids.record})).toEqual(result);expect(result.text).not.toMatch(/11111111|22222222|record_ref|token|TEST Empty|TEST User|TEST Formula/);
});
test('cancel creates nothing; next step is only ready-for-confirmation, never a saved Raw',()=>{
 const service=createBitableRawPreview({readSelectedRecord:snapshot});const result=service.prepare({recordRef:ids.record});if(result.kind!=='raw_preview')throw Error();expect(service.ready({previewRef:result.ref,previewDigest:'0'.repeat(64)})).toMatchObject({kind:'failure',reason:'preview_unavailable'});expect(service.ready({previewRef:result.ref,previewDigest:result.provenance.preview_digest})).toMatchObject({kind:'ready_for_import_confirmation'});expect(service.cancel({previewRef:result.ref})).toEqual({kind:'cancelled'});expect(service.ready({previewRef:result.ref,previewDigest:result.provenance.preview_digest})).toMatchObject({kind:'failure'});const next=service.prepare({recordRef:ids.record});if(next.kind!=='raw_preview')throw Error();expect(next.provenance.preview_digest).toBe(result.provenance.preview_digest);
});
test('missing, malformed, foreign or changed selected snapshot fails closed with no body input or re-fetch seam',()=>{
 let selected:any=snapshot();const service=createBitableRawPreview({readSelectedRecord:()=>selected});expect(service.prepare({recordRef:crypto.randomUUID()})).toMatchObject({reason:'selected_snapshot_unavailable'});expect(service.prepare({recordRef:ids.record,text:'OVERRIDE'})).toMatchObject({reason:'invalid_request'});const result=service.prepare({recordRef:ids.record});if(result.kind!=='raw_preview')throw Error();selected=undefined;expect(service.prepare({recordRef:ids.record})).toMatchObject({reason:'selected_snapshot_unavailable'});expect(service.ready({previewRef:result.ref,previewDigest:result.provenance.preview_digest})).toMatchObject({reason:'selected_snapshot_unavailable'});selected={...snapshot(),cells:[]};expect(service.prepare({recordRef:ids.record})).toMatchObject({reason:'selected_snapshot_unavailable'});
});
test('system fields stay outside Raw text; already-read formula display is allowed but missing complex display is never guessed',()=>{
 const s=snapshot();s.columns=[{name:'app_token',type:'text'},{name:'TEST Formula',type:'formula'},{name:'TEST Lookup',type:'lookup'}];s.cells=[{kind:'text',value:'PRIVATE_SYSTEM_ID'},{kind:'text',value:'TEST computed display'},{kind:'summary',category:'lookup',present:true}] as any;const result=createBitableRawPreview({readSelectedRecord:()=>s}).prepare({recordRef:ids.record});if(result.kind!=='raw_preview')throw Error();expect(result.text).toContain('TEST Formula：TEST computed display');expect(result.text).not.toMatch(/PRIVATE_SYSTEM_ID|app_token|TEST Lookup/);expect(result.ignoredFields).toEqual(expect.arrayContaining([{name:'app_token',reason:'technical_field'},{name:'TEST Lookup',reason:'display_not_available'}]));
});

test('disposing invalidates both a prepared preview and a trusted restored preview',()=>{
 const service=createBitableRawPreview({readSelectedRecord:snapshot}),preview=service.prepare({recordRef:ids.record});if(preview.kind!=='raw_preview')throw Error();
 const restored=createBitableRawPreview({readSelectedRecord:()=>undefined},preview);
 service.dispose();restored.dispose();
 const request={previewRef:preview.ref,previewDigest:preview.provenance.preview_digest};expect(service.resolveForImport(request)).toBeUndefined();expect(restored.resolveForImport(request)).toBeUndefined();expect(restored.restoredMetadata()).toBeUndefined();expect(restored.prepare({recordRef:ids.record})).toMatchObject({reason:'selected_snapshot_unavailable'});
});
