import {test,expect,vi} from 'vitest';
import {randomUUID} from 'node:crypto';
import {createFeishuDocumentReader} from '../packages/backend/platform/connectors/feishu/document';
import {createBitableRawPreview} from '../packages/backend/platform/connectors/feishu/raw-preview';
import {createBitableRecordPreview} from '../packages/backend/platform/connectors/feishu/record-preview';
const connected=async()=>({provider:'feishu' as const,state:'connected' as const});
const tableRef=randomUUID(),viewRef=randomUUID(),source={bitableRef:randomUUID(),bitableTitle:'TEST Base',tableRef,tableName:'TEST Table',viewRef,viewName:'TEST View'};
const snapshot=(recordRef=randomUUID())=>({source,recordRef,columns:[{name:'TEST Title',type:'text'}],cells:[{kind:'text' as const,value:'TEST body '+recordRef}],retrievedAt:'2026-10-09T00:00:00.000Z',selectedAt:'2026-10-09T00:00:01.000Z',upstreamUpdatedAt:null});
function docFixture(){const a=randomUUID(),b=randomUUID();const read=vi.fn(async(token:string)=>({items:[{id:token,parentId:'',type:1,children:['TESTbody'],text:''},{id:'TESTbody',parentId:token,type:2,children:[],text:'TEST body '+token}],hasMore:false}));const reader=createFeishuDocumentReader({getConnectionStatus:connected,resolveDocument:ref=>({token:ref===a?'TESTDocumentSourceA12345':'TESTDocumentSourceB12345',type:'docx',url:null,title:'TEST'}),readMetadata:async token=>({documentToken:token,title:'TEST',revision:1}),readBlocks:read});return{a,b,read,reader};}
test('purging a saved cloud source closes cached/replayed bodies and preserves an unrelated preview',async()=>{
 const f=docFixture(),requestId=randomUUID(),a=await f.reader.preview({requestId,selectedRef:f.a}),b=await f.reader.preview({requestId:randomUUID(),selectedRef:f.b});if(a.kind!=='document_preview'||b.kind!=='document_preview')throw Error();const materialId=randomUUID();expect(f.reader.bindSavedMaterial(a.ref,materialId)).toBe(true);const count=f.read.mock.calls.length;expect(f.reader.purgeSavedMaterials([materialId])).toMatchObject({trackedMaterialIds:[materialId],invalidatedPreviewRefs:[a.ref]});expect(f.reader.bindSavedMaterial(a.ref,materialId)).toBe(false);expect(f.reader.cachedPreview({selectedRef:f.a})).toMatchObject({reason:'preview_unavailable'});expect(f.reader.resolvePreview({previewRef:a.ref,previewDigest:a.provenance.previewDigest})).toBeUndefined();expect(await f.reader.preview({requestId,selectedRef:f.a})).toMatchObject({kind:'failure'});expect(f.reader.cachedPreview({selectedRef:f.b})).toEqual(b);expect(f.read).toHaveBeenCalledTimes(count);expect(f.reader.dispose()).toMatchObject({invalidatedPreviewRefs:[b.ref]});
});
test('purge rejects a same-source late cloud response without automatic reread; a new explicit request can read later',async()=>{
 const f=docFixture(),a=await f.reader.preview({requestId:randomUUID(),selectedRef:f.a});if(a.kind!=='document_preview')throw Error();const materialId=randomUUID();f.reader.bindSavedMaterial(a.ref,materialId);let reached!:()=>void,release!:()=>void;const started=new Promise<void>(r=>reached=r),wait=new Promise<void>(r=>release=r);f.read.mockImplementationOnce(async token=>{reached();await wait;return {items:[{id:token,parentId:'',type:1,children:[],text:''}],hasMore:false};});const requestId=randomUUID(),late=f.reader.preview({requestId,selectedRef:f.a});await started;f.reader.purgeSavedMaterials([materialId]);release();expect(await late).toMatchObject({kind:'failure'});expect(f.reader.cachedPreview({selectedRef:f.a})).toMatchObject({reason:'preview_unavailable'});const count=f.read.mock.calls.length;expect(await f.reader.preview({requestId,selectedRef:f.a})).toMatchObject({kind:'failure'});expect(f.read).toHaveBeenCalledTimes(count);expect((await f.reader.preview({requestId:randomUUID(),selectedRef:f.a})).kind).toBe('document_preview');
});
test('purged Bitable source cannot reappear through current or restored snapshot; unrelated prepared row stays readable',()=>{
 const a=snapshot(),b=snapshot();let selected:any=a;const converter=createBitableRawPreview({readSelectedRecord:()=>selected}),preview=converter.prepare({recordRef:a.recordRef});if(preview.kind!=='raw_preview')throw Error();const materialId=randomUUID();converter.bindSavedMaterial(preview.ref,materialId);const restored=createBitableRawPreview({readSelectedRecord:()=>undefined},preview);restored.bindSavedMaterial(preview.ref,materialId);selected=b;const other=converter.prepare({recordRef:b.recordRef});if(other.kind!=='raw_preview')throw Error();const change=converter.purgeSavedMaterials([materialId]);expect(converter.bindSavedMaterial(preview.ref,materialId)).toBe(false);expect(change).toMatchObject({trackedMaterialIds:[materialId],recordRefs:[a.recordRef],sources:[{tableRef,viewRef}]});expect(converter.resolveForImport({previewRef:other.ref,previewDigest:other.provenance.preview_digest})).toEqual(other);selected=a;expect(converter.prepare({recordRef:a.recordRef})).toMatchObject({kind:'failure'});expect(restored.purgeSavedMaterials([materialId]).invalidatedPreviewRefs).toEqual([preview.ref]);expect(restored.restoredMetadata()).toBeUndefined();expect(restored.resolveForImport({previewRef:preview.ref,previewDigest:preview.provenance.preview_digest})).toBeUndefined();expect(restored.prepare({recordRef:a.recordRef})).toMatchObject({kind:'failure'});
});
const target={appToken:'TESTBitableIdentity12345',tableId:'tblTEST',viewId:'vewTEST',tableName:source.tableName,viewName:source.viewName,bitableRef:source.bitableRef,bitableTitle:source.bitableTitle};
test('record snapshot revocation removes only the purged row from selected and replayed record caches',async()=>{
 const read=vi.fn(async()=>({columns:[{name:'TEST Title',type:'text'}],rows:[[{kind:'text' as const,value:'TEST purge A'}],[{kind:'text' as const,value:'TEST preserve B'}]],hasMore:false})),records=createBitableRecordPreview({getConnectionStatus:connected,resolveView:()=>target,readRecords:read});await records.select({tableRef,viewRef});const page=await records.preview({tableRef,viewRef,limit:5});if(page.kind!=='records')throw Error();const a=page.items[0]!.ref,b=page.items[1]!.ref;records.selectRecord({recordRef:a});records.invalidateRecordSnapshots([a],[{tableRef,viewRef}]);expect(records.readSelectedRecord()).toBeUndefined();expect(records.selectRecord({recordRef:a})).toMatchObject({kind:'failure'});expect(await records.preview({tableRef,viewRef,limit:5})).toMatchObject({kind:'records',items:[{ref:b,cells:[{kind:'text',value:'TEST preserve B'}]}]});expect(records.selectRecord({recordRef:b})).toMatchObject({kind:'selected_record'});expect(read).toHaveBeenCalledTimes(1);
});
test('purging a restored selected row fences a late read of its view and closes restored body paths',async()=>{
 const a=snapshot();let reached!:()=>void,release!:()=>void;const started=new Promise<void>(r=>reached=r),wait=new Promise<void>(r=>release=r);const read=vi.fn(async()=>{reached();await wait;return{columns:a.columns,rows:[a.cells],hasMore:false};}),records=createBitableRecordPreview({getConnectionStatus:connected,resolveView:()=>target,readRecords:read},a);await records.select({tableRef,viewRef});const late=records.preview({tableRef,viewRef,limit:5});await started;records.invalidateRecordSnapshots([a.recordRef],[{tableRef,viewRef}]);release();expect(await late).toMatchObject({kind:'failure'});expect(records.readSelectedRecord()).toBeUndefined();expect(records.getSelectedRecordMetadata()).toMatchObject({kind:'failure'});expect(records.selectRecord({recordRef:a.recordRef})).toMatchObject({kind:'failure'});expect(read).toHaveBeenCalledTimes(1);
});
