import {test,expect,vi} from 'vitest';
import {mkdtemp,rm,mkdir,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createFeishuConnector,type FeishuAuthState} from '../packages/backend/platform/connectors/feishu/connector';
test('account switch blocks the cached old identity and avatar without Contact until explicit connect',async()=>{
 const root=await mkdtemp(path.join(tmpdir(),'career-account-binding-TEST-'));let account:string|null='a'.repeat(64),auth:FeishuAuthState='ready';const contact=vi.fn(async()=>({displayName:account==='a'.repeat(64)?'TEST account A':'TEST account B',avatarUrl:'https://s3-imfile.feishucdn.com/TEST.png'}));const ports={profileRoot:root,authState:async()=>auth,currentAccountIdentity:()=>account,readCurrentUser:contact,downloadAvatar:async()=>({bytes:Buffer.from('TEST IMAGE'),mime:'image/png'})};let connector=createFeishuConnector(ports);
 try{expect((await connector.connect()).state).toBe('connected');expect(await connector.getCurrentIdentity()).toMatchObject({displayName:'TEST account A'});connector=createFeishuConnector(ports);expect((await connector.getConnectionStatus()).state).toBe('connected');expect(await connector.getAccountIdentity()).toBe('a'.repeat(64));account='b'.repeat(64);expect((await connector.getConnectionStatus()).state).toBe('not_connected');await expect(connector.getCurrentIdentity()).rejects.toThrow('not_connected');expect(await connector.readAvatar()).toBeUndefined();expect(await connector.getAccountIdentity()).toBeNull();auth='needs_refresh';expect((await connector.getConnectionStatus()).state).toBe('not_connected');expect(contact).toHaveBeenCalledTimes(1);auth='ready';expect((await connector.connect()).state).toBe('connected');expect(await connector.getCurrentIdentity()).toMatchObject({displayName:'TEST account B'});expect(await connector.getAccountIdentity()).toBe('b'.repeat(64));expect(contact).toHaveBeenCalledTimes(2);account=null;expect((await connector.getConnectionStatus()).state).toBe('connection_invalid');expect(await connector.getAccountIdentity()).toBeNull();expect(contact).toHaveBeenCalledTimes(2);
 }finally{await rm(root,{recursive:true,force:true});}
});
test('legacy unbound cache keeps compatibility but cannot acquire a current-account binding without explicit connect',async()=>{
 const root=await mkdtemp(path.join(tmpdir(),'career-account-legacy-TEST-')),directory=path.join(root,'connectors/feishu');await mkdir(directory,{recursive:true,mode:0o700});await writeFile(path.join(directory,'identity.json'),JSON.stringify({provider:'feishu',status:'connected',displayNameSource:'nickname',displayName:'TEST legacy display',avatarFile:null,avatarMime:null,avatarSha256:null,updatedAt:'2026-10-09T00:00:00.000Z'}),{mode:0o600});const contact=vi.fn(async()=>({displayName:'TEST explicit current display'}));const connector=createFeishuConnector({profileRoot:root,authState:async()=> 'ready',currentAccountIdentity:()=> 'b'.repeat(64),readCurrentUser:contact,downloadAvatar:async()=>{throw Error('TEST NO AVATAR');}});
 try{expect(await connector.getCurrentIdentity()).toMatchObject({displayName:'TEST legacy display'});expect(await connector.getAccountIdentity()).toBeNull();expect(contact).not.toHaveBeenCalled();await connector.connect();expect(await connector.getCurrentIdentity()).toMatchObject({displayName:'TEST explicit current display'});expect(await connector.getAccountIdentity()).toBe('b'.repeat(64));expect(contact).toHaveBeenCalledTimes(1);}finally{await rm(root,{recursive:true,force:true});}
});
