import {it,expect} from 'vitest';
import {chromium} from 'playwright';
import {createServer} from 'vite';
import {mkdir,writeFile,rm} from 'node:fs/promises';
import path from 'node:path';
async function fixture(){
 const root=path.resolve('dist/a6-ui');await mkdir(root,{recursive:true});
 await writeFile(path.join(root,'index.html'),'<div id="root"></div><script type="module" src="/main.tsx"></script>');
 await writeFile(path.join(root,'main.tsx'),`import React from 'react';import{createRoot}from'react-dom/client';import{HashRouter}from'react-router';import{CareerShell}from'../../packages/frontend/shell';import{G4Support}from'../../packages/frontend/app/g4-support';import'../../packages/frontend/app/style.css';import'../../packages/frontend/design-system/aura-approved.css';import'../../packages/frontend/app/aura-adapter.css';window.career={request:async(m,i)=>m==='application'?{kind:'data_targets',targets:[]}:m==='profile'?{status:'profile',profile:{revision:1,name:'PRIVATE PROFILE NAME',contact:'',links:[]}}:{kind:'product_tasks',tasks:[]}};const secret={request:async()=>({kind:'status',status:{configured:false,enabled:false}})};window.careerSecrets=secret;window.careerTavilySecrets=secret;createRoot(document.getElementById('root')).render(<HashRouter><CareerShell pages={{wiki:<textarea aria-label="Task draft" defaultValue="UNSAVED TEST input"/>,opportunity:<p>O</p>,project:<p>P</p>,employment:<p>E</p>}} auxiliary={<G4Support workspaceInstance="TEST" onRestore={async()=>{}} onApplied={()=>{}} onPurge={()=>{}} preferences={{pinned:null,order:['wiki','opportunity','project','employment'],busy:false,status:'',pin:async()=>{},reorder:async()=>{}}} helpOpen={false} onHelp={()=>{}} onHelpClose={()=>{}} onFinishTutorial={()=>{}} onOpenOpportunity={()=>{}}/>}/></HashRouter>);`);
 const server=await createServer({configFile:false,root,cacheDir:path.join(root,'.vite'),server:{host:'127.0.0.1',port:0,fs:{allow:[process.cwd()]}}});await server.listen();const address=server.httpServer!.address();if(!address||typeof address==='string')throw Error();const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:600,height:820}});page.setDefaultTimeout(5000);await page.goto('http://127.0.0.1:'+address.port);return{page,close:async()=>{await browser.close();await server.close();await rm(root,{recursive:true,force:true});}};
}
it('approved A6 brand is ornamental and the four compact entries retain visible names',async()=>{
 const {page,close}=await fixture();try{const nav=page.getByRole('navigation',{name:'一级导航'});await nav.getByRole('img',{name:'Career 豹头与字标',exact:true}).waitFor();expect(await nav.getByRole('link').count()).toBe(4);for(const name of ['Wiki','机会','项目','任职'])expect(await nav.getByRole('link',{name,exact:true}).isVisible()).toBe(true);const before=page.url();await nav.getByRole('img',{name:'Career 豹头与字标',exact:true}).click();expect(page.url()).toBe(before);expect(await nav.innerText()).not.toMatch(/首页|Home|PRIVATE PROFILE NAME/);expect(await nav.locator('img,image,canvas,video').count()).toBe(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(600);}finally{await close();}
},25000);
it('avatar contains the four auxiliary actions, never borrows Profile identity, and keeps a draft through Settings',async()=>{
 const {page,close}=await fixture();try{const draft=page.getByRole('textbox',{name:'Task draft'});await draft.fill('INDEPENDENT TEST draft');const trigger=page.getByRole('button',{name:'连接与辅助菜单'});await trigger.click();const menu=page.getByRole('menu',{name:'连接与辅助菜单'});expect(await menu.innerText()).not.toContain('PRIVATE PROFILE NAME');for(const name of ['更新日志','设置','帮助','反馈'])expect(await menu.getByRole('menuitem',{name,exact:true}).isVisible()).toBe(true);await menu.getByRole('menuitem',{name:'设置',exact:true}).click();const settings=page.getByRole('dialog',{name:'设置',exact:true});await settings.getByText('Career 版本',{exact:true}).waitFor();expect(await settings.innerText()).toContain('0.0.0');await settings.getByRole('button',{name:'返回原任务'}).click();expect(await draft.inputValue()).toBe('INDEPENDENT TEST draft');await trigger.click();await menu.getByRole('menuitem',{name:'更新日志'}).click();await page.getByRole('dialog',{name:'更新日志',exact:true}).waitFor();expect(await page.getByRole('dialog',{name:'更新日志',exact:true}).innerText()).toContain('品牌与机会管线');}finally{await close();}
},25000);
it('brand settles after one 0.75x playback, replays on hover and respects reduced motion',async()=>{
 const {page,close}=await fixture();try{const brand=page.getByRole('img',{name:'Career 豹头与字标',exact:true}),head=brand.locator('.career-brand-head'),letters=brand.locator('.career-brand-letter');await expect.poll(()=>head.evaluate(el=>getComputedStyle(el).transform),{timeout:6000}).toBe('none');await brand.hover();await expect.poll(()=>head.evaluate(el=>getComputedStyle(el).transform)).not.toBe('none');expect(await letters.last().evaluate(el=>Number(getComputedStyle(el).opacity))).toBeLessThan(1);await expect.poll(()=>head.evaluate(el=>getComputedStyle(el).transform),{timeout:5000}).toBe('none');expect(await letters.last().evaluate(el=>getComputedStyle(el).opacity)).toBe('1');await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('textbox',{name:'Task draft'}).hover();await brand.hover();expect(await head.evaluate(el=>getComputedStyle(el).transform)).toBe('none');expect(await brand.locator('.career-brand-eye').evaluate(el=>getComputedStyle(el).opacity)).toBe('0');expect(await brand.locator('.career-brand-trace').evaluate(el=>getComputedStyle(el).opacity)).toBe('0');expect(await brand.locator('.career-brand-name').evaluate(el=>getComputedStyle(el).letterSpacing)).toBe('1px');}finally{await close();}
},25000);
it('a click-open avatar menu stays open after pointer departure and Escape closes it',async()=>{
 const {page,close}=await fixture();try{await page.getByRole('button',{name:'连接与辅助菜单'}).click();await page.getByRole('textbox',{name:'Task draft'}).hover();await page.waitForTimeout(240);const menu=page.getByRole('menu',{name:'连接与辅助菜单'});expect(await menu.isVisible()).toBe(true);await menu.getByRole('menuitem',{name:'设置',exact:true}).press('Escape');expect(await menu.isVisible()).toBe(false);}finally{await close();}
},20000);
