import {it,expect} from 'vitest';import{chromium}from'playwright';import{createServer}from'vite';import{mkdir,writeFile,rm}from'node:fs/promises';import path from'node:path';
it('normal Settings keeps auxiliary groups without a second identity editing entrance',async()=>{
 const root=path.resolve('dist/frontend-c-settings');await mkdir(root,{recursive:true});await writeFile(path.join(root,'index.html'),'<div id="root"></div><script type="module" src="/main.tsx"></script>');
 await writeFile(path.join(root,'main.tsx'),`import React from'react';import{createRoot}from'react-dom/client';import{HashRouter}from'react-router';import{G4Support}from'../../packages/frontend/app/g4-support.tsx';window.career={request:async(module,input)=>module==='application'?{kind:'data_targets',targets:[]}:module==='profile'?{status:'profile',profile:{revision:1,name:'TEST identity',contact:'',links:[]}}:{kind:'product_tasks',tasks:[]}};const secrets={request:async()=>({kind:'status',status:{configured:false,enabled:false}})};window.careerSecrets=secrets;window.careerTavilySecrets=secrets;createRoot(document.getElementById('root')!).render(<HashRouter><G4Support workspaceInstance="TEST" onRestore={async()=>{}} onApplied={()=>{}} onPurge={()=>{}} preferences={{pinned:null,order:['wiki','opportunity','project','employment'],busy:false,status:'',pin:async()=>{},reorder:async()=>{}}} helpOpen={false} onHelp={()=>{}} onHelpClose={()=>{}} onFinishTutorial={()=>{}} onOpenOpportunity={()=>{}}/></HashRouter>);`);
 const server=await createServer({configFile:false,root,cacheDir:path.join(root,'.vite'),server:{host:'127.0.0.1',port:0,fs:{allow:[process.cwd()]}}}),browser=await chromium.launch({channel:'chrome',headless:true});
 try{await server.listen();const address=server.httpServer!.address();if(!address||typeof address==='string')throw Error();const page=await browser.newPage({viewport:{width:600,height:820}});page.setDefaultTimeout(6000);await page.goto('http://127.0.0.1:'+address.port);await page.getByRole('button',{name:'连接与辅助菜单'}).click();await page.getByRole('menuitem',{name:'设置',exact:true}).click();const panel=page.getByRole('dialog',{name:'设置',exact:true});
 for(const name of ['AI / Search 连接','备份与恢复','导航设置','高级资料维护'])expect(await panel.getByRole('button',{name,exact:true}).isVisible()).toBe(true);
 expect(await panel.getByRole('button',{name:'我的基础资料',exact:true}).count()).toBe(0);expect(await panel.getByLabel('姓名',{exact:true}).count()).toBe(0);expect(await panel.innerText()).not.toMatch(/fixture|J-07|TEST DATA|fake|UUID|generation|OpenAI official website/);
 await panel.getByRole('button',{name:'备份与恢复',exact:true}).click();await panel.getByRole('button',{name:'AI / Search 连接',exact:true}).click();await panel.getByRole('button',{name:'返回原任务'}).click();await page.getByRole('button',{name:'连接与辅助菜单'}).click();await page.getByRole('menuitem',{name:'设置',exact:true}).click();expect(await panel.getByRole('button',{name:'AI / Search 连接',exact:true}).getAttribute('aria-current')).toBe('page');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 }finally{await browser.close();await server.close();await rm(root,{recursive:true,force:true});}
},30000);

it('Profile refresh never replaces independently typed input with a late earlier read',async()=>{
 const root=path.resolve('dist/frontend-c-profile-race');await mkdir(root,{recursive:true});await writeFile(path.join(root,'index.html'),'<div id="root"></div><script type="module" src="/main.tsx"></script>');await writeFile(path.join(root,'main.tsx'),`import React from'react';import{createRoot}from'react-dom/client';import{ProfileSettings}from'../../packages/frontend/support/profile/index.tsx';let reads=0;window.career={request:async()=>{reads++;if(reads===1)throw Error('first read unavailable');if(reads===2)return new Promise(resolve=>{window.releaseProfile=()=>resolve({status:'profile',profile:{revision:1,name:'EARLIER TEST',contact:'',links:[]}})});return {status:'profile',profile:{revision:2,name:'LATEST TEST',contact:'',links:[]}};}};createRoot(document.getElementById('root')!).render(<ProfileSettings onSaved={()=>{}}/>);`);
 const server=await createServer({configFile:false,root,cacheDir:path.join(root,'.vite'),server:{host:'127.0.0.1',port:0,fs:{allow:[process.cwd()]}}}),browser=await chromium.launch({channel:'chrome',headless:true});try{await server.listen();const address=server.httpServer!.address();if(!address||typeof address==='string')throw Error();const page=await browser.newPage();page.setDefaultTimeout(6000);await page.goto('http://127.0.0.1:'+address.port);await page.getByRole('status').filter({hasText:'暂时无法读取'}).waitFor();const refresh=page.getByRole('button',{name:'刷新',exact:true});await refresh.click();
 if(await refresh.isEnabled()){await refresh.click();await page.getByLabel('姓名',{exact:true}).fill('INDEPENDENT TEST draft');await page.evaluate(()=>{(window as any).releaseProfile();});await page.waitForTimeout(100);expect(await page.getByLabel('姓名',{exact:true}).inputValue()).toBe('INDEPENDENT TEST draft');}else{await page.evaluate(()=>{(window as any).releaseProfile();});await page.getByLabel('姓名',{exact:true}).fill('INDEPENDENT TEST draft');expect(await page.getByLabel('姓名',{exact:true}).inputValue()).toBe('INDEPENDENT TEST draft');}
 }finally{await browser.close();await server.close();await rm(root,{recursive:true,force:true});}
},30000);
