import {it,expect} from 'vitest';
import {chromium} from 'playwright';
import {createServer} from 'vite';
import {mkdir,writeFile,rm} from 'node:fs/promises';
import path from 'node:path';
async function fixture(feishuConnected=false){
 const root=path.resolve('dist/a6-ui');await mkdir(root,{recursive:true});
 await writeFile(path.join(root,'index.html'),'<div id="root"></div><script type="module" src="/main.tsx"></script>');
 await writeFile(path.join(root,'main.tsx'),`import React from 'react';import{createRoot}from'react-dom/client';import{HashRouter}from'react-router';import{CareerShell}from'../../packages/frontend/shell';import{G4Support}from'../../packages/frontend/app/g4-support';import'../../packages/frontend/app/style.css';import'../../packages/frontend/design-system/aura-approved.css';import'../../packages/frontend/app/aura-adapter.css';window.career={request:async(m,i)=>m==='application'?{kind:'data_targets',targets:[]}:m==='profile'?{status:'profile',profile:{revision:1,name:'PRIVATE PROFILE NAME',contact:'',links:[]}}:{kind:'product_tasks',tasks:[]}};const secret={request:async()=>({kind:'status',status:{configured:false,enabled:false}})};window.careerSecrets=secret;window.careerTavilySecrets=secret;window.careerFeishu={getConnectionStatus:async()=>({provider:'feishu',state:${feishuConnected?'"connected"':'"not_connected"'}}),getCurrentIdentity:async()=>({connected:true,provider:'feishu',displayName:'飞书测试用户',avatar:'feishu/avatar'}),getAvatar:async()=>${feishuConnected?'"data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs="':'undefined'},connect:async()=>({provider:'feishu',state:'connected'})};function Review(){const[order,setOrder]=React.useState(['wiki','opportunity','project','employment']);return <HashRouter><CareerShell order={order} onReorder={async value=>setOrder(value)} pages={{wiki:<textarea aria-label="Task draft" defaultValue="UNSAVED TEST input"/>,opportunity:<p>O</p>,project:<p>P</p>,employment:<p>E</p>}} auxiliary={<G4Support workspaceInstance="TEST" onRestore={async()=>{}} onApplied={()=>{}} onPurge={()=>{}} preferences={{pinned:null,order,busy:false,status:'',pin:async()=>{},reorder:async value=>setOrder(value)}} helpOpen={false} onHelp={()=>{}} onHelpClose={()=>{}} onFinishTutorial={()=>{}} onOpenOpportunity={()=>{}}/>}/></HashRouter>};createRoot(document.getElementById('root')).render(<Review/>);`);
 const server=await createServer({configFile:false,root,cacheDir:path.resolve('out/implementation/a6/vite-ui-cache'),server:{watch:null,host:'127.0.0.1',port:0,fs:{allow:[process.cwd()]}}});await server.listen();const address=server.httpServer!.address();if(!address||typeof address==='string')throw Error();const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:600,height:820}});page.setDefaultTimeout(5000);await page.goto('http://127.0.0.1:'+address.port);return{page,close:async()=>{await browser.close();await server.close();await rm(root,{recursive:true,force:true});}};
}
it('unconnected sidebar keeps a neutral identity and routes its menu to Feishu settings at 600px',async()=>{
 const {page,close}=await fixture(false);try{await page.setViewportSize({width:600,height:820});const trigger=page.getByRole('button',{name:'连接与辅助菜单'});await trigger.click();const menu=page.getByRole('menu',{name:'连接与辅助菜单'});expect(await menu.getByRole('menuitem').first().innerText()).toContain('连接飞书');expect(await page.locator('.career-connection-name').count()).toBe(0);expect(await menu.innerText()).not.toContain('PRIVATE PROFILE NAME');await menu.getByRole('menuitem',{name:/连接飞书/}).click();const settings=page.getByRole('dialog',{name:'设置',exact:true});await settings.getByRole('button',{name:'AI / Search 连接',exact:true}).click();expect(await settings.getByText('未连接',{exact:true}).isVisible()).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}finally{await close();}
},25000);
it('connected sidebar shows only the Feishu name and actual cached avatar, never the Career Profile name',async()=>{
 const {page,close}=await fixture(true);try{await page.setViewportSize({width:600,height:820});expect(await page.locator('.career-connection-name').textContent()).toBe('飞书测试用户');expect(await page.locator('.career-avatar img[alt="飞书头像"]').isVisible()).toBe(true);const trigger=page.getByRole('button',{name:'连接与辅助菜单'});await trigger.click();const menu=page.getByRole('menu',{name:'连接与辅助菜单'});expect(await menu.innerText()).toContain('飞书测试用户');expect(await menu.innerText()).not.toContain('PRIVATE PROFILE NAME');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}finally{await close();}
},25000);
it('connected Feishu settings can refresh an outdated display name from the authorized user identity',async()=>{
 const {page,close}=await fixture(true);try{await page.evaluate(()=>{window.careerFeishu!.connect=async()=>({provider:'feishu',state:'connected'});window.careerFeishu!.getCurrentIdentity=async()=>({connected:true,provider:'feishu',displayName:'测试昵称',avatar:'feishu/avatar'});});const trigger=page.getByRole('button',{name:'连接与辅助菜单'});await trigger.click();await page.getByRole('menuitem',{name:'设置',exact:true}).click();const settings=page.getByRole('dialog',{name:'设置',exact:true});await settings.getByRole('button',{name:'AI / Search 连接',exact:true}).click();await settings.getByRole('button',{name:'刷新飞书身份',exact:true}).click();expect(await settings.getByText('测试昵称 · 头像可用',{exact:true}).isVisible()).toBe(true);expect(await settings.getByText('飞书身份信息已刷新。',{exact:true}).isVisible()).toBe(true);expect(await settings.innerText()).not.toContain('PRIVATE PROFILE NAME');}finally{await close();}
},25000);
it('approved A6 brand is ornamental and the four compact entries retain visible names',async()=>{
 const {page,close}=await fixture();try{const nav=page.getByRole('navigation',{name:'一级导航'});await nav.getByRole('img',{name:'Career 豹头与字标',exact:true}).waitFor();expect(await nav.getByRole('link').count()).toBe(4);for(const name of ['Wiki','机会','项目','任职'])expect(await nav.getByRole('link',{name,exact:true}).isVisible()).toBe(true);const before=page.url();await nav.getByRole('img',{name:'Career 豹头与字标',exact:true}).click();expect(page.url()).toBe(before);expect(await nav.innerText()).not.toMatch(/首页|Home|PRIVATE PROFILE NAME/);expect(await nav.locator('img,image,canvas,video').count()).toBe(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(600);}finally{await close();}
},25000);
it('avatar contains the four auxiliary actions, never borrows Profile identity, and keeps a draft through Settings',async()=>{
 const {page,close}=await fixture();try{const draft=page.getByRole('textbox',{name:'Task draft'});await draft.fill('INDEPENDENT TEST draft');const trigger=page.getByRole('button',{name:'连接与辅助菜单'});await trigger.click();const menu=page.getByRole('menu',{name:'连接与辅助菜单'});expect(await menu.innerText()).not.toContain('PRIVATE PROFILE NAME');for(const name of ['更新日志','设置','帮助','反馈'])expect(await menu.getByRole('menuitem',{name,exact:true}).isVisible()).toBe(true);await menu.getByRole('menuitem',{name:'设置',exact:true}).click();const settings=page.getByRole('dialog',{name:'设置',exact:true});await settings.getByText('Career 版本',{exact:true}).waitFor();expect(await settings.innerText()).toContain('0.0.0');await settings.getByRole('button',{name:'返回原任务'}).click();expect(await draft.inputValue()).toBe('INDEPENDENT TEST draft');await trigger.click();await menu.getByRole('menuitem',{name:'更新日志'}).click();await page.getByRole('dialog',{name:'更新日志',exact:true}).waitFor();expect(await page.getByRole('dialog',{name:'更新日志',exact:true}).innerText()).toContain('品牌与机会管线');}finally{await close();}
},25000);
it('brand settles after one 0.75x playback, replays on hover and respects reduced motion',async()=>{
 const {page,close}=await fixture();try{const brand=page.getByRole('img',{name:'Career 豹头与字标',exact:true}),head=brand.locator('.career-brand-head'),letters=brand.locator('.career-brand-letter');await expect.poll(()=>head.evaluate(el=>getComputedStyle(el).transform),{timeout:6000}).toBe('none');await brand.hover();await expect.poll(()=>head.evaluate(el=>getComputedStyle(el).transform)).not.toBe('none');expect(await letters.last().evaluate(el=>Number(getComputedStyle(el).opacity))).toBeLessThan(1);await expect.poll(()=>head.evaluate(el=>getComputedStyle(el).transform),{timeout:5000}).toBe('none');expect(await letters.last().evaluate(el=>getComputedStyle(el).opacity)).toBe('1');await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('textbox',{name:'Task draft'}).hover();await brand.hover();expect(await head.evaluate(el=>getComputedStyle(el).transform)).toBe('none');expect(await brand.locator('.career-brand-eye').evaluate(el=>getComputedStyle(el).opacity)).toBe('0');expect(await brand.locator('.career-brand-trace').evaluate(el=>getComputedStyle(el).opacity)).toBe('0');expect(await brand.locator('.career-brand-name').evaluate(el=>getComputedStyle(el).letterSpacing)).toBe('1px');}finally{await close();}
},25000);
it('a click-open avatar menu stays open after pointer departure and Escape closes it',async()=>{
 const {page,close}=await fixture();try{await page.getByRole('button',{name:'连接与辅助菜单'}).click();await page.getByRole('textbox',{name:'Task draft'}).hover();await page.waitForTimeout(240);const menu=page.getByRole('menu',{name:'连接与辅助菜单'});expect(await menu.isVisible()).toBe(true);await menu.getByRole('menuitem',{name:'设置',exact:true}).press('Escape');expect(await menu.isVisible()).toBe(false);}finally{await close();}
},20000);

it('Feedback uses the approved narrow side sheet, shows only page context, and retains its unsent draft',async()=>{
 const {page,close}=await fixture();try{page.on('dialog',d=>void d.accept());await page.getByRole('button',{name:'连接与辅助菜单'}).click();await page.getByRole('menuitem',{name:'反馈',exact:true}).click();const panel=page.getByRole('dialog',{name:'Career 反馈',exact:true});await panel.waitFor();expect(await panel.evaluate(el=>el.classList.contains('sheet')&&el.classList.contains('small-sheet'))).toBe(true);expect(await panel.locator('.context-line').innerText()).not.toMatch(/UUID|commandId|PRIVATE PROFILE NAME/);await panel.getByLabel('反馈内容').fill('TEST local feedback');await panel.getByRole('button',{name:'返回原任务（保留反馈草稿）',exact:true}).click();await page.getByRole('button',{name:'连接与辅助菜单'}).click();await page.getByRole('menuitem',{name:'反馈',exact:true}).click();expect(await page.getByLabel('反馈内容').inputValue()).toBe('TEST local feedback');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}finally{await close();}
},20000);

it('Sidebar can be dragged and keyboard reordered without opening another module',async()=>{
 const {page,close}=await fixture();try{const nav=page.getByRole('navigation',{name:'一级导航'}),link=nav.getByRole('link',{name:'项目',exact:true});await link.waitFor();await link.press('Alt+ArrowUp');await expect.poll(()=>nav.getByRole('link').allTextContents()).toEqual(['Wiki','项目','机会','任职']);await link.evaluate(el=>Promise.all(el.getAnimations().map(animation=>animation.finished)));const before=page.url(),a=await link.boundingBox(),b=await nav.getByRole('link',{name:'Wiki',exact:true}).boundingBox();await page.mouse.move(a!.x+24,a!.y+24);await page.mouse.down();await page.mouse.move(b!.x+24,b!.y+5,{steps:8});await page.mouse.up();await expect.poll(()=>nav.getByRole('link').allTextContents()).toEqual(['项目','Wiki','机会','任职']);expect(page.url()).toBe(before);}finally{await close();}
},20000);
