import {it,expect} from 'vitest';
import {chromium} from 'playwright';
import {createServer} from 'vite';
import Database from 'better-sqlite3';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import path from 'node:path';import {tmpdir} from 'node:os';import {randomUUID} from 'node:crypto';
import {createOpportunityDomain} from '../packages/backend/domains/opportunity/public';
import {opportunityMigration} from '../packages/backend/domains/opportunity/migration';
import {commandMigration} from '../packages/backend/platform/commands/receipts';
import {createSubmissionDomain} from '../packages/backend/domains/opportunity/submission/public';
import {submissionMigration} from '../packages/backend/domains/opportunity/submission/migration';
import {createCommunicationDomain} from '../packages/backend/domains/opportunity/communication/public';
import {communicationMigration} from '../packages/backend/domains/opportunity/communication/migration';
it('real functional UI retains scoped drafts, verifies lost-response receipts, records one first send and later correctable communication',async()=>{
 const root=await mkdtemp(path.join(tmpdir(),'career-g4-s-ui-'));const ui=path.resolve('dist/g4-s-ui-test');await mkdir(ui,{recursive:true});const db=new Database(path.join(root,'career.sqlite'));db.exec(commandMigration);db.exec(opportunityMigration);db.exec(submissionMigration);db.exec(communicationMigration);const core=createOpportunityDomain(db);const company=core.handle({operation:'company.create',commandId:randomUUID(),name:'G4 UI Company'});if(company.kind!=='company')throw Error();const ids=['A','B'].map(role=>{const result=core.handle({operation:'create',commandId:randomUUID(),companyId:company.company.id,role});if(result.kind!=='opportunity')throw Error();return result.opportunity.id;});
 const ports={core:core.capabilities,resolveFrozenResume:()=>undefined,resolveActualArtifact:()=>undefined,retainExisting(){}};const submission=createSubmissionDomain(db,ports);const communication=createCommunicationDomain(db,{...ports,hasFirstSubmission:submission.hasFirstSubmission});
 await writeFile(path.join(ui,'index.html'),'<html><body><div id="app"></div><script type="module" src="/main.tsx"></script></body></html>');
 await writeFile(path.join(ui,'main.tsx'),`import React,{useState}from'react';import{createRoot}from'react-dom/client';import{SubmissionPage}from'../../packages/frontend/features/opportunity/submission/index.tsx';import{CommunicationPage}from'../../packages/frontend/features/opportunity/communication/index.tsx';function Test(){const[id,setId]=useState('${ids[0]}');const send=async input=>{const response=await fetch('/owner',{method:'POST',body:JSON.stringify(input)});if(!response.ok)throw Error('lost');return response.json();};return <><button onClick={()=>setId('${ids[0]}')}>Open A</button><button onClick={()=>setId('${ids[1]}')}>Open B</button><SubmissionPage opportunityId={id} workspaceInstance="fixture" request={send}/><CommunicationPage opportunityId={id} workspaceInstance="fixture" request={send}/></>;}createRoot(document.getElementById('app')!).render(<Test/>);`);
 let drop=true;const server=await createServer({configFile:false,root:ui,cacheDir:path.join(ui,'.vite'),plugins:[{name:'real-g4-s-owner',configureServer(server){server.middlewares.use('/owner',(req,res)=>{let body='';req.on('data',chunk=>body+=String(chunk));req.on('end',()=>{try{const input=JSON.parse(body);const result=(input.operation.startsWith('submission.')?submission:communication).handle(input);if(drop&&input.operation==='submission.record-first'){drop=false;res.statusCode=503;res.end();return;}res.setHeader('content-type','application/json');res.end(JSON.stringify(result));}catch{res.statusCode=500;res.end();}});});}}],server:{host:'127.0.0.1',port:0,fs:{allow:[process.cwd()]}}});let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
 try{await server.listen();const address=server.httpServer!.address();if(!address||typeof address==='string')throw Error();browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage();page.setDefaultTimeout(8000);await page.goto(`http://127.0.0.1:${address.port}`);const first=page.getByRole('region',{name:'首次投递',exact:true});const comm=page.getByRole('region',{name:'沟通记录',exact:true});await first.getByRole('status').filter({hasText:'已读取'}).waitFor();await comm.getByRole('status').filter({hasText:'列表已读取'}).waitFor();
 await comm.getByLabel('沟通正文',{exact:true}).fill('A independent unsaved draft');await page.getByRole('button',{name:'Open B',exact:true}).click();await comm.getByRole('status').filter({hasText:'列表已读取'}).waitFor();await comm.getByLabel('沟通正文',{exact:true}).fill('B draft');await page.getByRole('button',{name:'Open A',exact:true}).click();expect(await comm.getByLabel('沟通正文',{exact:true}).inputValue()).toBe('A independent unsaved draft');expect(await page.evaluate(()=>!window.dispatchEvent(new Event('beforeunload',{cancelable:true})))).toBe(true);
 await first.getByLabel('本次实际简历状态',{exact:true}).selectOption('content_unknown');await first.getByLabel('历史缺失说明',{exact:true}).fill('Historical original unknown');await first.getByLabel('记录或纠错说明',{exact:true}).fill('Real first send');await first.getByRole('button',{name:'确认真实首次投递',exact:true}).click();await first.getByRole('status').filter({hasText:'结果待核对'}).waitFor();expect(await first.getByLabel('本次实际简历状态',{exact:true}).isDisabled()).toBe(true);await first.getByRole('button',{name:'核对原投递回执',exact:true}).click();await first.getByText('已登记首次投递；实际材料状态：content_unknown',{exact:true}).waitFor();
 await comm.getByLabel('沟通用途',{exact:true}).selectOption('resend');await comm.getByLabel('沟通正文',{exact:true}).fill('Later actual resend');await comm.getByLabel('本次实际简历状态',{exact:true}).selectOption('file_missing');await comm.getByLabel('历史缺失说明',{exact:true}).fill('Old original lost');await comm.getByLabel('当时已知的具体内容',{exact:true}).fill('Actual content A');await comm.getByLabel('记录或纠错说明',{exact:true}).fill('Actual resend');await comm.getByRole('button',{name:'确认再次发送材料',exact:true}).click();await comm.getByText('Later actual resend',{exact:true}).waitFor();expect(submission.hasFirstSubmission(ids[0])).toBe(true);const state=communication.handle({operation:'communication.list',opportunityId:ids[0]});expect(state).toMatchObject({kind:'list',items:[{purpose:'resend',sentMaterial:{kind:'file_missing',knownContent:'Actual content A'}}]});expect(submission.handle({operation:'submission.read',opportunityId:ids[0]})).toMatchObject({kind:'submission',submission:{resume:{kind:'content_unknown'}}});
 await comm.getByRole('button',{name:'更正此沟通正文',exact:true}).click();await comm.getByLabel('沟通正文',{exact:true}).fill('Corrected later send record');await comm.getByLabel('记录或纠错说明',{exact:true}).fill('Correct same record');if(state.kind!=='list')throw Error();communication.handle({operation:'communication.correct',commandId:randomUUID(),id:state.items[0].id,expectedRevision:state.items[0].revision,text:'Other current record',businessTime:{kind:'unknown'},reason:'Concurrent correction'});await comm.getByRole('button',{name:'明确更正沟通正文',exact:true}).click();await comm.getByRole('complementary',{name:'沟通冲突比较',exact:true}).waitFor();expect(await comm.getByLabel('沟通正文',{exact:true}).inputValue()).toBe('Corrected later send record');await comm.getByRole('button',{name:'采用沟通新基线并保留草稿',exact:true}).click();await comm.getByRole('button',{name:'明确更正沟通正文',exact:true}).click();await comm.getByText('Corrected later send record',{exact:true}).waitFor();expect(communication.handle({operation:'communication.list',opportunityId:ids[0]})).toMatchObject({kind:'list',items:[{source:{revision:3},text:'Corrected later send record'}]});await page.getByRole('button',{name:'Open B',exact:true}).click();expect(await comm.getByLabel('沟通正文',{exact:true}).inputValue()).toBe('B draft');
 }finally{await browser?.close();await server.close();db.close();await rm(root,{recursive:true,force:true});await rm(ui,{recursive:true,force:true});}
},40000);
