import {it,expect} from 'vitest';
import {chromium} from 'playwright';
import {createServer} from 'vite';
import Database from 'better-sqlite3';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import path from 'node:path';
import {tmpdir} from 'node:os';
import {createFeedback,feedbackMigration} from '../packages/backend/application/feedback/public';
import {commandMigration} from '../packages/backend/platform/commands/receipts';
it('UX-11: actual overlay preserves underlying dirty form, traps focus, restores it and recovers the same unknown receipt once',async()=>{
 const root=await mkdtemp(path.join(tmpdir(),'career-feedback-ui-')),ui=path.resolve('dist/g5-feedback-ui-test');await mkdir(ui,{recursive:true});const db=new Database(':memory:');db.exec(commandMigration+feedbackMigration);const owner=createFeedback(db);let lose=true;
 await writeFile(path.join(ui,'index.html'),'<html><body><div id="root"></div><script type="module" src="/main.tsx"></script></body></html>');
 await writeFile(path.join(ui,'main.tsx'),`import React from 'react';import{createRoot}from'react-dom/client';import{MemoryRouter}from'react-router';import{FeedbackOverlay}from'../../packages/frontend/support/feedback/index.tsx';window.career={request:async(_module,input)=>{const r=await fetch('/owner',{method:'POST',body:JSON.stringify(input)});if(!r.ok)throw Error('lost');return r.json();}};createRoot(document.getElementById('root')).render(<MemoryRouter initialEntries={['/project']}><label>当前业务草稿<input aria-label="当前业务草稿"/></label><FeedbackOverlay onPurged={()=>{}}/></MemoryRouter>);`);
 const server=await createServer({configFile:false,root:ui,cacheDir:path.join(ui,'.vite'),plugins:[{name:'feedback-owner-test',configureServer(server){server.middlewares.use('/owner',(req,res)=>{let body='';req.on('data',chunk=>body+=chunk);req.on('end',()=>{const input=JSON.parse(body),result=owner.handle(input);if(lose&&input.operation==='feedback.create'){lose=false;res.statusCode=503;res.end();return;}res.setHeader('content-type','application/json');res.end(JSON.stringify(result));});});}}],server:{host:'127.0.0.1',port:0,fs:{allow:[process.cwd()]}}});let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
 try{await server.listen();const address=server.httpServer!.address();if(!address||typeof address==='string')throw Error('port');browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage();await page.goto('http://127.0.0.1:'+address.port);const draft=page.getByLabel('当前业务草稿');await draft.fill('尚未保存的业务输入');await draft.focus();await page.getByRole('button',{name:'反馈',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Career 反馈'});await dialog.waitFor();expect(await draft.inputValue()).toBe('尚未保存的业务输入');expect(await page.locator('#root').evaluate(el=>(el as HTMLElement).inert)).toBe(true);
 await page.getByLabel('反馈内容').fill('只记录这条反馈');await page.getByRole('button',{name:'保存反馈并返回原任务'}).click();await page.getByRole('status').filter({hasText:'保存结果未知'}).waitFor();const records=owner.handle({operation:'feedback.list'});expect(records).toMatchObject({kind:'feedback_list',items:[{entries:[{text:'只记录这条反馈'}],location:{path:'/project'}}]});
 await page.getByRole('button',{name:'核对原反馈回执'}).click();await expect.poll(()=>dialog.count()).toBe(0);expect(await draft.inputValue()).toBe('尚未保存的业务输入');expect(await draft.evaluate(el=>document.activeElement===el)).toBe(true);const final=owner.handle({operation:'feedback.list'});if(final.kind!=='feedback_list')throw Error('list');expect(final.items).toHaveLength(1);
 await page.getByRole('button',{name:'反馈',exact:true}).click();await dialog.waitFor();await page.getByRole('button',{name:'返回原任务（保留反馈草稿）'}).focus();await page.keyboard.press('Tab');expect(await page.getByRole('dialog').evaluate(el=>el.contains(document.activeElement))).toBe(true);await page.keyboard.press('Escape');await expect.poll(()=>dialog.count()).toBe(0);expect(await draft.inputValue()).toBe('尚未保存的业务输入');
 }finally{await browser?.close();await server.close();db.close();await rm(root,{recursive:true,force:true});await rm(ui,{recursive:true,force:true});}
},20000);
