import {beforeAll,it,expect} from 'vitest';import {build,createServer} from 'vite';import {chromium} from 'playwright';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';import path from 'node:path';import {tmpdir} from 'node:os';import {randomUUID} from 'node:crypto';
import {createRuntimeBackend} from '../packages/backend/bootstrap/runtime';
import {Result} from '../packages/contracts/ai/schema';
import {createAiController,type AiWriterControllerPort} from '../packages/backend/ai-runtime/controller';
const artifact=path.resolve('dist/test-support/g6-ai-control-writer.cjs');
beforeAll(async()=>{await build({configFile:false,logLevel:'silent',build:{emptyOutDir:false,outDir:'dist/test-support',target:'node24',lib:{entry:'packages/backend/bootstrap/writer.ts',formats:['cjs'],fileName:()=> 'g6-ai-control-writer.cjs'},rolldownOptions:{external:[/^node:/,'better-sqlite3']}}});},20000);
it('F2 control Contract distinguishes immediate closed admission from an uncommitted original command',()=>{
 expect(Result.safeParse({kind:'execution_blocked',taskId:randomUUID(),commandId:randomUUID(),mode:'stop',dispatchBlocked:true,persistencePending:true}).success).toBe(true);
});
it('F2 held writer stop synchronously closes admission and preserves the original command identity',async()=>{
 let release!:()=>void,received:unknown;const writer:AiWriterControllerPort={prepareDispatch:async()=>{throw Error('unused');},markProcessing:async()=>{},settle:async()=>{},markUnknown:async()=>{},failOperation:async()=>{},cancelBeforeHandoff:async()=>{},stop:(...args)=>{received=args;return new Promise(resolve=>{release=resolve;});}};
 const controller=createAiController(writer,{network:'none',recipient:{service:'deterministic-fake',endpoint:'local://career-wiki-fake',account:'local-no-credential',generation:'fake-v1',model:'wiki-organizer-v1'},send:async()=>({proposals:[]})}),commandId=randomUUID();
 const pending=(controller.stop as (taskId:string,mode:'stop',commandId:string)=>Promise<void>)('task','stop',commandId);expect(controller.isClosed('task')).toBe(true);expect(received).toEqual(['task','stop',commandId]);release();await pending;
});
for(const kind of ['wiki','product'] as const)it(`F2 ${kind} real UI keeps original stop identity through held persistence, receipt read failure and receipt_missing`,async()=>{
 const root=await mkdtemp(path.join(tmpdir(),'career-g6-ai-control-')),ui=path.resolve('dist/g6-ai-control-'+kind),runtime=await createRuntimeBackend(path.join(root,'workspaces/local'),artifact,root),human=await runtime.connectHuman();const call=(module:Parameters<typeof runtime.business>[1],input:unknown)=>runtime.business(human,module,input) as Promise<any>;
 const company=(await call('opportunity',{operation:'company.create',commandId:randomUUID(),name:'G6 control UI isolated'})).company,opportunity=(await call('opportunity',{operation:'create',commandId:randomUUID(),companyId:company.id,role:'Control fixture'})).opportunity,round=await call('interview',{operation:'interview.confirm',commandId:randomUUID(),opportunityId:opportunity.id,expectedOpportunityRevision:1,title:'Actual source',confirmationTime:{kind:'unknown'}});
 await call('interview',{operation:'interview.save-document',commandId:randomUUID(),id:round.id,expectedRevision:1,document:'transcript',text:'Actual controlled source text'});
 const source={owner:'interview',objectId:round.id,revision:1,locator:'transcript',scope:'opportunity',opportunityId:opportunity.id};let original:any,receipts:string[]=[],listsAfterStop=0,receiptAttempts=0,final=false;await mkdir(ui,{recursive:true});await writeFile(path.join(ui,'index.html'),'<html><body><div id="root"></div><script type="module" src="/main.tsx"></script></body></html>');
 await writeFile(path.join(ui,'main.tsx'),`import React from 'react';import{createRoot}from'react-dom/client';import{WikiAiPage}from'../../packages/frontend/support/ai/index.tsx';import{ProductTaskPage}from'../../packages/frontend/support/ai/product-task.tsx';window.career={request:async(module,input)=>{const r=await fetch('/owner',{method:'POST',body:JSON.stringify({module,input})});if(!r.ok)throw Error('receipt read blocked');return r.json();}};window.careerMaterials={request:async()=>({kind:'list',items:[]})};createRoot(document.getElementById('root')).render(${kind==='wiki'?`<WikiAiPage request={input=>window.career.request('ai',input)} sources={async()=>[{ref:${JSON.stringify(source)},name:'Controlled actual source'}]}/>`:`<ProductTaskPage target={{kind:'greeting',opportunityId:'${opportunity.id}',includeName:false}}/>`});`);
 const server=await createServer({configFile:false,root:ui,cacheDir:path.join(ui,'.vite'),plugins:[{name:'held-control-test',configureServer(server){server.middlewares.use('/owner',(req,res)=>{let body='';req.on('data',chunk=>body+=chunk);req.on('end',async()=>{try{const {module,input}=JSON.parse(body);res.setHeader('content-type','application/json');if(input.operation.endsWith('.stop')){original=input;res.end(JSON.stringify({kind:'execution_blocked',taskId:input.taskId,commandId:input.commandId,mode:input.mode,dispatchBlocked:true,persistencePending:true}));return;}if(input.operation.endsWith('.receipt')){receipts.push(input.commandId);receiptAttempts++;if(receiptAttempts===1){res.statusCode=503;res.end();return;}if(receiptAttempts===2){res.end(JSON.stringify({kind:'receipt_missing'}));return;}await call('ai',original);final=true;const persisted=await call('ai',{operation:kind==='wiki'?'ai.read':'product.read',taskId:original.taskId});res.end(JSON.stringify({kind:kind==='wiki'?'receipt':'product_receipt',receipt:persisted}));return;}if(original&&!final&&input.operation.endsWith('.list'))listsAfterStop++;res.end(JSON.stringify(await call(module,input)));}catch{res.statusCode=500;res.end();}});});}}],server:{host:'127.0.0.1',port:0,fs:{allow:[process.cwd()]}}});let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
 try{await server.listen();const address=server.httpServer!.address();if(!address||typeof address==='string')throw Error('port');browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage();await page.goto('http://127.0.0.1:'+address.port);const area=page.getByRole('region',{name:kind==='wiki'?'Wiki AI 整理':'产品任务辅助'});
 if(kind==='wiki')await area.getByLabel(/Controlled actual source/).check();const prepare=area.getByRole('button',{name:kind==='wiki'?'准备本地 Context / 最终发送预览':'准备外发预览'});await prepare.click();await area.getByRole('button',{name:kind==='wiki'?'停止后续执行':'停止后续请求',exact:true}).click();await expect.poll(()=>area.getByRole('status').textContent()).toContain('后续派发已阻止');const receipt=area.getByRole('button',{name:kind==='wiki'?'核对原命令回执':'检查结果'});await expect.poll(()=>receipt.isEnabled()).toBe(true);expect(await prepare.isDisabled()).toBe(true);
 await receipt.click();await expect.poll(()=>area.getByRole('status').textContent()).toMatch(/结果读取未知|先检查结果/);await expect.poll(()=>receipt.isEnabled()).toBe(true);await receipt.click();await expect.poll(()=>area.getByRole('status').textContent()).toMatch(/尚未找到|尚无回执|已经确认这次操作尚未完成/);await expect.poll(()=>receipt.isEnabled()).toBe(true);expect(await prepare.isDisabled()).toBe(true);expect(listsAfterStop).toBe(0);await receipt.click();await expect.poll(()=>prepare.isEnabled()).toBe(true);if(kind==='product')expect(await area.getByRole('status').innerText()).toBe('已停止');expect(receipts).toEqual([original.commandId,original.commandId,original.commandId]);expect((await call('ai',{operation:kind==='wiki'?'ai.read':'product.read',taskId:original.taskId})).task.state).toBe('stopped');
 }finally{await browser?.close();await server.close();await runtime.close();await rm(root,{recursive:true,force:true});await rm(ui,{recursive:true,force:true});}
},30000);
