import {beforeAll,it,expect} from 'vitest';
import {build,createServer} from 'vite';import {chromium} from 'playwright';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import {randomUUID} from 'node:crypto';
import {createRuntimeBackend} from '../packages/backend/bootstrap/runtime';
beforeAll(async()=>{await build({configFile:false,logLevel:'silent',build:{emptyOutDir:false,outDir:'dist/application',target:'node24',lib:{entry:'packages/backend/bootstrap/writer.ts',formats:['cjs'],fileName:()=> 'writer.cjs'},rolldownOptions:{external:[/^node:/,'better-sqlite3']}}});},20000);
async function fixture(){
 const root=await mkdtemp(path.join(tmpdir(),'career-g6-resume-ui-')),ui=path.resolve('dist/g6-resume-ui-'+randomUUID());await mkdir(ui,{recursive:true});
 const runtime=await createRuntimeBackend(path.join(root,'workspaces/local'),path.resolve('dist/application/writer.cjs'),root),human=await runtime.connectHuman(),call=(module:Parameters<typeof runtime.business>[1],input:unknown)=>runtime.business(human,module,input) as Promise<any>;
 const company=(await call('opportunity',{operation:'company.create',commandId:randomUUID(),name:'G6 isolated Resume'})).company,opportunity=(await call('opportunity',{operation:'create',commandId:randomUUID(),companyId:company.id,role:'G6 cross-window'})).opportunity,opened=await call('resume',{operation:'resume.open',commandId:randomUUID(),opportunityId:opportunity.id}),content=structuredClone(opened.document.content);
 content.sections[0].blocks[0].spans=[{text:'Selected immutable starting block.',marks:[]}];content.sections.at(-1).blocks[0].spans=[{text:'Unrelated original block.',marks:[]}];await call('resume',{operation:'resume.save',commandId:randomUUID(),resumeId:opened.document.id,expectedRevision:1,expectedProfileRevision:0,content});
 let hold=false,arrived=false,release:(()=>void)|undefined;const saveIntents:any[]=[];
 await writeFile(path.join(ui,'index.html'),'<div id="root"></div><script type="module" src="/main.tsx"></script>');
 await writeFile(path.join(ui,'main.tsx'),`import React from 'react';import{createRoot}from'react-dom/client';import{QueryClient,QueryClientProvider}from'@tanstack/react-query';import{ResumePage}from ${JSON.stringify(path.resolve('packages/frontend/features/resume/index.tsx'))};window.career={developmentDiagnostics:true,request:async(module,input)=>{const response=await fetch('/owner',{method:'POST',body:JSON.stringify({module,input})});if(!response.ok)throw Error('transport');return response.json();}};window.careerMaterials={request:async()=>({kind:'list',items:[]})};createRoot(document.getElementById('root')).render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><ResumePage opportunityId="${opportunity.id}" request={input=>window.career.request('resume',input)} profileRequest={input=>window.career.request('profile',input)}/></QueryClientProvider>);`);
 const server=await createServer({configFile:false,root:ui,cacheDir:path.join(ui,'.vite'),plugins:[{name:'g6-held-real-apply',configureServer(server){server.middlewares.use('/owner',(req,res)=>{let body='';req.on('data',chunk=>body+=chunk);req.on('end',async()=>{try{const {module,input}=JSON.parse(body);if(input.operation==='product.decide'&&hold){arrived=true;await new Promise<void>(resolve=>{release=resolve;});}if(input.operation==='resume.save')saveIntents.push(input);res.setHeader('content-type','application/json');res.end(JSON.stringify(await call(module,input)));}catch{res.statusCode=500;res.end();}});});}}],server:{host:'127.0.0.1',port:0,fs:{allow:[process.cwd()]}}});
 await server.listen();const address=server.httpServer!.address();if(!address||typeof address==='string')throw Error('port');const browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage();page.setDefaultTimeout(10000);await page.goto('http://127.0.0.1:'+address.port);const editor=page.getByRole('textbox',{name:'简历正文'});await editor.waitFor();
 async function proposals(){await page.getByText('更多工具',{exact:true}).click();await page.getByRole('button',{name:'简历优化提案',exact:true}).click();const selection=page.getByLabel('简历优化选择');await selection.getByLabel(/个人简介 · Selected/).check();const ai=selection.getByRole('region',{name:'产品任务辅助'});await ai.getByRole('button',{name:'准备外发预览'}).click();await ai.getByRole('button',{name:'授权这份最终请求'}).click();const proposal=ai.getByRole('article',{name:'产品待审提案'}).filter({has:page.getByRole('heading',{name:/^修改简历内容/})});await proposal.waitFor();return proposal;}
 return {root,runtime,page,editor,call,opened,content,saveIntents,proposals,hold:()=>{hold=true;},arrived:()=>arrived,release:()=>release?.(),close:async()=>{release?.();await browser.close();await server.close();await runtime.close();await rm(root,{recursive:true,force:true});await rm(ui,{recursive:true,force:true});}};
}
it.each(['remote-only','remote-and-local'] as const)('RV-P1-03 held Apply protects its block; %s unrelated input never overwrites another window',async(mode)=>{
 const f=await fixture();try{const proposal=await f.proposals();f.hold();await proposal.getByRole('button',{name:'接受本条并立即生效'}).click();await expect.poll(f.arrived).toBe(true);
  await f.editor.locator('p').filter({hasText:'Selected immutable starting block.'}).first().click();await f.page.keyboard.press('End');await f.page.keyboard.insertText('BLOCKED-SAME-BLOCK');expect(await f.editor.textContent()).not.toContain('BLOCKED-SAME-BLOCK');
  const formal=await f.call('resume',{operation:'resume.read',resumeId:f.opened.document.id}),remote=structuredClone(formal.document.content);remote.sections[1].blocks[0].spans=[{text:'OTHER-WINDOW-FORMAL-B',marks:[{type:'bold'}]}];expect((await f.call('resume',{operation:'resume.save',commandId:randomUUID(),resumeId:f.opened.document.id,expectedRevision:formal.document.revision,expectedProfileRevision:0,content:remote})).status).toBe('document');
  if(mode==='remote-and-local'){await f.editor.locator('p').last().click();await f.page.keyboard.type('LOCAL-WHILE-APPLY');expect(await f.editor.textContent()).toContain('LOCAL-WHILE-APPLY');}
  const savesAtHandoff=f.saveIntents.length;f.release();await expect.poll(()=>proposal.getByRole('heading').textContent()).toContain('已采纳');await expect.poll(()=>f.editor.textContent()).toContain('受控优化建议');
  if(mode==='remote-only'){await expect.poll(()=>f.editor.textContent()).toContain('OTHER-WINDOW-FORMAL-B');await expect.poll(()=>f.page.getByTestId('resume-save-state').textContent()).toBe('已保存');}
  else {await expect.poll(()=>f.page.getByTestId('resume-save-state').textContent()).toContain('保存冲突');expect(await f.editor.textContent()).toContain('LOCAL-WHILE-APPLY');await new Promise(resolve=>setTimeout(resolve,1000));expect(f.saveIntents.length).toBe(savesAtHandoff);}
  const current=await f.call('resume',{operation:'resume.read',resumeId:f.opened.document.id});expect(current.document.content.sections[1].blocks[0]).toEqual(remote.sections[1].blocks[0]);
 }finally{await f.close();}
},30000);
it('RV-P1-03 immediately adjacent human-before / AI / human-after have separate Undo groups and history cancel retains the session',async()=>{
 const f=await fixture();try{const proposal=await f.proposals();await f.editor.locator('p').last().click();await f.page.keyboard.press('End');await f.page.keyboard.type(' HUMAN-BEFORE');await expect.poll(()=>f.page.getByTestId('resume-save-state').textContent()).toBe('已保存');await proposal.getByRole('button',{name:'接受本条并立即生效'}).click();await expect.poll(()=>f.editor.textContent()).toContain('受控优化建议');
  await f.editor.locator('p').last().click();await f.page.keyboard.press('End');await f.page.keyboard.type(' HUMAN-AFTER');expect(await f.editor.textContent()).toContain('HUMAN-AFTER');
  await f.page.getByRole('button',{name:'版本历史',exact:true}).click();await f.page.getByRole('button',{name:'关闭历史',exact:true}).click();
  await f.page.getByRole('button',{name:'撤销',exact:true}).click();expect(await f.editor.textContent()).not.toContain('HUMAN-AFTER');expect(await f.editor.textContent()).toContain('受控优化建议');expect(await f.editor.textContent()).toContain('HUMAN-BEFORE');
  await f.page.getByRole('button',{name:'撤销',exact:true}).click();expect(await f.editor.textContent()).not.toContain('受控优化建议');expect(await f.editor.textContent()).toContain('HUMAN-BEFORE');
  await f.page.getByRole('button',{name:'撤销',exact:true}).click();expect(await f.editor.textContent()).not.toContain('HUMAN-BEFORE');await f.editor.locator('p').last().click();await f.page.keyboard.type(' CONTINUE-AFTER-HISTORY');await expect.poll(()=>f.page.getByTestId('resume-save-state').textContent()).toBe('已保存');expect(await f.editor.textContent()).toContain('CONTINUE-AFTER-HISTORY');expect(await proposal.getByRole('heading').textContent()).toContain('已采纳');
 }finally{await f.close();}
},30000);
