import {it,expect} from 'vitest';
import {chromium,type Page,type Browser} from 'playwright';
import {createServer} from 'vite';
import {mkdtemp,mkdir,writeFile,rm,readdir,readFile} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {randomBytes,createCipheriv} from 'node:crypto';
import Database from 'better-sqlite3';
import {createSecretVault} from '../apps/desktop/capabilities/secret-vault';
import {createBackupManager} from '../packages/backend/platform/backup/public';
async function harness(service:'provider'|'tavily'='provider'){
 const root=await mkdtemp(path.join(os.tmpdir(),'g6-secret-ui-')),ui=path.resolve('dist/g6-secret-ui-harness'),security=path.join(root,'security');await mkdir(ui,{recursive:true});
 const key=randomBytes(32),control={available:true,encryptFailure:false,transportFailure:false,pause:undefined as Promise<void>|undefined},vault=createSecretVault(security,{available:async()=>control.available,encrypt:async value=>{if(control.pause)await control.pause;if(control.encryptFailure)throw Error('FAKE_ENCRYPT_ERROR_MUST_BE_SANITIZED');const nonce=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key,nonce);return Buffer.concat([nonce,cipher.update(value,'utf8'),cipher.final(),cipher.getAuthTag()]);}});
 const audit:{operation:string;result:unknown}[]=[],consoleMessages:string[]=[];
 await writeFile(path.join(ui,'index.html'),'<div id="app"></div><script type="module" src="/main.tsx"></script>');
 await writeFile(path.join(ui,'main.tsx'),`import React,{useState}from'react';import{createRoot}from'react-dom/client';import{QueryClient,QueryClientProvider}from'@tanstack/react-query';import{SecretSettings}from'../../packages/frontend/support/ai/secret-settings.tsx';const query=new QueryClient();window.testQuery=query;window.genericCommands=[];window.connectionRequests=[];const bridge={request:async input=>(await fetch('/secret-only',{method:'POST',body:JSON.stringify(input)})).json()};const testProvider=${service==='tavily'?"'tavily'":"'deepseek'"};const testBody=testProvider==='tavily'?{query:'OpenAI official website',search_depth:'basic',max_results:1,include_answer:false,include_raw_content:false,include_images:false,include_usage:false}:{model:'deepseek-flash',thinking:{type:'disabled'},response_format:{type:'json_object'},stream:false,max_tokens:16,messages:[{role:'system',content:'This is a provider connectivity check only. Do not request or infer user data. Return JSON only: {"status":"ready"}.'},{role:'user',content:'Connectivity check. Return {"status":"ready"}.'}]};const connectionBridge={request:async input=>{window.connectionRequests.push(input);return input.operation==='preview'?{kind:'preview',preview:testProvider==='deepseek'?{provider:'deepseek',displayModel:'DeepSeek V4.1-Flash',model:'deepseek-flash',endpoint:'https://api.deepseek.com/chat/completions',method:'POST',body:testBody,thinking:'disabled',fallback:false,automaticRetry:false,followRedirects:false,businessDataSent:false}:{provider:'tavily',endpoint:'https://api.tavily.com/search',method:'POST',body:testBody,fallback:false,automaticRetry:false,followRedirects:false,businessDataSent:false}}:{kind:'result',provider:testProvider,status:'connected',requestCount:1,httpStatus:200,responseValid:true,...(testProvider==='tavily'?{resultCount:1}:{})}}};function App(){const[shown,setShown]=useState(true);return <QueryClientProvider client={query}>{shown?<SecretSettings bridge={bridge} connectionBridge={connectionBridge} service="${service}"/>:<p>已卸载凭据输入</p>}<button onClick={()=>{window.detachedInput=document.querySelector('input');setShown(false);}}>离开设置</button></QueryClientProvider>}createRoot(document.getElementById('app')!).render(<App/>);`);
 const server=await createServer({configFile:false,root:ui,cacheDir:path.join(ui,'.vite'),plugins:[{name:'secret-only-vault',configureServer(s){s.middlewares.use('/secret-only',(req,res)=>{let body='';req.on('data',chunk=>body+=String(chunk));req.on('end',()=>{const parsed=JSON.parse(body);body='';if(control.transportFailure){res.statusCode=503;res.end('controlled transport failure');return;}void vault.request(parsed).then(result=>{audit.push({operation:parsed.operation,result});res.setHeader('content-type','application/json');res.end(JSON.stringify(result));});});});}}],server:{host:'127.0.0.1',port:0,fs:{allow:[process.cwd()]}}});
 let browser:Browser|undefined,page:Page;
 try{await server.listen();const address=server.httpServer!.address();if(!address||typeof address==='string')throw Error('server');browser=await chromium.launch({channel:'chrome',headless:true});page=await browser.newPage();page.setDefaultTimeout(5000);page.on('console',message=>consoleMessages.push(message.text()));page.on('pageerror',error=>consoleMessages.push(error.message));await page.goto(`http://127.0.0.1:${address.port}`);await page.getByRole('status').filter({hasText:'未配置'}).waitFor();await page.getByRole('button',{name:'配置 Key',exact:true}).click();await page.getByText('更多操作',{exact:true}).click();}
 catch(error){key.fill(0);await browser?.close();await server.close();await rm(root,{recursive:true,force:true});await rm(ui,{recursive:true,force:true});throw error;}
 return {root,security,page:page!,control,vault,audit,consoleMessages,async close(){key.fill(0);await browser?.close();await server.close();await rm(root,{recursive:true,force:true});await rm(ui,{recursive:true,force:true});}};
}
async function ordinaryState(page:Page){return page.evaluate(()=>({query:(window as unknown as {testQuery:{getQueryCache():{getAll():unknown[]}}}).testQuery.getQueryCache().getAll(),commands:(window as unknown as {genericCommands:unknown[]}).genericCommands}));}
it('real SecretSettings clears detached input on unmount without publishing its value to ordinary state or errors',async()=>{
 const h=await harness();try{const secret='FAKE_G6_UNMOUNT_SECRET_DO_NOT_LOG';await h.page.getByLabel('DeepSeek Key').fill(secret);await h.page.getByRole('button',{name:'离开设置'}).click();await h.page.getByText('已卸载凭据输入').waitFor();expect(await h.page.evaluate(()=>((window as unknown as {detachedInput:HTMLInputElement}).detachedInput).value)).toBe('');expect(JSON.stringify(await ordinaryState(h.page))+JSON.stringify(h.audit)+JSON.stringify(h.consoleMessages)).not.toContain(secret);expect(h.audit.map(record=>record.operation)).toEqual(['status']);}finally{await h.close();}
},30000);
it('real credential UI saves/replaces/cancels/disables/fails/deletes through the actual encrypted vault, with no fallback or ordinary-state leakage',async()=>{
 const h=await harness(),secrets=['FAKE_G6_FIRST_SECRET','FAKE_G6_REPLACEMENT_SECRET','FAKE_G6_CANCELLED_SECRET','FAKE_G6_FAILED_SECRET'];let release:(()=>void)|undefined;
 try{let input=h.page.getByLabel('DeepSeek Key');expect(await input.getAttribute('type')).toBe('password');expect(await input.getAttribute('autocomplete')).toBe('off');expect(await input.getAttribute('maxlength')).toBe('4096');
 h.control.pause=new Promise<void>(resolve=>release=resolve);await input.fill(secrets[0]!);await h.page.evaluate(()=>{(window as unknown as {savedInput:HTMLInputElement}).savedInput=document.querySelector('input')!;});await h.page.getByRole('button',{name:'保存到本机'}).click();expect(await h.page.evaluate(()=>((window as unknown as {savedInput:HTMLInputElement}).savedInput).value)).toBe('');expect(await input.isDisabled()).toBe(true);release!();h.control.pause=undefined;await h.page.getByRole('status').filter({hasText:'已配置'}).waitFor();expect(await h.page.getByLabel('DeepSeek Key').count()).toBe(0);const first=await h.vault.request({operation:'status'});if(first.kind!=='status')throw Error('first');expect(first.status).toMatchObject({configured:true,enabled:true});const oldGeneration=first.status.generation!;expect((await readFile(path.join(h.security,oldGeneration+'.encrypted'))).includes(Buffer.from(secrets[0]!))).toBe(false);
 await h.page.getByRole('button',{name:'更换 Key',exact:true}).click();input=h.page.getByLabel('DeepSeek Key');await input.fill(secrets[1]!);await h.page.getByRole('button',{name:'保存到本机'}).click();await expect.poll(()=>h.page.getByLabel('DeepSeek Key').count()).toBe(0);const replaced=await h.vault.request({operation:'status'});if(replaced.kind!=='status')throw Error('replacement');expect(replaced.status.generation).not.toBe(oldGeneration);await expect(readFile(path.join(h.security,oldGeneration+'.encrypted'))).rejects.toThrow();
 await h.page.getByRole('button',{name:'更换 Key',exact:true}).click();input=h.page.getByLabel('DeepSeek Key');const beforeCancel=h.audit.length;await input.fill(secrets[2]!);await h.page.getByRole('button',{name:'取消',exact:true}).click();expect(await h.page.getByLabel('DeepSeek Key').count()).toBe(0);expect(h.audit).toHaveLength(beforeCancel);expect(await h.vault.request({operation:'status'})).toEqual(replaced);
 await h.page.getByRole('button',{name:'停用',exact:true}).click();await h.page.getByRole('status').filter({hasText:'已停用'}).waitFor();h.control.available=false;await h.page.getByRole('button',{name:'配置 Key',exact:true}).click();input=h.page.getByLabel('DeepSeek Key');await input.fill(secrets[3]!);await h.page.getByRole('button',{name:'保存到本机'}).click();await h.page.getByRole('status').filter({hasText:'保存失败'}).waitFor();await expect.poll(()=>input.isEnabled()).toBe(true);expect(await h.page.getByLabel('DeepSeek Key').count()).toBe(1);expect(await input.inputValue()).toBe('');expect(await h.vault.request({operation:'status'})).toEqual({kind:'status',status:{...replaced.status,enabled:false}});
 h.control.available=true;h.control.encryptFailure=true;await input.fill(secrets[3]!);await h.page.getByRole('button',{name:'保存到本机'}).click();await h.page.getByRole('status').filter({hasText:'保存失败'}).waitFor();await expect.poll(()=>input.isEnabled()).toBe(true);expect(await input.inputValue()).toBe('');expect(await h.vault.request({operation:'status'})).toEqual({kind:'status',status:{...replaced.status,enabled:false}});h.control.encryptFailure=false;
 h.control.transportFailure=true;await input.fill(secrets[3]!);await h.page.getByRole('button',{name:'保存到本机'}).click();await h.page.getByRole('status').filter({hasText:'操作结果暂时无法确认'}).waitFor();await expect.poll(()=>input.isEnabled()).toBe(true);expect(await input.inputValue()).toBe('');h.control.transportFailure=false;await h.page.getByRole('button',{name:'刷新状态'}).click();await h.page.getByRole('status').filter({hasText:'已停用'}).waitFor();
 await h.page.getByRole('button',{name:'删除 Key'}).click();await h.page.getByRole('status').filter({hasText:'未配置'}).waitFor();expect(await h.vault.request({operation:'status'})).toEqual({kind:'status',status:{configured:false,enabled:false}});expect((await readdir(h.security)).filter(name=>name.endsWith('.encrypted'))).toEqual([]);
 const ordinary=JSON.stringify(await ordinaryState(h.page))+JSON.stringify(h.audit)+JSON.stringify(h.consoleMessages)+(await h.page.locator('body').innerText());for(const secret of secrets)expect(ordinary).not.toContain(secret);expect(ordinary).not.toContain('FAKE_ENCRYPT_ERROR_MUST_BE_SANITIZED');expect((await ordinaryState(h.page)).commands).toEqual([]);expect((await ordinaryState(h.page)).query).toEqual([]);for(const secret of secrets)expect(JSON.stringify(process.argv)).not.toContain(secret);
 }finally{release?.();await h.close();}
},30000);
it('the actual business backup excludes the actual encrypted vault and all fake credential bytes',async()=>{
 const h=await harness();let db:Database.Database|undefined;try{const secret='FAKE_G6_BACKUP_SECRET';await h.page.getByLabel('DeepSeek Key').fill(secret);await h.page.evaluate(()=>{(window as unknown as {savedInput:HTMLInputElement}).savedInput=document.querySelector('input')!;});await h.page.getByRole('button',{name:'保存到本机'}).click();expect(await h.page.evaluate(()=>((window as unknown as {savedInput:HTMLInputElement}).savedInput).value)).toBe('');await h.page.getByRole('status').filter({hasText:'已配置'}).waitFor();const active=path.join(h.root,'workspace');await mkdir(path.join(active,'blobs'),{recursive:true});db=new Database(path.join(active,'career.sqlite'));db.exec('CREATE TABLE platform_blobs(id TEXT,digest TEXT,size INTEGER,state TEXT);CREATE TABLE platform_artifact_retention(blob_id TEXT);CREATE TABLE business(body TEXT);');db.prepare('INSERT INTO business VALUES (?)').run('ordinary fictional career body');const manager=createBackupManager({root:h.root,getActiveRoot:()=>active,maintenance:async work=>work(),sanitizeCandidate:()=>{},validateRelations:()=>{}}),saved=await manager.backup(),folder=path.join(h.root,saved.relativePath);expect((await readdir(folder)).sort()).toEqual(['backup.json','blobs','career.sqlite']);const snapshot=await readFile(path.join(folder,'career.sqlite')),manifest=await readFile(path.join(folder,'backup.json'));expect(snapshot.includes(Buffer.from(secret))).toBe(false);expect(manifest.includes(Buffer.from(secret))).toBe(false);const encryptedName=(await readdir(h.security)).find(name=>name.endsWith('.encrypted'))!;expect(snapshot.includes(await readFile(path.join(h.security,encryptedName)))).toBe(false);expect(JSON.stringify(await ordinaryState(h.page))).not.toContain(secret);}finally{db?.close();await h.close();}
},30000);

it('Tavily Key entry uses the write-only credential UI, clears its input, and performs no search',async()=>{
 const h=await harness('tavily');try{
  const input=h.page.getByLabel('Tavily Search Key',{exact:true});expect(await input.getAttribute('type')).toBe('password');
  expect(await h.page.getByText('仅批准查询：OpenAI official website。',{exact:false}).count()).toBe(0);expect(await h.page.getByText(/保存不会发送请求/).count()).toBe(0);
  await input.fill('J07_SYNTHETIC_TAVILY_NOT_A_KEY');await h.page.evaluate(()=>{(window as unknown as {savedInput:HTMLInputElement}).savedInput=document.querySelector('input')!;});await h.page.getByRole('button',{name:'保存到本机'}).click();
  expect(await h.page.evaluate(()=>((window as unknown as {savedInput:HTMLInputElement}).savedInput).value)).toBe('');await h.page.getByRole('status').filter({hasText:'已配置'}).waitFor();
  expect(h.audit.filter(item=>item.operation==='save')).toHaveLength(1);expect(h.audit.every(item=>['status','save'].includes(item.operation))).toBe(true);expect(JSON.stringify(h.audit)+JSON.stringify(await ordinaryState(h.page))+JSON.stringify(h.consoleMessages)).not.toContain('J07_SYNTHETIC_TAVILY_NOT_A_KEY');
 }finally{await h.close();}
},30000);

it('shows the exact fixed test preview before sending and never sends automatically',async()=>{
 const h=await harness();try{
  const secret='FAKE_CONNECTION_UI_SECRET';await h.page.getByLabel('DeepSeek Key').fill(secret);await h.page.getByRole('button',{name:'保存到本机'}).click();await expect.poll(()=>h.page.getByLabel('DeepSeek Key').count()).toBe(0);
  await h.page.getByRole('button',{name:'测试连接',exact:true}).click();await h.page.getByRole('heading',{name:'连接测试预览'}).waitFor();
  expect(await h.page.getByText('只发送下方固定内容，不读取或附带 Career 资料。Key 只用于认证；本次单发，无重试、跳转或备用服务。',{exact:true}).count()).toBe(1);
  expect(await h.page.locator('pre').innerText()).toContain('deepseek-flash');expect(await h.page.evaluate(()=>((window as unknown as {connectionRequests:{operation:string}[]}).connectionRequests).map(item=>item.operation))).toEqual(['preview']);
  await h.page.getByRole('button',{name:'取消',exact:true}).click();expect(await h.page.evaluate(()=>((window as unknown as {connectionRequests:{operation:string}[]}).connectionRequests).map(item=>item.operation))).toEqual(['preview']);
  await h.page.getByRole('button',{name:'测试连接',exact:true}).click();await h.page.getByRole('button',{name:'发送一次测试'}).click();await h.page.getByRole('status').filter({hasText:'连接成功'}).waitFor();
  expect(await h.page.locator('.credential-status').innerText()).toBe('连接正常');
  expect(await h.page.evaluate(()=>((window as unknown as {connectionRequests:{operation:string}[]}).connectionRequests).map(item=>item.operation))).toEqual(['preview','preview','run']);expect(await h.page.getByRole('button',{name:'测试连接',exact:true}).isDisabled()).toBe(true);
  const visible=await h.page.locator('body').innerText();expect(visible).not.toContain(secret);expect(visible).not.toContain('Career Profile');
 }finally{await h.close();}
},30000);
