import {it,expect} from 'vitest';import Database from 'better-sqlite3';
import {createServer} from 'vite';import {chromium} from 'playwright';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';import path from 'node:path';import {tmpdir} from 'node:os';import {randomUUID} from 'node:crypto';
import {createOpportunityDomain} from '../packages/backend/domains/opportunity/public';import {opportunityMigration} from '../packages/backend/domains/opportunity/migration';
import {createProjectDomain,projectMigration} from '../packages/backend/domains/project/public';
import {createEmploymentDomain,employmentMigration} from '../packages/backend/domains/employment/public';import {commandMigration} from '../packages/backend/platform/commands/receipts';

it('100 real Opportunities and Projects remain navigable with Chinese short queries, ended filters and retained list position',async()=>{
 const root=await mkdtemp(path.join(tmpdir(),'career-g6-scale-'));const ui=path.resolve('dist/g6-scale-ui');await mkdir(ui,{recursive:true});
 const db=new Database(path.join(root,'career.sqlite'));db.pragma('foreign_keys=ON');db.exec(commandMigration+employmentMigration+projectMigration+opportunityMigration);
 const employment=createEmploymentDomain(db),project=createProjectDomain(db,employment),opportunity=createOpportunityDomain(db);
 const employments=Array.from({length:3},(_,i)=>{const r=employment.handle({operation:'create',commandId:randomUUID(),company:'Fixture employment '+i,role:'Engineer',goal:'Controlled scale fixture',started:true,start:{kind:'unknown'},plannedEnd:{kind:'unknown'}});if(r.kind!=='employment')throw Error(JSON.stringify(r));return r.employment.id;});
 const company=opportunity.handle({operation:'company.create',commandId:randomUUID(),name:'Scale fixture company'});if(company.kind!=='company')throw Error();
 let longRole='';for(let i=0;i<100;i++){
  const title=(i%2?'Engineering similar role ':'牛蛙相似名称 ')+String(i).padStart(3,'0')+(i===98?' long title '.repeat(10):'');if(i===98)longRole=title.trim();
  const p=project.handle({operation:'create',commandId:randomUUID(),name:title,description:i%10===0?'Large body '.repeat(900):'Fixture',tags:['G6 controlled fixture'],employmentId:i%4===0?null:employments[i%3],occurredAt:{kind:'unknown'}});
  const o=opportunity.handle({operation:'create',commandId:randomUUID(),companyId:company.company.id,role:title});
  if(p.kind!=='project'||o.kind!=='opportunity')throw Error('fixture_failed');
  if(i%4===0){expect(project.handle({operation:'state.change',commandId:randomUUID(),id:p.project.id,expectedRevision:1,state:'completed',mode:'change',reason:'Controlled ended fixture',occurredAt:{kind:'unknown'}}).kind).toBe('project');expect(opportunity.handle({operation:'end',commandId:randomUUID(),id:o.opportunity.id,expectedRevision:1,outcome:'withdrawn',reason:'Controlled ended fixture',businessTime:{kind:'unknown'}}).kind).toBe('opportunity');}
 }
 await writeFile(path.join(ui,'index.html'),'<div id="app"></div><script type="module" src="/main.tsx"></script>');
 await writeFile(path.join(ui,'main.tsx'),`import React from'react';import{createRoot}from'react-dom/client';import{HashRouter}from'react-router';import{QueryClient,QueryClientProvider}from'@tanstack/react-query';import{CareerShell}from'../../packages/frontend/shell/index.tsx';import{ProjectPage}from'../../packages/frontend/features/project/index.tsx';import{OpportunityPage}from'../../packages/frontend/features/opportunity/index.tsx';const client=new QueryClient();const send=module=>async input=>(await fetch('/owner',{method:'POST',body:JSON.stringify({module,input})})).json();createRoot(document.getElementById('app')!).render(<HashRouter><QueryClientProvider client={client}><CareerShell pages={{project:<ProjectPage request={send('project')} employmentRequest={send('employment')}/>,opportunity:<OpportunityPage request={send('opportunity')}/>,wiki:<p>Controlled unused Wiki entry</p>,employment:<p>Controlled unused Employment entry</p>}}/></QueryClientProvider></HashRouter>);`);
 const server=await createServer({configFile:false,root:ui,cacheDir:path.join(ui,'.vite'),plugins:[{name:'g6-real-owners',configureServer(s){s.middlewares.use('/owner',(req,res)=>{let body='';req.on('data',c=>body+=String(c));req.on('end',()=>{const v=JSON.parse(body),owner=v.module==='project'?project:v.module==='employment'?employment:opportunity;res.setHeader('content-type','application/json');res.end(JSON.stringify(owner.handle(v.input)));});});}}],server:{host:'127.0.0.1',port:0,fs:{allow:[process.cwd()]}}});
 let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
 try{await server.listen();const address=server.httpServer!.address();if(!address||typeof address==='string')throw Error();browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage();page.setDefaultTimeout(6000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${address.port}/#/project`);
  const p=page.getByRole('region',{name:'项目',exact:true}),o=page.getByRole('region',{name:'机会',exact:true});
  const projectList=p.locator(':scope > ul'),opportunityList=o.locator(':scope > ul');
  await expect.poll(()=>projectList.getByRole('button').count()).toBe(100);
  await p.getByLabel('搜索项目').fill('牛');expect(await projectList.getByRole('button').count()).toBe(50);
  await p.getByLabel('搜索项目').fill('牛蛙');expect(await projectList.getByRole('button').count()).toBe(50);
  await p.getByLabel('项目状态筛选').selectOption('completed');expect(await projectList.getByRole('button').count()).toBe(25);
  // Actual wheel/scroll offsets, not just retained query values.
  await projectList.hover();await page.mouse.wheel(0,480);await expect.poll(()=>projectList.evaluate(el=>el.scrollTop)).toBeGreaterThan(0);
  const opened=projectList.getByRole('button').nth(20);await opened.scrollIntoViewIfNeeded();const projectWindowBefore=await page.evaluate(()=>window.scrollY),projectScrollBefore=await projectList.evaluate(el=>el.scrollTop);expect(projectScrollBefore).toBeGreaterThan(0);
  await opened.click();await p.getByRole('button',{name:'保存项目内容',exact:true}).waitFor();await p.getByRole('textbox',{name:'项目名称',exact:true}).fill('Controlled unsaved project draft');
  await p.getByRole('button',{name:'返回项目列表（保留输入）'}).click();await expect.poll(async()=>Math.abs(await page.evaluate(()=>window.scrollY)-projectWindowBefore)).toBeLessThan(2);const projectWindowReturned=await page.evaluate(()=>window.scrollY),projectScrollReturned=await projectList.evaluate(el=>el.scrollTop);expect(projectScrollReturned).toBe(projectScrollBefore);expect(await p.getByLabel('搜索项目').inputValue()).toBe('牛蛙');
  await opened.click();expect(await p.getByRole('textbox',{name:'项目名称',exact:true}).inputValue()).toBe('Controlled unsaved project draft');await p.getByRole('button',{name:'返回项目列表（保留输入）'}).click();
  await p.getByLabel('项目状态筛选').selectOption('all');await p.getByLabel('搜索项目').fill('eNgInEeRiNg');expect(await projectList.getByRole('button').count()).toBe(50);
  await p.getByLabel('搜索项目').fill('long title');expect(await projectList.getByRole('button').count()).toBe(1);const projectLongTitle=(await projectList.getByRole('button').textContent())!;expect(projectLongTitle.length).toBeGreaterThan(100);await projectList.getByRole('button').click();await p.getByRole('button',{name:'保存项目内容',exact:true}).waitFor();expect(await p.getByRole('textbox',{name:'项目名称',exact:true}).inputValue()).toBe(longRole);await p.getByRole('button',{name:'返回项目列表（保留输入）'}).click();
  await p.getByLabel('搜索项目').fill('无匹配的测试');expect(await projectList.getByRole('button').count()).toBe(0);await p.getByText('没有符合筛选条件的项目',{exact:true}).waitFor();
  await p.getByLabel('搜索项目').fill('牛蛙');await p.getByLabel('项目状态筛选').selectOption('completed');await projectList.hover();await page.mouse.wheel(0,250);await expect.poll(()=>projectList.evaluate(el=>el.scrollTop)).toBeGreaterThan(0);const projectNavigationScroll=await projectList.evaluate(el=>el.scrollTop);
  await page.getByRole('navigation',{name:'一级导航'}).getByRole('link',{name:'机会',exact:true}).click();await expect.poll(()=>opportunityList.getByRole('button').count()).toBe(100);
  await o.getByLabel('搜索机会').fill('无匹配的测试');expect(await opportunityList.getByRole('button').count()).toBe(0);await o.getByText('没有符合筛选条件的机会',{exact:true}).waitFor();
  await o.getByLabel('搜索机会').fill('eNgInEeRiNg');expect(await opportunityList.getByRole('button').count()).toBe(50);await o.getByLabel('搜索机会').fill('long title');expect(await opportunityList.getByRole('button').count()).toBe(1);const opportunityLongTitle=(await opportunityList.getByRole('button').textContent())!;expect(opportunityLongTitle.length).toBeGreaterThan(100);await opportunityList.getByRole('button').click();await o.getByRole('button',{name:'保存机会修改',exact:true}).waitFor();expect(await o.getByLabel('岗位名称',{exact:true}).inputValue()).toBe(longRole);await o.getByRole('button',{name:'返回机会列表（保留输入）'}).click();
  await o.getByLabel('搜索机会').fill('牛');expect(await opportunityList.getByRole('button').count()).toBe(50);await o.getByLabel('搜索机会').fill('牛蛙');expect(await opportunityList.getByRole('button').count()).toBe(50);await o.getByLabel('机会结果筛选').selectOption('ended');expect(await opportunityList.getByRole('button').count()).toBe(25);
  await opportunityList.hover();await page.mouse.wheel(0,480);await expect.poll(()=>opportunityList.evaluate(el=>el.scrollTop)).toBeGreaterThan(0);const opportunityOpened=opportunityList.getByRole('button').nth(20);await opportunityOpened.scrollIntoViewIfNeeded();const opportunityWindowBefore=await page.evaluate(()=>window.scrollY),opportunityScrollBefore=await opportunityList.evaluate(el=>el.scrollTop);expect(opportunityScrollBefore).toBeGreaterThan(0);
  const selectedRole=(await opportunityOpened.textContent())!.split(' · ')[1];await opportunityOpened.click();await expect.poll(()=>o.getByLabel('岗位名称',{exact:true}).inputValue()).toBe(selectedRole);await o.getByLabel('岗位名称',{exact:true}).fill('Controlled unsaved opportunity draft');await o.getByRole('button',{name:'返回机会列表（保留输入）'}).click();await expect.poll(async()=>Math.abs(await page.evaluate(()=>window.scrollY)-opportunityWindowBefore)).toBeLessThan(2);const opportunityWindowReturned=await page.evaluate(()=>window.scrollY),opportunityScrollReturned=await opportunityList.evaluate(el=>el.scrollTop);expect(opportunityScrollReturned).toBe(opportunityScrollBefore);expect(await o.getByLabel('岗位名称',{exact:true}).inputValue()).toBe('Controlled unsaved opportunity draft');
  await page.getByRole('navigation',{name:'一级导航'}).getByRole('link',{name:'项目',exact:true}).click();expect(await p.getByLabel('项目状态筛选').inputValue()).toBe('completed');expect(await projectList.evaluate(el=>el.scrollTop)).toBe(projectNavigationScroll);
  await page.getByRole('navigation',{name:'一级导航'}).getByRole('link',{name:'机会',exact:true}).click();expect(await o.getByLabel('搜索机会').inputValue()).toBe('牛蛙');expect(await opportunityList.evaluate(el=>el.scrollTop)).toBe(opportunityScrollBefore);expect(await o.getByLabel('岗位名称',{exact:true}).inputValue()).toBe('Controlled unsaved opportunity draft');
  expect(errors).toEqual([]);await mkdir('/tmp/career-g6',{recursive:true});await writeFile('/tmp/career-g6/scale-observations.json',JSON.stringify({opportunities:100,projects:100,employments:3,chineseOneChar:50,chineseTwoChar:50,endedFiltered:25,noMatch:0,noMatchOwners:['project','opportunity'],englishMixedCase:50,longTitleOpened:{project:projectLongTitle.length,opportunity:opportunityLongTitle.length},actualScroll:{project:{before:projectScrollBefore,returned:projectScrollReturned,navigationRetained:projectNavigationScroll,windowBefore:projectWindowBefore,windowReturned:projectWindowReturned},opportunity:{before:opportunityScrollBefore,returned:opportunityScrollReturned,windowBefore:opportunityWindowBefore,windowReturned:opportunityWindowReturned}},draftsRetained:true,pageErrors:errors,benchmark:false},null,2));
 }finally{await browser?.close();await server.close();db.close();await rm(root,{recursive:true,force:true});await rm(ui,{recursive:true,force:true});}
},40000);
