import {it,expect} from 'vitest';
import {chromium} from 'playwright';
import {createServer} from 'vite';
import Database from 'better-sqlite3';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import path from 'node:path';import {tmpdir} from 'node:os';import {randomUUID} from 'node:crypto';
import {createOpportunityDomain} from '../packages/backend/domains/opportunity/public';
import {opportunityMigration} from '../packages/backend/domains/opportunity/migration';
import {commandMigration} from '../packages/backend/platform/commands/receipts';
import {createInterviewDomain} from '../packages/backend/domains/opportunity/interview/public';
import {interviewMigration} from '../packages/backend/domains/opportunity/interview/migration';
import {Request} from '../packages/contracts/opportunity/interview/schema';
it('a real browser confirms a pending round, saves manual preparation/transcript/review, corrects it and guards unknown saves',async()=>{
 const root=await mkdtemp(path.join(tmpdir(),'career-interview-ui-'));const ui=path.resolve('dist/interview-ui-test');await mkdir(ui,{recursive:true});const db=new Database(path.join(root,'career.sqlite'));db.exec(commandMigration);db.exec(opportunityMigration);db.exec(interviewMigration);const core=createOpportunityDomain(db);const c=core.handle({operation:'company.create',commandId:randomUUID(),name:'面试公司'});if(c.kind!=='company')throw Error();const o=core.handle({operation:'create',commandId:randomUUID(),companyId:c.company.id,role:'岗位'});if(o.kind!=='opportunity')throw Error();const owner=createInterviewDomain(db,{core:core.capabilities});const other=core.handle({operation:'create',commandId:randomUUID(),companyId:c.company.id,role:'机会 B'});if(other.kind!=='opportunity')throw Error();
 await writeFile(path.join(ui,'index.html'),'<html><body><div id="app"></div><script type="module" src="/main.tsx"></script></body></html>');
 await writeFile(path.join(ui,'main.tsx'),`import React,{useState}from'react';import{createRoot}from'react-dom/client';import{InterviewPage}from'../../packages/frontend/features/opportunity/interview/index.tsx';function Test(){const[id,setId]=useState('${o.opportunity.id}');return <><button onClick={()=>setId('${o.opportunity.id}')}>切到机会 A</button><button onClick={()=>setId('${other.opportunity.id}')}>切到机会 B</button><InterviewPage opportunityId={id} workspaceInstance="test" request={async input=>{const response=await fetch('/test-owner',{method:'POST',body:JSON.stringify(input)});if(!response.ok)throw Error('lost');return response.json();}}/></>;}createRoot(document.getElementById('app')!).render(<Test/>);`);
 let drop=false;let offlineReceipt=false;let failRead=false;let delay=false;let release:(()=>void)|undefined;let delayList=false;let releaseList:(()=>void)|undefined;
 const server=await createServer({configFile:false,root:ui,plugins:[{name:'interview-owner',configureServer(server){server.middlewares.use('/test-owner',(req,res)=>{let body='';req.on('data',chunk=>body+=String(chunk));req.on('end',()=>{void(async()=>{const input=Request.parse(JSON.parse(body));if(delayList&&input.operation==='interview.list'&&input.opportunityId===o.opportunity.id){delayList=false;await new Promise<void>(resolve=>releaseList=resolve);}if(delay&&input.operation==='interview.save-document'){delay=false;await new Promise<void>(resolve=>release=resolve);}if(offlineReceipt&&input.operation==='interview.receipt'||failRead&&input.operation==='interview.read'){res.statusCode=503;res.end();return;}const result=owner.handle(input);if(drop&&input.operation==='interview.save-document'){drop=false;res.statusCode=503;res.end();return;}res.setHeader('content-type','application/json');res.end(JSON.stringify(result));})().catch(()=>{res.statusCode=500;res.end();});});});}}],server:{host:'127.0.0.1',port:0,fs:{allow:[process.cwd()]}}});
 let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
 try{await server.listen();const address=server.httpServer!.address();if(!address||typeof address==='string')throw Error();browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage();page.setDefaultTimeout(6000);await page.goto(`http://127.0.0.1:${address.port}`);
 await page.getByLabel('真实轮次名称',{exact:true}).fill('真实二面');await page.getByRole('button',{name:'确认存在真实轮次',exact:true}).click();await page.getByRole('heading',{name:'真实二面',exact:true}).waitFor();expect(await page.getByText('待排期',{exact:true}).count()).toBeGreaterThan(0);
 const prep=page.getByLabel('当前准备',{exact:true}),transcript=page.getByLabel('当前文字稿',{exact:true}),review=page.getByLabel('当前终版复盘',{exact:true});await prep.fill('部分人工准备');await page.getByRole('button',{name:'保存当前准备',exact:true}).click();await page.getByRole('status').filter({hasText:'已保存'}).waitFor();await transcript.fill('第一次人工文字稿');await page.getByRole('button',{name:'保存当前文字稿',exact:true}).click();await page.getByRole('status').filter({hasText:'已保存'}).waitFor();await review.fill('人工结论保留');await page.getByRole('button',{name:'保存当前终版复盘',exact:true}).click();await page.getByRole('status').filter({hasText:'已保存'}).waitFor();await transcript.fill('明确更正后的文字稿');await page.getByRole('button',{name:'保存当前文字稿',exact:true}).click();await page.getByText('文字稿依据变化，终版复盘待复核',{exact:true}).waitFor();expect(await review.inputValue()).toBe('人工结论保留');
 await review.fill('未提交的复盘草稿');expect(await page.evaluate(()=>!window.dispatchEvent(new Event('beforeunload',{cancelable:true})))).toBe(true);
 delay=true;await page.getByRole('button',{name:'保存当前终版复盘',exact:true}).click();await expect.poll(()=>typeof release).toBe('function');expect(await review.isDisabled()).toBe(true);release?.();await page.getByRole('status').filter({hasText:'已保存'}).waitFor();
 await transcript.fill('保存结果待核对的文字稿');drop=true;offlineReceipt=true;await page.getByRole('button',{name:'保存当前文字稿',exact:true}).click();await page.getByRole('status').filter({hasText:'保存结果待核对'}).waitFor();expect(await transcript.isDisabled()).toBe(true);expect(await page.evaluate(()=>!window.dispatchEvent(new Event('beforeunload',{cancelable:true})))).toBe(true);offlineReceipt=false;await page.getByRole('button',{name:'核对原保存回执',exact:true}).click();await page.getByRole('status').filter({hasText:'已保存'}).waitFor();expect(await transcript.inputValue()).toBe('保存结果待核对的文字稿');
 failRead=true;await prep.fill('已经提交但回读失败的准备');await page.getByRole('button',{name:'保存当前准备',exact:true}).click();await page.getByRole('status').filter({hasText:'已保存，正文暂不可重读'}).waitFor();expect(await prep.inputValue()).toBe('已经提交但回读失败的准备');expect(await prep.isDisabled()).toBe(false);failRead=false;

 await page.getByLabel('面试变化说明',{exact:true}).fill('首次真实排期');await page.getByLabel('本次实际业务时间类型',{exact:true}).selectOption('date');await page.getByLabel('本次实际业务时间日期',{exact:true}).fill('2026-10-12');await page.getByRole('button',{name:'记录本轮真实变化',exact:true}).click();await page.getByText('已排期',{exact:true}).waitFor();
 await page.getByLabel('面试变化说明',{exact:true}).fill('招聘方真实改期');await page.getByLabel('本次实际业务时间类型',{exact:true}).selectOption('date');await page.getByLabel('本次实际业务时间日期',{exact:true}).fill('2026-10-13');await page.getByRole('button',{name:'记录本轮真实变化',exact:true}).click();await page.getByText(/预约：2026-10-13/).waitFor();
 await page.getByLabel('现实变化',{exact:true}).selectOption('temporarily_cancel');await page.getByLabel('面试变化说明',{exact:true}).fill('临时取消，需要重新约');await page.getByRole('button',{name:'记录本轮真实变化',exact:true}).click();await page.getByText('临时取消，待重约',{exact:true}).waitFor();
 await page.getByLabel('现实变化',{exact:true}).selectOption('complete');await page.getByLabel('面试变化说明',{exact:true}).fill('历史已经完成但日期未知');await page.getByRole('button',{name:'记录本轮真实变化',exact:true}).click();await page.locator('span').filter({hasText:/^已完成$/}).waitFor();
 await page.getByLabel('纠错后的原轮次状态',{exact:true}).selectOption('awaiting_schedule');await page.getByLabel('面试变化说明',{exact:true}).fill('误点完成，纠正同一轮');await page.getByRole('button',{name:'明确纠正本轮终态误操作',exact:true}).click();await page.getByText('待排期',{exact:true}).waitFor();

 const existing=owner.handle({operation:'interview.list',opportunityId:o.opportunity.id});if(existing.kind!=='sessions')throw Error();const round=existing.items[0];owner.handle({operation:'interview.save-document',commandId:randomUUID(),id:round.id,expectedRevision:round.revision,document:'preparation',text:'另一窗口的正式准备'});
 await transcript.fill('保留的冲突文字稿');await page.getByRole('button',{name:'保存当前文字稿',exact:true}).click();await page.getByRole('complementary',{name:'面试冲突比较',exact:true}).waitFor();expect(await transcript.inputValue()).toBe('保留的冲突文字稿');expect(await page.getByRole('complementary',{name:'面试冲突比较',exact:true}).textContent()).toContain('另一窗口的正式准备');await page.getByRole('button',{name:'采用面试新基线并保留草稿',exact:true}).click();expect(await transcript.inputValue()).toBe('保留的冲突文字稿');await page.getByRole('button',{name:'保存当前文字稿',exact:true}).click();await page.getByRole('status').filter({hasText:'已保存'}).waitFor();
 page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'放弃本轮所有未提交输入',exact:true}).click();expect(await prep.inputValue()).toBe('另一窗口的正式准备');
 await transcript.fill('未提交且不得被新轮次吞掉');await page.getByLabel('真实轮次名称',{exact:true}).fill('试图打开新轮次');await page.getByRole('button',{name:'确认存在真实轮次',exact:true}).click();await page.getByRole('status').filter({hasText:'当前轮次还有未提交输入'}).waitFor();expect(await transcript.inputValue()).toBe('未提交且不得被新轮次吞掉');page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'放弃本轮所有未提交输入',exact:true}).click();
 const list=owner.handle({operation:'interview.list',opportunityId:o.opportunity.id});expect(list).toMatchObject({kind:'sessions',items:[{title:'真实二面',preparation:'另一窗口的正式准备',transcript:{text:'保留的冲突文字稿'},finalReview:{text:'未提交的复盘草稿',needsRecheck:true}}]});

 await page.getByRole('button',{name:'切到机会 B',exact:true}).click();await page.getByText('尚无面试轮次，可确认现实已存在的轮次；打开页面不会自动创建。',{exact:true}).waitFor();
 delayList=true;await page.getByRole('button',{name:'切到机会 A',exact:true}).click();await expect.poll(()=>typeof releaseList).toBe('function');await page.getByRole('button',{name:'切到机会 B',exact:true}).click();await page.getByLabel('真实轮次名称',{exact:true}).fill('机会 B 的真实轮次');releaseList?.();await page.getByRole('button',{name:'确认存在真实轮次',exact:true}).click();await page.getByRole('heading',{name:'机会 B 的真实轮次',exact:true}).waitFor();expect(await page.getByRole('button',{name:'真实二面',exact:true}).count()).toBe(0);expect(owner.handle({operation:'interview.list',opportunityId:other.opportunity.id})).toMatchObject({kind:'sessions',items:[{title:'机会 B 的真实轮次',opportunityId:other.opportunity.id}]});
 }finally{release?.();releaseList?.();await browser?.close();await server.close();db.close();await rm(root,{recursive:true,force:true});await rm(ui,{recursive:true,force:true});}
},30000);
