import {it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import path from 'node:path';
import {createServer} from 'vite';
import {chromium} from 'playwright';
import {LegacyProposalHistory,LegacyHistoryRequest} from '../packages/contracts/ai/legacy-history/schema';
import {syntheticLegacyHistory} from './fixtures/legacy-history';
it('late historical details cannot overwrite a newer choice and repeated pagination cannot append duplicates',async()=>{
 const root=await mkdtemp(path.resolve('out/verification/legacy-history/ui-'));const input=syntheticLegacyHistory()[0]!;const rows=Array.from({length:101},(_,i)=>LegacyProposalHistory.parse({...input,id:randomUUID(),sourceRecordIdentity:'TEST-ui-'+i,archivedAt:'2026-10-04T00:00:00Z',content:input.content.availability==='available'?{...input.content,proposal:{...input.content.proposal,title:'TEST history '+i}}:input.content}));
 await writeFile(path.join(root,'index.html'),'<div id="root"></div><script type="module" src="/main.tsx"></script>');await writeFile(path.join(root,'main.tsx'),`import React from 'react';import {createRoot} from 'react-dom/client';import {LegacyHistoryView} from ${JSON.stringify('/@fs/'+path.resolve('packages/frontend/support/ai/legacy-history.tsx'))};createRoot(document.getElementById('root')).render(<LegacyHistoryView request={input=>fetch('/api',{method:'POST',body:JSON.stringify(input)}).then(r=>r.json())}/>);`);
 const server=await createServer({configFile:false,root,cacheDir:path.join(root,'.vite'),logLevel:'error',server:{host:'127.0.0.1',port:0,fs:{allow:[process.cwd()]}}});const browser=await chromium.launch({headless:true});let releaseRead:undefined|(()=>Promise<void>),releasePage:undefined|(()=>Promise<void>);
 try{await server.listen();const port=server.httpServer!.address();if(!port||typeof port==='string')throw Error();const page=await browser.newPage();page.setDefaultTimeout(5000);await page.route('**/api',async route=>{const request=LegacyHistoryRequest.parse(route.request().postDataJSON());if(request.operation==='legacy-history.list'){const result={kind:'legacy_history_list',items:request.afterId?rows.slice(100):rows.slice(0,100),...request.afterId?{}:{nextAfterId:rows[99]!.id}};if(request.afterId){releasePage=async()=>{await route.fulfill({json:result});};}else await route.fulfill({json:result});}else{const result={kind:'legacy_history',item:rows.find(i=>i.id===request.id)!};if(request.id===rows[0]!.id)releaseRead=async()=>{await route.fulfill({json:result});};else await route.fulfill({json:result});}});
  await page.goto('http://127.0.0.1:'+port.port);await page.getByRole('button',{name:'TEST history 0 · pending',exact:true}).click();await expect.poll(()=>!!releaseRead).toBe(true);await page.getByRole('button',{name:'TEST history 1 · pending',exact:true}).click();const detail=page.getByRole('article',{name:'历史 AI 建议详情'});await detail.getByRole('heading',{name:'TEST history 1',exact:true}).waitFor();await releaseRead!();await page.waitForTimeout(100);expect(await detail.getByRole('heading',{level:4}).textContent()).toBe('TEST history 1');
  const more=page.getByRole('button',{name:'查看更多历史'});await more.click();await expect.poll(()=>!!releasePage).toBe(true);expect(await more.isDisabled()).toBe(true);await releasePage!();await page.getByRole('button',{name:'TEST history 100 · pending',exact:true}).waitFor();expect(await page.getByRole('region',{name:'历史 AI 建议',exact:true}).locator('li').count()).toBe(101);
 }finally{await browser.close();await server.close();await rm(root,{recursive:true,force:true});}
},30000);
