import {it,expect} from 'vitest';
import {chromium} from 'playwright';
import {createServer} from 'vite';
import Database from 'better-sqlite3';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import path from 'node:path';
import {tmpdir} from 'node:os';
import {randomUUID} from 'node:crypto';
import {createOpportunityDomain} from '../packages/backend/domains/opportunity/public';
import {opportunityMigration} from '../packages/backend/domains/opportunity/migration';
import {commandMigration} from '../packages/backend/platform/commands/receipts';
import {createOfferDomain} from '../packages/backend/domains/opportunity/offer/public';
import {offerMigration} from '../packages/backend/domains/opportunity/offer/migration';
import {Request} from '../packages/contracts/opportunity/offer/schema';
it('real UI preserves conflicts and pending intents and accepts immutable conditions through the SQLite public owner',async()=>{
 const root=await mkdtemp(path.join(tmpdir(),'career-offer-ui-'));const ui=path.resolve('dist/offer-ui-test');await mkdir(ui,{recursive:true});const db=new Database(path.join(root,'career.sqlite'));db.exec(commandMigration);db.exec(opportunityMigration);db.exec(offerMigration);const core=createOpportunityDomain(db);
 const company=core.handle({operation:'company.create',commandId:randomUUID(),name:'Offer UI Company'});if(company.kind!=='company')throw Error('fixture');const created=core.handle({operation:'create',commandId:randomUUID(),companyId:company.company.id,role:'Engineer'});if(created.kind!=='opportunity')throw Error('fixture');const id=created.opportunity.id;
 const owner=createOfferDomain(db,{core:core.capabilities,validateSource:()=>({status:'unavailable'})});
 await writeFile(path.join(ui,'index.html'),'<html><body><div id="app"></div><script type="module" src="/main.tsx"></script></body></html>');
 await writeFile(path.join(ui,'main.tsx'),`import React from'react';import{createRoot}from'react-dom/client';import{OfferPage}from'../../packages/frontend/features/opportunity/offer/index.tsx';createRoot(document.getElementById('app')!).render(<OfferPage opportunityId="${id}" workspaceInstance="test-workspace" request={async input=>{const response=await fetch('/test-owner',{method:'POST',body:JSON.stringify(input)});if(!response.ok)throw Error('lost');return response.json();}}/>);`);
 let drop=false;const server=await createServer({configFile:false,root:ui,plugins:[{name:'offer-public-owner',configureServer(server){server.middlewares.use('/test-owner',(req,res)=>{let body='';req.on('data',chunk=>body+=String(chunk));req.on('end',()=>{try{const request=Request.parse(JSON.parse(body));const result=owner.handle(request);if(drop&&request.operation==='offer.accept'){drop=false;res.statusCode=503;res.end();return;}res.setHeader('content-type','application/json');res.end(JSON.stringify(result));}catch{res.statusCode=500;res.end();}});});}}],server:{host:'127.0.0.1',port:0,fs:{allow:[process.cwd()]}}});let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
 try{
 await server.listen();const address=server.httpServer!.address();if(!address||typeof address==='string')throw Error('port');browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage();page.setDefaultTimeout(5000);await page.goto(`http://127.0.0.1:${address.port}`);
 await page.getByText('尚未记录 Offer', {exact:true}).waitFor();await page.getByLabel('保证现金',{exact:true}).fill('30k monthly');await page.getByLabel('原件说明',{exact:true}).fill('口头约定从未有书面原件');await page.getByLabel('变化说明',{exact:true}).fill('现实已经收到');expect(await page.evaluate(()=>!window.dispatchEvent(new Event('beforeunload',{cancelable:true})))).toBe(true);await page.getByRole('button',{name:'确认现实收到 Offer',exact:true}).click();await page.getByRole('status').filter({hasText:'保存成功'}).waitFor();
 await page.getByLabel('保证现金',{exact:true}).fill('我的25k草稿');const current=owner.handle({operation:'offer.read',opportunityId:id});if(current.kind!=='offer')throw Error('read');owner.handle({operation:'offer.correct',commandId:randomUUID(),opportunityId:id,expectedRevision:current.offer.revision,expectedOpportunityRevision:current.opportunity.revision,conditions:{...current.offer.conditions,guaranteedCash:{kind:'known',value:'另一窗口26k'}},businessTime:{kind:'unknown'},reason:'纠正记录'});
 await page.getByLabel('变化说明',{exact:true}).fill('纠正笔误');await page.getByRole('button',{name:'纠正当前条件记录',exact:true}).click();await page.getByRole('complementary',{name:'Offer 冲突比较'}).waitFor();expect(await page.getByLabel('保证现金',{exact:true}).inputValue()).toBe('我的25k草稿');expect(await page.getByRole('complementary',{name:'Offer 冲突比较'}).textContent()).toContain('另一窗口26k');await page.getByRole('button',{name:'采用正式基线并保留草稿'}).click();await page.getByRole('button',{name:'纠正当前条件记录',exact:true}).click();await page.getByRole('status').filter({hasText:'保存成功'}).waitFor();
 await page.getByLabel('变化说明',{exact:true}).fill('接受当前实际条件');drop=true;await page.getByRole('button',{name:'接受当前有效条件',exact:true}).click();await page.getByRole('status').filter({hasText:'保存结果待核对'}).waitFor();expect(await page.getByLabel('保证现金',{exact:true}).isDisabled()).toBe(true);await page.getByRole('button',{name:'核对原保存回执',exact:true}).click();await page.getByRole('status').filter({hasText:'保存成功'}).waitFor();expect(core.handle({operation:'read',id})).toMatchObject({kind:'opportunity',opportunity:{result:'accepted'}});await page.getByRole('button',{name:'查看接受依据与历史',exact:true}).click();await page.getByRole('complementary',{name:'Offer 接受依据与历史'}).waitFor();expect(await page.getByRole('complementary',{name:'Offer 接受依据与历史'}).textContent()).toContain('我的25k草稿');
 }finally{await browser?.close();await server.close();db.close();await rm(root,{recursive:true,force:true});await rm(ui,{recursive:true,force:true});}
},30000);
it('switching owners retains independent drafts and a late A save result never writes B',async()=>{
 const root=await mkdtemp(path.join(tmpdir(),'career-offer-switch-'));const ui=path.resolve('dist/offer-switch-test');await mkdir(ui,{recursive:true});const db=new Database(path.join(root,'career.sqlite'));db.exec(commandMigration);db.exec(opportunityMigration);db.exec(offerMigration);const core=createOpportunityDomain(db);const company=core.handle({operation:'company.create',commandId:randomUUID(),name:'Switch'});if(company.kind!=='company')throw Error('fixture');const ids:string[]=[];
 for(const role of ['A','B']){const created=core.handle({operation:'create',commandId:randomUUID(),companyId:company.company.id,role});if(created.kind!=='opportunity')throw Error('fixture');ids.push(created.opportunity.id);}
 const owner=createOfferDomain(db,{core:core.capabilities,validateSource:()=>({status:'unavailable'})});
 await writeFile(path.join(ui,'index.html'),'<html><body><div id="app"></div><script type="module" src="/main.tsx"></script></body></html>');await writeFile(path.join(ui,'main.tsx'),`import React,{useState}from'react';import{createRoot}from'react-dom/client';import{OfferPage}from'../../packages/frontend/features/opportunity/offer/index.tsx';function Test(){const[id,setId]=useState('${ids[0]}');return <><button onClick={()=>setId('${ids[0]}')}>打开 A</button><button onClick={()=>setId('${ids[1]}')}>打开 B</button><OfferPage opportunityId={id} workspaceInstance="fixture" request={async input=>{const response=await fetch('/test-owner',{method:'POST',body:JSON.stringify(input)});if(!response.ok)throw Error('lost');return response.json();}}/></>;}createRoot(document.getElementById('app')!).render(<Test/>);`);
 let release:(()=>void)|undefined;let hold=true;
 const server=await createServer({configFile:false,root:ui,plugins:[{name:'offer-switch-owner',configureServer(server){server.middlewares.use('/test-owner',(req,res)=>{let body='';req.on('data',chunk=>body+=String(chunk));req.on('end',()=>{void(async()=>{const input=Request.parse(JSON.parse(body));const result=owner.handle(input);if(input.operation==='offer.receive'&&input.opportunityId===ids[0]&&hold){hold=false;await new Promise<void>(resolve=>release=resolve);}res.setHeader('content-type','application/json');res.end(JSON.stringify(result));})().catch(()=>{res.statusCode=500;res.end();});});});}}],server:{host:'127.0.0.1',port:0,fs:{allow:[process.cwd()]}}});let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
 try{
 await server.listen();const address=server.httpServer!.address();if(!address||typeof address==='string')throw Error('port');browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage();page.setDefaultTimeout(5000);await page.goto(`http://127.0.0.1:${address.port}`);await page.getByText('尚未记录 Offer',{exact:true}).waitFor();await page.getByLabel('保证现金',{exact:true}).fill('A draft');await page.getByLabel('原件说明',{exact:true}).fill('A oral');await page.getByLabel('变化说明',{exact:true}).fill('Actually received A');await page.getByRole('button',{name:'确认现实收到 Offer',exact:true}).click();await expect.poll(()=>typeof release).toBe('function');expect(await page.getByLabel('保证现金',{exact:true}).isDisabled()).toBe(true);
 await page.getByRole('button',{name:'打开 B',exact:true}).click();await page.getByText('尚未记录 Offer',{exact:true}).waitFor();await page.getByLabel('保证现金',{exact:true}).fill('B independent draft');release?.();await expect.poll(()=>owner.handle({operation:'offer.read',opportunityId:ids[0]})).toMatchObject({kind:'offer',offer:{conditions:{guaranteedCash:{kind:'known',value:'A draft'}}}});expect(await page.getByLabel('保证现金',{exact:true}).inputValue()).toBe('B independent draft');expect(await page.evaluate(()=>!window.dispatchEvent(new Event('beforeunload',{cancelable:true})))).toBe(true);expect(owner.handle({operation:'offer.read',opportunityId:ids[1]})).toMatchObject({kind:'empty',opportunity:{phase:'preparation'}});
 await page.getByRole('button',{name:'打开 A',exact:true}).click();await page.getByRole('status').filter({hasText:'保存成功'}).waitFor();expect(await page.getByLabel('保证现金',{exact:true}).inputValue()).toBe('A draft');await page.getByRole('button',{name:'打开 B',exact:true}).click();expect(await page.getByLabel('保证现金',{exact:true}).inputValue()).toBe('B independent draft');
 }finally{release?.();await browser?.close();await server.close();db.close();await rm(root,{recursive:true,force:true});await rm(ui,{recursive:true,force:true});}
},30000);
