import {wasPurged,type PurgeNotice} from '../../design-system/purge-notice';
import type {SourceRef} from '../../../contracts/common/source-ref';
import { useMemo,useState,useRef,useEffect,type ReactNode } from 'react';
import { QueryClient,QueryClientProvider,useQuery } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { Request,Result,type Knowledge,type History } from '../../../contracts/wiki/schema';
import { Result as MaterialsResult,type MaterialsBridge,type Raw } from '../../../contracts/materials/schema';
import { submitWikiIntent,checkWikiIntent,type WikiSaveState } from './save';
type Form={title:string;body:string;scope:Knowledge['scope'];scopeId:string;nature:Knowledge['nature'];reason:string;correction:boolean};
const empty:Form={title:'',body:'',scope:'personal',scopeId:'',nature:'observation',reason:'',correction:false};
const natureLabels={fact_statement:'事实陈述',observation:'观察',hypothesis:'待验证判断'};
export interface WikiPageProps {focusScope?:{scope:Knowledge['scope'];scopeId:string;sequence:number};importContent?:ReactNode|((onUse:(raw:Raw)=>void)=>ReactNode);researchContent?:ReactNode;changeEpoch?:number;purgeNotice?:PurgeNotice;request:(input:Request)=>Promise<Result>;materials?:MaterialsBridge;workspaceInstance?:string;sourceCatalogue?:()=>Promise<{id:string;name:string;source:SourceRef}[]>;scopeCatalogue?:()=>Promise<{scope:Knowledge['scope'];scopeId:string;label:string}[]>;readSourceVersion?:(ref:SourceRef)=>Promise<string|undefined>}
export function WikiPage(props:WikiPageProps){const [client]=useState(()=>new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}}));return <QueryClientProvider client={client}><WikiContents {...props}/></QueryClientProvider>;}
function WikiContents({focusScope,importContent,researchContent,changeEpoch,purgeNotice,request,materials,workspaceInstance='wiki-session',sourceCatalogue,readSourceVersion,scopeCatalogue}:WikiPageProps){
 const [view,setView]=useState<'list'|'knowledge'|'import'|'research'>('list'),[editing,setEditing]=useState(false),[search,setSearch]=useState('');
 useEffect(()=>{if(focusScope){setListScope(focusScope.scope+':'+focusScope.scopeId);setView('list');}},[focusScope?.sequence]);
 const [openedSource,setOpenedSource]=useState<SourceRef>();
 const [selected,setSelected]=useState<Knowledge>();const [sources,setSources]=useState<Knowledge['sources']>([]);const [sourcesDirty,setSourcesDirty]=useState(false);
 const [listScope,setListScope]=useState('general');const [includeRetired,setIncludeRetired]=useState(false);const [status,setStatus]=useState('未保存');const [pending,setPending]=useState<Request>();const [saveState,setSaveState]=useState<WikiSaveState>();const [busy,setBusy]=useState(false);
 const [history,setHistory]=useState<History[]>([]);const [sourceText,setSourceText]=useState('');const [sourceId,setSourceId]=useState('');const [purpose,setPurpose]=useState('');const [server,setServer]=useState<Knowledge>();
 const form=useForm<Form>({defaultValues:empty});const dirty=form.formState.isDirty||sourcesDirty;const contentDirty=!!(form.formState.dirtyFields.title||form.formState.dirtyFields.body||form.formState.dirtyFields.scope||form.formState.dirtyFields.nature||sourcesDirty);const viewGeneration=useRef(0);
 useEffect(()=>{const protect=(event:BeforeUnloadEvent)=>{if(dirty||pending){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',protect);return()=>window.removeEventListener('beforeunload',protect);},[dirty,pending]);
 const [filterScope,filterId]=listScope.split(':');const list=useQuery({queryKey:['wiki',workspaceInstance,'list',includeRetired,listScope],queryFn:async()=>{const r=Result.parse(await request(Request.parse({operation:'list',includeRetired,...(filterScope!=='general'?{scope:filterScope,...(filterId?{scopeId:filterId}:{})}:{})})));if(r.kind!=='list')throw Error('列表读取失败');return r.items;}});
 const rawList=useQuery({queryKey:['wiki',workspaceInstance,'materials'],enabled:!!materials,queryFn:async()=>{if(sourceCatalogue)return sourceCatalogue();if(!materials)return [];const r=MaterialsResult.parse(await materials.request({operation:'list'}));if(r.kind!=='list')throw Error('来源列表暂不可读');return r.items;}});
 const scopeOptions=useQuery({queryKey:['wiki',workspaceInstance,'scope-targets'],enabled:!!scopeCatalogue,queryFn:()=>scopeCatalogue!()});const activeScope=form.watch('scope');
 const sourceCandidates=useMemo(()=>rawList.data??[],[rawList.data]);
 function adopt(knowledge?:Knowledge){viewGeneration.current++;setSelected(knowledge);setSources(knowledge?.sources??[]);setSourcesDirty(false);form.reset(knowledge?{title:knowledge.title,body:knowledge.body,scope:knowledge.scope,scopeId:knowledge.scopeId??'',nature:knowledge.nature,reason:'',correction:false}:empty);setHistory([]);setSourceText('');setServer(undefined);setSaveState(undefined);setStatus(knowledge?'已保存':'未保存');}
 useEffect(()=>{if(changeEpoch)void list.refetch();},[changeEpoch]);
 useEffect(()=>{if(!purgeNotice)return;if(filterId&&wasPurged(purgeNotice,filterScope,filterId))setListScope('general');if(wasPurged(purgeNotice,'wiki',selected?.id)){adopt();setPending(undefined);setStatus('这条知识已永久清除；未保存的该对象输入已关闭。');}else{if(selected&&(selected.sources.some(source=>wasPurged(purgeNotice,source.ref.owner,source.ref.objectId))||(selected.trustedProvenance??[]).some(source=>wasPurged(purgeNotice,source.owner,source.objectId))))setSelected({...selected,reviewRequired:true});if(openedSource&&wasPurged(purgeNotice,openedSource.owner,openedSource.objectId)){viewGeneration.current++;setSourceText('');setOpenedSource(undefined);}}void list.refetch();void rawList.refetch();},[purgeNotice?.sequence]);
 async function open(id:string){if(pending)return;if(dirty&&!window.confirm('有未保存的知识输入。放弃后切换？'))return;const generation=++viewGeneration.current;try{const r=Result.parse(await request({operation:'read',id}));if(generation!==viewGeneration.current)return;if(r.kind==='knowledge'){adopt(r.knowledge);setView('knowledge');setEditing(false);}else setStatus('知识暂不可读');}catch{if(generation===viewGeneration.current)setStatus('读取失败，当前输入保留');}}
 async function finish(state:WikiSaveState,intent:Request){setSaveState(state);if(state.state==='saved'){setPending(undefined);adopt(state.knowledge);setView('knowledge');setEditing(false);setStatus('已保存');const refreshed=await list.refetch();if(refreshed.isError)setStatus('已保存，列表暂时未刷新；请重新读取');}else if(state.state==='unknown'){setPending(intent);setStatus('暂时无法确认是否保存。你的输入还在，请先检查保存结果。');}else if(state.state==='not_recorded'){setPending(intent);setStatus('已经确认这次保存尚未完成，可以继续保存。');}else{setPending(undefined);setStatus(state.state==='conflict'?'冲突：本地输入已保留，请比较正式值':'保存未完成，你的输入仍保留。');if(state.state==='conflict'&&selected){const r=Result.parse(await request({operation:'read',id:selected.id}));if(r.kind==='knowledge')setServer(r.knowledge);}}}
 async function run(intent:Request){setBusy(true);setPending(intent);setStatus('保存中');try{await finish(await submitWikiIntent(request,intent),intent);}catch{setStatus('结果读取失败，当前输入保留');}finally{setBusy(false);}}
 async function submit(values:Form){const common={title:values.title,body:values.body,scope:values.scope,...(values.scopeId&&!['personal','cognition'].includes(values.scope)?{scopeId:values.scopeId}:{}),nature:values.nature,sources};const candidate=selected?{...common,operation:'edit',commandId:crypto.randomUUID(),id:selected.id,expectedRevision:selected.revision,reason:values.reason,change:values.correction?'corrected':'edited',businessTime:{kind:'unknown'}}:{...common,operation:'create',commandId:crypto.randomUUID()};const parsed=Request.safeParse(candidate);if(!parsed.success){setStatus('请填写标题、正文；修改时说明原因。');return;}await run(parsed.data);}
 async function lifecycle(){if(!selected||contentDirty)return;const values=form.getValues();const candidate=Request.safeParse({operation:'lifecycle',commandId:crypto.randomUUID(),id:selected.id,expectedRevision:selected.revision,action:selected.status==='active'?'retire':'restore',reason:values.reason,businessTime:{kind:'unknown'},correction:values.correction});if(!candidate.success){setStatus('请填写退役或恢复说明');return;}await run(candidate.data);}
 async function showHistory(){if(!selected)return;const generation=viewGeneration.current;try{const r=Result.parse(await request({operation:'history',id:selected.id}));if(generation!==viewGeneration.current)return;if(r.kind==='history')setHistory(r.items);else setStatus('历史暂不可读');}catch{if(generation===viewGeneration.current)setStatus('历史读取失败，编辑输入保留');}}
 async function showSource(ref:SourceRef){setOpenedSource(ref);if(readSourceVersion){const generation=viewGeneration.current;setSourceText('来源读取中');try{const text=await readSourceVersion(ref);if(generation===viewGeneration.current)setSourceText(text??'该版本来源不可读；没有替换为当前文本');}catch{if(generation===viewGeneration.current)setSourceText('来源暂不可读');}return;}if(ref.owner!=='materials'){setSourceText('此来源归对应沟通或面试文字稿；旧版本不可读时不会替换为当前文本。');return;}if(!materials)return;const generation=viewGeneration.current;setSourceText('来源读取中');try{const r=MaterialsResult.parse(await materials.request({operation:'read',materialId:ref.objectId}));if(generation!==viewGeneration.current)return;if(r.kind==='raw'&&JSON.stringify(r.raw.source)===JSON.stringify(ref))setSourceText(r.raw.text);else setSourceText('该版本来源不可读；没有替换为其他版本');}catch{if(generation===viewGeneration.current)setSourceText('来源暂不可读');}}
 function addSource(){const raw=sourceCandidates.find(item=>item.id===sourceId);if(!raw||!purpose.trim())return;if(sources.some(item=>item.ref.objectId===raw.id)){setStatus('这个原件已经引用');return;}viewGeneration.current++;setSources([...sources,{ref:raw.source,purpose:purpose.trim()}]);setSourcesDirty(true);setPurpose('');}
 function start(){if(pending)return;if(dirty&&!window.confirm('放弃未保存输入并记录新知识？'))return;adopt();setView('knowledge');setEditing(true);}
 function useRaw(raw:Raw){if(pending)return;if(dirty&&!window.confirm('放弃未保存输入并使用这份原始材料？'))return;adopt();setSources([{ref:raw.source,purpose:'原始材料参考'}]);setSourcesDirty(true);void rawList.refetch();setView('knowledge');setEditing(true);}
 const visibleItems=(list.data??[]).filter(item=>!search.trim()||(item.title+' '+item.body).toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()));
 return <section aria-label="Wiki 知识" data-feedback-owner="wiki" data-feedback-id={selected?.id}><h1>Wiki</h1><p>这里放你以后还想找回和复用的职业资料。</p>
 <div hidden={view!=='list'}><div className="page-actions">{(dirty||pending||editing)&&<button onClick={()=>{setView('knowledge');setEditing(true);}}>继续编辑知识草稿</button>}<button className="primary-action" disabled={!!pending} onClick={start}>记录知识</button>{importContent&&<button onClick={()=>setView('import')}>导入原始材料</button>}</div><label>搜索知识<input value={search} onChange={event=>setSearch(event.target.value)}/></label>
 <label>知识列表范围<select value={listScope} onChange={event=>setListScope(event.target.value)}><option value="general">默认知识（不包括私有机会）</option><option value="personal">个人</option><option value="cognition">长期认知</option>{scopeOptions.data?.map(item=><option key={item.scope+item.scopeId} value={item.scope+":"+item.scopeId}>{item.label}</option>)}</select></label><label><input type="checkbox" checked={includeRetired} onChange={e=>setIncludeRetired(e.target.checked)}/>包括退役知识</label><button onClick={()=>{void list.refetch();void scopeOptions.refetch();}}>刷新</button>
 {list.isError?<p role="alert">列表暂不可读，当前输入保留。</p>:list.isPending?<p>正在读取知识…</p>:visibleItems.length===0?<p>{search?'没有找到匹配的知识，试试其他关键词。':'记下一条以后还想用的经验，也可以先保存一份原始材料。'}</p>:<ul className="readable-list">{visibleItems.map(item=><li key={item.id}><button disabled={!!pending} onClick={()=>void open(item.id)}>{item.title}</button><p>{item.status==='active'?'当前有效':'已退役'} · {natureLabels[item.nature]}</p></li>)}</ul>}
 {researchContent&&<details><summary>更多</summary><button onClick={()=>setView('research')}>查看机会情报引用</button></details>}</div>
 {view!=='list'&&<button onClick={()=>setView('list')}>返回知识列表（保留输入）</button>}
 <div hidden={view!=='import'}>{typeof importContent==='function'?importContent(useRaw):importContent}</div><div hidden={view!=='research'}>{researchContent}</div>
 <div hidden={view!=='knowledge'}>{selected&&<article aria-label="知识阅读" hidden={editing}><h2>{selected.title}</h2><p>{natureLabels[selected.nature]} · {selected.status==='active'?'当前有效':'已退役'} · {scopeOptions.data?.find(item=>item.scopeId===selected.scopeId)?.label??({personal:'个人',cognition:'长期认知',project:'项目',employment:'任职',person:'人物',opportunity:'机会'}[selected.scope])}</p><div className="readable-body">{selected.body}</div><p>{selected.origin==='ai_accepted'?'AI 建议经人工采纳':'用户记录'} · 未独立核实 · {selected.sources.length?`${selected.sources.length} 份来源`:'尚未引用原始材料'}</p>{selected.reviewRequired&&<p role="alert">依据已变化，需要复核；正文保持原内容。</p>}<button className="primary-action" onClick={()=>setEditing(true)}>编辑</button><details><summary>更多</summary><h3>来源详情</h3>{selected.sources.map(source=><div key={source.ref.objectId}><p>{sourceCandidates.find(item=>item.id===source.ref.objectId)?.name??'引用来源'} · {source.purpose}</p><button onClick={()=>void showSource(source.ref)}>查看原件</button></div>)}<button onClick={()=>void showHistory()}>查看知识修订历史</button><button onClick={()=>setEditing(true)}>{selected.status==='active'?'退役知识（填写说明）':'恢复知识（填写说明）'}</button><details><summary>查看技术详情</summary><pre>{JSON.stringify({id:selected.id,revision:selected.revision,sources:selected.sources},null,2)}</pre></details></details></article>}
 <div hidden={!editing}><button onClick={()=>selected?setEditing(false):setView('list')}>{selected?'返回阅读（保留输入）':'收起知识草稿（保留输入）'}</button>
 <form onChange={()=>{viewGeneration.current++;}} onSubmit={form.handleSubmit(submit)} aria-label="知识编辑"><fieldset disabled={busy||!!pending}><legend>{selected?'编辑知识':'手工记录知识'}</legend>
 <label>知识标题<input {...form.register('title')} maxLength={200}/></label><label>知识正文<textarea {...form.register('body')} maxLength={64000} rows={7}/></label>
 <label>范围<select {...form.register('scope')}><option value="personal">个人</option><option value="cognition">长期认知</option><option value="project">项目</option><option value="employment">任职</option><option value="person">人物</option><option value="opportunity">机会</option></select></label>{!['personal','cognition'].includes(activeScope)&&<label>明确所属对象<select {...form.register('scopeId')}><option value="">请选择真实对象</option>{selected?.scope===activeScope&&selected.scopeId&&!scopeOptions.data?.some(item=>item.scopeId===selected.scopeId)&&<option value={selected.scopeId}>当前所属对象（暂时不可读）</option>}{scopeOptions.data?.filter(item=>item.scope===activeScope).map(item=><option key={item.scopeId} value={item.scopeId}>{item.label}</option>)}</select></label>}
 <label>内容性质<select {...form.register('nature')}><option value="fact_statement">事实陈述</option><option value="observation">观察</option><option value="hypothesis">待验证判断</option></select></label><p>{selected?.origin==='ai_accepted'?'AI 建议经人工采纳':'用户记录'} · 未独立核实；没有来源也可以保存。</p>{selected?.reviewRequired&&<p role="alert">依据已变化 / 待复核；正文保持原内容。</p>}
 {selected&&<><label>变化说明<input {...form.register('reason')} maxLength={1000}/></label><label><input type="checkbox" {...form.register('correction')}/>纠正原记录；不勾选表示后来发生的变化</label></>}
 {materials&&<div><h3>引用已有原件或可更正文字稿</h3><button type="button" onClick={()=>void rawList.refetch()}>刷新原件列表</button><label>选择原件<select value={sourceId} onChange={e=>setSourceId(e.target.value)}><option value="">不选来源</option>{sourceCandidates.map(raw=><option key={raw.id} value={raw.id}>{raw.name}</option>)}</select></label><label>来源用途<input value={purpose} onChange={e=>setPurpose(e.target.value)} maxLength={500}/></label><button type="button" onClick={addSource}>加入来源引用</button>{rawList.isError&&<p>来源列表暂不可读</p>}</div>}
 <details><summary>来源引用</summary><ul>{sources.map((source,index)=><li key={source.ref.objectId}>{sourceCandidates.find(raw=>raw.id===source.ref.objectId)?.name??'引用来源'} · {source.purpose}<button type="button" onClick={()=>void showSource(source.ref)}>读取原件</button><button type="button" onClick={()=>{viewGeneration.current++;setSources(sources.filter((_,i)=>i!==index));setSourcesDirty(true);}}>移除引用</button></li>)}</ul></details>
 <button className="primary-action" type="submit">{selected?'保存知识修改':'保存知识'}</button>{selected&&<button type="button" disabled={contentDirty} onClick={()=>void lifecycle()}>{selected.status==='active'?'退役知识':'恢复知识'}</button>}
 </fieldset></form></div><p hidden={view==='list'&&!dirty&&!pending&&status==='未保存'} role="status">{status}{dirty&&!pending?' · 有未保存输入':''}</p>
 {pending&&'commandId'in pending&&<div><button disabled={busy} onClick={async()=>{setBusy(true);try{await finish(await checkWikiIntent(request,pending.commandId),pending);}finally{setBusy(false);}}}>检查是否已保存</button>{saveState?.state==='not_recorded'&&<button disabled={busy} onClick={()=>void run(pending)}>继续保存</button>}</div>}
 {server&&<aside aria-label="冲突比较"><h3>当前正式值（你的草稿仍在编辑区）</h3><p>{server.title}</p><pre>{server.body}</pre><button onClick={()=>{setSelected(server);setServer(undefined);setStatus('已采用正式版本作为新基线；草稿保留，请明确保存');}}>采用新基线并保留草稿</button><button onClick={()=>adopt(server)}>放弃草稿并读取正式值</button></aside>}
 {sourceText&&<aside aria-label="来源原文"><h3>来源原文（只读）</h3><pre>{sourceText}</pre><button onClick={()=>setSourceText('')}>关闭原件</button></aside>}
 {history.length>0&&<aside aria-label="知识历史"><h3>修订历史（只读）</h3>{history.map(item=><article key={item.knowledge.revision}><h4>版本 {item.knowledge.revision} · {({created:'创建',edited:'修改',retired:'退役',restored:'恢复',corrected:'纠正'}[item.change])} · {item.knowledge.status==='active'?'有效':'退役'}</h4><p>{item.reason}</p><pre>{item.knowledge.body}</pre></article>)}<button onClick={()=>setHistory([])}>关闭历史</button></aside>}
 </div></section>;
}
