import type {SourceRef} from '../../../contracts/common/source-ref';
import { useMemo,useState,useRef,useEffect } from 'react';
import { QueryClient,QueryClientProvider,useQuery } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { Request,Result,type Knowledge,type History } from '../../../contracts/wiki/schema';
import { Result as MaterialsResult,type MaterialsBridge } from '../../../contracts/materials/schema';
import { submitWikiIntent,checkWikiIntent,type WikiSaveState } from './save';
type Form={title:string;body:string;scope:Knowledge['scope'];nature:Knowledge['nature'];reason:string;correction:boolean};
const empty:Form={title:'',body:'',scope:'personal',nature:'observation',reason:'',correction:false};
const natureLabels={fact_statement:'事实陈述',observation:'观察',hypothesis:'待验证判断'};
export interface WikiPageProps {request:(input:Request)=>Promise<Result>;materials?:MaterialsBridge;workspaceInstance?:string}
export function WikiPage(props:WikiPageProps){const [client]=useState(()=>new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}}));return <QueryClientProvider client={client}><WikiContents {...props}/></QueryClientProvider>;}
function WikiContents({request,materials,workspaceInstance='wiki-session'}:WikiPageProps){
 const [selected,setSelected]=useState<Knowledge>();const [sources,setSources]=useState<Knowledge['sources']>([]);const [sourcesDirty,setSourcesDirty]=useState(false);
 const [includeRetired,setIncludeRetired]=useState(false);const [status,setStatus]=useState('未保存');const [pending,setPending]=useState<Request>();const [saveState,setSaveState]=useState<WikiSaveState>();const [busy,setBusy]=useState(false);
 const [history,setHistory]=useState<History[]>([]);const [sourceText,setSourceText]=useState('');const [sourceId,setSourceId]=useState('');const [purpose,setPurpose]=useState('');const [server,setServer]=useState<Knowledge>();
 const form=useForm<Form>({defaultValues:empty});const dirty=form.formState.isDirty||sourcesDirty;const contentDirty=!!(form.formState.dirtyFields.title||form.formState.dirtyFields.body||form.formState.dirtyFields.scope||form.formState.dirtyFields.nature||sourcesDirty);const viewGeneration=useRef(0);
 useEffect(()=>{const protect=(event:BeforeUnloadEvent)=>{if(dirty||pending){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',protect);return()=>window.removeEventListener('beforeunload',protect);},[dirty,pending]);
 const list=useQuery({queryKey:['wiki',workspaceInstance,'list',includeRetired],queryFn:async()=>{const r=Result.parse(await request({operation:'list',includeRetired}));if(r.kind!=='list')throw Error('列表读取失败');return r.items;}});
 const rawList=useQuery({queryKey:['wiki',workspaceInstance,'materials'],enabled:!!materials,queryFn:async()=>{if(!materials)return [];const r=MaterialsResult.parse(await materials.request({operation:'list'}));if(r.kind!=='list')throw Error('来源列表暂不可读');return r.items;}});
 const sourceCandidates=useMemo(()=>rawList.data??[],[rawList.data]);
 function adopt(knowledge?:Knowledge){viewGeneration.current++;setSelected(knowledge);setSources(knowledge?.sources??[]);setSourcesDirty(false);form.reset(knowledge?{title:knowledge.title,body:knowledge.body,scope:knowledge.scope,nature:knowledge.nature,reason:'',correction:false}:empty);setHistory([]);setSourceText('');setServer(undefined);setSaveState(undefined);setStatus(knowledge?'已保存':'未保存');}
 async function open(id:string){if(pending)return;if(dirty&&!window.confirm('有未保存的知识输入。放弃后切换？'))return;const generation=++viewGeneration.current;try{const r=Result.parse(await request({operation:'read',id}));if(generation!==viewGeneration.current)return;if(r.kind==='knowledge')adopt(r.knowledge);else setStatus('知识暂不可读');}catch{if(generation===viewGeneration.current)setStatus('读取失败，当前输入保留');}}
 async function finish(state:WikiSaveState,intent:Request){setSaveState(state);if(state.state==='saved'){setPending(undefined);adopt(state.knowledge);setStatus('已保存');const refreshed=await list.refetch();if(refreshed.isError)setStatus('已保存，列表暂时未刷新；请重新读取');}else if(state.state==='unknown'){setPending(intent);setStatus('保存结果待核对；当前输入保留');}else if(state.state==='not_recorded'){setPending(intent);setStatus('未发现原命令，可明确继续同一意图');}else{setPending(undefined);setStatus(state.state==='conflict'?'冲突：本地输入已保留，请比较正式值':'保存失败，当前输入保留：'+state.code);if(state.state==='conflict'&&selected){const r=Result.parse(await request({operation:'read',id:selected.id}));if(r.kind==='knowledge')setServer(r.knowledge);}}}
 async function run(intent:Request){setBusy(true);setPending(intent);setStatus('保存中');try{await finish(await submitWikiIntent(request,intent),intent);}catch{setStatus('结果读取失败，当前输入保留');}finally{setBusy(false);}}
 async function submit(values:Form){const common={title:values.title,body:values.body,scope:values.scope,nature:values.nature,sources};const candidate=selected?{...common,operation:'edit',commandId:crypto.randomUUID(),id:selected.id,expectedRevision:selected.revision,reason:values.reason,change:values.correction?'corrected':'edited',businessTime:{kind:'unknown'}}:{...common,operation:'create',commandId:crypto.randomUUID()};const parsed=Request.safeParse(candidate);if(!parsed.success){setStatus('请填写标题、正文；修改时说明原因。');return;}await run(parsed.data);}
 async function lifecycle(){if(!selected||contentDirty)return;const values=form.getValues();const candidate=Request.safeParse({operation:'lifecycle',commandId:crypto.randomUUID(),id:selected.id,expectedRevision:selected.revision,action:selected.status==='active'?'retire':'restore',reason:values.reason,businessTime:{kind:'unknown'},correction:values.correction});if(!candidate.success){setStatus('请填写退役或恢复说明');return;}await run(candidate.data);}
 async function showHistory(){if(!selected)return;const generation=viewGeneration.current;try{const r=Result.parse(await request({operation:'history',id:selected.id}));if(generation!==viewGeneration.current)return;if(r.kind==='history')setHistory(r.items);else setStatus('历史暂不可读');}catch{if(generation===viewGeneration.current)setStatus('历史读取失败，编辑输入保留');}}
 async function showSource(ref:SourceRef){if(ref.owner!=='materials'){setSourceText('此来源归对应沟通或面试文字稿；旧版本不可读时不会替换为当前文本。');return;}if(!materials)return;const generation=viewGeneration.current;setSourceText('来源读取中');try{const r=MaterialsResult.parse(await materials.request({operation:'read',materialId:ref.objectId}));if(generation!==viewGeneration.current)return;if(r.kind==='raw'&&JSON.stringify(r.raw.source)===JSON.stringify(ref))setSourceText(r.raw.text);else setSourceText('该版本来源不可读；没有替换为其他版本');}catch{if(generation===viewGeneration.current)setSourceText('来源暂不可读');}}
 function addSource(){const raw=sourceCandidates.find(item=>item.id===sourceId);if(!raw||!purpose.trim())return;if(sources.some(item=>item.ref.objectId===raw.id)){setStatus('这个原件已经引用');return;}setSources([...sources,{ref:raw.source,purpose:purpose.trim()}]);setSourcesDirty(true);setPurpose('');}
 return <section aria-label="Wiki 知识"><h1>Wiki</h1><p>先阅读知识，再查看性质、原件和修订。原件与事实陈述都不代表独立核实。</p>
 <div><label><input type="checkbox" checked={includeRetired} onChange={e=>setIncludeRetired(e.target.checked)}/>包括退役知识</label><button disabled={!!pending} onClick={()=>{if(!dirty||window.confirm('放弃未保存输入并创建新知识？'))adopt();}}>新建知识</button><button onClick={()=>void list.refetch()}>重新读取列表</button></div>
 {list.isError?<p role="alert">列表暂不可读，当前输入保留。</p>:list.data?.length===0?<p>还没有知识。可以直接手工记录，或选择已有个人原件作为来源。</p>:<ul>{list.data?.map(item=><li key={item.id}><button disabled={!!pending} onClick={()=>void open(item.id)}>{item.title}</button> · {item.status==='active'?'当前有效':'已退役'} · {natureLabels[item.nature]}</li>)}</ul>}
 <form onSubmit={form.handleSubmit(submit)} aria-label="知识编辑"><fieldset disabled={busy||!!pending}><legend>{selected?'编辑知识':'手工记录知识'}</legend>
 <label>知识标题<input {...form.register('title')} maxLength={200}/></label><label>知识正文<textarea {...form.register('body')} maxLength={64000} rows={7}/></label>
 <label>范围<select {...form.register('scope')}><option value="personal">个人</option><option value="cognition">长期认知</option></select></label>
 <label>内容性质<select {...form.register('nature')}><option value="fact_statement">事实陈述</option><option value="observation">观察</option><option value="hypothesis">待验证判断</option></select></label><p>{selected?.origin==='ai_accepted'?'AI 建议经人工采纳':'用户记录'} · 未独立核实；没有来源也可以保存。</p>{selected?.reviewRequired&&<p role="alert">依据已变化 / 待复核；正文保持原内容。</p>}
 {selected&&<><label>变化说明<input {...form.register('reason')} maxLength={1000}/></label><label><input type="checkbox" {...form.register('correction')}/>纠正原记录；不勾选表示后来发生的变化</label></>}
 {materials&&<div><h3>引用已有 Raw 原件</h3><button type="button" onClick={()=>void rawList.refetch()}>刷新原件列表</button><label>选择原件<select value={sourceId} onChange={e=>setSourceId(e.target.value)}><option value="">不选来源</option>{sourceCandidates.map(raw=><option key={raw.id} value={raw.id}>{raw.name}</option>)}</select></label><label>来源用途<input value={purpose} onChange={e=>setPurpose(e.target.value)} maxLength={500}/></label><button type="button" onClick={addSource}>加入来源引用</button>{rawList.isError&&<p>来源列表暂不可读</p>}</div>}
 <ul>{sources.map((source,index)=><li key={source.ref.objectId}>{sourceCandidates.find(raw=>raw.id===source.ref.objectId)?.name??source.ref.objectId} · {source.purpose} · 原件版本 {source.ref.revision}<button type="button" onClick={()=>void showSource(source.ref)}>读取原件</button><button type="button" onClick={()=>{setSources(sources.filter((_,i)=>i!==index));setSourcesDirty(true);}}>移除引用</button></li>)}</ul>
 <button type="submit">{selected?'保存知识修改':'保存知识'}</button>{selected&&<button type="button" disabled={contentDirty} onClick={()=>void lifecycle()}>{selected.status==='active'?'退役知识':'恢复知识'}</button>}
 </fieldset></form><p role="status">{status}{dirty&&!pending?' · 有未保存输入':''}</p>
 {pending&&'commandId'in pending&&<div><button disabled={busy} onClick={async()=>{setBusy(true);try{await finish(await checkWikiIntent(request,pending.commandId),pending);}finally{setBusy(false);}}}>核对原保存回执</button>{saveState?.state==='not_recorded'&&<button disabled={busy} onClick={()=>void run(pending)}>继续原保存意图</button>}</div>}
 {server&&<aside aria-label="冲突比较"><h3>当前正式值（你的草稿仍在编辑区）</h3><p>{server.title}</p><pre>{server.body}</pre><button onClick={()=>{setSelected(server);setServer(undefined);setStatus('已采用正式版本作为新基线；草稿保留，请明确保存');}}>采用新基线并保留草稿</button><button onClick={()=>adopt(server)}>放弃草稿并读取正式值</button></aside>}
 {sourceText&&<aside aria-label="来源原文"><h3>Materials 原件（只读）</h3><pre>{sourceText}</pre><button onClick={()=>setSourceText('')}>关闭原件</button></aside>}
 {selected&&<button onClick={()=>void showHistory()}>查看知识修订历史</button>}{history.length>0&&<aside aria-label="知识历史"><h3>修订历史（只读）</h3>{history.map(item=><article key={item.knowledge.revision}><h4>版本 {item.knowledge.revision} · {item.change} · {item.knowledge.status==='active'?'有效':'退役'}</h4><p>{item.reason}</p><pre>{item.knowledge.body}</pre></article>)}<button onClick={()=>setHistory([])}>关闭历史</button></aside>}
 </section>;
}
