const resultLabel:Record<OpportunityView['result'],string>={active:'进行中',accepted:'已接受 Offer',withdrawn:'已退出',recruiter_ended:'招聘方已终止'};
import {wasPurged,type PurgeNotice} from '../../../design-system/purge-notice';
import React, {useEffect,useRef,useState} from 'react';
import {Request,Result,Conditions,type Offer,type AcceptanceBasis,type Event} from '../../../../contracts/opportunity/offer/schema';
import type {OpportunityView} from '../../../../contracts/opportunity/schema';
import type {RawSummary} from '../../../../contracts/materials/schema';
import type {BusinessTime} from '../../../../contracts/common/business-time';
const fields={role:'条件中的岗位',location:'工作地点',guaranteedCash:'保证现金',variableIncome:'浮动收入',equity:'权益',oneTime:'一次性收入',paymentCycle:'支付周期',other:'其他条件'} as const;
type Values=Record<keyof typeof fields,string>;
const emptyValues:Values={role:'',location:'',guaranteedCash:'',variableIncome:'',equity:'',oneTime:'',paymentCycle:'',other:''};
type OriginalForm={kind:'never_existed'|'historically_lost'|'retained';explanation:string;objectId:string};
type Session={loaded:boolean;offer?:Offer;opportunity?:OpportunityView;values:Values;original:OriginalForm;reason:string;timeKind:BusinessTime['kind'];date:string;instant:string;timezone:string;historical:boolean;mode:'correction'|'replacement';busy:boolean;pending?:Request;missing:boolean;status:string;server?:Extract<Result,{kind:'offer'|'empty'}>;history?:{events:Event[];acceptances:AcceptanceBasis[]}};
function initial():Session{return {loaded:false,values:{...emptyValues},original:{kind:'never_existed',explanation:'',objectId:''},reason:'',timeKind:'unknown',date:'',instant:'',timezone:'',historical:false,mode:'correction',busy:false,missing:false,status:'正在读取 Offer'};}
function valuesOf(offer?:Offer):Values{return Object.fromEntries(Object.keys(fields).map(key=>{const condition=offer?.conditions[key as keyof Values];return [key,condition?.kind==='known'?condition.value:''];})) as Values;}
function originalOf(offer?:Offer):OriginalForm{return offer?{kind:offer.original.kind,explanation:offer.original.kind==='retained'?'':offer.original.explanation,objectId:offer.original.kind==='retained'?offer.original.source.objectId:''}:{kind:'never_existed',explanation:'',objectId:''};}
function conditionsOf(values:Values):Conditions{return Conditions.parse(Object.fromEntries(Object.entries(values).map(([key,value])=>[key,value.trim()?{kind:'known',value:value}:{kind:'unknown'}])));}
function contentDirty(session:Session){return JSON.stringify(session.values)!==JSON.stringify(valuesOf(session.offer))||JSON.stringify(session.original)!==JSON.stringify(originalOf(session.offer));}
function dirty(session:Session){return contentDirty(session)||!!session.reason||session.timeKind!=='unknown'||session.historical;}
function timeOf(session:Session):BusinessTime{return session.timeKind==='unknown'?{kind:'unknown'}:session.timeKind==='date'?{kind:'date',date:session.date}:{kind:'instant',instant:session.instant,timezone:session.timezone};}
function formatTime(time:BusinessTime){return time.kind==='unknown'?'未知':time.kind==='date'?time.date:time.instant+' ('+time.timezone+')';}
function conditionSummary(conditions:Conditions){return Object.entries(fields).map(([key,label])=>{const field=conditions[key as keyof Values];return `${label}：${field.kind==='known'?field.value:'未知'}`;}).join('；');}
export interface OfferPageProps {purgeNotice?:PurgeNotice;opportunityId:string;workspaceInstance:string;request(input:Request):Promise<Result>;onChanged?():void;sources?:RawSummary[];sourcesError?:boolean;}
export function OfferPage({purgeNotice,opportunityId,workspaceInstance,request,onChanged,sources,sourcesError}:OfferPageProps){
 const [editing,setEditing]=useState(false);
 const key=workspaceInstance+':'+opportunityId;const active=useRef(key);active.current=key;const send=useRef(request);send.current=request;
 const [sessions,setSessions]=useState<Record<string,Session>>({});const session=sessions[key]??initial();
 function update(target:string,change:(session:Session)=>Session){setSessions(previous=>({...previous,[target]:change(previous[target]??initial())}));}
 function patch(value:Partial<Session>){update(key,session=>({...session,...value}));}
 function adopt(target:string,result:Extract<Result,{kind:'offer'|'empty'}>,status:string){update(target,current=>({...current,loaded:true,offer:result.kind==='offer'?result.offer:undefined,opportunity:result.opportunity,values:valuesOf(result.kind==='offer'?result.offer:undefined),original:originalOf(result.kind==='offer'?result.offer:undefined),reason:'',timeKind:'unknown',date:'',instant:'',timezone:'',historical:false,mode:'correction',busy:false,pending:undefined,missing:false,server:undefined,history:undefined,status}));}
 useEffect(()=>{const target=key;let alive=true;update(target,current=>current.loaded?current:{...current,status:'正在读取 Offer'});void (async()=>{try{const result=Result.parse(await send.current({operation:'offer.read',opportunityId}));if(!alive)return;if(result.kind==='offer'||result.kind==='empty'){setSessions(previous=>{const existing=previous[target];if(existing?.loaded)return previous;return {...previous,[target]:{...initial(),loaded:true,offer:result.kind==='offer'?result.offer:undefined,opportunity:result.opportunity,values:valuesOf(result.kind==='offer'?result.offer:undefined),original:originalOf(result.kind==='offer'?result.offer:undefined),status:'已读取'}};});}else update(target,current=>({...current,status:'Offer 读取失败；不会把失败当成尚无 Offer。'}));}catch{if(alive)update(target,current=>({...current,status:'Offer 读取失败；输入保留。'}));}})();return ()=>{alive=false;};},[key]);
 useEffect(()=>{const guard=(event:BeforeUnloadEvent)=>{if(Object.values(sessions).some(session=>dirty(session)||!!session.pending)){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[sessions]);
 useEffect(()=>{if(!purgeNotice)return;setSessions(old=>Object.fromEntries(Object.entries(old).map(([id,value])=>wasPurged(purgeNotice,'offer',value.offer?.id)?[id,{...initial(),loaded:true,status:'这份Offer已永久清除，旧条件与历史已关闭。'}]:[id,value])));},[purgeNotice?.sequence]);
 async function compare(target=key){try{const result=Result.parse(await send.current({operation:'offer.read',opportunityId}));if(result.kind==='offer'||result.kind==='empty')update(target,current=>({...current,server:result,status:'冲突：草稿保留，请比较当前正式值。'}));else update(target,current=>({...current,status:'当前正式值暂不可读；草稿保留。'}));}catch{update(target,current=>({...current,status:'当前正式值读取失败；草稿保留。'}));}}
 async function handleResult(target:string,result:Result,intent:Request){
  if(result.kind==='offer'||result.kind==='empty'){
   adopt(target,result,'保存成功');if(active.current!==target)return;onChanged?.();
   // The receipt is already durable; a follow-up read failure is not a failed save.
   try{const fresh=Result.parse(await send.current({operation:'offer.read',opportunityId:result.opportunity.id}));if(fresh.kind!=='offer'&&fresh.kind!=='empty')throw Error('read');update(target,current=>({...current,...fresh.opportunity.revision!==result.opportunity.revision||fresh.kind==='offer'&&result.kind==='offer'&&fresh.offer.revision!==result.offer.revision?{server:fresh,status:'保存成功；正式值已有后续变化，请比较后采用。'}:{status:'保存成功'}}));}catch{update(target,current=>({...current,status:'保存成功；后续回读失败，可稍后重读。'}));}
  }else if(result.kind==='receipt_missing')update(target,current=>({...current,busy:false,missing:true,status:'确认尚未保存；可明确继续这次保存。'}));
  else if(result.kind==='failure'){
   update(target,current=>({...current,busy:false,pending:undefined,missing:false,status:result.code==='conflict'?'保存冲突；草稿保留。':result.code==='accepted_conditions_protected'?'已接受条件受到保护：误接受请先明确纠正该接受记录，真实条件变化请走正式新条件替代。':result.code==='source_unavailable'?'原件当前保存或读取失败，未保存；不能改称历史丢失。':`保存未完成；输入保留，请检查后继续。`}));if(result.code==='conflict')await compare(target);
  }
 }
 async function run(intent:Request){const target=key;patch({busy:true,pending:intent,missing:false,status:'保存中'});try{const result=Result.parse(await send.current(intent));await handleResult(target,result,intent);}catch{update(target,current=>({...current,busy:false,status:'结果暂时无法确认；请检查是否已保存，输入保留。'}));}}
 function submit(operation:'offer.receive'|'offer.correct'|'offer.replace'|'offer.accept'|'offer.withdraw'|'offer.correct-acceptance'|'offer.correct-withdrawal',extras:Record<string,unknown>={}){
  if(!session.opportunity||session.busy||session.pending)return;if(['offer.withdraw','offer.correct-acceptance','offer.correct-withdrawal'].includes(operation)&&!window.confirm('确认记录这次Offer撤回或纠错？这会改变当前机会结果，历史仍保留。'))return;
  if((operation==='offer.accept'||operation==='offer.withdraw'||operation==='offer.correct-acceptance'||operation==='offer.correct-withdrawal')&&contentDirty(session)){patch({status:'条件草稿尚未保存；请先保存或明确取消条件编辑。'});return;}
  const source=sources?.find(source=>source.id===session.original.objectId);
  const original=session.original.kind==='retained'?{kind:'retained',source:source?.source}:{kind:session.original.kind,explanation:session.original.explanation};
  const parsed=Request.safeParse({operation,commandId:crypto.randomUUID(),opportunityId,expectedOpportunityRevision:session.opportunity.revision,...operation!=='offer.receive'?{expectedRevision:session.offer?.revision}:{},businessTime:timeOf(session),reason:session.reason,...operation==='offer.receive'||operation==='offer.replace'?{conditions:conditionsOf(session.values),original}:{},...operation==='offer.correct'?{conditions:conditionsOf(session.values)}:{},...operation==='offer.accept'||operation==='offer.withdraw'||operation==='offer.replace'?{historical:session.historical}:{},...extras});
  if(!parsed.success){patch({status:'请填写变化说明、必要原件说明及合法实际时间；未知条件和日期可保持未知。'});return;}void run(parsed.data);
 }
 async function history(){const target=key;try{const result=Result.parse(await send.current({operation:'offer.history',opportunityId}));if(result.kind==='history')update(target,current=>({...current,history:{events:result.events,acceptances:result.acceptances},status:'历史已读取'}));else patch({status:'历史暂不可读；既有历史与输入保留。'});}catch{update(target,current=>({...current,status:'历史读取失败；既有历史与输入保留。'}));}}
 const disabled=session.busy||!!session.pending;const originalEditable=!session.offer||session.mode==='replacement';
 return <section className="section-view aura-owner-section" aria-label="Offer"><h2>Offer</h2><p>只记录现实已经收到的条件。没有投递或面试也可记录；不会自动创建任职。空条件明确表示未知，不从 JD 猜测。</p>
 {!session.loaded?<><p role="alert">{session.status}</p><button className="button" onClick={()=>void compare()}>刷新 Offer</button></>:<>
 {!session.offer?<p>现实收到 Offer 后在这里记录条件和原件。</p>:<p>当前条件{session.offer.valid?'有效':'已撤回，无当前有效条件'}；机会结果：{session.opportunity?resultLabel[session.opportunity.result]:'读取中'}；收到时间：{formatTime(session.offer.receivedAt)}</p>}
 {session.offer&&<article className="record-row" aria-label="当前 Offer 条件"><h3>当前条件</h3><p>{conditionSummary(session.offer.conditions)}</p><p>原件：{session.offer.original.kind==='retained'?session.offer.original.name:session.offer.original.kind==='never_existed'?'现实从未有原件':'历史原件已丢失'}</p><p>接受状态：{session.opportunity?.result==='accepted'?'已记录接受':'尚未记录接受当前有效条件'}</p></article>}<button className="button primary" disabled={disabled} onClick={()=>setEditing(true)}>{session.offer?'修改条件':'记录 Offer'}</button>{session.offer?.valid&&session.opportunity?.result!=='accepted'&&<button className="button" onClick={()=>setEditing(true)}>记录接受决定</button>}
 <fieldset hidden={!editing} disabled={disabled}><legend>明确当前条件</legend>{Object.entries(fields).map(([name,label])=><label key={name}>{label}<input aria-label={label} maxLength={4000} value={session.values[name as keyof Values]} onChange={event=>patch({values:{...session.values,[name]:event.target.value}})}/><small>留空表示未知</small></label>)}
 {session.offer&&<label className="field">条件保存含义<select value={session.mode} onChange={event=>patch({mode:event.target.value as Session['mode']})}><option value="correction">纠正笔误或原记录错误（同一条件）</option><option value="replacement">招聘方正式用新条件替代（新条件待决定）</option></select></label>}
 <fieldset disabled={!originalEditable}><legend>原件实际状态</legend><label className="field">原件状态<select value={session.original.kind} onChange={event=>patch({original:{...session.original,kind:event.target.value as OriginalForm['kind']}})}><option value="never_existed">现实从未有原件</option><option value="historically_lost">历史原件已经丢失</option><option value="retained" disabled={!sources?.length||sourcesError}>已有保存的原件</option></select></label>{session.original.kind==='retained'?<label className="field">明确选择既有原件<select value={session.original.objectId} onChange={event=>patch({original:{...session.original,objectId:event.target.value}})}><option value="">选择已保存材料</option>{sources?.map(source=><option key={source.id} value={source.id}>{source.name}</option>)}</select></label>:<label className="field">原件说明<input value={session.original.explanation} maxLength={1000} onChange={event=>patch({original:{...session.original,explanation:event.target.value}})}/></label>}{sourcesError&&<p role="alert">原件列表读取失败；不会自动改称“无原件”或“历史丢失”。</p>}{!sources&&!sourcesError&&<p>本入口尚无可选择原件列表；已有原件请先在材料入口保存并重读，不能手填或伪造。</p>}
 </fieldset>
 <label className="field">变化说明<input value={session.reason} maxLength={1000} onChange={event=>patch({reason:event.target.value})}/></label><label className="field">实际业务时间<select value={session.timeKind} onChange={event=>patch({timeKind:event.target.value as Session['timeKind']})}><option value="unknown">未知（不补今天）</option><option value="date">只知道实际日期</option><option value="instant">知道时刻和原时区</option></select></label>{session.timeKind==='date'&&<label className="field">实际日期<input type="date" value={session.date} onChange={event=>patch({date:event.target.value})}/></label>}{session.timeKind==='instant'&&<><label className="field">精确时刻（含偏移）<input value={session.instant} onChange={event=>patch({instant:event.target.value})}/></label><label className="field">原事件时区<input value={session.timezone} onChange={event=>patch({timezone:event.target.value})}/></label></>}
 {!session.offer?<button className="button" onClick={()=>submit('offer.receive')}>确认现实收到 Offer</button>:<>{session.mode==='correction'?<button className="button" onClick={()=>submit('offer.correct')}>纠正当前条件记录</button>:<button className="button" onClick={()=>submit('offer.replace')}>确认正式新条件替代</button>}<button className="button" disabled={!session.offer.valid&&!session.historical||contentDirty(session)} onClick={()=>submit('offer.accept')}>接受当前有效条件</button><details><summary>晚录 / 撤回</summary><label className="field"><input type="checkbox" checked={session.historical} onChange={event=>patch({historical:event.target.checked})}/>晚录旧条件、接受或撤回（不覆盖后来当前条件和结果）</label><button className="button" disabled={contentDirty(session)} onClick={()=>submit('offer.withdraw',{by:'recruiter'})}>确认招聘方撤回</button><button className="button" disabled={contentDirty(session)} onClick={()=>submit('offer.withdraw',{by:'user'})}>确认用户退出 Offer</button></details></>}
 </fieldset>
 <button className="button" hidden={!editing} disabled={disabled} onClick={()=>{if(dirty(session)&&!window.confirm('明确取消未保存的条件与事件输入？'))return;if(session.opportunity)adopt(key,session.offer?{kind:'offer',offer:session.offer,opportunity:session.opportunity}:{kind:'empty',opportunity:session.opportunity},'已取消输入');}}>取消未保存输入</button><details><summary>更多 / 历史 / 纠错</summary><button className="button" disabled={disabled} onClick={()=>void compare()}>刷新正式内容（保留输入）</button><button className="button" disabled={disabled} onClick={()=>void history()}>查看接受依据与历史</button></details>
 </>}
 <p role="status">{session.status}{dirty(session)?' · 有未保存输入':''}</p>
 {session.pending&&'commandId'in session.pending&&<><button className="button" disabled={session.busy} onClick={async()=>{const target=key;patch({busy:true});try{await handleResult(target,Result.parse(await send.current({operation:'offer.receipt',commandId:(session.pending as {commandId:string}).commandId})),session.pending!);}catch{update(target,current=>({...current,busy:false,status:'暂时无法确认是否已保存；输入保留，不重复保存。'}));}}}>检查是否已保存</button>{session.missing&&<button className="button" disabled={session.busy} onClick={()=>void run(session.pending!)}>继续这次保存</button>}</>}
 {session.server&&<aside aria-label="Offer 冲突比较"><h3>当前正式条件；你的草稿仍保留</h3><p>{session.server.kind==='offer'?conditionSummary(session.server.offer.conditions):'尚无正式 Offer'}</p><p>当前机会结果：{resultLabel[session.server.opportunity.result]}</p><button className="button" onClick={()=>patch({loaded:true,offer:session.server?.kind==='offer'?session.server.offer:undefined,opportunity:session.server!.opportunity,server:undefined,status:'采用了正式新基线；草稿保留，请明确保存。'})}>采用正式基线并保留草稿</button><button className="button" onClick={()=>{if(!dirty(session)||window.confirm('明确放弃输入并采用正式值？'))adopt(key,session.server!,'已读取正式值');}}>放弃草稿并采用正式值</button></aside>}
 {session.history&&<aside aria-label="Offer 接受依据与历史"><h3>不可变接受依据</h3>{session.history.acceptances.length===0?<p>尚无接受历史</p>:session.history.acceptances.map(basis=><article key={basis.id}><p>{conditionSummary(basis.conditions)}</p><p>接受时间：{formatTime(basis.acceptedAt)}；录入时间：{basis.recordedAt}</p><p>当时原件：{basis.original.kind==='retained'?basis.original.name:basis.original.kind==='never_existed'?'从未有原件：'+basis.original.explanation:'历史丢失：'+basis.original.explanation}</p><button className="button" disabled={disabled||contentDirty(session)} onClick={()=>submit('offer.correct-acceptance',{coreEventId:basis.coreEventId})}>纠正此误接受记录</button></article>)}<h3>现实变化与明确纠错</h3>{session.history.events.map(event=><article key={event.id}><p>{event.type} · {event.reason} · 实际时间 {formatTime(event.businessTime)} · 录入时间 {event.recordedAt}{event.historical?' · 历史晚录':''}</p>{(event.type==='recruiter_withdrew'||event.type==='user_withdrew')&&event.coreEventId&&<button className="button" disabled={disabled||contentDirty(session)} onClick={()=>submit('offer.correct-withdrawal',{coreEventId:event.coreEventId})}>纠正此误撤回记录</button>}{event.conditions&&<p>{conditionSummary(event.conditions)}</p>}{event.type==='conditions_replaced'&&event.historical&&<button className="button" disabled={disabled||contentDirty(session)} onClick={()=>submit('offer.accept',{historical:true,conditionsId:event.conditionsId})}>补录这些历史条件的接受</button>}</article>)}</aside>}
 </section>;
}
