import {useEffect,useRef,useState} from 'react';
import {Result,type Draft,type Request} from '../../../../contracts/opportunity/communication/schema';
import {wasPurged,type PurgeNotice} from '../../../design-system/purge-notice';
interface State {draft?:Draft;text:string;dirty:boolean;pending?:Extract<Request,{operation:'communication.draft.save'}>;busy:boolean;comparison?:Draft;notice:string}
const empty=():State=>({text:'',dirty:false,busy:false,notice:'尚未读取'});
/** An editable current draft is separate from a record of a real communication. */
export function GreetingDraft({opportunityId,request,purgeNotice}:{opportunityId:string;request(input:Request):Promise<unknown>;purgeNotice?:PurgeNotice}){
 const [states,setStates]=useState<Record<string,State>>({}),state=states[opportunityId]??empty(),latest=useRef(states),epoch=useRef(0),composing=useRef(false);latest.current=states;
 const patch=(id:string,value:Partial<State>)=>setStates(old=>({...old,[id]:{...(old[id]??empty()),...value}}));
 async function read(id=opportunityId){const generation=epoch.current;try{const result=Result.parse(await request({operation:'communication.draft.read',opportunityId:id}));if(generation!==epoch.current)return;if(result.kind==='draft'){const previous=latest.current[id];if(previous?.dirty||previous?.pending){if(result.draft.revision!==previous.draft?.revision)patch(id,{comparison:result.draft,notice:'正式草稿有变化；保留你的未保存输入，请比较。'});}else patch(id,{draft:result.draft,text:result.draft.text,notice:'当前草稿已读取；没有标记成已发送。'});}}catch{patch(id,{notice:'读取失败，保留当前输入。'});}}
 useEffect(()=>{void read();const timer=setInterval(()=>void read(),2000);return()=>clearInterval(timer);},[opportunityId]);
 useEffect(()=>{const guard=(event:BeforeUnloadEvent)=>{if(Object.values(states).some(item=>item.dirty||item.pending)){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[states]);
 useEffect(()=>{if(!purgeNotice)return;epoch.current++;setStates(old=>Object.fromEntries(Object.entries(old).map(([id,value])=>[id,wasPurged(purgeNotice,'communication-draft',id)||wasPurged(purgeNotice,'opportunity',id)?{...empty(),notice:'原草稿已永久清除，旧输入已关闭。'}:value])));},[purgeNotice?.sequence]);
 async function finish(id:string,result:ReturnType<typeof Result.parse>){if(result.kind==='draft')patch(id,{draft:result.draft,text:result.draft.text,dirty:false,pending:undefined,busy:false,comparison:undefined,notice:'草稿已保存；尚未发送，不会创建真实沟通。'});else if(result.kind==='receipt_missing')patch(id,{busy:false,notice:'原回执未找到；可明确继续同一个命令。'});else if(result.kind==='failure'){patch(id,{pending:undefined,busy:false,notice:'未生效：'+result.code+'；输入保留。'});if(result.code==='conflict')await read(id);}}
 async function run(input:Extract<Request,{operation:'communication.draft.save'}>,receipt=false){const id=input.opportunityId,generation=epoch.current;patch(id,{busy:true,pending:input});try{const result=Result.parse(await request(receipt?{operation:'communication.draft.receipt',commandId:input.commandId}:input));if(generation===epoch.current)await finish(id,result);}catch{if(generation===epoch.current)patch(id,{busy:false,notice:'结果未知；请核对原回执，不重复创建。'});}}
 return <section aria-label="当前 Greeting 草稿" onCompositionStart={()=>{composing.current=true;}} onCompositionEnd={()=>{composing.current=false;}}><h3>当前 Greeting / 沟通草稿</h3><p>可独立编辑、保存；AI 采用也只更新草稿。实际发送后另行记录真实沟通。</p><textarea aria-label="当前 Greeting 草稿正文" disabled={state.busy||!!state.pending} value={state.text} onChange={event=>patch(opportunityId,{text:event.target.value,dirty:true})}/><button disabled={!state.draft||state.busy||!!state.pending} onClick={()=>{if(composing.current)return;void run({operation:'communication.draft.save',commandId:crypto.randomUUID(),opportunityId,expectedRevision:state.draft!.revision,text:state.text});}}>保存当前草稿（未发送）</button><button disabled={state.busy||!!state.pending} onClick={()=>void read()}>重读草稿并保留输入</button>{state.comparison&&<aside><pre>{state.comparison.text}</pre><button onClick={()=>patch(opportunityId,{draft:state.comparison,comparison:undefined})}>采用新基线并保留我的草稿</button><button onClick={()=>patch(opportunityId,{draft:state.comparison,text:state.comparison!.text,dirty:false,comparison:undefined})}>明确放弃本地输入，采用正式草稿</button></aside>}{state.pending&&!state.busy&&<><button onClick={()=>void run(state.pending!,true)}>核对原草稿回执</button>{state.notice.includes('未找到')&&<button onClick={()=>void run(state.pending!)}>明确继续原草稿命令</button>}</>}<p role="status">{state.notice}{state.dirty?' · 未保存输入':''}</p></section>;
}
