import React,{useState,useEffect,useRef} from 'react';
import {Request,Result,type Communication} from '../../../../contracts/opportunity/communication/schema';
import {SendingFields,TimeFields,formatSendingTime,initialSendingForm,sendingValues,type SendingForm,type SendCandidate} from '../submission/fields';
interface Session {loaded:boolean;items:Communication[];text:string;medium:'text'|'phone'|'other';purpose:'general'|'salary'|'offer_followup'|'preemployment'|'resend';form:SendingForm;selected?:Communication;status:string;dirty:boolean;pending?:Request;busy:boolean;receiptMissing?:boolean;candidates:SendCandidate[];server?:Communication}
const initial=():Session=>({loaded:false,items:[],text:'',medium:'text',purpose:'general',form:initialSendingForm(),status:'正在读取沟通',dirty:false,busy:false,candidates:[]});
export function CommunicationPage({workspaceInstance,opportunityId,request,candidates=[],selectActual,onChanged}:{workspaceInstance:string;opportunityId:string;request(input:Request):Promise<unknown>;candidates?:SendCandidate[];selectActual?:()=>Promise<SendCandidate|undefined>;onChanged?:()=>void}){
 const key=`${workspaceInstance}:${opportunityId}`;const [sessions,setSessions]=useState<Record<string,Session>>({});const session=sessions[key]??initial();const send=useRef(request);send.current=request;const active=useRef(key);active.current=key;const composing=useRef(false);
 function update(target:string,values:Partial<Session>){setSessions(old=>({...old,[target]:{...(old[target]??initial()),...values}}));}
 function patchForm(values:Partial<SendingForm>){update(key,{form:{...session.form,...values},dirty:true});}
 async function list(target=key,id=opportunityId){try{const result=Result.parse(await send.current({operation:'communication.list',opportunityId:id}));if(result.kind==='list')update(target,{loaded:true,items:result.items,status:'沟通列表已读取；草稿保留。'});else update(target,{status:'沟通列表暂不可读；不会视作空列表。'});}catch{update(target,{status:'沟通读取失败；输入保留。'});}}
 useEffect(()=>{if(!sessions[key]?.loaded)void list(key);},[key]);
 useEffect(()=>{const guard=(event:BeforeUnloadEvent)=>{if(Object.values(sessions).some(value=>value.dirty||value.pending)){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[sessions]);
 const allCandidates=[...candidates,...session.candidates].filter((item,index,all)=>all.findIndex(other=>other.id===item.id&&other.kind===item.kind)===index);
 async function applyResult(target:string,result:Result,id:string){if(result.kind==='saved'){update(target,{pending:undefined,busy:false,dirty:false,selected:undefined,text:'',form:initialSendingForm(),status:'真实沟通已保存；不会自动创建面试或 Offer。'});if(active.current===target)onChanged?.();await list(target,id);}else if(result.kind==='purged'){update(target,{pending:undefined,busy:false,dirty:false,text:'',selected:undefined,status:'原沟通内容已永久清除；原命令不会重建正文。'});await list(target,id);}else if(result.kind==='failure')update(target,{pending:undefined,busy:false,status:`保存失败：${result.code}。草稿保留，请重读并明确比较；不自动重试。`});else if(result.kind==='receipt_missing')update(target,{busy:false,receiptMissing:true,status:'原回执未找到，可继续原命令。'});}
 async function run(intent:Request,target=key,id=opportunityId){update(target,{pending:intent,busy:true,receiptMissing:false,status:'正在保存真实沟通'});try{const result=Result.parse(await send.current(intent));await applyResult(target,result,id);if(result.kind==='failure'&&result.code==='conflict'&&'id'in intent){const current=Result.parse(await send.current({operation:'communication.read',id:intent.id}));if(current.kind==='communication')update(target,{server:current.communication,status:'沟通保存冲突；你的正文保留，请比较当前正式记录。'});}}catch{update(target,{busy:false,status:'结果待核对；原命令与输入保留。'});}}
 function submit(){if(session.busy||session.pending||composing.current)return;const values=sendingValues(session.form,allCandidates);const shared={commandId:crypto.randomUUID(),businessTime:values.businessTime,reason:values.reason};const parsed=Request.safeParse(session.selected?{operation:'communication.correct',...shared,id:session.selected.id,expectedRevision:session.selected.revision,text:session.text}:session.purpose==='resend'?{operation:'communication.resend',...shared,opportunityId,text:session.text,resume:values.resume,greeting:values.greeting,historical:values.historical}:{operation:'communication.record',...shared,opportunityId,text:session.text,medium:session.medium,purpose:session.purpose,historical:values.historical});if(!parsed.success){update(key,{status:'请填写真实沟通正文、记录说明和必要材料状态；时间未知可以明确保持未知。'});return;}void run(parsed.data);}
 function select(item:Communication){if(session.dirty){update(key,{status:'当前草稿尚未保存；先明确取消，不能静默覆盖。'});return;}const form=initialSendingForm();if(item.businessTime.kind==='date'){form.timeKind='date';form.date=item.businessTime.date;}if(item.businessTime.kind==='instant'){form.timeKind='instant';form.instant=item.businessTime.instant;form.timezone=item.businessTime.timezone;}update(key,{selected:item,text:item.text,medium:item.medium,purpose:item.purpose,form,status:'明确更正同一沟通正文；不保存被替换的旧全文。'});}
 async function choose(){const target=key;if(!selectActual)return;update(target,{busy:true});try{const item=await selectActual();setSessions(old=>{const state=old[target]??initial();return {...old,[target]:{...state,busy:false,...item?{candidates:[...state.candidates,item],form:{...state.form,resumeKind:'retained',candidateKey:`${item.kind}:${item.id}`},dirty:true,status:'实际文件已准备；仍需确认真实补发。'}:{status:'取消文件选择；输入保留。'}}};});}catch{update(target,{busy:false,status:'实际文件保存失败；不能改称历史文件缺失。'});}}
 const disabled=session.busy||!!session.pending;
 return <section aria-label="沟通记录" onCompositionStart={()=>{composing.current=true;}} onCompositionEnd={()=>{composing.current=false;}}><h2>沟通与后续材料发送</h2><p>记录文字、电话、谈薪、Offer 后续和报到联系。正文提到面试或 Offer 不等于确认真实活动。</p>{session.loaded&&<fieldset disabled={disabled}><legend>{session.selected?'更正原沟通记录':'记录真实沟通'}</legend><label>沟通方式<select aria-label="沟通方式" disabled={!!session.selected} value={session.medium} onChange={event=>update(key,{medium:event.target.value as Session['medium'],dirty:true})}><option value="text">文字</option><option value="phone">电话</option><option value="other">其他真实沟通</option></select></label><label>沟通用途<select aria-label="沟通用途" disabled={!!session.selected} value={session.purpose} onChange={event=>update(key,{purpose:event.target.value as Session['purpose'],dirty:true})}><option value="general">一般沟通</option><option value="salary">谈薪</option><option value="offer_followup">Offer 后续</option><option value="preemployment">入职前沟通</option><option value="resend">首次投递后的再次发送</option></select></label><label>沟通正文<textarea aria-label="沟通正文" value={session.text} onChange={event=>update(key,{text:event.target.value,dirty:true})}/></label>{session.purpose==='resend'&&!session.selected?<SendingFields form={session.form} patch={patchForm} candidates={allCandidates} selectActual={selectActual?()=>void choose():undefined}/>:<TimeFields form={session.form} patch={patchForm}/>}<button onClick={submit}>{session.selected?'明确更正沟通正文':session.purpose==='resend'?'确认再次发送材料':'保存真实沟通'}</button><button onClick={()=>update(key,{selected:undefined,text:'',form:initialSendingForm(),dirty:false,status:'已明确取消当前草稿'})}>明确取消当前草稿</button></fieldset>}
 {session.server&&<aside aria-label="沟通冲突比较"><h3>当前正式沟通；草稿保留</h3><p>{session.server.text}</p><button disabled={disabled} onClick={()=>update(key,{selected:session.server,server:undefined,status:'已采用当前正式版本基线；你的正文仍保留，请明确保存。'})}>采用沟通新基线并保留草稿</button></aside>}
 <button disabled={disabled} onClick={()=>void list()}>重读沟通列表并保留草稿</button><p role="status">{session.status}{session.dirty?' · 有未保存输入':''}</p>{session.pending&&'commandId'in session.pending&&<><button disabled={session.busy} onClick={async()=>{const target=key;update(target,{busy:true});try{await applyResult(target,Result.parse(await send.current({operation:'communication.receipt',commandId:(session.pending as {commandId:string}).commandId})),opportunityId);}catch{update(target,{busy:false,status:'回执核对失败；原意图保留。'});}}}>核对原沟通回执</button>{session.receiptMissing&&<button onClick={()=>void run(session.pending!)}>继续原沟通保存意图</button>}</>}
 {session.items.map(item=><article key={item.id}><p>{item.medium} · {item.purpose} · {item.historical?'晚补历史':'真实后续'} · {item.archived?'已归档':'当前记录'}</p><p>{item.text}</p><p>实际业务时间 {formatSendingTime(item.businessTime)}；来源版本 {item.source.revision}；录入时间 {item.recordedAt}</p>{item.sentMaterial&&<p>当时补发材料：{item.sentMaterial.kind==='retained'?item.sentMaterial.name:item.sentMaterial.kind}</p>}<button disabled={disabled} onClick={()=>select(item)}>更正此沟通正文</button><button disabled={disabled||session.dirty} onClick={()=>void run({operation:'communication.archive',commandId:crypto.randomUUID(),id:item.id,expectedRevision:item.revision,archived:!item.archived,reason:item.archived?'恢复到当前视图':'退出当前列表；保留来源引用'})}>{item.archived?'恢复此沟通':'归档此沟通（不清除来源）'}</button></article>)}
 </section>;
}
