import {useEffect,useRef,useState} from 'react';
import {Request,Result,type Content,type Proposal,type Target,type Task} from '../../../contracts/ai/schema';
import type {SourceRef} from '../../../contracts/common/source-ref';
export interface AiPageProps {request(input:Request):Promise<Result>;sources():Promise<{ref:SourceRef;name:string}[]>;targets?:{target:Target;label:string}[];workspaceInstance?:string;onApplied?():void}
const defaultTargets:{target:Target;label:string}[]=[{target:{scope:'personal'},label:'个人 Wiki'},{target:{scope:'cognition'},label:'长期认知 Wiki'}];
const operationLabels={not_sent:'尚未发送',dispatching:'进入派发',processing:'处理中',success:'已知成功',failure:'明确失败',outcome_unknown:'外部结果未知'};
export function WikiAiPage({request,sources,targets=defaultTargets,workspaceInstance='',onApplied}:AiPageProps){
 const [choices,setChoices]=useState<{ref:SourceRef;name:string}[]>([]),[selected,setSelected]=useState<string[]>([]),[targetIndex,setTargetIndex]=useState(0),[task,setTask]=useState<Task>(),[history,setHistory]=useState<Task[]>([]),[message,setMessage]=useState('只使用本地 deterministic fake；无真实外发，无 Key。'),[busy,setBusy]=useState(false),[requests,setRequests]=useState(1);
 const [pending,setPending]=useState<Request>();
 const epoch=useRef(0);
 const taskRef=useRef(task);taskRef.current=task;
 async function load(){const generation=epoch.current;try{const [materials,result]=await Promise.all([sources(),request({operation:'ai.list'})]);if(generation!==epoch.current)return;setChoices(materials);if(result.kind==='tasks')setHistory(result.tasks);else setMessage('任务列表暂不可读。');}catch{if(generation===epoch.current)setMessage('读取失败，当前输入保留。');}}
 useEffect(()=>{epoch.current++;setTask(undefined);setSelected([]);void load();return()=>{epoch.current++;};},[workspaceInstance]);
 useEffect(()=>{const timer=setInterval(async()=>{const current=taskRef.current;if(!current)return;const generation=epoch.current;try{const result=Result.parse(await request({operation:'ai.read',taskId:current.id}));if(generation===epoch.current&&result.kind==='task')setTask(result.task);}catch{/* Retain the existing review/draft and task identity. */}},1000);return()=>clearInterval(timer);},[request]);
 async function run(input:Request){if(busy)return;setBusy(true);const generation=epoch.current;try{const response=Result.parse(await request(input));if(generation!==epoch.current)return;const result=response.kind==='receipt'?response.receipt:response;setPending(undefined);if(result.kind==='task'){setTask(result.task);setMessage('任务状态已读取；模型输出仍须人工逐条采用。');}else if(result.kind==='decided'){setMessage(result.state==='accepted'?'本条已立即生效；采纳不等于独立核验。':result.state==='pending'?'本次忽略，仍可处理。':'已拒绝本条。');if(result.state==='accepted')onApplied?.();if(taskRef.current){const refreshed=await request({operation:'ai.read',taskId:taskRef.current.id});if(generation===epoch.current&&refreshed.kind==='task')setTask(refreshed.task);}}else if(result.kind==='failure')setMessage('未生效：'+result.code+'。编辑输入保留。');else if(result.kind==='receipt_missing')setMessage('尚未找到原命令回执；不自动重发。');await load();}catch{if(generation===epoch.current){setPending(input);setMessage('结果读取未知，请核对原命令回执；不会自动重发。');}}finally{setBusy(false);}}
 async function prepare(){const target=targets[targetIndex]?.target;if(!target||!selected.length){setMessage('请明确选择材料和 Wiki 目标。');return;}await run({operation:'ai.prepare',commandId:crypto.randomUUID(),sources:choices.filter(item=>selected.includes(item.ref.objectId)).map(item=>item.ref),target,budget:{requests,inputBytes:524288,outputBytes:196608}});}
 return <section aria-label="Wiki AI 整理"><h2>Wiki 整理</h2><p>只有明确选中材料会用于本地整理。准备不等于发送，发送不等于修改 Wiki。</p>
 <fieldset disabled={busy}><legend>选定本次资料和目标</legend><button onClick={()=>void load()}>刷新材料 / 任务</button>{choices.map(item=><label key={item.ref.objectId}><input type="checkbox" checked={selected.includes(item.ref.objectId)} onChange={event=>setSelected(event.target.checked?[...selected,item.ref.objectId]:selected.filter(id=>id!==item.ref.objectId))}/>{item.name} · {item.ref.owner} · v{item.ref.revision}</label>)}
 <label>Wiki 目标<select value={targetIndex} onChange={event=>setTargetIndex(Number(event.target.value))}>{targets.map((item,index)=><option key={JSON.stringify(item.target)} value={index}>{item.label}</option>)}</select></label><label>根任务请求上限<input type="number" min={1} max={10} value={requests} onChange={event=>setRequests(Number(event.target.value))}/></label><p>每次输入最多 512 KiB，输出最多 192 KiB；全任务最多 {requests} 次，累计上界分别为 {requests*512} / {requests*192} KiB。fake 无费用；未知请求仍占次数。</p><button onClick={()=>void prepare()}>准备本地 Context / 最终发送预览</button></fieldset>
 <p role="status">{message}</p>{pending&&'commandId'in pending&&<button disabled={busy} onClick={()=>void run({operation:'ai.receipt',commandId:pending.commandId})}>核对原命令回执</button>}<ul aria-label="已有整理任务">{history.map(item=><li key={item.id}><button onClick={()=>{epoch.current++;setTask(item);}}>{item.target.scope} · {item.state} · {item.id.slice(0,8)}</button></li>)}</ul>
 {task&&<article aria-label="AI 任务状态"><p>任务 {task.id} · {task.state} · 已预留 {task.usedRequests}/{task.budget.requests} 次</p><button disabled={busy} onClick={()=>void run({operation:'ai.stop',commandId:crypto.randomUUID(),taskId:task.id,mode:'stop'})}>停止后续执行</button><button disabled={busy} onClick={()=>void run({operation:'ai.stop',commandId:crypto.randomUUID(),taskId:task.id,mode:'revoke'})}>撤销执行及迟到内容保留</button>
 {task.operations.map(operation=><section key={operation.id} aria-label="单次外发操作"><h3>{operationLabels[operation.state]} · {operation.id.slice(0,8)}</h3>{operation.reason&&<p>{operation.reason}</p>}{operation.manifest&&<><h4>最终实际发送内容</h4><p>接收方 {operation.manifest.recipient.service} / {operation.manifest.recipient.endpoint} / {operation.manifest.recipient.account} / {operation.manifest.recipient.model} · 全文粒度 · 在 handoff 之前可停止</p><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(operation.manifest,null,2)}</pre>{operation.state==='not_sent'&&<button disabled={busy} onClick={()=>void run({operation:'ai.authorize',commandId:crypto.randomUUID(),operationId:operation.id,manifestDigest:operation.manifestDigest})}>授权这份最终请求（本地 fake，无真实外发）</button>}</>}{operation.state==='outcome_unknown'&&<><p>超时不等于失败，原请求仍可能产生费用和迟到结果；不会自动重发。</p><button disabled={busy} onClick={()=>void run({operation:'ai.retry-explicit',commandId:crypto.randomUUID(),taskId:task.id,acknowledgeUnknown:true})}>明确准备新的请求 B（保留 A 未知状态）</button></>}</section>)}
 {task.contentAvailability==='some_unavailable'&&<p role="alert">部分正文因当前来源权限不可读取；缓存和旧回执不能绕过权限。</p>}{task.state==='completed'&&task.proposals.length===0&&task.contentAvailability!=='some_unavailable'&&<p>正常完成：零修改。</p>}{task.proposals.map(proposal=><ProposalCard key={proposal.id} proposal={proposal} busy={busy} decide={(action,edited)=>run({operation:'ai.decide',commandId:crypto.randomUUID(),proposalId:proposal.id,action,...(edited?{edited}:{})})}/>)}</article>}
 </section>;
}
function ProposalCard({proposal,busy,decide}:{proposal:Proposal;busy:boolean;decide(action:'accept'|'edit-accept'|'reject'|'ignore',edited?:Content):Promise<void>}){
 const original=proposal.change.kind==='retire'?undefined:proposal.change.content;
 const [edited,setEdited]=useState<Content|undefined>(original),[editing,setEditing]=useState(false);
 return <article aria-label="Wiki 待审建议"><h3>{proposal.change.kind==='retire'?'退役':original?.title} · {proposal.state} · {proposal.validity}</h3><p>{proposal.change.reason}</p>{proposal.before&&<><h4>改前</h4><pre>{proposal.before.body}</pre></>}{original&&<><h4>改后</h4><pre>{original.body}</pre></>}<p>未核实点：{proposal.change.unknowns.join('；')||'未提供额外说明'}</p><p>解释引用：{proposal.change.citations.join('、')||'无引用'}；实际输入来源 {proposal.provenance.length} 项（引用不会缩小权限来源链）。</p>
 {proposal.state==='pending'&&<><button disabled={busy||proposal.validity!=='current'} onClick={()=>void decide('accept')}>接受本条并立即生效</button>{original&&<button disabled={busy} onClick={()=>setEditing(!editing)}>编辑后接受</button>}<button disabled={busy} onClick={()=>void decide('reject')}>拒绝本条</button><button disabled={busy} onClick={()=>void decide('ignore')}>本次忽略</button>{proposal.ignored&&<p>已忽略，仍可继续处理。</p>}{editing&&edited&&<fieldset disabled={busy}><label>建议标题<input value={edited.title} onChange={event=>setEdited({...edited,title:event.target.value})}/></label><label>建议正文<textarea aria-label="建议正文" value={edited.body} onChange={event=>setEdited({...edited,body:event.target.value})}/></label><label>陈述性质<select value={edited.nature} onChange={event=>setEdited({...edited,nature:event.target.value as Content['nature']})}><option value="fact_statement">事实陈述</option><option value="observation">观察</option><option value="hypothesis">待验证判断</option></select></label><button disabled={proposal.validity!=='current'} onClick={()=>void decide('edit-accept',edited)}>明确采用编辑后的本条</button></fieldset>}</>}
 </article>;
}
