import {useEffect,useRef,useState} from 'react';
import {LegacyHistoryResult,type LegacyProposalHistory,type LegacyHistoryRequest} from '../../../contracts/ai/legacy-history/schema';
import type {PurgeNotice} from '../../design-system/purge-notice';
const status=(item:LegacyProposalHistory)=>item.legacyStatus.kind==='known'?item.legacyStatus.value:'未识别：'+item.legacyStatus.original;
export function LegacyHistoryDetails({item}:{item:LegacyProposalHistory}){
 return <article aria-label="历史 AI 建议详情"><h3>{item.kind==='research'?'Research':'Resume'} · {status(item)}</h3><p>来源：旧 Career · 只读历史</p><p>历史接受仅表示当时采纳，不代表独立核验。</p><p>{item.target.resolution==='unresolved'?'原目标当前无法解析':'原目标已关联正式 owner'}</p>{item.content.availability==='purged'?<p>正文已永久清除，仅保留来源与状态。</p>:<><h4>{item.content.proposal.title}</h4><p style={{whiteSpace:'pre-wrap'}}>{'body'in item.content.proposal?item.content.proposal.body:item.content.proposal.text}</p><dl><dt>原建议类型</dt><dd>{'nature'in item.content.proposal?item.content.proposal.nature:item.content.proposal.changeKind}</dd><dt>原理由</dt><dd>{item.content.basis.reason||'未记录'}</dd><dt>原依据</dt><dd>{item.content.basis.evidence||'未记录'}</dd><dt>来源引用</dt><dd>{item.content.basis.sources.length?item.content.basis.sources.map((s,i)=><p key={i}>{s.sourceType} · {s.legacyIdentity}</p>):'未记录'}</dd></dl></>}<p>原记录时间：{item.recordedAt??'未知'}；归档时间：{item.archivedAt}</p></article>;
}
export function LegacyHistoryView({request,purgeNotice}:{request(input:LegacyHistoryRequest):Promise<unknown>;purgeNotice?:PurgeNotice}){
 const [items,setItems]=useState<LegacyProposalHistory[]>([]),[detail,setDetail]=useState<LegacyProposalHistory>(),[next,setNext]=useState<string>(),[message,setMessage]=useState('正在读取只读历史'),[loadingPage,setLoadingPage]=useState(false);
 const epoch=useRef(0),detailRequest=useRef(0),paging=useRef(false);
 async function list(afterId?:string){if(paging.current)return;paging.current=true;setLoadingPage(true);const generation=epoch.current;try{const result=LegacyHistoryResult.parse(await request({operation:'legacy-history.list',...afterId?{afterId}:{}}));if(generation!==epoch.current||result.kind!=='legacy_history_list')return;setItems(old=>afterId?[...old,...result.items]:result.items);setNext(result.nextAfterId);setMessage(result.items.length?'':'暂无旧 AI 建议历史');}catch{if(generation===epoch.current)setMessage('只读历史暂时不可用，请关闭后重新打开。');}finally{if(generation===epoch.current){paging.current=false;setLoadingPage(false);}}}
 useEffect(()=>{epoch.current++;paging.current=false;setItems([]);setDetail(undefined);setNext(undefined);void list();return ()=>{epoch.current++;};},[purgeNotice]);
 async function read(id:string){const generation=epoch.current,ticket=++detailRequest.current;setDetail(undefined);try{const result=LegacyHistoryResult.parse(await request({operation:'legacy-history.read',id}));if(generation===epoch.current&&ticket===detailRequest.current&&result.kind==='legacy_history')setDetail(result.item);}catch{if(generation===epoch.current&&ticket===detailRequest.current)setMessage('这条历史暂时不可用。');}}
 return <section aria-label="历史 AI 建议"><h2>历史 AI 建议</h2><p>来源：旧 Career · 只读历史；不属于当前待处理任务。</p><p role="status">{message}</p><ul>{items.map(item=><li key={item.id}><button onClick={()=>void read(item.id)}>{item.content.availability==='available'?item.content.proposal.title:'已清除的历史'} · {status(item)}</button></li>)}</ul>{next&&<button disabled={loadingPage} onClick={()=>void list(next)}>查看更多历史</button>}{detail&&<LegacyHistoryDetails item={detail}/>}</section>;
}
