import {useEffect,useState,useRef} from 'react';
import {Result as DataResult} from '../../../contracts/application/schema';
import {Result as InterviewResult,type Session} from '../../../contracts/opportunity/interview/schema';
import {Result as ResearchResult} from '../../../contracts/opportunity/research/schema';
import type {ProductTarget} from '../../../contracts/ai/product-context';
import type {Target} from '../../../contracts/ai/schema';
import type {PurgeNotice} from '../../design-system/purge-notice';
import {ProductTaskPage} from './product-task';
interface Choice {key:string;label:string;target:ProductTarget}
export function ProductTaskLauncher({purgeNotice,onApplied}:{purgeNotice?:PurgeNotice;onApplied():void}){
 const [choices,setChoices]=useState<Choice[]>([]),[key,setKey]=useState(''),[name,setName]=useState(false),[locks,setLocks]=useState<Record<string,boolean>>({}),[session,setSession]=useState<Session>(),[selection,setSelection]=useState<{start:number;end:number}>(),[meaning,setMeaning]=useState(''),[confirmed,setConfirmed]=useState(false),[wikiTarget,setWikiTarget]=useState<Target>({scope:'personal'}),[wikiChoices,setWikiChoices]=useState<{target:Target;label:string}[]>([]),[notice,setNotice]=useState('');
 const epoch=useRef(0);
 useEffect(()=>{if(!purgeNotice)return;epoch.current++;if(session&&purgeNotice.references.some(ref=>ref.owner==='interview'&&ref.objectId===session.id||ref.owner==='opportunity'&&ref.objectId===session.opportunityId)){setSession(undefined);setSelection(undefined);setMeaning('');setConfirmed(false);setKey('');setLocks({});setNotice('相关轮次已永久清除，原文字稿和选段已关闭。');}},[purgeNotice?.sequence]);
 const locked=Object.values(locks).some(Boolean);const protect=(id:string)=>(value:boolean)=>setLocks(old=>old[id]===value?old:{...old,[id]:value});
 async function load(){try{const result=DataResult.parse(await window.career.request('application',{operation:'data.targets'}));if(result.kind!=='data_targets')return;const next:Choice[]=[],add=(label:string,target:ProductTarget)=>next.push({key:JSON.stringify(target),label,target});for(const item of result.targets){if(item.owner==='company'||item.owner==='opportunity')add(item.label+' · 研究整理',{kind:'research-organize',owner:{kind:item.owner,id:item.objectId}});if(item.owner==='opportunity'){add(item.label+' · 沟通草稿',{kind:'greeting',opportunityId:item.objectId,includeName:false});add(item.label+' · Offer 分析',{kind:'offer-assist',opportunityId:item.objectId});const research=ResearchResult.parse(await window.career.request('research',{operation:'read',owner:{kind:'opportunity',id:item.objectId}}));if(research.kind==='document')for(const resolution of research.items)if(resolution.item.active&&resolution.editable){const opportunity=await window.career.request('opportunity',{operation:'read',id:item.objectId});const {Result}=await import('../../../contracts/opportunity/schema');const current=Result.parse(opportunity);if(current.kind==='opportunity')add(resolution.item.title+' · 建议共享为公司研究',{kind:'research-promotion',itemId:resolution.item.id,opportunityId:item.objectId,companyId:current.opportunity.companyId});}}if(item.owner==='interview'){add(item.label+' · 准备草稿',{kind:'interview-preparation',interviewId:item.objectId});add(item.label+' · 终版复盘草稿',{kind:'interview-review',interviewId:item.objectId});}}
 setChoices(next);setWikiChoices([{target:{scope:'personal'},label:'个人 Wiki'},{target:{scope:'cognition'},label:'长期认知 Wiki'},...result.targets.filter(item=>item.owner==='project').map(item=>({target:{scope:'project' as const,scopeId:item.objectId},label:item.label}))]);}catch{setNotice('目标读取失败，现有输入保留。');}}
 useEffect(()=>{void load();},[purgeNotice?.sequence]);
 const chosen=choices.find(choice=>choice.key===key),target=chosen?.target.kind==='greeting'?{...chosen.target,includeName:name}:chosen?.target;
 async function select(value:string){if(locked){setNotice('当前命令或编辑草稿尚待处理，请先核对或完成。');return;}const generation=++epoch.current;setKey(value);setSession(undefined);setSelection(undefined);setMeaning('');setConfirmed(false);const choice=choices.find(item=>item.key===value);if(choice?.target.kind==='interview-review'){const result=InterviewResult.parse(await window.career.request('interview',{operation:'interview.read',id:choice.target.interviewId}));if(generation===epoch.current&&result.kind==='session')setSession(result.session);}}
 return <section aria-label="完整旅程 AI 辅助"><h2>产品任务辅助</h2><p>Resume 优化请从所属简历进入。这里的研究、草稿、复盘和分析均不会替你执行现实动作。</p><button disabled={locked} onClick={()=>void load()}>刷新任务目标</button><label>选择真实任务目标<select aria-label="选择真实任务目标" disabled={locked} value={key} onChange={event=>void select(event.target.value)}><option value="">请选择</option>{choices.map(choice=><option value={choice.key} key={choice.key}>{choice.label}</option>)}</select></label>{target?.kind==='greeting'&&<label><input disabled={locked} type="checkbox" checked={name} onChange={event=>setName(event.target.checked)}/>独立允许署名使用本人姓名（不包括联系方式）</label>}
 {target&&<ProductTaskPage target={target} purgeNotice={purgeNotice} onProtected={protect('primary')} onApplied={()=>{onApplied();void load();}}/>}
 {session?.kind==='real'&&session.finalReview&&<><p>当前真实复盘可单独整理为 Research；不会自动写入。</p><ProductTaskPage target={{kind:'research-organize',owner:{kind:'opportunity',id:session.opportunityId},reviewId:session.id}} purgeNotice={purgeNotice} onProtected={protect('review-research')} onApplied={onApplied}/></>}
 {session?.kind==='simulation'&&session.transcript&&<section aria-label="模拟片段明确回流"><h3>只回流本人确认真实含义的选中片段</h3><p>在下面选中你本人说过且确认是真实经历的文字；模拟面试官的虚构公司条件不能回流为真实研究。</p><textarea aria-label="选择模拟片段" readOnly value={session.transcript.text} onSelect={event=>{if(locked)return;const input=event.currentTarget;setSelection({start:input.selectionStart,end:input.selectionEnd});setConfirmed(false);}}/><p>选中片段：{selection?session.transcript.text.slice(selection.start,selection.end):'尚未选择'}</p><label>本人确认的真实含义<textarea disabled={locked} value={meaning} onChange={event=>{setMeaning(event.target.value);setConfirmed(false);}}/></label><label>回流范围<select disabled={locked} value={JSON.stringify(wikiTarget)} onChange={event=>{setWikiTarget(JSON.parse(event.target.value));setConfirmed(false);}}>{wikiChoices.map(choice=><option key={JSON.stringify(choice.target)} value={JSON.stringify(choice.target)}>{choice.label}</option>)}</select></label><label><input disabled={locked} type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>我主动选择此片段，确认所写真实含义，不把角色扮演或模拟面试官虚构内容当作本人经历</label>{confirmed&&meaning.trim()&&selection&&selection.end>selection.start&&<ProductTaskPage target={{kind:'simulation-return',simulationId:session.id,transcriptVersion:session.transcript.version,wikiTarget,selectionStart:selection.start,selectionEnd:selection.end,confirmedRealMeaning:true,meaning}} purgeNotice={purgeNotice} onProtected={protect('simulation')} onApplied={onApplied}/>}</section>}
 {notice&&<p role="status">{notice}</p>}</section>;
}
