import {OpportunityHeader,phaseLabel,resultLabel,type OpportunitySection} from './detail-header';
import {JobDescription} from './jd';
import {wasPurged,type PurgeNotice} from '../../design-system/purge-notice';
import {useRef,useState,useEffect,useLayoutEffect} from 'react';
import {QueryClient,QueryClientProvider,useQuery} from '@tanstack/react-query';
import {useForm} from 'react-hook-form';
import {Request,Result,type OpportunityView,type Company,type History,type Phase} from '../../../contracts/opportunity/schema';
import {BusinessTime} from '../../../contracts/common/business-time';
import {sendOpportunityIntent} from './save';
import type { ReactNode } from 'react';
export interface OpportunityPageProps{active?:boolean;purgeNotice?:PurgeNotice;request:(input:Request)=>Promise<Result>;onOpenResume?:(opportunityId:string)=>void;workspaceInstance?:string;focusOpportunity?:{id:string;sequence:number};detail?:{id:string;section:OpportunitySection};onNavigate?:(id?:string,section?:OpportunitySection)=>void;renderOverview?:(opportunity:OpportunityView)=>ReactNode;renderSubmodules?:(opportunity:OpportunityView,onChanged:()=>void,section:OpportunitySection)=>ReactNode}
type IdentityForm={companyId:string;role:string;correction:boolean;reason:string};
type EventForm={reason:string;stage:'submitted'|'interview'|'offer';timeKind:'unknown'|'date'|'instant';date:string;instant:string;timezone:string};
const emptyIdentity:IdentityForm={companyId:'',role:'',correction:false,reason:''};
const emptyEvent:EventForm={reason:'',stage:'interview',timeKind:'unknown',date:'',instant:'',timezone:''};

const historyLabel:Record<History['type'],string>={created:'创建尝试',identity_edited:'身份信息更新',identity_corrected:'身份信息纠错',jd_updated:'JD 更新',stage_reached:'登记现实阶段',stage_corrected:'纠正原阶段事件',ended:'结果变化',end_corrected:'纠正误结束',continued:'现实重新继续',offer_accepted:'接受当时 Offer 条件',offer_conditions_replaced:'正式 Offer 条件替换',offer_recruiter_withdrew:'招聘方撤回 Offer',offer_user_withdrew:'用户退出 Offer',offer_acceptance_corrected:'纠正原接受误操作',offer_withdrawal_corrected:'纠正原 Offer 撤回误操作'};
export function OpportunityPage(props:OpportunityPageProps){const [client]=useState(()=>new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}}));return <QueryClientProvider client={client}><OpportunityContents {...props}/></QueryClientProvider>;}
function OpportunityContents({active=true,purgeNotice,request,onOpenResume,workspaceInstance='opportunity-session',focusOpportunity,detail,onNavigate,renderOverview,renderSubmodules}:OpportunityPageProps){
 const [view,setView]=useState<'list'|'new'|'detail'>(detail?'detail':'list'),[section,setSection]=useState<OpportunitySection>(detail?.section??'overview'),[companyMode,setCompanyMode]=useState<'existing'|'new'>('existing'),[newCompanyName,setNewCompanyName]=useState(''),[jdOpen,setJdOpen]=useState(false),[eventOpen,setEventOpen]=useState(false),[moreOpen,setMoreOpen]=useState(false),[advancedEvent,setAdvancedEvent]=useState(false);
 const contexts=useRef(new Map<string,OpportunityView>());const [,invalidateContexts]=useState(0);
 function navigate(id?:string,next:OpportunitySection='overview'){if(id){setView('detail');setSection(next);}else {generation.current++;setView('list');const position=listPosition.current;if(position)requestAnimationFrame(()=>window.scrollTo(position));}onNavigate?.(id,next);}
 const [search,setSearch]=useState(''),[resultFilter,setResultFilter]=useState('all');
 const listPosition=useRef<{left:number;top:number}|undefined>(undefined),details=useRef<HTMLDivElement>(null);
 const [jdDirty,setJdDirty]=useState(false);
 const [selected,setSelected]=useState<OpportunityView>();const [company,setCompany]=useState<Company>();const [status,setStatus]=useState('未保存');const [pending,setPending]=useState<Request>();const [missing,setMissing]=useState(false);const [busy,setBusy]=useState(false);const [history,setHistory]=useState<History[]>([]);const [server,setServer]=useState<OpportunityView>();const generation=useRef(0);if(selected){contexts.current.set(selected.id,selected);}
 const [companyServer,setCompanyServer]=useState<Company>();const [correctionEventId,setCorrectionEventId]=useState<string>();const [voidStage,setVoidStage]=useState(false);
 const identity=useForm<IdentityForm>({defaultValues:emptyIdentity});const event=useForm<EventForm>({defaultValues:emptyEvent});const companyForm=useForm<{name:string}>({defaultValues:{name:''}});
 useLayoutEffect(()=>{if(view==='detail')details.current?.scrollIntoView({block:'start'});},[selected?.id,view]);
 const identityDirty=identity.formState.isDirty;const eventDirty=event.formState.isDirty||!!correctionEventId||voidStage;const dirty=identityDirty||eventDirty||companyForm.formState.isDirty||jdDirty||!!newCompanyName;const focusedSequence=useRef<number|undefined>(undefined);
 useEffect(()=>{if(!dirty&&!pending&&!busy)return;const protect=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue='';};window.addEventListener('beforeunload',protect);return()=>window.removeEventListener('beforeunload',protect);},[dirty,pending,busy]);
 const companies=useQuery({queryKey:['opportunity',workspaceInstance,'companies'],queryFn:async()=>{const r=Result.parse(await request({operation:'company.list'}));if(r.kind!=='companies')throw Error('公司读取失败');return r.items;}});
 const opportunities=useQuery({queryKey:['opportunity',workspaceInstance,'list'],queryFn:async()=>{const r=Result.parse(await request({operation:'list'}));if(r.kind!=='opportunities')throw Error('机会读取失败');return r.items;}});
 function adopt(value?:OpportunityView){generation.current++;setNewCompanyName('');setCorrectionEventId(undefined);setVoidStage(false);setAdvancedEvent(false);setEventOpen(false);setJdOpen(false);setSelected(value);setCompany(undefined);setCompanyServer(undefined);companyForm.reset({name:''});identity.reset(value?{companyId:value.companyId,role:value.role,reason:'',correction:false}:emptyIdentity);event.reset(emptyEvent);setServer(undefined);setHistory([]);setStatus(value?'已保存':'未保存');}
 useEffect(()=>{if(!purgeNotice)return;generation.current++;for(const [id,value] of contexts.current){if(wasPurged(purgeNotice,'opportunity',id))contexts.current.delete(id);else if(wasPurged(purgeNotice,'company',value.companyId))contexts.current.set(id,{...value,companyName:'已清除的公司'});}invalidateContexts(v=>v+1);if(wasPurged(purgeNotice,'opportunity',selected?.id)){adopt();setView('list');navigate();setPending(undefined);setStatus('这条机会及从属资料已永久清除。');}if(wasPurged(purgeNotice,'company',company?.id)){setCompany(undefined);companyForm.reset({name:''});setCompanyServer(undefined);}if(selected&&wasPurged(purgeNotice,'company',selected.companyId)){generation.current++;setSelected({...selected,companyName:'已清除的公司'});}void companies.refetch();void opportunities.refetch();},[purgeNotice?.sequence]);
 async function open(id:string){if(selected?.id===id){const current=++generation.current;try{const r=Result.parse(await request({operation:'read',id}));if(current!==generation.current)return;if(r.kind!=='opportunity'){setStatus('机会状态暂时无法确认；保留输入，请返回列表检查。');return false;}if(selected.companyId!==r.opportunity.companyId||selected.role!==r.opportunity.role){if(identityDirty){setServer(r.opportunity);setStatus('正式公司或岗位已变化，输入保留；请比较后继续。');}else{setSelected(r.opportunity);identity.reset({companyId:r.opportunity.companyId,role:r.opportunity.role,reason:'',correction:false});}}else setSelected(r.opportunity);setView('detail');return true;}catch{if(current!==generation.current)return;setStatus('机会状态暂时无法读取，输入保留；请刷新。');return false;}}if(pending||dirty&&!window.confirm('有未保存输入。放弃后切换机会？'))return false;const position={left:window.scrollX,top:window.scrollY},current=++generation.current;try{const r=Result.parse(await request({operation:'read',id}));if(current!==generation.current)return;if(r.kind==='opportunity'){listPosition.current=position;adopt(r.opportunity);setView('detail');return true;}else setStatus('机会暂不可读');}catch{if(current===generation.current)setStatus('读取失败，输入保留');}}
 useEffect(()=>{if(!active){generation.current++;return;}if(detail){setSection(detail.section);void open(detail.id).then(opened=>{if(opened===false&&selected)navigate(selected.id,section);});}else if(onNavigate){generation.current++;setView('list');}},[active,detail?.id,detail?.section]);
 useEffect(()=>{if(!focusOpportunity||focusedSequence.current===focusOpportunity.sequence)return;focusedSequence.current=focusOpportunity.sequence;void open(focusOpportunity.id);},[focusOpportunity]);
 async function handleResult(result:Result|{kind:'unknown'},intent:Request){
  if(result.kind==='unknown'){setPending(intent);setMissing(false);setStatus('保存结果待核对，当前输入保留');return;}
  if(result.kind==='receipt_missing'){setPending(intent);setMissing(true);setStatus('确认尚未保存；你可以明确继续这次保存。');return;}
  setPending(undefined);setMissing(false);
  if(result.kind==='opportunity'){adopt(result.opportunity);if(intent.operation==='create')navigate(result.opportunity.id);const refreshed=await opportunities.refetch();if(refreshed.isError)setStatus('已保存，列表暂时未刷新');return;}
  if(result.kind==='company'){generation.current++;setCompany(result.company);companyForm.reset({name:result.company.name});if(selected?.companyId===result.company.id)setSelected({...selected,companyName:result.company.name});if(intent.operation==='company.create'){identity.setValue('companyId',result.company.id,{shouldDirty:true});setCompanyMode('existing');setNewCompanyName('');}setStatus('公司已保存');const [c,o]=await Promise.all([companies.refetch(),opportunities.refetch()]);if(c.isError||o.isError)setStatus('公司已保存，列表暂时未刷新');return;}
  if(result.kind==='failure'&&result.code==='conflict'&&intent.operation==='company.rename'){await compareCompany(intent.id);return;}
  if(result.kind==='failure'){setStatus(result.code==='conflict'?'冲突：输入保留，请比较正式值':intent.operation==='correct-end'&&result.code==='invalid_transition'?'当前结束不能在此纠正；若来自 Offer，请在 Offer 历史中纠正对应误撤回。':'保存未完成，输入保留；请检查后继续。');if(result.code==='conflict'&&selected&&intent.operation!=='company.rename'){try{const r=Result.parse(await request({operation:'read',id:selected.id}));if(r.kind==='opportunity')setServer(r.opportunity);}catch{setStatus('冲突，正式值暂不可读；输入保留');}}}
 }
 async function compareCompany(id:string){try{const result=Result.parse(await request({operation:'company.read',id}));if(result.kind==='company'){generation.current++;setCompanyServer(result.company);setStatus('公司改名冲突：草稿保留，请比较当前正式名称');}else setStatus('公司冲突，当前正式名称暂不可读；草稿保留');}catch{setStatus('公司冲突，当前正式名称暂不可读；草稿保留');}}
 async function run(value:unknown){const parsed=Request.safeParse(value);if(!parsed.success){setStatus('请填写必要内容、变化说明和合法实际时间。未知时间可保持未知。');return;}const intent=parsed.data;setBusy(true);setPending(intent);setStatus('保存中');try{const result=await sendOpportunityIntent(request,intent);await handleResult(result,intent);return result;}finally{setBusy(false);}}
 function businessTime(values:EventForm){return values.timeKind==='unknown'?{kind:'unknown'}:values.timeKind==='date'?{kind:'date',date:values.date}:{kind:'instant',instant:values.instant,timezone:values.timezone};}
 async function saveIdentity(values:IdentityForm){if(!selected&&companyMode==='new'){if(!values.role.trim()||!newCompanyName.trim()){setStatus('请填写公司和岗位。');return;}const created=await run({operation:'company.create',commandId:crypto.randomUUID(),name:newCompanyName});if(created?.kind!=='company')return;setCompanyMode('existing');const saved=await run({operation:'create',commandId:crypto.randomUUID(),companyId:created.company.id,role:values.role});if(saved?.kind!=='opportunity')setStatus('公司已建立并保留，机会尚未确认保存；请检查这次保存后继续，不必重新建公司。');return;}if(eventDirty||jdDirty){setStatus('事件输入尚未提交：请保留并先完成事件，或明确取消事件输入，再保存身份修改。');return;}await run(selected?{operation:'edit',commandId:crypto.randomUUID(),id:selected.id,expectedRevision:selected.revision,companyId:values.companyId,role:values.role,correction:values.correction,reason:values.reason,businessTime:{kind:'unknown'}}:{operation:'create',commandId:crypto.randomUUID(),companyId:values.companyId,role:values.role});}
 function cancelEventDraft(){if(eventDirty&&!window.confirm('明确取消尚未提交的阶段、结束或纠错输入？机会身份草稿仍保留。'))return;event.reset(emptyEvent);setCorrectionEventId(undefined);setVoidStage(false);setStatus('已取消未提交事件输入；机会身份草稿仍保留。');}
 function cancelIdentityDraft(){if(identityDirty&&!window.confirm('明确取消尚未保存的公司归属、岗位与修改说明？事件输入仍保留。'))return;identity.reset(selected?{companyId:selected.companyId,role:selected.role,reason:'',correction:false}:emptyIdentity);setStatus('已取消未保存的机会身份修改；事件输入仍保留。');}
 async function record(operation:'record-stage'|'end'|'correct-end'|'recontinue',outcome?:'withdrawn'|'recruiter_ended'){if((operation==='end'||operation==='correct-end'||operation==='recontinue')&&!window.confirm('确认记录这次真实结果变化？这会更新机会的当前结果。'))return;if(!selected||identityDirty||jdDirty||companyForm.formState.isDirty)return;const values=event.getValues();await run({operation,commandId:crypto.randomUUID(),id:selected.id,expectedRevision:selected.revision,reason:values.reason,businessTime:businessTime(values),...operation==='record-stage'?{stage:values.stage}:{},...operation==='end'?{outcome}:{}});}
 async function readHistory(){if(!selected)return;const current=generation.current;try{const r=Result.parse(await request({operation:'history',id:selected.id}));if(current!==generation.current)return;if(r.kind==='history')setHistory(r.items);else setStatus('历史暂不可读');}catch{if(current===generation.current)setStatus('历史读取失败，输入保留');}}
 async function refreshFromSubmodule(){if(!selected)return;const id=selected.id,current=++generation.current;try{const result=Result.parse(await request({operation:'read',id}));if(current!==generation.current||result.kind!=='opportunity')return;if(selected.companyId!==result.opportunity.companyId||selected.role!==result.opportunity.role)setServer(result.opportunity);else setSelected(result.opportunity);void opportunities.refetch();}catch{if(current===generation.current)setStatus('子模块保存结果保留；机会显示暂未刷新，请刷新。');}}
 const timeKind=event.watch('timeKind');
 const companyChoices=[...(companies.data??[]),...(company&&!companies.data?.some(item=>item.id===company.id)?[company]:[])];
 function companyChoiceLabel(item:Company){const same=companyChoices.filter(other=>other.name===item.name);if(same.length<2)return item.name;const roles=opportunities.data?.filter(o=>o.companyId===item.id).map(o=>o.role).join('、');return `${item.name} · 候选 ${same.findIndex(other=>other.id===item.id)+1}${roles?' · '+roles:' · 暂无关联岗位'}`;}
 const filtered=opportunities.data?.filter(item=>(resultFilter==='all'||(resultFilter==='active'?item.result==='active':item.result!=='active'))&&(item.companyName+' '+item.role).toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()));
 const ready=selected&&(!detail||selected.id===detail.id);
 return <section aria-label="机会" data-feedback-owner="opportunity" data-feedback-id={view==='detail'?selected?.id:undefined}>
 <div hidden={view!=='list'}><h1>机会</h1><p>一次机会，就是你正在接触的一份具体工作。选择公司和岗位，查看简历、情报及实际进展。</p><div className="opportunity-list-tools"><label>搜索机会<input value={search} onChange={e=>setSearch(e.target.value)} maxLength={300}/></label><label>机会结果筛选<select value={resultFilter} onChange={e=>setResultFilter(e.target.value)}><option value="all">全部</option><option value="active">进行中</option><option value="ended">已结束</option></select></label><button className="opportunity-primary" disabled={!!pending||busy} onClick={()=>{if(!selected&&dirty){setView('new');return;}if(selected&&dirty&&!window.confirm('放弃当前机会未保存的公司、岗位或进展输入，开始新建？'))return;adopt();setView('new');setCompanyMode('existing');setNewCompanyName('');}}>新建机会</button><button onClick={()=>void Promise.all([opportunities.refetch(),companies.refetch()])}>刷新</button></div>{opportunities.isPending?<p>正在读取机会…</p>:opportunities.isError?<p role="alert">机会暂时无法读取，请刷新；不会把读取失败当成空列表。</p>:!opportunities.data?.length?<p>还没有机会。点“新建机会”，公司和岗位就够，其他资料以后再补。</p>:<ul aria-label="机会列表" className="opportunity-cards">{filtered?.map(item=><li key={item.id}><button disabled={!!pending||busy} onClick={async()=>{if(await open(item.id))navigate(item.id);}}>{item.companyName} · {item.role}</button><p>{phaseLabel[item.phase]} · {resultLabel[item.result]}</p></li>)}</ul>}{filtered?.length===0&&opportunities.data?.length!==0&&<p>没有匹配的机会，试试更短的关键词或其他筛选。</p>}</div>
 <div hidden={view!=='new'}><h1>新建机会</h1><p>公司和岗位就够，JD可以以后再补。新公司先保存，再保存机会；其中一步失败会明确说明。</p><button onClick={()=>setView('list')}>返回机会列表（保留新建输入）</button></div>
 <div ref={details} hidden={view!=='detail'} className="opportunity-detail">{ready?<OpportunityHeader opportunity={selected} section={section} onList={()=>navigate()} onSection={next=>{if(next==='resume'){onOpenResume?.(selected.id);return;}navigate(selected.id,next);}}/>:<><p role="status">{status==='未保存'?'正在打开机会…':status}</p><button onClick={()=>navigate()}>返回机会列表</button></>}
 {ready&&<div hidden={section!=='overview'}><h2>概览</h2><p>已知关键日期：{(['submitted','interview','offer'] as const).map(stage=>`${phaseLabel[stage]} ${formatTime(selected.stageDates[stage])}`).join('；')}</p><p>{selected.jd?'已保存岗位介绍（JD），可展开阅读。':'尚无岗位介绍（JD）；不影响记录真实沟通、面试或Offer。'}</p>{renderOverview?.(selected)}<div className="opportunity-overview-actions"><button className="opportunity-primary" onClick={()=>onOpenResume?.(selected.id)}>修改简历</button><button onClick={()=>setJdOpen(true)}>{selected.jd?'修改 JD':'补充 JD'}</button><button onClick={()=>setEventOpen(!eventOpen)}>记录实际进展</button>{selected.result==='active'&&<button onClick={()=>navigate(selected.id,'communication')}>记录已投递</button>}</div><details open={jdOpen} onToggle={event=>setJdOpen(event.currentTarget.open)}><summary>岗位介绍（JD）</summary><pre>{selected.jd??'尚无JD'}</pre><JobDescription key={selected.id} opportunity={selected} request={request} onChanged={()=>void refreshFromSubmodule()} onDirty={setJdDirty}/></details><div hidden={!eventOpen}> <form onSubmit={event.handleSubmit(()=>record('record-stage'))}><fieldset disabled={busy||!!pending||identityDirty||companyForm.formState.isDirty}><legend>记录实际进展</legend><label>变化说明<input {...event.register('reason')} maxLength={1000}/></label><label>实际业务时间<select {...event.register('timeKind')}><option value="unknown">未知（不补今天）</option><option value="date">只知道日期</option><option value="instant">知道精确时刻和时区</option></select></label>{timeKind==='date'&&<label>实际日期<input type="date" {...event.register('date')}/></label>}{timeKind==='instant'&&<><label>精确时刻（含时区偏移）<input {...event.register('instant')} placeholder="2026-10-02T09:00:00+08:00"/></label><label>原事件时区<input {...event.register('timezone')} placeholder="Asia/Shanghai"/></label></>}
 <label>现实已达到阶段<select {...event.register('stage')}><option value="submitted">真实已投递</option><option value="interview">真实已面试</option><option value="offer">真实收到 Offer</option></select></label><button type="submit">登记真实阶段事件</button><p>只登记实际达到的阶段；不补造投递材料、面试轮次或 Offer 条件对象。</p>
 <div hidden={!advancedEvent}><button type="button" onClick={()=>void record('end','withdrawn')}>确认用户退出</button><button type="button" onClick={()=>void record('end','recruiter_ended')}>确认招聘方终止</button>{selected.result!=='active'&&<>{selected.result!=='accepted'&&<button type="button" onClick={()=>void record('correct-end')}>纠正当前误结束</button>}<button type="button" onClick={()=>void record('recontinue')}>登记后来现实继续</button></>}{correctionEventId&&<div><p>正在纠正已选历史阶段事件（同一身份）。</p><label><input type="checkbox" checked={voidStage} onChange={e=>setVoidStage(e.target.checked)}/>原事件未发生，撤销错误登记</label><button type="button" onClick={()=>{const values=event.getValues();void run({operation:'correct-stage',commandId:crypto.randomUUID(),id:selected.id,expectedRevision:selected.revision,eventId:correctionEventId,stage:values.stage,voided:voidStage,reason:values.reason,businessTime:businessTime(values)});setCorrectionEventId(undefined);}}>提交原阶段事件纠错</button><button type="button" onClick={()=>setCorrectionEventId(undefined)}>取消阶段纠错</button></div>}<p>{renderSubmodules?'接受、接受纠错与 Offer 撤回纠错请进入 Offer 历史，保留真实条件依据。':'接受 Offer 需要正式条件依据；本批尚未启用。'}</p></div></fieldset></form><button disabled={busy||!!pending||!eventDirty} onClick={cancelEventDraft}>取消未提交事件输入（保留身份草稿）</button>
</div><details open={moreOpen} onToggle={event=>setMoreOpen(event.currentTarget.open)}><summary>更多</summary><p>公司、岗位和历史纠错只在这里修改；不会自动推断真实事件。</p><button onClick={()=>void readHistory()}>查看机会变化历史</button><button onClick={()=>{setEventOpen(true);setAdvancedEvent(true);void readHistory();}}>纠正阶段 / 结束机会 / 后来现实继续</button> {history.length>0&&<aside aria-label="机会历史"><h3>变化历史（只读）</h3>{history.map(item=><article key={item.id}><h4>{historyLabel[item.type]}</h4><p>{item.reason} · 实际时间 {formatTime(item.businessTime)} · 当时阶段 {phaseLabel[item.phase]} · 当时结果 {resultLabel[item.result]}</p>{item.type==='stage_reached'&&!item.stageOwner&&<button disabled={!!pending} onClick={()=>{setCorrectionEventId(item.id);setVoidStage(false);setEventOpen(true);setAdvancedEvent(true);}}>选择此阶段事件纠错</button>}</article>)}<button onClick={()=>setHistory([])}>关闭历史</button></aside>}
<details><summary>查看技术详情</summary><p>机会 ID：{selected.id}；公司 ID：{selected.companyId}</p></details></details></div>}
 </div>
 <div hidden={view!=='new'&&!(view==='detail'&&ready&&section==='overview'&&moreOpen)}><details open={view==='new'||moreOpen}><summary>{view==='new'?'公司与岗位':'修改公司 / 岗位'}</summary> <form onSubmit={identity.handleSubmit(saveIdentity)}><fieldset disabled={busy||!!pending||selected&&companyForm.formState.isDirty}><legend>{selected?'修改公司与岗位':'建立机会'}</legend>{!selected&&<label>公司填写方式<select value={companyMode} onChange={e=>setCompanyMode(e.target.value as typeof companyMode)}><option value="existing">选择已有公司</option><option value="new">填写新公司</option></select></label>}{!selected&&companyMode==='new'?<label>公司名称<input value={newCompanyName} onChange={e=>setNewCompanyName(e.target.value)} maxLength={200}/></label>:<label>选择公司<select {...identity.register('companyId')}><option value="">请选择公司</option>{companyChoices.map(item=><option key={item.id} value={item.id}>{companyChoiceLabel(item)}</option>)}</select></label>}<label>岗位名称<input {...identity.register('role')} maxLength={200}/></label>{selected&&<><label>修改说明<input {...identity.register('reason')} maxLength={1000}/></label><label><input type="checkbox" {...identity.register('correction')}/>纠正原记录（更换误选公司必须勾选）</label></>}<button type="submit">{selected?'保存机会修改':'创建机会'}</button></fieldset></form>{selected&&<button disabled={busy||!!pending||!identityDirty} onClick={cancelIdentityDraft}>取消未保存的机会身份修改（保留事件输入）</button>}
<div hidden={!selected}> <fieldset disabled={busy||!!pending}><legend>公司管理</legend><form onSubmit={companyForm.handleSubmit(values=>run({operation:company?'company.rename':'company.create',commandId:crypto.randomUUID(),name:values.name,...company?{id:company.id,expectedRevision:company.revision}:{}}))}><label>公司名称<input {...companyForm.register('name')} maxLength={200}/></label><button type="submit">{company?'保存公司改名':'建立新公司'}</button><button type="button" onClick={()=>{if(companyForm.formState.isDirty&&!window.confirm('放弃未保存的公司名称并填写新公司？'))return;setCompany(undefined);setCompanyServer(undefined);companyForm.reset({name:''});}}>填写新公司</button></form>
 {companies.isError&&<p>公司列表暂不可读</p>}<ul>{companies.data?.map(item=><li key={item.id}><button onClick={()=>{if(companyForm.formState.isDirty&&!window.confirm('放弃未保存公司名称？'))return;setCompany(item);setCompanyServer(undefined);companyForm.reset({name:item.name});}}>{companyChoiceLabel(item)}</button> <button onClick={()=>identity.setValue('companyId',item.id,{shouldDirty:true})}>用于当前机会</button></li>)}</ul><p>同名公司保持不同身份，由你明确选择；改名沿用原身份。</p>{company&&<button type="button" onClick={()=>void compareCompany(company.id)}>刷新公司并保留输入</button>}{companyServer&&<aside aria-label="公司改名冲突比较"><h3>当前正式公司名称</h3><p>{companyServer.name}</p><p>你的名称草稿仍在公司名称输入框中。</p><button type="button" onClick={()=>{setCompany(companyServer);setCompanyServer(undefined);setStatus('已采用公司新版本基线；名称草稿保留，请明确保存');}}>采用公司新基线并保留名称草稿</button><button type="button" onClick={()=>{setCompany(companyServer);companyForm.reset({name:companyServer.name});setCompanyServer(undefined);setStatus('已明确放弃名称草稿并读取当前公司');}}>放弃名称草稿并读取当前公司</button></aside>}</fieldset>
</div></details></div>
 <div hidden={view!=='new'&&!(view==='detail'&&ready&&(section==='overview'||!!pending||dirty))} className="opportunity-core-status"> <p role="status">{status}{dirty?' · 有未保存输入':''}</p>{pending&&'commandId'in pending&&<div><button disabled={busy} onClick={async()=>{setBusy(true);try{await handleResult(await sendOpportunityIntent(request,{operation:'receipt',commandId:pending.commandId}),pending);}finally{setBusy(false);}}}>检查是否已保存</button>{missing&&<button disabled={busy} onClick={()=>void run(pending)}>继续这次保存</button>}</div>}
 {server&&<aside aria-label="机会冲突比较"><h3>当前正式值；草稿仍在输入区</h3><p>{server.companyName} · {server.role} · {phaseLabel[server.phase]} · {resultLabel[server.result]}</p><button onClick={()=>{setSelected(server);setServer(undefined);setStatus('已采用正式版本作为新基线；保留草稿，请明确保存');}}>采用新基线并保留草稿</button><button onClick={()=>adopt(server)}>放弃草稿并读取正式值</button></aside>}
</div>
 {Array.from(contexts.current.values()).map(value=><div key={value.id} hidden={view!=='detail'||!ready||selected?.id!==value.id||section==='overview'||section==='resume'}>{renderSubmodules?.(value,()=>{if(selected?.id===value.id)void refreshFromSubmodule();else void opportunities.refetch();},selected?.id===value.id?section:'overview')}</div>)}
 </section>;
}
function formatTime(time:BusinessTime){return time.kind==='unknown'?'未知':time.kind==='date'?time.date:time.instant+' ('+time.timezone+')';}
