import {useRef,useState,useEffect} from 'react';
import {QueryClient,QueryClientProvider,useQuery} from '@tanstack/react-query';
import {useForm} from 'react-hook-form';
import {Request,Result,type OpportunityView,type Company,type History,type Phase} from '../../../contracts/opportunity/schema';
import {BusinessTime} from '../../../contracts/common/business-time';
import {sendOpportunityIntent} from './save';
import type { ReactNode } from 'react';
export interface OpportunityPageProps{request:(input:Request)=>Promise<Result>;onOpenResume?:(opportunityId:string)=>void;workspaceInstance?:string;focusOpportunity?:{id:string;sequence:number};renderSubmodules?:(opportunity:OpportunityView,onChanged:()=>void)=>ReactNode}
type IdentityForm={companyId:string;role:string;correction:boolean;reason:string};
type EventForm={reason:string;stage:'submitted'|'interview'|'offer';timeKind:'unknown'|'date'|'instant';date:string;instant:string;timezone:string};
const emptyIdentity:IdentityForm={companyId:'',role:'',correction:false,reason:''};
const emptyEvent:EventForm={reason:'',stage:'interview',timeKind:'unknown',date:'',instant:'',timezone:''};
const phaseLabel={preparation:'投递准备',submitted:'已投递',interview:'面试',offer:'Offer'};const resultLabel={active:'进行中',accepted:'接受 Offer',withdrawn:'用户退出',recruiter_ended:'招聘方终止'};
const historyLabel:Record<History['type'],string>={created:'创建尝试',identity_edited:'身份信息更新',identity_corrected:'身份信息纠错',stage_reached:'登记现实阶段',stage_corrected:'纠正原阶段事件',ended:'结果变化',end_corrected:'纠正误结束',continued:'现实重新继续',offer_accepted:'接受当时 Offer 条件',offer_conditions_replaced:'正式 Offer 条件替换',offer_recruiter_withdrew:'招聘方撤回 Offer',offer_user_withdrew:'用户退出 Offer',offer_acceptance_corrected:'纠正原接受误操作'};
export function OpportunityPage(props:OpportunityPageProps){const [client]=useState(()=>new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}}));return <QueryClientProvider client={client}><OpportunityContents {...props}/></QueryClientProvider>;}
function OpportunityContents({request,onOpenResume,workspaceInstance='opportunity-session',focusOpportunity,renderSubmodules}:OpportunityPageProps){
 const [selected,setSelected]=useState<OpportunityView>();const [company,setCompany]=useState<Company>();const [status,setStatus]=useState('未保存');const [pending,setPending]=useState<Request>();const [missing,setMissing]=useState(false);const [busy,setBusy]=useState(false);const [history,setHistory]=useState<History[]>([]);const [server,setServer]=useState<OpportunityView>();const generation=useRef(0);const submoduleContext=useRef<OpportunityView|undefined>(undefined);if(selected)submoduleContext.current=selected;
 const [companyServer,setCompanyServer]=useState<Company>();const [correctionEventId,setCorrectionEventId]=useState<string>();const [voidStage,setVoidStage]=useState(false);
 const identity=useForm<IdentityForm>({defaultValues:emptyIdentity});const event=useForm<EventForm>({defaultValues:emptyEvent});const companyForm=useForm<{name:string}>({defaultValues:{name:''}});
 const identityDirty=identity.formState.isDirty;const eventDirty=event.formState.isDirty||!!correctionEventId||voidStage;const dirty=identityDirty||eventDirty||companyForm.formState.isDirty;const focusedSequence=useRef<number|undefined>(undefined);
 useEffect(()=>{if(!dirty&&!pending&&!busy)return;const protect=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue='';};window.addEventListener('beforeunload',protect);return()=>window.removeEventListener('beforeunload',protect);},[dirty,pending,busy]);
 const companies=useQuery({queryKey:['opportunity',workspaceInstance,'companies'],queryFn:async()=>{const r=Result.parse(await request({operation:'company.list'}));if(r.kind!=='companies')throw Error('公司读取失败');return r.items;}});
 const opportunities=useQuery({queryKey:['opportunity',workspaceInstance,'list'],queryFn:async()=>{const r=Result.parse(await request({operation:'list'}));if(r.kind!=='opportunities')throw Error('机会读取失败');return r.items;}});
 function adopt(value?:OpportunityView){generation.current++;setCorrectionEventId(undefined);setVoidStage(false);setSelected(value);setCompany(undefined);setCompanyServer(undefined);companyForm.reset({name:''});identity.reset(value?{companyId:value.companyId,role:value.role,reason:'',correction:false}:emptyIdentity);event.reset(emptyEvent);setServer(undefined);setHistory([]);setStatus(value?'已保存':'未保存');}
 async function open(id:string){if(pending||dirty&&!window.confirm('有未保存输入。放弃后切换机会？'))return;const current=++generation.current;try{const r=Result.parse(await request({operation:'read',id}));if(current!==generation.current)return;if(r.kind==='opportunity')adopt(r.opportunity);else setStatus('机会暂不可读');}catch{if(current===generation.current)setStatus('读取失败，输入保留');}}
 useEffect(()=>{if(!focusOpportunity||focusedSequence.current===focusOpportunity.sequence)return;focusedSequence.current=focusOpportunity.sequence;void open(focusOpportunity.id);},[focusOpportunity]);
 async function handleResult(result:Result|{kind:'unknown'},intent:Request){
  if(result.kind==='unknown'){setPending(intent);setMissing(false);setStatus('保存结果待核对，当前输入保留');return;}
  if(result.kind==='receipt_missing'){setPending(intent);setMissing(true);setStatus('未发现原命令，可明确继续同一意图');return;}
  setPending(undefined);setMissing(false);
  if(result.kind==='opportunity'){adopt(result.opportunity);const refreshed=await opportunities.refetch();if(refreshed.isError)setStatus('已保存，列表暂时未刷新');return;}
  if(result.kind==='company'){setCompany(result.company);companyForm.reset({name:result.company.name});if(selected?.companyId===result.company.id)setSelected({...selected,companyName:result.company.name});if(intent.operation==='company.create')identity.setValue('companyId',result.company.id,{shouldDirty:true});setStatus('公司已保存');const [c,o]=await Promise.all([companies.refetch(),opportunities.refetch()]);if(c.isError||o.isError)setStatus('公司已保存，列表暂时未刷新');return;}
  if(result.kind==='failure'&&result.code==='conflict'&&intent.operation==='company.rename'){await compareCompany(intent.id);return;}
  if(result.kind==='failure'){setStatus(result.code==='conflict'?'冲突：输入保留，请比较正式值':'保存失败，输入保留：'+result.code);if(result.code==='conflict'&&selected&&intent.operation!=='company.rename'){try{const r=Result.parse(await request({operation:'read',id:selected.id}));if(r.kind==='opportunity')setServer(r.opportunity);}catch{setStatus('冲突，正式值暂不可读；输入保留');}}}
 }
 async function compareCompany(id:string){try{const result=Result.parse(await request({operation:'company.read',id}));if(result.kind==='company'){setCompanyServer(result.company);setStatus('公司改名冲突：草稿保留，请比较当前正式名称');}else setStatus('公司冲突，当前正式名称暂不可读；草稿保留');}catch{setStatus('公司冲突，当前正式名称暂不可读；草稿保留');}}
 async function run(value:unknown){const parsed=Request.safeParse(value);if(!parsed.success){setStatus('请填写必要内容、变化说明和合法实际时间。未知时间可保持未知。');return;}const intent=parsed.data;setBusy(true);setPending(intent);setStatus('保存中');try{await handleResult(await sendOpportunityIntent(request,intent),intent);}finally{setBusy(false);}}
 function businessTime(values:EventForm){return values.timeKind==='unknown'?{kind:'unknown'}:values.timeKind==='date'?{kind:'date',date:values.date}:{kind:'instant',instant:values.instant,timezone:values.timezone};}
 async function saveIdentity(values:IdentityForm){if(eventDirty){setStatus('事件输入尚未提交：请保留并先完成事件，或明确取消事件输入，再保存身份修改。');return;}await run(selected?{operation:'edit',commandId:crypto.randomUUID(),id:selected.id,expectedRevision:selected.revision,companyId:values.companyId,role:values.role,correction:values.correction,reason:values.reason,businessTime:{kind:'unknown'}}:{operation:'create',commandId:crypto.randomUUID(),companyId:values.companyId,role:values.role});}
 function cancelEventDraft(){if(eventDirty&&!window.confirm('明确取消尚未提交的阶段、结束或纠错输入？机会身份草稿仍保留。'))return;event.reset(emptyEvent);setCorrectionEventId(undefined);setVoidStage(false);setStatus('已取消未提交事件输入；机会身份草稿仍保留。');}
 function cancelIdentityDraft(){if(identityDirty&&!window.confirm('明确取消尚未保存的公司归属、岗位与修改说明？事件输入仍保留。'))return;identity.reset(selected?{companyId:selected.companyId,role:selected.role,reason:'',correction:false}:emptyIdentity);setStatus('已取消未保存的机会身份修改；事件输入仍保留。');}
 async function record(operation:'record-stage'|'end'|'correct-end'|'recontinue',outcome?:'withdrawn'|'recruiter_ended'){if(!selected||identityDirty||companyForm.formState.isDirty)return;const values=event.getValues();await run({operation,commandId:crypto.randomUUID(),id:selected.id,expectedRevision:selected.revision,reason:values.reason,businessTime:businessTime(values),...operation==='record-stage'?{stage:values.stage}:{},...operation==='end'?{outcome}:{}});}
 async function readHistory(){if(!selected)return;const current=generation.current;try{const r=Result.parse(await request({operation:'history',id:selected.id}));if(current!==generation.current)return;if(r.kind==='history')setHistory(r.items);else setStatus('历史暂不可读');}catch{if(current===generation.current)setStatus('历史读取失败，输入保留');}}
 async function refreshFromSubmodule(){if(!selected)return;const id=selected.id,current=generation.current;try{const result=Result.parse(await request({operation:'read',id}));if(current!==generation.current||result.kind!=='opportunity')return;if(selected.companyId!==result.opportunity.companyId||selected.role!==result.opportunity.role)setServer(result.opportunity);else setSelected(result.opportunity);void opportunities.refetch();}catch{if(current===generation.current)setStatus('子模块保存结果保留；机会显示暂未刷新，请重新读取。');}}
 const timeKind=event.watch('timeKind');
 return <section aria-label="机会"><h1>机会</h1><p>公司和岗位即可建立求职尝试，不需要先填写 JD，也不需要伪造投递。</p>
 <fieldset disabled={busy||!!pending}><legend>可复用的公司身份</legend><form onSubmit={companyForm.handleSubmit(values=>run({operation:company?'company.rename':'company.create',commandId:crypto.randomUUID(),name:values.name,...company?{id:company.id,expectedRevision:company.revision}:{}}))}><label>公司名称<input {...companyForm.register('name')} maxLength={200}/></label><button type="submit">{company?'保存公司改名':'建立新公司'}</button><button type="button" onClick={()=>{if(companyForm.formState.isDirty&&!window.confirm('放弃未保存的公司名称并填写新公司？'))return;setCompany(undefined);setCompanyServer(undefined);companyForm.reset({name:''});}}>填写新公司</button></form>
 {companies.isError&&<p>公司列表暂不可读</p>}<ul>{companies.data?.map(item=><li key={item.id}><button onClick={()=>{if(companyForm.formState.isDirty&&!window.confirm('放弃未保存公司名称？'))return;setCompany(item);setCompanyServer(undefined);companyForm.reset({name:item.name});}}>{item.name}</button> · 身份 {item.id.slice(0,8)} <button onClick={()=>identity.setValue('companyId',item.id,{shouldDirty:true})}>用于当前机会</button></li>)}</ul><p>同名公司保持不同身份，由你明确选择；改名沿用原身份。</p>{company&&<button type="button" onClick={()=>void compareCompany(company.id)}>读取最新公司并保留草稿</button>}{companyServer&&<aside aria-label="公司改名冲突比较"><h3>当前正式公司名称</h3><p>{companyServer.name}</p><p>你的名称草稿仍在公司名称输入框中。</p><button type="button" onClick={()=>{setCompany(companyServer);setCompanyServer(undefined);setStatus('已采用公司新版本基线；名称草稿保留，请明确保存');}}>采用公司新基线并保留名称草稿</button><button type="button" onClick={()=>{setCompany(companyServer);companyForm.reset({name:companyServer.name});setCompanyServer(undefined);setStatus('已明确放弃名称草稿并读取当前公司');}}>放弃名称草稿并读取当前公司</button></aside>}</fieldset>
 <button disabled={!!pending} onClick={()=>{if(!dirty||window.confirm('放弃未保存输入并新建另一次尝试？')){adopt();setCompany(undefined);companyForm.reset({name:''});}}}>新建机会</button><button onClick={()=>void opportunities.refetch()}>重新读取机会列表</button>
 {opportunities.isError?<p role="alert">列表暂不可读，输入保留。</p>:opportunities.data?.length===0?<p>暂无机会。先建立或选择公司，再填写岗位。</p>:<ul>{opportunities.data?.map(item=><li key={item.id}><button disabled={!!pending} onClick={()=>void open(item.id)}>{item.companyName} · {item.role}</button> · {phaseLabel[item.phase]} · {resultLabel[item.result]}</li>)}</ul>}
 <form onSubmit={identity.handleSubmit(saveIdentity)}><fieldset disabled={busy||!!pending||companyForm.formState.isDirty}><legend>{selected?'机会身份':'建立机会'}</legend><label>明确选择公司<select {...identity.register('companyId')}><option value="">请选择公司身份</option>{companies.data?.map(item=><option key={item.id} value={item.id}>{item.name} · {item.id.slice(0,8)}</option>)}</select></label><label>岗位名称<input {...identity.register('role')} maxLength={200}/></label>{selected&&<><label>修改说明<input {...identity.register('reason')} maxLength={1000}/></label><label><input type="checkbox" {...identity.register('correction')}/>纠正原记录（更换误选公司必须勾选）</label></>}<button type="submit">{selected?'保存机会修改':'创建机会'}</button></fieldset></form>
 {selected&&<><button disabled={busy||!!pending||!identityDirty} onClick={cancelIdentityDraft}>取消未保存的机会身份修改（保留事件输入）</button><button disabled={busy||!!pending||!eventDirty} onClick={cancelEventDraft}>取消未提交事件输入（保留身份草稿）</button><h2>{selected.companyName} · {selected.role}</h2><p>实际达到阶段：{phaseLabel[selected.phase]}；当前结果：{resultLabel[selected.result]}</p><p>已知最早阶段日期：{(['submitted','interview','offer'] as const).map(stage=>`${phaseLabel[stage]} ${formatTime(selected.stageDates[stage])}`).join('；')}</p><button onClick={()=>onOpenResume?.(selected.id)} disabled={!onOpenResume||dirty||!!pending}>编辑本机会简历</button>
 <form onSubmit={event.handleSubmit(()=>record('record-stage'))}><fieldset disabled={busy||!!pending||identityDirty||companyForm.formState.isDirty}><legend>登记现实变化；先保存机会身份修改</legend><label>变化说明<input {...event.register('reason')} maxLength={1000}/></label><label>实际业务时间<select {...event.register('timeKind')}><option value="unknown">未知（不补今天）</option><option value="date">只知道日期</option><option value="instant">知道精确时刻和时区</option></select></label>{timeKind==='date'&&<label>实际日期<input type="date" {...event.register('date')}/></label>}{timeKind==='instant'&&<><label>精确时刻（含时区偏移）<input {...event.register('instant')} placeholder="2026-10-02T09:00:00+08:00"/></label><label>原事件时区<input {...event.register('timezone')} placeholder="Asia/Shanghai"/></label></>}
 <label>现实已达到阶段<select {...event.register('stage')}><option value="submitted">真实已投递</option><option value="interview">真实已面试</option><option value="offer">真实收到 Offer</option></select></label><button type="submit">登记真实阶段事件</button><p>只登记实际达到的阶段；不补造投递材料、面试轮次或 Offer 条件对象。</p>
 <button type="button" onClick={()=>void record('end','withdrawn')}>确认用户退出</button><button type="button" onClick={()=>void record('end','recruiter_ended')}>确认招聘方终止</button>{selected.result!=='active'&&<>{selected.result!=='accepted'&&<button type="button" onClick={()=>void record('correct-end')}>纠正当前误结束</button>}<button type="button" onClick={()=>void record('recontinue')}>登记后来现实继续</button></>}{correctionEventId&&<div><p>正在纠正已选历史阶段事件（同一身份）。</p><label><input type="checkbox" checked={voidStage} onChange={e=>setVoidStage(e.target.checked)}/>原事件未发生，撤销错误登记</label><button type="button" onClick={()=>{const values=event.getValues();void run({operation:'correct-stage',commandId:crypto.randomUUID(),id:selected.id,expectedRevision:selected.revision,eventId:correctionEventId,stage:values.stage,voided:voidStage,reason:values.reason,businessTime:businessTime(values)});setCorrectionEventId(undefined);}}>提交原阶段事件纠错</button><button type="button" onClick={()=>setCorrectionEventId(undefined)}>取消阶段纠错</button></div>}<p>{renderSubmodules?'接受与接受纠错请进入 Offer，保留真实条件依据。':'接受 Offer 需要正式条件依据；本批尚未启用。'}</p></fieldset></form>
 <button onClick={()=>void readHistory()}>查看机会变化历史</button></>}
 <p role="status">{status}{dirty?' · 有未保存输入':''}</p>{pending&&'commandId'in pending&&<div><button disabled={busy} onClick={async()=>{setBusy(true);try{await handleResult(await sendOpportunityIntent(request,{operation:'receipt',commandId:pending.commandId}),pending);}finally{setBusy(false);}}}>核对原保存回执</button>{missing&&<button disabled={busy} onClick={()=>void run(pending)}>继续原保存意图</button>}</div>}
 {server&&<aside aria-label="机会冲突比较"><h3>当前正式值；草稿仍在输入区</h3><p>{server.companyName} · {server.role} · {phaseLabel[server.phase]} · {resultLabel[server.result]}</p><button onClick={()=>{setSelected(server);setServer(undefined);setStatus('已采用正式版本作为新基线；保留草稿，请明确保存');}}>采用新基线并保留草稿</button><button onClick={()=>adopt(server)}>放弃草稿并读取正式值</button></aside>}
 {history.length>0&&<aside aria-label="机会历史"><h3>变化历史（只读）</h3>{history.map(item=><article key={item.id}><h4>{historyLabel[item.type]}</h4><p>{item.reason} · 实际时间 {formatTime(item.businessTime)} · 当时阶段 {phaseLabel[item.phase]} · 当时结果 {resultLabel[item.result]}</p>{item.type==='stage_reached'&&!item.stageOwner&&<button disabled={!!pending} onClick={()=>{setCorrectionEventId(item.id);setVoidStage(false);}}>选择此阶段事件纠错</button>}</article>)}<button onClick={()=>setHistory([])}>关闭历史</button></aside>}
 {submoduleContext.current&&renderSubmodules&&<div hidden={!selected}>{renderSubmodules(submoduleContext.current,()=>void refreshFromSubmodule())}</div>}
 </section>;
}
function formatTime(time:BusinessTime){return time.kind==='unknown'?'未知':time.kind==='date'?time.date:time.instant+' ('+time.timezone+')';}
