import {useEffect,useRef,useState} from 'react';
import {Result,type OpportunityView,type Request} from '../../../contracts/opportunity/schema';
export function JobDescription({opportunity,request,onChanged,onDirty}:{opportunity:OpportunityView;request:(input:Request)=>Promise<Result>;onChanged:()=>void;onDirty:(dirty:boolean)=>void}){
 const [base,setBase]=useState(opportunity),[text,setText]=useState(opportunity.jd??''),[reason,setReason]=useState(''),[pending,setPending]=useState<Request>(),[status,setStatus]=useState(''),[server,setServer]=useState<OpportunityView>(),[busy,setBusy]=useState(false);const owner=useRef(opportunity.id);const dirty=text!==(base.jd??'');
 useEffect(()=>{onDirty(dirty||!!pending);return()=>onDirty(false);},[dirty,pending,onDirty]);
 useEffect(()=>{if(owner.current!==opportunity.id){owner.current=opportunity.id;setBase(opportunity);setText(opportunity.jd??'');setReason('');setPending(undefined);setServer(undefined);setStatus('');}else if(!dirty&&!pending){setBase(opportunity);setText(opportunity.jd??'');}},[opportunity]);
 useEffect(()=>{if(!dirty&&!pending)return;const guard=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty,pending]);
 async function send(intent:Request,lookup=false){const id=base.id;setBusy(true);setPending(intent);try{const result=Result.parse(await request(lookup&&'commandId'in intent?{operation:'receipt',commandId:intent.commandId}:intent));if(owner.current!==id)return;
 if(result.kind==='opportunity'){setBase(result.opportunity);setText(result.opportunity.jd??'');setReason('');setPending(undefined);setServer(undefined);setStatus('JD 已保存；未推进现实阶段。');onChanged();}
 else if(result.kind==='failure'){setPending(undefined);setStatus('未保存，输入保留：'+result.code);if(result.code==='conflict'){const current=Result.parse(await request({operation:'read',id}));if(owner.current===id&&current.kind==='opportunity')setServer(current.opportunity);}}
 else setStatus('原保存尚未确认，请继续核对同一回执。');
 }catch{if(owner.current===id)setStatus('保存结果未知，输入保留；请核对同一回执，不重复创建。');}finally{if(owner.current===id)setBusy(false);}}
 return <section aria-label="岗位 JD"><h3>岗位 JD</h3>{!base.jd&&<p>尚未提供 JD；沟通、面试与 Offer 可照常记录，依赖 JD 的分析会明确列为缺项。</p>}<form onSubmit={e=>{e.preventDefault();if(!reason.trim())return;void send({operation:'save-jd',commandId:crypto.randomUUID(),id:base.id,expectedRevision:base.revision,jd:text,reason,businessTime:{kind:'unknown'}});}}><fieldset disabled={busy||!!pending}><label>JD 正文<textarea value={text} onChange={e=>setText(e.target.value)} maxLength={100000}/></label><label>JD 修改说明<input value={reason} onChange={e=>setReason(e.target.value)} required maxLength={1000}/></label><button>保存 JD</button><button type="button" onClick={()=>{if(dirty&&!window.confirm('取消未保存 JD 输入？其他表单保持原样。'))return;setText(base.jd??'');setReason('');}}>取消 JD 输入</button></fieldset></form>{server&&<aside><p>当前正式 JD：{server.jd??'尚无 JD'}</p><button onClick={()=>{setBase(server);setServer(undefined);setStatus('已更新基线，输入保留；请明确保存。');}}>保留输入并采用新基线</button></aside>}{pending&&<button disabled={busy} onClick={()=>void send(pending,true)}>核对 JD 原保存回执</button>}<p role="status">{status}</p></section>;
}
