import Database from 'better-sqlite3';import {randomUUID} from 'node:crypto';import {existsSync,readFileSync,readdirSync,lstatSync} from 'node:fs';import {mkdir,rm} from 'node:fs/promises';import path from 'node:path';
import {Request,Result,BackupSettings,Plan,type PurgeImpact,type PurgePlan} from '../../../contracts/application/schema';
import {createBackupManager,type BackupPorts} from '../../platform/backup/public';
import {durableJson,safeManagedPath,type ManagedCopy} from '../../platform/backup/managed-copies';
import type {PersistenceReference} from '../../platform/persistence/fence';
const externalLimit='只能清除本应用受管理的本地副本；不能承诺撤回已发给 Provider、用户下载/发送、系统快照或其他机器副本。';
export interface LifecyclePorts extends BackupPorts {
 targets?():Promise<{owner:string;objectId:string;label:string}[]>;
 impact(refs:readonly PersistenceReference[]):Promise<PurgeImpact>;
 markPurge(refs:readonly PersistenceReference[]):Promise<void>;
 drain(refs:readonly PersistenceReference[]):Promise<void>;
 purge(impact:PurgeImpact):Promise<void>;
 compact():Promise<void>;
 beforeActivate?():Promise<void>;
 prepareActivation?(root:string,workspaceInstance:string):Promise<void>;
 activate(input:{root:string;workspaceInstance:string;commitPointer:()=>void}):Promise<void>;
}
export function createDataLifecycle(ports:LifecyclePorts){const backups=createBackupManager(ports),registry=backups.registry;const settingsFile=path.join(ports.root,'backup-settings.json');let settings=BackupSettings.parse(existsSync(settingsFile)?JSON.parse(readFileSync(settingsFile,'utf8')):{enabled:false,periodHours:24,retainCount:14});let running=false;
 const activeCopy=()=>registry.register({relativePath:path.relative(ports.root,ports.getActiveRoot())||'.',kind:'current_workspace',state:'ready'});
 function registerActive(){const active=activeCopy();for(const [directory,kind] of Object.entries({staging:'staging',blobs:'blobs',quarantine:'quarantine',cache:'cache',proposals:'proposals',summaries:'summaries'} as const))registry.register({relativePath:path.posix.join(active.relativePath,directory),kind,state:'ready',sourceCopyId:active.id});}
 registerActive();
 // Unknown residual directories are quarantined in the maintenance manifest before any access.
 for(const top of ['backups','workspaces',path.posix.join(activeCopy().relativePath,'recovery')]){const folder=path.join(ports.root,top);if(existsSync(folder))for(const child of readdirSync(folder)){const rel=top+'/'+child;if(!registry.list().some(c=>c.relativePath===rel)&&lstatSync(path.join(folder,child)).isDirectory())registry.register({relativePath:rel,kind:'quarantine',state:'failed'});}}
 function status(){const complete=registry.list().filter(c=>c.kind==='backup'&&c.state==='ready').sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),last=complete[0]?.createdAt;return Result.parse({kind:'data_status',settings,copies:registry.list(),activeWorkspace:activeCopy().relativePath,lastCompleteAt:last,pendingPurgeCount:pendingPurges().length,automaticDue:settings.enabled&&(!last||Date.now()-Date.parse(last)>=settings.periodHours*3600000),provider:'deterministic fake only; real provider not configured'});}
 async function locked<T>(work:()=>Promise<T>){if(running)throw Error('maintenance_busy');running=true;try{return await ports.maintenance(work);}finally{running=false;}}
 const planPath=(id:string)=>safeManagedPath(ports.root,'purge-control/'+id+'.json');
 async function purge(plan:PurgePlan,selectedIds:string[],recovering=false){return locked(async()=>{if(!recovering){const current=await ports.impact(plan.impact.references);if(current.dependencies!==plan.impact.dependencies)throw Error('purge_plan_changed');}const selected=new Set(selectedIds);if([...selected].some(id=>!plan.copies.some(c=>c.id===id)))throw Error('purge_scope_invalid');const active=activeCopy();if(!selected.has(active.id))throw Error('current_workspace_required');const latest=registry.list().filter(c=>c.state!=='purged');if(latest.some(c=>!plan.copies.some(old=>old.id===c.id)))throw Error('purge_plan_changed');const intent={plan,selectedCopyIds:[...selected],state:'intent' as string,completedCopyIds:[] as string[],result:undefined as unknown};durableJson(planPath(plan.id),intent);
 try {await ports.markPurge(plan.impact.references);intent.state='marked';durableJson(planPath(plan.id),intent);await ports.drain(plan.impact.references);await ports.purge(plan.impact);for(const file of plan.impact.files)await rm(safeManagedPath(ports.getActiveRoot(),file),{force:true,recursive:true});
 for(const copy of latest.filter(c=>selected.has(c.id))){if(copy.id===active.id){intent.completedCopyIds.push(copy.id);continue;}if(path.resolve(ports.root,copy.relativePath).startsWith(path.resolve(ports.root,active.relativePath)+path.sep)&&['blobs','proposals','summaries','staging','cache'].includes(copy.kind)){intent.completedCopyIds.push(copy.id);continue;}registry.update(copy.id,{state:'purging'});await rm(safeManagedPath(ports.root,copy.relativePath),{force:false,recursive:true}).catch(error=>{if(error.code!=='ENOENT')throw error;});registry.update(copy.id,{state:'purged'});intent.completedCopyIds.push(copy.id);durableJson(planPath(plan.id),intent);}
 await ports.compact();const remaining=latest.filter(c=>!selected.has(c.id)).map(c=>c.id),result=Result.parse({kind:'purged',planId:plan.id,scope:remaining.length||plan.impact.independentReferences.length?'selected_scope':'all_managed_copies',remainingCopyIds:remaining,externalLimit});intent.result=result;intent.state='complete';durableJson(planPath(plan.id),intent);return result;
 }catch{intent.state='incomplete';durableJson(planPath(plan.id),intent);throw Error('purge_incomplete');}});}
 function pendingPurges(){const folder=path.join(ports.root,'purge-control');return !existsSync(folder)?[]:readdirSync(folder).filter(n=>n.endsWith('.json')).map(name=>JSON.parse(readFileSync(path.join(folder,name),'utf8'))).filter(record=>['intent','marked','incomplete'].includes(record.state));}
 async function recoverPendingPurges(){const pending=pendingPurges();for(const record of pending){const plan=Plan.parse(record.plan);await purge(plan,record.selectedCopyIds,true);}return pending.length;}
 async function activate(candidateId:string){return locked(async()=>{const copy=registry.get(candidateId);if(copy.kind!=='restore_candidate'||copy.state!=='ready')throw Error('restore_invalid');await ports.beforeActivate?.();await backups.verify(copy);
 // Completed and unfinished selected-copy purges must never be rolled back by a backup.
 const controls=path.join(ports.root,'purge-control');if(existsSync(controls))for(const name of readdirSync(controls).filter(n=>n.endsWith('.json'))){const control=JSON.parse(readFileSync(path.join(controls,name),'utf8'));if(control.state!=='plan'&&control.selectedCopyIds?.includes(copy.sourceCopyId))throw Error('restore_purge_blocked');if(['intent','marked','incomplete'].includes(control.state))throw Error('purge_incomplete');}
 const root=safeManagedPath(ports.root,copy.relativePath),workspaceInstance=randomUUID();if(ports.prepareActivation)await ports.prepareActivation(root,workspaceInstance);else{const db=new Database(path.join(root,'career.sqlite'));try{db.transaction(()=>{db.prepare('UPDATE platform_workspace SET instance=?').run(workspaceInstance);ports.sanitizeCandidate(db);})();db.pragma('wal_checkpoint(TRUNCATE)');}finally{db.close();}}durableJson(path.join(root,'activation.json'),{workspaceInstance,sourceCopyId:copy.sourceCopyId,validatedAt:new Date().toISOString()});await rm(path.join(root,'backup.json'));const old=activeCopy();await ports.activate({root,workspaceInstance,commitPointer(){durableJson(path.join(ports.root,'active-workspace-pointer.json'),{copyId:copy.id,relativePath:copy.relativePath,workspaceInstance});registry.update(old.id,{kind:'old_workspace'});registry.update(copy.id,{kind:'current_workspace'});}});registerActive();return Result.parse({kind:'restored',workspaceInstance,copy:registry.get(copy.id)});});}
 return {backups,status,pendingPurgeReferences:()=>pendingPurges().flatMap(record=>Plan.parse(record.plan).impact.references),recoverPendingPurges,async automaticCheck(){const state=status();if(state.kind==='data_status'&&state.automaticDue&&!running&&!pendingPurges().length)await backups.backup(settings.retainCount);},async handle(input:unknown,actor:'human'|'ai'){try{if(actor!=='human')throw Error('human_required');const request=Request.parse(input);if(pendingPurges().length&&!['data.status','data.purge.confirm'].includes(request.operation))throw Error('purge_incomplete');switch(request.operation){case 'data.status':return status();case 'data.targets':return Result.parse({kind:'data_targets',targets:await ports.targets?.()??[]});case 'data.settings':settings=request.settings;durableJson(settingsFile,settings);return status();case 'data.backup':return Result.parse({kind:'backup',copy:await backups.backup(settings.retainCount)});case 'data.restore.prepare':return Result.parse({kind:'restore_candidate',copy:await backups.prepareRestore(request.backupId)});case 'data.restore.activate':return await activate(request.candidateId);case 'data.purge.plan':return locked(async()=>{registerActive();const impact=await ports.impact(request.references),plan=Plan.parse({id:randomUUID(),createdAt:new Date().toISOString(),impact,copies:registry.list().filter(c=>c.state!=='purged'),externalLimit});durableJson(planPath(plan.id),{state:'plan',plan});return Result.parse({kind:'purge_plan',plan});});case 'data.purge.confirm':{const saved=JSON.parse(readFileSync(planPath(request.planId),'utf8'));if(saved.state==='complete')return Result.parse(saved.result);const recovering=['intent','marked','incomplete'].includes(saved.state);if(recovering&&JSON.stringify([...request.selectedCopyIds].sort())!==JSON.stringify([...saved.selectedCopyIds].sort()))throw Error('purge_scope_invalid');return await purge(Plan.parse(saved.plan),request.selectedCopyIds,recovering);}}}catch(error){return Result.parse({kind:'failure',code:error instanceof Error&&/^[a-z_]+$/.test(error.message)?error.message:'data_operation_failed'});}}};
}
export type DataLifecycle=ReturnType<typeof createDataLifecycle>;
