import {it,expect} from 'vitest';import {mkdtemp,rm} from 'node:fs/promises';import path from 'node:path';import {tmpdir} from 'node:os';import {randomUUID} from 'node:crypto';import {createNodeHost} from '../../apps/desktop/node/host';
it('browser bytes become a preview, cancel creates no Raw, and confirm is idempotent without accepting OS paths',async()=>{
 const profile=await mkdtemp(path.join(tmpdir(),'career-E1-TEST-files-'));const host=await createNodeHost({profile,artifacts:path.resolve('dist/application'),webRoot:path.resolve('dist/materials-renderer'),port:0,automaticBackups:false});
 async function call(endpoint:string,input:unknown){const response=await fetch(host.url+'/api/'+endpoint,{method:'POST',headers:{Origin:host.url,'Content-Type':'application/json',...auth},body:JSON.stringify(input)});return response.json();}
 let auth:Record<string,string>={};try{const bootstrap=await fetch(host.url+'/api/bootstrap',{method:'POST',headers:{Origin:host.url,'Content-Type':'application/json'},body:'{}'}),capability=(await bootstrap.json()).capability;auth={Cookie:bootstrap.headers.get('set-cookie')!.split(';')[0],'X-Career-Capability':capability};await call('ready',{});
  async function upload(name:string){const response=await fetch(host.url+'/api/files/materials',{method:'POST',headers:{Origin:host.url,...auth,'Content-Type':'application/octet-stream','X-Career-Upload-Metadata':encodeURIComponent(JSON.stringify({name}))},body:Buffer.from('TEST 原件 · bytes only')});return {status:response.status,...await response.json()};}
  const first=await upload('TEST.md');expect(first.result.kind).toBe('preview');expect(first.result.preview.text).toBe('TEST 原件 · bytes only');await call('materials',{operation:'cancel',importId:first.result.preview.importId});expect((await call('materials',{operation:'list'})).result.items).toEqual([]);
  const preview=(await upload('TEST.md')).result.preview,request={operation:'confirm',input:{commandId:randomUUID(),importId:preview.importId,expectedRevision:1,digest:preview.digest}};const saved=await call('materials',request);expect(saved.result.receipt.status).toBe('committed');expect((await call('materials',request)).result).toEqual(saved.result);expect((await call('materials',{operation:'list'})).result.items).toHaveLength(1);
  expect((await upload('/etc/TEST.md')).status).toBe(400);expect((await call('materials',{operation:'select',filename:'/etc/passwd'})).error).toBe('invalid_request');
 }finally{await host.close();await rm(profile,{recursive:true,force:true});}
});
