import {createHash} from 'node:crypto';
import {it,expect} from 'vitest';import {readFile} from 'node:fs/promises';import path from 'node:path';import {randomUUID} from 'node:crypto';
import {getDocument} from 'pdfjs-dist/legacy/build/pdf.mjs';import {renderSnapshot} from '../../packages/backend/domains/resume/public';import {createHeadlessPrinter} from '../../apps/desktop/capabilities/headless-pdf';
async function extract(bytes:Uint8Array){const job=getDocument({data:new Uint8Array(bytes)}),pdf=await job.promise,pages=[];for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i),content=await page.getTextContent();pages.push({size:page.view,text:content.items.filter((x:any)=>x.str).map((x:any)=>({text:x.str,xy:x.transform.map((n:number)=>Math.round(n*100)/100),width:Math.round(x.width*100)/100})),links:(await page.getAnnotations()).filter(x=>x.subtype==='Link').map(x=>({url:x.url,rect:x.rect}))});}await job.destroy();return pages;}
it('pinned Chrome preserves frozen Resume PDF geometry, Chinese, marks, alignment, links and repeatability',async()=>{
 const printer=createHeadlessPrinter(path.resolve('dist/application/pdf-environment.json'));
 const html=renderSnapshot({id:randomUUID(),resumeId:randomUUID(),opportunityId:randomUUID(),resumeRevision:1,profileRevision:1,contentHash:'0'.repeat(64),...printer.metadata(),templateVersion:'a4-basic-1',rendererVersion:'career-print-2',recordedAt:new Date().toISOString(),profile:{revision:1,name:'TEST Candidate 测试',contact:'',links:[{label:'TEST link',href:'https://example.com/'}]},content:{schemaVersion:1,layout:{template:'a4-basic',fontSize:12,identityPosition:'top',identityNameAlignment:'center'},sections:[{id:randomUUID(),kind:'summary',title:'TEST · 中文分页与格式',blocks:Array.from({length:90},(_,i)=>({id:randomUUID(),type:'paragraph',alignment:['left','center','right'][i%3],spans:[{text:`${i+1}. 蒸牛蛙 · 中文测试 ABC123 `,marks:[{type:'bold'}]},{text:'Italic 中文 ',marks:[{type:'italic'}]},{text:'TEST link',marks:[{type:'link',href:'https://example.com/'}]}]}))}]}});
 const expected=JSON.parse(await readFile('tests/fixtures/resume-pdf-baseline.json','utf8'));
 try{for(let i=0;i<3;i++){const pages=await extract(await printer.print(html));expect(pages.length).toBe(expected.pageCount);expect(pages[0].size[2]).toBeCloseTo(595,0);expect(pages[0].size[3]).toBeCloseTo(842,0);expect(pages.flatMap(p=>p.text.map(x=>x.text)).join('')).toContain('蒸牛蛙');expect(pages.reduce((n,p)=>n+p.links.length,0)).toBe(expected.linkCount);expect(createHash('sha256').update(JSON.stringify(pages)).digest('hex')).toBe(expected.normalizedSha256);}
 }finally{await printer.close();}
},90000);
