import {it,expect} from 'vitest';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import {randomUUID} from 'node:crypto';import {_electron} from 'playwright';
import {getDocument} from 'pdfjs-dist/legacy/build/pdf.mjs';import {renderSnapshot} from '../../packages/backend/domains/resume/public';import {createHeadlessPrinter} from '../../apps/desktop/capabilities/headless-pdf';
async function extract(bytes:Uint8Array){const job=getDocument({data:new Uint8Array(bytes)}),pdf=await job.promise,pages=[];for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i),content=await page.getTextContent();pages.push({size:page.view,text:content.items.filter((x:any)=>x.str).map((x:any)=>({text:x.str,xy:x.transform.map((n:number)=>Math.round(n*100)/100),width:Math.round(x.width*100)/100})),links:(await page.getAnnotations()).filter(x=>x.subtype==='Link').map(x=>({url:x.url,rect:x.rect}))});}await job.destroy();return pages;}
it('pinned Chrome preserves frozen Resume PDF geometry, Chinese, marks, alignment, links and repeatability',async()=>{
 const profile=await mkdtemp(path.join(tmpdir(),'career-E1-TEST-print-'));const printer=createHeadlessPrinter(path.resolve('dist/application/pdf-environment.json'));
 const html=renderSnapshot({id:randomUUID(),resumeId:randomUUID(),opportunityId:randomUUID(),resumeRevision:1,profileRevision:1,contentHash:'0'.repeat(64),...printer.metadata(),templateVersion:'a4-basic-1',rendererVersion:'career-print-2',recordedAt:new Date().toISOString(),profile:{revision:1,name:'TEST Candidate 测试',contact:'',links:[{label:'TEST link',href:'https://example.com/'}]},content:{schemaVersion:1,layout:{template:'a4-basic',fontSize:12,identityPosition:'top',identityNameAlignment:'center'},sections:[{id:randomUUID(),kind:'summary',title:'TEST · 中文分页与格式',blocks:Array.from({length:90},(_,i)=>({id:randomUUID(),type:'paragraph',alignment:['left','center','right'][i%3],spans:[{text:`${i+1}. 蒸牛蛙 · 中文测试 ABC123 `,marks:[{type:'bold'}]},{text:'Italic 中文 ',marks:[{type:'italic'}]},{text:'TEST link',marks:[{type:'link',href:'https://example.com/'}]}]}))}]}});
 const reference=await _electron.launch({args:[path.resolve('dist/test-support/e1-pdf-reference.cjs'),profile]});
 try{const electron=await reference.evaluate(async(_,html)=>Array.from(await (globalThis as any).printFixture(html) as Uint8Array),html);const expected=await extract(new Uint8Array(electron));expect(expected.length).toBe(3);expect(expected[0].size[2]).toBeCloseTo(595,0);expect(expected[0].size[3]).toBeCloseTo(842,0);for(let i=0;i<3;i++)expect(await extract(await printer.print(html))).toEqual(expected);expect(expected.flatMap(p=>p.text.map(x=>x.text)).join('')).toContain('蒸牛蛙');expect(expected.reduce((n,p)=>n+p.links.length,0)).toBe(91);
 }finally{await reference.close();await rm(profile,{recursive:true,force:true});}
},90000);
