import {it,expect} from 'vitest';import {mkdtemp,readdir,readFile,rm} from 'node:fs/promises';import path from 'node:path';import {tmpdir} from 'node:os';import {createNodeHost} from '../../apps/desktop/node/host';import {createNativeKeychainStorage} from '../../apps/desktop/capabilities/native-keychain';
const context={bind(){},replaceBinding(){},notify(){}};
it('TEST secret stays out of owner data/backups and restore disables service binding without reading a real key',async()=>{
 const profile=await mkdtemp(path.join(tmpdir(),'career-E1-TEST-boundary-')),options={profile,artifacts:path.resolve('dist/application'),webRoot:path.resolve('dist/materials-renderer'),port:0,automaticBackups:false};let host=await createNodeHost(options);const value='E1_SYNTHETIC_HEADER_ONLY_NOT_REAL';
 try{expect(await host.handlers['secrets/deepseek']({operation:'save',value,provider:'deepseek-v4.1-flash'},context)).toMatchObject({kind:'status',status:{configured:true,enabled:true}});expect(await host.handlers['secrets/deepseek']({operation:'check'},context)).toMatchObject({kind:'status',status:{readiness:'available'}});expect(await host.handlers['secrets/deepseek']({operation:'read'},context)).toEqual({kind:'failure',code:'invalid_request'});
  const backup:any=await host.handlers['business/application']({operation:'data.backup'},context);expect(backup.kind).toBe('backup');
  async function scan(directory:string){for(const entry of await readdir(directory,{withFileTypes:true})){const file=path.join(directory,entry.name);if(entry.isDirectory())await scan(file);else if(entry.isFile())expect((await readFile(file)).includes(Buffer.from(value))).toBe(false);}}
  await scan(profile);
  const prepared:any=await host.handlers['business/application']({operation:'data.restore.prepare',backupId:backup.copy.id},context);expect(prepared.kind).toBe('restore_candidate');expect(await host.handlers['business/application']({operation:'data.restore.activate',candidateId:prepared.copy.id,confirmed:true},context)).toMatchObject({kind:'restored'});expect(await host.handlers['secrets/deepseek']({operation:'status'},context)).toMatchObject({kind:'status',status:{configured:true,enabled:false}});await host.close();host=await createNodeHost(options);expect(await host.handlers['secrets/deepseek']({operation:'status'},context)).toMatchObject({kind:'status',status:{configured:true,enabled:false}});
 }finally{await host.close();const storage=createNativeKeychainStorage({profile,slot:'deepseek',helper:path.resolve('dist/application/career-keychain')});await storage.deleteTestRoot();storage.close();await rm(profile,{recursive:true,force:true});}
},60000);
