import {it,expect} from 'vitest';
import {mkdtemp,mkdir,writeFile,readFile,symlink,chmod,rm} from 'node:fs/promises';import path from 'node:path';import {tmpdir} from 'node:os';
import {createNodeHost} from '../../apps/desktop/node/host';
const context={bind(){},replaceBinding(){},notify(){}};
it('Node host stays responsive beyond 60 seconds of a narrow native authorization wait, without network or public key readback',async()=>{
 const root=await mkdtemp(path.join(tmpdir(),'career-E2-TEST-wait-')),artifacts=path.join(root,'artifacts'),profile=path.join(root,'profile');await mkdir(artifacts);const started=path.join(root,'native-started.json');
 for(const name of ['writer.cjs','local-search.cjs','print-worker.cjs','pdf-environment.json'])await symlink(path.resolve('dist/application',name),path.join(artifacts,name));
 const value='E2_SYNTHETIC_PRIVATE_NOT_A_KEY';await writeFile(path.join(artifacts,'career-keychain'),`#!${process.execPath}\nlet input='';process.stdin.on('data',c=>input+=c);process.stdin.on('end',()=>{const request=JSON.parse(input);if(request.action==='available'){process.stdout.write(JSON.stringify({available:true}));return;}if(request.action==='encrypt'){process.stdout.write(JSON.stringify({value:Buffer.from('opaque-TEST-cipher').toString('base64')}));return;}require('node:fs').writeFileSync(${JSON.stringify(started)},JSON.stringify({slot:request.slot,started:true}));setTimeout(()=>process.stdout.write(JSON.stringify({value:${JSON.stringify(value)}})),65000);});\n`);await chmod(path.join(artifacts,'career-keychain'),0o755);let network=0;
 const host=await createNodeHost({profile,artifacts,webRoot:path.resolve('dist/materials-renderer'),port:0,automaticBackups:false,tavilyTransport:async()=>{network++;throw Error('TEST_network_forbidden');}});
 try{expect(await host.handlers['secrets/tavily']({operation:'save',value},context)).toMatchObject({kind:'status',status:{configured:true}});const check=host.handlers['secrets/tavily']({operation:'check'},context);await expect.poll(()=>readFile(started,'utf8').then(JSON.parse).catch(()=>undefined)).toMatchObject({slot:'tavily',started:true});
  const control=Date.now();expect(await fetch(host.url+'/host-status').then(r=>r.json())).toMatchObject({ready:true});expect(Date.now()-control).toBeLessThan(2000);expect(await host.handlers['secrets/tavily']({operation:'status'},context)).toMatchObject({kind:'status',status:{authorization:'waiting_for_system_authorization'}});
  await new Promise(resolve=>setTimeout(resolve,61000));expect(await host.handlers['secrets/tavily']({operation:'status'},context)).toMatchObject({kind:'status',status:{authorization:'waiting_for_system_authorization'}});expect(await fetch(host.url+'/host-status').then(r=>r.json())).toMatchObject({ready:true});const ready=await check;expect(ready).toMatchObject({kind:'status',status:{authorization:'ready',readiness:'available'}});expect(JSON.stringify(ready)).not.toContain(value);expect(await host.handlers['secrets/tavily']({operation:'read'},context)).toEqual({kind:'failure',code:'invalid_request'});expect(network).toBe(0);
 }finally{await host.close();await rm(root,{recursive:true,force:true});}
},85000);
