import {it,expect} from 'vitest';import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';import path from 'node:path';import {tmpdir} from 'node:os';import {randomUUID,randomBytes,createHash} from 'node:crypto';
import {createNodeHost} from '../../apps/desktop/node/host';import {createNativeKeychainStorage} from '../../apps/desktop/capabilities/native-keychain';
const context={bind(){},replaceBinding(){},notify(){}};
it('legacy TEST ciphertext is untouched; native Tavily dispatch uses only its own TEST slot and public responses never return it',async()=>{
 const profile=await mkdtemp(path.join(tmpdir(),'career-E2-TEST-secrets-')),old=path.join(profile,'security-tavily'),oldBytes=randomBytes(128),generation=randomUUID();await mkdir(old);await writeFile(path.join(old,'binding.json'),JSON.stringify({enabled:true,generation}));await writeFile(path.join(old,generation+'.encrypted'),oldBytes);const hash=(b:Buffer)=>createHash('sha256').update(b).digest('hex');const before=hash(oldBytes),value='E2_SYNTHETIC_TAVILY_NOT_A_REAL_KEY';let requests=0,authMatch=false;
 const options={profile,artifacts:path.resolve('dist/application'),webRoot:path.resolve('dist/materials-renderer'),port:0,automaticBackups:false,tavilyTransport:(async (_url:any,input:any)=>{requests++;authMatch=new Headers(input.headers).get('Authorization')==='Bearer '+value;return new Response(JSON.stringify({query:'OpenAI official website',results:[{title:'TEST result',url:'https://example.test/',content:'TEST public source'}]}),{status:200});}) as typeof fetch};let host=await createNodeHost(options);
 try{expect(await host.handlers['secrets/tavily']({operation:'status'},context)).toMatchObject({kind:'status',status:{configured:false,enabled:false}});const saved=await host.handlers['secrets/tavily']({operation:'save',value},context);expect(saved).toMatchObject({kind:'status',status:{configured:true,enabled:true}});expect(JSON.stringify(saved)).not.toContain(value);expect(await host.handlers['secrets/tavily']({operation:'check'},context)).toMatchObject({kind:'status',status:{readiness:'available'}});
 const c:any=await host.handlers['business/opportunity']({operation:'company.create',commandId:randomUUID(),name:'E2 TEST public target'},context);const owner={kind:'company',id:c.company.id};const preview:any=await host.handlers['search/tavily']({operation:'preview',owner},context);expect(preview.kind).toBe('preview');const result:any=await host.handlers['search/tavily']({operation:'run',commandId:randomUUID(),owner,confirmed:true,previewDigest:preview.previewDigest},context);expect(result.kind,JSON.stringify(result)).toBe('candidate');expect(requests).toBe(1);expect(authMatch).toBe(true);expect(JSON.stringify(result)).not.toContain(value);expect(await host.handlers['secrets/tavily']({operation:'read'},context)).toEqual({kind:'failure',code:'invalid_request'});
 await host.close();host=await createNodeHost(options);expect(await host.handlers['secrets/tavily']({operation:'status'},context)).toMatchObject({kind:'status',status:{configured:true,enabled:true}});expect(await host.handlers['secrets/tavily']({operation:'check'},context)).toMatchObject({kind:'status',status:{readiness:'available'}});expect(hash(await readFile(path.join(old,generation+'.encrypted')))).toBe(before);expect(JSON.parse(await readFile(path.join(old,'binding.json'),'utf8'))).toEqual({enabled:true,generation});expect(requests).toBe(1);
 }finally{await host.close();const storage=createNativeKeychainStorage({profile,slot:'tavily',helper:path.resolve('dist/application/career-keychain')});await storage.deleteTestRoot();storage.close();await rm(profile,{recursive:true,force:true});}
},60000);
