import{test,expect,vi}from'vitest';import{mkdtemp,rm}from'node:fs/promises';import path from'node:path';import{tmpdir}from'node:os';import{createNodeHost}from'../../apps/desktop/node/host';import{createFeishuConnector}from'../../packages/backend/platform/connectors/feishu/connector';
test('local Raw preview uses one selected cached record; cancel and confirmation readiness cannot write or re-read',async()=>{
 const profile=await mkdtemp(path.join(tmpdir(),'career-F3C-TEST-')),records=vi.fn(async()=>({columns:[{name:'TEST Title',type:'text'},{name:'TEST Linked',type:'link'}],rows:[[{kind:'text' as const,value:'TEST content'},{kind:'summary' as const,category:'linked_record' as const,count:1,present:true}]],hasMore:false})),identity=vi.fn(async()=>({displayName:'TEST nickname'}));let host:Awaited<ReturnType<typeof createNodeHost>>|undefined;
 const options={profile,artifacts:path.resolve('dist/application'),webRoot:path.resolve('dist/materials-renderer'),automaticBackups:false,feishuSelectedBitable:{title:'TEST Base',url:'https://test.feishu.cn/base/TESTBitableIdentity12345'},feishuPorts:{authState:async()=>'ready' as const,readCurrentUser:identity,downloadAvatar:async()=>({bytes:Buffer.alloc(0),mime:'image/png'})},feishuBitablePorts:{listTables:async()=>({items:[{id:'tblTEST',name:'TEST Table'}],hasMore:false}),listViews:async()=>({items:[{id:'vewTEST',name:'TEST View',type:'grid'}],hasMore:false}),listFields:async()=>({items:[],hasMore:false})},feishuBitableRecordPorts:{readRecords:records}};const context={bind(){},replaceBinding(){},notify(){}};
 try{await createFeishuConnector({profileRoot:profile,...options.feishuPorts}).connect();host=await createNodeHost(options);const business=async()=>({profile:await host!.handlers['business/profile']({operation:'profile.read'},context),raw:await host!.handlers.materials({operation:'list'},context),wiki:await host!.handlers['business/wiki']({operation:'list',includeRetired:true},context)}),before=await business();const selected:any=await host.handlers['feishu/bitable/selected']({},context),tables:any=await host.handlers['feishu/bitable/tables']({selectedRef:selected.ref},context),tableRef=tables.items[0].ref,views:any=await host.handlers['feishu/bitable/views']({tableRef},context),viewRef=views.items[0].ref;await host.handlers['feishu/bitable/select-preview']({tableRef,viewRef},context);const page:any=await host.handlers['feishu/bitable/preview']({tableRef,viewRef,limit:5},context),recordRef=page.items[0].ref;expect(await host.handlers['feishu/bitable/raw-preview']({recordRef},context)).toMatchObject({reason:'selected_snapshot_unavailable'});await host.handlers['feishu/bitable/select-record']({recordRef},context);
 const boot=await fetch(host.url+'/api/bootstrap',{method:'POST',headers:{Origin:host.url,'Content-Type':'application/json'},body:'{}'}),headers={Origin:host.url,'Content-Type':'application/json',Cookie:boot.headers.get('set-cookie')!.split(';')[0]!,'X-Career-Capability':(await boot.json()).capability};await fetch(host.url+'/api/ready',{method:'POST',headers,body:'{}'});const send=(route:string,data:unknown,h=headers)=>fetch(host!.url+'/api/'+route,{method:'POST',headers:h,body:JSON.stringify(data)});
 expect((await send('feishu/bitable/raw-preview',{recordRef},{...headers,Origin:'https://other.example'})).status).toBe(403);expect((await(await send('feishu/bitable/raw-preview',{recordRef,text:'OVERRIDE'})).json()).result).toMatchObject({reason:'invalid_request'});const preview=(await(await send('feishu/bitable/raw-preview',{recordRef})).json()).result;expect(preview).toMatchObject({kind:'raw_preview',provenance:{source_type:'feishu_bitable_record',record_ref:recordRef}});expect(preview.text).toContain('TEST Linked：关联记录：1 项（未展开）');expect(JSON.stringify(preview)).not.toMatch(/TESTBitableIdentity|tblTEST|vewTEST|open_id|access_token/);expect((await(await send('feishu/bitable/raw-preview-ready',{previewRef:preview.ref,previewDigest:preview.provenance.preview_digest})).json()).result.kind).toBe('ready_for_import_confirmation');await send('feishu/bitable/raw-preview-cancel',{previewRef:preview.ref});expect(await business()).toEqual(before);expect(records).toHaveBeenCalledTimes(1);expect(identity).toHaveBeenCalledTimes(1);
 await host.close();host=await createNodeHost(options);expect(await host.handlers['feishu/bitable/raw-preview']({recordRef},context)).toMatchObject({reason:'selected_snapshot_unavailable'});expect(records).toHaveBeenCalledTimes(1);expect(await host.handlers['feishu/identity']({},context)).toMatchObject({displayName:'TEST nickname'});expect(await business()).toEqual(before);
 }finally{await host?.close();await rm(profile,{recursive:true,force:true});}
},30000);
