import {test,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createRuntimeBackend} from '../../packages/backend/bootstrap/runtime';
import {createFeishuDocumentReader} from '../../packages/backend/platform/connectors/feishu/document';
import {createFeishuDocumentImporter} from '../../packages/backend/application/materials/document-import';
import {createBitableRecordPreview} from '../../packages/backend/platform/connectors/feishu/record-preview';
import {createBitableRawPreview} from '../../packages/backend/platform/connectors/feishu/raw-preview';
import {createBitableRawImporter} from '../../packages/backend/application/materials/bitable-import';
import {Result as DataResult} from '../../packages/contracts/application/schema';
test('formal saved Raw purge closes only its bound cloud/Bitable caches while preserving an unrelated Raw and preview',async()=>{
 const root=await mkdtemp(path.join(tmpdir(),'career-cache-purge-TEST-')),runtime=await createRuntimeBackend(path.join(root,'workspaces/local'),path.resolve('dist/application/writer.cjs'),root,{automaticBackups:false,providerBinding:{enabled:false,generation:'fake-v1'}});
 const a=randomUUID(),b=randomUUID();let bodyReads=0;const cloud=createFeishuDocumentReader({getConnectionStatus:async()=>({provider:'feishu',state:'connected'}),resolveDocument:ref=>({token:ref===a?'TESTPurgeCloudSourceA12345':'TESTPreserveCloudSourceB12345',type:'docx',title:'TEST',url:null}),readMetadata:async token=>({documentToken:token,title:'TEST',revision:1}),readBlocks:async token=>{bodyReads++;return {items:[{id:token,parentId:'',type:1,children:['TEXT'],text:''},{id:'TEXT',parentId:token,type:2,children:[],text:token==='TESTPurgeCloudSourceA12345'?'TEST purge cloud body':'TEST preserve other body'}],hasMore:false};}});
 const snapshot={source:{bitableRef:randomUUID(),bitableTitle:'TEST Base',tableRef:randomUUID(),tableName:'TEST Table',viewRef:randomUUID(),viewName:'TEST View'},recordRef:randomUUID(),columns:[{name:'TEST Title',type:'text'}],cells:[{kind:'text' as const,value:'TEST purge Bitable row'}],retrievedAt:'2026-10-09T00:00:00.000Z',selectedAt:'2026-10-09T00:00:01.000Z',upstreamUpdatedAt:null},records=createBitableRecordPreview({getConnectionStatus:async()=>{throw Error('TEST EXTERNAL FORBIDDEN');},resolveView:()=>undefined,readRecords:async()=>{throw Error('TEST EXTERNAL FORBIDDEN');}},snapshot),bitable=createBitableRawPreview({readSelectedRecord:records.readSelectedRecord});
 try{const session=await runtime.connectHuman(),documents=createFeishuDocumentImporter({materials:runtime.materials,session:()=>session,resolvePreview:cloud.resolvePreview});const first=await cloud.preview({requestId:randomUUID(),selectedRef:a}),other=await cloud.preview({requestId:randomUUID(),selectedRef:b});if(first.kind!=='document_preview'||other.kind!=='document_preview')throw Error();
 const saved=await documents.importPreview({commandId:randomUUID(),previewRef:first.ref,previewDigest:first.provenance.previewDigest}),preserved=await documents.importPreview({commandId:randomUUID(),previewRef:other.ref,previewDigest:other.provenance.previewDigest});if(saved.kind!=='raw_saved'||preserved.kind!=='raw_saved')throw Error();expect(cloud.bindSavedMaterial(first.ref,saved.materialId)).toBe(true);cloud.bindSavedMaterial(other.ref,preserved.materialId);
 const table=bitable.prepare({recordRef:snapshot.recordRef});if(table.kind!=='raw_preview')throw Error();const tableSaved=await createBitableRawImporter({materials:runtime.materials,session:()=>session,resolvePreview:bitable.resolveForImport}).importPreview({commandId:randomUUID(),previewRef:table.ref,previewDigest:table.provenance.preview_digest});if(tableSaved.kind!=='raw_saved')throw Error();expect(bitable.bindSavedMaterial(table.ref,tableSaved.materialId)).toBe(true);
 const planned=DataResult.parse(await runtime.business(session,'application',{operation:'data.purge.plan',references:[{owner:'materials',objectId:saved.materialId},{owner:'materials',objectId:tableSaved.materialId}]}));if(planned.kind!=='purge_plan')throw Error(JSON.stringify(planned));const result=DataResult.parse(await runtime.business(session,'application',{operation:'data.purge.confirm',planId:planned.plan.id,selectedCopyIds:planned.plan.copies.map(copy=>copy.id),confirmed:true}));expect(result.kind).toBe('purged');
 const changed=cloud.purgeSavedMaterials([saved.materialId,tableSaved.materialId]),tableChanged=bitable.purgeSavedMaterials([saved.materialId,tableSaved.materialId]);records.invalidateRecordSnapshots(tableChanged.recordRefs,tableChanged.sources);expect(changed.trackedMaterialIds).toEqual([saved.materialId]);expect(tableChanged.trackedMaterialIds).toEqual([tableSaved.materialId]);expect(cloud.cachedPreview({selectedRef:a})).toMatchObject({kind:'failure'});expect(cloud.cachedPreview({selectedRef:b})).toEqual(other);expect(bitable.restoredMetadata()).toBeUndefined();expect(bitable.prepare({recordRef:snapshot.recordRef})).toMatchObject({kind:'failure'});expect(records.readSelectedRecord()).toBeUndefined();expect((await runtime.materials.list(session)).map(raw=>raw.id)).toEqual([preserved.materialId]);expect((await runtime.materials.read(session,preserved.materialId)).text).toBe('TEST preserve other body');await expect(runtime.materials.read(session,saved.materialId)).rejects.toThrow();expect(await runtime.materials.receipt(session,saved.commandId)).toMatchObject({status:'committed',materialId:saved.materialId});expect(await documents.importPreview({commandId:saved.commandId,previewRef:first.ref,previewDigest:first.provenance.previewDigest})).toEqual({kind:'failure',reason:'preview_unavailable'});expect(await createBitableRawImporter({materials:runtime.materials,session:()=>session,resolvePreview:bitable.resolveForImport}).importPreview({commandId:tableSaved.commandId,previewRef:table.ref,previewDigest:table.provenance.preview_digest})).toEqual({kind:'failure',reason:'preview_unavailable'});expect((await runtime.materials.list(session)).map(raw=>raw.id)).toEqual([preserved.materialId]);expect(bodyReads).toBe(2);
 }finally{cloud.dispose();bitable.dispose();records.dispose();await runtime.close();await rm(root,{recursive:true,force:true});}
},30000);
