import {test,expect,vi} from 'vitest';import{mkdtemp,rm}from'node:fs/promises';import path from'node:path';import{tmpdir}from'node:os';import{createNodeHost}from'../../apps/desktop/node/host';import{createFeishuConnector}from'../../packages/backend/platform/connectors/feishu/connector';
test('protected Browser preview uses only a confirmed table/view, retains F1 and all business data; never paginates',async()=>{
 const profile=await mkdtemp(path.join(tmpdir(),'career-F3B-TEST-')),identity=vi.fn(async()=>({displayName:'TEST nickname'})),records=vi.fn(async()=>({columns:[{name:'TEST Title',type:'text'}],rows:[[{kind:'text' as const,value:'TEST record'}]],hasMore:true}));let host:Awaited<ReturnType<typeof createNodeHost>>|undefined;
 try{await createFeishuConnector({profileRoot:profile,authState:async()=>'ready',readCurrentUser:identity,downloadAvatar:async()=>({bytes:Buffer.alloc(0),mime:'image/png'})}).connect();host=await createNodeHost({profile,artifacts:path.resolve('dist/application'),webRoot:path.resolve('dist/materials-renderer'),automaticBackups:false,feishuSelectedBitable:{title:'TEST Base',url:'https://test.feishu.cn/base/TESTBitableIdentity12345'},feishuPorts:{authState:async()=>'ready',readCurrentUser:identity,downloadAvatar:async()=>({bytes:Buffer.alloc(0),mime:'image/png'})},feishuBitablePorts:{listTables:async()=>({items:[{id:'tblTEST',name:'TEST Table'}],hasMore:false}),listViews:async()=>({items:[{id:'vewTEST',name:'TEST View',type:'grid'}],hasMore:false}),listFields:async()=>({items:[],hasMore:false})},feishuBitableRecordPorts:{readRecords:records}});
 const context={bind(){},replaceBinding(){},notify(){}};const business=async()=>({profile:await host!.handlers['business/profile']({operation:'profile.read'},context),raw:await host!.handlers.materials({operation:'list'},context),wiki:await host!.handlers['business/wiki']({operation:'list',includeRetired:true},context)}),before=await business();
 const seed:any=await host.handlers['feishu/bitable/selected']({},context),tables:any=await host.handlers['feishu/bitable/tables']({selectedRef:seed.ref},context),tableRef=tables.items[0].ref,views:any=await host.handlers['feishu/bitable/views']({tableRef},context),viewRef=views.items[0].ref;
 const boot=await fetch(host.url+'/api/bootstrap',{method:'POST',headers:{Origin:host.url,'Content-Type':'application/json'},body:'{}'}),headers={Origin:host.url,'Content-Type':'application/json',Cookie:boot.headers.get('set-cookie')!.split(';')[0]!,'X-Career-Capability':(await boot.json()).capability};await fetch(host.url+'/api/ready',{method:'POST',headers,body:'{}'});
 const send=(route:string,data:unknown,h=headers)=>fetch(host!.url+'/api/'+route,{method:'POST',headers:h,body:JSON.stringify(data)});
 expect((await send('feishu/bitable/preview',{tableRef,viewRef,limit:5},{...headers,Origin:'https://other.example'})).status).toBe(403);
 await send('feishu/bitable/select-preview',{tableRef,viewRef});expect(records).not.toHaveBeenCalled();
 for(const input of [{tableRef,viewRef,limit:6},{tableRef,viewRef,limit:5,pageToken:'NEXT'},{tableRef,viewRef,limit:5,appToken:'FORBIDDEN'}])expect((await(await send('feishu/bitable/preview',input)).json()).result).toMatchObject({kind:'failure'});expect(records).not.toHaveBeenCalled();
 const result=(await(await send('feishu/bitable/preview',{tableRef,viewRef,limit:5})).json()).result;expect(result).toMatchObject({kind:'records',hasMore:true});expect(JSON.stringify(result)).not.toMatch(/tblTEST|vewTEST|TESTBitableIdentity|open_id|token/);await send('feishu/bitable/preview',{tableRef,viewRef,limit:5});expect(records).toHaveBeenCalledTimes(1);expect(await business()).toEqual(before);expect(await host.handlers['feishu/identity']({},context)).toMatchObject({displayName:'TEST nickname'});expect(identity).toHaveBeenCalledTimes(1);expect((await send('feishu/rawApi',{})).status).toBe(404);
 }finally{await host?.close();await rm(profile,{recursive:true,force:true});}
},30000);
