import {test,expect,vi} from 'vitest';
import {randomUUID} from 'node:crypto';
import {mkdtemp,rm,mkdir,symlink} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createNodeHost} from '../../apps/desktop/node/host';
import {createFeishuConnector} from '../../packages/backend/platform/connectors/feishu/connector';
import {FeishuCacheEviction} from '../../packages/contracts/platform/feishu-cache-eviction';
async function fixture(){
 const profile=await mkdtemp(path.join(tmpdir(),'career-cache-host-purge-TEST-')),tokens=['TESTPurgeDocument12345','TESTPreserveDocument12345'],baseToken='TESTBitableIdentity12345';
 const snapshot={source:{bitableRef:randomUUID(),bitableTitle:'TEST Base',tableRef:randomUUID(),tableName:'TEST Table',viewRef:randomUUID(),viewName:'TEST View'},recordRef:randomUUID(),columns:[{name:'TEST Title',type:'text'}],cells:[{kind:'text' as const,value:'TEST restored row body'}],retrievedAt:'2026-10-09T00:00:00.000Z',selectedAt:'2026-10-09T00:00:01.000Z',upstreamUpdatedAt:null};
 const forbidden=vi.fn(async()=>{throw Error('TEST REAL EXTERNAL FORBIDDEN');}),bodies=vi.fn(async(token:string)=>({items:[{id:token,parentId:'',type:1,children:['TEXT'],text:''},{id:'TEXT',parentId:token,type:2,children:[],text:'TEST body '+token}],hasMore:false})),tables=vi.fn(async()=>({items:[{id:'tblTEST',name:'TEST Table'}],hasMore:false})),views=vi.fn(async()=>({items:[{id:'vewTEST',name:'TEST View',type:'grid'}],hasMore:false})),fields=vi.fn(async()=>({items:[{name:'TEST Title',type:'text'}],hasMore:false}));
 const identityPorts={authState:async()=> 'ready' as const,currentAccountIdentity:()=> 'a'.repeat(64),readCurrentUser:async()=>({displayName:'TEST current user'}),downloadAvatar:forbidden};await createFeishuConnector({profileRoot:profile,...identityPorts}).connect();
 const host=await createNodeHost({profile,artifacts:path.resolve('dist/application'),webRoot:path.resolve('dist/materials-renderer'),automaticBackups:false,providerBinding:{enabled:false,generation:'fake-v1'},feishuSelectedRecordSnapshot:snapshot,feishuPorts:identityPorts,feishuDiscoveryPorts:{searchDocuments:async()=>({hasMore:false,items:[...tokens.map(documentId=>({documentId,title:'TEST Document',type:'docx' as const,url:'https://test.feishu.cn/docx/'+documentId,updatedAt:null})),{documentId:baseToken,title:'TEST Metadata Base',type:'bitable',url:'https://test.feishu.cn/base/'+baseToken,updatedAt:null}]})},feishuDocumentPorts:{readMetadata:async token=>({documentToken:token,title:'TEST Document',revision:1}),readBlocks:bodies},feishuBitablePorts:{listTables:tables,listViews:views,listFields:fields},feishuBitableRecordPorts:{readRecords:forbidden},providerTransport:forbidden,tavilyTransport:forbidden});
 async function tab(){const boot=await fetch(host.url+'/api/bootstrap',{method:'POST',headers:{Origin:host.url,'Content-Type':'application/json'},body:'{}'}),headers={Origin:host.url,'Content-Type':'application/json',Cookie:boot.headers.get('set-cookie')!.split(';')[0]!,'X-Career-Capability':(await boot.json()).capability};const call=async(name:string,input:unknown)=>{const response=await fetch(host.url+'/api/'+name,{method:'POST',headers,body:JSON.stringify(input)});expect(response.status).toBe(200);return (await response.json()).result;};await call('ready',{});return{call,headers};}
 const one=await tab(),two=await tab();const discovery=await one.call('feishu/search',{searchId:randomUUID(),query:'TEST'}),sourceRefs=discovery.items;
 const structure=await one.call('feishu/bitable/tables',{selectedRef:sourceRefs[2].ref}),tableRef=structure.items[0].ref,viewList=await one.call('feishu/bitable/views',{tableRef}),fieldList=await one.call('feishu/bitable/fields',{tableRef});
 async function metadataPreserved(){expect(await one.call('feishu/bitable/tables',{selectedRef:sourceRefs[2].ref})).toEqual(structure);expect(await one.call('feishu/bitable/views',{tableRef})).toEqual(viewList);expect(await one.call('feishu/bitable/fields',{tableRef})).toEqual(fieldList);expect(tables).toHaveBeenCalledTimes(1);expect(views).toHaveBeenCalledTimes(1);expect(fields).toHaveBeenCalledTimes(1);}
 async function purge(materialIds:string[]){const plan=await one.call('business/application',{operation:'data.purge.plan',references:materialIds.map(objectId=>({owner:'materials',objectId}))});expect(plan.kind).toBe('purge_plan');const result=await one.call('business/application',{operation:'data.purge.confirm',planId:plan.plan.id,selectedCopyIds:plan.plan.copies.map((copy:{id:string})=>copy.id),confirmed:true});expect(result.kind).toBe('purged');return result;}
 return{profile,host,one,two,sourceRefs,snapshot,bodies,forbidden,metadataPreserved,purge,async close(){await host.close();await rm(profile,{recursive:true,force:true});}};
}
test('formal host binds saved sources, permanently purges targeted caches and notifies both tabs while preserving unrelated preview and metadata',async()=>{
 const f=await fixture();try{const requestA={requestId:randomUUID(),selectedRef:f.sourceRefs[0].ref},a=await f.one.call('feishu/document/preview',requestA),b=await f.one.call('feishu/document/preview',{requestId:randomUUID(),selectedRef:f.sourceRefs[1].ref}),table=await f.one.call('feishu/bitable/raw-preview',{recordRef:f.snapshot.recordRef});expect([a.kind,b.kind,table.kind]).toEqual(['document_preview','document_preview','raw_preview']);
 const request={commandId:randomUUID(),previewRef:a.ref,previewDigest:a.provenance.previewDigest},saved=await f.one.call('feishu/document/import',request),savedB=await f.one.call('feishu/document/import',{commandId:randomUUID(),previewRef:b.ref,previewDigest:b.provenance.previewDigest}),tableRequest={commandId:randomUUID(),previewRef:table.ref,previewDigest:table.provenance.preview_digest},savedTable=await f.one.call('feishu/bitable/raw-import',tableRequest);expect([saved.kind,savedB.kind,savedTable.kind]).toEqual(['raw_saved','raw_saved','raw_saved']);const reads=f.bodies.mock.calls.length;
 await f.purge([saved.materialId,savedTable.materialId]);expect(await f.one.call('feishu/document/cached-preview',{selectedRef:f.sourceRefs[0].ref})).toMatchObject({kind:'failure'});expect(await f.one.call('feishu/document/import',request)).toMatchObject({kind:'failure',reason:'preview_unavailable'});expect(await f.one.call('feishu/document/preview',requestA)).toMatchObject({kind:'failure'});expect(await f.one.call('feishu/document/cached-preview',{selectedRef:f.sourceRefs[1].ref})).toEqual(b);expect(await f.one.call('feishu/bitable/raw-preview',{recordRef:f.snapshot.recordRef})).toMatchObject({kind:'failure'});expect(await f.one.call('feishu/bitable/raw-import',tableRequest)).toMatchObject({kind:'failure',reason:'preview_unavailable'});expect(await f.one.call('feishu/bitable/record-selection',{})).toMatchObject({kind:'failure'});expect((await f.one.call('materials',{operation:'list'})).items.map((raw:{id:string})=>raw.id)).toEqual([savedB.materialId]);expect(f.bodies).toHaveBeenCalledTimes(reads);await f.metadataPreserved();
 for(const client of [f.one,f.two]){const events=await client.call('events',{}),notice=FeishuCacheEviction.parse(events.find((event:{kind:string})=>event.kind==='feishu_cache_evicted'));expect(notice).toMatchObject({all:false,materialIds:[saved.materialId,savedTable.materialId]});expect(notice.previewRefs).toEqual(expect.arrayContaining([a.ref,table.ref]));expect(notice.previewRefs).not.toContain(b.ref);expect(notice.recordRefs).toContain(f.snapshot.recordRef);expect(events).toEqual(expect.arrayContaining([expect.objectContaining({workspaceInstance:f.host.identity().workspaceInstance,references:expect.arrayContaining([{owner:'materials',objectId:saved.materialId},{owner:'materials',objectId:savedTable.materialId}])})]));}
 expect(f.forbidden).not.toHaveBeenCalled();
 }finally{await f.close();}
},30000);
test('purging an untracked historical Raw clears only body caches and emits all=true, retaining discovery and structure references',async()=>{
 const f=await fixture();try{const a=await f.one.call('feishu/document/preview',{requestId:randomUUID(),selectedRef:f.sourceRefs[0].ref}),table=await f.one.call('feishu/bitable/raw-preview',{recordRef:f.snapshot.recordRef});const upload=await fetch(f.host.url+'/api/files/materials',{method:'POST',headers:{...f.one.headers,'Content-Type':'application/octet-stream','X-Career-Upload-Metadata':encodeURIComponent(JSON.stringify({name:'TEST historic independent raw.txt'}))},body:'TEST local independent original'});expect(upload.status).toBe(200);const staged=(await upload.json()).result.preview,saved=await f.one.call('materials',{operation:'confirm',input:{commandId:randomUUID(),importId:staged.importId,expectedRevision:1,digest:staged.digest}});expect(saved.receipt.status).toBe('committed');const reads=f.bodies.mock.calls.length;
 await f.purge([saved.receipt.materialId]);expect(await f.one.call('feishu/document/cached-preview',{selectedRef:f.sourceRefs[0].ref})).toMatchObject({kind:'failure'});expect(await f.one.call('feishu/bitable/raw-preview',{recordRef:f.snapshot.recordRef})).toMatchObject({kind:'failure'});expect(await f.one.call('feishu/bitable/record-selection',{})).toMatchObject({kind:'failure'});await f.metadataPreserved();expect(f.bodies).toHaveBeenCalledTimes(reads);
 for(const client of [f.one,f.two]){const events=await client.call('events',{}),notice=FeishuCacheEviction.parse(events.find((event:{kind:string})=>event.kind==='feishu_cache_evicted'));expect(notice).toMatchObject({all:true,materialIds:[saved.receipt.materialId]});expect(notice.previewRefs).toEqual(expect.arrayContaining([a.ref,table.ref]));expect(notice.recordRefs).toContain(f.snapshot.recordRef);}
 expect(f.forbidden).not.toHaveBeenCalled();
 }finally{await f.close();}
},30000);
test('purge_incomplete with authoritative purgeReferences evicts the affected cloud body after owner fencing',async()=>{
 const f=await fixture();let faultPath:string|undefined;
 try{const preview=await f.one.call('feishu/document/preview',{requestId:randomUUID(),selectedRef:f.sourceRefs[0].ref}),saved=await f.one.call('feishu/document/import',{commandId:randomUUID(),previewRef:preview.ref,previewDigest:preview.provenance.previewDigest});expect(saved.kind).toBe('raw_saved');const plan=await f.one.call('business/application',{operation:'data.purge.plan',references:[{owner:'materials',objectId:saved.materialId}]});expect(plan.kind).toBe('purge_plan');const cache=plan.plan.copies.find((copy:{kind:string})=>copy.kind==='cache');expect(cache).toBeDefined();faultPath=path.join(f.profile,cache.relativePath);await rm(faultPath,{recursive:true,force:true});const faultTarget=path.join(f.profile,'TEST-cache-failure-target');await mkdir(faultTarget,{recursive:true});await symlink(faultTarget,faultPath);const reads=f.bodies.mock.calls.length;
 const result=await f.one.call('business/application',{operation:'data.purge.confirm',planId:plan.plan.id,selectedCopyIds:plan.plan.copies.map((copy:{id:string})=>copy.id),confirmed:true});expect(result).toMatchObject({kind:'failure',code:'purge_incomplete',purgeReferences:[{owner:'materials',objectId:saved.materialId}]});expect(await f.one.call('feishu/document/cached-preview',{selectedRef:f.sourceRefs[0].ref})).toMatchObject({kind:'failure',reason:'preview_unavailable'});expect(await f.one.call('feishu/document/import',{commandId:saved.commandId,previewRef:preview.ref,previewDigest:preview.provenance.previewDigest})).toMatchObject({kind:'failure',reason:'preview_unavailable'});expect(f.bodies).toHaveBeenCalledTimes(reads);
 for(const client of [f.one,f.two]){const events=await client.call('events',{}),notice=FeishuCacheEviction.parse(events.find((event:{kind:string})=>event.kind==='feishu_cache_evicted'));expect(notice).toMatchObject({all:false,materialIds:[saved.materialId],previewRefs:[preview.ref]});}expect(f.forbidden).not.toHaveBeenCalled();
 }finally{if(faultPath)await rm(faultPath,{force:true});await f.close();}
},30000);
