import {it,expect} from 'vitest';import Database from 'better-sqlite3';import {randomUUID,createHash} from 'node:crypto';import {mkdtemp,mkdir,writeFile,rm,readFile,symlink} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';
import {createManagedCopies} from '../../packages/backend/platform/backup/managed-copies';import {createBackupManager} from '../../packages/backend/platform/backup/public';
it('SQLite backup preserves WAL records with checked blob bytes, keeps failed points separate and validates isolated restore candidates',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'g4-backup-'));const active=path.join(root,'workspaces','initial');await mkdir(path.join(active,'blobs'),{recursive:true});const db=new Database(path.join(active,'career.sqlite'));db.pragma('journal_mode=WAL');db.exec('CREATE TABLE platform_workspace(instance TEXT);CREATE TABLE platform_blobs(id TEXT,digest TEXT,size INTEGER,state TEXT);CREATE TABLE platform_artifact_retention(blob_id TEXT,owner TEXT,object_id TEXT);CREATE TABLE fact(text TEXT);');db.prepare('INSERT INTO platform_workspace VALUES (?)').run(randomUUID());db.prepare('INSERT INTO fact VALUES (?)').run('real WAL business row');const blobId=randomUUID(),bytes=Buffer.from('immutable artifact');await writeFile(path.join(active,'blobs',blobId),bytes);db.prepare('INSERT INTO platform_blobs VALUES (?,?,?,?)').run(blobId,createHash('sha256').update(bytes).digest('hex'),bytes.length,'published');db.prepare('INSERT INTO platform_artifact_retention VALUES (?,?,?)').run(blobId,'materials','A');const registry=createManagedCopies(root);
 const manager=createBackupManager({root,registry,getActiveRoot:()=>active,maintenance:async work=>work(),sanitizeCandidate:()=>{},validateRelations:()=>{}});
 try{const first=manager.backup(1);await expect(manager.backup(1)).rejects.toThrow('maintenance_busy');const backup=await first;expect(backup.state).toBe('ready');const candidate=await manager.prepareRestore(backup.id);expect(candidate.kind).toBe('restore_candidate');const restored=new Database(path.join(root,candidate.relativePath,'career.sqlite'),{readonly:true});try{expect(restored.prepare('SELECT text FROM fact').get()).toEqual({text:'real WAL business row'});}finally{restored.close();}
 await writeFile(path.join(active,'blobs',blobId),'changed file');await expect(manager.backup(1)).rejects.toThrow('backup_incomplete');expect(manager.list().filter(c=>c.kind==='backup'&&c.state==='ready')).toHaveLength(1);expect(manager.list().some(c=>c.kind==='failed_backup'&&c.state==='failed')).toBe(true);
 await rm(path.join(root,backup.relativePath,'blobs',blobId));await symlink('/etc/passwd',path.join(root,backup.relativePath,'blobs',blobId));await expect(manager.prepareRestore(backup.id)).rejects.toThrow();
 }finally{db.close();await rm(root,{recursive:true,force:true});}
});
