import {it,expect} from 'vitest';
import Database from 'better-sqlite3';
import {randomUUID} from 'node:crypto';
import {commandMigration} from '../../packages/backend/platform/commands/receipts';
import {opportunityMigration} from '../../packages/backend/domains/opportunity/migration';
import {createOpportunityDomain} from '../../packages/backend/domains/opportunity/public';
import {createCommunicationDomain} from '../../packages/backend/domains/opportunity/communication/public';
import {communicationMigration} from '../../packages/backend/domains/opportunity/communication/migration';
function fixture(){const db=new Database(':memory:');db.exec(commandMigration);db.exec(opportunityMigration);db.exec(communicationMigration);const opportunity=createOpportunityDomain(db);const company=opportunity.handle({operation:'company.create',commandId:randomUUID(),name:'公司'});if(company.kind!=='company')throw Error();const created=opportunity.handle({operation:'create',commandId:randomUUID(),companyId:company.company.id,role:'岗位'});if(created.kind!=='opportunity')throw Error();const ports={core:opportunity.capabilities,resolveFrozenResume:()=>undefined,resolveActualArtifact:()=>undefined,retainExisting(){},hasFirstSubmission:()=>false};return {db,opportunity,id:created.opportunity.id,ports,communication:createCommunicationDomain(db,ports)};}
function record(id:string){return {operation:'communication.record',commandId:randomUUID(),opportunityId:id,medium:'phone',purpose:'salary',text:'电话讨论面试和 Offer，但只是沟通',businessTime:{kind:'unknown'},reason:'真人通话',historical:false};}
it('real call is one correctable source, ordinary Offer words do not create stage or independent original',()=>{const f=fixture();try{const intent=record(f.id);const saved=f.communication.handle(intent);expect(saved).toMatchObject({kind:'saved',revision:1});expect(f.communication.handle(intent)).toEqual(saved);if(saved.kind!=='saved')throw Error();const state=f.communication.handle({operation:'communication.read',id:saved.id});expect(state).toMatchObject({kind:'communication',communication:{text:intent.text,source:{owner:'communication',objectId:saved.id,revision:1,scope:'opportunity',opportunityId:f.id,locator:'text'}}});expect(f.opportunity.handle({operation:'read',id:f.id})).toMatchObject({kind:'opportunity',opportunity:{phase:'preparation',revision:1}});}finally{f.db.close();}});
it('correction changes source text revision, old text becomes unreadable; history and receipts retain no replaced full text',()=>{const f=fixture();try{const intent={...record(f.id),text:'独立负责，待更正的原文'};const saved=f.communication.handle(intent);if(saved.kind!=='saved')throw Error();const read=f.communication.handle({operation:'communication.read',id:saved.id});if(read.kind!=='communication')throw Error();const old=read.communication.source;const correct={operation:'communication.correct',commandId:randomUUID(),id:saved.id,expectedRevision:1,text:'参与',businessTime:{kind:'date',date:'2026-09-01'},reason:'更正真实参与范围'};expect(f.communication.handle(correct)).toMatchObject({kind:'saved',id:saved.id,revision:2});expect(f.communication.resolveSource(old)).toEqual({status:'old_version_unreadable',currentRevision:2});expect(f.communication.resolveSource({...old,revision:2})).toMatchObject({status:'available',text:'参与'});expect(JSON.stringify(f.communication.handle({operation:'communication.history',id:saved.id}))).not.toContain(intent.text);expect(JSON.stringify(f.communication.handle({operation:'communication.receipt',commandId:intent.commandId}))).not.toContain(intent.text);}finally{f.db.close();}});
it('archive preserves text source identity and readable references while concurrency still rejects old owner revision',()=>{const f=fixture();try{const saved=f.communication.handle(record(f.id));if(saved.kind!=='saved')throw Error();const state=f.communication.handle({operation:'communication.read',id:saved.id});if(state.kind!=='communication')throw Error();const source=state.communication.source;expect(f.communication.handle({operation:'communication.archive',commandId:randomUUID(),id:saved.id,expectedRevision:1,archived:true,reason:'退出当前列表'})).toMatchObject({kind:'saved',revision:2});expect(f.communication.resolveSource(source)).toMatchObject({status:'available',text:state.communication.text});expect(f.communication.handle({operation:'communication.correct',commandId:randomUUID(),id:saved.id,expectedRevision:1,text:'旧基线覆盖',businessTime:{kind:'unknown'},reason:'并发旧编辑'})).toEqual({kind:'failure',code:'conflict'});}finally{f.db.close();}});
it('communication after real ending records late and followup without reopening opportunity',()=>{const f=fixture();try{f.opportunity.handle({operation:'end',commandId:randomUUID(),id:f.id,expectedRevision:1,outcome:'withdrawn',businessTime:{kind:'unknown'},reason:'退出'});for(const [purpose,historical] of [['preemployment',false],['general',true]] as const)expect(f.communication.handle({...record(f.id),purpose,historical})).toMatchObject({kind:'saved'});expect(f.opportunity.handle({operation:'read',id:f.id})).toMatchObject({kind:'opportunity',opportunity:{result:'withdrawn',revision:2}});}finally{f.db.close();}});
it('later send is Communication with independently frozen materials, never a second first Submission',()=>{const f=fixture();try{const intent={operation:'communication.resend',commandId:randomUUID(),opportunityId:f.id,text:'补发已知原稿',resume:{kind:'file_missing',knownContent:'补发原稿 A',explanation:'历史文件已不可得'},greeting:{kind:'empty'},businessTime:{kind:'date',date:'2026-09-02'},reason:'本人确认后续再次发送',historical:true};expect(f.communication.handle(intent)).toEqual({kind:'failure',code:'first_submission_required'});const domain=createCommunicationDomain(f.db,{...f.ports,hasFirstSubmission:()=>true});const saved=domain.handle(intent);expect(saved).toMatchObject({kind:'saved'});expect(domain.handle(intent)).toEqual(saved);if(saved.kind!=='saved')throw Error();expect(domain.handle({operation:'communication.read',id:saved.id})).toMatchObject({kind:'communication',communication:{purpose:'resend',sentMaterial:intent.resume,greeting:{kind:'empty'}}});expect(f.opportunity.handle({operation:'history',id:f.id})).toMatchObject({kind:'history',items:[{type:'created'}]});}finally{f.db.close();}});
it('purge removes owner text, frozen materials, histories and any replayable receipt',()=>{const f=fixture();try{const intent=record(f.id);const saved=f.communication.handle(intent);if(saved.kind!=='saved')throw Error();expect(f.communication.describePurge(saved.id)).toMatchObject({id:saved.id,opportunityId:f.id,blobIds:[]});f.communication.purge(saved.id);expect(f.communication.handle({operation:'communication.read',id:saved.id})).toEqual({kind:'failure',code:'not_found'});expect(f.communication.handle({operation:'communication.receipt',commandId:intent.commandId})).toEqual({kind:'purged',id:saved.id});expect(f.communication.handle(intent)).toEqual({kind:'purged',id:saved.id});expect(f.communication.handle({operation:'communication.list',opportunityId:f.id})).toEqual({kind:'list',items:[]});}finally{f.db.close();}});
it('retained resend file failure cannot become historical missing and leaves no communication or successful receipt',()=>{const f=fixture();try{const domain=createCommunicationDomain(f.db,{...f.ports,hasFirstSubmission:()=>true,resolveActualArtifact:()=>({name:'actual.pdf',blobId:randomUUID(),digest:'a'.repeat(64),size:40}),retainExisting(){throw Error('storage_failed');}});const intent={operation:'communication.resend',commandId:randomUUID(),opportunityId:f.id,text:'Actual resend',resume:{kind:'retained',candidate:{kind:'artifact',id:randomUUID()}},greeting:{kind:'not_used'},businessTime:{kind:'unknown'},historical:false,reason:'真实再次发送'};expect(domain.handle(intent)).toEqual({kind:'failure',code:'storage_failed'});expect(domain.handle({operation:'communication.list',opportunityId:f.id})).toEqual({kind:'list',items:[]});expect(domain.handle({operation:'communication.receipt',commandId:intent.commandId})).toEqual({kind:'receipt_missing'});}finally{f.db.close();}});
