import {it,expect} from 'vitest';import {mkdtemp,writeFile,rm} from 'node:fs/promises';import path from 'node:path';import {tmpdir} from 'node:os';import {randomUUID} from 'node:crypto';import {createRuntimeBackend} from '../../packages/backend/bootstrap/runtime';
it('Raw → bullet Resume AI → named snapshot/copy → actual Submission/resend → preparation → complete backup/isolated restore keeps frozen lineage and unique nested IDs',async()=>{
 const root=await mkdtemp(path.join(tmpdir(),'career-g5-frozen-chain-')),runtime=await createRuntimeBackend(path.join(root,'workspaces/local'),path.resolve('dist/application/writer.cjs'),root);try{const human=await runtime.connectHuman(),call=(module:Parameters<typeof runtime.business>[1],input:unknown)=>runtime.business(human,module,input) as Promise<any>,company=(await call('opportunity',{operation:'company.create',commandId:randomUUID(),name:'Controlled lineage employer'})).company,opportunity=(await call('opportunity',{operation:'create',commandId:randomUUID(),companyId:company.id,role:'Controlled lineage role'})).opportunity;
 const file=path.join(root,'Actual personal source.txt');await writeFile(file,'Actual controlled first-person parser delivery.');const preview=await runtime.materials.selectFile(human,file),raw=await runtime.materials.confirm(human,{commandId:randomUUID(),importId:preview.importId,expectedRevision:1,digest:preview.digest});if(raw.status!=='committed')throw Error('raw');const opened=(await call('resume',{operation:'resume.open',commandId:randomUUID(),opportunityId:opportunity.id})).document,content=structuredClone(opened.content),block={id:randomUUID(),type:'bullet-list',items:[{id:randomUUID(),paragraphId:randomUUID(),spans:[{text:'Controlled own contribution',marks:[]}]}]};content.sections[0].blocks=[block];await call('resume',{operation:'resume.save',commandId:randomUUID(),resumeId:opened.id,expectedRevision:1,expectedProfileRevision:0,content});
 const prepared=await call('ai',{operation:'product.prepare',commandId:randomUUID(),input:{target:{kind:'resume-optimize',resumeId:opened.id,blockIds:[block.id],changeKinds:['rewrite','add']},sources:[raw.source],egressSourceIds:[raw.materialId],wikiIds:[],egressWikiIds:[],objects:[]},budget:{requests:1,inputBytes:524288,outputBytes:196608}});expect(prepared.kind).toBe('product_task');const operation=prepared.task.operations[0];await call('ai',{operation:'product.authorize',commandId:randomUUID(),operationId:operation.id,manifestDigest:operation.manifestDigest});let task:any;await expect.poll(async()=>{task=(await call('ai',{operation:'product.read',taskId:prepared.task.id})).task;return task.proposals.length;}).toBe(2);for(const proposal of task.proposals)expect(await call('ai',{operation:'product.decide',commandId:randomUUID(),proposalIds:[proposal.id],action:'accept'})).toMatchObject({kind:'product_decided'});
 const current=(await call('resume',{operation:'resume.read',resumeId:opened.id})).document,versionId=randomUUID(),pending=await call('resume',{operation:'resume.name-version',commandId:versionId,resumeId:opened.id,expectedRevision:current.revision,expectedProfileRevision:0,name:'Controlled frozen lineage A'});expect(pending.status).toBe('pending-job');
 // Binary boundary fixture; real Chromium PDF execution is verified by normal desktop journeys.
 const bytes=Buffer.from('%PDF-1.4\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n2 0 obj<</Type/Pages/Kids [3 0 R]/Count 1>>endobj\n3 0 obj<</Type/Page/Parent 2 0 R/MediaBox [0 0 595 842]>>endobj\ntrailer<</Root 1 0 R>>\n%%EOF');const completed=await runtime.completePdf(human,versionId,bytes);expect(completed.status).toBe('version');if(completed.status!=='version')throw Error('pdf');expect(completed.version.snapshot.blockProvenance?.some((b:any)=>b.provenance.some((p:any)=>p.owner==='materials'&&p.objectId===raw.materialId))).toBe(true);
 const second=(await call('opportunity',{operation:'create',commandId:randomUUID(),companyId:company.id,role:'Explicit copy destination'})).opportunity,other=(await call('resume',{operation:'resume.open',commandId:randomUUID(),opportunityId:second.id})).document;expect(await call('resume',{operation:'resume.copy-version',commandId:randomUUID(),resumeId:other.id,versionId,expectedRevision:1,expectedProfileRevision:0})).toMatchObject({status:'document'});
 const submission=await call('submission',{operation:'submission.record-first',commandId:randomUUID(),opportunityId:opportunity.id,expectedOpportunityRevision:1,resume:{kind:'retained',candidate:{kind:'resume',id:versionId}},greeting:{kind:'empty'},businessTime:{kind:'unknown'},reason:'Actual human selected frozen A',historical:false});expect(submission.kind).toBe('submission');expect(await call('communication',{operation:'communication.resend',commandId:randomUUID(),opportunityId:opportunity.id,text:'Actual later sending of A',resume:{kind:'retained',candidate:{kind:'resume',id:versionId}},greeting:{kind:'empty'},businessTime:{kind:'date',date:'2026-10-02'},reason:'Actual resend',historical:false})).toMatchObject({kind:'saved'});
 const now=(await call('opportunity',{operation:'read',id:opportunity.id})).opportunity,round=await call('interview',{operation:'interview.confirm',commandId:randomUUID(),opportunityId:opportunity.id,expectedOpportunityRevision:now.revision,title:'Actual interview',confirmationTime:{kind:'unknown'}}),preparation=await call('ai',{operation:'product.prepare',commandId:randomUUID(),input:{target:{kind:'interview-preparation',interviewId:round.id},sources:[],egressSourceIds:[],wikiIds:[],egressWikiIds:[],objects:[]},budget:{requests:1,inputBytes:524288,outputBytes:196608}});expect(preparation.kind).toBe('product_task');expect(preparation.task.operations[0].provenance.some((p:any)=>p.owner==='materials'&&p.objectId===raw.materialId)).toBe(true);
 const backup=await call('application',{operation:'data.backup'});expect(backup.kind,JSON.stringify(backup)).toBe('backup');expect(await call('application',{operation:'data.restore.prepare',backupId:backup.copy.id})).toMatchObject({kind:'restore_candidate'});
 }finally{await runtime.close();await rm(root,{recursive:true,force:true});}
},20000);
