import {it,expect} from 'vitest';
import {mkdtemp,rm} from 'node:fs/promises';
import path from 'node:path';import os from 'node:os';import {randomUUID} from 'node:crypto';
import {createRuntimeBackend} from '../../packages/backend/bootstrap/runtime';
import {Result as AiResult} from '../../packages/contracts/ai/schema';
import type {ProductTask} from '../../packages/contracts/ai/product';
import type {ProductTarget} from '../../packages/contracts/ai/product-context';
it('controlled product tasks use real owners: preparation/review, atomic Research and promotion, selective simulation return and Offer analysis',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'career-g5-policies-')),runtime=await createRuntimeBackend(path.join(root,'workspaces/local'),path.resolve('dist/application/writer.cjs'),root);
 try{let session=await runtime.connectHuman();const call=(module:Parameters<typeof runtime.business>[1],input:unknown)=>runtime.business(session,module,input) as Promise<any>;
 const company=(await call('opportunity',{operation:'company.create',commandId:randomUUID(),name:'G5 controlled employer'})).company;
 const opportunity=(await call('opportunity',{operation:'create',commandId:randomUUID(),companyId:company.id,role:'G5 controlled role'})).opportunity;
 await call('profile',{operation:'profile.save',commandId:randomUUID(),expectedRevision:0,name:'Explicit greeting name',contact:'Never include this contact',links:[]});
 const greetingInput={operation:'product.prepare',commandId:randomUUID(),input:{target:{kind:'greeting',opportunityId:opportunity.id,includeName:true},sources:[],egressSourceIds:[],wikiIds:[],egressWikiIds:[],objects:[]},budget:{requests:2,inputBytes:524288,outputBytes:196608}};
 const greeting=await call('ai',greetingInput);expect(greeting.kind).toBe('product_task');expect(greeting.task.operations[0].manifest.product.identityFields).toEqual([{field:'name',value:'Explicit greeting name'}]);expect(JSON.stringify(greeting.task.operations[0].manifest)).not.toContain('Never include this contact');
 const round=await call('interview',{operation:'interview.confirm',commandId:randomUUID(),opportunityId:opportunity.id,expectedOpportunityRevision:1,title:'Actual round',confirmationTime:{kind:'unknown'}});
 const prepare=async(target:ProductTarget):Promise<ProductTask>=>{const response=AiResult.parse(await call('ai',{operation:'product.prepare',commandId:randomUUID(),input:{target,sources:[],egressSourceIds:[],wikiIds:[],egressWikiIds:[],objects:[]},budget:{requests:3,inputBytes:524288,outputBytes:196608}}));expect(response.kind).toBe('product_task');if(response.kind!=='product_task')throw Error(JSON.stringify(response));return response.task;};
 const run=async(target:ProductTarget)=>{const task=await prepare(target),operation=task.operations[0];await call('ai',{operation:'product.authorize',commandId:randomUUID(),operationId:operation.id,manifestDigest:operation.manifestDigest});let result:ProductTask=task;await expect.poll(async()=>{const response=AiResult.parse(await call('ai',{operation:'product.read',taskId:task.id}));if(response.kind==='product_task')result=response.task;if(result.operations[0].state==='failure')throw Error(result.operations[0].reason);return result.operations[0].state;},{timeout:5000}).toBe('success');return result;};
 const accept=(task:ProductTask,ids=task.proposals.map(p=>p.id))=>call('ai',{operation:'product.decide',commandId:randomUUID(),proposalIds:ids,action:'accept'});
 const greetingTask=await run({kind:'greeting',opportunityId:opportunity.id,includeName:false});expect(await accept(greetingTask)).toMatchObject({kind:'product_decided',owner:'communication-draft'});expect((await call('communication',{operation:'communication.list',opportunityId:opportunity.id})).items).toEqual([]);expect((await call('communication',{operation:'communication.draft.read',opportunityId:opportunity.id})).draft.text).toContain('未发送');
 const prep=await run({kind:'interview-preparation',interviewId:round.id});expect(prep.proposals.length).toBe(1);expect(await accept(prep)).toMatchObject({kind:'product_decided',owner:'interview'});const preparedRound=(await call('interview',{operation:'interview.read',id:round.id})).session;expect(preparedRound.preparation).toContain('缺少');expect((await call('submission',{operation:'submission.read',opportunityId:opportunity.id})).kind).toBe('empty');
 await call('interview',{operation:'interview.save-document',commandId:randomUUID(),id:round.id,expectedRevision:preparedRound.revision,document:'transcript',text:'Real interviewer stated the team is building a compiler.'});
 const review=await run({kind:'interview-review',interviewId:round.id});expect(await accept(review)).toMatchObject({kind:'product_decided',owner:'interview'});
 const research=await run({kind:'research-organize',owner:{kind:'opportunity',id:opportunity.id},reviewId:round.id});expect(research.proposals.length).toBe(2);expect(await accept(research)).toMatchObject({kind:'product_decided',owner:'research'});const document=await call('research',{operation:'read',owner:{kind:'opportunity',id:opportunity.id}});expect(document.items).toHaveLength(2);expect(document.items.every((r:any)=>r.item.userConfirmed&&!r.item.independentlyVerified)).toBe(true);
 const item=document.items[0].item,promotion=await run({kind:'research-promotion',itemId:item.id,opportunityId:opportunity.id,companyId:company.id});expect(await call('ai',{operation:'product.decide',commandId:randomUUID(),proposalIds:[promotion.proposals[0].id],action:'edit-accept',edited:{...promotion.proposals[0].change.kind==='create'?promotion.proposals[0].change.content:{},body:'Cannot alter the promoted content'}})).toMatchObject({kind:'failure',code:'promotion_is_same_content_only'});expect(await accept(promotion)).toMatchObject({kind:'product_decided',owner:'research',objectId:item.id});const shared=await call('research',{operation:'read',owner:{kind:'company',id:company.id}});expect(shared.items.map((r:any)=>r.item.id)).toEqual([item.id]);expect((await call('research',{operation:'read',owner:{kind:'opportunity',id:opportunity.id}})).references[0].itemId).toBe(item.id);
 const simulation=await call('interview',{operation:'interview.create-simulation',commandId:randomUUID(),opportunityId:opportunity.id,realRoundId:round.id,title:'Practice'});const transcript='I delivered a real parser project.\nMock interviewer fiction: this employer pays 999 million.';await call('interview',{operation:'interview.save-document',commandId:randomUUID(),id:simulation.id,expectedRevision:1,document:'transcript',text:transcript});
 const returned=await prepare({kind:'simulation-return',simulationId:simulation.id,transcriptVersion:1,wikiTarget:{scope:'personal'},selectionStart:0,selectionEnd:33,confirmedRealMeaning:true,meaning:'The selected first-person parser project is my actual experience.'});expect(JSON.stringify(returned.operations[0].manifest)).not.toContain('999 million');const back=await run(returned.input!.target);expect(await accept(back)).toMatchObject({kind:'product_decided',owner:'wiki'});const knowledge=(await call('wiki',{operation:'list'})).items.find((item:any)=>item.simulationConfirmation?.simulationId===simulation.id);expect(knowledge.simulationConfirmation.confirmedByHuman).toBe(true);const resume=(await call('resume',{operation:'resume.open',commandId:randomUUID(),opportunityId:opportunity.id})).document;const selectedWikiInput={operation:'product.prepare',commandId:randomUUID(),input:{target:{kind:'resume-optimize',resumeId:resume.id,blockIds:[resume.content.sections[0].blocks[0].id]},sources:[],egressSourceIds:[],wikiIds:[knowledge.id],egressWikiIds:[knowledge.id],objects:[]},budget:{requests:1,inputBytes:524288,outputBytes:196608}};expect(await call('ai',selectedWikiInput)).toMatchObject({kind:'product_task'});expect(await call('ai',{...selectedWikiInput,commandId:randomUUID(),input:{...selectedWikiInput.input,target:{kind:'research-organize',owner:{kind:'company',id:company.id}}}})).toMatchObject({kind:'failure',code:'egress_forbidden'});await call('wiki',{operation:'edit',commandId:randomUUID(),id:knowledge.id,expectedRevision:knowledge.revision,title:knowledge.title,body:'Changed meaning after human confirmation',scope:'personal',nature:'hypothesis',sources:[],reason:'Correcting the selected meaning',businessTime:{kind:'unknown'},change:'corrected'});expect(await call('ai',{...selectedWikiInput,commandId:randomUUID()})).toMatchObject({kind:'failure',code:'egress_forbidden'});

 await expect(call('ai',{operation:'product.prepare',commandId:randomUUID(),input:{...returned.input,target:{...returned.input!.target,wikiTarget:{scope:'opportunity',scopeId:opportunity.id}}},budget:returned.budget})).rejects.toThrow();
 const now=(await call('opportunity',{operation:'read',id:opportunity.id})).opportunity;const unknown={kind:'unknown'},conditions={role:{kind:'known',value:'Engineer'},location:unknown,guaranteedCash:{kind:'known',value:'100 controlled units'},variableIncome:unknown,equity:unknown,oneTime:unknown,paymentCycle:unknown,other:unknown};await call('offer',{operation:'offer.receive',commandId:randomUUID(),opportunityId:opportunity.id,expectedOpportunityRevision:now.revision,businessTime:{kind:'unknown'},reason:'Actual received offer',conditions,original:{kind:'never_existed',explanation:'Verbal offer only'}});
 const offerBefore=await call('offer',{operation:'offer.read',opportunityId:opportunity.id}),offer=await run({kind:'offer-assist',opportunityId:opportunity.id});const originalChange=structuredClone(offer.proposals[0].change);if(originalChange.kind!=='create')throw Error('expected analysis draft');const adoptedContent={...originalChange.content,title:'User edited offer analysis',body:'User reviewed negotiation notes; no acceptance or condition change.'};expect(await call('ai',{operation:'product.decide',commandId:randomUUID(),proposalIds:[offer.proposals[0].id],action:'edit-accept',edited:adoptedContent})).toMatchObject({kind:'product_decided',owner:'ai'});const adopted=await call('ai',{operation:'product.read',taskId:offer.id});expect(adopted.task.proposals[0]).toMatchObject({state:'accepted',adoptedContent,change:originalChange});expect(await call('offer',{operation:'offer.read',opportunityId:opportunity.id})).toEqual(offerBefore);expect((await call('employment',{operation:'list'})).employments).toEqual([]);
 const backup=await call('application',{operation:'data.backup'});expect(backup.kind).toBe('backup');const candidate=await call('application',{operation:'data.restore.prepare',backupId:backup.copy.id});expect(candidate.kind).toBe('restore_candidate');const restored=await call('application',{operation:'data.restore.activate',candidateId:candidate.copy.id,confirmed:true});expect(restored.kind).toBe('restored');const oldSession=session;session=await runtime.connectHuman();expect(session.workspaceInstance).not.toBe(oldSession.workspaceInstance);expect((await call('ai',{operation:'product.read',taskId:offer.id})).task.proposals[0]).toMatchObject({adoptedContent,change:originalChange,state:'accepted'});const restoredReview=await call('ai',{operation:'product.read',taskId:review.id});expect(restoredReview.task.proposals[0].state).toBe('accepted');expect(restoredReview.task.operations[0].authorized).toBe(false);expect(restoredReview.task.operations[0].manifest).toBeUndefined();expect((await call('communication',{operation:'communication.draft.read',opportunityId:opportunity.id})).draft.revision).toBe(1);
 }finally{await runtime.close();await rm(root,{recursive:true,force:true});}
},30000);
