import {it,expect} from 'vitest';
import {mkdtemp,rm} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {randomUUID} from 'node:crypto';
import {createRuntimeBackend} from '../../packages/backend/bootstrap/runtime';
import {Result as ResumeResult} from '../../packages/contracts/resume/schema';
import {Result as OpportunityResult} from '../../packages/contracts/opportunity/schema';
import {Result as AiResult} from '../../packages/contracts/ai/schema';
it('Resume product task uses real current owner, excludes managed identity, preserves unrelated edits and applies a proposal only once',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'career-g5-resume-product-')),runtime=await createRuntimeBackend(path.join(root,'workspaces/local'),path.resolve('dist/application/writer.cjs'),root);
 try{const session=await runtime.connectHuman(),call=(module:Parameters<typeof runtime.business>[1],input:unknown)=>runtime.business(session,module,input);
 await call('profile',{operation:'profile.save',commandId:randomUUID(),expectedRevision:0,name:'Never egress managed name',contact:'Never egress managed contact',links:[]});
 const company=OpportunityResult.parse(await call('opportunity',{operation:'company.create',commandId:randomUUID(),name:'Controlled company'}));if(company.kind!=='company')throw Error('company');const opportunity=OpportunityResult.parse(await call('opportunity',{operation:'create',commandId:randomUUID(),companyId:company.company.id,role:'Engineer'}));if(opportunity.kind!=='opportunity')throw Error('opportunity');
 const opened=ResumeResult.parse(await call('resume',{operation:'resume.open',commandId:randomUUID(),opportunityId:opportunity.opportunity.id}));if(opened.status!=='document')throw Error('resume');const content=structuredClone(opened.document.content),block=content.sections[0].blocks[0];if(block.type!=='paragraph')throw Error('paragraph');block.spans=[{text:'My recorded project contribution',marks:[]}];block.alignment='center';content.layout.identityNameAlignment='center';await call('resume',{operation:'resume.save',commandId:randomUUID(),resumeId:opened.document.id,expectedRevision:1,expectedProfileRevision:1,content});
 const prepared=AiResult.parse(await call('ai',{operation:'product.prepare',commandId:randomUUID(),input:{target:{kind:'resume-optimize',resumeId:opened.document.id,blockIds:[block.id]},sources:[],egressSourceIds:[],wikiIds:[],egressWikiIds:[],objects:[]},budget:{requests:2,inputBytes:524288,outputBytes:196608}}));expect(prepared.kind).toBe('product_task');if(prepared.kind!=='product_task')throw Error(JSON.stringify(prepared));const operation=prepared.task.operations[0];expect(JSON.stringify(operation.manifest)).not.toContain('Never egress');expect(operation.manifest?.product?.identityFields).toEqual([]);expect(operation.state).toBe('not_sent');
 await call('ai',{operation:'product.authorize',commandId:randomUUID(),operationId:operation.id,manifestDigest:operation.manifestDigest});let proposalId='',additionId='';await expect.poll(async()=>{const result=AiResult.parse(await call('ai',{operation:'product.read',taskId:prepared.task.id}));if(result.kind==='product_task'){proposalId=result.task.proposals.find(p=>p.change.kind==='resume-block')?.id??'';additionId=result.task.proposals.find(p=>p.change.kind==='resume-add')?.id??'';}return proposalId;},{timeout:5000}).not.toBe('');
 const other=content.sections[1].blocks[0];if(other.type!=='paragraph')throw Error('paragraph');other.spans=[{text:'Unrelated typing while proposal is pending',marks:[]}];await call('resume',{operation:'resume.save',commandId:randomUUID(),resumeId:opened.document.id,expectedRevision:2,expectedProfileRevision:1,content});
 const intent={operation:'product.decide',commandId:randomUUID(),proposalIds:[proposalId],action:'accept'},accepted=AiResult.parse(await call('ai',intent));expect(accepted).toMatchObject({kind:'product_decided',state:'accepted'});expect(await call('ai',intent)).toEqual(accepted);const current=ResumeResult.parse(await call('resume',{operation:'resume.read',resumeId:opened.document.id}));if(current.status!=='document')throw Error('read');expect(current.document.revision).toBe(4);expect(current.document.content.layout.identityNameAlignment).toBe('center');expect(current.document.content.sections[0].blocks[0]).toMatchObject({alignment:'center'});expect(current.document.content.sections[1].blocks[0]).toEqual(other);expect(current.document.content.sections[0].blocks[0]).not.toEqual(block);
 expect(await call('ai',{...intent,commandId:randomUUID()})).toMatchObject({kind:'failure',code:'proposal_processed'});
 expect(await call('ai',{operation:'product.decide',commandId:randomUUID(),proposalIds:[additionId],action:'accept'})).toMatchObject({kind:'product_decided',state:'accepted'});
 const added=ResumeResult.parse(await call('resume',{operation:'resume.read',resumeId:opened.document.id}));if(added.status!=='document')throw Error('added');expect(added.document.content.sections[0].blocks).toHaveLength(2);expect(added.document.content.sections[1].blocks[0]).toEqual(other);
 const deletedTask=AiResult.parse(await call('ai',{operation:'product.prepare',commandId:randomUUID(),input:{target:{kind:'resume-optimize',resumeId:opened.document.id,blockIds:[block.id],changeKinds:['delete']},sources:[],egressSourceIds:[],wikiIds:[],egressWikiIds:[],objects:[]},budget:{requests:1,inputBytes:524288,outputBytes:196608}}));if(deletedTask.kind!=='product_task')throw Error('delete prepare');const deleteOperation=deletedTask.task.operations[0];await call('ai',{operation:'product.authorize',commandId:randomUUID(),operationId:deleteOperation.id,manifestDigest:deleteOperation.manifestDigest});let deletionId='';await expect.poll(async()=>{const result=AiResult.parse(await call('ai',{operation:'product.read',taskId:deletedTask.task.id}));if(result.kind==='product_task')deletionId=result.task.proposals[0]?.id??'';return deletionId;}).not.toBe('');expect(await call('ai',{operation:'product.decide',commandId:randomUUID(),proposalIds:[deletionId],action:'accept'})).toMatchObject({kind:'product_decided'});const deleted=ResumeResult.parse(await call('resume',{operation:'resume.read',resumeId:opened.document.id}));if(deleted.status!=='document')throw Error('deleted');expect(deleted.document.content.sections[0].blocks).toHaveLength(1);expect(deleted.document.content.sections[0].blocks[0].id).not.toBe(block.id);expect(deleted.document.content.sections[1].blocks[0]).toEqual(other);expect((await call('application',{operation:'data.backup'}))).toMatchObject({kind:'backup'});

 }finally{await runtime.close();await rm(root,{recursive:true,force:true});}
},20000);
