import {it,expect} from 'vitest';import {mkdtemp,writeFile,rm} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {randomUUID} from 'node:crypto';import {createRuntimeBackend} from '../../packages/backend/bootstrap/runtime';
it('Preparation uses the actual retained sending A, never current Resume B; a Submission correction invalidates authorization',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'career-g5-prep-evidence-')),runtime=await createRuntimeBackend(path.join(root,'workspaces/local'),path.resolve('dist/application/writer.cjs'),root);try{const human=await runtime.connectHuman(),call=(module:Parameters<typeof runtime.business>[1],input:unknown)=>runtime.business(human,module,input) as Promise<any>,company=(await call('opportunity',{operation:'company.create',commandId:randomUUID(),name:'Controlled preparation employer'})).company,opportunity=(await call('opportunity',{operation:'create',commandId:randomUUID(),companyId:company.id,role:'Controlled preparation role'})).opportunity;
 const file=path.join(root,'Actual Sending A.txt');await writeFile(file,'ACTUAL_SENT_A parser experience.');const artifact=await runtime.selectSentFile(human,file);const submission=await call('submission',{operation:'submission.record-first',commandId:randomUUID(),opportunityId:opportunity.id,expectedOpportunityRevision:1,resume:{kind:'retained',candidate:{kind:'artifact',id:artifact.id}},greeting:{kind:'empty'},businessTime:{kind:'unknown'},reason:'Actual sending A',historical:false});expect(submission.kind).toBe('submission');
 const opened=(await call('resume',{operation:'resume.open',commandId:randomUUID(),opportunityId:opportunity.id})).document;const content=structuredClone(opened.content);content.sections[0].blocks[0].spans=[{text:'CURRENT_B_MUST_NOT_REPLACE_SENDING',marks:[]}];await call('resume',{operation:'resume.save',commandId:randomUUID(),resumeId:opened.id,expectedRevision:1,expectedProfileRevision:0,content});
 const current=(await call('opportunity',{operation:'read',id:opportunity.id})).opportunity,round=await call('interview',{operation:'interview.confirm',commandId:randomUUID(),opportunityId:opportunity.id,expectedOpportunityRevision:current.revision,title:'Actual interview',confirmationTime:{kind:'unknown'}});const task=await call('ai',{operation:'product.prepare',commandId:randomUUID(),input:{target:{kind:'interview-preparation',interviewId:round.id},sources:[],egressSourceIds:[],wikiIds:[],egressWikiIds:[],objects:[]},budget:{requests:1,inputBytes:524288,outputBytes:196608}});expect(task.kind).toBe('product_task');const operation=task.task.operations[0];expect(operation.manifest.product.body).toContain('ACTUAL_SENT_A');expect(operation.manifest.product.body).not.toContain('[object Object]');expect(JSON.stringify(operation.manifest)).not.toContain('CURRENT_B_MUST_NOT_REPLACE_SENDING');expect(operation.productDependencies.some((d:any)=>d.owner==='submission'&&d.objectId===submission.submission.id)).toBe(true);
 const now=(await call('opportunity',{operation:'read',id:opportunity.id})).opportunity;await call('submission',{operation:'submission.correct-time',commandId:randomUUID(),opportunityId:opportunity.id,expectedOpportunityRevision:now.revision,expectedRevision:1,businessTime:{kind:'date',date:'2026-09-30'},reason:'Correcting original date'});expect(await call('ai',{operation:'product.authorize',commandId:randomUUID(),operationId:operation.id,manifestDigest:operation.manifestDigest})).toMatchObject({kind:'failure',code:'stale'});
 }finally{await runtime.close();await rm(root,{recursive:true,force:true});}
});
