import {beforeAll,it,expect} from 'vitest';import {build} from 'vite';
import {mkdtemp,rm,writeFile} from 'node:fs/promises';import path from 'node:path';import {tmpdir} from 'node:os';import {randomUUID} from 'node:crypto';
import {createRuntimeBackend} from '../../packages/backend/bootstrap/runtime';
import type {HumanSession} from '../../packages/backend/platform/runtime/sessions';
const artifact=path.resolve('dist/test-support/g6-ai-transport-writer.cjs');
beforeAll(async()=>{await build({configFile:false,logLevel:'silent',build:{emptyOutDir:false,outDir:'dist/test-support',target:'node24',lib:{entry:'packages/backend/bootstrap/writer.ts',formats:['cjs'],fileName:()=> 'g6-ai-transport-writer.cjs'},rolldownOptions:{external:[/^node:/,'better-sqlite3']}}});},20000);
async function fixture(){const root=await mkdtemp(path.join(tmpdir(),'career-g6-ai-transport-')),runtime=await createRuntimeBackend(path.join(root,'workspaces/local'),artifact,root),human=await runtime.connectHuman();const call=(module:Parameters<typeof runtime.business>[1],input:unknown)=>runtime.business(human,module,input).catch(error=>{throw Error(module+'/'+(input as {operation:string}).operation+': '+error.message);}) as Promise<any>;
 const company=(await call('opportunity',{operation:'company.create',commandId:randomUUID(),name:'G6 transport isolated company'})).company,opportunity=(await call('opportunity',{operation:'create',commandId:randomUUID(),companyId:company.id,role:'G6 role'})).opportunity,opened=await call('resume',{operation:'resume.open',commandId:randomUUID(),opportunityId:opportunity.id});return {root,runtime,human,call,company,opportunity,opened,close:async()=>{await runtime.close();await rm(root,{recursive:true,force:true});}};}
it('F2 actual runtime transport rejects AI/manual/UI/human-looking/generic/self-accept across every reality write owner',async()=>{
 const f=await fixture();try{
  const aiSession={...f.human,actor:{kind:'ai',token:f.human.actor.token}} as unknown as HumanSession,humanSpoof:HumanSession={...f.human,actor:{kind:'human',token:randomUUID()}};
  const unknown={kind:'unknown'},conditions={role:unknown,location:unknown,guaranteedCash:unknown,variableIncome:unknown,equity:unknown,oneTime:unknown,paymentCycle:unknown,other:unknown};
  const received=await f.call('offer',{operation:'offer.receive',commandId:randomUUID(),opportunityId:f.opportunity.id,expectedOpportunityRevision:1,businessTime:{kind:'unknown'},reason:'Real controlled verbal offer',conditions,original:{kind:'never_existed',explanation:'Verbal controlled fixture'}});expect(received.kind).toBe('offer');
  const prepared=await f.call('ai',{operation:'product.prepare',commandId:randomUUID(),input:{target:{kind:'greeting',opportunityId:f.opportunity.id,includeName:false},sources:[],egressSourceIds:[],wikiIds:[],egressWikiIds:[],objects:[]},budget:{requests:1,inputBytes:524288,outputBytes:196608}}),op=prepared.task.operations[0];await f.call('ai',{operation:'product.authorize',commandId:randomUUID(),operationId:op.id,manifestDigest:op.manifestDigest});let proposal:any;await expect.poll(async()=>{proposal=(await f.call('ai',{operation:'product.read',taskId:prepared.task.id})).task.proposals[0];return !!proposal;}).toBe(true);
  const current=(await f.call('opportunity',{operation:'read',id:f.opportunity.id})).opportunity,before={opportunity:current,history:await f.call('opportunity',{operation:'history',id:current.id}),offer:await f.call('offer',{operation:'offer.read',opportunityId:current.id}),resume:await f.call('resume',{operation:'resume.read',resumeId:f.opened.document.id}),wiki:await f.call('wiki',{operation:'list'}),employment:await f.call('employment',{operation:'list'}),submission:await f.call('submission',{operation:'submission.read',opportunityId:current.id})};
  const attacks:[Parameters<typeof f.runtime.business>[1],unknown][]=[
   ['wiki',{operation:'create',commandId:randomUUID(),title:'AI manual draft',body:'Must remain non-fact',scope:'personal',nature:'observation',sources:[]}],
   ['opportunity',{operation:'record-stage',commandId:randomUUID(),id:current.id,expectedRevision:current.revision,stage:'submitted',reason:'human-looking UI command',businessTime:unknown}],
   ['resume',{operation:'resume.save',commandId:randomUUID(),resumeId:f.opened.document.id,expectedRevision:1,expectedProfileRevision:0,content:f.opened.document.content}],
   ['offer',{operation:'offer.accept',commandId:randomUUID(),opportunityId:current.id,expectedOpportunityRevision:current.revision,expectedOfferRevision:1,businessTime:unknown,reason:'AI cannot accept'}],
   ['employment',{operation:'create',commandId:randomUUID(),company:'G6 AI spoof',role:'Fake employment',businessTime:unknown}],
   ['submission',{operation:'submission.record-first',commandId:randomUUID(),opportunityId:current.id,expectedOpportunityRevision:current.revision,resume:{kind:'not_used'},greeting:{kind:'not_used'},businessTime:unknown,historical:true,reason:'AI cannot record reality'}],
   ['ai',{operation:'product.decide',commandId:randomUUID(),proposalIds:[proposal.id],action:'accept'}]
  ];
  for(const [module,input] of attacks){await expect(f.runtime.business(aiSession,module,input)).rejects.toThrow('invalid_capability');await expect(f.runtime.business(humanSpoof,module,{...input as object,userApproved:true,actor:'human'})).rejects.toThrow('invalid_capability');}
  expect({opportunity:(await f.call('opportunity',{operation:'read',id:current.id})).opportunity,history:await f.call('opportunity',{operation:'history',id:current.id}),offer:await f.call('offer',{operation:'offer.read',opportunityId:current.id}),resume:await f.call('resume',{operation:'resume.read',resumeId:f.opened.document.id}),wiki:await f.call('wiki',{operation:'list'}),employment:await f.call('employment',{operation:'list'}),submission:await f.call('submission',{operation:'submission.read',opportunityId:current.id})}).toEqual(before);
  expect((await f.call('ai',{operation:'product.read',taskId:prepared.task.id})).task.proposals[0].state).toBe('pending');
 }finally{await f.close();}
});
it('RV-P1-03 frozen export rejects stale Resume/Profile and late PDF retains original two revisions and marks',async()=>{
 const f=await fixture();try{
  await f.call('profile',{operation:'profile.save',commandId:randomUUID(),expectedRevision:0,name:'Profile A',contact:'A@example.test',links:[]});const content=structuredClone(f.opened.document.content);content.sections[0].blocks[0].spans=[{text:'Plain original ',marks:[]},{text:'frozen bold',marks:[{type:'bold'}]},{text:' and italic',marks:[{type:'italic'}]}];await f.call('resume',{operation:'resume.save',commandId:randomUUID(),resumeId:f.opened.document.id,expectedRevision:1,expectedProfileRevision:1,content});
  const aId=randomUUID(),a=await f.call('resume',{operation:'resume.export',commandId:aId,resumeId:f.opened.document.id,expectedRevision:2,expectedProfileRevision:1});expect(a.status).toBe('pending-job');expect((await f.runtime.printHtml(f.human,aId)).html).toContain('Profile A');
  await f.call('profile',{operation:'profile.save',commandId:randomUUID(),expectedRevision:1,name:'Profile B',contact:'B@example.test',links:[]});const newer=structuredClone(content);newer.sections[0].blocks[0].spans=[{text:'Current Resume B',marks:[]}];await f.call('resume',{operation:'resume.save',commandId:randomUUID(),resumeId:f.opened.document.id,expectedRevision:2,expectedProfileRevision:2,content:newer});
  for(const [expectedRevision,expectedProfileRevision] of [[2,2],[3,1]]){expect(await f.call('resume',{operation:'resume.export',commandId:randomUUID(),resumeId:f.opened.document.id,expectedRevision,expectedProfileRevision})).toMatchObject({status:'conflict'});}
  const completed=await f.runtime.completePdf(f.human,aId,Buffer.from('%PDF-1.4\nOriginal A controlled local bytes\n%%EOF'));expect(completed).toMatchObject({status:'version',version:{id:aId,snapshot:{resumeRevision:2,profileRevision:1,profile:{name:'Profile A'},content}}});
  const current=await f.call('resume',{operation:'resume.read',resumeId:f.opened.document.id});expect(current).toMatchObject({status:'document',document:{revision:3,content:newer},profile:{revision:2,name:'Profile B'}});expect(await f.call('resume',{operation:'resume.version',resumeId:f.opened.document.id,versionId:aId})).toEqual(completed);
  // This is persistence binding evidence, not a claim that synthetic bytes replace Chromium typography acceptance.
 }finally{await f.close();}
});
it('RV-P1-07 evidence Raw has no ordinary overwrite; Transcript can correct and real Review without Search produces Research while Simulation cannot',async()=>{
 const f=await fixture();try{
  const file=path.join(f.root,'original.txt');await writeFile(file,'G6 evidence Raw original');const preview=await f.runtime.materials.selectFile(f.human,file),raw=await f.runtime.materials.confirm(f.human,{commandId:randomUUID(),importId:preview.importId,expectedRevision:1,digest:preview.digest});if(raw.status!=='committed')throw Error('import');
  await expect(f.call('materials' as any,{operation:'materials.save',commandId:randomUUID(),id:raw.materialId,text:'AI tries ordinary overwrite'})).rejects.toThrow();expect((await f.runtime.materials.read(f.human,raw.materialId)).text).toBe('G6 evidence Raw original');
  const round=await f.call('interview',{operation:'interview.confirm',commandId:randomUUID(),opportunityId:f.opportunity.id,expectedOpportunityRevision:1,title:'G6 actual review record',confirmationTime:{kind:'unknown'}});
  expect((await f.call('interview',{operation:'interview.save-document',commandId:randomUUID(),id:round.id,expectedRevision:1,document:'transcript',text:'Original real statement'})).kind).toBe('saved');expect((await f.call('interview',{operation:'interview.save-document',commandId:randomUUID(),id:round.id,expectedRevision:2,document:'transcript',text:'Corrected real statement'})).kind).toBe('saved');expect((await f.call('interview',{operation:'interview.save-document',commandId:randomUUID(),id:round.id,expectedRevision:3,document:'final-review',text:'Real review derived from corrected interview'})).kind).toBe('saved');
  const prepare=(reviewId:string)=>f.call('ai',{operation:'product.prepare',commandId:randomUUID(),input:{target:{kind:'research-organize',owner:{kind:'opportunity',id:f.opportunity.id},reviewId},sources:[],egressSourceIds:[],wikiIds:[],egressWikiIds:[],objects:[]},budget:{requests:1,inputBytes:524288,outputBytes:196608}});
  const task=await prepare(round.id);expect(task.kind).toBe('product_task');expect(task.task.operations[0].manifest.product.body).toContain('Real review derived');expect(task.task.operations[0].manifest.materials).toEqual([]);const op=task.task.operations[0];await f.call('ai',{operation:'product.authorize',commandId:randomUUID(),operationId:op.id,manifestDigest:op.manifestDigest});let result:any;await expect.poll(async()=>{result=await f.call('ai',{operation:'product.read',taskId:task.task.id});return result.task.operations[0].state;}).toBe('success');expect(result.task.proposals).toHaveLength(2);expect((await f.call('research',{operation:'read',owner:{kind:'opportunity',id:f.opportunity.id}})).items).toEqual([]);
  const simulation=await f.call('interview',{operation:'interview.create-simulation',commandId:randomUUID(),opportunityId:f.opportunity.id,realRoundId:round.id,title:'G6 fictional practice'});await f.call('interview',{operation:'interview.save-document',commandId:randomUUID(),id:simulation.id,expectedRevision:1,document:'transcript',text:'Fictional employer pays impossible amount'});await f.call('interview',{operation:'interview.save-document',commandId:randomUUID(),id:simulation.id,expectedRevision:2,document:'final-review',text:'Fictional review'});expect(await prepare(simulation.id)).toMatchObject({kind:'failure',code:'source_unavailable'});
 }finally{await f.close();}
});
