import {it,expect} from 'vitest';
import {mkdtemp,writeFile,rm,readFile,readdir,mkdir} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {randomUUID} from 'node:crypto';
import {createRuntimeBackend} from '../../packages/backend/bootstrap/runtime';
import {Result as AiResult} from '../../packages/contracts/ai/schema';
import {Result as DataResult} from '../../packages/contracts/application/schema';
it('real restore changes all three identities, rejects old capability, preserves pending Proposal without reviving execution or device Secret',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'g6-f3-restore-runtime-')),active=path.join(root,'workspaces/local'),source=path.join(root,'fixture.txt');await writeFile(source,'Deterministic fake-only source A');await mkdir(path.join(root,'security'));await writeFile(path.join(root,'security','vault'),'FAKE_DEVICE_SECRET_NOT_IN_BACKUP');const runtime=await createRuntimeBackend(active,path.resolve('dist/application/writer.cjs'),root);
 try{let session=await runtime.connectHuman();const preview=await runtime.materials.selectFile(session,source),receipt=await runtime.materials.confirm(session,{commandId:randomUUID(),importId:preview.importId,expectedRevision:1,digest:preview.digest});if(receipt.status!=='committed')throw Error('raw');const prepared=AiResult.parse(await runtime.business(session,'ai',{operation:'ai.prepare',commandId:randomUUID(),sources:[receipt.source],target:{scope:'personal'},budget:{requests:2,inputBytes:524288,outputBytes:196608}}));if(prepared.kind!=='task')throw Error('task');const operation=prepared.task.operations[0]!;await runtime.business(session,'ai',{operation:'ai.authorize',commandId:randomUUID(),operationId:operation.id,manifestDigest:operation.manifestDigest});let proposalId='';await expect.poll(async()=>{const state=AiResult.parse(await runtime.business(session,'ai',{operation:'ai.read',taskId:prepared.task.id}));if(state.kind==='task')proposalId=state.task.proposals[0]?.id??'';return proposalId;},{timeout:5000}).not.toBe('');
 const backup=DataResult.parse(await runtime.business(session,'application',{operation:'data.backup'}));if(backup.kind!=='backup')throw Error('backup');expect((await readFile(path.join(root,backup.copy.relativePath,'career.sqlite'))).includes(Buffer.from('FAKE_DEVICE_SECRET_NOT_IN_BACKUP'))).toBe(false);const candidate=DataResult.parse(await runtime.business(session,'application',{operation:'data.restore.prepare',backupId:backup.copy.id}));if(candidate.kind!=='restore_candidate')throw Error('candidate');expect(await readdir(path.join(root,candidate.copy.relativePath))).not.toContain('security');const old=session;const restored=DataResult.parse(await runtime.business(session,'application',{operation:'data.restore.activate',candidateId:candidate.copy.id,confirmed:true}));expect(restored.kind).toBe('restored');session=await runtime.connectHuman();for(const key of ['workspaceInstance','backendGeneration','connectionGeneration'] as const)expect(session[key]).not.toBe(old[key]);await expect(runtime.business(old,'ai',{operation:'ai.read',taskId:prepared.task.id})).rejects.toThrow('invalid_capability');const state=AiResult.parse(await runtime.business(session,'ai',{operation:'ai.read',taskId:prepared.task.id}));expect(state).toMatchObject({kind:'task',task:{operations:[{authorized:false}],proposals:[{id:proposalId,state:'pending'}]}});
 const accepted=AiResult.parse(await runtime.business(session,'ai',{operation:'ai.decide',commandId:randomUUID(),proposalId,action:'accept'}));expect(accepted).toMatchObject({kind:'decided',state:'accepted'});expect(await readFile(path.join(root,'security','vault'),'utf8')).toBe('FAKE_DEVICE_SECRET_NOT_IN_BACKUP');
 }finally{await runtime.close();await rm(root,{recursive:true,force:true});}
},30000);
it('concurrent real backup and GC serialize, and purge either waits for the registered backup or fails visibly before deletion',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'g6-f3-maintenance-')),active=path.join(root,'workspaces/local'),source=path.join(root,'fixture.txt');await writeFile(source,'SENSITIVE_G6_CONCURRENT_PURGE');const runtime=await createRuntimeBackend(active,path.resolve('dist/application/writer.cjs'),root);
 try{const session=await runtime.connectHuman(),preview=await runtime.materials.selectFile(session,source),receipt=await runtime.materials.confirm(session,{commandId:randomUUID(),importId:preview.importId,expectedRevision:1,digest:preview.digest});if(receipt.status!=='committed')throw Error('raw');const [saved]=await Promise.all([runtime.business(session,'application',{operation:'data.backup'}),runtime.materials.collectGarbage()]);const backup=DataResult.parse(saved);if(backup.kind!=='backup')throw Error('backup');expect(await runtime.materials.read(session,receipt.materialId)).toMatchObject({text:'SENSITIVE_G6_CONCURRENT_PURGE'});
 const saving=runtime.business(session,'application',{operation:'data.backup'}),planning=runtime.business(session,'application',{operation:'data.purge.plan',references:[{owner:'materials',objectId:receipt.materialId}]}).catch(error=>({kind:'failure',code:error.message}));const [second,planned]=await Promise.all([saving,planning]);expect(DataResult.parse(second).kind).toBe('backup');let plan=DataResult.parse(planned);if(plan.kind==='failure'){expect(plan.code).toBe('maintenance_busy');plan=DataResult.parse(await runtime.business(session,'application',{operation:'data.purge.plan',references:[{owner:'materials',objectId:receipt.materialId}]}));}if(plan.kind!=='purge_plan')throw Error('plan');expect(plan.plan.copies.filter(copy=>copy.kind==='backup'&&copy.state==='ready')).toHaveLength(2);const erased=await runtime.business(session,'application',{operation:'data.purge.confirm',planId:plan.plan.id,selectedCopyIds:plan.plan.copies.map(copy=>copy.id),confirmed:true});expect(erased).toMatchObject({kind:'purged',scope:'all_managed_copies'});expect(await runtime.materials.list(session)).toEqual([]);
 }finally{await runtime.close();await rm(root,{recursive:true,force:true});}
},30000);
