import {it,expect,afterEach,vi} from 'vitest';
import Database from 'better-sqlite3';
import {randomUUID,createHash} from 'node:crypto';
import {mkdtemp,mkdir,writeFile,rm,readFile,readdir,symlink} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {createManagedCopies} from '../../packages/backend/platform/backup/managed-copies';
import {createBackupManager,type BackupPorts} from '../../packages/backend/platform/backup/public';
const allocated:{root:string;db:Database.Database}[]=[];
afterEach(async()=>{vi.restoreAllMocks();for(const f of allocated.splice(0)){if(f.db.open)f.db.close();await rm(f.root,{recursive:true,force:true});}});
async function fixture(){
 const root=await mkdtemp(path.join(os.tmpdir(),'g6-f3-')),active=path.join(root,'workspaces','local');await mkdir(path.join(active,'blobs'),{recursive:true});
 const db=new Database(path.join(active,'career.sqlite'));allocated.push({root,db});db.pragma('journal_mode=WAL');db.exec('CREATE TABLE platform_workspace(instance TEXT);CREATE TABLE platform_blobs(id TEXT,digest TEXT,size INTEGER,state TEXT);CREATE TABLE platform_artifact_retention(blob_id TEXT,owner TEXT,object_id TEXT);CREATE TABLE fact(body TEXT);CREATE TABLE excluded(body TEXT);');
 db.prepare('INSERT INTO platform_workspace VALUES (?)').run(randomUUID());db.prepare('INSERT INTO fact VALUES (?)').run('retained career fact');db.prepare('INSERT INTO excluded VALUES (?)').run('SENSITIVE_G6_EXCLUDED_BODY_'+'private'.repeat(1000));
 const blobId=randomUUID(),bytes=Buffer.from('frozen PDF / retained raw fixture'),digest=createHash('sha256').update(bytes).digest('hex');await writeFile(path.join(active,'blobs',blobId),bytes);db.prepare('INSERT INTO platform_blobs VALUES (?,?,?,?)').run(blobId,digest,bytes.length,'published');db.prepare('INSERT INTO platform_artifact_retention VALUES (?,?,?)').run(blobId,'materials','A');
 const registry=createManagedCopies(root);const ports:BackupPorts={root,registry,getActiveRoot:()=>active,maintenance:async work=>work(),sanitizeCandidate:candidate=>candidate.prepare('DELETE FROM excluded').run(),validateRelations:()=>{}};
 return {root,active,db,blobId,bytes,ports,registry,manager:createBackupManager(ports)};
}
it('a completed backup publishes only compact filtered SQLite and retained blobs, with no excluded body or device security file',async()=>{
 const f=await fixture();await mkdir(path.join(f.root,'security'));await writeFile(path.join(f.root,'security','vault'),'FAKE_TEST_SECRET_G6');const backup=await f.manager.backup();const folder=path.join(f.root,backup.relativePath);expect((await readdir(folder)).sort()).toEqual(['backup.json','blobs','career.sqlite']);const bytes=await readFile(path.join(folder,'career.sqlite'));expect(bytes.includes(Buffer.from('SENSITIVE_G6_EXCLUDED_BODY_'))).toBe(false);expect(bytes.includes(Buffer.from('FAKE_TEST_SECRET_G6'))).toBe(false);const copy=new Database(path.join(folder,'career.sqlite'),{readonly:true});try{expect(copy.prepare('SELECT body FROM fact').get()).toEqual({body:'retained career fact'});expect(copy.prepare('SELECT * FROM excluded').all()).toEqual([]);}finally{copy.close();}await expect(f.manager.verify(backup)).resolves.toMatchObject({id:backup.id});
});
it.each(['missing','changed','extra','symlink','traversal','corrupt'] as const)('untrusted restore package rejects %s without replacing or modifying active SQLite',async attack=>{
 const f=await fixture(),backup=await f.manager.backup(),folder=path.join(f.root,backup.relativePath),blob=path.join(folder,'blobs',f.blobId);
 if(attack==='missing')await rm(blob);
 if(attack==='changed')await writeFile(blob,'wrong bytes');
 if(attack==='extra')await writeFile(path.join(folder,'unexpected'),'unexpected data');
 if(attack==='symlink'){await rm(blob);await symlink(path.join(f.active,'blobs',f.blobId),blob);}
 if(attack==='traversal'){const filename=path.join(folder,'backup.json'),manifest=JSON.parse(await readFile(filename,'utf8'));manifest.artifacts[0].id='../outside';await writeFile(filename,JSON.stringify(manifest));}
 if(attack==='corrupt'){const filename=path.join(folder,'career.sqlite');await writeFile(filename,'not SQLite');const manifestFile=path.join(folder,'backup.json'),manifest=JSON.parse(await readFile(manifestFile,'utf8'));manifest.databaseDigest=createHash('sha256').update('not SQLite').digest('hex');await writeFile(manifestFile,JSON.stringify(manifest));}
 await expect(f.manager.prepareRestore(backup.id)).rejects.toThrow();expect(f.db.prepare('SELECT body FROM fact').get()).toEqual({body:'retained career fact'});expect(f.registry.list().filter(copy=>copy.kind==='restore_candidate'&&copy.state==='ready')).toHaveLength(0);
});
it.each(['missing','hash mismatch'] as const)('failed backup %s cannot prune the previous complete point',async failure=>{
 const f=await fixture(),complete=await f.manager.backup(1);if(failure==='missing')await rm(path.join(f.active,'blobs',f.blobId));else await writeFile(path.join(f.active,'blobs',f.blobId),'bad');await expect(f.manager.backup(1)).rejects.toThrow('backup_incomplete');expect(f.registry.get(complete.id).state).toBe('ready');await expect(f.manager.verify(complete)).resolves.toMatchObject({id:complete.id});expect(f.registry.list().filter(copy=>copy.kind==='failed_backup'&&copy.state==='failed')).toHaveLength(1);
});

import {createPersistenceFence,createPersistenceSinkGate,persistenceMigration} from '../../packages/backend/platform/persistence/fence';
it('purge drains and discards affected AI/parser/import/PDF staging, including closed results, while unrelated staging survives',async()=>{
 const f=await fixture();f.db.exec(persistenceMigration);await mkdir(path.join(f.active,'staging'));const A={owner:'materials',objectId:'A'},B={owner:'materials',objectId:'B'},fence=createPersistenceFence(f.db,{workspaceInstance:'workspace',backendGeneration:'backend'}),gate=createPersistenceSinkGate(token=>fence.assert(token));
 const producers=['ai','parser','import','pdf'].map(producerId=>({token:fence.capture({producerId,inputs:[A],targets:[]}),file:path.join(f.active,'staging',producerId)}));
 const opened=await Promise.all(producers.map(async producer=>{const sink=await gate.controlledSink(producer.token,producer.file);await sink.append(Buffer.from('SENSITIVE_A_'+producer.token.producerId));return sink;}));await opened[1]!.close();
 const safe=fence.capture({producerId:'safe',inputs:[B],targets:[]}),safeFile=path.join(f.active,'staging','safe'),safeSink=await gate.controlledSink(safe,safeFile);await safeSink.append(Buffer.from('public B'));await safeSink.close();f.db.transaction(()=>fence.markPurge([A]))();
 await gate.drainAndDiscard([A]);
 for(const producer of producers){await expect(readFile(producer.file)).rejects.toThrow();expect(()=>fence.assert(producer.token)).toThrow('persistence_denied');await expect(gate.withLease(producer.token,async()=>writeFile(producer.file,'late body / summary / patch / PDF'))).rejects.toThrow('persistence_denied');}
 for(const sink of opened)await expect(sink.append(Buffer.from('late'))).rejects.toThrow('persistence_denied');expect(await readFile(safeFile,'utf8')).toBe('public B');
});

it('restart classifies an interrupted registered backup candidate as failed, never as a complete point',async()=>{
 const f=await fixture(),complete=await f.manager.backup(1),incomplete=f.registry.register({kind:'backup',relativePath:'backups/'+randomUUID()});await mkdir(path.join(f.root,incomplete.relativePath));await writeFile(path.join(f.root,incomplete.relativePath,'working.sqlite'),'partial bytes');const restarted=createBackupManager({...f.ports,registry:createManagedCopies(f.root)});expect(restarted.registry.get(incomplete.id)).toMatchObject({kind:'failed_backup',state:'failed'});expect(restarted.registry.get(complete.id).state).toBe('ready');
});

import {createDataLifecycle} from '../../packages/backend/application/data-lifecycle/public';
it.each([false,true])('all managed copy kinds are visible and approved scope clears sensitive bytes; retained backup=%s is honestly reported',async retainBackup=>{
 const f=await fixture();f.db.exec(persistenceMigration);const marker='SENSITIVE_G6_ALL_COPIES_BODY';f.db.prepare('UPDATE fact SET body=?').run(marker);const fence=createPersistenceFence(f.db,{workspaceInstance:'w',backendGeneration:'b'}),gate=createPersistenceSinkGate(token=>fence.assert(token)),A={owner:'materials',objectId:'A'};
 const lifecycle=createDataLifecycle({...f.ports,impact:async refs=>({references:[...refs],description:'permanently remove selected material',independentReferences:[],files:['blobs/'+f.blobId],dependencies:'A-current'}),markPurge:async refs=>{f.db.transaction(()=>fence.markPurge(refs))();},drain:refs=>gate.drainAndDiscard(refs),purge:async()=>{f.db.transaction(()=>{f.db.prepare('DELETE FROM fact').run();f.db.prepare('DELETE FROM excluded').run();f.db.prepare('DELETE FROM platform_artifact_retention').run();})();},compact:async()=>{f.db.pragma('wal_checkpoint(TRUNCATE)');f.db.exec('VACUUM');f.db.pragma('wal_checkpoint(TRUNCATE)');},activate:async()=>{throw Error('not_requested');}});
 const saved=await lifecycle.handle({operation:'data.backup'},'human');if(saved.kind!=='backup')throw Error('backup');
 const extra=[];for(const kind of ['old_workspace','restore_candidate','quarantine','failed_backup','staging','blobs','proposals','summaries','cache'] as const){const copy=f.registry.register({relativePath:'copies/'+kind,kind,state:kind==='failed_backup'?'failed':'ready'});extra.push(copy);await mkdir(path.join(f.root,copy.relativePath),{recursive:true});await writeFile(path.join(f.root,copy.relativePath,'sensitive.txt'),marker);}
 await mkdir(path.join(f.active,'staging'),{recursive:true});const token=fence.capture({producerId:'late-ai',inputs:[A],targets:[]}),staged=path.join(f.active,'staging','late-ai'),sink=await gate.controlledSink(token,staged);await sink.append(Buffer.from(marker));await sink.close();
 const plan=await lifecycle.handle({operation:'data.purge.plan',references:[A]},'human');if(plan.kind!=='purge_plan')throw Error('plan');expect(plan.plan.copies.map(copy=>copy.kind)).toEqual(expect.arrayContaining(['current_workspace','old_workspace','restore_candidate','quarantine','failed_backup','backup','staging','blobs','proposals','summaries','cache']));
 const selected=plan.plan.copies.filter(copy=>!retainBackup||copy.id!==saved.copy.id).map(copy=>copy.id),result=await lifecycle.handle({operation:'data.purge.confirm',planId:plan.plan.id,selectedCopyIds:selected,confirmed:true},'human');expect(result).toMatchObject({kind:'purged',scope:retainBackup?'selected_scope':'all_managed_copies',remainingCopyIds:retainBackup?[saved.copy.id]:[]});
 for(const copy of extra)await expect(readFile(path.join(f.root,copy.relativePath,'sensitive.txt'))).rejects.toThrow();await expect(readFile(staged)).rejects.toThrow();expect(f.db.prepare('SELECT * FROM fact').all()).toEqual([]);expect((await readFile(path.join(f.active,'career.sqlite'))).includes(Buffer.from(marker))).toBe(false);expect((await readFile(path.join(f.root,'purge-control',plan.plan.id+'.json'),'utf8'))).not.toContain(marker);expect(()=>fence.assert(token)).toThrow('persistence_denied');
 if(retainBackup){expect(f.registry.get(saved.copy.id).state).toBe('ready');expect((await readFile(path.join(f.root,saved.copy.relativePath,'career.sqlite'))).includes(Buffer.from(marker))).toBe(true);}else await expect(readFile(path.join(f.root,saved.copy.relativePath,'career.sqlite'))).rejects.toThrow();
});
it('startup inventories a prior generation staging file as quarantine before purge can claim selected scope complete',async()=>{
 const f=await fixture();await mkdir(path.join(f.active,'staging'));const relative='workspaces/local/staging/interrupted-producer',filename=path.join(f.root,relative);await writeFile(filename,'SENSITIVE_G6_PREVIOUS_GENERATION_STAGING');const lifecycle=createDataLifecycle({...f.ports,impact:async refs=>({references:[...refs],description:'clear fixture',independentReferences:[],files:[],dependencies:'one'}),markPurge:async()=>{},drain:async()=>{},purge:async()=>{},compact:async()=>{},activate:async()=>{throw Error('not_requested');}});const plan=await lifecycle.handle({operation:'data.purge.plan',references:[{owner:'materials',objectId:'A'}]},'human');if(plan.kind!=='purge_plan')throw Error('plan');expect(plan.plan.copies).toEqual(expect.arrayContaining([expect.objectContaining({relativePath:relative,kind:'quarantine',state:'failed'})]));expect(await lifecycle.handle({operation:'data.purge.confirm',planId:plan.plan.id,selectedCopyIds:plan.plan.copies.map(copy=>copy.id),confirmed:true},'human')).toMatchObject({kind:'purged',scope:'all_managed_copies'});await expect(readFile(filename)).rejects.toThrow();
});
it('startup quarantines unknown blob residuals while protecting every owner-registered incarnation',async()=>{
 const f=await fixture(),unknown='unregistered-sensitive-blob',relative='workspaces/local/blobs/'+unknown;await writeFile(path.join(f.active,'blobs',unknown),'SENSITIVE_UNKNOWN_BLOB');const lifecycle=createDataLifecycle({...f.ports,knownBlobIds:()=>[f.blobId],impact:async refs=>({references:[...refs],description:'fixture',independentReferences:[],files:[],dependencies:'one'}),markPurge:async()=>{},drain:async()=>{},purge:async()=>{},compact:async()=>{},activate:async()=>{throw Error('not_requested');}});const plan=await lifecycle.handle({operation:'data.purge.plan',references:[{owner:'materials',objectId:'A'}]},'human');if(plan.kind!=='purge_plan')throw Error('plan');expect(plan.plan.copies).toEqual(expect.arrayContaining([expect.objectContaining({relativePath:relative,kind:'quarantine',state:'failed'})]));expect(plan.plan.copies.some(copy=>copy.relativePath==='workspaces/local/blobs/'+f.blobId)).toBe(false);expect(await lifecycle.handle({operation:'data.purge.confirm',planId:plan.plan.id,selectedCopyIds:plan.plan.copies.map(copy=>copy.id),confirmed:true},'human')).toMatchObject({kind:'purged'});await expect(readFile(path.join(f.active,'blobs',unknown))).rejects.toThrow();expect(await readFile(path.join(f.active,'blobs',f.blobId))).toEqual(f.bytes);
});
