import {it,expect,beforeAll} from 'vitest';
import {build} from 'vite';
import Database from 'better-sqlite3';
import {mkdtemp,mkdir,rm,readFile} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {randomUUID} from 'node:crypto';
import {createRuntimeBackend} from '../../packages/backend/bootstrap/runtime';
import {createWriterCommands} from '../../packages/backend/bootstrap/writer-commands';
import {openWorkspace} from '../../packages/backend/platform/database/database';
import {materialsMigration} from '../../packages/backend/domains/materials/migration';
import {releases} from '../../packages/backend/bootstrap/releases';
import {Result as WikiResult} from '../../packages/contracts/wiki/schema';
import {Result as ProjectResult} from '../../packages/contracts/project/schema';
import {Result as OpportunityResult} from '../../packages/contracts/opportunity/schema';
import {Result as DataResult} from '../../packages/contracts/application/schema';
import type {BusinessModule} from '../../packages/contracts/common/bridge';
const output=path.resolve('dist/g6-search-lifecycle'),writer=path.join(output,'writer.cjs'),unknown={kind:'unknown'} as const;
beforeAll(async()=>{for(const [name,entry] of [['writer','packages/backend/bootstrap/writer.ts'],['local-search','packages/backend/platform/search/worker.ts']])await build({configFile:false,logLevel:'warn',build:{outDir:output,emptyOutDir:false,target:'node24',lib:{entry,formats:['cjs'],fileName:()=>name+'.cjs'},rolldownOptions:{external:[/^node:/,'better-sqlite3']}}});});
async function seed(business:(module:BusinessModule,input:unknown)=>Promise<unknown>,prefix:string){
 const wiki=WikiResult.parse(await business('wiki',{operation:'create',commandId:randomUUID(),title:'知识 '+prefix,body:prefix+' 旧知识中文正文',scope:'personal',nature:'observation',sources:[]}));if(wiki.kind!=='knowledge')throw Error('wiki');
 const project=ProjectResult.parse(await business('project',{operation:'create',commandId:randomUUID(),name:'项目 '+prefix,description:prefix+' 旧项目中文正文',tags:[],employmentId:null,occurredAt:unknown}));if(project.kind!=='project')throw Error('project');
 const company=OpportunityResult.parse(await business('opportunity',{operation:'company.create',commandId:randomUUID(),name:'公司 '+prefix}));if(company.kind!=='company')throw Error('company');const opportunity=OpportunityResult.parse(await business('opportunity',{operation:'create',commandId:randomUUID(),companyId:company.company.id,role:'岗位 '+prefix}));if(opportunity.kind!=='opportunity')throw Error('opportunity');const saved=OpportunityResult.parse(await business('opportunity',{operation:'save-jd',commandId:randomUUID(),id:opportunity.opportunity.id,expectedRevision:1,jd:prefix+' 旧职位中文正文',reason:'真实夹具岗位说明',businessTime:unknown}));expect(saved,JSON.stringify(saved)).toMatchObject({kind:'opportunity',opportunity:{jd:prefix+' 旧职位中文正文',revision:2}});return {wiki:wiki.knowledge,project:project.project,opportunity:opportunity.opportunity,company:company.company};
}
function inspect(root:string,check:(db:Database.Database)=>void){const db=new Database(path.join(root,'career.sqlite'),{readonly:true,fileMustExist:true});try{check(db);}finally{db.close();}}
async function search(runtime:Awaited<ReturnType<typeof createRuntimeBackend>>,session:Awaited<ReturnType<typeof runtime.connectHuman>>,owner:'wiki'|'project'|'opportunity',query:string){const result=await runtime.search(session,{operation:'local-search.query',owner,query});expect(result.kind).toBe('local-search.results');if(result.kind!=='local-search.results')throw Error(result.code);return result;}
it('normal release6 owner writes dirty Wiki/Project/Opportunity, fresh maintenance replaces all three and purge removes sensitive FTS/doc/chunks',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'g6-search-lifecycle-')),active=path.join(root,'workspaces/local'),runtime=await createRuntimeBackend(active,writer,root);
 try{const session=await runtime.connectHuman(),business=(module:BusinessModule,input:unknown)=>runtime.business(session,module,input),f=await seed(business,'G6_SENSITIVE_INDEX_ORIGINAL');inspect(active,db=>{expect(db.pragma('user_version',{simple:true})).toBe(8);expect(db.prepare('SELECT COUNT(*) AS n FROM platform_local_search_dirty').get()).toEqual({n:3});});
 expect((await search(runtime,session,'wiki','旧知识')).items.map(item=>item.id),'wiki old body').toEqual([f.wiki.id]);
 expect((await search(runtime,session,'project','旧项目')).items.map(item=>item.id),'project old body').toEqual([f.project.id]);
 expect((await search(runtime,session,'opportunity','旧职位')).items.map(item=>item.id),'opportunity old JD').toEqual([f.opportunity.id]);
 expect(await business('wiki',{operation:'edit',commandId:randomUUID(),id:f.wiki.id,expectedRevision:1,title:f.wiki.title,body:'新知识正文',scope:'personal',nature:'observation',sources:[],change:'corrected',reason:'实际改稿',businessTime:unknown})).toMatchObject({kind:'knowledge',knowledge:{revision:2,body:'新知识正文'}});expect(await business('project',{operation:'edit',commandId:randomUUID(),id:f.project.id,expectedRevision:1,name:f.project.name,description:'新项目正文',tags:[],mode:'correction',reason:'实际改稿',occurredAt:unknown})).toMatchObject({kind:'project',project:{revision:2,description:'新项目正文'}});expect(await business('opportunity',{operation:'save-jd',commandId:randomUUID(),id:f.opportunity.id,expectedRevision:2,jd:'新职位正文',reason:'实际改稿',businessTime:unknown})).toMatchObject({kind:'opportunity',opportunity:{revision:3,jd:'新职位正文'}});inspect(active,db=>expect(db.prepare('SELECT COUNT(*) AS n FROM platform_local_search_dirty').get()).toEqual({n:3}));
 for(const [owner,oldQuery,newQuery,id] of [['wiki','旧知识','新知识',f.wiki.id],['project','旧项目','新项目',f.project.id],['opportunity','旧职位','新职位',f.opportunity.id]] as const){expect((await search(runtime,session,owner,oldQuery)).items).toEqual([]);expect((await search(runtime,session,owner,newQuery)).items.map(item=>item.id)).toEqual([id]);}
 const references=[{owner:'wiki',objectId:f.wiki.id},{owner:'project',objectId:f.project.id},{owner:'opportunity',objectId:f.opportunity.id},{owner:'company',objectId:f.company.id}],planned=DataResult.parse(await business('application',{operation:'data.purge.plan',references}));if(planned.kind!=='purge_plan')throw Error('plan');expect(await business('application',{operation:'data.purge.confirm',planId:planned.plan.id,selectedCopyIds:planned.plan.copies.map(copy=>copy.id),confirmed:true})).toMatchObject({kind:'purged'});
 for(const owner of ['wiki','project','opportunity'] as const){const result=await search(runtime,session,owner,'G6_SENSITIVE');expect(result.items).toEqual([]);expect(result.partial).toBe(false);}
 inspect(active,db=>{expect(db.prepare('SELECT COUNT(*) AS n FROM platform_local_search_documents').get()).toEqual({n:0});expect(db.prepare('SELECT COUNT(*) AS n FROM platform_local_search_chunks').get()).toEqual({n:0});expect(db.prepare("SELECT COUNT(*) AS n FROM platform_local_search_fts WHERE platform_local_search_fts MATCH 'G6_SENSITIVE'").get()).toEqual({n:0});});expect((await readFile(path.join(active,'career.sqlite'))).includes(Buffer.from('G6_SENSITIVE_INDEX_ORIGINAL'))).toBe(false);
 }finally{await runtime.close();await rm(root,{recursive:true,force:true});}
},30000);
it.each([5,6])('normal v%s backup restores through release6, excludes derived payload and rebuilds current owner search without purged content revival',async version=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'g6-search-restore-')),active=path.join(root,'workspaces/local');await mkdir(active,{recursive:true});let runtime:Awaited<ReturnType<typeof createRuntimeBackend>>|undefined,workspace:Awaited<ReturnType<typeof openWorkspace>>|undefined;
 try{let backupId:string,fixture:Awaited<ReturnType<typeof seed>>;
 if(version===5){workspace=await openWorkspace(active,materialsMigration,releases.filter(release=>release.version<=5));const current=workspace,commands=createWriterCommands(current.database,current.workspaceInstance,randomUUID(),{dataRoot:root,control:{maintenance:async work=>work(),drain:async()=>{},beforeActivate:async()=>{},closeWorkspace:()=>current.close()}}),session=commands.connect(),business=(module:BusinessModule,input:unknown)=>commands.business(session,module,input);fixture=await seed(business,'G6_SAFE_RESTORE');const saved=DataResult.parse(await business('application',{operation:'data.backup'}));if(saved.kind!=='backup')throw Error('v5 backup');backupId=saved.copy.id;inspect(path.join(root,saved.copy.relativePath),db=>expect(db.pragma('user_version',{simple:true})).toBe(5));current.close();workspace=undefined;runtime=await createRuntimeBackend(active,writer,root);
 }else{runtime=await createRuntimeBackend(active,writer,root);const session=await runtime.connectHuman(),business=(module:BusinessModule,input:unknown)=>runtime!.business(session,module,input);fixture=await seed(business,'G6_SAFE_RESTORE');for(const owner of ['wiki','project','opportunity'] as const)expect((await search(runtime,session,owner,'G6_SAFE')).items).toHaveLength(1);const sensitive=WikiResult.parse(await business('wiki',{operation:'create',commandId:randomUUID(),title:'临时敏感',body:'G6_PURGED_MUST_NOT_REVIVE',scope:'personal',nature:'observation',sources:[]}));if(sensitive.kind!=='knowledge')throw Error('sensitive');expect((await search(runtime,session,'wiki','G6_PURGED')).items).toHaveLength(1);const planned=DataResult.parse(await business('application',{operation:'data.purge.plan',references:[{owner:'wiki',objectId:sensitive.knowledge.id}]}));if(planned.kind!=='purge_plan')throw Error('plan');expect(await business('application',{operation:'data.purge.confirm',planId:planned.plan.id,selectedCopyIds:planned.plan.copies.map(copy=>copy.id),confirmed:true})).toMatchObject({kind:'purged'});for(const owner of ['wiki','project','opportunity'] as const)expect((await search(runtime,session,owner,'G6_SAFE')).items).toHaveLength(1);const saved=DataResult.parse(await business('application',{operation:'data.backup'}));if(saved.kind!=='backup')throw Error('v6 backup');backupId=saved.copy.id;const copy=path.join(root,saved.copy.relativePath);inspect(copy,db=>{expect(db.prepare('SELECT COUNT(*) AS n FROM platform_local_search_documents').get()).toEqual({n:0});expect(db.prepare('SELECT COUNT(*) AS n FROM platform_local_search_chunks').get()).toEqual({n:0});expect(db.prepare('SELECT COUNT(*) AS n FROM platform_local_search_fts').get()).toEqual({n:0});expect(db.prepare('SELECT COUNT(*) AS n FROM platform_local_search_dirty').get()).toEqual({n:3});});expect((await readFile(path.join(copy,'career.sqlite'))).includes(Buffer.from('G6_PURGED_MUST_NOT_REVIVE'))).toBe(false);}
 let session=await runtime.connectHuman();const prepared=DataResult.parse(await runtime.business(session,'application',{operation:'data.restore.prepare',backupId}));if(prepared.kind!=='restore_candidate')throw Error('candidate');const old=session;const restored=DataResult.parse(await runtime.business(session,'application',{operation:'data.restore.activate',candidateId:prepared.copy.id,confirmed:true}));if(restored.kind!=='restored')throw Error(JSON.stringify(restored));session=await runtime.connectHuman();expect(session.workspaceInstance).not.toBe(old.workspaceInstance);await expect(runtime.search(old,{operation:'local-search.query',owner:'wiki',query:'G6_SAFE'})).rejects.toThrow('invalid_capability');
 const current=path.join(root,restored.copy.relativePath);inspect(current,db=>{expect(db.pragma('user_version',{simple:true})).toBe(8);expect(db.prepare('SELECT COUNT(*) AS n FROM platform_local_search_dirty').get()).toEqual({n:3});});
 for(const [owner,id] of [['wiki',fixture.wiki.id],['project',fixture.project.id],['opportunity',fixture.opportunity.id]] as const){const result=await search(runtime,session,owner,'G6_SAFE');expect(result.items.map(item=>item.id)).toEqual([id]);expect(result.partial).toBe(false);const bodyQuery=owner==='wiki'?'旧知识':owner==='project'?'旧项目':'旧职位';expect((await search(runtime,session,owner,bodyQuery)).items.map(item=>item.id)).toEqual([id]);expect((await search(runtime,session,owner,'G6_PURGED')).items).toEqual([]);}inspect(current,db=>{expect(db.prepare('SELECT COUNT(*) AS n FROM platform_local_search_dirty').get()).toEqual({n:0});expect(db.prepare('SELECT COUNT(*) AS n FROM platform_local_search_documents').get()).toEqual({n:3});});
 }finally{if(workspace)workspace.close();await runtime?.close();await rm(root,{recursive:true,force:true});}
},45000);
