import {afterEach,expect,it} from 'vitest';
import Database from 'better-sqlite3';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createInterviewDomain} from '../../packages/backend/domains/opportunity/interview/public';
import {interviewMigration} from '../../packages/backend/domains/opportunity/interview/migration';
import {createOpportunityDomain} from '../../packages/backend/domains/opportunity/public';
import {opportunityMigration} from '../../packages/backend/domains/opportunity/migration';
import {commandMigration} from '../../packages/backend/platform/commands/receipts';
const opened:{db:Database.Database;root:string}[]=[];
afterEach(()=>{for(const{db,root}of opened.splice(0)){db.close();rmSync(root,{recursive:true,force:true});}});
function setup(){const root=mkdtempSync(path.join(tmpdir(),'career-interview-'));const db=new Database(path.join(root,'career.sqlite'));db.pragma('foreign_keys=ON');db.exec(commandMigration);db.exec(opportunityMigration);db.exec(interviewMigration);opened.push({db,root});const core=createOpportunityDomain(db);const company=core.handle({operation:'company.create',commandId:randomUUID(),name:'面试公司'});if(company.kind!=='company')throw Error();const o=core.handle({operation:'create',commandId:randomUUID(),companyId:company.company.id,role:'岗位'});if(o.kind!=='opportunity')throw Error();const domain=createInterviewDomain(db,{core:core.capabilities});return {db,core,domain,opportunity:o.opportunity};}
it('DM-27 confirming an unknown-date actual round is real, pending scheduling, and advances only the core stage',()=>{const{domain,core,opportunity}=setup();const intent={operation:'interview.confirm',commandId:randomUUID(),opportunityId:opportunity.id,expectedOpportunityRevision:1,title:'第一轮',confirmationTime:{kind:'unknown'}};const saved=domain.handle(intent);if(saved.kind!=='saved')throw Error(JSON.stringify(saved));expect(domain.handle({operation:'interview.read',id:saved.id})).toMatchObject({kind:'session',session:{kind:'real',state:'awaiting_schedule',confirmationTime:{kind:'unknown'},scheduledTime:{kind:'unknown'},completionTime:{kind:'unknown'}}});expect(domain.handle(intent)).toEqual(saved);expect(core.handle({operation:'read',id:opportunity.id})).toMatchObject({kind:'opportunity',opportunity:{phase:'interview',result:'active',stageDates:{submitted:{kind:'unknown'},interview:{kind:'unknown'}}}});});
function getSession(domain:ReturnType<typeof createInterviewDomain>,id:string){const r=domain.handle({operation:'interview.read',id});if(r.kind!=='session')throw Error(JSON.stringify(r));return r.session;}
function confirm(domain:ReturnType<typeof createInterviewDomain>,opportunityId:string,expectedOpportunityRevision:number=1){const r=domain.handle({operation:'interview.confirm',commandId:randomUUID(),opportunityId,expectedOpportunityRevision,title:'二面',confirmationTime:{kind:'unknown'}});if(r.kind!=='saved')throw Error(JSON.stringify(r));return getSession(domain,r.id);}
it('DM-26/28/37 schedule, reschedule, temporary cancellation, completion and correction retain one round and independent times',()=>{const{domain,core,opportunity}=setup();let round=confirm(domain,opportunity.id);const step=(action:string,time:unknown)=>{const r=domain.handle({operation:'interview.transition',commandId:randomUUID(),id:round.id,expectedRevision:round.revision,action,businessTime:time,reason:'现实发生此变化'});expect(r.kind).toBe('saved');round=getSession(domain,round.id);};step('schedule',{kind:'date',date:'2026-10-10'});expect(round.state).toBe('scheduled');expect(round.confirmationTime).toEqual({kind:'unknown'});step('schedule',{kind:'instant',instant:'2026-10-11T10:00:00+08:00',timezone:'Asia/Shanghai'});expect(round.scheduledTime).toEqual({kind:'instant',instant:'2026-10-11T10:00:00+08:00',timezone:'Asia/Shanghai'});step('temporarily_cancel',{kind:'date',date:'2026-10-09'});expect(round.state).toBe('awaiting_rebooking');step('schedule',{kind:'date',date:'2026-10-12'});step('complete',{kind:'unknown'});expect(round.state).toBe('completed');expect(round.completionTime).toEqual({kind:'unknown'});expect(domain.handle({operation:'interview.transition',commandId:randomUUID(),id:round.id,expectedRevision:round.revision,action:'schedule',businessTime:{kind:'date',date:'2026-10-15'},reason:'不应该静默改终态'})).toMatchObject({kind:'failure',code:'invalid_transition'});const fixed=domain.handle({operation:'interview.correct-terminal',commandId:randomUUID(),id:round.id,expectedRevision:round.revision,state:'scheduled',businessTime:{kind:'date',date:'2026-10-12'},reason:'误点完成，实际上还未开始'});expect(fixed.kind).toBe('saved');round=getSession(domain,round.id);expect(round.state).toBe('scheduled');expect(domain.handle({operation:'interview.list',opportunityId:opportunity.id})).toMatchObject({kind:'sessions',items:[{id:round.id}]});expect(domain.handle({operation:'interview.history',id:round.id})).toMatchObject({kind:'history',items:expect.arrayContaining([expect.objectContaining({type:'terminal_corrected',reason:'误点完成，实际上还未开始'})])});expect(core.handle({operation:'read',id:opportunity.id})).toMatchObject({kind:'opportunity',opportunity:{revision:2,result:'active',stageDates:{interview:{kind:'unknown'}}}});});
it('DM-29 current preparation, corrected transcript and current review are separate; only affected review awaits recheck',()=>{const{domain,opportunity}=setup();let round=confirm(domain,opportunity.id);const save=(document:string,text:string)=>{const r=domain.handle({operation:'interview.save-document',commandId:randomUUID(),id:round.id,expectedRevision:round.revision,document,text});expect(r.kind).toBe('saved');round=getSession(domain,round.id);return r;};save('preparation','部分准备，其他尚空');expect(round.transcript).toBeUndefined();save('transcript','初次文字稿');save('final-review','人工终版：需要改进');expect(round.finalReview).toMatchObject({text:'人工终版：需要改进',needsRecheck:false,transcriptVersion:1});const corrected=save('transcript','明确更正后的当前文字稿');expect(round.transcript).toEqual({text:'明确更正后的当前文字稿',version:2});expect(round.finalReview).toMatchObject({text:'人工终版：需要改进',needsRecheck:true,transcriptVersion:1});expect(corrected).toEqual({kind:'saved',id:round.id,revision:5});expect(domain.handle({operation:'interview.history',id:round.id})).not.toMatchObject({items:expect.arrayContaining([expect.objectContaining({text:'初次文字稿'})])});save('final-review','人工明确复核后保存的当前结论');expect(round.finalReview).toMatchObject({needsRecheck:false,transcriptVersion:2});});
it('DM-26 multiple simulations belong to the same actual round and have their own state/content without actual stage effects',()=>{const{domain,core,opportunity}=setup();const round=confirm(domain,opportunity.id);const before=core.handle({operation:'read',id:opportunity.id});const ids:string[]=[];for(const title of ['练习一','练习二']){const created=domain.handle({operation:'interview.create-simulation',commandId:randomUUID(),opportunityId:opportunity.id,realRoundId:round.id,title});expect(created.kind).toBe('saved');if(created.kind!=='saved')throw Error();ids.push(created.id);expect(getSession(domain,created.id)).toMatchObject({kind:'simulation',realRoundId:round.id,state:'pending'});}expect(domain.handle({operation:'interview.create-simulation',commandId:randomUUID(),opportunityId:opportunity.id,realRoundId:ids[0],title:'不允许模拟关联模拟'})).toMatchObject({kind:'failure',code:'invalid_relation'});let simulation=getSession(domain,ids[0]);const saved=domain.handle({operation:'interview.save-document',commandId:randomUUID(),id:simulation.id,expectedRevision:1,document:'transcript',text:'模拟面试官虚构内容，仅为练习'});expect(saved.kind).toBe('saved');simulation=getSession(domain,ids[0]);expect(domain.handle({operation:'interview.transition-simulation',commandId:randomUUID(),id:simulation.id,expectedRevision:simulation.revision,state:'completed',businessTime:{kind:'unknown'},reason:'练习完成'}).kind).toBe('saved');expect(getSession(domain,round.id).state).toBe('awaiting_schedule');expect(core.handle({operation:'read',id:opportunity.id})).toEqual(before);});
it('DM-33/39 late completed rounds with unknown dates retain the later result and first actual interview date',()=>{const{domain,core,opportunity}=setup();const first=domain.handle({operation:'interview.confirm',commandId:randomUUID(),opportunityId:opportunity.id,expectedOpportunityRevision:1,title:'第一轮',confirmationTime:{kind:'date',date:'2026-09-20'}});expect(first.kind).toBe('saved');core.handle({operation:'end',commandId:randomUUID(),id:opportunity.id,expectedRevision:2,outcome:'withdrawn',reason:'真实后来退出',businessTime:{kind:'date',date:'2026-09-25'}});const late=confirm(domain,opportunity.id,3);expect(domain.handle({operation:'interview.transition',commandId:randomUUID(),id:late.id,expectedRevision:1,action:'complete',businessTime:{kind:'unknown'},reason:'补录已经完成但日期已不记得'}).kind).toBe('saved');expect(core.handle({operation:'read',id:opportunity.id})).toMatchObject({kind:'opportunity',opportunity:{phase:'interview',result:'withdrawn',stageDates:{interview:{kind:'date',date:'2026-09-20'},submitted:{kind:'unknown'}}}});expect(getSession(domain,late.id)).toMatchObject({state:'completed',completionTime:{kind:'unknown'}});});
it('DM-28/37 permanent cancellation stays distinct and explicit correction keeps the same ID and cancellation explanation',()=>{const{domain,opportunity}=setup();const round=confirm(domain,opportunity.id);expect(domain.handle({operation:'interview.transition',commandId:randomUUID(),id:round.id,expectedRevision:1,action:'permanently_cancel',businessTime:{kind:'unknown'},reason:'以为轮次彻底取消'}).kind).toBe('saved');expect(getSession(domain,round.id).state).toBe('permanently_cancelled');expect(domain.handle({operation:'interview.correct-terminal',commandId:randomUUID(),id:round.id,expectedRevision:2,state:'awaiting_schedule',businessTime:{kind:'unknown'},reason:'其实是日期未定，误点永久取消'}).kind).toBe('saved');expect(getSession(domain,round.id)).toMatchObject({id:round.id,state:'awaiting_schedule',revision:3});expect(domain.handle({operation:'interview.history',id:round.id})).toMatchObject({kind:'history',items:[expect.objectContaining({type:'terminal_corrected',previousState:'permanently_cancelled',reason:'其实是日期未定，误点永久取消'}),expect.objectContaining({type:'permanently_cancel',reason:'以为轮次彻底取消'}),expect.objectContaining({type:'confirmed'})]});});
it('RV-MODULE failure after public core stage change rolls both owners and receipt back; foreign commands cannot write core',()=>{const{db,domain,core,opportunity}=setup();const failing=createInterviewDomain(db,{core:{...core.capabilities,recordStage(input){core.capabilities.recordStage(input);throw Error('storage_failed');}}});const intent={operation:'interview.confirm',commandId:randomUUID(),opportunityId:opportunity.id,expectedOpportunityRevision:1,title:'应该回滚的轮次',confirmationTime:{kind:'date',date:'2026-10-02'}};expect(failing.handle(intent)).toEqual({kind:'failure',code:'storage_failed'});expect(domain.handle({operation:'interview.list',opportunityId:opportunity.id})).toMatchObject({kind:'sessions',items:[]});expect(core.handle({operation:'read',id:opportunity.id})).toMatchObject({kind:'opportunity',opportunity:{revision:1,phase:'preparation'}});expect(core.handle({operation:'history',id:opportunity.id})).toMatchObject({kind:'history',items:[expect.objectContaining({type:'created'})]});expect(domain.handle({operation:'interview.receipt',commandId:intent.commandId})).toEqual({kind:'receipt_missing'});expect(domain.handle({operation:'record-stage',commandId:randomUUID(),id:opportunity.id,expectedRevision:1,stage:'offer',reason:'越权',businessTime:{kind:'unknown'}})).toEqual({kind:'failure',code:'invalid_request'});expect(domain.handle({...intent,commandId:randomUUID(),expectedOpportunityRevision:99})).toEqual({kind:'failure',code:'conflict'});expect(domain.handle({operation:'interview.list',opportunityId:opportunity.id})).toMatchObject({kind:'sessions',items:[]});});
it('simulation cannot bind to a real round from another opportunity and optimistic command retries keep intent',()=>{const{domain,core,opportunity}=setup();const round=confirm(domain,opportunity.id);const other=core.handle({operation:'create',commandId:randomUUID(),companyId:opportunity.companyId,role:'另一个岗位'});if(other.kind!=='opportunity')throw Error();expect(domain.handle({operation:'interview.create-simulation',commandId:randomUUID(),opportunityId:other.opportunity.id,realRoundId:round.id,title:'跨机会模拟'})).toEqual({kind:'failure',code:'invalid_relation'});const intent={operation:'interview.save-document',commandId:randomUUID(),id:round.id,expectedRevision:1,document:'transcript',text:'只有当前稿'};expect(domain.handle(intent)).toMatchObject({kind:'saved',revision:2});expect(domain.handle(intent)).toMatchObject({kind:'saved',revision:2});expect(domain.handle({...intent,text:'改写同一意图'})).toEqual({kind:'failure',code:'conflict'});expect(domain.handle({...intent,commandId:randomUUID()})).toEqual({kind:'failure',code:'conflict'});expect(domain.handle({operation:'interview.receipt',commandId:intent.commandId})).toEqual({kind:'saved',id:round.id,revision:2});});
it('saving identical current transcript text does not invalidate unchanged review support',()=>{const{domain,opportunity}=setup();const round=confirm(domain,opportunity.id);domain.handle({operation:'interview.save-document',commandId:randomUUID(),id:round.id,expectedRevision:1,document:'transcript',text:'未改变的正文'});domain.handle({operation:'interview.save-document',commandId:randomUUID(),id:round.id,expectedRevision:2,document:'final-review',text:'用户已复核的结论'});domain.handle({operation:'interview.save-document',commandId:randomUUID(),id:round.id,expectedRevision:3,document:'transcript',text:'未改变的正文'});expect(getSession(domain,round.id)).toMatchObject({transcript:{version:1},finalReview:{needsRecheck:false,transcriptVersion:1}});});
it('a public capability failure DTO cannot be mistaken for a successful round or receipt',()=>{const{db,domain,core,opportunity}=setup();const broken=createInterviewDomain(db,{core:{...core.capabilities,recordStage(input){core.capabilities.recordStage(input);return {kind:'failure',code:'storage_failed'} as unknown as ReturnType<typeof core.capabilities.recordStage>;}}});const commandId=randomUUID();expect(broken.handle({operation:'interview.confirm',commandId,opportunityId:opportunity.id,expectedOpportunityRevision:1,title:'不能提交',confirmationTime:{kind:'unknown'}})).toEqual({kind:'failure',code:'storage_failed'});expect(domain.handle({operation:'interview.list',opportunityId:opportunity.id})).toMatchObject({kind:'sessions',items:[]});expect(core.handle({operation:'read',id:opportunity.id})).toMatchObject({kind:'opportunity',opportunity:{revision:1,phase:'preparation'}});expect(domain.handle({operation:'interview.receipt',commandId})).toEqual({kind:'receipt_missing'});});
it('saved actual/manual simulation content and metadata-only receipt survive a SQLite restart',()=>{const{db,domain,opportunity}=setup();const round=confirm(domain,opportunity.id);const commandId=randomUUID();domain.handle({operation:'interview.save-document',commandId,id:round.id,expectedRevision:1,document:'transcript',text:'重启后回读的当前正文'});const filename=db.name;const entry=opened.find(item=>item.db===db)!;db.close();const reopened=new Database(filename);reopened.pragma('foreign_keys=ON');entry.db=reopened;const core=createOpportunityDomain(reopened),again=createInterviewDomain(reopened,{core:core.capabilities});expect(getSession(again,round.id)).toMatchObject({id:round.id,revision:2,transcript:{text:'重启后回读的当前正文',version:1}});expect(again.handle({operation:'interview.receipt',commandId})).toEqual({kind:'saved',id:round.id,revision:2});expect(core.handle({operation:'read',id:opportunity.id})).toMatchObject({kind:'opportunity',opportunity:{phase:'interview',stageDates:{submitted:{kind:'unknown'}}}});});
it('wrong confirmation and completed dates can be corrected on the same real round via its public core capability without changing state or inventing submission',()=>{
 const {db,core,domain,opportunity}=setup();const confirmed=domain.handle({operation:'interview.confirm',commandId:randomUUID(),opportunityId:opportunity.id,expectedOpportunityRevision:1,title:'Time correction',confirmationTime:{kind:'date',date:'2025-09-01'}});if(confirmed.kind!=='saved')throw Error();
 const fixed=domain.handle({operation:'interview.correct-time',commandId:randomUUID(),id:confirmed.id,expectedRevision:1,expectedOpportunityRevision:2,field:'confirmation',businessTime:{kind:'date',date:'2026-09-01'},reason:'Wrong year originally recorded'});
 expect(fixed).toMatchObject({kind:'saved',id:confirmed.id,revision:2});expect(core.capabilities.readOpportunity(opportunity.id)).toMatchObject({phase:'interview',stageDates:{interview:{kind:'date',date:'2026-09-01'},submitted:{kind:'unknown'}}});
 expect(domain.handle({operation:'interview.transition',commandId:randomUUID(),id:confirmed.id,expectedRevision:2,action:'complete',businessTime:{kind:'unknown'},reason:'Actual complete, date initially unknown'})).toMatchObject({kind:'saved',revision:3});
 expect(domain.handle({operation:'interview.correct-time',commandId:randomUUID(),id:confirmed.id,expectedRevision:3,expectedOpportunityRevision:3,field:'completion',businessTime:{kind:'date',date:'2026-09-10'},reason:'Confirmed the real date later'})).toMatchObject({kind:'saved',revision:4});
 expect(domain.handle({operation:'interview.read',id:confirmed.id})).toMatchObject({kind:'session',session:{state:'completed',confirmationTime:{kind:'date',date:'2026-09-01'},completionTime:{kind:'date',date:'2026-09-10'}}});
 expect(core.capabilities.readOpportunity(opportunity.id)?.revision).toBe(3);
});
