import {it,expect} from 'vitest';import {mkdtemp,rm} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {randomUUID} from 'node:crypto';
import {createRuntimeBackend} from '../../packages/backend/bootstrap/runtime';import {tavilyPreviewDigest} from '../../packages/contracts/ai/tavily-search';
it('real Search adapter results persist under SearchRun only, with matching source refs and empty formal Research',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'j07-search-runtime-'));let searches=0,models=0,reads=0;
 const runtime=await createRuntimeBackend(path.join(root,'workspaces/local'),path.resolve('dist/application/writer.cjs'),root,{automaticBackups:false,tavilyKey:async()=>{reads++;return 'SYNTHETIC_TAVILY';},tavilyTransport:async(_url,init)=>{searches++;expect(init?.body).toBe('{"query":"OpenAI official website"}');return new Response(JSON.stringify({query:'OpenAI official website',results:[{title:'OpenAI',url:'https://openai.com/',content:'Public test response.'}]}));},providerTransport:async()=>{models++;throw Error('no model allowed');}});
 try{const session=await runtime.connectHuman(),call=(module:Parameters<typeof runtime.business>[1],input:unknown)=>runtime.business(session,module,input) as Promise<any>,company=(await call('opportunity',{operation:'company.create',commandId:randomUUID(),name:'Example Corp'})).company,owner={kind:'company' as const,id:company.id};
 expect(await runtime.externalSearch(session,{operation:'preview',owner},randomUUID())).toMatchObject({kind:'preview',query:'OpenAI official website',used:false});expect(searches).toBe(0);expect(reads).toBe(0);
 const result=await runtime.externalSearch(session,{operation:'run',owner,commandId:randomUUID(),confirmed:true,previewDigest:tavilyPreviewDigest},randomUUID());expect(result.kind).toBe('candidate');if(result.kind!=='candidate')throw Error(JSON.stringify(result));const source=result.run.results[0]!.source;
 expect(source).toMatchObject({owner:'search',objectId:result.run.id,scope:'company',scopeId:company.id});expect(result.run).toMatchObject({adapter:'tavily',network:'external',externalEvidence:{requestCount:1}});expect(await call('ai',{operation:'search.read',id:result.run.id})).toMatchObject({kind:'search_run',run:result.run});expect((await call('research',{operation:'read',owner})).items).toEqual([]);expect(await runtime.externalSearch(session,{operation:'receipt'})).toEqual(result);
 expect(await runtime.externalSearch(session,{operation:'run',owner,commandId:randomUUID(),confirmed:true,previewDigest:tavilyPreviewDigest},randomUUID())).toMatchObject({kind:'failure',code:'already_consumed'});expect(searches).toBe(1);expect(reads).toBe(1);expect(models).toBe(0);
 }finally{await runtime.close();await rm(root,{recursive:true,force:true});}
},15000);

it('Tavily credential invalidation during retrieval blocks the runtime handoff',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'j07-search-invalidate-'));let reads=0,calls=0,release!:(key:string)=>void;
 const runtime=await createRuntimeBackend(path.join(root,'workspaces/local'),path.resolve('dist/application/writer.cjs'),root,{automaticBackups:false,tavilyKey:()=>{reads++;return new Promise(resolve=>release=resolve);},tavilyTransport:async()=>{calls++;throw Error('must not send');}});
 try{const session=await runtime.connectHuman(),company=await runtime.business(session,'opportunity',{operation:'company.create',commandId:randomUUID(),name:'TEST DATA'}) as any,owner={kind:'company',id:company.company.id};const pending=runtime.externalSearch(session,{operation:'run',commandId:randomUUID(),owner,confirmed:true,previewDigest:tavilyPreviewDigest},randomUUID());await expect.poll(()=>reads).toBe(1);runtime.invalidateTavily();release('SYNTHETIC');expect(await pending).toMatchObject({kind:'failure',code:'credential_unavailable'});expect(calls).toBe(0);expect(await runtime.externalSearch(session,{operation:'receipt'})).toMatchObject({kind:'state',state:'not_sent',requestCount:0});}finally{release?.('SYNTHETIC');await runtime.close();await rm(root,{recursive:true,force:true});}
},15000);
it('formal private credential readiness never reserves an operation or calls transport',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'j07-search-readiness-'));let reads=0,calls=0;
 const runtime=await createRuntimeBackend(path.join(root,'workspaces/local'),path.resolve('dist/application/writer.cjs'),root,{automaticBackups:false,tavilyKey:async()=>{reads++;return 'SYNTHETIC_LOCAL_ONLY';},tavilyTransport:async()=>{calls++;throw Error('never send');}});
 try{const session=await runtime.connectHuman();const result=await runtime.externalSearch(session,{operation:'credential.check'},randomUUID());expect(result).toMatchObject({kind:'credential_readiness',available:true});expect(JSON.stringify(result)).not.toContain('SYNTHETIC_LOCAL_ONLY');expect(reads).toBe(1);expect(calls).toBe(0);expect(await runtime.externalSearch(session,{operation:'receipt'})).toMatchObject({kind:'state',state:'not_run',requestCount:0});}finally{await runtime.close();await rm(root,{recursive:true,force:true});}
},15000);
it.each(['credential_cancelled','credential_denied','credential_timeout','credential_unavailable'])('formal runtime preserves %s for readiness and authorized preflight without network',async reason=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'j07-wait-runtime-'));let calls=0;
 const runtime=await createRuntimeBackend(path.join(root,'workspaces/local'),path.resolve('dist/application/writer.cjs'),root,{automaticBackups:false,tavilyKey:async()=>{throw Error(reason);},tavilyTransport:async()=>{calls++;throw Error('Network forbidden');}});
 try{const session=await runtime.connectHuman();expect(await runtime.externalSearch(session,{operation:'credential.check'},randomUUID())).toMatchObject({kind:'credential_readiness',available:false,failureReason:reason});expect(await runtime.externalSearch(session,{operation:'receipt'})).toMatchObject({kind:'state',state:'not_run',requestCount:0});const company=await runtime.business(session,'opportunity',{operation:'company.create',commandId:randomUUID(),name:'TEST DATA'}) as any;const outcome=await runtime.externalSearch(session,{operation:'run',commandId:randomUUID(),owner:{kind:'company',id:company.company.id},confirmed:true,previewDigest:tavilyPreviewDigest},randomUUID());expect(outcome).toMatchObject({kind:'failure',code:reason,credentialFailure:reason,failureStage:'credential_resolve'});expect(await runtime.externalSearch(session,{operation:'receipt'})).toMatchObject({kind:'state',state:'not_sent',requestCount:0,credentialFailure:reason});expect(calls).toBe(0);
 }finally{await runtime.close();await rm(root,{recursive:true,force:true});}
},15000);
it('normal Search preflight waiting leaves business and receipt controls responsive; cancellation sends nothing',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'j07-search-wait-control-'));let entered!:()=>void,cancel!:(error:Error)=>void,calls=0;
 const started=new Promise<void>(resolve=>entered=resolve),credential=new Promise<string>((_resolve,reject)=>cancel=reject);
 const runtime=await createRuntimeBackend(path.join(root,'workspaces/local'),path.resolve('dist/application/writer.cjs'),root,{automaticBackups:false,tavilyKey:()=>{entered();return credential;},tavilyTransport:async()=>{calls++;throw Error('Network forbidden');}});
 try{const session=await runtime.connectHuman(),company=await runtime.business(session,'opportunity',{operation:'company.create',commandId:randomUUID(),name:'TEST DATA'}) as any;const pending=runtime.externalSearch(session,{operation:'run',commandId:randomUUID(),owner:{kind:'company',id:company.company.id},confirmed:true,previewDigest:tavilyPreviewDigest},randomUUID());await started;
  const began=Date.now();expect(await runtime.business(session,'wiki',{operation:'list'})).toMatchObject({kind:'list'});expect(await runtime.externalSearch(session,{operation:'receipt'})).toMatchObject({kind:'state',state:'reserved',requestCount:0});expect(Date.now()-began).toBeLessThan(2000);
  cancel(Error('credential_cancelled'));expect(await pending).toMatchObject({kind:'failure',code:'credential_cancelled',credentialFailure:'credential_cancelled'});expect(calls).toBe(0);expect(await runtime.externalSearch(session,{operation:'receipt'})).toMatchObject({kind:'state',state:'not_sent',requestCount:0});
 }finally{cancel(Error('credential_cancelled'));await runtime.close();await rm(root,{recursive:true,force:true});}
},15000);
