import{it,expect}from'vitest';import Database from'better-sqlite3';import{randomUUID}from'node:crypto';
import{createResumeDomain,resumeMigration}from'../../packages/backend/domains/resume/public';import{createProfileDomain,profileMigration}from'../../packages/backend/domains/profile/public';import{commandMigration}from'../../packages/backend/platform/commands/receipts';import{renderSnapshot}from'../../packages/backend/domains/resume/render';import{toEditor,fromEditor}from'../../packages/frontend/features/resume/adapter';
it('source resume template and structured entry fields save, reopen, freeze and survive text-only AI edits without replacing Career owners',()=>{
 const db=new Database(':memory:');db.exec(commandMigration+profileMigration+resumeMigration);try{
 const owner=createResumeDomain(db,{profile:createProfileDomain(db),resolveOpportunity:id=>({id,companyName:'TEST Company',role:'TEST Role'})});const opened=owner.handle({operation:'resume.open',commandId:randomUUID(),opportunityId:randomUUID()});if(opened.status!=='document')throw Error();
 const content:any=structuredClone(opened.document.content);content.layout.template='miaoda-resume';content.layout.identityNameAlignment='center';const entryId=randomUUID();content.sections=[{id:randomUUID(),kind:'education',title:'教育经历',blocks:[{id:randomUUID(),type:'paragraph',entry:{id:entryId,field:'school'},spans:[{text:'TEST University',marks:[{type:'bold'}]}]},{id:randomUUID(),type:'paragraph',entry:{id:entryId,field:'startDate'},spans:[{text:'2023-06',marks:[]}]},{id:randomUUID(),type:'paragraph',entry:{id:entryId,field:'endDate'},spans:[{text:'2024-06',marks:[]}]}]}];
 const saved=owner.handle({operation:'resume.save',commandId:randomUUID(),resumeId:opened.document.id,expectedRevision:1,expectedProfileRevision:0,content});expect(saved.status).toBe('document');if(saved.status!=='document')throw Error();expect(fromEditor(toEditor(saved.document.content),saved.document.content.layout)).toEqual(saved.document.content);
 const block=saved.document.content.sections[0].blocks[0],dependency=owner.blockDependency(opened.document.id,block.id)!;const applied=owner.applyBlockProposal({commandId:randomUUID(),resumeId:opened.document.id,blockId:block.id,expectedDigest:dependency.digest,after:{id:block.id,type:'paragraph',spans:[{text:'TEST Updated University',marks:[]}]}});if(applied.status!=='document')throw Error();expect(applied.document.content.sections[0].blocks[0]).toMatchObject({entry:{id:entryId,field:'school'}});
 const prepared=owner.prepareVersion({operation:'resume.name-version',commandId:randomUUID(),resumeId:opened.document.id,expectedRevision:applied.document.revision,expectedProfileRevision:0,name:'TEST Source Template'});expect(prepared.status).toBe('pending-job');if(prepared.status!=='pending-job')throw Error();expect(prepared.job.templateVersion).toBe('miaoda-resume-1');const html=renderSnapshot(prepared.job);expect(html).toContain('miaoda-entry-row');expect(html).toContain('2023-06 – 2024-06');expect(html).toContain('TEST Updated University');expect(html).not.toContain('localStorage');const completed=owner.completeVersion(prepared.job.id,{blobId:randomUUID(),digest:'b'.repeat(64),size:100},()=>{});if(completed.status!=='version')throw Error();const later=structuredClone(applied.document.content);later.layout.template='a4-basic';owner.handle({operation:'resume.save',commandId:randomUUID(),resumeId:opened.document.id,expectedRevision:applied.document.revision,expectedProfileRevision:0,content:later});const frozen=owner.handle({operation:'resume.version',resumeId:opened.document.id,versionId:completed.version.id});if(frozen.status!=='version')throw Error();expect(frozen.version.snapshot.content.layout.template).toBe('miaoda-resume');expect(frozen.version.snapshot.content.sections[0].blocks[0]).toMatchObject({entry:{id:entryId,field:'school'}});
 }finally{db.close();}
});
