import {useEffect,useRef,useState} from 'react';
import {Request,Result,type Session,type History,type RoundState} from '../../../../contracts/opportunity/interview/schema';
import {BusinessTime} from '../../../../contracts/common/business-time';
import {sendInterviewIntent} from './save';
export interface InterviewPageProps{opportunityId:string;workspaceInstance:string;request:(input:Request)=>Promise<Result>;onChanged?:()=>void}
type TimeDraft={kind:'unknown'|'date'|'instant';date:string;instant:string;timezone:string};
const blankTime:TimeDraft={kind:'unknown',date:'',instant:'',timezone:''};
const stateNames:Record<Session['state'],string>={awaiting_schedule:'待排期',scheduled:'已排期',awaiting_rebooking:'临时取消，待重约',completed:'已完成',permanently_cancelled:'永久取消',pending:'练习待完成',cancelled:'练习取消'};
function actualTime(value:TimeDraft):BusinessTime{return BusinessTime.parse(value.kind==='unknown'?{kind:'unknown'}:value.kind==='date'?{kind:'date',date:value.date}:{kind:'instant',instant:value.instant,timezone:value.timezone});}
function displayTime(value:BusinessTime){return value.kind==='unknown'?'日期未知':value.kind==='date'?value.date:value.instant+'（'+value.timezone+'）';}
function TimeInput({label,value,onChange}:{label:string;value:TimeDraft;onChange:(value:TimeDraft)=>void}){return <fieldset><legend>{label}</legend><label>{label}类型<select aria-label={label+'类型'} value={value.kind} onChange={e=>onChange({...value,kind:e.target.value as TimeDraft['kind']})}><option value="unknown">未知</option><option value="date">仅日期</option><option value="instant">精确时刻（含时区）</option></select></label>{value.kind==='date'&&<label>{label}日期<input aria-label={label+'日期'} type="date" value={value.date} onChange={e=>onChange({...value,date:e.target.value})}/></label>}{value.kind==='instant'&&<><label>{label}时刻<input aria-label={label+'时刻'} placeholder="2026-10-10T10:00:00+08:00" value={value.instant} onChange={e=>onChange({...value,instant:e.target.value})}/></label><label>{label}时区<input aria-label={label+'时区'} placeholder="Asia/Shanghai" value={value.timezone} onChange={e=>onChange({...value,timezone:e.target.value})}/></label></>}</fieldset>;}
export function InterviewPage({opportunityId,workspaceInstance,request,onChanged}:InterviewPageProps){
 const [context,setContext]=useState({opportunityId,workspaceInstance});const [items,setItems]=useState<Session[]>([]);const [coreRevision,setCoreRevision]=useState(0);const [selected,setSelected]=useState<Session>();const [history,setHistory]=useState<History[]>([]);const [status,setStatus]=useState('读取中');const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [pending,setPending]=useState<Request>();const [receiptMissing,setReceiptMissing]=useState(false);const [conflict,setConflict]=useState<Session>();const [coreConflict,setCoreConflict]=useState<number>();
 const [title,setTitle]=useState('');const [confirmation,setConfirmation]=useState<TimeDraft>(blankTime);const [preparation,setPreparation]=useState('');const [transcript,setTranscript]=useState('');const [review,setReview]=useState('');const [reason,setReason]=useState('');const [time,setTime]=useState<TimeDraft>(blankTime);const [action,setAction]=useState<'schedule'|'temporarily_cancel'|'complete'|'permanently_cancel'>('schedule');const [correctState,setCorrectState]=useState<RoundState>('awaiting_schedule');const [timeField,setTimeField]=useState<'confirmation'|'scheduled'|'completion'>('confirmation');const [simulationTitle,setSimulationTitle]=useState('');const generation=useRef(0);
 const dirty=!!title||confirmation.kind!=='unknown'||preparation!==(selected?.preparation??'')||transcript!==(selected?.transcript?.text??'')||review!==(selected?.finalReview?.text??'')||!!reason||time.kind!=='unknown'||!!simulationTitle;
 const dirtyRef=useRef(false);dirtyRef.current=dirty||busy||!!pending;const scopeChanged=context.opportunityId!==opportunityId||context.workspaceInstance!==workspaceInstance;
 useEffect(()=>{if(!dirty&&!busy&&!pending)return;const protect=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue='';};window.addEventListener('beforeunload',protect);return()=>window.removeEventListener('beforeunload',protect);},[dirty,busy,pending]);
 async function list(scope=context,current=generation.current){const result=Result.parse(await request({operation:'interview.list',opportunityId:scope.opportunityId}));if(current!==generation.current)return;if(result.kind!=='sessions')throw Error('列表暂不可读');setItems(result.items);setCoreRevision(result.opportunityRevision);}
 function adopt(session:Session){setSelected(session);setPreparation(session.preparation??'');setTranscript(session.transcript?.text??'');setReview(session.finalReview?.text??'');setReason('');setTime(blankTime);setSimulationTitle('');setConflict(undefined);setHistory([]);}
 async function loadHistory(id:string,current=generation.current){try{const value=Result.parse(await request({operation:'interview.history',id}));if(current===generation.current&&value.kind==='history')setHistory(value.items);}catch{/* Primary content and save status remain usable; history has an independent error below. */if(current===generation.current)setStatus(previous=>previous+'；历史暂不可读');}}
 useEffect(()=>{const current=++generation.current;setLoading(true);setItems([]);setSelected(undefined);setCoreRevision(0);setTitle('');setConfirmation(blankTime);setPreparation('');setTranscript('');setReview('');setReason('');setTime(blankTime);setSimulationTitle('');setConflict(undefined);setHistory([]);setStatus('读取中');void list(context,current).then(()=>{if(current===generation.current){setLoading(false);setStatus('未保存');}}).catch(()=>{if(current===generation.current){setLoading(false);setStatus('列表读取失败，可重试');}});return()=>{generation.current++;};},[context.opportunityId,context.workspaceInstance]);
 useEffect(()=>{if(!scopeChanged||dirtyRef.current)return;setContext({opportunityId,workspaceInstance});},[opportunityId,workspaceInstance]);
 async function open(session:Session){if(busy||pending||dirty&&!window.confirm('有未提交输入，放弃后切换面试？'))return;const current=++generation.current;try{const r=Result.parse(await request({operation:'interview.read',id:session.id}));if(current!==generation.current)return;if(r.kind==='session'){adopt(r.session);setTitle('');setConfirmation(blankTime);setStatus('已保存');void loadHistory(r.session.id,current);}else setStatus('轮次暂不可读');}catch{if(current===generation.current)setStatus('读取失败，当前输入保留');}}
 async function apply(result:Result|{kind:'unknown'},intent:Request,current:number){
  if(current!==generation.current)return;
  if(result.kind==='unknown'){setPending(intent);setReceiptMissing(false);setStatus('保存结果待核对，输入保留');return;}
  if(result.kind==='receipt_missing'){setPending(intent);setReceiptMissing(true);setStatus('未发现原命令，可明确继续同一意图');return;}
  setPending(undefined);setReceiptMissing(false);
  if(result.kind==='failure'){
   setStatus(result.code==='conflict'?'冲突，草稿保留；比较正式值后再继续':'保存失败，输入保留：'+result.code);
   if(result.code==='conflict')try{if(intent.operation==='interview.correct-time'){const rounds=Result.parse(await request({operation:'interview.list',opportunityId:context.opportunityId}));if(current===generation.current&&rounds.kind==='sessions')setCoreConflict(rounds.opportunityRevision);}if('id'in intent){const server=Result.parse(await request({operation:'interview.read',id:intent.id}));if(current===generation.current&&server.kind==='session')setConflict(server.session);}else{const r=Result.parse(await request({operation:'interview.list',opportunityId:context.opportunityId}));if(current===generation.current&&r.kind==='sessions')setCoreConflict(r.opportunityRevision);}}catch{if(current===generation.current)setStatus('冲突，正式值暂不可读；草稿保留');}
   return;
  }
  if(result.kind!=='saved')return;
  setStatus('已保存');onChanged?.();
  if(intent.operation==='interview.confirm'){setTitle('');setConfirmation(blankTime);}
  if(intent.operation==='interview.create-simulation')setSimulationTitle('');
  if(['interview.transition','interview.correct-terminal','interview.correct-time','interview.transition-simulation'].includes(intent.operation)){setReason('');setTime(blankTime);}
  // Commit is known even if the subsequent query fails; only the submitted field loses its dirty flag.
  if(selected?.id===result.id){const next={...selected,revision:result.revision};if(intent.operation==='interview.save-document'){if(intent.document==='preparation')next.preparation=intent.text;if(intent.document==='transcript'&&intent.text!==selected.transcript?.text){next.transcript={text:intent.text,version:(selected.transcript?.version??0)+1};if(next.finalReview)next.finalReview={...next.finalReview,needsRecheck:true};}if(intent.document==='final-review')next.finalReview={text:intent.text,transcriptVersion:selected.transcript?.version??null,needsRecheck:false};}setSelected(next);}
  try{
   const r=Result.parse(await request({operation:'interview.read',id:result.id}));if(current!==generation.current)return;if(r.kind!=='session')throw Error('unreadable');
   if(selected?.id===r.session.id){setSelected(r.session);if(intent.operation==='interview.save-document'){if(intent.document==='preparation')setPreparation(r.session.preparation??'');if(intent.document==='transcript')setTranscript(r.session.transcript?.text??'');if(intent.document==='final-review')setReview(r.session.finalReview?.text??'');}}
   else adopt(r.session);
   try{await list(context,current);if(current===generation.current)setStatus('已保存');}catch{if(current===generation.current)setStatus('已保存，列表暂时未刷新；正文已回读');}if(current===generation.current)void loadHistory(r.session.id,current);
  }catch{if(current===generation.current)setStatus('已保存，正文暂不可重读；当前输入保留');}
 }
 async function submit(intent:Request,continueOriginal=false){if(busy||pending&&!continueOriginal)return;const current=generation.current;setBusy(true);setStatus('保存中');try{await apply(await sendInterviewIntent(request,intent),intent,current);}finally{if(current===generation.current)setBusy(false);}}
 async function receipt(){if(!pending||busy)return;const current=generation.current;setBusy(true);try{const r=Result.parse(await request({operation:'interview.receipt',commandId:('commandId'in pending)?pending.commandId:''}));await apply(r,pending,current);}catch{if(current===generation.current)setStatus('保存结果待核对，输入保留');}finally{if(current===generation.current)setBusy(false);}}
 function withTime(make:(businessTime:BusinessTime)=>Request,value=time){try{void submit(make(actualTime(value)));}catch{setStatus('业务时间格式无效，输入保留；未知不能补日期');}}
 function saveDocument(document:'preparation'|'transcript'|'final-review',text:string){if(!selected)return;void submit({operation:'interview.save-document',commandId:crypto.randomUUID(),id:selected.id,expectedRevision:selected.revision,document,text});}
 const disabled=busy||!!pending||loading||scopeChanged&&!dirty;
 return <section aria-label="面试子模块"><h2>真实面试与人工练习</h2><p>没有投递记录不妨碍已确认的真实面试；这里不会补造投递。练习不推进机会阶段。</p><p role="status">{status}</p>
 {scopeChanged&&<aside>有上一机会未提交输入，请先保存或明确放弃。<button disabled={busy||!!pending} onClick={()=>{if(window.confirm('放弃未提交输入，切换到新机会？'))setContext({opportunityId,workspaceInstance});}}>放弃输入并切换机会</button></aside>}
 <button disabled={disabled} onClick={()=>{void list().then(()=>setStatus('列表已刷新')).catch(()=>setStatus('列表读取失败，输入保留'));}}>重读轮次列表</button>
 {items.length===0&&<p>尚无面试轮次，可确认现实已存在的轮次；打开页面不会自动创建。</p>}
 <ul>{items.map(item=><li key={item.id}><button disabled={disabled} onClick={()=>void open(item)}>{item.kind==='simulation'?'练习：':''}{item.title}</button>（{stateNames[item.state]}）</li>)}</ul>
 <fieldset disabled={disabled}><legend>确认现实已存在的真实轮次</legend><label>真实轮次名称<input aria-label="真实轮次名称" value={title} onChange={e=>setTitle(e.target.value)}/></label><TimeInput label="现实确认时间" value={confirmation} onChange={setConfirmation}/><button disabled={!title.trim()||!coreRevision} onClick={()=>{if(selected&&(preparation!==(selected.preparation??'')||transcript!==(selected.transcript?.text??'')||review!==(selected.finalReview?.text??'')||reason||time.kind!=='unknown'||simulationTitle)){setStatus('当前轮次还有未提交输入，请先保存或取消');return;}withTime(businessTime=>({operation:'interview.confirm',commandId:crypto.randomUUID(),opportunityId:context.opportunityId,expectedOpportunityRevision:coreRevision,title:title.trim(),confirmationTime:businessTime}),confirmation);}}>确认存在真实轮次</button></fieldset>
 {coreConflict!==undefined&&<aside aria-label="确认轮次冲突比较">机会正式修订已为 {coreConflict}；草稿仍保留。<button onClick={()=>{setCoreRevision(coreConflict);setCoreConflict(undefined);setStatus('已采用机会新基线，请明确重试');}}>采用机会新基线并保留草稿</button></aside>}
 {selected&&<><h3>{selected.title}</h3><p>{selected.kind==='real'?'真实轮次':'模拟练习'} · <span>{stateNames[selected.state]}</span></p><p>确认：{displayTime(selected.confirmationTime)}；预约：{displayTime(selected.scheduledTime)}；完成：{displayTime(selected.completionTime)}</p>
 <fieldset disabled={disabled}><legend>当前人工文档</legend>{selected.kind==='real'&&<><label>当前准备<textarea aria-label="当前准备" value={preparation} onChange={e=>setPreparation(e.target.value)}/></label><button onClick={()=>saveDocument('preparation',preparation)}>保存当前准备</button></>}<label>当前文字稿<textarea aria-label="当前文字稿" value={transcript} onChange={e=>setTranscript(e.target.value)}/></label><button onClick={()=>saveDocument('transcript',transcript)}>保存当前文字稿</button><label>当前终版复盘<textarea aria-label="当前终版复盘" value={review} onChange={e=>setReview(e.target.value)}/></label><button onClick={()=>saveDocument('final-review',review)}>保存当前终版复盘</button>{selected.finalReview?.needsRecheck&&<p>文字稿依据变化，终版复盘待复核</p>}</fieldset>
 <fieldset disabled={disabled}><legend>{selected.kind==='real'?'现实排期、变化与明确纠错':'练习自身状态'}</legend><label>变化说明<input aria-label="面试变化说明" value={reason} onChange={e=>setReason(e.target.value)}/></label><TimeInput label="本次实际业务时间" value={time} onChange={setTime}/>{selected.kind==='real'?<><label>现实变化<select aria-label="现实变化" value={action} onChange={e=>setAction(e.target.value as typeof action)}><option value="schedule">排期或改期</option><option value="temporarily_cancel">临时取消待重约</option><option value="complete">真实完成</option><option value="permanently_cancel">永久取消</option></select></label><button disabled={!reason.trim()||['completed','permanently_cancelled'].includes(selected.state)} onClick={()=>withTime(businessTime=>({operation:'interview.transition',commandId:crypto.randomUUID(),id:selected.id,expectedRevision:selected.revision,action,businessTime,reason}))}>记录本轮真实变化</button>{['completed','permanently_cancelled'].includes(selected.state)&&<><label>纠错后的原轮次状态<select aria-label="纠错后的原轮次状态" value={correctState} onChange={e=>setCorrectState(e.target.value as RoundState)}>{Object.entries(stateNames).filter(([key])=>!['pending','cancelled'].includes(key)).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><button disabled={!reason.trim()} onClick={()=>withTime(businessTime=>({operation:'interview.correct-terminal',commandId:crypto.randomUUID(),id:selected.id,expectedRevision:selected.revision,state:correctState,businessTime,reason}))}>明确纠正本轮终态误操作</button></>}</>:<>{(['pending','completed','cancelled'] as const).map(state=><button key={state} disabled={!reason.trim()} onClick={()=>withTime(businessTime=>({operation:'interview.transition-simulation',commandId:crypto.randomUUID(),id:selected.id,expectedRevision:selected.revision,state,businessTime,reason}))}>{stateNames[state]}</button>)}</>}</fieldset>
 {selected.kind==='real'&&<fieldset disabled={disabled}><legend>纠正原轮次的业务时间</legend><p>只纠正原记录或补充已核实日期，不伪造新轮次；使用上方业务时间和变化说明。</p><label>纠正时间字段<select value={timeField} onChange={e=>setTimeField(e.target.value as typeof timeField)}><option value='confirmation'>真实确认时间</option><option value='scheduled'>预约时间</option><option value='completion'>完成时间</option></select></label><button disabled={!reason.trim()} onClick={()=>withTime(businessTime=>({operation:'interview.correct-time',commandId:crypto.randomUUID(),id:selected.id,expectedRevision:selected.revision,expectedOpportunityRevision:coreRevision,field:timeField,businessTime,reason}))}>明确纠正原轮次时间</button></fieldset>}
 {selected.kind==='real'&&<fieldset disabled={disabled}><legend>同机会、同真实轮次的人工练习</legend><label>练习名称<input aria-label="练习名称" value={simulationTitle} onChange={e=>setSimulationTitle(e.target.value)}/></label><button disabled={!simulationTitle.trim()} onClick={()=>{if((preparation!==(selected.preparation??'')||transcript!==(selected.transcript?.text??'')||review!==(selected.finalReview?.text??'')||reason||time.kind!=='unknown')){setStatus('真实轮次还有未提交输入，请先保存');return;}void submit({operation:'interview.create-simulation',commandId:crypto.randomUUID(),opportunityId:context.opportunityId,realRoundId:selected.id,title:simulationTitle.trim()});}}>创建关联练习</button></fieldset>}
 <button disabled={disabled} onClick={()=>{if(dirty&&!window.confirm('放弃本轮所有未提交输入？已保存内容不撤销。'))return;adopt(conflict??selected);setTitle('');setConfirmation(blankTime);setStatus('已放弃未提交输入，已保存内容保留');}}>放弃本轮所有未提交输入</button>
 <details><summary>本轮真实变化与纠错历史</summary><ul>{history.map(item=><li key={item.id}>{item.type}：{item.reason}；{displayTime(item.businessTime)}（录入时间 {item.recordedAt}）</li>)}</ul></details></>}
 {conflict&&<aside aria-label="面试冲突比较"><p>当前正式值：修订 {conflict.revision}，{stateNames[conflict.state]}</p><p>准备：{conflict.preparation??'未建立'}；文字稿：{conflict.transcript?.text??'未建立'}；终版复盘：{conflict.finalReview?.text??'未建立'}</p><button disabled={disabled} onClick={()=>{setSelected(conflict);setConflict(undefined);setStatus('已采用新基线，草稿保留，请明确重试');}}>采用面试新基线并保留草稿</button></aside>}
 {pending&&<aside><button disabled={busy} onClick={()=>void receipt()}>核对原保存回执</button>{receiptMissing&&<button disabled={busy} onClick={()=>{const original=pending;void submit(original,true);}}>继续原保存意图</button>}</aside>}
 </section>;
}
