import {useEffect,useRef,useState} from 'react';
import {BitableRawPreviewResult,BitableRawPreviewCancelled,BitableRawPreviewReady,BitableRawImportResult,type SelectedBitableRecordMetadata,type BitableRawPreview,type FeishuBitableRawPreviewBridge} from '../../../contracts/platform/feishu-bitable-raw-preview';
import {Result} from '../../../contracts/materials/schema';
import {useFeishuCacheEviction} from './feishu-cache-eviction';
const messages={invalid_request:'这次预览请求无效。',selected_snapshot_unavailable:'已选记录的会话快照已不可用。没有重新读取飞书，请先另行确认下一步。',preview_unavailable:'这份预览已失效，请重新生成本地预览。'};
export function BitableRawImportPreview({record,bridge=window.careerFeishuBitableRawPreview}:{record:SelectedBitableRecordMetadata;bridge?:FeishuBitableRawPreviewBridge}){
 const [preview,setPreview]=useState<BitableRawPreview>(),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[ready,setReady]=useState(false),flight=useRef(false);
 const [saved,setSaved]=useState(false),[unknown,setUnknown]=useState(false),command=useRef<string|undefined>(undefined);
 const generation=useRef(0),material=useRef<string|undefined>(undefined);
 useEffect(()=>()=>{generation.current++;},[]);
 useFeishuCacheEviction(notice=>{if(!notice.all&&!notice.recordRefs.includes(record.recordRef)&&!notice.previewRefs.includes(preview?.ref??'')&&!notice.materialIds.includes(material.current??''))return;generation.current++;if(preview)void bridge?.cancelRawPreview({previewRef:preview.ref}).catch(()=>{});material.current=undefined;command.current=undefined;flight.current=false;setPreview(undefined);setSaved(false);setUnknown(false);setReady(false);setBusy(false);setMessage('相关内容已永久清除，旧预览已关闭。');});
 async function action(kind:'prepare'|'cancel'|'ready'){
  if(!bridge||flight.current)return;const started=generation.current;flight.current=true;setBusy(true);setMessage('');try{
   if(kind==='prepare'){const response=BitableRawPreviewResult.parse(await bridge.prepareRawPreview({recordRef:record.recordRef}));if(started!==generation.current)return;if(response.kind==='failure'){setMessage(messages[response.reason]);return;}setPreview(response);setReady(false);setSaved(false);setUnknown(false);command.current=undefined;}
   else if(preview&&kind==='cancel'){const response=BitableRawPreviewCancelled.parse(await bridge.cancelRawPreview({previewRef:preview.ref}));if(started!==generation.current)return;if(response.kind==='failure'){setMessage(messages[response.reason]);return;}setPreview(undefined);setReady(false);}
   else if(preview){const response=BitableRawPreviewReady.parse(await bridge.readyRawPreview({previewRef:preview.ref,previewDigest:preview.provenance.preview_digest}));if(started!==generation.current)return;if(response.kind==='failure'){setMessage(messages[response.reason]);return;}setReady(true);}
 }catch{if(started===generation.current)setMessage('本地预览未完成，没有读取飞书或保存材料。');}finally{if(started===generation.current){flight.current=false;setBusy(false);}}
 }
 async function save(){
  if(!preview||!bridge?.importRawPreview||flight.current||saved||unknown)return;
  const started=generation.current;flight.current=true;setBusy(true);setMessage('');command.current??=crypto.randomUUID();
  try{const result=BitableRawImportResult.parse(await bridge.importRawPreview({commandId:command.current,previewRef:preview.ref,previewDigest:preview.provenance.preview_digest}));
   if(started!==generation.current)return;if(result.kind==='raw_saved'){command.current=result.commandId;material.current=result.materialId;setSaved(true);return;}
   if(result.reason==='result_unknown'){setUnknown(true);setMessage('保存结果暂时无法确认。请先检查是否已保存，不要重新导入。');}
   else setMessage(result.reason==='preview_unavailable'?messages.preview_unavailable:result.reason==='invalid_request'?messages.invalid_request:'保存未完成，没有再次读取飞书。');
  }catch{if(started===generation.current){setUnknown(true);setMessage('保存结果暂时无法确认。请先检查是否已保存，不要重新导入。');}}
  finally{if(started===generation.current){flight.current=false;setBusy(false);}}
 }
 async function checkSaved(){if(!command.current||flight.current||!preview)return;const started=generation.current;flight.current=true;setBusy(true);try{const result=Result.parse(await window.careerMaterials.request({operation:'receipt',commandId:command.current}));if(started!==generation.current)return;if(result.kind==='receipt'&&result.receipt.status==='committed'){material.current=result.receipt.materialId;const read=Result.parse(await window.careerMaterials.request({operation:'read',materialId:result.receipt.materialId}));if(started!==generation.current)return;if(read.kind==='raw'&&read.raw.text===preview.text){setSaved(true);setUnknown(false);setMessage('已保存，内容与预览一致。');}else setMessage('已保存，但暂时无法核对内容。不要重新导入。');}else setMessage('尚未确认这次保存，请检查后台连接。没有自动重试。');}catch{if(started===generation.current)setMessage('暂时无法检查保存结果，请检查后台连接后再检查。');}finally{if(started===generation.current){flight.current=false;setBusy(false);}}}
 return <section className="bitable-raw-preview" aria-label="Raw 导入预览"><div className="bitable-structure-heading"><h3>导入预览</h3>{!preview&&<button className="button" disabled={!bridge||busy} onClick={()=>void action('prepare')}>生成导入预览</button>}</div><p className="muted">{saved?'材料已保存。':'只使用已读取的选中记录，确认后才保存。'}不会再次读取飞书，也不会调用 AI。</p>{message&&<p role="alert">{message}</p>}
 {preview&&<><h4>即将保存到 Career</h4><p className="bitable-raw-source">来源：飞书 · Bitable Record<br/>{preview.source.bitableTitle} → {preview.source.tableName} → {preview.source.viewName} → {preview.title}</p><pre className="bitable-raw-text" aria-label="规范化 Raw 内容">{preview.text}</pre><details><summary>将保留的字段（{preview.includedFields.length}）</summary><ul>{preview.includedFields.map((field,i)=><li key={i}>{field.name}{field.mode==='count_placeholder'?'（仅数量占位）':''}</li>)}</ul></details>
 {preview.excludedComplexFields.length>0&&<details open><summary>不导入的完整内容（{preview.excludedComplexFields.length}）</summary><ul>{preview.excludedComplexFields.map((field,i)=><li key={i}>{field.name}：{field.reason==='content_not_read'?'未读取':field.reason==='not_expanded'?'未展开':field.reason==='display_not_available'?'已读快照没有显示值':'本轮不展开'}</li>)}</ul></details>}{preview.ignoredFields.length>0&&<details><summary>忽略的字段（{preview.ignoredFields.length}）</summary><ul>{preview.ignoredFields.map((field,i)=><li key={i}>{field.name}：{field.reason==='empty'?'空值':field.reason==='technical_field'?'技术信息':field.reason==='display_not_available'?'无已有显示值':'本轮不支持'}</li>)}</ul></details>}
 <details><summary>来源详情</summary><p>读取时间：{preview.provenance.retrieved_at??'上轮未记录'}<br/>选择确认时间：{preview.provenance.selected_at}<br/>来源更新时间：{preview.provenance.upstream_updated_at??'未提供'}</p></details><div className="bitable-raw-actions">{!saved&&<button className="text-button" disabled={busy||unknown} onClick={()=>void action('cancel')}>取消预览</button>}{unknown&&<button className="button" disabled={busy} onClick={()=>void checkSaved()}>检查是否已保存</button>}{bridge?.importRawPreview?<button className="button" disabled={busy||saved||unknown} onClick={()=>void save()}>{saved?'已保存':busy?'正在保存…':'确认保存 Raw'}</button>:<button className="button" disabled={busy||ready} onClick={()=>void action('ready')}>下一步确认导入</button>}</div>{saved?<p role="status">已保存为 1 条 Raw。再次确认不会重复创建。</p>:ready&&<p role="status">预览已准备好，尚未导入。等待你明确确认保存。</p>}</>}
 </section>;
}
