import {it,expect} from 'vitest';
import {launchBrowserFixture,skipTutorial} from '../fixtures/browser-host';
it('explicit TEST fake passes final authorization over the real Node/Browser boundary',async()=>{
 const f=await launchBrowserFixture({fake:true});try{await skipTutorial(f.page);const result=await f.page.evaluate(async()=>{const call=(m:any,i:any)=>window.career.request(m,i) as Promise<any>;const c=await call('opportunity',{operation:'company.create',commandId:crypto.randomUUID(),name:'E2 TEST Company'}),o=await call('opportunity',{operation:'create',commandId:crypto.randomUUID(),companyId:c.company.id,role:'E2 TEST Analyst'});const prepared=await call('ai',{operation:'product.prepare',commandId:crypto.randomUUID(),input:{target:{kind:'research-organize',owner:{kind:'opportunity',id:o.opportunity.id}},sources:[],egressSourceIds:[],wikiIds:[],egressWikiIds:[],objects:[]},budget:{requests:2,inputBytes:524288,outputBytes:196608}});const op=prepared.task.operations[0];const authorized=await call('ai',{operation:'product.authorize',commandId:crypto.randomUUID(),operationId:op.id,manifestDigest:op.manifestDigest});return {prepared,authorized};});expect(result.authorized.kind).toBe('product_task');await expect.poll(()=>f.page.evaluate(id=>window.career.request('ai',{operation:'product.read',taskId:id}),result.prepared.task.id)).toMatchObject({kind:'product_task',task:{operations:[{state:'success'}],proposals:[{state:'pending'},{state:'pending'}]}});
 }finally{await f.close();}
},60000);
it('unconfigured production host cannot activate a fake provider or expose a stored key through browser commands',async()=>{
 const f=await launchBrowserFixture();try{await skipTutorial(f.page);const result=await f.page.evaluate(async()=>{const status=await window.careerSecrets.request({operation:'status'});const c:any=await window.career.request('opportunity',{operation:'company.create',commandId:crypto.randomUUID(),name:'E2 TEST disabled provider'});const prepared=await window.career.request('ai',{operation:'product.prepare',commandId:crypto.randomUUID(),input:{target:{kind:'research-organize',owner:{kind:'company',id:c.company.id}},sources:[],egressSourceIds:[],wikiIds:[],egressWikiIds:[],objects:[]},budget:{requests:1,inputBytes:524288,outputBytes:196608}});return {status,prepared,read:await window.careerSecrets.request({operation:'read'} as never),tasks:await window.career.request('ai',{operation:'product.list'})};});expect(result.status).toMatchObject({kind:'status',status:{configured:false,enabled:false}});expect(result.prepared).toMatchObject({kind:'failure'});expect(result.tasks).toEqual({kind:'product_tasks',tasks:[]});expect(result.read).toEqual({kind:'failure',code:'invalid_request'});
 }finally{await f.close();}
},45000);
