import {it,expect} from 'vitest';
import {_electron} from 'playwright';
import {mkdir,rm,readFile,writeFile,mkdtemp} from 'node:fs/promises';
import path from 'node:path';
it('frontend A: onboarding, named 600px shell and auxiliary panels preserve a real TEST DATA editor',async()=>{
 const base=path.resolve('out/verification/frontend-a/PACKAGED-TEST-DATA');await mkdir(base,{recursive:true});const profile=await mkdtemp(path.join(base,'profile-')); 
 const packaged=process.env.CAREER_PACKAGED==='1';const options={executablePath:packaged?path.resolve(process.env.CAREER_PACKAGED_EXECUTABLE??'out/CareerNext-darwin-arm64/CareerNext.app/Contents/MacOS/CareerNext'):undefined,args:packaged?[`--user-data-dir=${profile}`]:['.',`--user-data-dir=${profile}`],timeout:30000};
 let app=await _electron.launch(options);try{
  let page=await app.firstWindow();page.setDefaultTimeout(10000);await page.getByRole('navigation',{name:'一级导航'}).waitFor();await page.evaluate(()=>{window.confirm=()=>true;});
  await page.getByRole('button',{name:'帮助',exact:true}).waitFor({timeout:3000});
  const onboarding=page.getByRole('region',{name:'新手教程'});await onboarding.waitFor();await onboarding.getByRole('button',{name:'下一步'}).click();await onboarding.getByRole('button',{name:'上一步'}).click();await onboarding.getByRole('button',{name:'下一步'}).click();await onboarding.getByRole('button',{name:'下一步'}).click();await onboarding.getByRole('button',{name:'下一步'}).click();await onboarding.getByRole('button',{name:'完成',exact:true}).click();await expect.poll(()=>onboarding.count()).toBe(0);
  const empty=await page.evaluate(async()=>{const o:any=await window.career.request('opportunity',{operation:'list'}),p:any=await window.career.request('profile',{operation:'profile.read'}),projects:any=await window.career.request('project',{operation:'list'});return {opportunities:o.items.length,profile:p.profile.revision,projects:projects.projects.length};});expect(empty).toEqual({opportunities:0,profile:0,projects:0});
  await page.getByRole('button',{name:'修改机会的简历',exact:true}).click();await page.getByRole('dialog',{name:'选择要修改简历的机会'}).getByRole('button',{name:'先去创建机会'}).click();expect(page.url()).toContain('/opportunity');await page.getByRole('link',{name:'Wiki',exact:true}).click();
  await page.getByRole('button',{name:'帮助',exact:true}).click();const help=page.getByRole('dialog',{name:'如何使用 Career',exact:true});await help.waitFor();await help.getByText('我看到一个岗位，应该从哪里开始？',{exact:true}).click();expect(await help.textContent()).toContain('选择或填写公司');await help.getByRole('button',{name:'重新查看新手教程'}).click();await help.getByRole('button',{name:'跳过',exact:true}).click();await help.getByRole('button',{name:'返回原任务',exact:true}).click();
  await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setBounds({width:600,height:820}));await page.getByRole('button',{name:'收起侧栏'}).click();for(const name of ['Wiki','机会','项目','任职'])expect(await page.getByRole('link',{name,exact:true}).isVisible()).toBe(true);expect(await page.getByRole('link',{name:'Wiki',exact:true}).getAttribute('aria-current')).toBe('page');expect(await page.getByRole('navigation').getByRole('button',{name:/置顶|上移/}).count()).toBe(0);expect(await page.getByRole('button',{name:'反馈',exact:true}).evaluate(el=>el.getBoundingClientRect().bottom<=innerHeight&&el.getBoundingClientRect().top>innerHeight/2)).toBe(true);
  await page.getByRole('button',{name:'设置',exact:true}).click();const settings=page.getByRole('dialog',{name:'设置',exact:true});await settings.waitFor();await settings.getByLabel('新凭据').fill('UNSAVED TEST SECRET INPUT');await settings.getByText('导航设置',{exact:true}).click();await settings.getByRole('button',{name:'置顶机会首页',exact:true}).click();await settings.getByRole('button',{name:'上移项目',exact:true}).click();await settings.getByRole('button',{name:'返回原任务',exact:true}).click();await page.getByRole('button',{name:'设置',exact:true}).click();expect(await settings.getByLabel('新凭据').inputValue()).toBe('');await settings.getByRole('button',{name:'返回原任务',exact:true}).click();
  const fixture=await page.evaluate(async()=>{const call=async(module:any,input:any):Promise<any>=>window.career.request(module,input);const c=await call('opportunity',{operation:'company.create',commandId:crypto.randomUUID(),name:'Frontend A TEST DATA'}),o=await call('opportunity',{operation:'create',commandId:crypto.randomUUID(),companyId:c.company.id,role:'Frontend A TEST ROLE'}),r=await call('resume',{operation:'resume.open',commandId:crypto.randomUUID(),opportunityId:o.opportunity.id});return {opportunityId:o.opportunity.id,resumeId:r.document.id};});
  await page.getByRole('link',{name:'机会',exact:true}).click();await page.getByRole('button',{name:'修改机会的简历',exact:true}).click();const chooser=page.getByRole('dialog',{name:'选择要修改简历的机会'});await chooser.getByRole('button',{name:'Frontend A TEST DATA · Frontend A TEST ROLE'}).click();
  const editor=page.getByRole('textbox',{name:'简历正文',exact:true});await editor.waitFor();expect(page.url()).toContain(fixture.opportunityId+'/resume');await editor.locator('p').first().click();await page.keyboard.type('FRONTEND A SESSION TEST');await page.getByTestId('resume-save-state').filter({hasText:'已保存'}).waitFor();
  await editor.locator('p').first().click();await page.keyboard.press('ControlOrMeta+a');const selected=await page.evaluate(()=>window.getSelection()?.toString());
  for(const action of ['帮助','设置']){await page.getByRole('button',{name:action,exact:true}).click();const dialog=page.getByRole('dialog',{name:action==='帮助'?'如何使用 Career':'设置',exact:true});await dialog.waitFor();await dialog.getByRole('button',{name:'返回原任务',exact:true}).click();expect(await page.evaluate(()=>window.getSelection()?.toString())).toBe(selected);expect(await editor.textContent()).toContain('FRONTEND A SESSION TEST');}
  await page.getByRole('button',{name:'反馈',exact:true}).click();await page.getByLabel('反馈内容').fill('Frontend A feedback draft TEST');await page.getByRole('button',{name:'返回原任务（保留反馈草稿）'}).click();await page.getByRole('button',{name:'反馈',exact:true}).click();expect(await page.getByLabel('反馈内容').inputValue()).toBe('Frontend A feedback draft TEST');await page.getByLabel('反馈内容').fill('');await page.getByRole('button',{name:'返回原任务（保留反馈草稿）'}).click();
  await page.getByRole('button',{name:'撤销',exact:true}).click();expect(await editor.textContent()).not.toContain('FRONTEND A SESSION TEST');await page.getByRole('button',{name:'重做',exact:true}).click();expect(await editor.textContent()).toContain('FRONTEND A SESSION TEST');
  expect(await page.getByRole('navigation').textContent()).not.toMatch(/[a-f0-9]{8}-[a-f0-9]{4}|commandId|revision|receipt|operation|JSON/);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setBounds({width:1280,height:850}));await page.getByTestId('resume-save-state').filter({hasText:'已保存'}).waitFor();
  // The same formal Settings owner can restore a TEST DATA backup and reconnect the editor.
  await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByText('备份与恢复',{exact:true}).click();const maintenance=page.getByRole('region',{name:'资料维护设置'});await maintenance.getByRole('button',{name:'立即建立备份',exact:true}).click();await expect.poll(()=>maintenance.getByRole('status').textContent()).toContain('完整恢复点已建立');await maintenance.getByRole('button',{name:'检查并准备恢复',exact:true}).click();await page.getByRole('dialog',{name:'确认恢复',exact:true}).getByRole('button',{name:'确认切换资料',exact:true}).click();await page.getByRole('dialog',{name:'设置',exact:true}).waitFor({state:'hidden'});await page.evaluate(id=>{location.hash='#/opportunity/'+id+'/resume';},fixture.opportunityId);await page.getByRole('textbox',{name:'简历正文',exact:true}).waitFor();await expect.poll(()=>page.getByRole('textbox',{name:'简历正文',exact:true}).textContent()).toContain('FRONTEND A SESSION TEST');
  // Save the existing explicit Resume deep link as the normal launch URL, without adding a test capability.
  await app.evaluate(({dialog})=>{dialog.showMessageBoxSync=(()=>1) as typeof dialog.showMessageBoxSync;});await app.close();app=await _electron.launch(options);page=await app.firstWindow();await page.getByRole('navigation',{name:'一级导航'}).waitFor();expect(await page.getByRole('region',{name:'新手教程'}).count()).toBe(0);expect(await page.getByRole('navigation').getByRole('link').first().textContent()).toContain('机会');
  await page.evaluate(id=>{localStorage.removeItem('career.ui.introduction.v1');location.hash='#/opportunity/'+id+'/resume';},fixture.opportunityId);await page.reload();await page.getByRole('textbox',{name:'简历正文',exact:true}).waitFor();expect(await page.getByRole('region',{name:'新手教程'}).count()).toBe(0);
  await writeFile('out/verification/frontend-a/packaged-results.json',JSON.stringify({packaged,profile,fixture,onboarding:true,businessDataNotCreatedByOnboarding:true,help:true,namedSidebar:true,navigationSettings:true,quickResumeOwner:true,selection:true,undoRedo:true,feedbackDraft:true,width600:true,width1280:true,deepLink:true,persistence:true,backupRestore:true,realIME:'NOT RUN; prior alignment human PASS preserved'},null,2));
 }finally{await app.evaluate(({dialog})=>{dialog.showMessageBoxSync=(()=>1) as typeof dialog.showMessageBoxSync;}).catch(()=>{});await app.close();}
},120000);
