import {it,expect} from 'vitest';
import {_electron} from 'playwright';
import {mkdir,mkdtemp,writeFile} from 'node:fs/promises';
import path from 'node:path';
it('opportunity opens as a readable list, then one six-section detail with a real owned Resume',async()=>{
 const base=path.resolve('out/verification/frontend-b/TEST-DATA');await mkdir(base,{recursive:true});const profile=await mkdtemp(path.join(base,'profile-')),packaged=process.env.CAREER_PACKAGED==='1';
 const app=await _electron.launch({executablePath:packaged?path.resolve(process.env.CAREER_PACKAGED_EXECUTABLE??'out/CareerNext-darwin-arm64/CareerNext.app/Contents/MacOS/CareerNext'):undefined,args:packaged?[`--user-data-dir=${profile}`]:['.',`--user-data-dir=${profile}`],timeout:30000});
 try{const page=await app.firstWindow();page.setDefaultTimeout(10000);await page.getByRole('navigation',{name:'一级导航'}).waitFor();await page.evaluate(()=>{window.confirm=()=>true;});const fixture=await page.evaluate(async()=>{const call=async(module:any,input:any):Promise<any>=>window.career.request(module,input);const c=await call('opportunity',{operation:'company.create',commandId:crypto.randomUUID(),name:'Frontend B TEST Company'});const o=await call('opportunity',{operation:'create',commandId:crypto.randomUUID(),companyId:c.company.id,role:'Frontend B TEST Analyst'});return {opportunityId:o.opportunity.id};});
 await page.getByRole('link',{name:'机会',exact:true}).click();await page.getByRole('region',{name:'机会',exact:true}).getByRole('button',{name:'刷新',exact:true}).click();expect(await page.getByLabel('公司名称',{exact:true}).isVisible().catch(()=>false)).toBe(false);
 await page.getByRole('button',{name:'Frontend B TEST Company · Frontend B TEST Analyst',exact:true}).click();await page.getByRole('navigation',{name:'机会分区'}).waitFor();expect(page.url()).toContain(fixture.opportunityId+'/overview');expect(await page.getByRole('button',{name:'新建机会',exact:true}).isVisible().catch(()=>false)).toBe(false);
 for(const label of ['概览','简历','情报','沟通','面试','Offer'])expect(await page.getByRole('navigation',{name:'机会分区'}).getByRole('button',{name:label,exact:true}).isVisible()).toBe(true);
 await page.getByRole('button',{name:'返回机会列表',exact:true}).click();expect(page.url().endsWith('#/opportunity')).toBe(true);await page.getByRole('button',{name:'Frontend B TEST Company · Frontend B TEST Analyst',exact:true}).click();
 const tabs=page.getByRole('navigation',{name:'机会分区'});
 await tabs.getByRole('button',{name:'情报',exact:true}).click();const research=page.getByRole('region',{name:'岗位情报',exact:true});await research.getByRole('status').filter({hasText:'已读取'}).waitFor();expect(await research.getByLabel('研究正文',{exact:true}).isVisible()).toBe(false);await research.getByRole('button',{name:'记录情报',exact:true}).click();await research.getByLabel('研究标题',{exact:true}).fill('Frontend B unsaved research');await research.getByLabel('研究正文',{exact:true}).fill('TEST DATA research draft stays across sections');await tabs.getByRole('button',{name:'概览',exact:true}).click();await tabs.getByRole('button',{name:'情报',exact:true}).click();expect(await research.getByLabel('研究正文',{exact:true}).inputValue()).toBe('TEST DATA research draft stays across sections');
 await tabs.getByRole('button',{name:'沟通',exact:true}).click();const communication=page.getByRole('region',{name:'沟通记录',exact:true});await communication.getByRole('status').filter({hasText:'沟通列表'}).waitFor();expect(await communication.getByLabel('沟通正文',{exact:true}).isVisible()).toBe(false);await communication.getByRole('button',{name:'记录沟通',exact:true}).click();await communication.getByLabel('沟通正文',{exact:true}).fill('Frontend B communication draft TEST DATA');await tabs.getByRole('button',{name:'情报',exact:true}).click();await tabs.getByRole('button',{name:'沟通',exact:true}).click();expect(await communication.getByLabel('沟通正文',{exact:true}).inputValue()).toContain('communication draft');const submission=page.getByRole('region',{name:'首次投递',exact:true});await submission.getByRole('button',{name:'记录已投递',exact:true}).click();expect(await submission.getByRole('button',{name:'确认真实首次投递',exact:true}).isVisible()).toBe(true);await communication.getByRole('button',{name:'明确取消当前草稿',exact:true}).click();await tabs.getByRole('button',{name:'情报',exact:true}).click();
 await tabs.getByRole('button',{name:'面试',exact:true}).click();const interview=page.getByRole('region',{name:'面试子模块',exact:true});await interview.getByRole('status').filter({hasText:'面试记录已读取'}).waitFor();expect(await interview.getByLabel('真实轮次名称',{exact:true}).isVisible()).toBe(false);await interview.getByRole('button',{name:'记录面试',exact:true}).click();await interview.getByLabel('真实轮次名称',{exact:true}).fill('Frontend B pending scheduling TEST');await tabs.getByRole('button',{name:'Offer',exact:true}).click();const offer=page.getByRole('region',{name:'Offer',exact:true});await offer.getByRole('status').filter({hasText:'已读取'}).waitFor();expect(await offer.getByLabel('条件中的岗位',{exact:true}).isVisible()).toBe(false);await offer.getByRole('button',{name:'记录 Offer',exact:true}).click();await offer.getByLabel('条件中的岗位',{exact:true}).fill('Frontend B Offer unsaved TEST');await tabs.getByRole('button',{name:'面试',exact:true}).click();expect(await interview.getByLabel('真实轮次名称',{exact:true}).inputValue()).toContain('pending scheduling');await tabs.getByRole('button',{name:'Offer',exact:true}).click();expect(await offer.getByLabel('条件中的岗位',{exact:true}).inputValue()).toContain('Offer unsaved');await offer.getByRole('button',{name:'取消未保存输入',exact:true}).click();await tabs.getByRole('button',{name:'面试',exact:true}).click();await interview.getByRole('button',{name:'取消新面试输入',exact:true}).click();await tabs.getByRole('button',{name:'情报',exact:true}).click();
 await research.getByRole('button',{name:'取消未保存输入',exact:true}).click();
 await writeFile('out/verification/frontend-b/desktop-results.json',JSON.stringify({packaged,profile,fixture,list:true,detail:true,return:true},null,2));
 }catch(error){const page=await app.firstWindow();await writeFile('out/verification/frontend-b/last-failure.txt',await page.locator('body').innerText());throw error;}finally{await app.evaluate(({dialog})=>{dialog.showMessageBoxSync=(()=>1) as typeof dialog.showMessageBoxSync;}).catch(()=>{});await app.close();}
},120000);
it('single new flow validates company and role, then creates each through its formal owner without duplicates',async()=>{
 const base=path.resolve('out/verification/frontend-b/TEST-DATA');await mkdir(base,{recursive:true});const profile=await mkdtemp(path.join(base,'create-')),packaged=process.env.CAREER_PACKAGED==='1';
 const app=await _electron.launch({executablePath:packaged?path.resolve(process.env.CAREER_PACKAGED_EXECUTABLE??'out/CareerNext-darwin-arm64/CareerNext.app/Contents/MacOS/CareerNext'):undefined,args:packaged?[`--user-data-dir=${profile}`]:['.',`--user-data-dir=${profile}`],timeout:30000});
 try{const page=await app.firstWindow();page.setDefaultTimeout(10000);await page.getByRole('navigation',{name:'一级导航'}).waitFor();await page.getByRole('link',{name:'机会',exact:true}).click();await page.getByRole('button',{name:'新建机会',exact:true}).click();await page.getByLabel('公司填写方式').selectOption('new');const name=page.getByLabel('公司名称',{exact:true}).filter({visible:true});await name.fill('Frontend B new TEST Company');await page.getByRole('button',{name:'返回机会列表（保留新建输入）'}).click();await page.getByRole('button',{name:'新建机会',exact:true}).click();expect(await page.getByLabel('公司名称',{exact:true}).filter({visible:true}).inputValue()).toBe('Frontend B new TEST Company');await page.getByLabel('岗位名称',{exact:true}).fill('Preserved unfinished role TEST');await page.getByRole('button',{name:'返回机会列表（保留新建输入）'}).click();await page.getByRole('button',{name:'新建机会',exact:true}).click();expect(await page.getByLabel('公司名称',{exact:true}).filter({visible:true}).inputValue()).toBe('Frontend B new TEST Company');expect(await page.getByLabel('岗位名称',{exact:true}).inputValue()).toBe('Preserved unfinished role TEST');await page.getByLabel('岗位名称',{exact:true}).fill('');
 // Incomplete new flow must not create a business object.
 await page.getByRole('button',{name:'创建机会',exact:true}).click();await page.getByRole('status').filter({hasText:'请填写公司和岗位'}).waitFor();const known=await page.evaluate(async()=>({companies:await window.career.request('opportunity',{operation:'company.list'}),opportunities:await window.career.request('opportunity',{operation:'list'})})) as any;expect(known.companies.items).toHaveLength(0);expect(known.opportunities.items).toHaveLength(0);
 await page.getByLabel('岗位名称',{exact:true}).fill('TEST new role');await page.getByRole('button',{name:'创建机会',exact:true}).click();await page.getByRole('heading',{name:'Frontend B new TEST Company · TEST new role',exact:true}).waitFor();const after=await page.evaluate(async()=>({companies:await window.career.request('opportunity',{operation:'company.list'}),opportunities:await window.career.request('opportunity',{operation:'list'})})) as any;expect(after.companies.items).toHaveLength(1);expect(after.opportunities.items).toHaveLength(1);expect(after.opportunities.items[0].companyId).toBe(after.companies.items[0].id);
 }catch(error){const page=await app.firstWindow();await writeFile('out/verification/frontend-b/last-failure.txt',await page.locator('body').innerText());throw error;}finally{await app.evaluate(({dialog})=>{dialog.showMessageBoxSync=(()=>1) as typeof dialog.showMessageBoxSync;}).catch(()=>{});await app.close();}
},90000);
it('real TEST DATA journey retains Resume, Wiki/Search deep links, auxiliary panels and 600px section drafts',async()=>{
 const base=path.resolve('out/verification/frontend-b/TEST-DATA');await mkdir(base,{recursive:true});const profile=await mkdtemp(path.join(base,'journey-')),packaged=process.env.CAREER_PACKAGED==='1';
 const app=await _electron.launch({executablePath:packaged?path.resolve(process.env.CAREER_PACKAGED_EXECUTABLE??'out/CareerNext-darwin-arm64/CareerNext.app/Contents/MacOS/CareerNext'):undefined,args:packaged?[`--user-data-dir=${profile}`]:['.',`--user-data-dir=${profile}`],timeout:30000});
 try{const page=await app.firstWindow();page.setDefaultTimeout(10000);await page.getByRole('navigation',{name:'一级导航'}).waitFor();await page.evaluate(()=>{window.confirm=()=>true;});const fixture=await page.evaluate(async()=>{const call=(module:any,input:any)=>window.career.request(module,input) as Promise<any>;const c=await call('opportunity',{operation:'company.create',commandId:crypto.randomUUID(),name:'B JOURNEY TEST'}),o=await call('opportunity',{operation:'create',commandId:crypto.randomUUID(),companyId:c.company.id,role:'Section continuity TEST'});return {id:o.opportunity.id};});
 await page.evaluate(id=>{location.hash='#/opportunity/'+id+'/research';},fixture.id);let tabs=page.getByRole('navigation',{name:'机会分区'});await tabs.getByRole('button',{name:'情报',exact:true}).waitFor();expect(await tabs.getByRole('button',{name:'情报',exact:true}).getAttribute('aria-current')).toBe('page');const research=page.getByRole('region',{name:'岗位情报',exact:true});await research.getByRole('button',{name:'记录情报',exact:true}).click();await research.getByLabel('研究标题',{exact:true}).fill('B research TEST');await research.getByLabel('研究正文',{exact:true}).fill('Fictional TEST DATA, not independently verified.');await research.getByRole('button',{name:'保存研究',exact:true}).click();await research.getByRole('status').filter({hasText:'已保存'}).waitFor();await research.getByRole('button',{name:'取消未保存输入',exact:true}).click();expect(await research.getByRole('article',{name:'情报阅读'}).textContent()).toContain('未独立核验');
 await page.getByRole('link',{name:'Wiki',exact:true}).click();await page.getByRole('region',{name:'Wiki 知识'}).getByText('更多',{exact:true}).click();await page.getByRole('button',{name:'查看机会情报引用',exact:true}).click();const refs=page.getByRole('region',{name:'Wiki 研究引用'});await refs.getByRole('button',{name:'刷新研究机会'}).click();await refs.getByLabel('查看哪个机会的研究引用').selectOption(fixture.id);await refs.getByRole('heading',{name:'B research TEST'}).waitFor();await refs.getByRole('button',{name:'到所属机会编辑研究正本'}).click();expect(page.url()).toContain(fixture.id+'/research');await tabs.getByRole('button',{name:'简历',exact:true}).click();const editor=page.getByRole('textbox',{name:'简历正文',exact:true});await editor.waitFor();await editor.locator('p').first().click();await page.keyboard.type('FRONTEND B RESUME SESSION');await page.getByTestId('resume-save-state').filter({hasText:'已保存'}).waitFor();await page.getByRole('button',{name:'正文居中',exact:true}).click();await page.getByTestId('resume-save-state').filter({hasText:'已保存'}).waitFor();
 await tabs.getByRole('button',{name:'情报',exact:true}).click();await research.getByRole('button',{name:'修改情报',exact:true}).click();await research.getByLabel('研究正文',{exact:true}).fill('B UNSAVED research draft TEST');
 for(const action of ['帮助','设置']){await page.getByRole('button',{name:action,exact:true}).click();const dialog=page.getByRole('dialog',{name:action==='帮助'?'如何使用 Career':'设置',exact:true});await dialog.waitFor();await dialog.getByRole('button',{name:'返回原任务',exact:true}).click();expect(page.url()).toContain(fixture.id+'/research');expect(await research.getByLabel('研究正文',{exact:true}).inputValue()).toBe('B UNSAVED research draft TEST');}
 await tabs.getByRole('button',{name:'简历',exact:true}).click();expect(await editor.textContent()).toContain('FRONTEND B RESUME SESSION');expect(await editor.locator('p').first().evaluate(el=>getComputedStyle(el).textAlign)).toBe('center');await page.getByRole('button',{name:'返回所属机会',exact:true}).click();expect(page.url()).toContain(fixture.id+'/overview');
 await page.getByRole('button',{name:'设置',exact:true}).click();const settings=page.getByRole('dialog',{name:'设置',exact:true});await settings.getByRole('button',{name:'高级资料维护',exact:true}).click();await settings.getByText('本地资料搜索',{exact:true}).click();const search=settings.getByRole('region',{name:'本地资料检索'});await search.getByLabel('查找范围').selectOption('opportunity');await search.getByLabel('查找内容').fill('Section continuity');await search.getByRole('button',{name:'查找本地资料'}).click();await search.getByRole('button',{name:/B JOURNEY TEST.*Section continuity TEST/}).click();expect(page.url()).toContain(fixture.id+'/overview');expect(await settings.isVisible()).toBe(false);
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setBounds({width:600,height:820}));for(const label of ['情报','沟通','面试','Offer','概览']){await tabs.getByRole('button',{name:label,exact:true}).click();expect(await tabs.getByRole('button',{name:label,exact:true}).getAttribute('aria-current')).toBe('page');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}await tabs.getByRole('button',{name:'情报',exact:true}).click();expect(await research.getByLabel('研究正文',{exact:true}).inputValue()).toBe('B UNSAVED research draft TEST');await research.getByRole('button',{name:'取消未保存输入',exact:true}).click();await tabs.getByRole('button',{name:'概览',exact:true}).click();expect(await page.getByRole('button',{name:'确认用户退出',exact:true}).isVisible()).toBe(false);await page.getByText('更多',{exact:true}).filter({visible:true}).click();await page.getByRole('button',{name:'纠正阶段 / 结束机会 / 后来现实继续',exact:true}).click();expect(await page.getByRole('button',{name:'确认用户退出',exact:true}).isVisible()).toBe(true);expect(await page.getByRole('button',{name:'保存机会修改',exact:true}).isVisible()).toBe(true);
 await page.getByText('更多',{exact:true}).filter({visible:true}).click();await page.getByRole('button',{name:'返回机会列表',exact:true}).click();expect(await page.getByRole('button',{name:'确认用户退出',exact:true}).isVisible()).toBe(false);expect(await page.getByRole('region',{name:'机会',exact:true}).innerText()).not.toMatch(/[a-f0-9]{8}-[a-f0-9]{4}|commandId|revision|receipt|JSON|operation/);await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setBounds({width:1280,height:850}));
 await writeFile('out/verification/frontend-b/journey-results.json',JSON.stringify({packaged,profile,fixture,deepLink:true,wikiReference:true,localSearch:true,resumeReturn:true,alignment:true,sectionDraft:true,helpSettings:true,lowFrequency:true,width600:true,width1280:true,realDataChanged:false},null,2));
 }catch(error){const page=await app.firstWindow();await writeFile('out/verification/frontend-b/last-failure.txt',await page.locator('body').innerText());throw error;}finally{await app.evaluate(({dialog})=>{dialog.showMessageBoxSync=(()=>1) as typeof dialog.showMessageBoxSync;}).catch(()=>{});await app.close();}
},120000);
