import{it,expect}from'vitest';import {launchBrowserFixture} from '../fixtures/browser-host';import{mkdir,mkdtemp,writeFile}from'node:fs/promises';import path from'node:path';
it('A6 Node/Browser UI keeps four entries, tabular stages and Resume selection across avatar auxiliaries',async()=>{
 const base=path.resolve('out/verification/frontend-a6/TEST-DATA');await mkdir(base,{recursive:true});const profile=await mkdtemp(path.join(base,'profile-'));const f=await launchBrowserFixture({profile});const page=f.page;page.setDefaultTimeout(12000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 try{await page.getByRole('navigation',{name:'一级导航'}).waitFor();await page.setViewportSize({width:1280,height:850});await page.getByRole('region',{name:'新手教程'}).getByRole('button',{name:'跳过'}).click();await page.evaluate(()=>{window.confirm=()=>true;});expect(await page.evaluate(()=>window.career.developmentDiagnostics)).toBe(false);
 const ids=await page.evaluate(async()=>{const call=async(i:any):Promise<any>=>window.career.request('opportunity',i);const ids:string[]=[];for(let n=0;n<6;n++){const c=await call({operation:'company.create',commandId:crypto.randomUUID(),name:'Aura TEST Company '+(n+1)}),o=await call({operation:'create',commandId:crypto.randomUUID(),companyId:c.company.id,role:'TEST Analyst '+(n+1)});ids.push(o.opportunity.id);if(n===1)await call({operation:'record-stage',commandId:crypto.randomUUID(),id:o.opportunity.id,expectedRevision:1,stage:'submitted',reason:'TEST actual submission',businessTime:{kind:'unknown'}});}return ids;});
 const moduleSeeds=await page.evaluate(async()=>{
  const profile:any=await window.career.request('profile',{operation:'profile.save',commandId:crypto.randomUUID(),expectedRevision:0,name:'TEST Candidate',contact:'candidate@example.test',links:[]});
  const wiki:any=await window.career.request('wiki',{operation:'create',commandId:crypto.randomUUID(),title:'TEST 可复用的职业经验',body:'TEST DATA: record what worked and keep its source.',scope:'personal',nature:'observation',sources:[]});
  const employment:any=await window.career.request('employment',{operation:'create',commandId:crypto.randomUUID(),company:'TEST Workplace',role:'TEST Analyst',goal:'TEST long-term work',started:true,start:{kind:'unknown'},plannedEnd:{kind:'unknown'}});
  const project:any=await window.career.request('project',{operation:'create',commandId:crypto.randomUUID(),name:'TEST Feedback Analysis',description:'TEST DATA: a fictional project summary.',tags:[],employmentId:employment.employment.id,occurredAt:{kind:'unknown'}});
  return {wiki:wiki.kind,employment:employment.kind,project:project.kind,profile:profile.status};
 });expect(moduleSeeds).toEqual({wiki:'knowledge',employment:'employment',project:'project',profile:'profile'});await page.reload();await page.getByRole('navigation',{name:'一级导航'}).waitFor();await page.evaluate(()=>{window.confirm=()=>true;});
 const nav=page.getByRole('navigation',{name:'一级导航'});const brand=nav.getByRole('img',{name:'Career 豹头与字标',exact:true});expect(await nav.getByRole('link').count()).toBe(4);const url=page.url();await brand.click();expect(page.url()).toBe(url);expect(await nav.innerText()).not.toMatch(/首页|我的账号/);expect(await nav.locator('img,image,canvas,video').count()).toBe(0);
 await nav.getByRole('link',{name:'机会',exact:true}).click();const core=page.getByRole('region',{name:'机会',exact:true});await core.getByRole('button',{name:'机会更多',exact:true}).click();await core.getByRole('button',{name:'刷新',exact:true}).click();const table=core.getByRole('table',{name:'机会管线'});await expect.poll(()=>table.getByRole('row').count()).toBe(7);expect(await table.getByRole('columnheader').allTextContents()).toEqual(['公司 / 岗位','阶段','下一步','提醒日期']);expect(await nav.getByRole('link',{name:'机会',exact:true}).evaluate(el=>({width:el.getBoundingClientRect().width,height:el.getBoundingClientRect().height}))).toEqual({width:48,height:48});expect(await table.getByRole('row').nth(1).evaluate(el=>el.getBoundingClientRect().height)).toBe(46);expect(await table.getByRole('cell').first().evaluate(el=>getComputedStyle(el).padding)).toBe('8px 18px');await core.getByRole('button',{name:/^已投递/}).click();expect(await table.getByRole('row').count()).toBe(2);await core.getByRole('button',{name:/^总表/}).click();await core.getByRole('button',{name:'Aura TEST Company 1 · TEST Analyst 1',exact:true}).click();const sections=page.getByRole('navigation',{name:'机会分区'});await sections.waitFor();expect(await sections.getByRole('button').count()).toBe(6);expect(await core.locator('.detail-grid .reading').getByRole('heading',{name:'岗位重点',exact:true}).isVisible()).toBe(true);expect(await core.locator('.detail-grid .detail-aside').getByRole('heading',{name:'当前进度',exact:true}).isVisible()).toBe(true);expect(await sections.locator('.tabs button[aria-selected=true]').innerText()).toBe('概览');await page.screenshot({path:path.join(base,'detail-1280.png')});await sections.getByRole('button',{name:'简历',exact:true}).click();const editor=page.getByRole('textbox',{name:'简历正文',exact:true});expect(await page.locator('.paper-header h2').innerText()).toBe('TEST Candidate');expect(await page.getByLabel('基础资料姓名').isVisible()).toBe(false);await editor.locator('p').first().click();await page.keyboard.type('Aura TEST Resume session');await page.getByRole('button',{name:'正文居中',exact:true}).click();await page.getByTestId('resume-save-state').filter({hasText:'已保存'}).waitFor();await editor.locator('p').first().click();await page.keyboard.press('ControlOrMeta+a');const selection=await page.evaluate(()=>window.getSelection()?.toString());await page.screenshot({path:path.join(base,'resume-1280.png')});
 async function open(name:string){await page.getByRole('button',{name:'连接与辅助菜单'}).click();await page.getByRole('menuitem',{name,exact:true}).click();}
 for(const name of ['设置','帮助','更新日志']){await open(name);const panel=page.getByRole('dialog',{name:name==='帮助'?'帮助':name,exact:true});await panel.waitFor();if(name==='设置'){expect(await panel.getByText('Career 版本',{exact:true}).isVisible()).toBe(true);expect(await panel.innerText()).toContain('0.0.0');}await panel.getByRole('button',{name:'返回原任务'}).click();expect(await page.evaluate(()=>window.getSelection()?.toString())).toBe(selection);expect(await editor.textContent()).toContain('Aura TEST Resume session');expect(await editor.locator('p').first().evaluate(el=>getComputedStyle(el).textAlign)).toBe('center');}
 await open('反馈');expect(await page.getByRole('dialog',{name:'Career 反馈'}).evaluate(el=>el.classList.contains('sheet')&&el.classList.contains('small-sheet'))).toBe(true);await page.getByLabel('反馈内容').fill('A6 TEST feedback draft');await page.getByRole('button',{name:'返回原任务（保留反馈草稿）'}).click();await open('反馈');expect(await page.getByLabel('反馈内容').inputValue()).toBe('A6 TEST feedback draft');await page.getByLabel('反馈内容').fill('');await page.getByRole('button',{name:'返回原任务（保留反馈草稿）'}).click();await page.getByRole('button',{name:'撤销',exact:true}).click();await page.getByRole('button',{name:'重做',exact:true}).click();expect(await editor.textContent()).toContain('Aura TEST Resume session');
 for(const [label,text]of [['Wiki','TEST 可复用的职业经验'],['项目','TEST Feedback Analysis'],['任职','TEST Workplace · TEST Analyst']]){await nav.getByRole('link',{name:label,exact:true}).click();await page.locator('.aura-module .recent-row').filter({hasText:text}).waitFor();expect(await page.locator('.aura-module:visible .page-header').count()).toBe(1);await page.screenshot({path:path.join(base,'module-'+label+'.png')});}
 await nav.getByRole('link',{name:'机会',exact:true}).click();for(const width of [600,1280]){await page.setViewportSize({width,height:850});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);for(const label of ['Wiki','机会','项目','任职'])expect(await nav.getByRole('link',{name:label,exact:true}).isVisible()).toBe(true);await page.screenshot({path:path.join(base,'pipeline-'+width+'.png')});}
 await page.emulateMedia({reducedMotion:'reduce'});await brand.hover();expect(await brand.locator('.career-brand-head').evaluate(el=>getComputedStyle(el).transform)).toBe('none');expect(await brand.locator('.career-brand-eye').evaluate(el=>getComputedStyle(el).opacity)).toBe('0');await page.emulateMedia({reducedMotion:'no-preference'});await table.hover();await brand.hover();await expect.poll(()=>brand.locator('.career-brand-head').evaluate(el=>getComputedStyle(el).transform)).not.toBe('none');await expect.poll(()=>brand.locator('.career-brand-head').evaluate(el=>getComputedStyle(el).transform),{timeout:5000}).toBe('none');expect(errors).toEqual([]);
 await writeFile(path.join(base,'RESULT.json'),JSON.stringify({profile,ids,normal:true,moduleRows:true,detailGrid:true,resumePaper:true,feedbackSheet:true,widths:[600,1280],fourLabels:true,noHome:true,pipeline:true,selection:true,alignment:true,feedbackDraft:true,motion:true,reducedMotion:true,privateDataChanged:false,externalRequests:0,pageErrors:errors},null,2));
 }catch(error){await writeFile(path.join(base,'FAILURE.txt'),String(error)+'\n'+await page.locator('body').innerText());throw error;}finally{page.on('dialog',d=>void d.dismiss().catch(()=>{}));await f.close();}
},110000);
