import {it,expect} from 'vitest';
import {_electron,type Page} from 'playwright';
import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {Result as EmploymentResult} from '../../packages/contracts/employment/schema';
import {Result as ProjectResult} from '../../packages/contracts/project/schema';
import {Result as ResumeResult} from '../../packages/contracts/resume/schema';
import {Result as OpportunityResult} from '../../packages/contracts/opportunity/schema';
import {Result as WikiResult} from '../../packages/contracts/wiki/schema';
it('normal desktop runs all six manual owner journeys, real PDF, protected quit, navigation and durable restart',async()=>{
 const root=await mkdtemp(path.join(tmpdir(),'career-g2-desktop-'));
 const fixture=path.join(root,'Evidence.txt');await writeFile(fixture,'Actual independent Raw source.');
 const packaged=process.env.CAREER_PACKAGED==='1';
 const options={executablePath:packaged?path.resolve(process.env.CAREER_PACKAGED_EXECUTABLE??'out/CareerNext-darwin-arm64/CareerNext.app/Contents/MacOS/CareerNext'):undefined,args:packaged?['--career-desktop-ui',`--user-data-dir=${root}/profile`]:['.','--career-desktop-ui',`--user-data-dir=${root}/profile`],timeout:30000};
 let application=await _electron.launch(options);
 try{
  let page=await application.firstWindow();page.on('dialog',()=>{});page.setDefaultTimeout(10000);const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  await page.getByRole('navigation',{name:'一级导航'}).waitFor();
  expect(await page.getByRole('navigation').getByRole('link').allTextContents()).toEqual(['◇Wiki','◉机会','▤项目','▥任职']);
  const nav=async(name:string)=>page.getByRole('navigation').getByRole('link',{name,exact:false}).click();
  await application.evaluate(({dialog},fixture)=>{dialog.showOpenDialog=(async()=>({canceled:false,filePaths:[fixture]})) as typeof dialog.showOpenDialog;},fixture);
  await page.getByRole('button',{name:'选择本地文本材料'}).click();await page.getByRole('button',{name:'确认保存原件'}).click();await expect.poll(()=>page.locator('#saved-text').textContent()).toContain('Actual independent Raw');
  const wiki=page.getByRole('region',{name:'Wiki 知识'});
  await wiki.getByLabel('知识标题').fill('Traceable knowledge');await wiki.getByLabel('知识正文').fill('My own knowledge, distinct from the original.');
  await wiki.getByRole('button',{name:'刷新原件列表'}).click();await expect.poll(()=>wiki.getByLabel('选择原件').locator('option').count()).toBe(2);
  await wiki.getByLabel('选择原件').selectOption({label:'Evidence.txt'});await wiki.getByLabel('来源用途').fill('Original evidence');await wiki.getByRole('button',{name:'加入来源引用'}).click();await wiki.getByRole('button',{name:'保存知识',exact:true}).click();
  await wiki.getByRole('button',{name:'保存知识修改'}).waitFor();await wiki.getByRole('button',{name:'读取原件'}).click();await wiki.getByRole('complementary',{name:'来源原文'}).getByText('Actual independent Raw source.',{exact:true}).waitFor();
  const knowledge=WikiResult.parse(await page.evaluate(()=>window.career.request('wiki',{operation:'list'})));expect(knowledge.kind).toBe('list');if(knowledge.kind!=='list')throw Error('Wiki list');expect(knowledge.items).toHaveLength(1);expect(knowledge.items[0].sources[0].ref.owner).toBe('materials');
  await nav('任职');const e=page.getByRole('region',{name:'任职',exact:true});
  const createEmployment=async(company:string)=>{await e.getByRole('button',{name:'新增任职',exact:true}).click();const form=e.getByRole('button',{name:'创建任职',exact:true}).locator('xpath=ancestor::form');await form.getByLabel('公司',{exact:true}).fill(company);await form.getByLabel('岗位',{exact:true}).fill('Engineer');await form.getByLabel('当前目标',{exact:true}).fill('Actual work');await form.getByLabel('我确认已经真实开始这段任职').check();await form.getByRole('button',{name:'创建任职',exact:true}).click();await e.getByRole('button',{name:'保存任职',exact:true}).waitFor();await e.getByRole('heading',{name:company+' · Engineer',exact:true}).waitFor();};
  await createEmployment('Workplace A');
  const person=e.getByRole('heading',{name:'新增人物（同名不会合并）'}).locator('xpath=ancestor::form');await person.getByLabel('姓名',{exact:true}).fill('Colleague');await person.getByLabel('任职角色',{exact:true}).fill('Department reviewer');await person.getByRole('button',{name:'保存人物',exact:true}).click();await expect.poll(()=>e.getByRole('heading',{name:'维护人物',exact:true}).count()).toBe(1);
  const employmentEdit=e.getByRole('button',{name:'保存任职',exact:true}).locator('xpath=ancestor::form');await employmentEdit.getByLabel('当前目标',{exact:true}).fill('Revised actual work');await employmentEdit.getByLabel('变化说明',{exact:true}).fill('Corrected goal');await employmentEdit.getByRole('button',{name:'保存任职',exact:true}).click();await expect.poll(()=>employmentEdit.getByRole('status').textContent()).toContain('已保存');
  await createEmployment('Workplace B');
  const es=EmploymentResult.parse(await page.evaluate(()=>window.career.request('employment',{operation:'list'})));if(es.kind!=='list')throw Error('employment list');expect(es.employments).toHaveLength(2);const a=es.employments.find(item=>item.company==='Workplace A')!,b=es.employments.find(item=>item.company==='Workplace B')!;
  await nav('项目');const p=page.getByRole('region',{name:'项目',exact:true});await p.getByRole('button',{name:'新增项目',exact:true}).click();const projectCreate=p.getByRole('button',{name:'创建项目',exact:true}).locator('xpath=ancestor::form');await projectCreate.getByLabel('项目名称',{exact:true}).fill('Independent project');await projectCreate.getByLabel('描述',{exact:true}).fill('Project-owned work');await projectCreate.getByLabel('关联任职',{exact:true}).selectOption(a.id);await projectCreate.getByRole('button',{name:'创建项目',exact:true}).click();await p.getByRole('heading',{name:'Independent project',exact:true}).waitFor();
  await p.getByLabel('变化说明',{exact:true}).fill('Actual reassociation');await p.getByLabel('新的关联任职',{exact:true}).selectOption(b.id);await p.getByRole('button',{name:'确认变更任职关联'}).click();await expect.poll(()=>p.getByText(/当前归属：Workplace B/).textContent()).toContain('Workplace B');await p.getByRole('button',{name:'读取项目与协作历史'}).click();await p.getByText('Actual reassociation',{exact:false}).waitFor();
  const ps=ProjectResult.parse(await page.evaluate(()=>window.career.request('project',{operation:'list'})));if(ps.kind!=='list')throw Error('project list');const projectId=ps.projects[0].id;expect(ps.projects[0].employmentId).toBe(b.id);
  await nav('机会');const o=page.getByRole('region',{name:'机会',exact:true});await o.getByLabel('公司名称',{exact:true}).fill('Hiring company');await o.getByRole('button',{name:'建立新公司'}).click();await o.getByRole('button',{name:'保存公司改名'}).waitFor();await o.getByLabel('明确选择公司').selectOption({index:1});await o.getByLabel('岗位名称').fill('Target role');await o.getByRole('button',{name:'创建机会',exact:true}).click();await o.getByRole('button',{name:'编辑本机会简历'}).waitFor();
  await o.getByLabel('变化说明',{exact:true}).fill('Actual interview without submission');await o.getByLabel('现实已达到阶段').selectOption('interview');await o.getByRole('button',{name:'登记真实阶段事件'}).click();await expect.poll(()=>o.getByText(/实际达到阶段：面试/).textContent()).toContain('面试');
  await o.getByLabel('变化说明',{exact:true}).fill('User withdraws');await o.getByRole('button',{name:'确认用户退出'}).click();await o.getByRole('button',{name:'纠正当前误结束'}).waitFor();await o.getByLabel('变化说明',{exact:true}).fill('Incorrect ending');await o.getByRole('button',{name:'纠正当前误结束'}).click();await expect.poll(()=>o.getByText(/实际达到阶段：/).textContent()).toContain('进行中');
  await o.getByRole('button',{name:'编辑本机会简历'}).click();const editor=page.getByRole('textbox',{name:'简历正文'});await editor.waitFor();
  await page.getByLabel('基础资料姓名').filter({visible:true}).fill('G2 Candidate');await page.getByLabel('基础资料联系方式').filter({visible:true}).fill('candidate@example.test');await page.getByRole('button',{name:'保存基础资料'}).click();await page.getByText('基础资料已保存，所有当前简历使用最新身份').filter({visible:true}).waitFor();
  await editor.click();await page.keyboard.press('ControlOrMeta+End');await page.keyboard.type('Continuous real keyboard editing.');await expect.poll(()=>page.getByTestId('resume-save-state').textContent()).toBe('已保存');
  const resumeUrl=page.url();await nav('Wiki');await nav('机会');await o.getByRole('button',{name:'编辑本机会简历'}).click();expect(page.url()).toBe(resumeUrl);expect(await editor.textContent()).toContain('Continuous real keyboard editing.');
  await page.getByLabel('简历字号').selectOption('13');await expect.poll(()=>page.getByTestId('resume-save-state').textContent()).toBe('已保存');expect(await page.locator('.resume-paper').evaluate(element=>getComputedStyle(element).fontSize)).toBe('17.3333px');
  await page.getByRole('button',{name:'命名版本（⌘S）'}).click();await page.getByLabel('版本名称').fill('Actual immutable PDF');await page.getByRole('button',{name:'保存版本及 PDF'}).click();await expect.poll(async()=>{const alerts=await page.getByRole('alert').allTextContents();if(alerts.some(text=>text.includes('版本生成失败')))throw Error('PDF diagnostic: '+alerts.join(' | '));return page.getByText('命名版本及 PDF 已冻结保存',{exact:true}).isVisible();},{timeout:45000}).toBe(true);
  await page.getByRole('button',{name:'版本历史',exact:true}).click();await page.getByRole('button',{name:'Actual immutable PDF',exact:true}).click();await page.getByRole('heading',{name:'Actual immutable PDF（冻结材料）'}).waitFor();
  const opportunityId=new URL(resumeUrl).hash.split('/')[2];
  const opened=ResumeResult.parse(await page.evaluate(id=>window.career.request('resume',{operation:'resume.open',commandId:crypto.randomUUID(),opportunityId:id}),opportunityId));if(opened.status!=='document')throw Error('resume read');
  const versions=ResumeResult.parse(await page.evaluate(id=>window.career.request('resume',{operation:'resume.versions',resumeId:id}),opened.document.id));if(versions.status!=='versions')throw Error('versions');expect(versions.versions).toHaveLength(1);const frozen=versions.versions[0];
  const bytes=await readFile(path.join(root,'profile/workspaces/local/blobs',frozen.pdf.blobId));expect(bytes.subarray(0,5).toString()).toBe('%PDF-');expect(bytes.length).toBe(frozen.pdf.size);
  const {getDocument}=await import('pdfjs-dist/legacy/build/pdf.mjs');const loading=getDocument({data:new Uint8Array(bytes),useSystemFonts:true});const pdf=await loading.promise;let text='';for(let n=1;n<=pdf.numPages;n++)text+=(await (await pdf.getPage(n)).getTextContent()).items.map(item=>'str'in item?item.str:'').join(' ');await loading.destroy();expect(text.normalize('NFKC').replace(/\s/g,'')).toContain('个人简介');expect(frozen.snapshot.fontVersion).toMatch(/Arial=[a-f0-9]{12}/);expect(frozen.snapshot.engineVersion).toContain('electron-44.5.1');expect(text).toContain('G2 Candidate');expect(text).toContain('Continuous real keyboard editing.');
  expect(await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().length)).toBe(1);
  await editor.click();await page.keyboard.press('ControlOrMeta+End');await page.keyboard.type(' Later current-only change.');await expect.poll(()=>page.getByTestId('resume-save-state').textContent()).toBe('已保存');await Promise.all([page.waitForEvent('dialog').then(dialog=>dialog.accept()),page.getByRole('button',{name:'恢复此版本正文'}).click()]);await expect.poll(()=>editor.textContent()).not.toContain('Later current-only change.');await expect.poll(()=>page.getByTestId('resume-save-state').textContent()).toBe('已保存');
  // Explicit object routes may point to a different owner than the retained Opportunity view.
  const companies=OpportunityResult.parse(await page.evaluate(()=>window.career.request('opportunity',{operation:'company.list'})));if(companies.kind!=='companies')throw Error('company list');
  const bOpportunity=OpportunityResult.parse(await page.evaluate(companyId=>window.career.request('opportunity',{operation:'create',commandId:crypto.randomUUID(),companyId,role:'Alternative owner'}),companies.items[0].id));if(bOpportunity.kind!=='opportunity')throw Error('second opportunity');const bId=bOpportunity.opportunity.id;
  await page.evaluate(id=>{location.hash='#/opportunity/'+id+'/resume';},bId);await page.getByRole('heading',{name:'Hiring company · Alternative owner 的简历'}).waitFor();await page.getByRole('button',{name:'返回所属机会'}).filter({visible:true}).click();await o.getByRole('heading',{name:'Hiring company · Alternative owner',exact:true}).waitFor();
  await o.getByRole('button',{name:'Hiring company · Target role',exact:true}).click();await o.getByRole('button',{name:'编辑本机会简历'}).click();await editor.waitFor();
  // Cancel protected quit keeps the true live input; discard is chosen only by this external test driver.
  await page.getByLabel('基础资料姓名').filter({visible:true}).fill('Unsaved identity');
  await application.evaluate(({app,dialog})=>{dialog.showMessageBoxSync=(()=>0) as typeof dialog.showMessageBoxSync;app.quit();});await expect.poll(()=>page.getByLabel('基础资料姓名').filter({visible:true}).inputValue()).toBe('Unsaved identity');
  await page.getByRole('button',{name:'保存基础资料'}).click();await page.getByText('基础资料已保存，所有当前简历使用最新身份').filter({visible:true}).waitFor();
  expect(errors).toEqual([]);await application.close();application=await _electron.launch(options);page=await application.firstWindow();page.on('dialog',()=>{});await page.getByRole('navigation').waitFor();
  await page.getByRole('navigation').getByRole('link',{name:'机会'}).click();await page.getByRole('button',{name:'Hiring company · Target role',exact:true}).click();await page.getByRole('button',{name:'编辑本机会简历'}).click();await expect.poll(()=>page.getByRole('textbox',{name:'简历正文'}).textContent()).toContain('Continuous real keyboard editing.');expect(await page.getByLabel('基础资料姓名').filter({visible:true}).inputValue()).toBe('Unsaved identity');
  expect(ResumeResult.parse(await page.evaluate(id=>window.career.request('resume',{operation:'resume.versions',resumeId:id}),opened.document.id))).toEqual(versions);
  expect(ProjectResult.parse(await page.evaluate(id=>window.career.request('project',{operation:'read',id}),projectId))).toMatchObject({kind:'project',project:{employmentId:b.id}});
  await writeFile(path.join(tmpdir(),`career-next-g2-${packaged?'packaged':'dev'}.json`),JSON.stringify({mode:packaged?'packaged':'dev',sixJourneys:true,realPdfSelectableEnglish:true,immutableVersion:true,durableRestart:true,protectedQuit:true,ime:'pending-real-human-system-input'},null,2));
 }catch(error){await pageDiagnostic(application,root).catch(()=>undefined);throw error;}finally{await application.evaluate(({dialog})=>{dialog.showMessageBoxSync=(()=>1) as typeof dialog.showMessageBoxSync;}).catch(()=>undefined);await application.close();await rm(root,{recursive:true,force:true});}
},150000);

async function pageDiagnostic(application:Awaited<ReturnType<typeof _electron.launch>>,root:string){
 const page=await application.firstWindow();await writeFile('/tmp/career-g2-desktop-diagnostic.txt',await page.locator('body').innerText());await page.screenshot({path:'/tmp/career-g2-desktop-diagnostic.png'});
 const {default:Database}=await import('better-sqlite3');const db=new Database(path.join(root,'profile/workspaces/local/career.sqlite'),{readonly:true});try{await writeFile('/tmp/career-g2-pdf-diagnostic.json',JSON.stringify({jobs:db.prepare('SELECT command_id FROM resume_render_jobs').all(),receipts:db.prepare('SELECT * FROM platform_commands WHERE owner=\'resume\'').all(),ledger:db.prepare('SELECT * FROM platform_artifact_receipts').all()}));}finally{db.close();}
}
