import {it,expect} from 'vitest';
import {_electron} from 'playwright';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {Result as OpportunityResult} from '../../packages/contracts/opportunity/schema';
import {Result as ResearchResult} from '../../packages/contracts/opportunity/research/schema';
import {Result as InterviewResult} from '../../packages/contracts/opportunity/interview/schema';
import {Result as OfferResult} from '../../packages/contracts/opportunity/offer/schema';
import {Result as EmploymentResult} from '../../packages/contracts/employment/schema';

it('normal arm64 application connects three owners, real protected Raw, public core, Wiki readonly reference and durable restart',async()=>{
 const root=await mkdtemp(path.join(tmpdir(),'career-g3-desktop-')),file=path.join(root,'Formal Offer.txt');await writeFile(file,'Guaranteed cash 30k. Actual protected original.');
 const packaged=process.env.CAREER_PACKAGED==='1';
 const options={executablePath:packaged?path.resolve('out/CareerNext-darwin-arm64/CareerNext.app/Contents/MacOS/CareerNext'):undefined,args:packaged?[`--user-data-dir=${root}/profile`]:['.',`--user-data-dir=${root}/profile`],timeout:30000};
 let app=await _electron.launch(options);
 try{
  let page=await app.firstWindow();page.setDefaultTimeout(10000);const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  await page.getByRole('navigation',{name:'一级导航'}).waitFor();
  expect(await page.getByRole('navigation').getByRole('link').allTextContents()).toEqual(['◇Wiki','◉机会','▤项目','▥任职']);
  await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=(async()=>({canceled:false,filePaths:[file]})) as typeof dialog.showOpenDialog;},file);
  await page.getByRole('button',{name:'选择本地文本材料'}).click();await page.getByRole('button',{name:'确认保存原件'}).click();await expect.poll(()=>page.locator('#saved-text').textContent()).toContain('Actual protected original');
  await page.getByRole('navigation').getByRole('link',{name:'机会'}).click();const opportunity=page.getByRole('region',{name:'机会',exact:true});
  await opportunity.getByLabel('公司名称',{exact:true}).fill('G3 Company');await opportunity.getByRole('button',{name:'建立新公司'}).click();await opportunity.getByRole('button',{name:'保存公司改名'}).waitFor();
  await opportunity.getByLabel('明确选择公司').selectOption({index:1});await opportunity.getByLabel('岗位名称').fill('G3 Role');await opportunity.getByRole('button',{name:'创建机会',exact:true}).click();await opportunity.getByRole('button',{name:'打开岗位情报'}).click();
  const research=page.getByRole('region',{name:'岗位情报'});
  await research.getByLabel('研究归属').selectOption('company');await research.getByLabel('研究标题').fill('Company current research');await research.getByLabel('研究正文').fill('Company shared manual statement');await research.getByRole('button',{name:'保存研究',exact:true}).click();await research.getByRole('button',{name:'保存改写'}).waitFor();
  await research.getByLabel('研究归属').selectOption('opportunity');await research.getByLabel('研究标题').fill('Promotable item');await research.getByLabel('研究正文').fill('Opportunity-owned manual statement');await research.getByLabel('用户确认',{exact:true}).check();await research.getByRole('button',{name:'保存研究',exact:true}).click();await research.getByRole('button',{name:'保存改写'}).waitFor();
  await research.getByLabel('研究正文').fill('Corrected unique statement');await research.getByLabel('变化说明',{exact:true}).fill('Correct source understanding');await research.getByLabel('已重新判断保留来源是否适用；改写清除旧确认与核验').check();await research.getByRole('button',{name:'保存改写'}).click();await expect.poll(()=>research.getByLabel('用户确认',{exact:true}).isChecked()).toBe(false);
  await research.getByLabel('变化说明',{exact:true}).fill('Obsolete evidence');await research.getByRole('button',{name:'撤回条目',exact:true}).click();await research.getByRole('button',{name:'确认撤回条目'}).click();await research.getByRole('button',{name:'恢复条目'}).waitFor();
  await research.getByLabel('变化说明',{exact:true}).fill('Reassessed');await research.getByRole('button',{name:'恢复条目',exact:true}).click();await research.getByRole('button',{name:'确认恢复条目'}).click();await research.getByRole('button',{name:'撤回条目'}).waitFor();
  await Promise.all([page.waitForEvent('dialog').then(dialog=>dialog.accept()),research.getByRole('button',{name:'提升为公司共享研究'}).click()]);await research.getByRole('button',{name:'查看公司唯一正文'}).waitFor();
  const listed=OpportunityResult.parse(await page.evaluate(()=>window.career.request('opportunity',{operation:'list'})));if(listed.kind!=='opportunities')throw Error('list');const id=listed.items[0].id,companyId=listed.items[0].companyId;
  const privateDoc=ResearchResult.parse(await page.evaluate(id=>window.career.request('research',{operation:'read',owner:{kind:'opportunity',id}}),id));expect(privateDoc).toMatchObject({kind:'document',items:[],references:[{owner:{kind:'company',id:companyId}}]});
  await page.getByRole('navigation').getByRole('link',{name:'Wiki'}).click();const wiki=page.getByRole('region',{name:'Wiki 研究引用'});await wiki.getByRole('button',{name:'刷新研究机会'}).click();await expect.poll(()=>wiki.getByLabel('查看哪个机会的研究引用').locator('option').count()).toBe(2);await wiki.getByLabel('查看哪个机会的研究引用').selectOption(id);await wiki.getByText('Corrected unique statement',{exact:true}).waitFor();expect(await wiki.locator('textarea,[contenteditable=true]').count()).toBe(0);await wiki.getByRole('button',{name:'到所属机会编辑研究正本'}).click();await research.getByRole('button',{name:'查看公司唯一正文'}).waitFor();
  await opportunity.getByRole('button',{name:'打开面试'}).click();const interview=page.getByRole('region',{name:'面试子模块'});await interview.getByLabel('真实轮次名称').fill('Unknown-time real round');await interview.getByRole('button',{name:'确认存在真实轮次'}).click();await interview.getByRole('heading',{name:'Unknown-time real round',exact:true}).waitFor();await interview.getByText(/确认：日期未知；预约：日期未知；完成：日期未知/).waitFor();
  const transition=async(action:string,reason:string,date?:string)=>{await interview.getByLabel('面试变化说明').fill(reason);await interview.getByLabel('现实变化').selectOption(action);await interview.getByLabel('本次实际业务时间类型').selectOption(date?'date':'unknown');if(date)await interview.getByLabel('本次实际业务时间日期').fill(date);await interview.getByRole('button',{name:'记录本轮真实变化'}).click();await expect.poll(()=>interview.getByRole('status').textContent()).toContain('已保存');};
  await transition('schedule','Actual scheduling','2026-10-10');await transition('schedule','Actual rescheduling','2026-10-12');await transition('temporarily_cancel','Temporarily cancelled');await interview.getByText('临时取消，待重约',{exact:true}).filter({visible:true}).first().waitFor();await transition('schedule','Rebooked','2026-10-15');await transition('complete','Completed, date unknown');
  await interview.getByLabel('当前准备').fill('Manual preparation');await interview.getByRole('button',{name:'保存当前准备'}).click();await expect.poll(()=>interview.getByRole('status').textContent()).toContain('已保存');
  await interview.getByLabel('真实轮次名称').fill('Late-recorded older round');await interview.getByLabel('现实确认时间类型').selectOption('date');await interview.getByLabel('现实确认时间日期').fill('2026-09-01');await interview.getByRole('button',{name:'确认存在真实轮次'}).click();await interview.getByRole('heading',{name:'Late-recorded older round',exact:true}).waitFor();await transition('complete','Historical completed fact');
  const rounds=InterviewResult.parse(await page.evaluate(id=>window.career.request('interview',{operation:'interview.list',opportunityId:id}),id));if(rounds.kind!=='sessions')throw Error('rounds');expect(rounds.items).toHaveLength(2);expect(rounds.items.every(round=>round.completionTime.kind==='unknown')).toBe(true);
  // A different opportunity has no synthetic predecessor but may have a real Offer.
  const direct=OpportunityResult.parse(await page.evaluate(companyId=>window.career.request('opportunity',{operation:'create',commandId:crypto.randomUUID(),companyId,role:'Direct Offer Role'}),companyId));if(direct.kind!=='opportunity')throw Error('direct');const offerId=direct.opportunity.id;
  await opportunity.getByRole('button',{name:'重新读取机会列表'}).click();await opportunity.getByRole('button',{name:'G3 Company · Direct Offer Role',exact:true}).click();await opportunity.getByRole('button',{name:'打开 Offer'}).click();const offer=page.getByRole('region',{name:'Offer',exact:true});
  await offer.getByLabel('保证现金',{exact:true}).fill('30k');await offer.getByLabel('原件状态').selectOption('retained');await expect.poll(()=>offer.getByLabel('明确选择既有原件').locator('option').count()).toBe(2);await offer.getByLabel('明确选择既有原件').selectOption({index:1});await offer.getByLabel('变化说明',{exact:true}).fill('Actual direct Offer');await offer.getByRole('button',{name:'确认现实收到 Offer'}).click();await offer.getByRole('button',{name:'接受当前有效条件'}).waitFor();
  const readOffer=()=>page.evaluate(id=>window.career.request('offer',{operation:'offer.read',opportunityId:id}),offerId).then(value=>OfferResult.parse(value));
  expect(await readOffer()).toMatchObject({kind:'offer',opportunity:{phase:'offer',result:'active',stageDates:{submitted:{kind:'unknown'},interview:{kind:'unknown'}}},offer:{original:{kind:'retained',name:'Formal Offer.txt'}}});
  await offer.getByLabel('变化说明',{exact:true}).fill('Explicit real acceptance');await offer.getByRole('button',{name:'接受当前有效条件'}).click();await expect.poll(async()=>JSON.stringify(await readOffer())).toContain('"result":"accepted"');
  await offer.getByLabel('保证现金',{exact:true}).fill('25k');await offer.getByLabel('条件保存含义').selectOption('replacement');await offer.getByLabel('变化说明',{exact:true}).fill('Formal later replacement');await offer.getByRole('button',{name:'确认正式新条件替代'}).click();await expect.poll(async()=>JSON.stringify(await readOffer())).toContain('"value":"25k"');expect(await readOffer()).toMatchObject({kind:'offer',opportunity:{result:'active'}});
  await offer.getByRole('button',{name:'查看接受依据与历史'}).click();await offer.getByRole('complementary',{name:'Offer 接受依据与历史'}).getByText(/保证现金：30k/).first().waitFor();
  const history=OfferResult.parse(await page.evaluate(id=>window.career.request('offer',{operation:'offer.history',opportunityId:id}),offerId));expect(history).toMatchObject({kind:'history',acceptances:[{conditions:{guaranteedCash:{kind:'known',value:'30k'}},original:{kind:'retained'}}]});
  expect(EmploymentResult.parse(await page.evaluate(()=>window.career.request('employment',{operation:'list'})))).toMatchObject({kind:'list',employments:[]});expect(errors).toEqual([]);
  await app.close();app=await _electron.launch(options);page=await app.firstWindow();await page.getByRole('navigation').waitFor();expect(await readOffer()).toMatchObject({kind:'offer',offer:{conditions:{guaranteedCash:{value:'25k'}}}});expect(OfferResult.parse(await page.evaluate(id=>window.career.request('offer',{operation:'offer.history',opportunityId:id}),offerId))).toEqual(history);
  await writeFile(path.join(tmpdir(),`career-next-g3-${packaged?'packaged':'dev'}.json`),JSON.stringify({mode:packaged?'packaged':'dev',researchPromotionUniqueOwner:true,wikiReadOnly:true,unknownDates:true,rescheduleRebookComplete:true,directOffer:true,realProtectedOriginal:true,immutableAcceptance:true,noSyntheticSubmissionOrEmployment:true,durableRestart:true,errors},null,2));
 }catch(error){const page=await app.firstWindow();await writeFile('/tmp/career-g3-desktop-diagnostic.txt',await page.locator('body').innerText());await page.screenshot({path:'/tmp/career-g3-desktop-diagnostic.png'});throw error;}finally{await app.evaluate(({dialog})=>{dialog.showMessageBoxSync=(()=>1) as typeof dialog.showMessageBoxSync;}).catch(()=>undefined);await app.close();await rm(root,{recursive:true,force:true});}
},150000);
