import {it,expect} from 'vitest';
import {_electron} from 'playwright';
import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {Result as ResumeResult} from '../../packages/contracts/resume/schema';
import {Result as OpportunityResult} from '../../packages/contracts/opportunity/schema';
import {Result as SubmissionResult} from '../../packages/contracts/opportunity/submission/schema';
import {Result as DataResult} from '../../packages/contracts/application/schema';
import {Result as WikiResult} from '../../packages/contracts/wiki/schema';
it('normal application joins exported A/current B, first/resend, actual raw AI review, backup, isolated restore and user-confirmed purge',async()=>{
 const root=await mkdtemp(path.join(tmpdir(),'career-g4-desktop-')),fixture=path.join(root,'G4 Evidence.txt');await writeFile(fixture,'G4 fake fixture: actual immutable evidence.');
 const packaged=process.env.CAREER_PACKAGED==='1';const options={executablePath:packaged?path.resolve(process.env.CAREER_PACKAGED_EXECUTABLE??'out/CareerNext-darwin-arm64/CareerNext.app/Contents/MacOS/CareerNext'):undefined,args:packaged?['--career-desktop-ui',`--user-data-dir=${root}/profile`]:['.','--career-desktop-ui',`--user-data-dir=${root}/profile`],timeout:30000};let app=await _electron.launch(options);
 try{let page=await app.firstWindow();page.on('dialog',()=>{});page.setDefaultTimeout(15000);const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await page.getByRole('navigation',{name:'一级导航'}).waitFor();
 expect(await page.getByRole('navigation').getByRole('link').allTextContents()).toEqual(['◇Wiki','◉机会','▤项目','▥任职']);
 await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=(async()=>({canceled:false,filePaths:[file]})) as typeof dialog.showOpenDialog;},fixture);
 await page.getByRole('button',{name:'选择本地文本材料'}).click();await page.getByRole('button',{name:'确认保存原件'}).click();await expect.poll(()=>page.locator('#saved-text').textContent()).toContain('actual immutable evidence');
 await page.getByRole('navigation').getByRole('link',{name:'机会'}).click();const opportunity=page.getByRole('region',{name:'机会',exact:true});await opportunity.getByLabel('公司名称',{exact:true}).fill('G4 Company');await opportunity.getByRole('button',{name:'建立新公司'}).click();await opportunity.getByRole('button',{name:'保存公司改名'}).waitFor();await opportunity.getByLabel('明确选择公司').selectOption({index:1});await opportunity.getByLabel('岗位名称').fill('G4 Role');await opportunity.getByRole('button',{name:'创建机会',exact:true}).click();await opportunity.getByRole('button',{name:'编辑本机会简历'}).click();
 const editor=page.getByRole('textbox',{name:'简历正文'});await editor.waitFor();await page.getByLabel('基础资料姓名').filter({visible:true}).fill('G4 Candidate A');await page.getByRole('button',{name:'保存基础资料'}).click();await page.getByText('基础资料已保存，所有当前简历使用最新身份').filter({visible:true}).waitFor();await editor.click();await page.keyboard.press('ControlOrMeta+End');await page.keyboard.type('Frozen content A.');await expect.poll(()=>page.getByTestId('resume-save-state').textContent()).toBe('已保存');
 await page.getByRole('button',{name:'导出 PDF（无需命名）'}).click();await page.getByText('未命名导出快照及 PDF 已冻结，可作为实际发送候选',{exact:true}).waitFor({timeout:45000});
 const listed=OpportunityResult.parse(await page.evaluate(()=>window.career.request('opportunity',{operation:'list'})));if(listed.kind!=='opportunities')throw Error('opportunity');const id=listed.items[0].id;
 const candidates=ResumeResult.parse(await page.evaluate(id=>window.career.request('resume',{operation:'resume.candidates',opportunityId:id}),id));if(candidates.status!=='versions')throw Error('versions');expect(candidates.versions).toHaveLength(1);const frozen=candidates.versions[0],pdfBefore=await readFile(path.join(root,'profile/workspaces/local/blobs',frozen.pdf.blobId));
 await editor.click();await page.keyboard.press('ControlOrMeta+End');await page.keyboard.type(' Current B only.');await expect.poll(()=>page.getByTestId('resume-save-state').textContent()).toBe('已保存');await page.getByLabel('基础资料姓名').filter({visible:true}).fill('G4 Candidate B');await page.getByRole('button',{name:'保存基础资料'}).click();await page.getByText('基础资料已保存，所有当前简历使用最新身份').filter({visible:true}).waitFor();
 await page.getByRole('button',{name:'返回所属机会'}).filter({visible:true}).click();await opportunity.getByRole('button',{name:'打开首次投递'}).click();const submission=page.getByRole('region',{name:'首次投递',exact:true});await submission.getByLabel('本次实际简历状态').selectOption('retained');await expect.poll(()=>submission.getByLabel('选择当时真实发送材料').locator('option').count()).toBe(2);await submission.getByLabel('选择当时真实发送材料').selectOption(`resume:${frozen.id}`);await submission.getByLabel('Greeting 实际状态').selectOption('empty');await submission.getByLabel('记录或纠错说明').fill('Real first sending of frozen A');await submission.getByRole('button',{name:'确认真实首次投递'}).click();await expect.poll(()=>submission.getByRole('status').textContent()).toContain('已保存真实首次投递');
 const first=SubmissionResult.parse(await page.evaluate(id=>window.career.request('submission',{operation:'submission.read',opportunityId:id}),id));expect(first).toMatchObject({kind:'submission',submission:{resume:{kind:'retained',snapshot:{profile:{name:'G4 Candidate A'}}},greeting:{kind:'empty'}}});if(first.kind!=='submission'||first.submission.resume.kind!=='retained')throw Error('submission');expect(JSON.stringify(first.submission.resume)).not.toContain('Current B only');expect(await readFile(path.join(root,'profile/workspaces/local/blobs',frozen.pdf.blobId))).toEqual(pdfBefore);
 await opportunity.getByRole('button',{name:'打开沟通'}).click();const communication=page.getByRole('region',{name:'沟通记录',exact:true});await communication.getByLabel('沟通用途').selectOption('resend');await communication.getByLabel('沟通正文').fill('Actual resend; mentioning Interview and Offer creates no rounds.');await communication.getByLabel('本次实际简历状态').selectOption('retained');await communication.getByRole('button',{name:'选择外部实际发送文件'}).click();await communication.getByLabel('记录或纠错说明').fill('Actual later file');await communication.getByRole('button',{name:'确认再次发送材料'}).click();await communication.getByText('Actual resend; mentioning Interview and Offer creates no rounds.',{exact:true}).waitFor();expect(await page.evaluate(id=>window.career.request('submission',{operation:'submission.read',opportunityId:id}),id)).toEqual(first);
 await page.getByRole('navigation').getByRole('link',{name:'Wiki'}).click();const wikiEntry=page.getByRole('region',{name:'Wiki 知识'});await wikiEntry.getByLabel('知识标题',{exact:true}).fill('G4 private opportunity knowledge');await wikiEntry.getByLabel('知识正文',{exact:true}).fill('Private opportunity fixture only');await wikiEntry.getByRole('button',{name:'刷新范围对象'}).click();await wikiEntry.getByLabel(/^范围/).selectOption('opportunity');await wikiEntry.getByLabel('明确所属对象').selectOption(id);await wikiEntry.getByRole('button',{name:'保存知识',exact:true}).click();await expect.poll(()=>wikiEntry.getByRole('status').textContent()).toBe('已保存');expect(await wikiEntry.getByRole('button',{name:'G4 private opportunity knowledge',exact:true}).count()).toBe(0);await wikiEntry.getByLabel('知识列表范围').selectOption(`opportunity:${id}`);await wikiEntry.getByRole('button',{name:'G4 private opportunity knowledge',exact:true}).waitFor();await wikiEntry.getByLabel('知识列表范围').selectOption('general');await page.getByRole('button',{name:'Wiki 整理辅助',exact:true}).click();const ai=page.getByRole('region',{name:'Wiki AI 整理'});await ai.getByLabel('G4 Evidence.txt',{exact:false}).check();await ai.getByRole('button',{name:'准备本地 Context / 最终发送预览'}).click();await ai.getByRole('heading',{name:'最终实际发送内容'}).waitFor();expect(await ai.getByText(/local:\/\/career-wiki-fake/).first().textContent()).toContain('local://career-wiki-fake');await ai.getByRole('button',{name:'授权这份最终请求（本地 fake，无真实外发）'}).click();const proposal=ai.getByRole('article',{name:'Wiki 待审建议'});await proposal.getByRole('button',{name:'本次忽略'}).click();await proposal.getByText('已忽略，仍可继续处理。').waitFor();await proposal.getByRole('button',{name:'编辑后接受'}).click();await proposal.getByLabel('建议标题').fill('G4 Human reviewed');await proposal.getByLabel('建议正文').fill('Explicit human-edited local fake proposal');await proposal.getByRole('button',{name:'明确采用编辑后的本条'}).click();await expect.poll(()=>ai.getByRole('status').textContent()).toContain('本条已立即生效');
 const wiki=WikiResult.parse(await page.evaluate(()=>window.career.request('wiki',{operation:'list'})));expect(wiki).toMatchObject({kind:'list',items:[{title:'G4 Human reviewed',origin:'ai_accepted',verification:'not_verified'}]});
 const knowledgeView=page.getByRole('region',{name:'Wiki 知识'});await knowledgeView.getByRole('button',{name:'G4 Human reviewed',exact:true}).click();await knowledgeView.getByRole('button',{name:'读取原件'}).click();await knowledgeView.getByRole('complementary',{name:'来源原文'}).getByText('G4 fake fixture: actual immutable evidence.',{exact:true}).waitFor();
 await page.getByRole('button',{name:'设置与资料维护',exact:true}).click();let settings=page.getByRole('region',{name:'资料维护设置'});expect(await settings.getByLabel('应用运行时启用周期备份').isChecked()).toBe(false);await settings.getByRole('button',{name:'立即建立备份'}).click();await expect.poll(()=>settings.getByRole('status').textContent()).toContain('完整恢复点已建立');await settings.getByRole('button',{name:'验证恢复候选'}).click();const restore=settings.getByRole('dialog',{name:'确认恢复'});await restore.getByText(/未保存的编辑将被清空/).waitFor();await restore.getByRole('button',{name:'确认切换资料'}).click();
 await expect.poll(async()=>{const status=DataResult.parse(await page.evaluate(()=>window.career.request('application',{operation:'data.status'})));return status.kind==='data_status'?status.activeWorkspace:'';}).not.toBe('workspaces/local');
 // Restore replaces frontend editor state and keeps the single active pointer through restart.
 await expect.poll(()=>page.getByRole('button',{name:'设置与资料维护',exact:true}).count()).toBe(1);
 await page.getByRole('region',{name:'Wiki 知识'}).getByRole('button',{name:'G4 Human reviewed',exact:true}).click();await page.getByRole('region',{name:'Wiki 知识'}).getByRole('button',{name:'读取原件'}).click();await page.getByRole('complementary',{name:'来源原文'}).getByText('G4 fake fixture: actual immutable evidence.',{exact:true}).waitFor();await page.getByRole('region',{name:'Wiki 知识'}).getByLabel('知识正文').fill('Unrelated dirty knowledge survives Raw purge.');
 await page.getByRole('button',{name:'设置与资料维护',exact:true}).click();settings=page.getByRole('region',{name:'资料维护设置'});await expect.poll(()=>settings.getByLabel('要清除的材料').locator('option').allTextContents()).toContain('materials · G4 Evidence.txt');const optionsList=await settings.getByLabel('要清除的材料').locator('option').allTextContents();await settings.getByLabel('要清除的材料').selectOption({index:optionsList.indexOf('materials · G4 Evidence.txt')});await settings.getByRole('button',{name:'查看清除影响'}).click();const impact=settings.getByRole('dialog',{name:'永久清除影响确认'});await impact.getByText(/old_workspace/).waitFor();await impact.getByRole('button',{name:'确认永久清除选定范围'}).click();await expect.poll(()=>settings.getByRole('status').textContent()).toContain('清除');expect(await page.evaluate(()=>window.careerMaterials.request({operation:'list'}))).toMatchObject({kind:'list',items:[]});expect(await page.getByRole('region',{name:'Wiki 知识'}).getByLabel('知识正文').inputValue()).toBe('Unrelated dirty knowledge survives Raw purge.');expect(await page.locator('#saved-text').count()).toBe(0);expect(await page.getByRole('complementary',{name:'来源原文'}).count()).toBe(0);expect(errors).toEqual([]);
 const pointerBefore=JSON.parse(await readFile(path.join(root,'profile/active-workspace-pointer.json'),'utf8'));await app.evaluate(({dialog})=>{dialog.showMessageBoxSync=(()=>1) as typeof dialog.showMessageBoxSync;});await app.close();app=await _electron.launch(options);page=await app.firstWindow();page.on('dialog',()=>{});await page.getByRole('navigation').waitFor();expect(JSON.parse(await readFile(path.join(root,'profile/active-workspace-pointer.json'),'utf8'))).toEqual(pointerBefore);expect(await page.evaluate(()=>window.careerMaterials.request({operation:'list'}))).toMatchObject({kind:'list',items:[]});
 await writeFile(path.join(tmpdir(),`career-next-g4-${packaged?'packaged':'dev'}.json`),JSON.stringify({mode:packaged?'packaged':'dev',realPdfFrozenA:true,currentBUnchangedHistory:true,oneFirstSubmission:true,realExternalResendFile:true,humanPreviewAuthorizeIgnoreEditAccept:true,provider:'deterministic fake only',backupRestorePurge:true,activePointerDurable:true,errors},null,2));
 }catch(error){const page=await app.firstWindow();await writeFile('/tmp/career-g4-desktop-diagnostic.txt',await page.locator('body').innerText());await page.screenshot({path:'/tmp/career-g4-desktop-diagnostic.png'});throw error;}finally{await app.evaluate(({dialog})=>{dialog.showMessageBoxSync=(()=>1) as typeof dialog.showMessageBoxSync;}).catch(()=>{});await app.close();await rm(root,{recursive:true,force:true});}
},180000);
