import {it,expect} from 'vitest';
import {_electron} from 'playwright';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {Result as EmploymentResult} from '../../packages/contracts/employment/schema';
import {Result as ProjectResult} from '../../packages/contracts/project/schema';
import {Result as WikiResult} from '../../packages/contracts/wiki/schema';

it('J02 continuously accumulates actual Project Raw, people, Wiki, rejected/accepted proposal, reassociation, corrected basis and purge',async()=>{
 const root=await mkdtemp(path.join(tmpdir(),'career-g5-work-')),fixture=path.join(root,'Project evidence.txt');await writeFile(fixture,'Actual project notes: I participated in delivery.');
 const packaged=process.env.CAREER_PACKAGED==='1';const app=await _electron.launch({executablePath:packaged?path.resolve(process.env.CAREER_PACKAGED_EXECUTABLE??'out/CareerNext-darwin-arm64/CareerNext.app/Contents/MacOS/CareerNext'):undefined,args:packaged?['--career-desktop-ui',`--user-data-dir=${root}/profile`]:['.','--career-desktop-ui',`--user-data-dir=${root}/profile`]});
 const page=await app.firstWindow();page.on('dialog',dialog=>void dialog.dismiss().catch(()=>{}));page.setDefaultTimeout(15000);
 try{
 await page.getByRole('navigation').waitFor();const nav=async(name:string)=>page.getByRole('navigation').getByRole('link',{name,exact:false}).click();
 await nav('任职');const e=page.getByRole('region',{name:'任职',exact:true});
 const employment=async(company:string)=>{await e.getByRole('button',{name:'新增任职',exact:true}).click();const form=e.getByRole('button',{name:'创建任职',exact:true}).locator('xpath=ancestor::form');await form.getByLabel('公司',{exact:true}).fill(company);await form.getByLabel('岗位',{exact:true}).fill('Engineer');await form.getByLabel('我确认已经真实开始这段任职').check();await form.getByRole('button',{name:'创建任职',exact:true}).click();await e.getByRole('heading',{name:company+' · Engineer',exact:true}).waitFor();};
 await employment('Work A');const person=e.getByRole('heading',{name:'新增人物（同名不会合并）'}).locator('xpath=ancestor::form');await person.getByLabel('姓名',{exact:true}).fill('Colleague');await person.getByLabel('任职角色',{exact:true}).fill('Reviewer');await person.getByRole('button',{name:'保存人物',exact:true}).click();await e.getByRole('heading',{name:'维护人物',exact:true}).waitFor();await employment('Work B');
 const es=EmploymentResult.parse(await page.evaluate(()=>window.career.request('employment',{operation:'list'})));if(es.kind!=='list')throw Error('employment list');const a=es.employments.find(item=>item.company==='Work A')!,b=es.employments.find(item=>item.company==='Work B')!;
 await nav('项目');const p=page.getByRole('region',{name:'项目',exact:true});await p.getByRole('button',{name:'新增项目',exact:true}).click();const form=p.getByRole('button',{name:'创建项目',exact:true}).locator('xpath=ancestor::form');await form.getByLabel('项目名称',{exact:true}).fill('Delivery project');await form.getByLabel('关联任职',{exact:true}).selectOption(a.id);await form.getByRole('button',{name:'创建项目',exact:true}).click();await p.getByRole('heading',{name:'Delivery project',exact:true}).waitFor();await p.getByLabel('当前任职人物').selectOption({index:1});await p.getByLabel('新参与的项目职责').fill('Project quality reviewer');await p.getByLabel('变化说明',{exact:true}).fill('Actual colleague joined');await p.getByRole('button',{name:'确认加入或重新加入项目'}).click();await p.getByText(/项目职责：Project quality reviewer/).waitFor();
 const ps=ProjectResult.parse(await page.evaluate(()=>window.career.request('project',{operation:'list'})));if(ps.kind!=='list')throw Error('project list');const id=ps.projects[0].id;
 await nav('机会');const opportunity=page.getByRole('region',{name:'机会',exact:true});await opportunity.getByLabel('公司名称',{exact:true}).fill('Actual interview employer');await opportunity.getByRole('button',{name:'建立新公司'}).click();await opportunity.getByRole('button',{name:'保存公司改名'}).waitFor();await opportunity.getByLabel('明确选择公司').selectOption({index:1});await opportunity.getByLabel('岗位名称').fill('Project experience discussion');await opportunity.getByRole('button',{name:'创建机会',exact:true}).click();await opportunity.getByRole('button',{name:'打开面试'}).click();const interview=page.getByRole('region',{name:'面试子模块'});await interview.getByLabel('真实轮次名称').fill('Actual project discussion');await interview.getByRole('button',{name:'确认存在真实轮次'}).click();await interview.getByRole('heading',{name:'Actual project discussion',exact:true}).waitFor();await interview.getByLabel('当前文字稿').fill('I independently led delivery.');await interview.getByRole('button',{name:'保存当前文字稿',exact:true}).click();await expect.poll(()=>interview.getByRole('status').textContent()).toContain('已保存');
 await nav('Wiki');await page.getByRole('button',{name:'刷新归属对象'}).click();await page.getByLabel('材料归属对象').selectOption({label:'project · Delivery project'});await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=(async()=>({canceled:false,filePaths:[file]})) as typeof dialog.showOpenDialog;},fixture);await page.getByRole('button',{name:'选择本地文本材料'}).click();await page.getByRole('button',{name:'确认保存原件'}).click();await expect.poll(()=>page.locator('#saved-text').textContent()).toContain('participated in delivery');
 const wiki=page.getByRole('region',{name:'Wiki 知识'});await wiki.getByRole('button',{name:'刷新范围对象'}).click();await wiki.getByLabel(/^范围/).selectOption('project');await wiki.getByLabel('明确所属对象').selectOption(id);await wiki.getByLabel('知识标题').fill('Delivery basis');await wiki.getByLabel('知识正文').fill('I led all delivery.');await wiki.getByRole('button',{name:'刷新原件列表'}).click();await wiki.getByLabel('选择原件').selectOption({label:'Project evidence.txt'});await wiki.getByLabel('来源用途').fill('Actual original');await wiki.getByRole('button',{name:'加入来源引用'}).click();await wiki.getByLabel('选择原件').selectOption({label:'Project experience discussion · Actual project discussion文字稿'});await wiki.getByLabel('来源用途').fill('Actual correctable source');await wiki.getByRole('button',{name:'加入来源引用'}).click();await wiki.getByRole('button',{name:'保存知识',exact:true}).click();await wiki.getByRole('button',{name:'保存知识修改'}).waitFor();await wiki.getByRole('button',{name:'读取原件'}).first().click();await wiki.getByRole('complementary',{name:'来源原文'}).getByText('Actual project notes: I participated in delivery.',{exact:true}).waitFor();await wiki.getByLabel('知识列表范围').selectOption(`project:${id}`);
 await page.getByRole('button',{name:'Wiki 整理辅助',exact:true}).click();const ai=page.getByRole('region',{name:'Wiki AI 整理'});await ai.getByLabel('Project evidence.txt',{exact:false}).check();await ai.getByLabel('Wiki 目标').selectOption({label:'project · Delivery project'});
 const prepare=async()=>{await ai.getByRole('button',{name:'准备本地 Context / 最终发送预览'}).click();await ai.getByRole('button',{name:'授权这份最终请求（本地 fake，无真实外发）'}).click();await ai.getByRole('article',{name:'Wiki 待审建议'}).waitFor();};await prepare();await ai.getByRole('button',{name:'拒绝本条'}).click();await expect.poll(()=>ai.getByRole('status').textContent()).toContain('已拒绝本条');await prepare();await ai.getByRole('button',{name:'接受本条并立即生效'}).click();await expect.poll(()=>ai.getByRole('status').textContent()).toContain('本条已立即生效');
 const list=()=>page.evaluate(()=>window.career.request('wiki',{operation:'list'}));const before=WikiResult.parse(await list());if(before.kind!=='list')throw Error('wiki');const derived=before.items.find(item=>item.origin==='ai_accepted')!;expect(derived).toMatchObject({scope:'project',scopeId:id,verification:'not_verified',reviewRequired:false});expect(derived.trustedProvenance?.some(source=>source.owner==='wiki')).toBe(true);
 await nav('项目');await p.getByLabel('变化说明',{exact:true}).fill('Actual change to Work B');await p.getByLabel('新的关联任职').selectOption(b.id);await p.getByRole('button',{name:'确认变更任职关联'}).click();await p.getByText(/当前归属：Work B/).waitFor();await p.getByText(/Project quality reviewer · 历史协作/).waitFor();await p.getByRole('button',{name:'读取项目与协作历史'}).click();await p.getByText(/Actual change to Work B/).waitFor();
 await nav('Wiki');expect(await wiki.getByLabel('知识列表范围').inputValue()).toBe(`project:${id}`);expect(await wiki.getByLabel('知识标题').inputValue()).toBe('Delivery basis');expect(await wiki.getByLabel('知识正文').inputValue()).toBe('I led all delivery.');// Continue editing the same selection verified above; do not start a redundant asynchronous reopen.
 await wiki.getByLabel('知识正文').fill('Correction: I participated, not led all delivery.');await wiki.getByLabel('变化说明').fill('Correct inaccurate derived basis against unchanged original');await wiki.getByLabel('纠正原记录；不勾选表示后来发生的变化').check();await wiki.getByRole('button',{name:'保存知识修改'}).click();await expect.poll(async()=>{const value=WikiResult.parse(await list());return value.kind==='list'?value.items.find(item=>item.title==='Delivery basis')?.body:undefined;}).toBe('Correction: I participated, not led all delivery.');await wiki.getByRole('button',{name:'查看知识修订历史'}).click();const knowledgeHistory=wiki.getByRole('complementary',{name:'知识历史'});await expect.poll(()=>knowledgeHistory.getByRole('article').count()).toBe(2);await knowledgeHistory.getByRole('article').filter({hasText:'版本 1 · created'}).getByText('I led all delivery.',{exact:true}).waitFor();await knowledgeHistory.getByRole('article').filter({hasText:'版本 2 · corrected'}).getByText('Correction: I participated, not led all delivery.',{exact:true}).waitFor();
 await nav('机会');await opportunity.getByRole('button',{name:'打开面试'}).click();await interview.getByLabel('当前文字稿').fill('Corrected: I participated in delivery.');await interview.getByRole('button',{name:'保存当前文字稿',exact:true}).click();await expect.poll(()=>interview.getByRole('status').textContent()).toContain('已保存');await nav('Wiki');
 const corrected=WikiResult.parse(await list());if(corrected.kind!=='list')throw Error('wiki');expect(corrected.items.find(item=>item.id===derived.id)).toMatchObject({scopeId:id,body:derived.body,reviewRequired:true});
 await page.getByRole('button',{name:'设置与资料维护',exact:true}).click();const settings=page.getByRole('region',{name:'资料维护设置'});await settings.getByLabel('要清除的材料').selectOption({label:'materials · Project evidence.txt'});await settings.getByRole('button',{name:'查看清除影响'}).click();await settings.getByRole('dialog',{name:'永久清除影响确认'}).getByRole('button',{name:'确认永久清除选定范围'}).click();await expect.poll(()=>settings.getByRole('status').textContent()).toContain('清除');expect(await page.evaluate(()=>window.careerMaterials.request({operation:'list'}))).toMatchObject({kind:'list',items:[]});const after=WikiResult.parse(await list());if(after.kind!=='list')throw Error('wiki');expect(after.items).toHaveLength(2);expect(after.items.every(item=>item.scopeId===id&&item.reviewRequired)).toBe(true);expect(await page.getByRole('complementary',{name:'来源原文'}).count()).toBe(0);
 await writeFile(path.join(tmpdir(),`career-next-g5-work-${packaged?'packaged':'dev'}.json`),JSON.stringify({mode:packaged?'packaged':'dev',journey:'J-02',realProjectScopedFile:true,personRoleAndHistoricalContext:true,sameSessionListFilterPreserved:true,meaningfulSelectedKnowledgePreserved:true,rejectAccept:true,unchangedRawCorrectedTranscriptBasis:true,derivedReviewRequired:true,rawPurgeOwnerPreserved:true,provider:'deterministic fake only'},null,2));
 }catch(error){await writeFile('/tmp/career-g5-work-diagnostic.txt',await page.locator('body').innerText());throw error;}finally{await app.evaluate(({dialog})=>{dialog.showMessageBoxSync=(()=>1) as typeof dialog.showMessageBoxSync;}).catch(()=>{});await app.close();await rm(root,{recursive:true,force:true});}
},120000);
