import {it,expect} from 'vitest';import {_electron} from 'playwright';import {mkdtemp,writeFile,rm} from 'node:fs/promises';import path from 'node:path';import {tmpdir} from 'node:os';
it('normal two-window editor keeps remote unrelated typing, explicit conflict comparison, refresh and protected close',async()=>{
 const root=await mkdtemp(path.join(tmpdir(),'career-g5-windows-')),packaged=process.env.CAREER_PACKAGED==='1',app=await _electron.launch({executablePath:packaged?path.resolve(process.env.CAREER_PACKAGED_EXECUTABLE??'out/CareerNext-darwin-arm64/CareerNext.app/Contents/MacOS/CareerNext'):undefined,args:packaged?['--career-desktop-ui',`--user-data-dir=${root}/profile`]:['.','--career-desktop-ui',`--user-data-dir=${root}/profile`],timeout:30000});
 try{const a=await app.firstWindow();a.setDefaultTimeout(15000);a.on('dialog',dialog=>{void dialog.dismiss().catch(()=>{});});await a.getByRole('navigation').waitFor();await a.getByRole('navigation').getByRole('link',{name:'机会'}).click();const opportunity=a.getByRole('region',{name:'机会',exact:true});await opportunity.getByLabel('公司名称',{exact:true}).fill('G5 windows employer');await opportunity.getByRole('button',{name:'建立新公司'}).click();await opportunity.getByRole('button',{name:'保存公司改名'}).waitFor();await opportunity.getByLabel('明确选择公司').selectOption({index:1});await opportunity.getByLabel('岗位名称').fill('Shared real owner');await opportunity.getByRole('button',{name:'创建机会',exact:true}).click();await opportunity.getByRole('button',{name:'编辑本机会简历'}).click();const editorA=a.getByRole('textbox',{name:'简历正文'});await editorA.waitFor();await editorA.locator('p').first().click();await a.keyboard.type('Actual selected paragraph.');await expect.poll(()=>a.getByTestId('resume-save-state').textContent()).toBe('已保存');
 // Invoke the ordinary production File menu, never a test-only renderer bridge.
 const next=app.waitForEvent('window');await app.evaluate(({Menu,BrowserWindow})=>{const file=Menu.getApplicationMenu()?.items.find(i=>i.label==='文件'),item=file?.submenu?.items.find(i=>i.label==='新建窗口');if(!item)throw Error('new-window menu missing');item.click(undefined as never,BrowserWindow.getAllWindows()[0],undefined as never);});const b=await next;b.setDefaultTimeout(15000);b.on('dialog',dialog=>{void dialog.dismiss().catch(()=>{});});await b.getByRole('navigation').waitFor();await b.getByRole('navigation').getByRole('link',{name:'机会'}).click();await b.getByRole('button',{name:'G5 windows employer · Shared real owner',exact:true}).click();await b.getByRole('button',{name:'编辑本机会简历'}).click();const editorB=b.getByRole('textbox',{name:'简历正文'});await editorB.waitFor();expect(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().length)).toBe(2);
 await b.getByLabel('基础资料姓名').filter({visible:true}).fill('B unsaved identity');await a.getByLabel('基础资料姓名').filter({visible:true}).fill('A committed global identity');await a.getByRole('button',{name:'保存基础资料'}).click();await a.getByText('基础资料已保存，所有当前简历使用最新身份').filter({visible:true}).waitFor();await b.getByText(/当前正式资料：A committed global identity/).waitFor();expect(await b.getByLabel('基础资料姓名').filter({visible:true}).inputValue()).toBe('B unsaved identity');await b.getByRole('button',{name:'放弃本地身份输入，采用正式资料'}).click();expect(await b.getByLabel('基础资料姓名').filter({visible:true}).inputValue()).toBe('A committed global identity');
 await a.getByRole('button',{name:'简历优化提案',exact:true}).click();const selection=a.getByLabel('简历优化选择');await selection.getByLabel(/个人简介 · Actual selected/).check();const ai=selection.getByRole('region',{name:'产品任务辅助'});await ai.getByRole('button',{name:'准备当前任务与最终预览'}).click();await ai.getByRole('button',{name:'授权这份最终请求'}).click();await ai.getByRole('article',{name:'产品待审提案'}).first().waitFor();await editorB.locator('p').last().click();await b.keyboard.type('Remote window unrelated saved contribution.');await expect.poll(()=>b.getByTestId('resume-save-state').textContent()).toBe('已保存');await ai.getByRole('article',{name:'产品待审提案'}).first().getByRole('button',{name:'接受本条并立即生效'}).click();await expect.poll(()=>editorA.textContent()).toContain('受控优化建议');expect(await editorA.textContent()).toContain('Remote window unrelated saved contribution.');await expect.poll(()=>a.getByTestId('resume-save-state').textContent()).toBe('已保存');
 // A single AI undo must retain B's separately committed text.
 await a.getByRole('button',{name:'撤销',exact:true}).click();await expect.poll(()=>editorA.textContent()).not.toContain('受控优化建议');expect(await editorA.textContent()).toContain('Remote window unrelated saved contribution.');await expect.poll(()=>a.getByTestId('resume-save-state').textContent()).toBe('已保存');
 await b.reload();await editorB.waitFor();await editorB.locator('p').last().click();await b.keyboard.press('End');await b.keyboard.type(' Remote next-block newer text before AI addition.');await expect.poll(()=>b.getByTestId('resume-save-state').textContent()).toBe('已保存');const addition=ai.getByRole('article',{name:'产品待审提案'}).filter({hasText:'resume-add ·'});await addition.getByRole('button',{name:'接受本条并立即生效'}).click();await expect.poll(()=>editorA.locator('p').count()).toBe(6);expect(await editorA.textContent()).toContain('Remote next-block newer text before AI addition.');await expect.poll(()=>a.getByTestId('resume-save-state').textContent()).toBe('已保存');await a.getByRole('button',{name:'撤销',exact:true}).click();await expect.poll(()=>editorA.locator('p').count()).toBe(5);expect(await editorA.textContent()).toContain('Remote next-block newer text before AI addition.');await expect.poll(()=>a.getByTestId('resume-save-state').textContent()).toBe('已保存');
 await a.reload();await editorA.waitFor();await b.reload();await editorB.waitFor();expect(await editorB.textContent()).toContain('Remote next-block newer text');
 // Both renderers really edit the same baseline. B commits first; A must retain its local text without overwriting B.
 await editorB.locator('p').last().click();await b.keyboard.press('End');await b.keyboard.type(' B actual newer edit.');await expect.poll(()=>b.getByTestId('resume-save-state').textContent()).toBe('已保存');await editorA.locator('p').last().click();await a.keyboard.press('End');await a.keyboard.type(' A unsaved comparison draft.');await a.getByRole('button',{name:'放弃本地正文，采用正式正文'}).waitFor();expect(await editorA.textContent()).toContain('A unsaved comparison draft.');expect(await a.locator('pre').textContent()).toContain('B actual newer edit.');await a.getByRole('button',{name:'放弃本地正文，采用正式正文'}).click();expect(await editorA.textContent()).toContain('B actual newer edit.');expect(await editorA.textContent()).not.toContain('A unsaved comparison draft.');
 const long=Array.from({length:30},(_,i)=>'Ordinary paragraph '+i+' about controlled actual delivery.').join(' ');await editorA.locator('p').last().click();await a.keyboard.press('End');await a.keyboard.type(long);await expect.poll(()=>a.getByTestId('resume-save-state').textContent()).toBe('已保存');await a.reload();await expect.poll(()=>editorA.textContent()).toContain('Ordinary paragraph 29');
 await a.getByLabel('基础资料姓名').filter({visible:true}).fill('Unsaved protected identity');await app.evaluate(({dialog})=>{dialog.showMessageBoxSync=(()=>0) as typeof dialog.showMessageBoxSync;});await (await app.browserWindow(a)).evaluate(window=>window.close());await expect.poll(()=>app.windows().length).toBe(2);expect(await a.getByLabel('基础资料姓名').filter({visible:true}).inputValue()).toBe('Unsaved protected identity');await a.getByRole('button',{name:'保存基础资料'}).click();await a.getByText('基础资料已保存，所有当前简历使用最新身份').filter({visible:true}).waitFor();// Restore while the other actual window refuses reload. A material reconnect must not reauthorize its old editor.
 await b.getByLabel('基础资料姓名').filter({visible:true}).fill('Old workspace input must stay isolated');await app.evaluate(({dialog})=>{dialog.showMessageBoxSync=(()=>0) as typeof dialog.showMessageBoxSync;});await a.getByRole('button',{name:'设置与资料维护',exact:true}).click();const settings=a.getByRole('region',{name:'资料维护设置'});await settings.getByRole('button',{name:'立即建立备份'}).click();await expect.poll(()=>settings.getByRole('status').textContent(),{timeout:30000}).toContain('完整恢复点已建立');await settings.getByRole('button',{name:'验证恢复候选'}).first().click();await settings.getByRole('dialog',{name:'确认恢复'}).getByRole('button',{name:'确认切换资料'}).click();await expect.poll(()=>settings.count(),{timeout:30000}).toBe(0);await a.getByRole('navigation').waitFor();await expect.poll(()=>b.evaluate(()=>window.careerMaterials.reconnect().then(()=>false,()=>true))).toBe(true);expect(await b.getByLabel('基础资料姓名').filter({visible:true}).inputValue()).toBe('Old workspace input must stay isolated');expect(await b.evaluate(()=>window.career.request('opportunity',{operation:'list'}).then(()=>false,()=>true))).toBe(true);await app.evaluate(({dialog})=>{dialog.showMessageBoxSync=(()=>1) as typeof dialog.showMessageBoxSync;});b.on('dialog',dialog=>{void dialog.dismiss().catch(()=>{});});await b.reload();await editorB.waitFor();expect(await b.getByLabel('基础资料姓名').filter({visible:true}).inputValue()).toBe('Unsaved protected identity');expect(await b.evaluate(()=>window.career.request('opportunity',{operation:'list'}))).toMatchObject({kind:'opportunities'});
 // Exact purge metadata reaches every same-workspace normal window and removes B's cached Resume.
 await a.getByRole('button',{name:'设置与资料维护',exact:true}).click();const refreshed=a.getByRole('region',{name:'资料维护设置'}),targets=await a.evaluate(()=>window.career.request('application',{operation:'data.targets'})) as any,resume=targets.targets.find((item:any)=>item.owner==='resume');await refreshed.getByLabel('要清除的材料').selectOption({label:resume.label});await refreshed.getByRole('button',{name:'查看清除影响'}).click();await refreshed.getByRole('dialog',{name:'永久清除影响确认'}).getByRole('button',{name:'确认永久清除选定范围'}).click();await expect.poll(()=>editorB.count()).toBe(0);await b.getByRole('button',{name:'明确开始新的当前简历'}).waitFor();
 await writeFile(path.join(tmpdir(),`career-next-g5-windows-${packaged?'packaged':'dev'}.json`),JSON.stringify({normalMenuTwoWindows:true,sharedSingleWriter:true,dirtyIdentityPreservedWithFormalComparison:true,remoteUnrelatedPreserved:true,conflictDraftComparison:true,refreshSavedOnly:true,ordinaryLongBody:true,protectedClose:true,restoreOldWindowRebindDenied:true,crossWindowPurgeInvalidation:true,realIME:'pending human'},null,2));
 }catch(error){for(const [index,page] of app.windows().entries())await writeFile('/tmp/career-g5-windows-'+index+'.txt',await page.locator('body').innerText());throw error;}finally{await app.evaluate(({dialog})=>{dialog.showMessageBoxSync=(()=>1) as typeof dialog.showMessageBoxSync;}).catch(()=>{});await app.close();await rm(root,{recursive:true,force:true});}
},150000);
