import {expect,it} from 'vitest';
import {_electron,type ElectronApplication,type Page} from 'playwright';
import Database from 'better-sqlite3';
import {mkdtemp,readFile,writeFile,rm,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
const executable=process.env.CAREER_PACKAGED_EXECUTABLE;
const observations:Record<string,unknown>={packagedExecutable:executable,physicalSleepWake:'NOT RUN',humanNativeChoice:'NOT RUN'};
async function record(name:string,value:unknown){observations[name]=value;await mkdir('/tmp/career-g6-continuity',{recursive:true});await writeFile('/tmp/career-g6-continuity/observations.json',JSON.stringify(observations,null,2));}
async function launch(profile:string){if(!executable)throw Error('normal packaged executable required');const app=await _electron.launch({executablePath:executable,args:['--career-desktop-ui',`--user-data-dir=${profile}`],timeout:30000});const page=await app.firstWindow();page.setDefaultTimeout(15000);await page.getByRole('navigation',{name:'一级导航'}).waitFor();return {app,page};}
async function closeWindow(app:ElectronApplication){const process=app.process(),exit=new Promise<void>((resolve,reject)=>{if(process.exitCode!==null)return resolve();const timer=setTimeout(()=>reject(Error('normal window close did not finish')),30000);process.once('exit',()=>{clearTimeout(timer);resolve();});});await app.evaluate(({BrowserWindow,dialog})=>{dialog.showMessageBoxSync=(()=>1) as typeof dialog.showMessageBoxSync;BrowserWindow.getAllWindows().find(w=>w.isVisible())!.close();});await exit;}
async function finish(app:ElectronApplication|undefined,root:string){if(app){await app.evaluate(({dialog})=>{dialog.showMessageBoxSync=(()=>1) as typeof dialog.showMessageBoxSync;}).catch(()=>{});await app.close().catch(()=>{});}await rm(root,{recursive:true,force:true});}
async function seed(page:Page){return page.evaluate(async()=>{const call=(module:any,input:any)=>window.career.request(module,input) as Promise<any>;const company=(await call('opportunity',{operation:'company.create',commandId:crypto.randomUUID(),name:'G6 continuity fictional company'})).company;const opportunity=(await call('opportunity',{operation:'create',commandId:crypto.randomUUID(),companyId:company.id,role:'Continuity fixture'})).opportunity;const resume=await call('resume',{operation:'resume.open',commandId:crypto.randomUUID(),opportunityId:opportunity.id});const wiki=await call('wiki',{operation:'create',commandId:crypto.randomUUID(),title:'G6 continuity preserved',body:'Only isolated synthetic continuity evidence.',scope:'personal',nature:'observation',sources:[]});if(wiki.kind!=='knowledge'||resume.status!=='document')throw Error('fixture failed');return {companyId:company.id,opportunityId:opportunity.id,resumeId:resume.document.id,resumeRevision:resume.document.revision,profileRevision:resume.profile.revision,wikiId:wiki.knowledge.id};});}
async function copies(profile:string):Promise<any[]>{return JSON.parse(await readFile(path.join(profile,'managed-copies-manifest.json'),'utf8'));}
async function currentDatabase(profile:string){const pointer=JSON.parse(await readFile(path.join(profile,'active-workspace-pointer.json'),'utf8'));return path.join(profile,pointer.relativePath,'career.sqlite');}
it('normal packaged app closes with real PDF bytes held before delivery; reopen fails the original job without creating a version',async()=>{
 const root=await mkdtemp(path.join(tmpdir(),'career-g6-pdf-close-')),profile=path.join(root,'profile');let app:ElectronApplication|undefined;
 try{let session=await launch(profile);app=session.app;const fixture=await seed(session.page),commandId=randomUUID();
  await app.evaluate(({app})=>{(globalThis as any).__g6Pdf=undefined;app.on('browser-window-created',(_event,win)=>{const original=win.webContents.printToPDF.bind(win.webContents);win.webContents.printToPDF=async options=>{const bytes=await original(options);(globalThis as any).__g6Pdf={header:bytes.subarray(0,5).toString(),size:bytes.length,eof:bytes.subarray(-1024).includes(Buffer.from('%%EOF'))};await new Promise<void>(()=>{});return bytes;};});});
  await session.page.evaluate(({fixture,commandId})=>{(window as any).__g6Pending=window.career.request('resume',{operation:'resume.name-version',commandId,resumeId:fixture.resumeId,expectedRevision:fixture.resumeRevision,expectedProfileRevision:fixture.profileRevision,name:'Must not freeze interrupted PDF'}).catch(()=>undefined);},{fixture,commandId});
  await expect.poll(()=>app!.evaluate(()=>(globalThis as any).__g6Pdf),{timeout:45000}).toMatchObject({header:'%PDF-',eof:true});const pdf=await app.evaluate(()=>(globalThis as any).__g6Pdf);expect(pdf.size).toBeGreaterThan(500);
  await closeWindow(app);app=undefined;session=await launch(profile);app=session.app;
  const receipt=await session.page.evaluate(commandId=>window.career.request('resume',{operation:'resume.receipt',commandId}),commandId);expect(receipt).toEqual({status:'failure',code:'pdf-failed'});expect(await session.page.evaluate(resumeId=>window.career.request('resume',{operation:'resume.versions',resumeId}),fixture.resumeId)).toMatchObject({status:'versions',versions:[]});
  await record('pendingPdfClose',{status:'PASS',commandId,actualChromiumPdf:pdf,receipt,versionCount:0});
 }finally{await finish(app,root);}
},120000);
it('normal packaged app closes while a real backup is candidate and resolves it without losing the last complete point',async()=>{
 const root=await mkdtemp(path.join(tmpdir(),'career-g6-backup-close-')),profile=path.join(root,'profile');let app:ElectronApplication|undefined;
 try{let session=await launch(profile);app=session.app;await seed(session.page);const prior=await session.page.evaluate(()=>window.career.request('application',{operation:'data.backup'})) as any;expect(prior.kind).toBe('backup');
  await session.page.evaluate(async()=>{for(let i=0;i<24;i++){const result=await window.career.request('wiki',{operation:'create',commandId:crypto.randomUUID(),title:'G6 bounded backup '+i,body:'Synthetic backup continuity body. '.repeat(1700),scope:'personal',nature:'observation',sources:[]});if((result as {kind:string}).kind!=='knowledge')throw Error('large fixture failed');}});
  const known=new Set((await copies(profile)).map(copy=>copy.id));await session.page.evaluate(()=>{(window as any).__g6Backup=window.career.request('application',{operation:'data.backup'}).catch(()=>undefined);});
  let candidate:any;await expect.poll(async()=>{candidate=(await copies(profile)).find(copy=>!known.has(copy.id)&&copy.kind==='backup'&&copy.state==='candidate');return !!candidate;},{interval:1,timeout:15000}).toBe(true);
  const candidateAtClose=await copies(profile);expect(candidateAtClose.find(copy=>copy.id===candidate.id)?.state).toBe('candidate');await closeWindow(app);app=undefined;session=await launch(profile);app=session.app;
  const resolved=(await copies(profile)).find(copy=>copy.id===candidate.id);expect(['ready','failed']).toContain(resolved.state);const before=(await copies(profile)).find(copy=>copy.id===prior.copy.id);expect(before).toMatchObject({kind:'backup',state:'ready'});
  const prepared=await session.page.evaluate(id=>window.career.request('application',{operation:'data.restore.prepare',backupId:id}),prior.copy.id) as any;expect(prepared.kind).toBe('restore_candidate');
  if(resolved.state==='ready')expect((await session.page.evaluate(id=>window.career.request('application',{operation:'data.restore.prepare',backupId:id}),candidate.id) as any).kind).toBe('restore_candidate');
  await record('pendingBackupClose',{status:'PASS',observedBeforeClose:candidateAtClose.find(copy=>copy.id===candidate.id),resolved,lastCompleteVerified:prior.copy.id});
 }finally{await finish(app,root);}
},120000);
it('normal packaged stop immediately blocks dispatch during backup and a real DB lock; original receipt is recovered with the same command',async()=>{
 const root=await mkdtemp(path.join(tmpdir(),'career-g6-stop-maintenance-')),profile=path.join(root,'profile');let app:ElectronApplication|undefined,locker:Database.Database|undefined;
 try{const session=await launch(profile);app=session.app;const fixture=await seed(session.page);const prepared=await session.page.evaluate(opportunityId=>window.career.request('ai',{operation:'product.prepare',commandId:crypto.randomUUID(),input:{target:{kind:'greeting',opportunityId,includeName:false},sources:[],egressSourceIds:[],wikiIds:[],egressWikiIds:[],objects:[]},budget:{requests:2,inputBytes:524288,outputBytes:196608}}),fixture.opportunityId) as any;expect(prepared.kind).toBe('product_task');const taskId=prepared.task.id,commandId=randomUUID();
  locker=new Database(await currentDatabase(profile));locker.exec('BEGIN IMMEDIATE');const known=new Set((await copies(profile)).map(copy=>copy.id));await session.page.evaluate(()=>{(window as any).__g6Backup=window.career.request('application',{operation:'data.backup'}).catch(()=>undefined);});let candidate:any;await expect.poll(async()=>{candidate=(await copies(profile)).find(copy=>!known.has(copy.id)&&copy.kind==='backup'&&copy.state==='candidate');return !!candidate;},{interval:1,timeout:15000}).toBe(true);
  const started=Date.now(),reply=await session.page.evaluate(({taskId,commandId})=>window.career.request('ai',{operation:'product.stop',commandId,taskId,mode:'revoke'}),{taskId,commandId});const elapsed=Date.now()-started;expect(reply).toMatchObject({kind:'execution_blocked',taskId,commandId,dispatchBlocked:true,persistencePending:true});expect(elapsed).toBeLessThan(1000);
  // Keep the actual writer locked until its configured SQLite busy timeout has expired.
  await new Promise(resolve=>setTimeout(resolve,3500));locker.exec('ROLLBACK');locker.close();locker=undefined;
  const original=await session.page.evaluate(commandId=>window.career.request('ai',{operation:'product.receipt',commandId}),commandId);expect((original as {kind:string}).kind).toBe('receipt_missing');
  await session.page.evaluate(({taskId,commandId})=>window.career.request('ai',{operation:'product.stop',commandId,taskId,mode:'revoke'}),{taskId,commandId});await expect.poll(()=>session.page.evaluate(commandId=>window.career.request('ai',{operation:'product.receipt',commandId}),commandId),{timeout:15000}).toMatchObject({kind:'product_receipt',receipt:{kind:'product_task',task:{state:'revoked',usedRequests:0}}});
  await record('stopFailureMaintenance',{status:'PASS',realBackupCandidate:candidate.id,reply,elapsedMs:elapsed,originalReceipt:original,originalCommandRetried:commandId,externalRequests:0});
 }finally{if(locker){locker.exec('ROLLBACK');locker.close();}await finish(app,root);}
},120000);
it('normal packaged restore candidate survives reopen, activates only after confirmation, and corrupt pointer recovery uses an explicit native choice',async()=>{
 const root=await mkdtemp(path.join(tmpdir(),'career-g6-restore-choice-')),profile=path.join(root,'profile');let app:ElectronApplication|undefined;
 try{let session=await launch(profile);app=session.app;const fixture=await seed(session.page),originalIdentity=await session.page.evaluate(()=>window.careerMaterials.ready()),backup=await session.page.evaluate(()=>window.career.request('application',{operation:'data.backup'})) as any;expect(backup.kind).toBe('backup');const candidate=await session.page.evaluate(id=>window.career.request('application',{operation:'data.restore.prepare',backupId:id}),backup.copy.id) as any;expect(candidate.kind).toBe('restore_candidate');const pointerBefore=await readFile(path.join(profile,'active-workspace-pointer.json'),'utf8');
  await closeWindow(app);app=undefined;session=await launch(profile);app=session.app;expect(await readFile(path.join(profile,'active-workspace-pointer.json'),'utf8')).toBe(pointerBefore);expect((await copies(profile)).find(copy=>copy.id===candidate.copy.id)).toMatchObject({kind:'restore_candidate',state:'ready'});
  expect((await session.page.evaluate(id=>window.career.request('application',{operation:'data.restore.activate',candidateId:id,confirmed:true}),candidate.copy.id) as any).kind).toBe('restored');const activated=await session.page.evaluate(()=>window.careerMaterials.ready());expect(activated.workspaceInstance).not.toBe(originalIdentity.workspaceInstance);expect(activated.backendGeneration).not.toBe(originalIdentity.backendGeneration);expect(activated.connectionGeneration).not.toBe(originalIdentity.connectionGeneration);
  await closeWindow(app);app=undefined;session=await launch(profile);app=session.app;expect((await session.page.evaluate(()=>window.careerMaterials.ready())).workspaceInstance).toBe(activated.workspaceInstance);
  // Install the explicit test choice before triggering the real reconnect path; no startup/dialog timing race.
  await app.evaluate(({dialog})=>{(globalThis as any).__g6Choice=undefined;dialog.showMessageBox=(async(_owner,options)=>{(globalThis as any).__g6Choice={message:options.message,buttons:options.buttons,response:1};return {response:1,checkboxChecked:false};}) as typeof dialog.showMessageBox;});
  await writeFile(path.join(profile,'active-workspace-pointer.json'),'{"broken":true}');const recovered=await session.page.evaluate(()=>window.careerMaterials.reconnect().catch(error=>({error:String(error)})));expect(recovered).toMatchObject({error:expect.stringContaining('workspace_changed_reload_required')});await session.page.reload();await session.page.getByRole('navigation',{name:'一级导航'}).waitFor();const recoveredIdentity=await session.page.evaluate(()=>window.careerMaterials.ready());expect(recoveredIdentity.workspaceInstance).not.toBe(activated.workspaceInstance);const choice=await app.evaluate(()=>(globalThis as any).__g6Choice);expect(choice.response).toBe(1);expect(choice.buttons[1]).toContain('验证并恢复备份');expect(await session.page.evaluate(id=>window.career.request('wiki',{operation:'read',id}),fixture.wikiId)).toMatchObject({kind:'knowledge',knowledge:{title:'G6 continuity preserved'}});
  await closeWindow(app);app=undefined;session=await launch(profile);app=session.app;expect((await session.page.evaluate(()=>window.careerMaterials.ready())).workspaceInstance).toBe(recoveredIdentity.workspaceInstance);await record('restoreAndExplicitRecovery',{status:'PASS',candidateId:candidate.copy.id,candidateDidNotAutoActivate:true,originalIdentity,activated,recoveredIdentity,nativeDialogChoice:choice,choicePerformedBy:'test adapter; not human',realVerificationAndActivation:true,restartPointerPreserved:true});
 }finally{await finish(app,root);}
},150000);
