import{it,expect}from'vitest';import{_electron}from'playwright';import{mkdtemp,readFile,readdir,writeFile,rm}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';import{randomUUID}from'node:crypto';
it('normal preload/Main use real macOS safeStorage for virtual credentials and enforce current fake provider generation without secret leakage',async()=>{
 const root=await mkdtemp(path.join(tmpdir(),'career-g6-native-secret-')),profile=path.join(root,'profile'),exe=process.env.CAREER_PACKAGED_EXECUTABLE;const app=await _electron.launch({executablePath:exe,args:exe?[`--user-data-dir=${profile}`]:['.',`--user-data-dir=${profile}`],timeout:30000});const logs:string[]=[];app.process().stderr?.on('data',c=>logs.push(String(c)));const fake='G6_VIRTUAL_NOT_A_REAL_KEY_'+randomUUID();
 try{const page=await app.firstWindow();await page.getByRole('navigation').waitFor();await page.getByRole('button',{name:'设置与资料维护',exact:true}).click();const area=page.getByRole('region',{name:'外部服务凭据',exact:true});await area.waitFor();await area.getByLabel('新凭据').fill(fake);await writeFile('/tmp/career-g6/native-secret-phase.txt','actual safeStorage encrypt starting');await area.getByRole('button',{name:'安全保存新凭据',exact:true}).click();
 await expect.poll(async()=>page.evaluate(()=>window.careerSecrets.request({operation:'status'})),{timeout:120000}).toMatchObject({kind:'status',status:{configured:true,enabled:true}});expect(await area.getByLabel('新凭据').inputValue()).toBe('');
 const binding=JSON.parse(await readFile(path.join(profile,'security/binding.json'),'utf8')),cipher=await readFile(path.join(profile,'security',binding.generation+'.encrypted'));expect(cipher.includes(Buffer.from(fake))).toBe(false);const decrypted=await app.evaluate(async({safeStorage},data)=>safeStorage.decryptStringAsync(Buffer.from(data)),[...cipher]);expect(decrypted.result).toBe(fake);
 const company=await page.evaluate(commandId=>window.career.request('opportunity',{operation:'company.create',commandId,name:'Native generation fixture'}),randomUUID()) as any;const prepare=()=>page.evaluate(async({companyId,commandId})=>window.career.request('ai',{operation:'product.prepare',commandId,input:{target:{kind:'research-organize',owner:{kind:'company',id:companyId}},sources:[],egressSourceIds:[],wikiIds:[],egressWikiIds:[],objects:[]},budget:{requests:2,inputBytes:524288,outputBytes:196608}}),{companyId:company.company.id,commandId:randomUUID()}) as Promise<any>;
 const task=await prepare();expect(task.task.operations[0].recipient.generation).toBe(binding.generation);await area.getByRole('button',{name:'停用凭据',exact:true}).click();await expect.poll(async()=>page.evaluate(()=>window.careerSecrets.request({operation:'status'}))).toMatchObject({kind:'status',status:{enabled:false}});expect(await prepare()).toMatchObject({kind:'failure',code:'provider_disabled'});
 await area.getByLabel('新凭据').fill('G6_VIRTUAL_CANCEL');await area.getByRole('button',{name:'取消凭据输入',exact:true}).click();expect(await area.getByLabel('新凭据').inputValue()).toBe('');expect((await page.evaluate(()=>window.careerSecrets.request({operation:'status'})) as any).status.generation).toBe(binding.generation);
 await app.evaluate(({safeStorage})=>{(globalThis as any).g6OriginalAvailability=safeStorage.isAsyncEncryptionAvailable;safeStorage.isAsyncEncryptionAvailable=async()=>false;});await area.getByLabel('新凭据').fill('G6_VIRTUAL_FAILED_REPLACEMENT');await area.getByRole('button',{name:'安全保存新凭据',exact:true}).click();await area.getByRole('status').getByText('安全保存失败，请重新输入；没有使用明文备用方式。').waitFor();expect(await area.getByLabel('新凭据').inputValue()).toBe('');expect(await page.evaluate(()=>window.careerSecrets.request({operation:'status'}))).toMatchObject({kind:'status',status:{enabled:false,generation:binding.generation}});expect(await prepare()).toMatchObject({kind:'failure',code:'provider_disabled'});await app.evaluate(({safeStorage})=>{safeStorage.isAsyncEncryptionAvailable=(globalThis as any).g6OriginalAvailability;delete(globalThis as any).g6OriginalAvailability;});
 const replacement='G6_VIRTUAL_REPLACEMENT_'+randomUUID();await area.getByLabel('新凭据').fill(replacement);await area.getByRole('button',{name:'安全保存新凭据',exact:true}).click();await expect.poll(async()=>page.evaluate(()=>window.careerSecrets.request({operation:'status'}))).toMatchObject({kind:'status',status:{enabled:true}});const nextBinding=JSON.parse(await readFile(path.join(profile,'security/binding.json'),'utf8'));expect(nextBinding.generation).not.toBe(binding.generation);expect((await readdir(path.join(profile,'security')))).not.toContain(binding.generation+'.encrypted');expect((await prepare()).task.operations[0].recipient.generation).toBe(nextBinding.generation);
 const backup=await page.evaluate(()=>window.career.request('application',{operation:'data.backup'})) as any;expect(backup.kind).toBe('backup');expect(await readdir(path.join(profile,backup.copy.relativePath))).not.toContain('security');const bytes=await readFile(path.join(profile,backup.copy.relativePath,'career.sqlite'));expect(bytes.includes(Buffer.from(fake))).toBe(false);expect(bytes.includes(cipher)).toBe(false);expect((await app.evaluate(()=>process.argv)).join(' ')).not.toContain(fake);expect(logs.join('')).not.toContain(fake);expect(logs.join('')).not.toContain(replacement);const tasks=await page.evaluate(()=>window.career.request('ai',{operation:'product.list'}));expect(JSON.stringify(tasks)).not.toContain(fake);expect(JSON.stringify(tasks)).not.toContain(replacement);
 await area.getByRole('button',{name:'删除凭据',exact:true}).click();await expect.poll(async()=>page.evaluate(()=>window.careerSecrets.request({operation:'status'}))).toMatchObject({kind:'status',status:{configured:false,enabled:false}});expect((await readdir(path.join(profile,'security'))).some(n=>n.endsWith('.encrypted'))).toBe(false);await writeFile('/tmp/career-g6/native-secret-results.json',JSON.stringify({packaged:!!exe,macOSSafeStorageEncryptDecrypt:true,writeOnlyPreload:true,inputCleared:true,providerGeneration:true,disableClosesGate:true,cancel:true,failedReplacementDoesNotFallback:true,replacement:true,delete:true,noPlaintextBusinessBackupLogsArgs:true,realProvider:'NOT TESTED'},null,2));
 }finally{await app.evaluate(({dialog})=>{dialog.showMessageBoxSync=(()=>1) as typeof dialog.showMessageBoxSync;}).catch(()=>{});await app.close().catch(()=>{});await rm(root,{recursive:true,force:true});}
},160000);
