import{it,expect}from'vitest';import{_electron}from'playwright';import{mkdtemp,writeFile,readFile,rm}from'node:fs/promises';import{spawn}from'node:child_process';import path from'node:path';import{tmpdir}from'node:os';import{randomUUID}from'node:crypto';
it('normal arm64 process uses real search helper, fails closed on corrupt pointer, reconnects after SIGKILL and preserves committed data across duplicate launch and reopen',async()=>{
 const root=await mkdtemp(path.join(tmpdir(),'career-g6-desktop-')),profile=path.join(root,'profile'),exe=process.env.CAREER_PACKAGED_EXECUTABLE;const opts={executablePath:exe,args:exe?[`--user-data-dir=${profile}`]:['.',`--user-data-dir=${profile}`],timeout:30000};let app=await _electron.launch(opts);const errors:string[]=[];
 try{let page=await app.firstWindow();await page.getByRole('navigation').waitFor();page.on('pageerror',e=>errors.push(e.message));
 const initial=await page.evaluate(()=>window.careerMaterials.ready());
 const wiki=await page.evaluate(id=>window.career.request('wiki',{operation:'create',commandId:id,title:'Desktop 牛蛙',body:'正常一字两字中文查询 controlled',scope:'personal',nature:'observation',sources:[]}),randomUUID()) as any;if(wiki.kind!=='knowledge')throw Error(JSON.stringify(wiki));
 const search=await page.evaluate(()=>window.careerSearch.request({operation:'local-search.query',owner:'wiki',query:'牛蛙',includeInactive:false}));expect(search).toMatchObject({kind:'local-search.results',items:[{title:'Desktop 牛蛙'}],partial:false});
 expect(await page.evaluate(()=>window.careerSecrets.request({operation:'status'}))).toMatchObject({kind:'status',status:{configured:false,enabled:false}});
 const pid=await app.evaluate(({app})=>app.getAppMetrics().find(value=>value.name==='Career Materials Backend')?.pid);if(!pid)throw Error('normal backend pid missing');process.kill(pid,'SIGKILL');
 await expect.poll(async()=>page.evaluate(()=>window.careerMaterials.reconnect()).catch(()=>null),{timeout:30000}).not.toBe(null);
 const reconnected=await page.evaluate(()=>window.careerMaterials.ready());expect(reconnected.workspaceInstance).toBe(initial.workspaceInstance);expect(reconnected.backendGeneration).not.toBe(initial.backendGeneration);expect(reconnected.connectionGeneration).not.toBe(initial.connectionGeneration);
 expect(await page.evaluate(()=>window.career.request('wiki',{operation:'list'}))).toMatchObject({kind:'list',items:[{title:'Desktop 牛蛙'}]});
 if(exe){const duplicate=spawn(exe,[`--user-data-dir=${profile}`],{stdio:'ignore'});const exit=await new Promise<number|null>((resolve,reject)=>{const timer=setTimeout(()=>{duplicate.kill();reject(Error('duplicate failed to exit'));},10000);duplicate.once('exit',code=>{clearTimeout(timer);resolve(code);});});expect(exit).toBe(0);expect(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().length)).toBe(1);}
 const backup=await page.evaluate(()=>window.career.request('application',{operation:'data.backup'})) as any;expect(backup.kind).toBe('backup');const pointer=await readFile(path.join(profile,'active-workspace-pointer.json'),'utf8');await app.close();app=await _electron.launch(opts);page=await app.firstWindow();await page.getByRole('navigation').waitFor();expect(await readFile(path.join(profile,'active-workspace-pointer.json'),'utf8')).toBe(pointer);expect(await page.evaluate(()=>window.career.request('wiki',{operation:'list'}))).toMatchObject({items:[{title:'Desktop 牛蛙'}]});
 await app.close();const registryFile=path.join(profile,'managed-copies-manifest.json');const copies=JSON.parse(await readFile(registryFile,'utf8'));for(const copy of copies)if(copy.kind==='backup')copy.state='failed';await writeFile(registryFile,JSON.stringify(copies));await writeFile(path.join(profile,'active-workspace-pointer.json'),'{"broken":true}');app=await _electron.launch(opts);await app.evaluate(({dialog})=>{dialog.showMessageBox=(async()=>({response:0,checkboxChecked:false})) as typeof dialog.showMessageBox;});page=await app.firstWindow();await page.getByRole('heading',{name:'资料尚未打开'}).waitFor();expect(await readFile(path.join(profile,'active-workspace-pointer.json'),'utf8')).toBe('{"broken":true}');expect(await app.evaluate(({app})=>app.getAppMetrics().some(value=>value.name==='Career Materials Backend'))).toBe(false);expect(errors).toEqual([]);
 await writeFile('/tmp/career-g6/desktop-observations.json',JSON.stringify({packaged:!!exe,realSearchHelper:true,backendSIGKILL:true,reconnect:true,duplicateLaunch:!!exe,closeReopen:true,pointerReadOnly:true,sleepWake:'NOT RUN',safeStorageEncryption:'NOT RUN',errors},null,2));
 }finally{await app.evaluate(({dialog})=>{dialog.showMessageBoxSync=(()=>1) as typeof dialog.showMessageBoxSync;}).catch(()=>{});await app.close().catch(()=>{});await rm(root,{recursive:true,force:true});}
},90000);
