import {it,expect} from 'vitest';import {_electron} from 'playwright';import {mkdtemp,writeFile,rm,readFile} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {randomUUID} from 'node:crypto';
import {tavilyPreviewDigest} from '../../packages/contracts/ai/tavily-search';
it('configured native Tavily credentials reach the formal Search resolver over the private bridge without real network',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'j07-native-bridge-')),main=path.resolve('out/CareerNext-darwin-arm64/CareerNext.app/Contents/Resources/app.asar/dist/application/main.cjs'),shim=path.join(root,'utility-shim.cjs'),entry=path.join(root,'main-shim.cjs'),trace=path.join(root,'transport-flags.json'),synthetic='J07_SYNTHETIC_BRIDGE_CREDENTIAL';
 await writeFile(shim,`const fs=require('node:fs');globalThis.fetch=async(url,options)=>{fs.writeFileSync(${JSON.stringify(trace)},JSON.stringify({recipientMatches:url==='https://api.tavily.com/search',body:options.body,keyMatches:options.headers.Authorization==='Bearer '+${JSON.stringify(synthetic)}}));return new Response(JSON.stringify({query:'OpenAI official website',results:[{title:'PUBLIC SYNTHETIC TEST',url:'https://example.invalid/',content:'Synthetic boundary result, never real acceptance.'}]}));};require(${JSON.stringify(main.replace('main.cjs','utility.cjs'))});`);
 await writeFile(entry,`const {utilityProcess}=require('electron');const original=utilityProcess.fork.bind(utilityProcess);utilityProcess.fork=(modulePath,args,options)=>original(modulePath.endsWith('/utility.cjs')?${JSON.stringify(shim)}:modulePath,args,options);require(${JSON.stringify(main)});`);
 const application=await _electron.launch({args:[entry,'--user-data-dir='+path.join(root,'profile')]});
 try{const page=await application.firstWindow();await page.getByRole('button',{name:'设置与资料维护'}).waitFor();await expect.poll(()=>page.evaluate(async()=>{try{return (await window.career.ready()).workspaceInstance;}catch{return '';}})).not.toBe('');
 const result=await page.evaluate(async({synthetic,digest,companyCommand,opportunityCommand,searchCommand})=>{const company=await window.career.request('opportunity',{operation:'company.create',commandId:companyCommand,name:'Example Corp'}) as any;const opportunity=await window.career.request('opportunity',{operation:'create',commandId:opportunityCommand,companyId:company.company.id,role:'Test Opportunity'}) as any;const saved=await window.careerTavilySecrets.request({operation:'save',value:synthetic});const owner={kind:'opportunity' as const,id:opportunity.opportunity.id};const preview=await window.careerTavilySearch.request({operation:'preview',owner});const search=await window.careerTavilySearch.request({operation:'run',owner,commandId:searchCommand,confirmed:true,previewDigest:digest as typeof tavilyPreviewDigest});return {saved,preview,search};},{synthetic,digest:tavilyPreviewDigest,companyCommand:randomUUID(),opportunityCommand:randomUUID(),searchCommand:randomUUID()});
 expect(result.saved).toMatchObject({kind:'status',status:{configured:true,enabled:true}});expect(result.preview).toMatchObject({kind:'preview',configured:true,enabled:true});expect(result.search).toMatchObject({kind:'candidate'});expect(JSON.parse(await readFile(trace,'utf8'))).toEqual({recipientMatches:true,body:'{"query":"OpenAI official website"}',keyMatches:true});expect(JSON.stringify(result)).not.toContain(synthetic);
 }finally{await application.close();await rm(root,{recursive:true,force:true});}
},30000);

it('a saved credential that Main cannot open is unavailable in the formal UI and never reaches Search transport',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'j07-native-unavailable-')),bundle=process.env.J07_PACKAGE_PATH??'out/CareerNext-darwin-arm64/CareerNext.app',main=path.resolve(bundle,'Contents/Resources/app.asar/dist/application/main.cjs'),shim=path.join(root,'utility-shim.cjs'),entry=path.join(root,'main-shim.cjs'),trace=path.join(root,'transport-flags.json');
 await writeFile(shim,`globalThis.fetch=async()=>{require('node:fs').writeFileSync(${JSON.stringify(trace)},'unexpected transport');throw Error('never send');};require(${JSON.stringify(main.replace('main.cjs','utility.cjs'))});`);
 await writeFile(entry,`const {utilityProcess,safeStorage}=require('electron');safeStorage.decryptStringAsync=async()=>{throw Error('SYNTHETIC OS DECRYPT FAILURE');};const original=utilityProcess.fork.bind(utilityProcess);utilityProcess.fork=(modulePath,args,options)=>original(modulePath.endsWith('/utility.cjs')?${JSON.stringify(shim)}:modulePath,args,options);require(${JSON.stringify(main)});`);
 const application=await _electron.launch({args:[entry,'--user-data-dir='+path.join(root,'profile')]});
 try{const page=await application.firstWindow();await page.getByRole('button',{name:'设置与资料维护'}).waitFor();await expect.poll(()=>page.evaluate(async()=>{try{return (await window.career.ready()).workspaceInstance;}catch{return '';}})).not.toBe('');
  const result=await page.evaluate(async({digest,companyCommand,searchCommand})=>{const company=await window.career.request('opportunity',{operation:'company.create',commandId:companyCommand,name:'Example Corp'}) as any;const owner={kind:'company' as const,id:company.company.id};const saved=await window.careerTavilySecrets.request({operation:'save',value:'J07_SYNTHETIC_UNAVAILABLE_CREDENTIAL'});const preview=await window.careerTavilySearch.request({operation:'preview',owner});const search=await window.careerTavilySearch.request({operation:'run',owner,commandId:searchCommand,confirmed:true,previewDigest:digest as typeof tavilyPreviewDigest});const status=await window.careerTavilySecrets.request({operation:'status'});const receipt=await window.careerTavilySearch.request({operation:'receipt'});return {saved,preview,search,status,receipt};},{digest:tavilyPreviewDigest,companyCommand:randomUUID(),searchCommand:randomUUID()});
  expect(result.saved).toMatchObject({kind:'status',status:{configured:true,enabled:true}});expect(result.preview).toMatchObject({kind:'preview',configured:true});expect(result.search).toMatchObject({kind:'failure',code:'credential_unavailable'});expect(result.status).toMatchObject({kind:'status',status:{configured:true,readiness:'unavailable',readinessReason:'decrypt_failed'}});expect(result.receipt).toMatchObject({kind:'state',state:'not_sent',requestCount:0});await expect(readFile(trace)).rejects.toThrow();expect(JSON.stringify(result)).not.toContain('J07_SYNTHETIC_UNAVAILABLE_CREDENTIAL');
  await page.getByRole('button',{name:'设置与资料维护'}).click();await page.getByRole('status').filter({hasText:'凭据已保存，但当前不可用'}).waitFor();
 }finally{await application.close();await rm(root,{recursive:true,force:true});}
},30000);
it('slow local keychain resolution is awaited by the formal private Search bridge without a false unavailable result',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'j07-slow-private-bridge-')),main=path.resolve('out/CareerNext-darwin-arm64/CareerNext.app/Contents/Resources/app.asar/dist/application/main.cjs'),shim=path.join(root,'utility-shim.cjs'),entry=path.join(root,'main-shim.cjs'),trace=path.join(root,'transport-flags.json');
 await writeFile(shim,`globalThis.fetch=async(url,options)=>{require('node:fs').writeFileSync(${JSON.stringify(trace)},JSON.stringify({calls:1,body:options.body,credentialMatches:options.headers.Authorization==='Bearer SYNTHETIC_SLOW_LOCAL_CREDENTIAL'}));return new Response(JSON.stringify({query:'OpenAI official website',results:[{title:'PUBLIC SYNTHETIC',url:'https://example.invalid/',content:'Not real acceptance.'}]}));};require(${JSON.stringify(main.replace('main.cjs','utility.cjs'))});`);
 await writeFile(entry,`const {utilityProcess,safeStorage}=require('electron');safeStorage.isAsyncEncryptionAvailable=async()=>true;safeStorage.encryptStringAsync=async()=>Buffer.from('SYNTHETIC_OPAQUE_BYTES');safeStorage.decryptStringAsync=async()=>{await new Promise(resolve=>setTimeout(resolve,16000));return {result:'SYNTHETIC_SLOW_LOCAL_CREDENTIAL'};};const original=utilityProcess.fork.bind(utilityProcess);utilityProcess.fork=(modulePath,args,options)=>original(modulePath.endsWith('/utility.cjs')?${JSON.stringify(shim)}:modulePath,args,options);require(${JSON.stringify(main)});`);
 const application=await _electron.launch({args:[entry,'--user-data-dir='+path.join(root,'profile')]});
 try{const page=await application.firstWindow();await page.getByRole('button',{name:'设置与资料维护'}).waitFor();await expect.poll(()=>page.evaluate(async()=>{try{return (await window.career.ready()).workspaceInstance;}catch{return '';}})).not.toBe('');
 const result=await page.evaluate(async({digest,create,run})=>{const company=await window.career.request('opportunity',{operation:'company.create',commandId:create,name:'Example Corp'}) as any;await window.careerTavilySecrets.request({operation:'save',value:'SYNTHETIC_SLOW_LOCAL_CREDENTIAL'});const search=await window.careerTavilySearch.request({operation:'run',commandId:run,owner:{kind:'company',id:company.company.id},confirmed:true,previewDigest:digest as typeof tavilyPreviewDigest});const status=await window.careerTavilySecrets.request({operation:'status'});return {search,status};},{digest:tavilyPreviewDigest,create:randomUUID(),run:randomUUID()});
 expect(result.status).toMatchObject({kind:'status',status:{readiness:'available'}});expect(result.search).toMatchObject({kind:'candidate'});expect(JSON.parse(await readFile(trace,'utf8'))).toEqual({calls:1,body:'{"query":"OpenAI official website"}',credentialMatches:true});expect(JSON.stringify(result)).not.toContain('SYNTHETIC_SLOW_LOCAL_CREDENTIAL');
 }finally{await application.close();await rm(root,{recursive:true,force:true});}
},40000);
