import {Modal} from '../../design-system/Modal';
import React,{useEffect,useState} from 'react';
import {Request,Result,type DataRequest,type DataResult,type PurgePlan} from '../../../contracts/application/schema';
const copyNames:Record<string,string>={current_workspace:'当前资料',old_workspace:'回退资料',restore_candidate:'待恢复资料',backup:'完整备份',failed_backup:'未完成备份',staging:'验证资料',quarantine:'隔离资料',blobs:'文件副本',proposals:'建议缓存',summaries:'摘要缓存',cache:'本地缓存'};
const stateNames:Record<string,string>={ready:'可用',candidate:'验证中',failed:'未完成',purging:'正在清除',purged:'已清除'};
interface Target {owner:string;objectId:string;label:string}
export function DataLifecycleSettings({request,targets=[],section='all'}:{section?:'backup'|'maintenance'|'all';request:(input:DataRequest)=>Promise<unknown>;targets?:Target[]}){
 const [status,setStatus]=useState<Extract<DataResult,{kind:'data_status'}>>(),[message,setMessage]=useState(''),[technical,setTechnical]=useState(''),[busy,setBusy]=useState(false),[candidate,setCandidate]=useState<Extract<DataResult,{kind:'restore_candidate'}>>(),[plan,setPlan]=useState<PurgePlan>(),[selected,setSelected]=useState<string[]>([]),[target,setTarget]=useState(''),[enabled,setEnabled]=useState(false),[hours,setHours]=useState(24),[count,setCount]=useState(14);
 async function refresh(){const result=Result.parse(await request({operation:'data.status'}));if(result.kind==='data_status'){setStatus(result);setEnabled(result.settings.enabled);setHours(result.settings.periodHours);setCount(result.settings.retainCount);}}
 useEffect(()=>{let alive=true;request({operation:'data.status'}).then(value=>{const result=Result.parse(value);if(alive&&result.kind==='data_status'){setStatus(result);setEnabled(result.settings.enabled);setHours(result.settings.periodHours);setCount(result.settings.retainCount);}}).catch(()=>{if(alive)setMessage('无法读取设置，请重试。');});return()=>{alive=false;};},[request]);
 async function run(input:DataRequest){setBusy(true);setMessage('');try{const result=Result.parse(await request(Request.parse(input)));switch(result.kind){case 'failure':setTechnical(result.code);setMessage(result.code==='purge_incomplete'?'清除尚未完成，相关内容已关闭，请先检查并完成清除。':'操作未完成，当前资料保留；请检查状态再继续。');break;case 'backup':setMessage('完整恢复点已建立。');break;case 'restore_candidate':setCandidate(result);setMessage('候选已校验；尚未切换当前资料。');break;case 'restored':setCandidate(undefined);setMessage('已切换到经过验证的新资料副本；外部服务需重新配置授权。');break;case 'purge_plan':setPlan(result.plan);setSelected(result.plan.copies.map(c=>c.id));break;case 'purged':setPlan(undefined);setMessage(result.scope==='all_managed_copies'?'选定材料及全部受管理副本已清除。':'当前选定范围已清除；未选择的副本或明确保留的独立资料仍保留。');break;case 'data_status':setMessage('备份设置已保存。');break;}await refresh();}catch{setMessage('结果暂时无法确认，请检查状态；不要重复提交。');}finally{setBusy(false);}}
 return <section aria-label="资料维护设置"><h2>{section==='maintenance'?'高级资料维护':'备份与恢复'}</h2><div hidden={section==='maintenance'}><p>备份保留当前业务资料，服务密钥与发送授权不会随资料恢复。恢复前请保存需要保留的输入。</p><p>当前使用本机资料；最近完整恢复点：{status?.lastCompleteAt??'尚无'}。</p><details><summary>查看技术详情</summary><p>资料位置：{status?.dataLocation??status?.activeWorkspace??'读取中'}</p>{technical&&<p>诊断：{technical}</p>}<ul>{status?.copies.map(copy=><li key={copy.id}>{copy.kind} · {copy.state} · {copy.relativePath}</li>)}</ul></details><fieldset disabled={busy}><legend>自动备份</legend><label className="field"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>应用运行时启用周期备份</label><label className="field">间隔小时<input aria-label="备份间隔小时" type="number" min={1} max={8760} value={hours} onChange={e=>setHours(Number(e.target.value))}/></label><label className="field">完整恢复点保留数量<input aria-label="恢复点保留数量" type="number" min={1} max={1000} value={count} onChange={e=>setCount(Number(e.target.value))}/></label><button className="button" onClick={()=>void run({operation:'data.settings',settings:{enabled,periodHours:hours,retainCount:count}})}>保存备份设置</button><p>默认每天检查、保留 14 个完整恢复点；启用后生效。应用退出期间没有备份，启动仅补一个需要的恢复点。</p><button className="button" onClick={()=>void run({operation:'data.backup'})}>立即建立备份</button></fieldset>
 {Boolean(status?.pendingPurgeCount)&&<p role="alert">有尚未完成的永久清除。相关内容与迟到写回已关闭；备份和恢复暂不可用，需先完成原清除。</p>}<p>这里是当前资料的普通备份 / 恢复，不是旧 Career 迁移。</p><h3>可用备份与回退资料</h3><ul>{status?.copies.filter(copy=>['backup','failed_backup','old_workspace'].includes(copy.kind)).map(copy=><li key={copy.id}>{copyNames[copy.kind]??'资料副本'} · {stateNames[copy.state]??'待检查'} · {copy.createdAt}{copy.kind==='backup'&&copy.state==='ready'&&<button className="button" disabled={busy} onClick={()=>void run({operation:'data.restore.prepare',backupId:copy.id})}>检查并准备恢复</button>}</li>)}</ul>
 {candidate&&<Modal label="确认恢复" busy={busy} onCancel={()=>setCandidate(undefined)}><p>候选完整性已验证。恢复将切换当前资料到这份已验证副本（{candidate.copy.createdAt}），旧资料保留为受管理回退副本；AI 执行权与凭据不会恢复。未保存的编辑将被清空，请先保存需要保留的内容。</p>{Boolean(candidate.purgeWarnings.length)&&<div role="alert"><p>这个明确保留的旧备份可能带回此前已在当前选定范围清除的内容。此次确认恢复将允许重新打开它们，请先核对：</p><ul>{candidate.purgeWarnings.map(ref=><li key={ref.owner+':'+ref.objectId}>{targets.find(t=>t.owner===ref.owner&&t.objectId===ref.objectId)?.label??'此前清除的关联资料'}</li>)}</ul></div>}<button className="button" disabled={busy} onClick={()=>void run({operation:'data.restore.activate',candidateId:candidate.copy.id,confirmed:true})}>确认切换资料</button><button className="button" data-dialog-cancel disabled={busy} onClick={()=>setCandidate(undefined)}>暂不恢复</button></Modal>}
 </div><div hidden={section==='backup'}><h3>永久清除</h3><p>永久清除会删除选定内容及派生残留，与归档、纠错不同。外部收件方、用户下载/发送文件、系统快照不能承诺撤回。</p><label className="field">要清除的材料<select aria-label="要清除的材料" value={target} onChange={e=>setTarget(e.target.value)}><option value="">请选择</option>{targets.map((t,i)=><option key={t.owner+':'+t.objectId} value={String(i)}>{t.label}</option>)}</select></label><button className="button" disabled={busy||target===''} onClick={()=>{const t=targets[Number(target)];if(t)void run({operation:'data.purge.plan',references:[{owner:t.owner,objectId:t.objectId}]});}}>查看清除影响</button>
 {plan&&<Modal label="永久清除影响确认" busy={busy} onCancel={()=>setPlan(undefined)}><p>{plan.impact.description}</p><ul aria-label="本次清除对象">{plan.impact.references.map(ref=><li key={ref.owner+ref.objectId}>{targets.find(t=>t.owner===ref.owner&&t.objectId===ref.objectId)?.label??'关联资料（可查看技术详情）'}</li>)}</ul><p>独立对象/冻结历史保留关系：{plan.impact.independentReferences.join('；')||'无'}</p><p>{plan.externalLimit}</p><p>选择备份或旧资料副本会删除该完整副本；未选择的副本仍可能保留内容。</p>{plan.copies.map(copy=><label key={copy.id}><input type="checkbox" checked={selected.includes(copy.id)} onChange={e=>setSelected(old=>e.target.checked?[...old,copy.id]:old.filter(id=>id!==copy.id))}/>{copyNames[copy.kind]??'资料副本'} · {copy.createdAt} · {stateNames[copy.state]??'待检查'}</label>)}<button className="button" disabled={busy} onClick={()=>void run({operation:'data.purge.confirm',planId:plan.id,selectedCopyIds:selected,confirmed:true})}>确认永久清除选定范围</button><button className="button" data-dialog-cancel disabled={busy} onClick={()=>setPlan(undefined)}>取消</button></Modal>}
 </div><button className="button" disabled={busy} onClick={()=>void refresh().catch(()=>setMessage('暂时无法刷新，请稍后再试；没有重复提交。'))}>刷新备份状态</button><p role="status">{busy?'正在维护；完成前请勿关闭应用。':message}</p></section>;
}
