import type {AiPorts,SourceSnapshot,WikiSnapshot} from '../ai-runtime/ports';
import type {Target,Provenance} from '../../contracts/ai/schema';
import type {SourceRef} from '../../contracts/common/source-ref';
import type {composeDomains} from './domain-registry';
import type {Store} from '../domains/materials/store';
import type {PersistenceFence} from '../platform/persistence/fence';
import {readArtifact} from '../platform/files/protected-original';
export function composeAiPorts(domains:ReturnType<typeof composeDomains>,materials:Store,root:string,identity:AiPorts['identity'],fence:PersistenceFence,humanAllowed:()=>boolean):AiPorts{
 const knownRefs=new Map<string,SourceRef>();
 const validateTarget=(target:Target)=>{if(['personal','cognition'].includes(target.scope))return !target.scopeId;const id=target.scopeId;if(!id)return false;if(target.scope==='opportunity')return !!domains.opportunity.capabilities.readOpportunity(id);if(target.scope==='project')return domains.project.handle({operation:'read',id}).kind==='project';if(target.scope==='employment')return !!domains.employment.resolveEmployment(id);const all=domains.employment.handle({operation:'list'});return all.kind==='list'&&all.employments.some(e=>!!domains.employment.resolvePerson(id,e.id));};
 function source(ref:SourceRef,current=false):SourceSnapshot|undefined{knownRefs.set(ref.owner+'/'+ref.objectId,ref);const metadata=domains.resolveSource(ref);if(!metadata)return undefined;const actual=current?metadata.source:ref;if(!current&&metadata.revision!==ref.revision)return undefined;let body:string|undefined,nature='real_correctable_record';
 if(actual.owner==='materials'){const artifact=materials.resolveSourceArtifact(actual);const bytes=artifact&&readArtifact(root,artifact);if(bytes)body=new TextDecoder('utf8',{fatal:true}).decode(bytes);nature='evidence-original';}
 else if(actual.owner==='interview'){const value=domains.interview.resolveTranscript(actual);body=value?.text;nature=value?.nature??nature;}
 else {const value=domains.communication.resolveSource(actual);if(value.status==='available')body=value.text;}
 if(body===undefined)return undefined;return {ref:actual,body,nature,restrictions:{read:true,egress:true},provenance:[{owner:actual.owner,objectId:actual.objectId,revision:actual.revision,scope:actual.scope,...(actual.owner!=='materials'?{scopeId:actual.opportunityId}:{}),kind:nature,restrictions:{read:true,egress:true}}]};}
 function snapshot(id:string):WikiSnapshot|undefined{const item=domains.wiki.read(id);if(!item)return undefined;const provenance:Provenance[]=[...(item.trustedProvenance??[]),{owner:'wiki',objectId:id,revision:item.revision,scope:item.scope,...(item.scopeId?{scopeId:item.scopeId}:{}),kind:item.origin==='ai_accepted'?'ai_accepted':'user_record',restrictions:{read:true,egress:true}}];for(const support of item.sources){const value=source(support.ref);if(!value)return {...item,provenance:[...provenance,{owner:support.ref.owner,objectId:support.ref.objectId,revision:support.ref.revision,scope:support.ref.scope,kind:'unavailable',restrictions:{read:false,egress:false}}]};provenance.push(...value.provenance);}return {...item,provenance};}
 return {identity,fence,humanAllowed,sources:{read:ref=>source(ref),current:ref=>source(ref,true),provenanceCurrent(input){if(input.owner==='wiki'){const item=domains.wiki.read(input.objectId);return item?{revision:item.revision,read:true,egress:true}:undefined;}const allRef=input.owner==='materials'?{owner:'materials',objectId:input.objectId,revision:input.revision,locator:'whole',scope:'personal'}:undefined;if(allRef){const value=source(allRef as SourceRef,true);return value?{revision:value.ref.revision,...value.restrictions}:undefined;}
 // Correctable source metadata requires its actual scope, not a guessed global resolver.
 const taskRef=input.scopeId&&['interview','communication'].includes(input.owner)?{owner:input.owner,objectId:input.objectId,revision:input.revision,locator:input.owner==='interview'?'transcript':'text',scope:'opportunity',opportunityId:input.scopeId} as SourceRef:knownRefs.get(input.owner+'/'+input.objectId);const value=taskRef&&source(taskRef,true);return value?{revision:value.ref.revision,...value.restrictions}:undefined;}},wiki:{validateTarget,list(target){return domains.wiki.maintenanceObjects(target.scope,target.scopeId).filter(item=>domains.wiki.read(item.id)?.status==='active').map(item=>snapshot(item.id)!).filter(Boolean);},read:snapshot,apply(input){const change=input.change,content=input.edited??('content'in change?change.content:undefined);const sources=input.sources.map(ref=>({ref,purpose:'实际任务输入'}));if(change.kind==='retire'){const old=domains.wiki.read(change.itemId);if(!old)throw Error('target_unavailable');domains.wiki.applyProposal({operation:'lifecycle',commandId:input.commandId,id:old.id,expectedRevision:old.revision,action:'retire',correction:false,reason:change.reason,businessTime:{kind:'unknown'}},input.provenance);return;}if(!content)throw Error('invalid_output');const common={commandId:input.commandId,...content,...input.target,sources};if(change.kind==='create')domains.wiki.applyProposal({operation:'create',...common},input.provenance);else {const old=domains.wiki.read(change.itemId);if(!old||old.revision!==input.before?.revision)throw Error('conflict');domains.wiki.applyProposal({operation:'edit',...common,id:old.id,expectedRevision:old.revision,change:'corrected',reason:change.reason,businessTime:{kind:'unknown'}},input.provenance);}}}};
 // Owner metadata is remembered only as a locator, never as independent content or authority.
}
