import {composeFeedback} from './feedback-composition';
import type Database from 'better-sqlite3';
import {SourceRef} from '../../contracts/common/source-ref';
import { createEmploymentDomain } from '../domains/employment/public';
import { createProjectDomain } from '../domains/project/public';
import { createOpportunityDomain } from '../domains/opportunity/public';
import { createProfileDomain } from '../domains/profile/public';
import { createResumeDomain } from '../domains/resume/public';
import { createWikiDomain } from '../domains/wiki/public';
import type { Store } from '../domains/materials/store';
import { Result as ResumeResult,Request as ResumeRequest } from '../../contracts/resume/schema';
import {printingMetadata} from './printing-metadata';
import { registerDomains } from './generated/routing';
import path from 'node:path';
import {createResearchDomain} from '../domains/opportunity/research/public';
import {createInterviewDomain} from '../domains/opportunity/interview/public';
import {createOfferDomain} from '../domains/opportunity/offer/public';
import {createLedger} from '../platform/database/ledger';
import {createSubmissionDomain} from '../domains/opportunity/submission/public';
import {createCommunicationDomain} from '../domains/opportunity/communication/public';
import {createFileCandidates} from '../platform/files/candidates';
import {verifyArtifact,verifyProtectedOriginal} from '../platform/files/protected-original';
export function composeDomains(db:Database.Database,materials:Store,extra:{ai:{handle(input:unknown):unknown};application:{handle(input:unknown):unknown}}){
 const employment=createEmploymentDomain(db);
 const project=createProjectDomain(db,{resolveEmployment:employment.resolveEmployment,resolvePerson:employment.resolvePerson});
 const opportunity=createOpportunityDomain(db);
 const root=path.dirname(db.name),ledger=createLedger(db),feedback=composeFeedback(db,root);
 const artifact=(ref:Parameters<Store['resolveSourceArtifact']>[0])=>{const value=materials.resolveSourceArtifact(ref);return value&&verifyProtectedOriginal(root,value)?value:undefined;};
 const profile=createProfileDomain(db);
 const resume=createResumeDomain(db,{resolveOpportunity:opportunity.resolveOpportunity,profile});
 const files=createFileCandidates(db,root);
 const sent={core:opportunity.capabilities,resolveFrozenResume:(id:string)=>{const value=resume.resolveFrozenVersion(id);return value&&verifyArtifact(root,value.pdf,16*1024*1024)?{name:value.name||'未命名导出.pdf',snapshot:value.snapshot,pdf:value.pdf}:undefined;},resolveActualArtifact:files.read,retainExisting:(blobId:string,owner:'submission'|'communication',id:string)=>ledger.retainExisting(blobId,id,owner),releaseRetention:(owner:'submission'|'communication',id:string)=>ledger.releaseRetention(owner,id)};
 const submission=createSubmissionDomain(db,sent);
 const communication=createCommunicationDomain(db,{...sent,hasFirstSubmission:submission.hasFirstSubmission});
 const interview=createInterviewDomain(db,{core:opportunity.capabilities});
 const resolveSource=(ref:import('../../contracts/common/source-ref').SourceRef)=>ref.owner==='materials'?(artifact(ref)?materials.resolveSourceMetadata(ref):undefined):ref.owner==='interview'?interview.resolveTranscript(ref)?.metadata:communication.resolveSourceMetadata(ref);
 const wiki=createWikiDomain(db,{resolveSource,resolveProvenance(input){const parsed=SourceRef.safeParse(input.owner==='materials'?{owner:input.owner,objectId:input.objectId,revision:input.revision,locator:'whole',scope:input.scope}:{owner:input.owner,objectId:input.objectId,revision:input.revision,locator:input.owner==='interview'?'transcript':'text',scope:input.scope,opportunityId:input.scopeId});return parsed.success?resolveSource(parsed.data):undefined;},validateScope:(scope,id)=>{if(!id)return scope==='personal'||scope==='cognition';if(scope==='opportunity')return !!opportunity.capabilities.readOpportunity(id);if(scope==='employment')return !!employment.resolveEmployment(id);if(scope==='project')return project.handle({operation:'read',id}).kind==='project';if(scope==='person'){const all=employment.handle({operation:'list'});return all.kind==='list'&&all.employments.some(e=>!!employment.resolvePerson(id,e.id));}return false;}});
 const research=createResearchDomain(db,{core:opportunity.capabilities,resolveSource:ref=>{const current=resolveSource(ref);return current?{ref:current.source,status:current.revision===ref.revision?'readable':'stale',scope:ref.owner==='materials'?{kind:'personal'}:{kind:'opportunity',id:ref.opportunityId}}:undefined;}});
 const offer=createOfferDomain(db,{core:opportunity.capabilities,validateSource:ref=>{const value=artifact(ref);return value?{status:'available',name:value.name,digest:value.digest}:{status:'unavailable'};},releaseRetention:id=>ledger.releaseRetention('offer',id),retainSource:(ref,id)=>{const value=artifact(ref);if(!value)throw Error('source_unavailable');ledger.retainExisting(value.blobId,id,'offer');}});
 const metadata=printingMetadata();
 const printedResume={handle(input:unknown){const request=ResumeRequest.parse(input);return (request.operation==='resume.name-version'||request.operation==='resume.export')?resume.prepareVersion(request,metadata):resume.handle(request);}};
 const handle=registerDomains({wiki,employment,project,opportunity,profile,resume:printedResume,research,interview,offer,submission,communication,...extra});
 return {handle,resume,wiki,employment,project,opportunity,research,interview,offer,profile,submission,communication,feedback,files,resolveSource,pendingPrint(commandId:string){const result=ResumeResult.parse(resume.handle({operation:'resume.receipt',commandId}));if(result.status!=='pending-job')return undefined;return result.job;}};
}
