import type Database from 'better-sqlite3';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {maintenanceTargets} from './maintenance-targets';
import type {HumanSession} from '../platform/runtime/sessions';
import {createDataLifecycle} from '../application/data-lifecycle/public';
import {createLedger} from '../platform/database/ledger';
import type {PersistenceFence,PersistenceReference} from '../platform/persistence/fence';
import type {composeDomains} from './domain-registry';
import type {Store} from '../domains/materials/store';
import {sanitizeAiCandidate,type createAiRuntime} from '../ai-runtime/public';
import type {PurgeImpact} from '../../contracts/application/schema';
export interface LifecycleControl {drain(refs:readonly PersistenceReference[]):Promise<void>;beforeActivate():Promise<void>;maintenance<T>(work:()=>Promise<T>):Promise<T>;closeWorkspace():void;}
export function composeLifecycle(db:Database.Database,domains:ReturnType<typeof composeDomains>,materials:Store,fence:PersistenceFence,ai:ReturnType<typeof createAiRuntime>,root:string,dataRoot:string,control:LifecycleControl,currentHuman:()=>HumanSession|undefined){
 const ledger=createLedger(db);
 type Impact={id:string;revision?:number;name?:string;blobIds:string[];retentions?:{owner:string;objectId:string}[];retentionIds?:string[];producerIds?:string[];relatedIds?:string[]};
 type Owner={purgeImpact?(id:string):Impact|undefined;describePurge?(id:string):Impact|undefined;purge(id:string):void};
 const owners:Record<string,Owner>={materials,wiki:domains.wiki,research:domains.research,interview:domains.interview,resume:domains.resume,submission:domains.submission,communication:domains.communication,'actual-artifact':domains.files,company:{purgeImpact:domains.opportunity.companyPurgeImpact,purge:domains.opportunity.purgeCompany},profile:domains.profile,project:domains.project,employment:domains.employment,person:{purgeImpact:domains.employment.personPurgeImpact,purge:domains.employment.purgePerson},offer:domains.offer,opportunity:domains.opportunity};
 function items(refs:readonly PersistenceReference[]){return refs.map(ref=>{const owner=owners[ref.owner];if(!owner)throw Error('purge_owner_unavailable');const item=owner.purgeImpact?.(ref.objectId)??owner.describePurge?.(ref.objectId);if(!item)throw Error('not_found');const retentions=item.retentions??(item.retentionIds??[]).map(objectId=>({owner:ref.owner,objectId}));return {ref,owner,item,retentions};});}
 async function impact(refs:readonly PersistenceReference[]):Promise<PurgeImpact>{const selected=items(refs);for(const i of selected)for(const producer of i.item.producerIds??[]){const held=ledger.heldArtifact('resume.version/'+producer);if(held)i.item.blobIds.push(held.id);}const references=selected.flatMap(({ref,item})=>[ref,...(ref.owner==='employment'?(item.relatedIds??[]).map(objectId=>({owner:'person',objectId})):[])]);const deleting=selected.flatMap(i=>i.retentions),blobs=[...new Set([...selected.flatMap(i=>i.item.blobIds),...ledger.retainedArtifacts().filter(blob=>ledger.retentionReasons(blob.id).some(r=>deleting.some(d=>d.owner===r.owner&&d.objectId===r.objectId))).map(blob=>blob.id)])],independentReferences:string[]=[];const files:string[]=[];
 for(const blobId of blobs){const keep=ledger.retentionReasons(blobId).filter(reason=>!deleting.some(d=>d.owner===reason.owner&&d.objectId===reason.objectId));if(keep.length)independentReferences.push(...keep.map(r=>`${r.owner}/${r.objectId} 保留独立历史材料`));else files.push('blobs/'+blobId);}
 for(const {ref,item} of selected){for(const related of domains.wiki.referencing(ref))if(!references.some(r=>r.owner==='wiki'&&r.objectId===related.id))independentReferences.push(`wiki/${related.id} 保留原结论并待复核`);for(const related of domains.research.referencing(ref))if(!references.some(r=>r.owner==='research'&&r.objectId===related.id))independentReferences.push(`research/${related.id} 保留原结论并待复核`);for(const id of item.producerIds??[])files.push('staging/'+id);for(const id of item.blobIds)files.push('staging/publish-'+id);}
 const dependencies=createHash('sha256').update(JSON.stringify(selected.map(({ref,item,retentions})=>({ref,item:{revision:item.revision,blobIds:item.blobIds,producerIds:item.producerIds},retentions,holds:item.blobIds.map(id=>ledger.retentionReasons(id))})))).digest('hex');return {references:references.map(({owner,objectId})=>({owner,objectId})),description:`永久清除 ${selected.length} 个已选择对象的正文、历史和受影响 AI 中间结果；独立业务结论与独立发送历史按下列范围保留。`,independentReferences:[...new Set(independentReferences)],files:[...new Set(files)],dependencies};}
 return createDataLifecycle({root:dataRoot,getActiveRoot:()=>root,maintenance:control.maintenance,impact,targets:()=>maintenanceTargets(domains,materials,currentHuman()),
 markPurge:async refs=>{db.transaction(()=>fence.markPurge(refs))();},drain:control.drain,
 purge:async plan=>{db.transaction(()=>{for(const ref of plan.references){const owner=owners[ref.owner];if(!owner)throw Error('purge_owner_unavailable');const item=owner.purgeImpact?.(ref.objectId)??owner.describePurge?.(ref.objectId);if(item){for(const producer of item.producerIds??[])ledger.fail('resume.version/'+producer,'invalid_capability');const retentions=item.retentions??(item.retentionIds??[]).map(objectId=>({owner:ref.owner,objectId}));for(const r of retentions)ledger.releaseRetention(r.owner,r.objectId);}owner.purge(ref.objectId);}ai.purgeByReferences(plan.references.map(ref=>ref.objectId));})();},
 compact:async()=>{db.pragma('wal_checkpoint(TRUNCATE)');db.exec('VACUUM');db.pragma('wal_checkpoint(TRUNCATE)');},
 sanitizeCandidate(candidate){sanitizeAiCandidate(candidate);candidate.prepare('DELETE FROM platform_file_candidates WHERE status=?').run('pending');candidate.prepare("DELETE FROM platform_artifact_holds").run();candidate.prepare("DELETE FROM platform_artifact_retention WHERE owner='actual-artifact' AND object_id NOT IN(SELECT id FROM platform_file_candidates)").run();candidate.prepare("UPDATE platform_artifact_receipts SET status='failed',error='invalid_capability' WHERE status='pending'").run();},
 validateRelations(candidate){if(candidate.pragma('user_version',{simple:true})!==4)throw Error('backup_schema_invalid');if((candidate.pragma('foreign_key_check') as unknown[]).length)throw Error('backup_incomplete');},
 beforeActivate:control.beforeActivate,async activate(input){control.closeWorkspace();input.commitPointer();},
 });
}
