import {useEffect,useState,useRef} from 'react';
import {Request,Result,type Profile} from '../../../contracts/profile/schema';
const call=async(input:Request)=>Result.parse(await window.career.request('profile',input));
export function ProfileSettings({onSaved,purgeNotice}:{onSaved():void;purgeNotice?:import('../../design-system/purge-notice').PurgeNotice}){
 const [profile,setProfile]=useState<Profile>(),[draft,setDraft]=useState<Profile>(),[comparison,setComparison]=useState<Profile>(),[pending,setPending]=useState<Extract<Request,{operation:'profile.save'}>>(),[mayContinue,setMayContinue]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('正在读取基础资料…');
 const dirty=!!draft&&JSON.stringify(draft)!==JSON.stringify(profile);
 const readEpoch=useRef(0),alive=useRef(true);
 async function refresh(){const ticket=++readEpoch.current;setBusy(true);try{const value=await call({operation:'profile.read'});if(!alive.current||ticket!==readEpoch.current)return;if(value.status==='profile'){setProfile(value.profile);setDraft(value.profile);setNotice('');}else setNotice('基础资料暂时无法读取。');}catch{if(alive.current&&ticket===readEpoch.current)setNotice('基础资料暂时无法读取。');}finally{if(alive.current&&ticket===readEpoch.current)setBusy(false);}}
 useEffect(()=>{alive.current=true;void refresh();return()=>{alive.current=false;readEpoch.current++;};},[]);
 useEffect(()=>{if(!purgeNotice?.references.some(ref=>ref.owner==='profile'))return;readEpoch.current++;setProfile(undefined);setDraft(undefined);setComparison(undefined);setPending(undefined);setMayContinue(false);void refresh();},[purgeNotice?.sequence]);
 useEffect(()=>{if(!dirty&&!pending)return;const protect=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue='';};window.addEventListener('beforeunload',protect);return()=>window.removeEventListener('beforeunload',protect);},[dirty,pending]);
 async function send(input:Request){const ticket=readEpoch.current;setBusy(true);setMayContinue(false);try{const value=await call(input);if(!alive.current||ticket!==readEpoch.current)return;if(value.status==='profile'){setProfile(value.profile);setDraft(value.profile);setPending(undefined);setComparison(undefined);setNotice('基础资料已保存，所有当前简历会同步。');onSaved();}else if(value.status==='conflict'){setComparison(value.profile);setPending(undefined);setNotice('基础资料已在其他地方更新。你的输入还在，请比较后决定。');}else if(value.status==='not-found'){setMayContinue(true);setNotice('已经确认这次保存尚未完成，可以继续保存。');}else{setPending(undefined);setNotice('保存未完成，请检查输入后再保存。');}}catch{if(alive.current&&ticket===readEpoch.current)setNotice('暂时无法确认是否保存。你的输入还在，请先检查保存结果。');}finally{if(alive.current&&ticket===readEpoch.current)setBusy(false);}}
 if(!profile||!draft)return <section><h3>我的基础资料</h3><p role="status">{notice}</p><button disabled={busy} onClick={()=>void refresh()}>刷新</button></section>;
 return <section aria-label="我的基础资料"><h3>我的基础资料</h3><p>姓名、联系方式等基础资料会同步到所有当前简历。历史命名版本继续保留创建时的资料。</p><form className="form" onSubmit={event=>{event.preventDefault();const input=Request.safeParse({operation:'profile.save',commandId:crypto.randomUUID(),expectedRevision:profile.revision,name:draft.name,contact:draft.contact,links:draft.links});if(!input.success||input.data.operation!=='profile.save'){setNotice('请检查姓名、联系方式和网页链接。');return;}setPending(input.data);void send(input.data);}}><fieldset disabled={busy||!!pending}><label className="field">姓名<input maxLength={120} value={draft.name} onChange={event=>setDraft({...draft,name:event.target.value})}/></label><label className="field">联系方式<input maxLength={500} value={draft.contact} onChange={event=>setDraft({...draft,contact:event.target.value})}/></label>{draft.links.map((link,index)=><div key={index}><label className="field">网页名称 {index+1}<input value={link.label} onChange={event=>setDraft({...draft,links:draft.links.map((item,i)=>i===index?{...item,label:event.target.value}:item)})}/></label><label className="field">网页地址 {index+1}<input value={link.href} onChange={event=>setDraft({...draft,links:draft.links.map((item,i)=>i===index?{...item,href:event.target.value}:item)})}/></label><button type="button" onClick={()=>setDraft({...draft,links:draft.links.filter((_,i)=>i!==index)})}>移除网页 {index+1}</button></div>)}<button type="button" disabled={draft.links.length>=20} onClick={()=>setDraft({...draft,links:[...draft.links,{label:'',href:''}]})}>添加个人网页</button><button className="button primary" type="submit">保存基础资料</button></fieldset></form><p role="status">{notice}{dirty?' · 有未保存输入':''}</p>{pending&&<button disabled={busy} onClick={()=>void send({operation:'profile.receipt',commandId:pending.commandId})}>检查是否已保存</button>}{pending&&mayContinue&&<button disabled={busy} onClick={()=>void send(pending)}>继续保存</button>}{comparison&&<aside><p>当前保存的基础资料：{comparison.name} / {comparison.contact}</p><button onClick={()=>{setProfile(comparison);setComparison(undefined);}}>保留输入，采用最新资料作为保存基线</button><button onClick={()=>{setProfile(comparison);setDraft(comparison);setComparison(undefined);}}>放弃本地修改，使用已保存资料</button></aside>}</section>;
}
