import {Dependency,ProductTarget,ProductContext} from './product-context.ts';
import {z} from 'zod';
import {SourceRef} from '../common/source-ref.ts';
import {Provenance} from '../common/provenance.ts';
import {Target,Content,Recipient,Budget,OperationState} from './protocol.ts';
const Before=Content.extend({id:z.uuid(),revision:z.number().int().positive()}).strict();
export const Manifest=z.object({product:ProductContext.optional(),taskId:z.uuid(),target:Target,recipient:Recipient,granularity:z.literal('fulltext'),system:z.string().max(2000),tools:z.tuple([]),materials:z.array(z.object({ref:SourceRef,body:z.string().max(262144),nature:z.string().max(80)}).strict()).max(20),knowledge:z.array(Before).max(500),budget:Budget,validity:z.object({workspaceInstance:z.string().min(1),backendGeneration:z.string().min(1),expiresAt:z.iso.datetime()}).strict(),stopBoundary:z.literal('before-handoff'),provenance:z.array(Provenance).max(1000)}).strict();
export type Manifest=z.infer<typeof Manifest>;
export const Operation=z.object({productTarget:ProductTarget.optional(),productTargets:z.array(z.strictObject({owner:z.string().max(80),objectId:z.string().max(160)})).max(1000).optional(),productDependencies:z.array(Dependency).max(1000).optional(),id:z.uuid(),taskId:z.uuid(),state:OperationState,manifestDigest:z.string().regex(/^[a-f0-9]{64}$/),manifest:Manifest.optional(),provenance:z.array(Provenance).max(1000),recipient:Recipient,reserved:Budget,actualOutputBytes:z.number().int().nonnegative().optional(),reason:z.string().max(500).optional(),authorized:z.boolean()}).strict();
export type Operation=z.infer<typeof Operation>;
