import type Database from 'better-sqlite3';
import {createHash} from 'node:crypto';
import {ProductTask,ProductProposal} from '../../../contracts/ai/product';
import {Operation} from '../../../contracts/ai/schema';
import {redactedCommandResults} from '../../platform/commands/receipts';
const TaskRecord=ProductTask.omit({operations:true,proposals:true});
export function validateProductCandidate(db:Database.Database){try{
 const tasks=new Map<string,ReturnType<typeof TaskRecord.parse>>(),operations=new Map<string,Operation>(),counts=new Map<string,number>();
 for(const row of db.prepare('SELECT id,data_json FROM ai_product_tasks').all() as {id:string;data_json:string}[]){const task=TaskRecord.parse(JSON.parse(row.data_json));if(task.id!==row.id||task.usedRequests>task.budget.requests||task.state==='purged'&&task.input||task.state!=='purged'&&!task.input||task.input&&task.policy!==task.input.target.kind)throw Error();tasks.set(row.id,task);}
 for(const row of db.prepare('SELECT id,task_id,data_json FROM ai_product_operations').all() as {id:string;task_id:string;data_json:string}[]){const raw=JSON.parse(row.data_json),op=Operation.parse(raw),task=tasks.get(row.task_id);if(!task||op.id!==row.id||op.taskId!==row.task_id||op.reserved.requests!==1||op.reserved.inputBytes>task.budget.inputBytes||op.reserved.outputBytes>task.budget.outputBytes||op.actualOutputBytes!==undefined&&op.actualOutputBytes>op.reserved.outputBytes)throw Error();const count=(counts.get(task.id)??0)+1;counts.set(task.id,count);if(count>20||task.state==='purged'&&(op.manifest||op.authorized||op.provenance.length)||task.state!=='purged'&&JSON.stringify(op.productTarget)!==JSON.stringify(task.input!.target))throw Error();if(raw.manifest&&(createHash('sha256').update(JSON.stringify(raw.manifest)).digest('hex')!==op.manifestDigest||op.manifest!.taskId!==task.id||JSON.stringify(op.manifest!.product?.target)!==JSON.stringify(task.input!.target)||JSON.stringify(op.manifest!.provenance)!==JSON.stringify(op.provenance)||JSON.stringify(op.manifest!.product?.dependencies)!==JSON.stringify(op.productDependencies)))throw Error();operations.set(row.id,op);}
 for(const task of tasks.values())if(!counts.has(task.id)&&task.state!=='purged')throw Error();
 const proposalCounts=new Map<string,number>();
 for(const row of db.prepare('SELECT id,task_id,operation_id,data_json FROM ai_product_proposals').all() as {id:string;task_id:string;operation_id:string;data_json:string}[]){const proposal=ProductProposal.parse(JSON.parse(row.data_json)),task=tasks.get(row.task_id),op=operations.get(row.operation_id);if(!task||!op||proposal.id!==row.id||proposal.taskId!==task.id||proposal.operationId!==op.id||op.taskId!==task.id||task.state==='purged'||op.state!=='success'||JSON.stringify(proposal.target)!==JSON.stringify(task.input!.target)||JSON.stringify(proposal.provenance)!==JSON.stringify(op.provenance)||proposal.state==='accepted'&&!proposal.receiptId||proposal.dependencies.some(dep=>!op.productDependencies?.some(expected=>JSON.stringify(dep)===JSON.stringify(expected)))||proposal.change.citations.some(id=>!op.provenance.some(p=>p.objectId===id)&&!((proposal.change.kind==='resume-block'||proposal.change.kind==='resume-delete')&&proposal.change.blockId===id||proposal.change.kind==='resume-add'&&proposal.change.afterBlockId===id)))throw Error();const count=(proposalCounts.get(task.id)??0)+1;proposalCounts.set(task.id,count);if(count>400)throw Error();}
 }catch{throw Error('backup_product_ai_invalid');}}
export function productCandidateRelations(db:Database.Database){validateProductCandidate(db);const relations:{owner:string;objectId:string;kind:'object';revision?:number;provenance?:Operation['provenance'][number];optional?:boolean}[]=[];
 for(const row of db.prepare('SELECT data_json FROM ai_product_operations').all() as {data_json:string}[]){const op=Operation.parse(JSON.parse(row.data_json));if(!op.provenance.length)continue;for(const provenance of op.provenance)relations.push({owner:provenance.owner,objectId:provenance.objectId,kind:'object',revision:provenance.revision,provenance});for(const target of op.productTargets??[])relations.push({owner:target.owner,objectId:target.objectId,kind:'object'});for(const dep of op.productDependencies??[])relations.push({owner:dep.owner,objectId:dep.objectId,kind:'object',revision:dep.revision,optional:dep.owner==='communication-draft'&&dep.revision===0});}
 return relations;
}
export function sanitizeProductCandidate(db:Database.Database){for(const row of db.prepare('SELECT id,data_json FROM ai_product_operations').all() as {id:string;data_json:string}[]){const op=Operation.parse(JSON.parse(row.data_json));op.authorized=false;delete op.manifest;if(['dispatching','processing'].includes(op.state)){op.state='outcome_unknown';op.reason='restored_handoff_unconfirmed';}db.prepare('UPDATE ai_product_operations SET data_json=?,fence_json=? WHERE id=?').run(JSON.stringify(op),'{}',row.id);}redactedCommandResults(db,'ai.product',result=>(result as {kind:string}).kind==='product_task',{kind:'failure',code:'historical_receipt_body_unavailable'});}
