import {useEffect,useRef,useState} from 'react';
import {Request,Result,type Item,type Owner,type Source,type Resolution} from '../../../../contracts/opportunity/research/schema';
import type {BusinessTime} from '../../../../contracts/common/business-time';
import type {SourceRef} from '../../../../contracts/materials/schema';
export interface ResearchPageProps{opportunityId:string;companyId:string;workspaceInstance:string;request:(input:Request)=>Promise<Result>;onChanged?:()=>void;availableSources?:{ref:SourceRef;name:string}[];}
type Draft={title:string;body:string;nature:Item['nature'];sources:Source[];leads:Item['leads'];userConfirmed:boolean;independentlyVerified:boolean;reason:string;reevaluated:boolean;timeKind:BusinessTime['kind'];date:string;instant:string;timezone:string;};
const empty=():Draft=>({title:'',body:'',nature:'fact_statement',sources:[],leads:[],userConfirmed:false,independentlyVerified:false,reason:'',reevaluated:false,timeKind:'unknown',date:'',instant:'',timezone:''});
type Session={owner:Owner;items:Resolution[];references:{itemId:string;originRevision:number;owner:Owner;originOwner:Owner}[];docRevision:number;selected?:Item;draft:Draft;dirty:boolean;status:string;pending?:Request;busy:boolean;server?:Item;companyComparison?:Resolution[];history?:string[];loaded:boolean;readEpoch:number;};
export function ResearchPage({opportunityId,companyId,workspaceInstance,request,onChanged,availableSources=[]}:ResearchPageProps){
 const [scope,setScope]=useState<'opportunity'|'company'>('opportunity');const sessions=useRef(new Map<string,Session>());const [,refresh]=useState(0);const render=()=>refresh(v=>v+1);
 const owner:Owner={kind:scope,id:scope==='company'?companyId:opportunityId};const key=workspaceInstance+':'+owner.kind+':'+owner.id;
 if(!sessions.current.has(key))sessions.current.set(key,{owner,items:[],references:[],docRevision:0,draft:empty(),dirty:false,status:'正在读取',busy:false,loaded:false,readEpoch:0});
 const s=sessions.current.get(key)!;
 const active=useRef(key);active.current=key;
 const protects=[...sessions.current.values()].some(v=>v.dirty||v.pending||v.busy);
 useEffect(()=>{if(!protects)return;const protect=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',protect);return()=>window.removeEventListener('beforeunload',protect);},[protects]);
 async function load(session:Session,afterSave=false){const epoch=++session.readEpoch;try{const r=Result.parse(await request({operation:'read',owner:session.owner}));if(epoch!==session.readEpoch)return;if(r.kind!=='document')throw Error();session.items=r.items;session.references=r.references;session.docRevision=r.revision;session.loaded=true;if(!afterSave)session.status='已读取';}catch{if(epoch!==session.readEpoch)return;session.status=afterSave?'已保存，暂时未刷新；可重新读取':'读取失败，保留当前输入';}render();}
 useEffect(()=>{if(!s.loaded)void load(s);},[key]);
 function adopt(item?:Item){s.selected=item;s.draft=item?{title:item.title,body:item.body,nature:item.nature,sources:item.sources,leads:item.leads,userConfirmed:item.userConfirmed,independentlyVerified:item.independentlyVerified,reason:'',reevaluated:false,timeKind:'unknown',date:'',instant:'',timezone:''}:empty();s.dirty=false;s.server=undefined;s.companyComparison=undefined;s.history=undefined;render();}
 function switchItem(item?:Item){if(s.pending||s.busy)return;if(s.dirty&&!window.confirm('放弃尚未保存的研究输入？'))return;adopt(item);}
 function change<K extends keyof Draft>(name:K,value:Draft[K]){s.draft={...s.draft,[name]:value};s.dirty=true;render();}
 async function result(session:Session,r:Result,intent:Request){
  if(r.kind==='receipt_missing'){session.pending=intent;session.status='未发现原回执；可明确继续同一意图';render();return;}
  session.pending=undefined;
  if(r.kind==='item'){session.selected=r.item.owner.kind===session.owner.kind&&r.item.owner.id===session.owner.id?r.item:undefined;session.draft=session.selected?{...session.draft,title:r.item.title,body:r.item.body,nature:r.item.nature,sources:r.item.sources,leads:r.item.leads,userConfirmed:r.item.userConfirmed,independentlyVerified:r.item.independentlyVerified,reason:'',reevaluated:false,timeKind:'unknown',date:'',instant:'',timezone:''}:empty();session.dirty=false;session.server=undefined;session.status='已保存';onChanged?.();await load(session,true);}
  else if(r.kind==='failure'){session.status=r.code==='conflict'?'冲突：本地输入保留，请比较当前正式值':'保存失败，输入保留：'+r.code;if(r.code==='conflict'&&intent.operation==='promote'){try{const target=Result.parse(await request({operation:'read',owner:{kind:'company',id:intent.companyId}}));if(target.kind==='document')session.companyComparison=target.items;}catch{session.status='公司提升冲突，目标公司正文暂不可读；机会输入保留';}}if(r.code==='conflict'&&session.selected&&intent.operation!=='promote'){try{const current=Result.parse(await request({operation:'resolve',id:session.selected.id,viewer:session.owner}));if(current.kind==='resolution')session.server=current.resolution.item;}catch{session.status='冲突，正式值暂不可读；输入保留';}}}
  render();
 }
 async function run(input:unknown,session=s){const parsed=Request.safeParse(input);if(!parsed.success){session.status='请填写正文、必要说明；改写需重新判断保留的来源。';render();return;}const intent=parsed.data;session.readEpoch++;session.pending=intent;session.busy=true;session.status='保存中';render();try{await result(session,Result.parse(await request(intent)),intent);}catch{session.status='保存结果待核对，当前输入保留';}finally{session.busy=false;render();}}
 function actualTime():BusinessTime{return s.draft.timeKind==='unknown'?{kind:'unknown'}:s.draft.timeKind==='date'?{kind:'date',date:s.draft.date}:{kind:'instant',instant:s.draft.instant,timezone:s.draft.timezone};}
 function base(){return {commandId:crypto.randomUUID(),owner:s.owner,id:s.selected!.id,expectedRevision:s.selected!.revision,reason:s.draft.reason,businessTime:actualTime()};}
 function save(){const d=s.draft;void run(s.selected?{operation:'correct',...base(),title:d.title,body:d.body,nature:d.nature,sources:d.sources,leads:d.leads,reevaluatedSources:d.reevaluated}:{operation:'create',commandId:crypto.randomUUID(),owner:s.owner,title:d.title,body:d.body,nature:d.nature,sources:d.sources,leads:d.leads,userConfirmed:d.userConfirmed,independentlyVerified:d.independentlyVerified});}
 async function promote(){if(!s.selected||s.dirty){s.status='请先保存或明确取消未保存输入，再提升。';render();return;}if(!window.confirm('提升后，同公司全部机会可读取此条正文；公司成为唯一可修改正本。私有原件和旧机会历史不会一起共享。确认扩大共享范围？'))return;try{const r=Result.parse(await request({operation:'read',owner:{kind:'company',id:companyId}}));if(r.kind!=='document')throw Error();const duplicate=r.items.find(v=>v.item.active&&v.item.title===s.selected!.title);if(duplicate){s.companyComparison=r.items;s.status='公司存在同标题条目，请比较后明确改写标题或取消提升。公司：'+duplicate.item.body+'；机会：'+s.selected.body;render();return;}await run({operation:'promote',...base(),reason:'用户明确提升至公司共享范围',companyId,expectedCompanyDocumentRevision:r.revision,sharingConfirmed:true});}catch{s.status='公司正式值读取失败，尚未提升';render();}}
 async function history(){if(!s.selected)return;const session=s;const id=s.selected.id;try{const r=Result.parse(await request({operation:'history',id,owner:s.owner}));if(session.selected?.id!==id)return;if(r.kind==='history')session.history=r.items.map(v=>`${v.action}：${v.item.body}；确认 ${v.item.userConfirmed?'是':'否'}，独立核验 ${v.item.independentlyVerified?'是':'否'}；实际时间 ${v.businessTime.kind==='unknown'?'未知':v.businessTime.kind==='date'?v.businessTime.date:v.businessTime.instant}`);else session.status='历史暂不可读';}catch{if(session.selected?.id!==id)return;session.status='历史读取失败';}render();}
 const d=s.draft;const disabled=s.busy||!!s.pending;
 return <section aria-label="岗位情报"><h2>岗位情报</h2><p>机会私有研究与公司共享研究各有唯一正文。事实陈述不自动等于确认或核验。</p><label>研究归属<select value={scope} disabled={disabled} onChange={e=>{setScope(e.target.value as typeof scope);}}><option value="opportunity">本机会私有</option><option value="company">公司共享</option></select></label><p role="status">{s.status}{s.dirty?' · 未保存':''}</p><button disabled={disabled} onClick={()=>void load(s)}>重新读取研究</button>
 <ul>{s.items.map(({item,reviewRequired})=><li key={item.id}><button disabled={disabled} onClick={()=>switchItem(item)}>{item.title}{item.active?'':'（已撤回）'}</button> · {item.nature==='fact_statement'?'事实陈述':item.nature==='inference'?'推断':'未知'}{reviewRequired?' · 依据已变化或不可读／待复核':''}</li>)}</ul>
 {s.references.map(ref=><p key={ref.itemId}>已提升至公司：只读引用 <button onClick={async()=>{const result=Result.parse(await request({operation:'resolve',id:ref.itemId,viewer:s.owner}));if(result.kind==='resolution'){s.status='公司条目（只读）：'+result.resolution.item.body;render();}}}>查看公司唯一正文</button></p>)}
 <fieldset disabled={disabled}><legend>{s.selected?'研究条目':'新增研究条目'}</legend><button type="button" onClick={()=>switchItem()}>新增研究</button><label>研究标题<input value={d.title} onChange={e=>change('title',e.target.value)}/></label><label htmlFor={key+'-body'}>研究正文</label><textarea id={key+'-body'} value={d.body} onChange={e=>change('body',e.target.value)}/><label>陈述性质<select value={d.nature} onChange={e=>change('nature',e.target.value as Item['nature'])}><option value="fact_statement">事实陈述</option><option value="inference">推断</option><option value="unknown">未知</option></select></label><label><input type="checkbox" checked={d.userConfirmed} onChange={e=>change('userConfirmed',e.target.checked)}/>用户确认</label><label><input type="checkbox" checked={d.independentlyVerified} onChange={e=>change('independentlyVerified',e.target.checked)}/>独立核验</label>
 <label>选择来源原件<select value="" onChange={e=>{const source=availableSources.find(v=>v.ref.objectId===e.target.value);if(source&&!d.sources.some(v=>v.ref.objectId===source.ref.objectId))change('sources',[...d.sources,{ref:source.ref,purpose:'',excerpt:'',assessment:'lead_only'}]);}}><option value="">选择已保存原件</option>{availableSources.map(v=><option key={v.ref.objectId} value={v.ref.objectId}>{v.name}</option>)}</select></label>
 {d.sources.map((source,i)=><div key={source.ref.objectId}><p>{availableSources.find(v=>v.ref.objectId===source.ref.objectId)?.name??'已关联来源；可读性以正式查询为准'}</p><label>来源用途<input value={source.purpose} onChange={e=>change('sources',d.sources.map((v,n)=>n===i?{...v,purpose:e.target.value}:v))}/></label><label htmlFor={key+'-excerpt-'+i}>支持摘录</label><textarea id={key+'-excerpt-'+i} value={source.excerpt} onChange={e=>change('sources',d.sources.map((v,n)=>n===i?{...v,excerpt:e.target.value}:v))}/><label>证据关系<select value={source.assessment} onChange={e=>change('sources',d.sources.map((v,n)=>n===i?{...v,assessment:e.target.value as Source['assessment']}:v))}><option value="lead_only">仅线索</option><option value="supports">支持正文</option><option value="needs_review">待复核</option></select></label><button onClick={()=>change('sources',d.sources.filter((_,n)=>n!==i))}>移除此来源</button></div>)}
 <button onClick={()=>change('leads',[...d.leads,{title:'',url:''}])}>新增标题与链接线索</button>{d.leads.map((lead,i)=><div key={i}><label>线索标题<input value={lead.title} onChange={e=>change('leads',d.leads.map((v,n)=>n===i?{...v,title:e.target.value}:v))}/></label><label>线索链接<input value={lead.url} onChange={e=>change('leads',d.leads.map((v,n)=>n===i?{...v,url:e.target.value}:v))}/></label><button onClick={()=>change('leads',d.leads.filter((_,n)=>n!==i))}>移除此线索</button></div>)}
 {s.selected&&<><label>实际变化时间<select value={d.timeKind} onChange={e=>change('timeKind',e.target.value as BusinessTime['kind'])}><option value="unknown">未知</option><option value="date">仅日期</option><option value="instant">带时区时刻</option></select></label>{d.timeKind==='date'&&<label>实际日期<input type="date" value={d.date} onChange={e=>change('date',e.target.value)}/></label>}{d.timeKind==='instant'&&<><label>实际时刻<input placeholder="2026-10-03T12:00:00+08:00" value={d.instant} onChange={e=>change('instant',e.target.value)}/></label><label>原时区<input placeholder="Asia/Shanghai" value={d.timezone} onChange={e=>change('timezone',e.target.value)}/></label></>}<label>变化说明<input value={d.reason} onChange={e=>change('reason',e.target.value)}/></label><label><input type="checkbox" checked={d.reevaluated} onChange={e=>change('reevaluated',e.target.checked)}/>已重新判断保留来源是否适用；改写清除旧确认与核验</label><button onClick={()=>{if(d.title!==s.selected!.title||d.body!==s.selected!.body||d.nature!==s.selected!.nature){s.status='正文已改变，请使用改写保存；补证不能偷偷改写正文。';render();return;}void run({operation:'supplement',...base(),sources:d.sources,leads:d.leads,userConfirmed:d.userConfirmed,independentlyVerified:d.independentlyVerified});}}>只补证／更新确认核验</button><button onClick={()=>{if(s.dirty){s.status='未保存输入仍在，请先处理再撤回或恢复';render();return;}const reason=window.prompt('填写撤回或恢复说明');if(reason)void run({operation:'lifecycle',...base(),reason,action:s.selected!.active?'withdraw':'restore'});}}>{s.selected.active?'撤回条目':'恢复条目'}</button>{s.owner.kind==='opportunity'&&<button onClick={()=>void promote()}>提升为公司共享研究</button>}<button onClick={()=>void history()}>查看研究历史</button></>}
 <button onClick={save}>{s.selected?'保存改写':'保存研究'}</button><button onClick={()=>{if(s.dirty&&!window.confirm('明确取消未保存的研究输入？'))return;adopt(s.selected);}}>取消未保存输入</button></fieldset>
 {s.companyComparison&&<aside aria-label="公司提升冲突比较"><p>目标公司共享研究与本机会私有研究的比较；不会自动合并。</p><p>本机会正文：{s.selected?.body}</p>{s.companyComparison.map(v=><p key={v.item.id}>公司正文 · {v.item.title}：{v.item.body}</p>)}<button disabled={disabled} onClick={()=>void promote()}>重新比较并确认提升</button><button onClick={()=>{s.companyComparison=undefined;s.status='已取消提升，机会条目保留';render();}}>取消提升保留机会条目</button></aside>}
 {s.server&&<aside aria-label="研究冲突比较"><p>当前正式值：{s.server.body}；本地草稿：{d.body}</p><button onClick={()=>{s.selected=s.server;s.server=undefined;s.status='已采用新基线，草稿仍保留；请明确重新保存';render();}}>采用新基线并保留草稿</button><button onClick={()=>adopt(s.server)}>放弃草稿采用正式值</button></aside>}
 {s.pending&&!s.busy&&<><button onClick={async()=>{try{await result(s,Result.parse(await request({operation:'receipt',commandId:'commandId'in s.pending!?s.pending!.commandId:''})),s.pending!);}catch{s.status='回执仍不可读；不重复创建';render();}}}>核对原保存回执</button>{s.status.includes('未发现原回执')&&<button onClick={()=>void run(s.pending)}>明确继续同一意图</button>}</>}
 {s.history&&<ol aria-label="研究历史">{s.history.map((v,i)=><li key={i}>{v}</li>)}</ol>}
 </section>;
}
