import type {} from '../../contracts/common/file-bridge';
import {NavigationIcon} from '../design-system/NavigationIcon';
import {AvatarMenu} from '../support/experience/avatar-menu';
import {careerVersion} from '../support/experience/version';
import changelog from '../../../docs/ux/CHANGELOG.md?raw';
import {LegacyHistoryView} from '../support/ai/legacy-history';
import {ProductTaskLauncher} from '../support/ai/product-launcher';
import {LocalSearch} from '../support/local-search';
import {TavilySearch} from '../support/ai/tavily-search';
import {SecretSettings} from '../support/ai/secret-settings';
import {FeedbackOverlay} from '../support/feedback';
import type {PurgeNotice} from '../design-system/purge-notice';
import {useEffect,useState,useRef,useCallback} from 'react';
import {AuxiliaryPanel} from '../support/experience/panel';
import {HelpContent} from '../support/experience';
import {navigationManifest,type NavigationId} from '../shell/routes';
import {WikiAiPage} from '../support/ai';
import {DataLifecycleSettings} from '../support/data-lifecycle/page';
import {Result as AiResult,type Request as AiRequest,type Target} from '../../contracts/ai/schema';
import {Result as DataResult,type DataRequest} from '../../contracts/application/schema';
import {Result as MaterialsResult} from '../../contracts/materials/schema';
import {Result as WikiResult} from '../../contracts/wiki/schema';
import {FeishuConnectionStatus,FeishuCurrentIdentity,type FeishuConnectionStatus as FeishuConnectionStatusType,type FeishuCurrentIdentity as FeishuCurrentIdentityType} from '../../contracts/platform/feishu-identity';
import type {SourceRef} from '../../contracts/common/source-ref';
const aiRequest=async(input:AiRequest)=>AiResult.parse(await window.career.request('ai',input));
async function sources(){const result=MaterialsResult.parse(await window.careerMaterials.request({operation:'list'}));return result.kind==='list'?result.items.map(item=>({ref:item.source,name:item.name})):[];}
interface PurgeTarget {owner:string;objectId:string;label:string}
export function G4Support({workspaceInstance,onRestore,onApplied,onPurge,purgeNotice,preferences,helpOpen,onHelp,onHelpClose,onFinishTutorial,onOpenOpportunity}:{workspaceInstance:string;onRestore():Promise<void>;onApplied():void;onPurge(refs:PurgeNotice['references']):void;purgeNotice?:PurgeNotice;preferences:{pinned:NavigationId|null;order:NavigationId[];busy:boolean;status:string;pin(id:NavigationId|null):Promise<void>;reorder(order:NavigationId[]):Promise<void>};helpOpen:boolean;onHelp():void;onHelpClose():void;onFinishTutorial():void;onOpenOpportunity(id:string):void}){
 const handlers=useRef({onRestore,onPurge,onApplied});handlers.current={onRestore,onPurge,onApplied};
 const diagnostics=window.career.developmentDiagnostics===true;
 const [group,setGroup]=useState<string>(),[visited,setVisited]=useState<string[]>([]);function openGroup(value:string){setGroup(value);setVisited(old=>old.includes(value)?old:[...old,value]);}
 const [settingsVisited,setSettingsVisited]=useState(false),[changelogOpen,setChangelogOpen]=useState(false);
 const [feishuStatus,setFeishuStatus]=useState<FeishuConnectionStatusType>({provider:'feishu',state:'not_connected'}),[feishuIdentity,setFeishuIdentity]=useState<FeishuCurrentIdentityType>(),[feishuAvatar,setFeishuAvatar]=useState<string>(),[feishuBusy,setFeishuBusy]=useState(false),[feishuMessage,setFeishuMessage]=useState('');
 const refreshFeishu=useCallback(async()=>{const bridge=window.careerFeishu;if(!bridge){setFeishuStatus({provider:'feishu',state:'connection_invalid'});setFeishuIdentity(undefined);setFeishuAvatar(undefined);return;}try{const status=FeishuConnectionStatus.parse(await bridge.getConnectionStatus());setFeishuStatus(status);if(status.state!=='connected'){setFeishuIdentity(undefined);setFeishuAvatar(undefined);return;}const identity=FeishuCurrentIdentity.parse(await bridge.getCurrentIdentity());setFeishuIdentity(identity);setFeishuAvatar(identity.avatar?await bridge.getAvatar():undefined);}catch{setFeishuStatus({provider:'feishu',state:'connection_invalid'});setFeishuIdentity(undefined);setFeishuAvatar(undefined);}},[]);
 useEffect(()=>{void refreshFeishu();window.addEventListener('career-connection-changed',refreshFeishu);return()=>window.removeEventListener('career-connection-changed',refreshFeishu);},[refreshFeishu]);
 useEffect(()=>()=>{if(feishuAvatar?.startsWith('blob:'))URL.revokeObjectURL(feishuAvatar);},[feishuAvatar]);
 async function connectFeishu(){if(!window.careerFeishu||feishuBusy)return;const wasConnected=feishuStatus.state==='connected';setFeishuBusy(true);setFeishuMessage('');try{const status=FeishuConnectionStatus.parse(await window.careerFeishu.connect());setFeishuStatus(status);if(status.state==='connected'){await refreshFeishu();window.dispatchEvent(new Event('career-connection-changed'));setFeishuMessage(wasConnected?'飞书连接已更新。':'飞书已连接。');}else if(status.state==='reauthorization_required')setFeishuMessage('飞书的登录授权已失效，需要你重新授权；短期凭据过期会自动刷新。');else if(status.state==='not_connected')setFeishuMessage('尚未发现可用的飞书用户授权。');else setFeishuMessage('暂时无法读取飞书连接状态。');}catch{setFeishuMessage('暂时无法确认飞书连接状态。');}finally{setFeishuBusy(false);}}
 const menuConnection=feishuStatus.state==='connected'&&feishuIdentity?{name:feishuIdentity.displayName,avatar:feishuAvatar?<img alt="飞书头像" src={feishuAvatar}/>:<NavigationIcon name="person"/>}:undefined;
 const plans=useRef(new Map<string,PurgeNotice['references']>());
 const [history,setHistory]=useState(false),[settings,setSettings]=useState(false),[ai,setAi]=useState(false),[product,setProduct]=useState(false),[productVisited,setProductVisited]=useState(false),[targets,setTargets]=useState<PurgeTarget[]>([]),[scopes,setScopes]=useState<{target:Target;label:string}[]>([{target:{scope:'personal'},label:'个人 Wiki'},{target:{scope:'cognition'},label:'长期认知 Wiki'}]);
 async function load(){try{const result=DataResult.parse(await window.career.request('application',{operation:'data.targets'}));if(result.kind!=='data_targets')return;setTargets(result.targets);const next:{target:Target;label:string}[]=[{target:{scope:'personal'},label:'个人 Wiki'},{target:{scope:'cognition'},label:'长期认知 Wiki'}];for(const t of result.targets){if(['project','employment','person','opportunity'].includes(t.owner))next.push({target:{scope:t.owner as Target['scope'],scopeId:t.objectId},label:t.label});}setScopes(next);}catch{/* Current input and known targets remain available; mutations never retry. */}}
 useEffect(()=>{void load();},[workspaceInstance,settings,ai]);
 const requestData=useCallback(async(input:DataRequest)=>{const result=DataResult.parse(await window.career.request('application',input));if(result.kind==='purge_plan')plans.current.set(result.plan.id,result.plan.impact.references);if(result.kind==='restored'||result.kind==='failure'&&result.code==='restore_failed_reconnected')await handlers.current.onRestore();if(result.kind==='failure'&&result.code==='purge_incomplete'&&input.operation==='data.purge.confirm')handlers.current.onPurge(plans.current.get(input.planId)??[]);if(result.kind==='purged'){handlers.current.onPurge(plans.current.get(result.planId)??[]);await load();handlers.current.onApplied();}return result;},[workspaceInstance]);
 function move(id:NavigationId){const order=[...preferences.order],index=order.indexOf(id);if(index<1)return;[order[index-1],order[index]]=[order[index],order[index-1]];void preferences.reorder(order);}
 return <><AvatarMenu connection={menuConnection} onConnection={()=>{setSettingsVisited(true);openGroup('connections');setSettings(true);}}><button className="account-menu-item popover-item" role="menuitem" onClick={()=>setChangelogOpen(true)}><NavigationIcon name="changelog"/>更新日志</button><button className="account-menu-item popover-item" role="menuitem" onClick={()=>{setSettingsVisited(true);if(!group)openGroup('connections');setSettings(true);}}> <NavigationIcon name="settings"/>设置</button><button className="account-menu-item popover-item" role="menuitem" onClick={onHelp}><NavigationIcon name="help"/>帮助</button><FeedbackOverlay renderTrigger={show=><button className="account-menu-item popover-item" role="menuitem" onClick={show}><NavigationIcon name="feedback"/>反馈</button>} purgeNotice={purgeNotice} onPurged={refs=>{onPurge(refs);void load();onApplied();}}/></AvatarMenu>
 {settingsVisited&&<AuxiliaryPanel open={settings} label="设置" onClose={()=>setSettings(false)} footer={<div className="settings-version career-settings-version"><span><strong>Career 版本</strong> · {careerVersion}</span>{window.careerHost&&<button onClick={()=>{if(window.confirm('请先确认正在编辑的内容已保存。退出后台后，浏览器标签仍会保留；重新启动 Career 再连接即可继续。要退出本地后台吗？'))void window.careerHost!.stop().catch(()=>window.alert('暂时无法确认后台是否退出，请查看启动器状态；不要重复操作。'));}}>退出本地后台</button>}<button onClick={()=>{setSettings(false);setChangelogOpen(true);}}>更新日志 →</button></div>}><div className="settings-layout"><nav aria-label="设置分类" className="settings-nav settings-groups">{[['connections','AI / Search 连接','管理本机安全连接；发送仍需单独授权'],['backup','备份与恢复','保护资料，选择经过验证的恢复点'],['navigation','导航设置','调整启动入口和四模块顺序'],['maintenance','高级资料维护','查找资料、只读历史与永久清除']] .map(([id,name,description])=><button key={id} aria-label={name} aria-current={group===id?'page':undefined} aria-selected={group===id} title={description} onClick={()=>openGroup(id)}><strong>{name}</strong></button>)}</nav><div className="settings-page">
 {visited.includes('navigation')&&<div hidden={group!=='navigation'}><h3>导航设置</h3><p>选择启动时打开的模块；未设置时先到 Wiki。</p>{preferences.order.map(id=>{const item=navigationManifest.find(entry=>entry.id===id)!;return <div className="nav-setting-row" key={id}><span><NavigationIcon name={id}/>{item.label}</span><button disabled={preferences.busy} aria-pressed={preferences.pinned===id} onClick={()=>void preferences.pin(preferences.pinned===id?null:id)}>{preferences.pinned===id?`取消${item.label}启动入口`:`设${item.label}为启动入口`}</button><button disabled={preferences.busy||preferences.order.indexOf(id)===0} onClick={()=>move(id)}>上移{item.label}</button></div>;})}<button className="text-button" disabled={preferences.busy} onClick={()=>void preferences.reorder(['wiki','opportunity','project','employment'])}>恢复默认顺序</button><p role="status">{preferences.status}</p></div>}
 {visited.includes('connections')&&<div hidden={group!=='connections'}><p className="connection-safety">密钥只保存在本机；保存不会发送请求，任务外发前会逐次确认。</p><section className="feishu-card career-feishu-info" aria-label="飞书连接身份"><div className="feishu-card-head"><NavigationIcon name="source"/><h3>飞书连接</h3></div><p>Career 资料保存在本机。飞书身份仅用于连接显示，与 Profile 姓名分开。</p><div className="career-feishu-status" role="status"><strong>{feishuStatus.state==='connected'?'已连接':feishuStatus.state==='reauthorization_required'?'需要重新授权':feishuStatus.state==='connection_invalid'?'连接失效':'未连接'}</strong>{feishuStatus.state==='connected'&&feishuIdentity&&<span>{feishuIdentity.displayName} · {feishuAvatar?'头像可用':'头像暂不可用'}</span>}</div><button className="button" disabled={feishuBusy} onClick={()=>void connectFeishu()}>{feishuBusy?'正在连接…':feishuStatus.state==='connected'?'更新连接':'连接飞书'}</button>{feishuMessage&&<p role="status">{feishuMessage}</p>}</section><SecretSettings diagnostics={diagnostics} active={settings&&group==='connections'} bridge={window.careerSecrets} connectionBridge={window.careerConnectionTest}/><SecretSettings active={settings&&group==='connections'} bridge={window.careerTavilySecrets} connectionBridge={window.careerConnectionTest} service="tavily"/></div>}
 {visited.includes('backup')&&<div hidden={group!=='backup'}><DataLifecycleSettings section="backup" request={requestData} targets={targets}/></div>}
 {visited.includes('maintenance')&&<div hidden={group!=='maintenance'}><h3>高级资料维护</h3><details><summary>本地资料搜索</summary><LocalSearch bridge={window.careerSearch} purgeNotice={purgeNotice} onOpenOpportunity={id=>{setSettings(false);onOpenOpportunity(id);}}/></details><details><summary>历史 AI 建议（只读）</summary><p>这些是旧建议的历史记录，不能再次执行或接受。</p><LegacyHistoryView request={aiRequest} purgeNotice={purgeNotice}/></details><details><summary>永久清除</summary><DataLifecycleSettings section="maintenance" request={requestData} targets={targets}/></details></div>}
 {diagnostics&&<details><summary>开发诊断（仅隔离验收）</summary><p>以下能力使用明确的本地诊断模式，不代表真实服务已通过。</p><button onClick={()=>{setProduct(!product);setProductVisited(true);}}>AI 任务辅助</button>{productVisited&&<div hidden={!product}><ProductTaskLauncher purgeNotice={purgeNotice} onApplied={onApplied}/></div>}<button onClick={()=>setAi(!ai)}>整理 Wiki 资料</button>{ai&&<WikiAiPage purgeNotice={purgeNotice} request={aiRequest} sources={sources} targets={scopes} workspaceInstance={workspaceInstance} onApplied={()=>{void load();onApplied();}}/>}<TavilySearch bridge={window.careerTavilySearch} targets={targets}/></details>}
 </div></div></AuxiliaryPanel>}
 <AuxiliaryPanel open={changelogOpen} label="更新日志" onClose={()=>setChangelogOpen(false)}><div className="release-top"><span className="release-icon"><NavigationIcon name="changelog"/></span><div><h3>Career</h3><p>当前版本 v{careerVersion}</p></div></div>{changelog.split(/^## /m).slice(1).map(part=><article className="release-entry" key={part}><div className="release-entry-header"><h3>{part.split("\n")[0]}</h3></div>{part.slice(part.indexOf("\n")+1).trim().split(/\n\s*\n/).map((text,i)=><p key={i}>{text}</p>)}</article>)}</AuxiliaryPanel>
 <AuxiliaryPanel open={helpOpen} label="帮助" onClose={onHelpClose}><HelpContent onFinishTutorial={onFinishTutorial}/></AuxiliaryPanel></>;
}
