import type Database from 'better-sqlite3';import {randomUUID} from 'node:crypto';
import {SearchRun,SearchRequest,SearchResult} from '../../../contracts/ai/search';
import {SearchSourceRef,type SourceRef} from '../../../contracts/common/source-ref';
import {CapturedSearch} from '../../platform/providers/tavily';
import {tavilyPreviewDigest} from '../../../contracts/ai/tavily-search';
import {executeCommand,commandReceipt,redactedCommandResults} from '../../platform/commands/receipts';
export const searchMigration=`CREATE TABLE ai_search_runs(id TEXT PRIMARY KEY,body_json TEXT NOT NULL);`;
/** SearchRun owns returned candidates and sources; fixtures and real captures remain distinct. */
export function createSearchRuns(db:Database.Database,validOwner:(owner:SearchRun['owner'])=>boolean){
 function read(id:string){const row=db.prepare('SELECT body_json FROM ai_search_runs WHERE id=?').get(id) as {body_json:string}|undefined;return row?SearchRun.parse(JSON.parse(row.body_json)):undefined;}
 function handle(input:unknown):SearchResult|{kind:'failure';code:string}|{kind:'receipt_missing'}{try{const request=SearchRequest.parse(input);if(request.operation==='search.list')return {kind:'search_runs',runs:(db.prepare('SELECT id FROM ai_search_runs ORDER BY rowid DESC LIMIT 100').all() as {id:string}[]).map(row=>read(row.id)!)};if(request.operation==='search.read'){const run=read(request.id);return run?{kind:'search_run',run}:{kind:'failure',code:'not_found'};}if(request.operation==='search.receipt'){const result=commandReceipt(db,'ai.search',request.commandId);return result===undefined?{kind:'receipt_missing'}:result as SearchResult|{kind:'failure';code:string};}if(!validOwner(request.owner))throw Error('target_unavailable');if(request.operation==='search.preview')return {kind:'search_preview',owner:request.owner,query:request.query,adapter:'controlled-fixture',network:'none',recipient:'local controlled Search fixture; no public network'};
 return executeCommand(db,'ai.search',request.commandId,request,()=>{const id=randomUUID(),run=SearchRun.parse({id,owner:request.owner,query:request.query,adapter:'controlled-fixture',network:'none',recordedAt:new Date().toISOString(),results:[1,2].map(index=>{const resultId=randomUUID();return {id:resultId,title:'受控搜索资料 '+index,url:'https://example.invalid/career-g5-fixture/'+index,body:'受控 Search fixture 返回 '+index+'。查询为：'+request.query+'。不是实际公网结果，不证明公司事实。',source:{owner:'search',objectId:id,revision:1,locator:resultId,scope:request.owner.kind,scopeId:request.owner.id}};})});db.prepare('INSERT INTO ai_search_runs VALUES(?,?)').run(id,JSON.stringify(run));return {kind:'search_run' as const,run};});}catch(error){return {kind:'failure',code:error instanceof Error&&/^[a-z_]{1,80}$/.test(error.message)?error.message:'invalid_request'};}}
 function resolveSource(input:SourceRef){const parsed=SearchSourceRef.safeParse(input);if(!parsed.success)return undefined;const ref=parsed.data,run=read(ref.objectId),result=run?.results.find(result=>result.id===ref.locator);if(!result||run!.owner.kind!==ref.scope||run!.owner.id!==ref.scopeId)return undefined;return {metadata:{id:run!.id,revision:1,scope:ref.scope,source:result.source},body:result.body,nature:run!.adapter==='tavily'?'public_search_result_unverified':'controlled_search_result'};}
 function recordExternal(owner:SearchRun['owner'],input:unknown){const captured=CapturedSearch.parse(input);if(!validOwner(owner))throw Error('target_unavailable');return executeCommand(db,'ai.search.tavily',captured.id,{owner,captured},()=>{const run=SearchRun.parse({id:captured.id,owner,query:captured.response.query,adapter:'tavily',network:'external',recordedAt:captured.recordedAt,externalEvidence:{endpoint:'https://api.tavily.com/search',previewDigest:tavilyPreviewDigest,requestCount:1,...captured.response.request_id?{providerRequestId:captured.response.request_id}:{}},results:captured.response.results.map(result=>{const id=randomUUID();return {id,title:result.title,url:result.url,body:result.content,source:{owner:'search',objectId:captured.id,revision:1,locator:id,scope:owner.kind,scopeId:owner.id}};})});db.prepare('INSERT INTO ai_search_runs VALUES (?,?)').run(run.id,JSON.stringify(run));return {kind:'search_run' as const,run};});}
 return {handle,read,resolveSource,recordExternal,list:()=> (db.prepare('SELECT id FROM ai_search_runs').all() as {id:string}[]).map(row=>read(row.id)!),purgeImpact(id:string){const run=read(id);return run?{id,revision:1,name:'受控 SearchRun '+run.query,blobIds:[]}:undefined;},purge(id:string){db.prepare('DELETE FROM ai_search_runs WHERE id=?').run(id);for(const namespace of ['ai.search','ai.search.tavily'])redactedCommandResults(db,namespace,result=>(result as {run?:SearchRun}).run?.id===id,{kind:'failure',code:'body_purged'});}};
}
export function validateSearchCandidate(db:Database.Database){for(const row of db.prepare('SELECT id,body_json FROM ai_search_runs').all() as {id:string;body_json:string}[]){const run=SearchRun.parse(JSON.parse(row.body_json));if(run.id!==row.id||new Set(run.results.map(r=>r.id)).size!==run.results.length||run.results.some(result=>result.source.objectId!==run.id||result.source.locator!==result.id||result.source.scope!==run.owner.kind||result.source.scopeId!==run.owner.id))throw Error('backup_search_invalid');}}
export function searchCandidateRelations(db:Database.Database){return (db.prepare('SELECT body_json FROM ai_search_runs').all() as {body_json:string}[]).map(row=>{const run=SearchRun.parse(JSON.parse(row.body_json));return {owner:run.owner.kind,objectId:run.owner.id,kind:'object' as const};});}
