import type {} from '../../../contracts/common/file-bridge';
import {NavigationIcon} from '../../design-system/NavigationIcon';
import {AuxiliaryPanel} from '../../support/experience/panel';
import {useTaskAvailability} from '../../support/ai/business-entry';
import {ProductTaskPage,type ProductDecision} from '../../support/ai/product-task';
import type {ProductProposal} from '../../../contracts/ai/product';
import type {Result as AiResult} from '../../../contracts/ai/schema';
import {wasPurged,type PurgeNotice} from '../../design-system/purge-notice';
import React,{useEffect,useRef,useState,useId} from 'react';
import {createPortal} from 'react-dom';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {useForm,useFieldArray} from 'react-hook-form';
import {EditorContent,useEditor,Extension,Node as TiptapNode,type Editor,type JSONContent} from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import {Plugin,TextSelection} from '@tiptap/pm/state';
import {closeHistory,isHistoryTransaction} from '@tiptap/pm/history';
import type {Request as ResumeRequest,Result as ResumeResult,Profile,CareerDocument,Version} from '../../../contracts/resume/schema';
import {Alignment,ResumeEntry} from '../../../contracts/resume/schema';
import {toEditor,fromEditor} from './adapter';
import {createResumeSaveSession} from './save-session';
import './source-paper.css';
import {SourcePaperStage} from './source-paper';
import {MiaodaToolbar} from './miaoda/toolbar';
import {FrozenResumeBody} from './frozen-body';
import './resume.css';
import type {Request as ProfileRequest,Result as ProfileResult} from '../../../contracts/profile/schema';
type Request=ResumeRequest|ProfileRequest;
type Result=ResumeResult|ProfileResult;
type Transport=(request:Request)=>Promise<Result>;
type Opened=Extract<Result,{status:'document'}>;
const sourceParagraph=TiptapNode.create({name:'paragraph',priority:1000,group:'block',content:'inline*',parseHTML(){return [{tag:'p'}];},renderHTML({HTMLAttributes}){return ['p',HTMLAttributes,['span',{class:'source-entry-text',style:'display:block;min-height:1em;min-width:1ch','data-placeholder':HTMLAttributes['data-placeholder']??''},0]];}});
const sourceHeading=TiptapNode.create({name:'heading',group:'block',content:'inline*',marks:'',defining:true,addAttributes(){return {level:{default:2}};},parseHTML(){return [{tag:'h2'}];},renderHTML({HTMLAttributes}){return ['h2',HTMLAttributes,['span',{class:'heading-text'},0],['i',{class:'heading-line','aria-hidden':'true'}]];}});
const stableIds=Extension.create({
 name:'careerStableIds',
 addGlobalAttributes(){return [{types:['heading','paragraph','bulletList','listItem'],attributes:{careerId:{default:null},careerKind:{default:'summary'}}},{types:['paragraph'],attributes:{careerEntry:{default:null,parseHTML:element=>{const parsed=ResumeEntry.safeParse({id:element.getAttribute('data-entry-id'),field:element.getAttribute('data-entry-field')});return parsed.success?parsed.data:null;},renderHTML:attrs=>attrs.careerEntry?{'data-entry-id':attrs.careerEntry.id,'data-entry-field':attrs.careerEntry.field,'data-placeholder':({name:'项目名称',responsibility:'项目职责',date:'起止时间',school:'学校',major:'专业',company:'单位',position:'岗位'} as Record<string,string>)[attrs.careerEntry.field]??''}:{}},textAlign:{default:null,parseHTML:element=>Alignment.safeParse(element.style.textAlign).success?element.style.textAlign:null,renderHTML:attrs=>Alignment.safeParse(attrs.textAlign).success?{style:'text-align:'+attrs.textAlign}:{}}}},{types:['doc'],attributes:{careerIdentityNameAlignment:{default:null},careerTemplate:{default:'a4-basic'}}}];},
 addProseMirrorPlugins(){return [new Plugin({appendTransaction(transactions,_old,state){
  if(!transactions.some(transaction=>transaction.docChanged))return null;
  const seen=new Set<string>();const transaction=state.tr;
  state.doc.descendants((node,pos)=>{if(!['heading','paragraph','bulletList','listItem'].includes(node.type.name))return;let id=node.attrs.careerId as string|null;if(!id||seen.has(id)){id=crypto.randomUUID();transaction.setNodeMarkup(pos,undefined,{...node.attrs,careerId:id,...node.type.name==='paragraph'&&node.attrs.careerEntry?{careerEntry:null}:{}});}seen.add(id);});
  return transaction.docChanged?transaction:null;
 }})];}
});
const statusLabels={saved:'已保存',dirty:'未保存',saving:'保存中',composition:'正在中文输入，暂不保存',conflict:'保存冲突，保留了你的输入',unknown:'暂时无法确认是否保存。你的输入还在，请先检查保存结果。',failed:'保存失败，保留了你的输入'};
function ProfileFields({profile,request,onSaved,onDirty,plain=false,formRef,support}:{support?:HTMLElement|null;plain?:boolean;formRef?:React.RefObject<HTMLFormElement|null>;profile:Profile;request:Transport;onSaved:(profile:Profile)=>void;onDirty:(dirty:boolean)=>void}){
 const formId=useId();
 const defaults=(value:Profile)=>({name:value.name,contact:value.contact,links:value.links.length?structuredClone(value.links):plain?[]:[{label:'个人网页',href:''}]});
 const form=useForm<{name:string;contact:string;links:Profile['links']}>({defaultValues:defaults(profile)}),links=useFieldArray({control:form.control,name:'links'});
 const revision=useRef(profile.revision);
 const [profileMayContinue,setProfileMayContinue]=useState(false),[profileBusy,setProfileBusy]=useState(false);
 const [comparison,setComparison]=useState<Profile>();const [notice,setNotice]=useState('');
 const [pending,setPending]=useState<Extract<Request,{operation:'profile.save'}>>();
 useEffect(()=>onDirty(form.formState.isDirty||!!pending),[form.formState.isDirty,pending,onDirty]);
 useEffect(()=>{if(profile.revision===revision.current)return;if(form.formState.isDirty||pending)setComparison(profile);else{revision.current=profile.revision;form.reset(defaults(profile));}},[profile,form,pending]);
 async function accept(result:Result){setProfileMayContinue(false);if(result.status==='profile'){revision.current=result.profile.revision;form.reset(defaults(result.profile));setComparison(undefined);setPending(undefined);setNotice('基础资料已保存，所有当前简历使用最新身份');onSaved(result.profile);}else if(result.status==='conflict'){setComparison(result.profile);setPending(undefined);setNotice('基础资料有冲突，保留了你的输入');}else{setPending(undefined);setNotice('未保存：请检查资料及网页链接');}}
 const save=form.handleSubmit(async values=>{if(pending)return;const input:Extract<Request,{operation:'profile.save'}>={operation:'profile.save',commandId:crypto.randomUUID(),expectedRevision:revision.current,name:values.name,contact:values.contact,links:values.links.filter(link=>link.href.trim())};setPending(input);setProfileBusy(true);setNotice('基础资料保存中');try{await accept(await request(input));}catch{setNotice('基础资料保存结果待核对');}finally{setProfileBusy(false);}});
 const linkFields=links.fields.map((field,index)=><div className={plain?'paper-contact-link':'field-row'} key={field.id}>{plain?<><input aria-label={'链接显示文字 '+(index+1)} size={Math.max(4,Math.min(70,form.watch(`links.${index}.label`).length+2))} maxLength={120} {...form.register(`links.${index}.label`)}/><details className="paper-link-address"><summary aria-label={'修改网页地址 '+(index+1)}>编辑地址</summary><label className="field">网页 / GitHub 地址<input aria-label={index===0?'基础资料个人网页':'网页地址 '+(index+1)} {...form.register(`links.${index}.href`)}/></label></details></>:<><label className="field">网页名称<input maxLength={120} {...form.register(`links.${index}.label`)}/></label><label className="field">网页 / GitHub 地址<input aria-label={index===0?'基础资料个人网页':'网页地址 '+(index+1)} {...form.register(`links.${index}.href`)}/></label></>}<button type="button" className="paper-contact-remove" aria-label={'移除网页 '+(index+1)} onClick={()=>links.remove(index)}>×</button></div>);
 const controls=<div className="paper-identity-support">{(!plain||form.formState.isDirty||pending)&&<div className="paper-identity-actions"><span className="resume-note">适用于所有当前简历，历史版本不变。</span><button form={formId} className="button" type="submit" disabled={!!pending}>{plain?'保存信息':'保存基础资料'}</button></div>}{notice&&<span role="status">{notice}</span>}</div>;
 return <form id={formId} ref={formRef} className={'resume-identity'+(plain?' paper-identity':'')} onSubmit={save}>
  {!plain&&<p className="resume-note">修改后会同步到所有当前简历；历史版本保留当时的信息。</p>}
  <fieldset disabled={!!pending}>
   {plain?<><h2><input aria-label="基础资料姓名" placeholder="姓名" maxLength={120} {...form.register('name')}/></h2><p className="paper-contact"><input aria-label="基础资料联系方式" placeholder="点击填写联系方式" maxLength={500} {...form.register('contact')}/></p></>:<><label className="field">姓名<input aria-label="基础资料姓名" maxLength={120} {...form.register('name')}/></label><label className="field">联系方式<input aria-label="基础资料联系方式" maxLength={500} {...form.register('contact')}/></label></>}
   <div className="paper-contact-links">{linkFields}<button className="paper-contact-add" type="button" disabled={links.fields.length>=20} onClick={()=>links.append({label:'网页 / GitHub',href:''})}>＋ 网页 / GitHub</button></div>
  </fieldset>
  {plain&&support?createPortal(controls,support):controls}
  {pending&&!profileBusy&&<><button className="button" type="button" onClick={async()=>{setProfileBusy(true);try{const result=await request({operation:'profile.receipt',commandId:pending.commandId});if(result.status==='not-found'){setProfileMayContinue(true);setNotice('已经确认基础资料尚未保存，可以继续保存');}else await accept(result);}catch{setNotice('仍无法核对，保留输入');}finally{setProfileBusy(false);}}}>检查基础资料是否已保存</button>{profileMayContinue&&<button className="button" type="button" onClick={async()=>{setProfileMayContinue(false);setProfileBusy(true);try{await accept(await request(pending));}catch{setNotice('基础资料保存结果待核对');}finally{setProfileBusy(false);}}}>继续保存基础资料</button>}</>}
  {comparison&&<aside><p>当前正式资料：{comparison.name} / {comparison.contact}。你的输入保留在上方。</p><button className="button" type="button" onClick={()=>{revision.current=comparison.revision;setComparison(undefined);setNotice('已采用新版本基线，请确认再保存你的输入');}}>以新版本为基线保留输入</button><button className="button" type="button" onClick={()=>{revision.current=comparison.revision;form.reset(defaults(comparison));setComparison(undefined);onSaved(comparison);}}>放弃本地身份输入，采用正式资料</button></aside>}
 </form>;
}
function replaceUndoably(editor:Editor,content:CareerDocument){
 editor.view.dispatch(closeHistory(editor.state.tr));
 const next=editor.schema.nodeFromJSON(toEditor(content));
 editor.view.dispatch(editor.state.tr.replaceWith(0,editor.state.doc.content.size,next.content).setDocAttribute('careerIdentityNameAlignment',content.layout.identityNameAlignment??null).setDocAttribute('careerTemplate',content.layout.template));
 editor.view.dispatch(closeHistory(editor.state.tr));
}
function applyAiPatchUndoably(editor:Editor,content:CareerDocument,recordUndo=true){
 const old=editor.state.doc,next=editor.schema.nodeFromJSON(toEditor(content)),before:{node:typeof old;pos:number}[]=[],after:typeof old[]=[];old.forEach((node,pos)=>before.push({node,pos}));next.forEach(node=>after.push(node));
 const changes:{start:number;end:number;nodes:typeof old[]}[]=[];let previousOld=-1,previousNew=-1;
 const gap=(oldEnd:number,newEnd:number)=>{const from=previousOld+1,to=oldEnd,start=before[from]?.pos??old.content.size,end=before[to]?.pos??old.content.size,nodes=after.slice(previousNew+1,newEnd);if(start!==end||nodes.length)changes.push({start,end,nodes});};
 for(let index=0;index<after.length;index++){const id=after[index].attrs.careerId,match=before.findIndex((item,at)=>at>previousOld&&id&&item.node.attrs.careerId===id);if(match<0)continue;gap(match,index);if(!before[match].node.eq(after[index]))changes.push({start:before[match].pos,end:before[match].pos+before[match].node.nodeSize,nodes:[after[index]]});previousOld=match;previousNew=index;}
 gap(before.length,after.length);const identityChanged=old.attrs.careerIdentityNameAlignment!==next.attrs.careerIdentityNameAlignment;if(!changes.length&&!identityChanged)return;
 if(recordUndo)editor.view.dispatch(closeHistory(editor.state.tr));let transaction=editor.state.tr.setMeta('careerProposalApply',true).setMeta('addToHistory',recordUndo);if(identityChanged)transaction=transaction.setDocAttribute('careerIdentityNameAlignment',next.attrs.careerIdentityNameAlignment);for(const change of changes.sort((a,b)=>b.start-a.start||b.end-a.end))transaction=transaction.replaceWith(change.start,change.end,change.nodes);editor.view.dispatch(transaction);if(recordUndo)editor.view.dispatch(closeHistory(editor.state.tr));
}
function ResumeEditor({opened,request,onReturn,active,purgeNotice,embedded,heading}:{purgeNotice?:PurgeNotice;opened:Opened;request:Transport;onReturn?:()=>void;active:boolean;embedded?:boolean;heading?:{id:string;companyName:string;role:string}}){
 const aiSupported=useTaskAvailability('resume-optimize');
 const [,redraw]=useState(0);const transport=useRef(request);transport.current=request;
 const [profile,setProfile]=useState(opened.profile);const [profileDirty,setProfileDirty]=useState(false);const profileDirtyRef=useRef(false);profileDirtyRef.current=profileDirty;
 const resumeTransport=async(input:ResumeRequest):Promise<ResumeResult>=>{const result=await transport.current(input);if(result.status==='profile')throw new Error('unexpected Profile response');return result;};
 const sessionRef=useRef<ReturnType<typeof createResumeSaveSession>|null>(null);
 if(!sessionRef.current)sessionRef.current=createResumeSaveSession({resumeId:opened.document.id,revision:opened.document.revision,profileRevision:opened.profile.revision,content:opened.document.content},resumeTransport,()=>redraw(value=>value+1));
 const session=sessionRef.current;const state=session.state();
 const [error,setError]=useState('');const [formatError,setFormatError]=useState('');const formatErrorRef=useRef('');const [history,setHistory]=useState(false);const [versions,setVersions]=useState<Version[]>([]);const [viewed,setViewed]=useState<Version>();const [historyReadStatus,setHistoryReadStatus]=useState<'unread'|'loading'|'loaded'|'failed'>('unread');const historyReadGeneration=useRef(0);
 const [restoreCommand,setRestoreCommand]=useState<Extract<Request,{operation:'resume.restore'|'resume.copy-version'}>>();const [restoreBusy,setRestoreBusy]=useState(false),[restoreMayContinue,setRestoreMayContinue]=useState(false);
 const [naming,setNaming]=useState(false);const [versionName,setVersionName]=useState('');const [namingBusy,setNamingBusy]=useState(false),[versionMayContinue,setVersionMayContinue]=useState(false);const [versionCommand,setVersionCommand]=useState<Extract<Request,{operation:'resume.name-version'|'resume.export'}>>();
 const aiProtection=useRef<string[]>([]),aiProposal=useRef<ProductProposal|undefined>(undefined),aiBaseline=useRef<CareerDocument|undefined>(undefined),aiApplyingRef=useRef(false);const [aiApplying,setAiApplying]=useState(false),[aiTaskLocked,setAiTaskLocked]=useState(false),[aiOpen,setAiOpen]=useState(false),[aiBlocks,setAiBlocks]=useState<string[]>([]);
 const [copyOpen,setCopyOpen]=useState(false),[copyItems,setCopyItems]=useState<Extract<ResumeResult,{status:'copy-candidates'}>['items']>([]);
 const moreMenu=useRef<HTMLDetailsElement>(null);
 useEffect(()=>{const close=(event:PointerEvent)=>{if(!moreMenu.current?.contains(event.target as Node))moreMenu.current?.removeAttribute('open');};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close);},[]);
 const [profileOpen,setProfileOpen]=useState(false);const identityForm=useRef<HTMLFormElement>(null);const [identitySupport,setIdentitySupport]=useState<HTMLDivElement|null>(null);
 const [findOpen,setFindOpen]=useState(false);const [find,setFind]=useState('');const [replacement,setReplacement]=useState('');const [overflow,setOverflow]=useState(false);
 function updateFromEditor(updated:Editor){
  try{session.change(fromEditor(updated.getJSON(),session.state().content.layout));formatErrorRef.current='';setFormatError('');setError('');if(session.state().content.layout.template==='a4-basic')setOverflow(updated.view.dom.scrollHeight>900);}
  catch(cause){const message=cause instanceof Error?cause.message:'当前格式不受支持，未保存';formatErrorRef.current=message;setFormatError(message);}
 }
 const editorRef=useRef<Editor|null>(null);
 const editor=useEditor({injectCSS:false,extensions:[StarterKit.configure({heading:false,paragraph:false,trailingNode:opened.document.content.layout.template==='miaoda-paper'?false:undefined,code:false,codeBlock:false,blockquote:false,hardBreak:false,horizontalRule:false,orderedList:false,underline:false,link:{openOnClick:false}}),sourceHeading,sourceParagraph,stableIds,Extension.create({name:'careerProposalProtection',addProseMirrorPlugins(){return [new Plugin({filterTransaction(transaction,state){if(profileDirtyRef.current&&transaction.doc.attrs.careerTemplate!==state.doc.attrs.careerTemplate){queueMicrotask(()=>setError('请先保存姓名、联系方式和网页的未提交输入，再切换版式。'));return false;}if(aiApplyingRef.current&&isHistoryTransaction(transaction))return false;if(!transaction.docChanged||transaction.getMeta('careerProposalApply')||!aiProtection.current.length)return true;const selected=(doc:typeof state.doc)=>{const values:unknown[]=[];doc.descendants(node=>{if(aiProtection.current.includes(node.attrs.careerId))values.push(node.toJSON());});return JSON.stringify(values);};return selected(transaction.doc)===selected(state.doc);}})];}})],content:toEditor(opened.document.content),editorProps:{attributes:{'aria-label':'简历正文','role':'textbox','aria-multiline':'true'},handleDOMEvents:{mousedown:(view,event)=>{const paragraph=(event.target as HTMLElement).closest('p[careerid]');if(!paragraph)return false;let target:number|undefined;view.state.doc.descendants((node,pos)=>{if(node.type.name==='paragraph'&&node.content.size===0&&node.attrs.careerId===paragraph.getAttribute('careerid'))target=pos+1;});if(target===undefined)return false;event.preventDefault();view.dispatch(view.state.tr.setSelection(TextSelection.create(view.state.doc,target)));view.focus();return true;},compositionstart:()=>{session.composition(true);return false;},compositionend:()=>{setTimeout(()=>{session.composition(false);if(editorRef.current)updateFromEditor(editorRef.current);},0);return false;}}},onUpdate:({editor:updated})=>updateFromEditor(updated)});
 editorRef.current=editor;
 function setAlignment(value:import('../../../contracts/resume/schema').Alignment,identity=false){
  if(!editor||state.status==='composition'||aiApplyingRef.current||restoreCommand)return;
  editor.commands.focus();editor.view.dispatch(closeHistory(editor.state.tr));let transaction=editor.state.tr;
  if(identity)transaction=transaction.setDocAttribute('careerIdentityNameAlignment',value);
  else editor.state.doc.nodesBetween(editor.state.selection.from,editor.state.selection.to,(node,pos)=>{if(node.type.name==='paragraph')transaction.setNodeMarkup(pos,undefined,{...node.attrs,textAlign:value});});
  if(transaction.docChanged)editor.view.dispatch(transaction);editor.view.dispatch(closeHistory(editor.state.tr));
 }
 function selectSection(id:string){if(!editor||state.status==='composition'||restoreCommand)return;let position:number|undefined;editor.state.doc.forEach((node,pos)=>{if(node.type.name==='heading'&&node.attrs.careerId===id)position=Math.min(pos+node.nodeSize+1,editor.state.doc.content.size);});if(position!==undefined)editor.chain().focus().setTextSelection(position).scrollIntoView().run();}
 function addSection(kind:CareerDocument['sections'][number]['kind']){if(!editor||state.status==='composition'||restoreCommand||aiApplying||state.content.sections.length>=30)return;const labels={summary:'个人简介',education:'教育经历',experience:'工作经历',project:'项目经历',skills:'专业技能'};editor.view.dispatch(closeHistory(editor.state.tr));editor.chain().focus().insertContentAt(editor.state.doc.content.size,[{type:'heading',attrs:{level:2,careerId:crypto.randomUUID(),careerKind:kind},content:[{type:'text',text:labels[kind]}]},{type:'paragraph',attrs:{careerId:crypto.randomUUID()}}]).run();editor.view.dispatch(closeHistory(editor.state.tr));}

 function setTemplate(value:CareerDocument['layout']['template']){if(!editor||state.status==='composition'||restoreCommand||aiApplying||profileDirty)return;editor.view.dispatch(closeHistory(editor.state.tr));let tr=editor.state.tr.setDocAttribute('careerTemplate',value);if(value!=='a4-basic'&&!state.content.layout.identityNameAlignment)tr=tr.setDocAttribute('careerIdentityNameAlignment','center');editor.view.dispatch(tr);editor.view.dispatch(closeHistory(editor.state.tr));}
 function addEntry(kind:CareerDocument['sections'][number]['kind']){if(!editor||state.status==='composition'||restoreCommand||aiApplying)return;const config=kind==='skills'?{kind,title:'专业技能',fields:[{key:'items',label:'技能'}]}:kind==='education'?{kind,title:'教育经历',fields:[{key:'school',label:'学校'},{key:'major',label:'专业'},{key:'date',label:'起止时间'}]}:kind==='experience'?{kind,title:'工作经历',fields:[{key:'company',label:'单位'},{key:'position',label:'岗位'},{key:'date',label:'起止时间'}]}:kind==='project'?{kind,title:'项目经历',fields:[{key:'name',label:'项目名称'},{key:'responsibility',label:'项目职责'},{key:'date',label:'起止时间'}]}:undefined;if(!config)return;const section=state.content.sections.find(s=>s.kind===kind);if(!section&&state.content.sections.length>=30)return;if(section&&section.blocks.length+config.fields.length>200)return;const entryId=crypto.randomUUID();const nodes:JSONContent[]=config.fields.map(f=>({type:'paragraph',attrs:{careerId:crypto.randomUUID(),careerEntry:{id:entryId,field:f.key}}}));let at=editor.state.doc.content.size;if(section){let found=false;editor.state.doc.forEach((n,pos)=>{if(n.type.name==='heading'){if(n.attrs.careerId===section.id)found=true;else if(found){at=pos;found=false;}}});}else nodes.unshift({type:'heading',attrs:{level:2,careerId:crypto.randomUUID(),careerKind:kind},content:[{type:'text',text:config.title}]});editor.view.dispatch(closeHistory(editor.state.tr));editor.chain().insertContentAt(at,nodes).run();editor.view.dispatch(closeHistory(editor.state.tr));}
 const queryClient=useQueryClient();
 const [profilePurge,setProfilePurge]=useState(0);
 const profileQuery=useQuery({queryKey:['resume',opened.document.opportunityId,'profile'],queryFn:async()=>{const result=await transport.current({operation:'profile.read'});if(result.status!=='profile')throw new Error('基础资料读取失败');return result.profile;},initialData:opened.profile,refetchInterval:5000,retry:false});
 useEffect(()=>{if(!wasPurged(purgeNotice,'profile','current'))return;setProfilePurge(purgeNotice!.sequence);setProfile(old=>({...old,name:'',contact:'',links:[]}));setProfileDirty(false);void profileQuery.refetch();},[purgeNotice?.sequence]);
 useEffect(()=>{if(profileQuery.data.revision!==profile.revision){setProfile(profileQuery.data);session.profileRevision(profileQuery.data.revision);}},[profileQuery.data,profile.revision,session]);
 useEffect(()=>{if(state.status!=='dirty'||formatError||aiApplying)return;const timer=setTimeout(()=>{if(!formatErrorRef.current&&!aiProtection.current.length)void session.flush();},650);return()=>clearTimeout(timer);},[state.content,state.status,formatError,session,aiApplying]);
 useEffect(()=>{const protect=(event:BeforeUnloadEvent)=>{if(session.state().status!=='saved'||formatErrorRef.current||profileDirty||restoreCommand||versionCommand){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',protect);return()=>window.removeEventListener('beforeunload',protect);},[session,profileDirty,restoreCommand,versionCommand]);
 useEffect(()=>()=>session.dispose(),[session]);
 useEffect(()=>{const shortcut=(event:KeyboardEvent)=>{if(!active||document.querySelector('dialog[open],[role="dialog"]:not(dialog)')||restoreCommand||!event.metaKey||event.isComposing||session.state().status==='composition')return;if(event.key.toLowerCase()==='s'){event.preventDefault();setNaming(true);}if(event.key.toLowerCase()==='f'){event.preventDefault();setFindOpen(true);}};window.addEventListener('keydown',shortcut);return()=>window.removeEventListener('keydown',shortcut);},[session,restoreCommand,active]);
 async function stableSave(){if(aiProtection.current.length)return false;for(let tries=0;tries<4;tries++){if(formatErrorRef.current)return false;if(await session.flush())return !formatErrorRef.current;if(session.state().status!=='dirty')return false;}return false;}
 async function applyProposal(proposal:ProductProposal,_intent:ProductDecision,send:()=>Promise<AiResult>){if(!editor||profileDirty||restoreCommand||versionCommand||aiApplyingRef.current)throw Error('save_required');const change=proposal.change;if(!['resume-block','resume-add','resume-delete'].includes(change.kind))throw Error('invalid_proposal');aiApplyingRef.current=true;setAiApplying(true);if(!await stableSave()){aiApplyingRef.current=false;setAiApplying(false);throw Error('save_required');}aiProposal.current=proposal;aiBaseline.current=structuredClone(session.state().content);aiProtection.current=[change.kind==='resume-add'?change.afterBlockId:'blockId'in change?change.blockId:''];
  // Finish the editor transaction and revision handoff before the task view can discard an outdated response.
  const response=await send();await reconcileProposal(response);return response;
 }
 async function reconcileProposal(response:AiResult){const proposal=aiProposal.current;if(!proposal||!editor)return;const result=response.kind==='product_receipt'?response.receipt:response;if(result.kind==='receipt_missing')return;if(result.kind==='product_decided'&&result.state==='accepted'){
   const current=await request({operation:'resume.read',resumeId:opened.document.id});if(current.status!=='document')throw Error('read_unavailable');const application=result.resumeApplication;if(!application||application.before.id!==opened.document.id||application.after.id!==opened.document.id)throw Error('apply_receipt_unavailable');const live=fromEditor(editor.getJSON(),session.state().content.layout),change=proposal.change,id=change.kind==='resume-add'?change.afterBlockId:'blockId'in change?change.blockId:'',sectionId=live.sections.find(s=>s.blocks.some(b=>b.id===id))?.id;const merged=structuredClone(live),liveSection=merged.sections.find(s=>s.id===sectionId),formalSection=application.after.content.sections.find(s=>s.id===sectionId);
   if(!liveSection)throw Error('target_unavailable');const index=liveSection.blocks.findIndex(b=>b.id===id);if(change.kind==='resume-delete'){liveSection.blocks.splice(index,1);if(!liveSection.blocks.length)merged.sections=merged.sections.filter(s=>s.id!==sectionId);}else if(change.kind==='resume-add'){const block=formalSection?.blocks.find(b=>b.id===change.after.id);if(!block)throw Error('target_unavailable');liveSection.blocks.splice(index+1,0,block);}else{const block=formalSection?.blocks.find(b=>b.id===id);if(!block)throw Error('target_unavailable');liveSection.blocks[index]=block;}
   const same=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b),remoteChanged=!same(application.before.content,aiBaseline.current),localChanged=!same(live,aiBaseline.current);aiProtection.current=[];if(remoteChanged&&!localChanged){applyAiPatchUndoably(editor,application.before.content,false);Object.assign(merged,structuredClone(application.after.content));}applyAiPatchUndoably(editor,merged);if(current.document.revision!==application.after.revision||remoteChanged&&localChanged){session.compare({status:'conflict',document:current.document,profile:current.profile});setError('AI 本条已正式生效；其他窗口也有修改。你的输入保留，请比较后明确处理，未自动覆盖正式稿。');}else{session.adopted(application.after.content,application.after.revision,current.profile.revision);if(!same(merged,application.after.content))session.change(merged);setError('仅选定区块的提案已生效，可独立撤销；其他输入保留。');}
  }aiProtection.current=[];aiProposal.current=undefined;aiBaseline.current=undefined;aiApplyingRef.current=false;setAiApplying(false);
 }
 async function refreshHistory(){
  const generation=++historyReadGeneration.current;setHistoryReadStatus('loading');
  try{const result=await request({operation:'resume.versions',resumeId:opened.document.id});if(generation!==historyReadGeneration.current)return;if(result.status==='versions'){setVersions(result.versions);setHistoryReadStatus('loaded');}else setHistoryReadStatus('failed');}
  catch{if(generation===historyReadGeneration.current)setHistoryReadStatus('failed');}
 }
 async function finishVersion(result:Result,fromReceipt=false){setVersionMayContinue(false);if(result.status==='version'){setNaming(false);setVersionName('');setVersionCommand(undefined);await refreshHistory();if(result.version.kind==='export'&&window.careerPdf){try{await window.careerPdf.download(result.version.resumeId,result.version.id);}catch{setError('PDF 已冻结保存，但下载未完成；可从历史版本重新下载');editor?.commands.focus();return;}}setError(result.version.kind==='export'?'未命名导出快照及 PDF 已冻结，可作为实际发送候选':'命名版本及 PDF 已冻结保存');editor?.commands.focus();}else if(result.status==='conflict'){session.compare({status:'conflict',profile:result.profile,...('document' in result?{document:result.document}:{})});setVersionCommand(undefined);}else if(result.status==='not-found'&&fromReceipt){setVersionMayContinue(true);setError('已确认版本尚未生成，可以继续这次操作。');}else if(result.status==='pending-job'){setError('PDF 正在生成，尚未完成命名版本');}else{setError('版本生成失败，未产生完成版本；当前稿仍保留');setVersionCommand(undefined);}}
 async function exportPdf(){if(aiProtection.current.length||profileDirty||restoreCommand||versionCommand||namingBusy){setError('请先完成当前资料保存或核对');return;}if(!await stableSave()){setError('请先结束中文输入并完成正文保存');return;}const current=session.state();const input:Extract<Request,{operation:'resume.export'}>={operation:'resume.export',commandId:crypto.randomUUID(),resumeId:opened.document.id,expectedRevision:current.revision,expectedProfileRevision:current.profileRevision};setVersionCommand(input);setVersionMayContinue(false);setNamingBusy(true);try{await finishVersion(await request(input));}catch{setError('导出结果待核对，请检查是否已保存');}finally{setNamingBusy(false);}}
 async function nameVersion(){if(aiProtection.current.length||profileDirty){setError('请先保存基础资料的未提交输入，再冻结版本');return;}if(restoreCommand||namingBusy||versionCommand||!versionName.trim())return;if(!await stableSave()){setError('请先结束中文输入并解决当前稿保存状态');return;}const current=session.state();const input:Extract<Request,{operation:'resume.name-version'}>={operation:'resume.name-version',commandId:crypto.randomUUID(),resumeId:opened.document.id,expectedRevision:current.revision,expectedProfileRevision:current.profileRevision,name:versionName.trim()};setVersionCommand(input);setVersionMayContinue(false);setNamingBusy(true);try{await finishVersion(await request(input));}catch{setError('命名版本结果待核对，请检查是否已保存');}finally{setNamingBusy(false);}}
 async function finishRestore(result:Result,fromReceipt=false){
  setRestoreMayContinue(false);
  if(!editor)return;
  if(result.status==='document'){
   replaceUndoably(editor,result.document.content);session.adopted(result.document.content,result.document.revision,result.profile.revision);setProfile(result.profile);setViewed(undefined);setRestoreCommand(undefined);editor.setEditable(true,false);setError('已恢复正文；此替换可以撤销');
  }else if(result.status==='conflict'){session.compare({status:'conflict',profile:result.profile,...('document' in result?{document:result.document}:{})});setRestoreCommand(undefined);editor.setEditable(true);}
  else if(result.status==='not-found'&&fromReceipt){setRestoreMayContinue(true);setError('已确认尚未恢复，可以继续这次恢复。');}
  else{setError('未恢复，当前正文保留');setRestoreCommand(undefined);editor.setEditable(true);}
 }
 async function restore(version:Version){
  if(profileDirty){setError('请先保存姓名、联系方式和网页的未提交输入，再恢复版本。');return;}
  if(restoreCommand||!editor||!await stableSave()){setError('恢复前请先完成当前稿保存');return;}
  if(!window.confirm('恢复此版本的正文与布局？当前基础资料保持最新。'))return;
  const current=session.state();const input:Extract<Request,{operation:'resume.restore'}>={operation:'resume.restore',commandId:crypto.randomUUID(),resumeId:opened.document.id,versionId:version.id,expectedRevision:current.revision,expectedProfileRevision:current.profileRevision};
  setRestoreCommand(input);setRestoreMayContinue(false);setRestoreBusy(true);editor.setEditable(false);
  try{await finishRestore(await request(input));}catch{setError('恢复结果待核对；编辑暂受保护，请检查是否已保存。');}finally{setRestoreBusy(false);}
 }
 async function readCopyCandidates(){setCopyOpen(true);try{const result=await request({operation:'resume.copy-candidates',resumeId:opened.document.id});if(result.status==='copy-candidates')setCopyItems(result.items);else setError('其他机会的普通版本暂不可读');}catch{setError('其他机会的普通版本读取失败，当前稿保持不变');}}
 async function copyVersion(versionId:string){if(!editor||restoreCommand||profileDirty||versionCommand||!await stableSave()){setError('复制前请先完成当前稿保存');return;}if(!window.confirm('只复制这个普通版本的正文与布局到当前简历？全局身份、原版本和 PDF 不复制。此替换可以撤销。'))return;const current=session.state();const intent:Extract<Request,{operation:'resume.copy-version'}>={operation:'resume.copy-version',commandId:crypto.randomUUID(),resumeId:opened.document.id,versionId,expectedRevision:current.revision,expectedProfileRevision:current.profileRevision};setRestoreCommand(intent);setRestoreMayContinue(false);setRestoreBusy(true);editor.setEditable(false);try{await finishRestore(await request(intent));setCopyOpen(false);}catch{setError('复制结果待核对；请检查是否已保存，当前稿仍保留。');}finally{setRestoreBusy(false);}}
 function findNext(replace:boolean){if(!editor||!find||state.status==='composition'||restoreCommand)return;let match:{from:number;to:number}|undefined;editor.state.doc.descendants((node,pos)=>{if(match||!node.isText||!node.text)return;const offset=node.text.indexOf(find);if(offset>=0)match={from:pos+offset,to:pos+offset+find.length};});if(!match){setError('当前文稿没有找到该文字');return;}editor.chain().focus().setTextSelection(match).run();if(replace)editor.view.dispatch(editor.state.tr.insertText(replacement,match.from,match.to));}
 return <section className={'screen resume-feature'+(state.content.layout.template!=='a4-basic'?' miaoda-page':'')} id={active?'resume':undefined} data-feedback-owner="resume" data-feedback-id={opened.document.id}>
  {onReturn&&<button className="text-button link-back" onClick={onReturn}><NavigationIcon name="back"/>返回所属机会</button>}
  {state.content.layout.template!=='a4-basic'?<><MiaodaToolbar status={profileDirty?'未保存':statusLabels[state.status]} busy={state.status==='composition'||!!restoreCommand||namingBusy||!!versionCommand} onSave={()=>{if(profileDirty)identityForm.current?.requestSubmit();else void stableSave();}} onExport={()=>void exportPdf()} onHistory={()=>{setHistory(true);void refreshHistory();}} historyCount={historyReadStatus==='loaded'?versions.filter(v=>v.name).length:undefined} tools={<details ref={moreMenu} className="resume-more" onKeyDown={event=>{if(event.key==='Escape'){moreMenu.current?.removeAttribute('open');moreMenu.current?.querySelector('summary')?.focus();}}}><summary className="icon-button" aria-label="简历更多"><NavigationIcon name="more"/><span className="sr-only">更多工具</span></summary><div className="menu resume-more-menu" onClick={event=>{if((event.target as HTMLElement).closest('button'))event.currentTarget.closest('details')?.removeAttribute('open');}}>
   <button className="button" disabled={state.status==='composition'||!!restoreCommand} onClick={()=>setNaming(true)}>命名版本（⌘S）</button><button className="button" onClick={()=>{setHistory(value=>!value);void refreshHistory();}}>版本历史</button><button className="button" disabled={state.status==='composition'||!!restoreCommand} onClick={()=>void readCopyCandidates()}>复制其他机会普通版本内容</button><button className="button" onClick={()=>setFindOpen(value=>!value)}>查找替换</button><button className="button" onClick={()=>{setProfileOpen(value=>!value);}}>修改基础资料</button>
   <label className="field">模板<select aria-label="简历模板" disabled={state.status==='composition'||!!restoreCommand||aiApplying||profileDirty} value={state.content.layout.template} onChange={e=>setTemplate(e.target.value as CareerDocument['layout']['template'])}><option value="miaoda-paper">指定 A4 纸面</option><option value="a4-basic">原基础版式</option></select></label><label className="field">字号<select disabled={state.status==='composition'||!!restoreCommand} aria-label="简历字号" value={state.content.layout.fontSize} onChange={event=>session.change({...state.content,layout:{...state.content.layout,fontSize:Number(event.target.value)}})}>{[10,11,12,13,14].map(size=><option key={size}>{size}</option>)}</select></label>
   <div aria-label="姓名对齐">{(['left','center','right'] as const).map((alignment,index)=><button className="button" key={alignment} disabled={!editor||state.status==='composition'||!!restoreCommand||aiApplying} onClick={()=>setAlignment(alignment,true)}>姓名{['左对齐','居中','右对齐'][index]}</button>)}</div>
  </div></details>}/><p className="miaoda-context">{heading?.companyName??opened.opportunity.companyName} · {heading?.role??opened.opportunity.role}</p></>:<header className="page-header resume-head"><div className="title"><h1>简历</h1><p>{heading?.companyName??opened.opportunity.companyName} · {heading?.role??opened.opportunity.role}</p></div><div className="actions"><button className="button primary" disabled={state.status==='composition'||!!restoreCommand||namingBusy||!!versionCommand} onClick={()=>void exportPdf()}>导出 PDF（无需命名）</button><details ref={moreMenu} className="resume-more" onKeyDown={event=>{if(event.key==='Escape'){moreMenu.current?.removeAttribute('open');moreMenu.current?.querySelector('summary')?.focus();}}}><summary className="icon-button" aria-label="简历更多"><NavigationIcon name="more"/><span className="sr-only">更多工具</span></summary><div className="menu resume-more-menu" onClick={event=>{if((event.target as HTMLElement).closest('button'))event.currentTarget.closest('details')?.removeAttribute('open');}}>
   <button className="button" disabled={state.status==='composition'||!!restoreCommand} onClick={()=>setNaming(true)}>命名版本（⌘S）</button><button className="button" onClick={()=>{setHistory(value=>!value);void refreshHistory();}}>版本历史</button><button className="button" disabled={state.status==='composition'||!!restoreCommand} onClick={()=>void readCopyCandidates()}>复制其他机会普通版本内容</button><button className="button" onClick={()=>setFindOpen(value=>!value)}>查找替换</button><button className="button" onClick={()=>{setProfileOpen(value=>!value);}}>修改基础资料</button>
   <label className="field">字号<select disabled={state.status==='composition'||!!restoreCommand} aria-label="简历字号" value={state.content.layout.fontSize} onChange={event=>session.change({...state.content,layout:{...state.content.layout,fontSize:Number(event.target.value)}})}>{[10,11,12,13,14].map(size=><option key={size}>{size}</option>)}</select></label>
   <div aria-label="姓名对齐">{(['left','center','right'] as const).map((alignment,index)=><button className="button" key={alignment} disabled={!editor||state.status==='composition'||!!restoreCommand||aiApplying} onClick={()=>setAlignment(alignment,true)}>姓名{['左对齐','居中','右对齐'][index]}</button>)}</div>
  </div></details></div></header>}

  <div className="resume-tools" aria-label="简历格式工具"><div className="format-group">
   <button className="icon-button" aria-label="加粗" aria-pressed={editor?.isActive('bold')??false} disabled={!editor||state.status==='composition'||!!restoreCommand} onMouseDown={event=>event.preventDefault()} onClick={()=>editor?.chain().focus().toggleBold().run()}><b>B</b></button>
   <button className="icon-button" aria-label="斜体" aria-pressed={editor?.isActive('italic')??false} disabled={!editor||state.status==='composition'||!!restoreCommand} onMouseDown={event=>event.preventDefault()} onClick={()=>editor?.chain().focus().toggleItalic().run()}><i>I</i></button>
   <button className="icon-button" aria-label="要点列表" disabled={!editor||state.status==='composition'||!!restoreCommand} onMouseDown={event=>event.preventDefault()} onClick={()=>editor?.chain().focus().toggleBulletList().run()}>☷</button><span className="tool-divider"/>
   {(['left','center','right'] as const).map((alignment,index)=><button className="icon-button" key={alignment} aria-label={'正文'+['左对齐','居中','右对齐'][index]} disabled={!editor||state.status==='composition'||!!restoreCommand||aiApplying} onMouseDown={event=>event.preventDefault()} onClick={()=>setAlignment(alignment)}>{['≡','☰','≣'][index]}</button>)}<span className="tool-divider"/>
   <button className="icon-button" aria-label="撤销" disabled={!editor||state.status==='composition'||!!restoreCommand||aiApplying} onMouseDown={event=>event.preventDefault()} onClick={()=>editor?.chain().focus().undo().run()}>↶</button><button className="icon-button" aria-label="重做" disabled={!editor||state.status==='composition'||!!restoreCommand||aiApplying} onMouseDown={event=>event.preventDefault()} onClick={()=>editor?.chain().focus().redo().run()}>↷</button>
   {aiSupported&&<button className="button ghost" aria-label="简历优化提案" disabled={state.status==='composition'||!!restoreCommand||aiApplying} onMouseDown={event=>event.preventDefault()} onClick={()=>setAiOpen(value=>!value)}><NavigationIcon name="spark"/>AI 建议</button>}
  </div><span className={'save'+(state.status==='saved'?'':' unsaved')}><i className="save-dot"/><span role="status" data-testid="resume-save-state">{formatError?'格式不受支持，当前输入未保存':statusLabels[state.status]}</span></span></div>
  {aiApplying&&<p role="status">正在将本条 AI 修改加入正文，完成或核对前暂停撤销和重做。</p>}
  <AuxiliaryPanel open={aiOpen&&aiSupported} label="简历建议" onClose={()=>setAiOpen(false)} small modal={false}><div aria-label="简历优化选择"><p>明确选择需要改写、增补或删除的区块；其他内容继续由你编辑。采纳前会核对当前区块，身份默认不外发。</p>{state.content.sections.flatMap(section=>section.blocks.map(block=><label key={block.id}><input disabled={aiApplying||aiTaskLocked} type="checkbox" checked={aiBlocks.includes(block.id)} onChange={event=>setAiBlocks(old=>event.target.checked?[...old,block.id]:old.filter(id=>id!==block.id))}/>{section.title} · {block.type==='paragraph'?block.spans.map(s=>s.text).join('').slice(0,60):'要点列表'}</label>))}{aiBlocks.length>0&&<ProductTaskPage target={{kind:'resume-optimize',resumeId:opened.document.id,blockIds:aiBlocks,changeKinds:['rewrite','add','delete']}} purgeNotice={purgeNotice} beforePrepare={stableSave} onProtected={setAiTaskLocked} apply={applyProposal} onResolved={reconcileProposal}/>}</div></AuxiliaryPanel>
  {findOpen&&<div className="resume-panel"><label className="field">查找<input autoFocus value={find} onChange={event=>setFind(event.target.value)}/></label><label className="field">替换为<input value={replacement} onChange={event=>setReplacement(event.target.value)}/></label><button className="button" onClick={()=>findNext(false)}>定位</button><button className="button" onClick={()=>findNext(true)}>替换一处</button><button className="button" onClick={()=>{setFindOpen(false);editor?.commands.focus();}}>关闭查找</button></div>}
  {state.status==='unknown'&&<aside><button className="button" onClick={()=>void session.verify()}>检查是否已保存</button>{state.mayContinue&&<button className="button" onClick={()=>void session.continueOriginal()}>继续这次保存</button>}</aside>}
  {state.status==='failed'&&<aside><p>保存未成功，当前编辑内容保留。</p><button className="button" onClick={async()=>{try{const result=await request({operation:'resume.read',resumeId:opened.document.id});if(result.status==='document')session.compare({status:'conflict',profile:result.profile,document:result.document});else setError('当前正式稿暂不可读，保留你的输入');}catch{setError('当前正式稿读取失败，保留你的输入');}}}>比较后重新保存</button></aside>}
  {state.comparison&&<aside><p>当前正式正文如下；你的当前稿仍在纸面上。</p><pre>{state.comparison.document?.content.sections.map(section=>section.title+'\n'+section.blocks.map(block=>block.type==='paragraph'?block.spans.map(span=>span.text).join(''):block.items.map(item=>item.spans.map(span=>span.text).join('')).join('\n')).join('\n')).join('\n\n')}</pre><button className="button" onClick={()=>session.useComparisonRevision()}>确认以正式版本为基线保存我的输入</button><button className="button" onClick={()=>{const current=state.comparison;if(current?.document&&editor){replaceUndoably(editor,current.document.content);session.adopted(current.document.content,current.document.revision,current.profile.revision);}}}>放弃本地正文，采用正式正文</button></aside>}
  {restoreCommand&&!restoreBusy&&<aside><p>恢复结果待核对，当前正文仍保留。为避免覆盖，核对前暂停正文编辑。</p><button className="button" onClick={async()=>{try{await finishRestore(await request({operation:'resume.receipt',commandId:restoreCommand.commandId}),true);}catch{setError('恢复结果仍无法核对');}}}>检查是否已恢复</button>{restoreMayContinue&&<button className="button" onClick={async()=>{setRestoreMayContinue(false);setRestoreBusy(true);try{await finishRestore(await request(restoreCommand));}catch{setError('恢复结果待核对');}finally{setRestoreBusy(false);}}}>继续这次恢复</button>}</aside>}
  {versionCommand?.operation==='resume.export'&&!namingBusy&&<aside><p>未命名导出结果待核对，当前输入保留。</p><button className="button" onClick={async()=>{try{await finishVersion(await request({operation:'resume.receipt',commandId:versionCommand.commandId}),true);}catch{setError('仍无法核对导出结果');}}}>检查是否已导出</button>{versionMayContinue&&<button className="button" onClick={async()=>{setVersionMayContinue(false);setNamingBusy(true);try{await finishVersion(await request(versionCommand));}catch{setError('导出结果待核对');}finally{setNamingBusy(false);}}}>继续这次导出</button>}</aside>}
  {formatError&&<p role="alert">{formatError}</p>}{error&&!naming&&<p role="alert">{error}</p>}{historyReadStatus==='failed'&&!history&&<aside><p role="alert">版本历史读取失败，缓存可能不完整；已保存的版本保持不变。</p><button className="button" onClick={()=>void refreshHistory()}>重新读取版本历史</button></aside>}{historyReadStatus==='loading'&&!history&&<p role="status">正在读取版本历史…</p>}{overflow&&<p>正文超过一页 A4；导出将自动分页，请检查 PDF 页数。</p>}
  {state.content.layout.template==='a4-basic'&&<div hidden={!profileOpen}><ProfileFields key={profilePurge} profile={profile} request={request} onDirty={setProfileDirty} onSaved={current=>{setProfile(current);session.profileRevision(current.revision);queryClient.setQueryData(['resume',opened.document.opportunityId,'profile'],current);}}/><button className="text-button" onClick={()=>{setProfileOpen(false);editor?.commands.focus();}}>收起基础资料（保留输入）</button></div>}
  <label hidden={state.content.layout.template!=='a4-basic'} className="miaoda-template-picker">简历模板<select aria-label="简历模板" disabled={state.status==='composition'||!!restoreCommand||aiApplying||profileDirty} value={state.content.layout.template} onChange={e=>setTemplate(e.target.value as CareerDocument['layout']['template'])}><option value="miaoda-paper">指定 A4 纸面</option><option value="a4-basic">原基础版式</option></select></label>
  <div className="source-paper-controls"><button className="text-button" disabled={state.status==='composition'||!!restoreCommand||aiApplying} onClick={()=>addEntry('experience')}>添加工作经历</button><button className="text-button" disabled={state.status==='composition'||!!restoreCommand||aiApplying} onClick={()=>addEntry('project')}>添加项目</button><button className="text-button" disabled={state.status==='composition'||!!restoreCommand||aiApplying} onClick={()=>addEntry('education')}>添加教育经历</button><button className="text-button" disabled={state.status==='composition'||!!restoreCommand||aiApplying} onClick={()=>addSection('skills')}>添加技能分区</button></div>
  <div ref={setIdentitySupport}/><SourcePaperStage onOverflow={setOverflow}><article className={`paper resume-paper${state.content.layout.template==='a4-basic'?'':' source-paper'} resume-font-${state.content.layout.fontSize}`} aria-label="简历编辑纸面" style={{'--source-scale':state.content.layout.fontSize/12*(state.content.layout.contentScale??1)} as React.CSSProperties}>
   <header className="paper-header" data-testid="resume-name-layout" data-name-alignment={state.content.layout.identityNameAlignment??'left'} style={{textAlign:state.content.layout.identityNameAlignment??'left'}}>{state.content.layout.template==='a4-basic'?<><h2 onClick={()=>setProfileOpen(true)}>{profile.name||'尚未填写姓名'}</h2>{profile.contact&&<p>{profile.contact}</p>}{profile.links.length>0&&<p>{profile.links.map((link,index)=><a key={index} href={link.href} target="_blank" rel="noreferrer">{link.label}</a>)}</p>}</>:<ProfileFields key={profilePurge} plain formRef={identityForm} support={identitySupport} profile={profile} request={request} onDirty={setProfileDirty} onSaved={current=>{setProfile(current);session.profileRevision(current.revision);queryClient.setQueryData(['resume',opened.document.opportunityId,'profile'],current);}}/>}</header>
   <EditorContent editor={editor}/>
  </article></SourcePaperStage>

  <AuxiliaryPanel open={copyOpen} label="复制普通版本" small onClose={()=>setCopyOpen(false)}><aside className="resume-panel" aria-label="复制普通版本"><h2>其他机会的普通版本</h2><p>只复制正文与布局；不复制身份、历史或导出文件。</p>{copyItems.length===0&&<p>暂无其他机会的普通命名版本。</p>}{copyItems.map(item=><button className="button" key={item.versionId} onClick={()=>void copyVersion(item.versionId)}>{item.companyName} · {item.role} · {item.name}</button>)}<button className="button" onClick={()=>{setCopyOpen(false);editor?.commands.focus();}}>取消复制，继续当前稿</button></aside></AuxiliaryPanel>
  <AuxiliaryPanel open={history} label="命名版本 / 历史" onClose={()=>{setHistory(false);setViewed(undefined);}}><aside className="resume-history"><h2>命名版本历史</h2>{history&&historyReadStatus==='failed'&&<><p role="alert">版本历史读取失败，缓存可能不完整；已保存的版本保持不变。</p><button className="button" onClick={()=>void refreshHistory()}>重新读取版本历史</button></>}{historyReadStatus==='loading'&&<p role="status">正在读取版本历史…</p>}{historyReadStatus==='loaded'&&versions.length===0&&<p>尚未创建命名版本。</p>}{versions.map(version=><button className="button" key={version.id} onClick={()=>setViewed(version)}>{version.name||'未命名导出'}</button>)}<button className="button" onClick={()=>{setHistory(false);setViewed(undefined);editor?.commands.focus();}}>关闭历史</button>{viewed&&<div><h3>{viewed.name||'未命名导出'}（冻结材料）</h3>{viewed.snapshot.content.layout.template!=='a4-basic'?<SourcePaperStage><article className="paper source-paper" style={{'--miaoda-font-scale':viewed.snapshot.content.layout.fontSize/12,'--source-scale':viewed.snapshot.content.layout.fontSize/12*(viewed.snapshot.content.layout.contentScale??1)} as React.CSSProperties} aria-label="历史简历纸面"><header className="paper-header"><h2 data-testid="frozen-resume-name" style={{textAlign:viewed.snapshot.content.layout.identityNameAlignment??'left'}}>{viewed.snapshot.profile.name}</h2><p>{viewed.snapshot.profile.contact}</p>{viewed.snapshot.profile.links.length>0&&<p>{viewed.snapshot.profile.links.map((l,i)=><React.Fragment key={i}>{i>0&&' · '}<a href={l.href}>{l.label}</a></React.Fragment>)}</p>}</header><FrozenResumeBody content={viewed.snapshot.content}/></article></SourcePaperStage>:<><p data-testid="frozen-resume-name" style={{textAlign:viewed.snapshot.content.layout.identityNameAlignment??'left'}}>{viewed.snapshot.profile.name}</p><p>{viewed.snapshot.profile.contact}</p><FrozenResumeBody content={viewed.snapshot.content}/></>}<p>对应 PDF 已保留，{viewed.pdf.size} 字节；源正文不会被当前编辑改写。</p><>{window.careerPdf&&<button className="button" onClick={()=>void window.careerPdf!.download(viewed.resumeId,viewed.id).catch(()=>setError('PDF 下载未完成，已保存版本保持不变'))}>下载 PDF</button>}</><button className="button" onClick={()=>void restore(viewed)}>恢复此版本正文</button><button className="button" onClick={()=>{setViewed(undefined);editor?.commands.focus();}}>取消查看 / 恢复</button></div>}</aside></AuxiliaryPanel>
  <AuxiliaryPanel open={naming} small label="命名简历版本" onClose={()=>{if(!namingBusy){setNaming(false);editor?.commands.focus();}}}><div className="form"><h2>命名版本</h2>{naming&&error&&<p role="alert">{error}</p>}<label className="field">版本名称<input disabled={namingBusy||!!versionCommand} autoFocus maxLength={120} value={versionName} onChange={event=>setVersionName(event.target.value)}/></label><button className="button" disabled={namingBusy||!!versionCommand} onClick={()=>void nameVersion()}>保存版本及 PDF</button>{versionCommand&&!namingBusy&&<><button className="button" onClick={async()=>{try{await finishVersion(await request({operation:'resume.receipt',commandId:versionCommand.commandId}),true);}catch{setError('仍无法核对版本结果');}}}>检查是否已生成版本</button>{versionMayContinue&&<button className="button" onClick={async()=>{setVersionMayContinue(false);setNamingBusy(true);try{await finishVersion(await request(versionCommand));}catch{setError('版本结果待核对');}finally{setNamingBusy(false);}}}>继续生成这次版本</button>}</>}<button className="button" disabled={namingBusy} onClick={()=>{setNaming(false);editor?.commands.focus();}}>关闭，保留当前稿</button></div></AuxiliaryPanel>
 </section>;
}
/** Nested Opportunity view. Keeping this component mounted retains independent editor sessions. */
export function ResumePage({purgeNotice,request,profileRequest,opportunityId,onReturn,active=true,embedded=false,heading}:{purgeNotice?:PurgeNotice;request:(input:ResumeRequest)=>Promise<ResumeResult>;profileRequest:(input:ProfileRequest)=>Promise<ProfileResult>;opportunityId:string;onReturn?:()=>void;active?:boolean;embedded?:boolean;heading?:{id:string;companyName:string;role:string}}){
 const dispatch:Transport=input=>input.operation==='profile.read'||input.operation==='profile.save'||input.operation==='profile.receipt'?profileRequest(input):request(input);
 const [blocked,setBlocked]=useState<string[]>([]);
 const [documents,setDocuments]=useState<Record<string,Opened>>({});const [error,setError]=useState('');const transport=useRef(dispatch);transport.current=dispatch;
 useEffect(()=>{if(!purgeNotice)return;const removed=Object.entries(documents).filter(([id,doc])=>wasPurged(purgeNotice,'resume',doc.document.id)||wasPurged(purgeNotice,'opportunity',id)).map(([id])=>id);if(!removed.length)return;setBlocked(old=>[...new Set([...old,...removed])]);setDocuments(old=>Object.fromEntries(Object.entries(old).filter(([id])=>!removed.includes(id))));setError('选定简历已永久清除；原编辑器与历史已关闭。');},[purgeNotice?.sequence]);
 useEffect(()=>{let active=true;if(documents[opportunityId]||blocked.includes(opportunityId))return;setError('');void transport.current({operation:'resume.open',commandId:crypto.randomUUID(),opportunityId}).then(result=>{if(!active)return;if(result.status==='document')setDocuments(current=>({...current,[opportunityId]:result}));else setError('无法打开指定机会的简历，请返回所属机会。');}).catch(()=>{if(active)setError('简历打开结果待核对，请返回机会后重新打开原对象。');});return()=>{active=false;};},[opportunityId,documents,blocked]);
 return <>{blocked.includes(opportunityId)&&<button className="button" onClick={()=>{setBlocked(old=>old.filter(id=>id!==opportunityId));setError('');}}>明确开始新的当前简历</button>}{error&&<p role="alert">{error}</p>}{!documents[opportunityId]&&!error&&<p>正在读取简历…</p>}{Object.entries(documents).map(([id,opened])=><div key={id} hidden={id!==opportunityId}><ResumeEditor heading={heading?.id===id?heading:undefined} embedded={embedded} purgeNotice={purgeNotice} opened={opened} request={dispatch} onReturn={onReturn} active={active&&id===opportunityId}/></div>)}</>;
}
