import {cp,mkdir,readFile,writeFile,chmod,rm} from 'node:fs/promises';import path from 'node:path';import {execFileSync} from 'node:child_process';import {chromium} from 'playwright';
if(process.platform!=='darwin'||process.arch!=='arm64')throw Error('E1 package currently verified only on macOS arm64');
const application=path.resolve('out/Career-E1-arm64/Career.app'),contents=path.join(application,'Contents'),resources=path.join(contents,'Resources');
await mkdir(path.join(contents,'MacOS'),{recursive:true});await mkdir(resources,{recursive:true});
await cp('dist/application',path.join(resources,'application'),{recursive:true});
// Electron artifacts remain in the repository fallback, but are never included in this new runtime bundle.
const {unlink}=await import('node:fs/promises');for(const name of ['main.cjs','preload.cjs','utility.cjs','workspace-check.cjs'])await unlink(path.join(resources,'application',name)).catch(error=>{if(error.code!=='ENOENT')throw error;});
await cp('dist/recovery-renderer',path.join(resources,'recovery-renderer'),{recursive:true});
await cp('dist/materials-renderer',path.join(resources,'materials-renderer'),{recursive:true});await mkdir(path.join(resources,'runtime'),{recursive:true});await cp('node_modules/node/bin/node',path.join(resources,'runtime/node'));await chmod(path.join(resources,'runtime/node'),0o755);
for(const name of ['better-sqlite3','playwright','playwright-core'])await cp('node_modules/'+name,path.join(resources,'application/node_modules',name),{recursive:true});
const engine=chromium.executablePath();const engineBundle=engine.slice(0,engine.indexOf('.app/')+4);if(!engineBundle.endsWith('.app'))throw Error('Pinned Chrome for Testing bundle required');const bundledEngine=path.join(resources,'engine/Chrome for Testing.app');await rm(bundledEngine,{recursive:true,force:true});await cp(engineBundle,bundledEngine,{recursive:true,verbatimSymlinks:true});
const manifest=JSON.parse(await readFile('dist/application/pdf-environment.json','utf8'));manifest.executable=path.relative(path.join(resources,'application'),path.join(resources,'engine/Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing'));await writeFile(path.join(resources,'application/pdf-environment.json'),JSON.stringify(manifest,null,2));
await cp('dist/application/career-launcher',path.join(contents,'MacOS/Career'));await chmod(path.join(contents,'MacOS/Career'),0o755);
await writeFile(path.join(contents,'Info.plist'),`<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>CFBundleExecutable</key><string>Career</string><key>CFBundleIdentifier</key><string>dev.career.next.launcher</string><key>CFBundleName</key><string>Career</string><key>CFBundleDisplayName</key><string>Career</string><key>CFBundleVersion</key><string>1</string><key>CFBundleShortVersionString</key><string>0.0.0</string><key>CFBundlePackageType</key><string>APPL</string><key>LSUIElement</key><true/><key>LSMinimumSystemVersion</key><string>14.0</string></dict></plist>`);
execFileSync('/usr/bin/codesign',['--force','--deep','--sign','-',application],{stdio:'inherit'});console.log(application);
