import type Database from 'better-sqlite3';
import {Draft} from '../../../../contracts/opportunity/communication/schema';
import type {Provenance} from '../../../../contracts/common/provenance';
import type {OpportunityCapabilities} from '../../../../contracts/opportunity/capabilities';
import {executeCommand,redactedCommandResults} from '../../../platform/commands/receipts';
export const draftMigration=`CREATE TABLE opportunity_communication_drafts(opportunity_id TEXT PRIMARY KEY,body_json TEXT NOT NULL);`;
export function createCommunicationDrafts(db:Database.Database,core:OpportunityCapabilities){
 function read(opportunityId:string){if(!core.readOpportunity(opportunityId))throw Error('not_found');const row=db.prepare('SELECT body_json FROM opportunity_communication_drafts WHERE opportunity_id=?').get(opportunityId) as {body_json:string}|undefined;return row?Draft.parse(JSON.parse(row.body_json)):Draft.parse({opportunityId,revision:0,text:''});}
 function save(input:{commandId:string;opportunityId:string;expectedRevision:number;text:string;provenance?:Provenance[]}){return executeCommand(db,'communication.draft',input.commandId,input,()=>{const old=read(input.opportunityId);if(old.revision!==input.expectedRevision)throw Error('conflict');const draft=Draft.parse({opportunityId:old.opportunityId,revision:old.revision+1,text:input.text,...input.provenance??old.trustedProvenance?{trustedProvenance:input.provenance??old.trustedProvenance}:{}});db.prepare('INSERT INTO opportunity_communication_drafts VALUES(?,?) ON CONFLICT(opportunity_id) DO UPDATE SET body_json=excluded.body_json').run(draft.opportunityId,JSON.stringify(draft));return {kind:'draft' as const,draft};});}
 function purge(id:string){db.prepare('DELETE FROM opportunity_communication_drafts WHERE opportunity_id=?').run(id);redactedCommandResults(db,'communication.draft',result=>(result as {draft?:Draft}).draft?.opportunityId===id,{kind:'failure',code:'content_purged'});}
 return {read,save,purge,purgeImpact(id:string){const row=db.prepare('SELECT body_json FROM opportunity_communication_drafts WHERE opportunity_id=?').get(id) as {body_json:string}|undefined;const draft=row?Draft.parse(JSON.parse(row.body_json)):{revision:0};return draft.revision?{id,revision:draft.revision,name:'当前沟通草稿（未发送）',blobIds:[]}:undefined;}};
}
export function validateDraftCandidate(db:Database.Database){for(const row of db.prepare('SELECT opportunity_id,body_json FROM opportunity_communication_drafts').all() as {opportunity_id:string;body_json:string}[]){const draft=Draft.parse(JSON.parse(row.body_json));if(draft.opportunityId!==row.opportunity_id||draft.revision<1)throw Error('invalid_candidate');}}
export function draftCandidateRelations(db:Database.Database){return (db.prepare('SELECT body_json FROM opportunity_communication_drafts').all() as {body_json:string}[]).flatMap(row=>{const draft=Draft.parse(JSON.parse(row.body_json));return [{owner:'opportunity',objectId:draft.opportunityId,kind:'object' as const},...(draft.trustedProvenance??[]).map(p=>({owner:p.owner,objectId:p.objectId,kind:'object' as const,provenance:p}))];});}
