import {wasPurged,type PurgeNotice} from '../../design-system/purge-notice';
import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {useLocation} from 'react-router';
import {Result as ApplicationResult,type PurgePlan} from '../../../contracts/application/schema';
import {FeedbackResult,type Feedback,type FeedbackRequest} from '../../../contracts/application/feedback';
import '../../../contracts/opportunity/submission/file-selection';
import './feedback.css';
const request=async(input:FeedbackRequest)=>ApplicationResult.parse(await window.career.request('application',input));
export function FeedbackOverlay({onPurged,purgeNotice}:{purgeNotice?:PurgeNotice;onPurged:(refs:{owner:string;objectId:string}[])=>void}){
 const location=useLocation();const [open,setOpen]=useState(false),[text,setText]=useState(''),[screenshot,setScreenshot]=useState<{id:string;name:string}>(),[pending,setPending]=useState<FeedbackRequest>(),[status,setStatus]=useState(''),[technical,setTechnical]=useState(''),[busy,setBusy]=useState(false),[items,setItems]=useState<Feedback[]>([]),[selected,setSelected]=useState<Feedback>(),[append,setAppend]=useState(''),[view,setView]=useState<'new'|'list'|'detail'>('new'),[plan,setPlan]=useState<PurgePlan>(),[copies,setCopies]=useState<string[]>([]);const epoch=useRef(0),panel=useRef<HTMLDivElement>(null),previousFocus=useRef<HTMLElement|null>(null),previousRange=useRef<Range|null>(null),path=useRef('/');
 useEffect(()=>{if(!open)return;const root=document.getElementById('root');if(root)root.inert=true;const first=panel.current?.querySelector<HTMLElement>('textarea,input,button');first?.focus();return()=>{if(root)root.inert=false;const original=previousFocus.current;if(original?.isConnected){original.focus({preventScroll:true});if(previousRange.current&&original.isContentEditable){const selection=window.getSelection();selection?.removeAllRanges();try{selection?.addRange(previousRange.current);}catch{/* Owner editor remains mounted; stale DOM ranges are not restored. */}}}};},[open]);
 const dirty=!!text.trim()||!!screenshot||!!append.trim()||!!pending;
 useEffect(()=>{if(!dirty)return;const guard=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty]);
 function show(){previousFocus.current=document.activeElement as HTMLElement;const selection=window.getSelection();previousRange.current=selection?.rangeCount?selection.getRangeAt(0).cloneRange():null;path.current=location.pathname;setOpen(true);}
 function close(){if(pending){setOpen(false);return;}if(dirty&&!window.confirm('关闭反馈并保留反馈草稿？底下业务输入保持原样。'))return;setOpen(false);}
 useEffect(()=>{if(!purgeNotice)return;epoch.current++;setItems(old=>old.filter(item=>!wasPurged(purgeNotice,'feedback',item.id)));if(wasPurged(purgeNotice,'feedback',selected?.id)){setSelected(undefined);setAppend('');setPlan(undefined);setPending(undefined);setView('list');setStatus('相关反馈已永久清除，原正文与附件引用已关闭。');}if(wasPurged(purgeNotice,'actual-artifact',screenshot?.id)){setScreenshot(undefined);}setBusy(false);},[purgeNotice?.sequence]);
 async function list(){const generation=epoch.current;setView('list');try{const result=await request({operation:'feedback.list'});if(generation!==epoch.current)return;if(result.kind==='feedback_list')setItems(result.items);else setStatus('反馈列表暂不可读。');}catch{setStatus('反馈列表读取失败；草稿仍保留。');}}
 async function accept(result:ReturnType<typeof ApplicationResult.parse>,intent:FeedbackRequest){if(result.kind==='feedback'){setSelected(result.feedback);setPending(undefined);setStatus('反馈已保存。');if(intent.operation==='feedback.create'){setText('');setScreenshot(undefined);setView('new');setOpen(false);}else{setAppend('');setView('detail');}}else if(result.kind==='feedback_conflict'){setSelected(result.feedback);setPending(undefined);setStatus('其他窗口已更新反馈；你的补充保留，请比较后重新提交。');}else if(result.kind==='receipt_missing'){setStatus('已确认尚未保存，可以继续这次保存。');}else{setPending(undefined);setTechnical(result.kind==='failure'?result.code:'unexpected_result');setStatus('没有保存成功，你的输入仍保留。');}}
 async function send(intent:FeedbackRequest,lookup=false){const generation=epoch.current;setBusy(true);setPending(intent);try{const result=await request(lookup&&'commandId'in intent?{operation:'feedback.receipt',commandId:intent.commandId}:intent);if(generation===epoch.current)await accept(result,intent);}catch{setStatus('反馈保存结果暂时无法确认；先检查是否已保存，不重复创建。');}finally{setBusy(false);}}
 async function discardScreenshot(id:string){const result=await request({operation:'feedback.discard-screenshot',commandId:crypto.randomUUID(),candidateId:id});if(result.kind!=='feedback_screenshot_discarded')throw Error('discard_failed');}
 async function exportOne(){if(!selected)return;const generation=epoch.current;try{const result=FeedbackResult.parse(await request({operation:'feedback.export',id:selected.id}));if(generation===epoch.current&&result.kind==='feedback_export'){const url=URL.createObjectURL(new Blob([result.text],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download=result.filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),30000);setStatus('已请求导出反馈（包含可读附件；缺失附件会明确标注）。');}}catch{setStatus('反馈导出失败。');}}
 async function preparePurge(){if(!selected||dirty)return;try{const result=ApplicationResult.parse(await window.career.request('application',{operation:'data.purge.plan',references:[{owner:'feedback',objectId:selected.id}]}));if(result.kind==='purge_plan'){setPlan(result.plan);setCopies(result.plan.copies.filter(c=>c.kind==='current_workspace').map(c=>c.id));}else setStatus('清除预览失败。');}catch{setStatus('清除预览暂不可用。');}}
 async function purge(){if(!plan)return;setBusy(true);try{const result=ApplicationResult.parse(await window.career.request('application',{operation:'data.purge.confirm',planId:plan.id,selectedCopyIds:copies,confirmed:true}));if(result.kind==='purged'){onPurged(plan.impact.references);setSelected(undefined);setPlan(undefined);setStatus(result.remainingCopyIds.length?'选定范围已清除，未选备份仍可能含副本。':'受管理副本已清除；外部导出文件不在清除范围。');await list();}else{if(result.kind==='failure'&&result.code==='purge_incomplete'){onPurged(plan.impact.references);setSelected(undefined);setItems([]);setPlan(undefined);}setTechnical(result.kind==='failure'?result.code:'unknown');setStatus('清除尚未完成，请检查状态再继续。');}}catch{setStatus('清除结果尚未确认，请打开设置与资料维护核对。');}finally{setBusy(false);}}
 return <><button onMouseDown={e=>e.preventDefault()} onClick={show}>反馈</button>{open&&createPortal(<div className="feedback-backdrop"><div ref={panel} className="feedback-dialog" role="dialog" aria-modal="true" aria-label="Career 反馈" onKeyDown={e=>{if(e.key==='Escape'&&!busy){e.preventDefault();close();}if(e.key==='Tab'){const nodes=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),textarea:not(:disabled),input:not(:disabled)'));const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}}><h2>反馈</h2><p>只记录位置和版本，不自动抓取业务正文或截图。</p><button disabled={busy} onClick={()=>setView('new')}>填写反馈</button><button disabled={busy} onClick={()=>void list()}>查看反馈</button><button disabled={busy} onClick={close}>返回原任务（保留反馈草稿）</button>
 {view==='new'&&<form onSubmit={e=>{e.preventDefault();if(!text.trim()||pending)return;const object=Array.from(document.querySelectorAll<HTMLElement>('[data-feedback-id]')).find(el=>el.checkVisibility()&&el.dataset.feedbackId);const objectPath=object?'/'+object.dataset.feedbackOwner+'/'+object.dataset.feedbackId:path.current;void send({operation:'feedback.create',commandId:crypto.randomUUID(),text,location:{path:objectPath,version:'career-next-g5'},...screenshot?{screenshotCandidateId:screenshot.id}:{}});}}><fieldset disabled={busy||!!pending}><label>反馈内容<textarea aria-label="反馈内容" maxLength={10000} value={text} onChange={e=>setText(e.target.value)} required/></label><button type="button" onClick={async()=>{try{const result=await window.careerSentFiles.select();if(result){if(screenshot)await discardScreenshot(screenshot.id);setScreenshot(result);}}catch{setStatus('截图选择失败；请选 PNG/JPEG/WebP，最多 2MB。');}}}>选择截图文件（可选）</button>{screenshot&&<p>{screenshot.name}<button type="button" onClick={async()=>{if(!screenshot)return;try{await discardScreenshot(screenshot.id);setScreenshot(undefined);}catch{setStatus('附件取消结果未确认，保留原候选；可到资料维护核对。');}}}>不附这张截图</button></p>}<button>保存反馈并返回原任务</button></fieldset></form>}
 {view==='list'&&<ul>{items.map(item=><li key={item.id}><button onClick={()=>{setSelected(item);setView('detail');setPlan(undefined);}}>{item.entries[0]?.text} {item.archived?'（已归档）':''}</button></li>)}</ul>}
 {view==='detail'&&selected&&<article><details><summary>查看技术详情</summary><p>位置：{selected.location.path} · {selected.location.version}</p></details>{selected.entries.map((entry,index)=><p key={index}>{entry.text} · {entry.recordedAt}</p>)}{selected.screenshot&&<p>附件：{selected.screenshot.name}（导出时核对可读性）</p>}<fieldset disabled={busy||!!pending}><label>补充反馈<textarea value={append} onChange={e=>setAppend(e.target.value)} maxLength={10000}/></label><button disabled={!append.trim()} onClick={()=>void send({operation:'feedback.append',commandId:crypto.randomUUID(),id:selected.id,expectedRevision:selected.revision,text:append})}>保存补充</button><button onClick={()=>void send({operation:'feedback.archive',commandId:crypto.randomUUID(),id:selected.id,expectedRevision:selected.revision,archived:!selected.archived})}>{selected.archived?'取消归档':'归档反馈'}</button><button onClick={()=>void exportOne()}>导出反馈与附件</button><button disabled={dirty} onClick={()=>void preparePurge()}>预览永久清除反馈</button></fieldset></article>}
 {plan&&<aside><h3>永久清除影响</h3><p>{plan.impact.description}</p><p>{plan.externalLimit}</p><p>未勾选的备份仍可能保留反馈，导出的文件不会被撤回。</p>{plan.copies.map(copy=><label key={copy.id}><input type="checkbox" checked={copies.includes(copy.id)} onChange={e=>setCopies(old=>e.target.checked?[...old,copy.id]:old.filter(id=>id!==copy.id))}/>{copy.kind} · {copy.relativePath}</label>)}<button disabled={busy} onClick={()=>{if(window.confirm('永久清除所选受管理副本中的这条反馈及截图？'))void purge();}}>确认永久清除选定副本</button><button onClick={()=>setPlan(undefined)}>取消清除</button></aside>}
 {pending&&<aside><button disabled={busy} onClick={()=>void send(pending,true)}>检查是否已保存</button>{status.includes('确认尚未保存')&&<button disabled={busy} onClick={()=>void send(pending)}>继续这次保存</button>}<p>关闭后仍保留这次待确认的保存，避免重复反馈。</p></aside>}<p role="status">{status}</p>{technical&&<details><summary>查看技术详情</summary><p>{technical}</p></details>}</div></div>,document.body)}</>;
}
