import {randomUUID} from 'node:crypto';
import path from 'node:path';
import {existsSync,lstatSync,mkdirSync,readFileSync,renameSync,openSync,writeFileSync,fsyncSync,closeSync} from 'node:fs';
import {z} from 'zod';
export const Copy=z.strictObject({id:z.uuid(),relativePath:z.string().min(1).max(500),kind:z.enum(['current_workspace','old_workspace','restore_candidate','quarantine','backup','failed_backup','staging','blobs','proposals','summaries','cache']),state:z.enum(['candidate','ready','failed','purging','purged']),sourceCopyId:z.uuid().optional(),createdAt:z.string(),reason:z.string().max(100).optional()});
export type ManagedCopy=z.infer<typeof Copy>;
export function safeManagedPath(root:string,relative:string){if(path.isAbsolute(relative)||relative.split(/[\\/]/).some(p=>p==='..'||p==='')||relative.includes('\0'))throw Error('unsafe_copy_path');const full=path.resolve(root,relative);if(full!==path.resolve(root)&&!full.startsWith(path.resolve(root)+path.sep))throw Error('unsafe_copy_path');let current=path.resolve(root);if(lstatSync(current).isSymbolicLink())throw Error('unsafe_copy_path');for(const piece of relative.split('/')){current=path.join(current,piece);if(existsSync(current)&&lstatSync(current).isSymbolicLink())throw Error('unsafe_copy_path');}return full;}
export function durableJson(filename:string,value:unknown){mkdirSync(path.dirname(filename),{recursive:true,mode:0o700});const temp=filename+'.'+randomUUID()+'.pending';const fd=openSync(temp,'wx',0o600);try{writeFileSync(fd,JSON.stringify(value));fsyncSync(fd);}finally{closeSync(fd);}renameSync(temp,filename);const dir=openSync(path.dirname(filename),'r');try{fsyncSync(dir);}finally{closeSync(dir);}}
export function createManagedCopies(root:string){mkdirSync(root,{recursive:true,mode:0o700});const file=path.join(root,'managed-copies-manifest.json');let copies:ManagedCopy[]=existsSync(file)?z.array(Copy).max(10000).parse(JSON.parse(readFileSync(file,'utf8'))):[];for(const c of copies)safeManagedPath(root,c.relativePath);
 const persist=()=>durableJson(file,copies);
 return {list:()=>copies.map(c=>({...c})),register(input:Pick<ManagedCopy,'relativePath'|'kind'>&Partial<Pick<ManagedCopy,'sourceCopyId'|'state'>>){safeManagedPath(root,input.relativePath);const existing=copies.find(c=>c.relativePath===input.relativePath&&c.state!=='purged');if(existing)return {...existing};const c=Copy.parse({...input,id:randomUUID(),state:input.state??'candidate',createdAt:new Date().toISOString()});copies.push(c);persist();return {...c};},update(id:string,patch:Partial<Pick<ManagedCopy,'kind'|'state'|'reason'>>){const current=copies.find(c=>c.id===id);if(!current)throw Error('copy_missing');Object.assign(current,Copy.parse({...current,...patch}));persist();},get(id:string){const c=copies.find(c=>c.id===id);if(!c)throw Error('copy_missing');return {...c};}};
}
export type ManagedCopies=ReturnType<typeof createManagedCopies>;
