import Database from 'better-sqlite3';
import {Worker} from 'node:worker_threads';import {createRequire} from 'node:module';
import {randomUUID,createHash} from 'node:crypto';import path from 'node:path';
import {mkdir,readFile,readdir,lstat,rm,open} from 'node:fs/promises';
import {constants} from 'node:fs';import {z} from 'zod';import {createManagedCopies,durableJson,safeManagedPath,type ManagedCopies,type ManagedCopy} from './managed-copies';
const Artifact=z.strictObject({id:z.uuid(),digest:z.string().regex(/^[0-9a-f]{64}$/),size:z.number().int().nonnegative().max(256*1024*1024)});
const BackupManifest=z.strictObject({format:z.literal(1),id:z.uuid(),createdAt:z.string(),schemaVersion:z.number().int().nonnegative(),databaseDigest:z.string().regex(/^[0-9a-f]{64}$/),artifacts:z.array(Artifact).max(100000)});
export interface CandidateInspection {schemaVersion:number;artifacts:z.infer<typeof Artifact>[]}
export interface BackupPorts {root:string;registry?:ManagedCopies;getActiveRoot():string;maintenance<T>(work:()=>Promise<T>):Promise<T>;sanitizeCandidate(db:Database.Database):void;validateRelations(db:Database.Database):void;driverPath?:string;prepareCandidate?(filename:string,compactDestination:string):Promise<CandidateInspection>;inspectCandidate?(filename:string):Promise<CandidateInspection>}
async function synchronize(file:string){const handle=await open(file,'r');try{await handle.sync();}finally{await handle.close();}}
async function secureRead(file:string){const handle=await open(file,constants.O_RDONLY|constants.O_NOFOLLOW);try{const stat=await handle.stat();if(!stat.isFile()||stat.size>256*1024*1024)throw Error('invalid_backup_file');const buffer=Buffer.alloc(stat.size+1);let offset=0;while(offset<buffer.length){const result=await handle.read(buffer,offset,buffer.length-offset,offset);if(!result.bytesRead)break;offset+=result.bytesRead;}if(offset!==stat.size||(await handle.stat()).size!==stat.size)throw Error('invalid_backup_file');return buffer.subarray(0,offset);}finally{await handle.close();}}
async function digestFile(file:string){return createHash('sha256').update(await secureRead(file)).digest('hex');}
async function safeCopy(source:string,destination:string){const bytes=await secureRead(source),handle=await open(destination,'wx',0o600);try{await handle.writeFile(bytes);await handle.sync();}finally{await handle.close();}}
/** Native Backup API runs on a dedicated readonly-source worker, never a second active writer. */
async function snapshot(source:string,destination:string,driverPath?:string){const driver=driverPath??createRequire(typeof __filename==='string'?__filename:import.meta.url).resolve('better-sqlite3');await new Promise<void>((resolve,reject)=>{const worker=new Worker(`const {parentPort,workerData}=require('node:worker_threads');const DB=require(workerData.driver);const db=new DB(workerData.source,{readonly:true,fileMustExist:true});db.backup(workerData.destination).then(()=>{db.close();parentPort.postMessage('done');},()=>{db.close();parentPort.postMessage('failed');});`,{eval:true,workerData:{source,destination,driver}});worker.once('message',result=>result==='done'?resolve():reject(Error('backup_incomplete')));worker.once('error',()=>reject(Error('backup_incomplete')));worker.once('exit',code=>{if(code!==0)reject(Error('backup_incomplete'));});});}
export function createBackupManager(ports:BackupPorts){const registry=ports.registry??createManagedCopies(ports.root);let busy=false;
 // Startup never promotes an interrupted copy by inspecting its mtime or files.
 for(const copy of registry.list())if(copy.kind==='backup'&&copy.state==='candidate')registry.update(copy.id,{kind:'failed_backup',state:'failed',reason:'backup_interrupted'});
 async function single<T>(work:()=>Promise<T>){if(busy)throw Error('maintenance_busy');busy=true;try{return await ports.maintenance(work);}finally{busy=false;}}
 async function verify(copy:ManagedCopy){const location=safeManagedPath(ports.root,copy.relativePath);for(const entry of await readdir(location)){if(!['career.sqlite','blobs','backup.json'].includes(entry))throw Error('backup_extra_file');if((await lstat(path.join(location,entry))).isSymbolicLink())throw Error('unsafe_copy_path');}const manifest=BackupManifest.parse(JSON.parse((await secureRead(path.join(location,'backup.json'))).toString('utf8')));if(manifest.id!==(copy.kind==='restore_candidate'?copy.sourceCopyId:copy.id))throw Error('backup_identity_mismatch');if(manifest.artifacts.reduce((sum,a)=>sum+a.size,0)>2*1024*1024*1024)throw Error('backup_size_exceeded');if(await digestFile(path.join(location,'career.sqlite'))!==manifest.databaseDigest)throw Error('backup_hash_mismatch');let inspection:CandidateInspection;if(ports.inspectCandidate)inspection=await ports.inspectCandidate(path.join(location,'career.sqlite'));else{const database=new Database(path.join(location,'career.sqlite'),{readonly:true,fileMustExist:true});try{if(database.pragma('integrity_check',{simple:true})!=='ok'||(database.pragma('foreign_key_check') as unknown[]).length)throw Error('backup_incomplete');inspection={schemaVersion:database.pragma('user_version',{simple:true}) as number,artifacts:z.array(Artifact).parse(database.prepare("SELECT DISTINCT b.id,b.digest,b.size FROM platform_blobs b JOIN platform_artifact_retention r ON r.blob_id=b.id WHERE b.state='published'").all())};ports.validateRelations(database);}finally{database.close();}}if(inspection.schemaVersion!==manifest.schemaVersion||JSON.stringify([...inspection.artifacts].sort((a,b)=>a.id.localeCompare(b.id)))!==JSON.stringify([...manifest.artifacts].sort((a,b)=>a.id.localeCompare(b.id))))throw Error('backup_incomplete');const names=await readdir(path.join(location,'blobs'));if(names.length!==manifest.artifacts.length||names.some(name=>!manifest.artifacts.some(a=>a.id===name)))throw Error('backup_extra_file');for(const artifact of manifest.artifacts){const file=path.join(location,'blobs',artifact.id);if(await digestFile(file)!==artifact.digest||(await lstat(file)).size!==artifact.size)throw Error('backup_hash_mismatch');}return manifest;}
 async function backup(retainCount=14){if(!Number.isInteger(retainCount)||retainCount<1||retainCount>1000)throw Error('backup_settings_invalid');return single(async()=>{const previous=registry.list().filter(c=>c.kind==='backup'&&c.state==='ready');const current=registry.register({kind:'current_workspace',relativePath:path.relative(ports.root,ports.getActiveRoot())||'.',state:'ready'});const copy=registry.register({relativePath:'backups/'+randomUUID(),kind:'backup',sourceCopyId:current.id});const location=safeManagedPath(ports.root,copy.relativePath);try{await mkdir(path.join(location,'blobs'),{recursive:true,mode:0o700});await snapshot(path.join(ports.getActiveRoot(),'career.sqlite'),path.join(location,'working.sqlite'),ports.driverPath);let artifacts:z.infer<typeof Artifact>[];let schemaVersion:number;if(ports.prepareCandidate){const prepared=await ports.prepareCandidate(path.join(location,'working.sqlite'),path.join(location,'career.sqlite'));artifacts=z.array(Artifact).parse(prepared.artifacts);schemaVersion=prepared.schemaVersion;}else{const candidate=new Database(path.join(location,'working.sqlite'));try{candidate.pragma('foreign_keys=ON');ports.sanitizeCandidate(candidate);artifacts=z.array(Artifact).parse(candidate.prepare("SELECT DISTINCT b.id,b.digest,b.size FROM platform_blobs b JOIN platform_artifact_retention r ON r.blob_id=b.id WHERE b.state='published'").all());schemaVersion=candidate.pragma('user_version',{simple:true}) as number;candidate.prepare('VACUUM INTO ?').run(path.join(location,'career.sqlite'));}finally{candidate.close();}}await rm(path.join(location,'working.sqlite'));for(const a of artifacts!){const source=path.join(ports.getActiveRoot(),'blobs',a.id);if(await digestFile(source)!==a.digest||(await lstat(source)).size!==a.size)throw Error('backup_incomplete');await safeCopy(source,path.join(location,'blobs',a.id));await synchronize(path.join(location,'blobs',a.id));}await synchronize(path.join(location,'career.sqlite'));await synchronize(path.join(location,'blobs'));durableJson(path.join(location,'backup.json'),BackupManifest.parse({format:1,id:copy.id,createdAt:copy.createdAt,schemaVersion:schemaVersion!,databaseDigest:await digestFile(path.join(location,'career.sqlite')),artifacts:artifacts!}));await verify(copy);await synchronize(location);registry.update(copy.id,{state:'ready'});
 // Publish the new complete point before pruning any earlier complete point.
 for(const old of previous.sort((a,b)=>a.createdAt.localeCompare(b.createdAt)).slice(0,Math.max(0,previous.length+1-retainCount))){await rm(safeManagedPath(ports.root,old.relativePath),{recursive:true,force:true});registry.update(old.id,{state:'purged'});}return registry.get(copy.id);
 }catch{registry.update(copy.id,{kind:'failed_backup',state:'failed',reason:'backup_incomplete'});throw Error('backup_incomplete');}});}
 async function prepareRestore(id:string){return single(async()=>{const source=registry.get(id);if(source.kind!=='backup'||source.state!=='ready')throw Error('backup_unavailable');await verify(source);const candidate=registry.register({relativePath:'workspaces/'+randomUUID(),kind:'restore_candidate',sourceCopyId:id});const dest=safeManagedPath(ports.root,candidate.relativePath);try{await mkdir(path.join(dest,'blobs'),{recursive:true,mode:0o700});const src=safeManagedPath(ports.root,source.relativePath);const manifest=await verify(source);for(const file of ['career.sqlite','backup.json',...manifest.artifacts.map(a=>'blobs/'+a.id)])await safeCopy(path.join(src,file),path.join(dest,file));await synchronize(path.join(dest,'blobs'));await synchronize(dest);await verify(candidate);registry.update(candidate.id,{state:'ready'});return registry.get(candidate.id);}catch{registry.update(candidate.id,{kind:'quarantine',state:'failed',reason:'restore_invalid'});throw Error('restore_invalid');}});}
 return {backup,prepareRestore,verify,list:()=>registry.list(),registry};
}
