import type Database from 'better-sqlite3';
import {randomUUID} from 'node:crypto';
import {Feedback,FeedbackRequest,FeedbackResult,type Screenshot} from '../../../contracts/application/feedback';
import {executeCommand,commandReceipt} from '../../platform/commands/receipts';
import {redactOwnerReceipts} from '../../platform/commands/purge-receipts';
export const feedbackMigration=`CREATE TABLE application_feedback(id TEXT PRIMARY KEY,revision INTEGER NOT NULL,content_json TEXT NOT NULL);`;
export interface FeedbackPorts{discardScreenshotCandidate?(id:string):void;resolveScreenshot(id:string):Screenshot|undefined;retainScreenshot(candidateId:string,feedbackId:string,screenshot:Screenshot):void;releaseScreenshot(id:string):void;readScreenshot(screenshot:Screenshot):string|undefined;}
export function createFeedback(db:Database.Database,ports?:FeedbackPorts){
 function read(id:string){const row=db.prepare('SELECT content_json FROM application_feedback WHERE id=?').get(id) as {content_json:string}|undefined;return row?Feedback.parse(JSON.parse(row.content_json)):undefined;}
 function list(){return (db.prepare('SELECT content_json FROM application_feedback ORDER BY rowid DESC LIMIT 500').all() as {content_json:string}[]).map(row=>Feedback.parse(JSON.parse(row.content_json)));}
 function handle(input:unknown):FeedbackResult|{kind:'failure';code:string}|{kind:'receipt_missing'}{const parsed=FeedbackRequest.safeParse(input);if(!parsed.success)return {kind:'failure' as const,code:'invalid_request'};try{const request=parsed.data;
 if(request.operation==='feedback.receipt'){const receipt=commandReceipt(db,'application.feedback',request.commandId);if(!receipt)return {kind:'receipt_missing'};if((receipt as {kind:string}).kind==='failure')return {kind:'failure',code:'content_purged'};return FeedbackResult.parse(receipt);}
 if(request.operation==='feedback.discard-screenshot')return executeCommand(db,'application.feedback',request.commandId,request,()=>{if(!ports?.discardScreenshotCandidate)throw Error('screenshot_unavailable');ports.discardScreenshotCandidate(request.candidateId);return {kind:'feedback_screenshot_discarded' as const,candidateId:request.candidateId};});
 if(request.operation==='feedback.list')return {kind:'feedback_list' as const,items:list()};
 if(request.operation==='feedback.read'||request.operation==='feedback.export'){const feedback=read(request.id);if(!feedback)return {kind:'failure' as const,code:'not_found'};if(request.operation==='feedback.read')return {kind:'feedback' as const,feedback};const image=feedback.screenshot?ports?.readScreenshot(feedback.screenshot):undefined;return {kind:'feedback_export' as const,filename:'career-feedback-'+feedback.id+'.json',text:JSON.stringify({...feedback,...feedback.screenshot?{screenshot:{...feedback.screenshot,...image?{dataURL:image}:{missing:true}}}:{}},null,2)};}
 return executeCommand(db,'application.feedback',request.commandId,request,()=>{let feedback:Feedback;
 if(request.operation==='feedback.create'){const screenshot=request.screenshotCandidateId?ports?.resolveScreenshot(request.screenshotCandidateId):undefined;if(request.screenshotCandidateId&&!screenshot)throw Error('screenshot_unavailable');const recordedAt=new Date().toISOString();feedback=Feedback.parse({id:randomUUID(),revision:1,location:request.location,entries:[{text:request.text,recordedAt}],...screenshot?{screenshot}:{},archived:false,recordedAt});if(screenshot)ports!.retainScreenshot(request.screenshotCandidateId!,feedback.id,screenshot);}
 else{const current=read(request.id);if(!current)return {kind:'failure' as const,code:'not_found'};if(current.revision!==request.expectedRevision)return {kind:'feedback_conflict' as const,feedback:current};feedback=Feedback.parse({...current,revision:current.revision+1,...request.operation==='feedback.append'?{entries:[...current.entries,{text:request.text,recordedAt:new Date().toISOString()}]}:{archived:request.archived}});}
 db.prepare('INSERT INTO application_feedback VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET revision=excluded.revision,content_json=excluded.content_json').run(feedback.id,feedback.revision,JSON.stringify(feedback));return {kind:'feedback' as const,feedback};});
 }catch(error){return {kind:'failure' as const,code:error instanceof Error&&['conflict','screenshot_unavailable'].includes(error.message)?error.message:'storage_failed'};}}
 return {handle,list,purgeImpact(id:string){const feedback=read(id);return feedback?{id,revision:feedback.revision,name:'反馈及附件',blobIds:feedback.screenshot?[feedback.screenshot.blobId]:[],retentions:feedback.screenshot?[{owner:'feedback',objectId:id}]:[]}:undefined;},purge(id:string){db.transaction(()=>{ports?.releaseScreenshot(id);db.prepare('DELETE FROM application_feedback WHERE id=?').run(id);redactOwnerReceipts(db,'application.feedback',[id],{kind:'failure',code:'content_purged'});})();}};
}
export function validateFeedbackCandidate(db:Database.Database){for(const row of db.prepare('SELECT id,revision,content_json FROM application_feedback').all() as {id:string;revision:number;content_json:string}[]){const feedback=Feedback.parse(JSON.parse(row.content_json));if(feedback.id!==row.id||feedback.revision!==row.revision)throw Error('backup_domain_invalid');if(feedback.screenshot&&!db.prepare("SELECT 1 FROM platform_blobs b JOIN platform_artifact_retention r ON r.blob_id=b.id WHERE b.id=? AND b.digest=? AND b.size=? AND b.state='published' AND r.owner='feedback' AND r.object_id=?").get(feedback.screenshot.blobId,feedback.screenshot.digest,feedback.screenshot.size,row.id))throw Error('backup_relation_invalid');}}
