import type {TaskEvidence,ProductPolicy} from '../../../contracts/ai/task-policy';
import type {ProductContext,Dependency,ProductTarget} from '../../../contracts/ai/product-context';
import type {Provenance} from '../../../contracts/common/provenance';
import {ResumeBlock} from '../../../contracts/resume/schema';
import type {createResumeDomain} from './public';
export type RelatedContext=TaskEvidence;
export function createResumeAiPolicy(owner:ReturnType<typeof createResumeDomain>,related:(opportunityId:string)=>RelatedContext):ProductPolicy{
 function target(input:ProductTarget){if(input.kind!=='resume-optimize')throw Error('invalid_policy');return input;}
 return {
  targets(input){return [{owner:'resume',objectId:target(input).resumeId}];},
  prepare(input){const selected=target(input);if(new Set(selected.blockIds).size!==selected.blockIds.length)throw Error('duplicate_block');const result=owner.handle({operation:'resume.read',resumeId:selected.resumeId});if(result.status!=='document')throw Error('target_unavailable');const blocks=selected.blockIds.map(id=>{const block=owner.blockDependency(selected.resumeId,id);if(!block)throw Error('target_unavailable');return block;});const context=related(result.document.opportunityId),resumeBlocks=blocks.map(({section,block,digest,anchorDigest})=>({sectionId:section.id,blockId:block.id,block,canDelete:result.document.content.sections.reduce((n,s)=>n+s.blocks.length,0)>1,title:section.title,text:block.type==='paragraph'?block.spans.map(span=>span.text).join(''):block.items.map(item=>item.spans.map(span=>span.text).join('')).join('\n'),digest,anchorDigest}));
   return {context:{target:input,body:context.body+'\n\n已选最小简历正文：\n'+resumeBlocks.map(block=>block.title+'\n'+block.text).join('\n\n')+'\n受管理姓名、联系方式、地址、链接默认未加入。自由正文没有万能脱敏保证；请核对最终预览。',missing:context.missing,dependencies:[...context.dependencies,...blocks.flatMap(block=>[{owner:'resume',objectId:selected.resumeId,revision:result.document.revision,role:'target' as const,locator:block.block.id,digest:block.digest},{owner:'resume',objectId:selected.resumeId,revision:result.document.revision,role:'target' as const,locator:'anchor:'+block.block.id,digest:block.anchorDigest}])],resumeBlocks,identityFields:[]},provenance:[...context.provenance,...blocks.flatMap(block=>block.provenance),{owner:'resume',objectId:selected.resumeId,revision:result.document.revision,scope:'opportunity',scopeId:result.document.opportunityId,kind:'current_resume_selected_blocks',restrictions:{read:true,egress:true}}],sources:[]};
  },
  validate(change,context){const selected=target(context.target),id=change.kind==='resume-add'?change.afterBlockId:change.kind==='resume-block'||change.kind==='resume-delete'?change.blockId:undefined;const kind=change.kind==='resume-add'?'add':change.kind==='resume-delete'?'delete':'rewrite';if(!id||!selected.changeKinds.includes(kind)||!selected.blockIds.includes(id)||!context.resumeBlocks?.some(b=>b.blockId===id)||change.kind==='resume-delete'&&!context.resumeBlocks.find(b=>b.blockId===id)?.canDelete||change.kind==='resume-block'&&change.after.id!==id||change.kind==='resume-add'&&context.resumeBlocks?.some(b=>b.blockId===change.after.id))throw Error('invalid_output');},
  dependencies(change,context){const locator=change.kind==='resume-add'?'anchor:'+change.afterBlockId:change.kind==='resume-block'||change.kind==='resume-delete'?change.blockId:undefined;if(!locator)throw Error('invalid_output');return context.dependencies.filter(dep=>dep.role==='evidence'||dep.owner!=='resume'||dep.locator===locator);},
  apply({commandId,proposal,edited}){const selected=target(proposal.target),change=proposal.change;if(!['resume-block','resume-add','resume-delete'].includes(change.kind))throw Error('invalid_output');const id=change.kind==='resume-add'?change.afterBlockId:change.kind==='resume-block'||change.kind==='resume-delete'?change.blockId:'';const dependency=proposal.dependencies.find(dep=>dep.owner==='resume'&&dep.locator===(change.kind==='resume-add'?'anchor:'+id:id));if(!dependency?.digest)throw Error('invalid_dependency');if(change.kind==='resume-delete'&&edited)throw Error('invalid_output');const after=change.kind==='resume-delete'?undefined:edited?ResumeBlock.parse(edited):'after'in change?change.after:undefined;const before=owner.blockDependency(selected.resumeId,id)?.doc;if(!before)throw Error('target_unavailable');const result=owner.applyBlockProposal({commandId,resumeId:selected.resumeId,blockId:id,expectedDigest:dependency.digest,action:change.kind==='resume-add'?'insert':change.kind==='resume-delete'?'delete':'replace',after,provenance:proposal.provenance});if(result.status!=='document')throw Error(result.status==='conflict'?'conflict':'target_unavailable');return {owner:'resume',objectId:selected.resumeId,resumeApplication:{before,after:result.document}};}
 };
}
