import type Database from 'better-sqlite3';
import {createHash} from 'node:crypto';
import {Document,Snapshot,Version,NameVersion,Export,BlockProvenance} from '../../../contracts/resume/schema';
function validateSnapshot(value:Snapshot){if(value.profileRevision!==value.profile.revision||createHash('sha256').update(JSON.stringify({content:value.content,profile:value.profile,...value.blockProvenance?{blockProvenance:value.blockProvenance}:{}})).digest('hex')!==value.contentHash)throw Error('invalid_candidate');}
export function validateCandidate(db:Database.Database):void {
 const documents=new Map<string,zDocument>();
 for(const row of db.prepare('SELECT id,opportunity_id,revision,content,recorded_at FROM resume_documents').all() as {id:string;opportunity_id:string;revision:number;content:string;recorded_at:string}[]){const value=Document.parse({id:row.id,opportunityId:row.opportunity_id,revision:row.revision,content:JSON.parse(row.content),recordedAt:row.recorded_at});documents.set(value.id,value);}
 if(db.prepare("SELECT 1 FROM sqlite_master WHERE name='resume_block_provenance'").get())for(const row of db.prepare('SELECT resume_id,block_id,provenance_json FROM resume_block_provenance').all() as {resume_id:string;block_id:string;provenance_json:string}[]){const proof=BlockProvenance.parse({blockId:row.block_id,provenance:JSON.parse(row.provenance_json)});if(!documents.get(row.resume_id)?.content.sections.some(section=>section.blocks.some(block=>block.id===proof.blockId)))throw Error('invalid_candidate');}
 for(const row of db.prepare('SELECT command_id,payload_json,snapshot_json,name FROM resume_render_jobs').all() as {command_id:string;payload_json:string;snapshot_json:string;name:string}[]){const request=NameVersion.or(Export).parse(JSON.parse(row.payload_json));const snapshot=Snapshot.parse(JSON.parse(row.snapshot_json));validateSnapshot(snapshot);const document=documents.get(snapshot.resumeId);if(request.commandId!==row.command_id||snapshot.id!==row.command_id||request.resumeId!==snapshot.resumeId||request.expectedRevision!==snapshot.resumeRevision||request.expectedProfileRevision!==snapshot.profileRevision||row.name!==('name'in request?request.name:'')||!document||snapshot.opportunityId!==document.opportunityId||snapshot.resumeRevision>document.revision)throw Error('invalid_candidate');}
 for(const row of db.prepare('SELECT id,resume_id,body FROM resume_versions').all() as {id:string;resume_id:string;body:string}[]){const value=Version.parse(JSON.parse(row.body));validateSnapshot(value.snapshot);const document=documents.get(row.resume_id);if(value.id!==row.id||value.resumeId!==row.resume_id||value.snapshot.id!==value.id||value.snapshot.resumeId!==value.resumeId||!document||value.snapshot.opportunityId!==document.opportunityId||value.snapshot.resumeRevision>document.revision||value.kind==='export'&&value.name!==''||value.kind!=='export'&&!value.name.trim())throw Error('invalid_candidate');}
}
type zDocument=ReturnType<typeof Document.parse>;
/** References only; frozen Profile content is a snapshot, not a live Profile dependency. */
export function candidateRelations(db:Database.Database):{owner:string;objectId:string;kind:'object'|'source'}[]{
 const relations:{owner:string;objectId:string;kind:'object'|'source';provenance?:import('../../../contracts/common/provenance').Provenance}[]=[];const add=(values:ReturnType<typeof BlockProvenance.parse>[])=>{for(const value of values)for(const provenance of value.provenance)relations.push({owner:provenance.owner,objectId:provenance.objectId,kind:'object',provenance});};if(db.prepare("SELECT 1 FROM sqlite_master WHERE name='resume_block_provenance'").get())for(const row of db.prepare('SELECT block_id,provenance_json FROM resume_block_provenance').all() as {block_id:string;provenance_json:string}[])add([BlockProvenance.parse({blockId:row.block_id,provenance:JSON.parse(row.provenance_json)})]);
 for(const row of db.prepare('SELECT opportunity_id FROM resume_documents').all() as {opportunity_id:string}[])relations.push({owner:'opportunity',objectId:row.opportunity_id,kind:'object'});
 for(const row of db.prepare('SELECT snapshot_json FROM resume_render_jobs').all() as {snapshot_json:string}[]){const snapshot=Snapshot.parse(JSON.parse(row.snapshot_json));relations.push({owner:'opportunity',objectId:snapshot.opportunityId,kind:'object'});add(snapshot.blockProvenance??[]);}
 for(const row of db.prepare('SELECT body FROM resume_versions').all() as {body:string}[]){const value=Version.parse(JSON.parse(row.body));relations.push({owner:'opportunity',objectId:value.snapshot.opportunityId,kind:'object'});add(value.snapshot.blockProvenance??[]);}
 return relations;
}
