import type{CareerDocument,Span}from'../../../contracts/resume/schema';
/** Static port of the supplied ResumePreview SectionTitle/EntryRow template, using frozen Career values. */
export const MIAODA_PRINT_CSS=`header{text-align:center}h1{font-size:calc(24px * var(--miaoda-font-scale,1));line-height:32px;font-weight:700;margin:0}header p{font-size:calc(12px * var(--miaoda-font-scale,1));line-height:18px;margin:4px 0 0;color:#737373}.miaoda-paper-section{padding:0;margin:0;border:0}.miaoda-paper-section h2{display:flex;align-items:center;gap:8px;border-bottom:1px solid #e5e5e5;padding:0 0 4px;margin:16px 0;font-size:calc(16px * var(--miaoda-font-scale,1));line-height:24px;font-weight:600;break-after:avoid}.miaoda-paper-section h2 span{display:inline-block;height:16px;width:4px;flex-shrink:0;border-radius:4px;background:#262626}.miaoda-entry-row{display:grid;grid-template-columns:140px minmax(0,1fr) auto;align-items:baseline;column-gap:16px;border-bottom:1px dashed #f5f5f5;padding:8px 0;break-inside:avoid}.miaoda-entry-row:last-child{border:0}.miaoda-period{font-variant-numeric:tabular-nums;color:#737373;font-size:calc(12px * var(--miaoda-font-scale,1))}.miaoda-entry-title{font-size:calc(14px * var(--miaoda-font-scale,1));font-weight:600}.miaoda-entry-subtitle,.miaoda-extra{color:#737373;font-size:calc(12px * var(--miaoda-font-scale,1))}.miaoda-description{grid-column:1/-1;white-space:pre-wrap;font-size:calc(12px * var(--miaoda-font-scale,1));line-height:1.625;color:#525252}.miaoda-paper-section p,.miaoda-paper-section li{font-size:calc(12px * var(--miaoda-font-scale,1));line-height:1.625;color:#404040;white-space:pre-wrap;margin:0}.miaoda-skill+.miaoda-skill{margin-top:6px}.miaoda-paper-section ul{padding-left:18px}section{break-inside:auto}`;
export function renderMiaodaSections(content:CareerDocument,escape:(s:string)=>string,spans:(v:Span[])=>string){
 const categories=[{kind:'summary',title:'个人简介',aliases:['个人简介']},{kind:'education',title:'教育经历',aliases:['教育','教育经历']},{kind:'experience',title:'实习经历',aliases:['经历','实习经历']},{kind:'project',title:'项目经历',aliases:['项目','项目经历']},{kind:'skills',title:'专业技能',aliases:['技能','专业技能']}];
 const sections=categories.flatMap(c=>{const matching=content.sections.filter(s=>s.kind===c.kind),standard=matching.filter(s=>c.aliases.includes(s.title)),custom=matching.filter(s=>!c.aliases.includes(s.title));return [...(standard.length?[{...standard[0],title:c.title,blocks:standard.flatMap(s=>s.blocks)}]:[]),...custom];});
 return sections.map(section=>{
 const paragraphs=section.blocks.filter(b=>b.type==='paragraph'),ids=new Set(paragraphs.flatMap(b=>b.entry?[b.entry.id]:[])),plain=section.blocks.filter(b=>b.type!=='paragraph'||!b.entry);
 if(!ids.size&&!plain.some(b=>b.type==='paragraph'?b.spans.some(s=>s.text):b.items.length))return '';
 const entries=[...ids].map(id=>{const value=(field:string)=>paragraphs.filter(b=>b.entry?.id===id&&b.entry.field===field).flatMap(b=>b.spans),text=(field:string)=>value(field).map(s=>s.text).join(''),style=(field:string)=>{const a=paragraphs.find(b=>b.entry?.id===id&&b.entry.field===field)?.alignment;return a?' style="text-align:'+a+'"':'';};const title=section.kind==='education'?'school':section.kind==='experience'?'company':section.kind==='project'?'name':'category';
 if(section.kind==='skills')return '<p class="miaoda-skill"'+style('items')+'><strong>'+spans(value(title))+(text(title)?'：':'')+'</strong>'+spans(value('items'))+'</p>';
 const period=text('startDate')||text('endDate')?escape(text('startDate')+' – '+text('endDate')):'';
 const subtitle=section.kind==='education'?spans(value('degree'))+(text('degree')&&text('major')?' · ':'')+spans(value('major')):spans(value(section.kind==='project'?'role':'position'));
 return '<div class="miaoda-entry-row"><div class="miaoda-period">'+period+'</div><div><div class="miaoda-entry-title"'+style(title)+'>'+spans(value(title))+'</div><div class="miaoda-entry-subtitle">'+subtitle+'</div></div><div class="miaoda-extra">'+spans(value('techStack'))+'</div>'+(text('description')?'<div class="miaoda-description"'+style('description')+'>'+spans(value('description'))+'</div>':'')+'</div>';
 }).join('');
 const blocks=plain.map(b=>b.type==='paragraph'?'<p'+(b.alignment?' style="text-align:'+b.alignment+'"':'')+'>'+spans(b.spans)+'</p>':'<ul>'+b.items.map(i=>'<li'+(i.alignment?' style="text-align:'+i.alignment+'"':'')+'>'+spans(i.spans)+'</li>').join('')+'</ul>').join('');
 return '<section class="miaoda-paper-section"><h2><span aria-hidden="true"></span>'+escape(section.title)+'</h2>'+entries+blocks+'</section>';
 }).join('');
}
