import React from 'react';
import type {BusinessTime} from '../../../../contracts/common/business-time';
import type {SentResumeInput} from '../../../../contracts/opportunity/submission/schema';
export interface SendCandidate {kind:'resume'|'artifact';id:string;name:string}
export interface SendingForm {resumeKind:SentResumeInput['kind'];candidateKey:string;explanation:string;knownContent:string;greetingKind:'not_used'|'empty'|'unknown'|'known';greetingText:string;timeKind:'unknown'|'date'|'instant';date:string;instant:string;timezone:string;reason:string;historical:boolean}
export function initialSendingForm():SendingForm{return {resumeKind:'not_used',candidateKey:'',explanation:'',knownContent:'',greetingKind:'unknown',greetingText:'',timeKind:'unknown',date:'',instant:'',timezone:'',reason:'',historical:false};}
export function sendingValues(form:SendingForm,candidates:SendCandidate[]){const candidate=candidates.find(item=>`${item.kind}:${item.id}`===form.candidateKey);return {resume:form.resumeKind==='retained'?{kind:'retained',candidate:candidate?{kind:candidate.kind,id:candidate.id}:undefined}:form.resumeKind==='not_used'?{kind:'not_used'}:form.resumeKind==='content_unknown'?{kind:'content_unknown',explanation:form.explanation}:{kind:'file_missing',knownContent:form.knownContent,explanation:form.explanation},greeting:form.greetingKind==='known'?{kind:'known',text:form.greetingText}:{kind:form.greetingKind},businessTime:form.timeKind==='unknown'?{kind:'unknown'}:form.timeKind==='date'?{kind:'date',date:form.date}:{kind:'instant',instant:form.instant,timezone:form.timezone},reason:form.reason,historical:form.historical};}
export function TimeFields({form,patch}:{form:SendingForm;patch(values:Partial<SendingForm>):void}){return <><label>实际发送时间<select aria-label="实际发送时间" value={form.timeKind} onChange={event=>patch({timeKind:event.target.value as SendingForm['timeKind']})}><option value="unknown">未知（不猜今天）</option><option value="date">仅实际日期</option><option value="instant">精确时刻和原时区</option></select></label>{form.timeKind==='date'&&<label>实际发送日期<input type="date" value={form.date} onChange={event=>patch({date:event.target.value})}/></label>}{form.timeKind==='instant'&&<><label>发送时刻（含偏移）<input value={form.instant} onChange={event=>patch({instant:event.target.value})}/></label><label>原时区<input value={form.timezone} onChange={event=>patch({timezone:event.target.value})}/></label></>}<label>记录或纠错说明<input maxLength={2000} value={form.reason} onChange={event=>patch({reason:event.target.value})}/></label><label><input type="checkbox" checked={form.historical} onChange={event=>patch({historical:event.target.checked})}/>晚补已发生的历史</label></>;}
export function SendingFields({form,patch,candidates,selectActual}:{form:SendingForm;patch(values:Partial<SendingForm>):void;candidates:SendCandidate[];selectActual?:()=>void}){return <><label>本次实际简历状态<select aria-label="本次实际简历状态" value={form.resumeKind} onChange={event=>patch({resumeKind:event.target.value as SendingForm['resumeKind']})}><option value="not_used">明确没使用简历</option><option value="content_unknown">使用简历，但内容未知</option><option value="file_missing">内容已知，但历史原文件缺失</option><option value="retained">实际发送文件仍存在</option></select></label>{form.resumeKind==='retained'?<><label>选择当时真实发送材料<select aria-label="选择当时真实发送材料" value={form.candidateKey} onChange={event=>patch({candidateKey:event.target.value})}><option value="">明确选择已保存的材料</option>{candidates.map(item=><option key={`${item.kind}:${item.id}`} value={`${item.kind}:${item.id}`}>{item.name}</option>)}</select></label>{selectActual&&<button type="button" onClick={selectActual}>选择外部实际发送文件</button>}<p>仅保留当时实际文件；不拿最新稿或重新生成 PDF 代替。</p></>:form.resumeKind!=='not_used'&&<><label>历史缺失说明<input value={form.explanation} onChange={event=>patch({explanation:event.target.value})}/></label>{form.resumeKind==='file_missing'&&<label>当时已知的具体内容<textarea aria-label="当时已知的具体内容" value={form.knownContent} onChange={event=>patch({knownContent:event.target.value})}/></label>}</>}
 <label>Greeting 实际状态<select aria-label="Greeting 实际状态" value={form.greetingKind} onChange={event=>patch({greetingKind:event.target.value as SendingForm['greetingKind']})}><option value="unknown">历史未记录，未知</option><option value="not_used">明确未使用</option><option value="empty">确实发送了空 Greeting</option><option value="known">已知具体 Greeting</option></select></label>{form.greetingKind==='known'&&<label>实际 Greeting<textarea aria-label="实际 Greeting" value={form.greetingText} onChange={event=>patch({greetingText:event.target.value})}/></label>}
 <TimeFields form={form} patch={patch}/></>;}

export function formatSendingTime(time:BusinessTime){return time.kind==='unknown'?'未知':time.kind==='date'?time.date:`${time.instant}（${time.timezone}）`;}
