import {wasPurged,type PurgeNotice} from '../../../design-system/purge-notice';
import React,{useState,useEffect,useRef} from 'react';
import {Request,Result,type Submission} from '../../../../contracts/opportunity/submission/schema';
import type {OpportunityView} from '../../../../contracts/opportunity/schema';
import {SendingFields,TimeFields,formatSendingTime,initialSendingForm,sendingValues,type SendingForm,type SendCandidate} from './fields';
export type {SendCandidate} from './fields';
interface Session {form:SendingForm;opportunity?:OpportunityView;submission?:Submission;loaded:boolean;status:string;pending?:Request;busy:boolean;receiptMissing?:boolean;candidates:SendCandidate[];dirty:boolean;purged?:boolean;server?:Result}
const initial=():Session=>({form:initialSendingForm(),loaded:false,status:'正在读取首次投递',busy:false,candidates:[],dirty:false});
export function SubmissionPage({purgeNotice,workspaceInstance,opportunityId,request,candidates=[],selectActual,onChanged}:{purgeNotice?:PurgeNotice;workspaceInstance:string;opportunityId:string;request(input:Request):Promise<unknown>;candidates?:SendCandidate[];selectActual?:()=>Promise<SendCandidate|undefined>;onChanged?:()=>void}){
 const [editing,setEditing]=useState(false);
 const key=`${workspaceInstance}:${opportunityId}`;const [sessions,setSessions]=useState<Record<string,Session>>({});const session=sessions[key]??initial();const send=useRef(request);send.current=request;const active=useRef(key);active.current=key;const composing=useRef(false);
 function update(target:string,patch:Partial<Session>){setSessions(old=>({...old,[target]:{...(old[target]??initial()),...patch}}));}
 function patch(form:Partial<SendingForm>){update(key,{form:{...session.form,...form},dirty:true});}
 async function read(target=key,explicit=false){try{const result=Result.parse(await send.current({operation:'submission.read',opportunityId}));if(result.kind==='submission'||result.kind==='empty')setSessions(old=>{const state=old[target]??initial();return {...old,[target]:{...state,loaded:true,opportunity:result.opportunity,submission:result.kind==='submission'?result.submission:undefined,status:explicit&&state.dirty?'正式基线已读取，草稿保留，请确认后再保存。':'已读取正式首次投递'}};});else if(result.kind==='purged')update(target,{loaded:true,purged:true,status:'首次投递材料已永久清除；仅保留发生身份，不能再建第二次首次投递。'});else update(target,{status:'首次投递读取失败；不会视作尚无投递。'});}catch{update(target,{status:'首次投递暂不可读；输入保留。'});}}
 useEffect(()=>{if(!sessions[key]?.loaded)void read(key);},[key]);
 useEffect(()=>{const guard=(event:BeforeUnloadEvent)=>{if(Object.values(sessions).some(value=>value.dirty||value.pending)){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[sessions]);
 useEffect(()=>{if(!purgeNotice)return;setSessions(old=>Object.fromEntries(Object.entries(old).map(([id,value])=>wasPurged(purgeNotice,'submission',value.submission?.id)?[id,{...initial(),loaded:true,purged:true,status:'这次投递内容已永久清除；原发生身份仍保留。'}]:[id,value])));},[purgeNotice?.sequence]);
 const allCandidates=[...candidates,...session.candidates].filter((item,index,all)=>all.findIndex(other=>other.id===item.id&&other.kind===item.kind)===index);
 async function resultFor(target:string,result:Result){if(result.kind==='submission'){update(target,{loaded:true,submission:result.submission,opportunity:result.opportunity,dirty:false,pending:undefined,busy:false,status:'已保存真实首次投递；材料冻结保留。'});if(active.current===target)onChanged?.();}else if(result.kind==='purged'){update(target,{purged:true,loaded:true,busy:false,pending:undefined,dirty:false,status:'原投递内容已永久清除；这次保存不会重新生成材料。'});}else if(result.kind==='failure'){update(target,{busy:false,pending:undefined,status:`保存未完成。草稿保留；文件失败不会改称历史缺失。`});}else if(result.kind==='receipt_missing')update(target,{busy:false,receiptMissing:true,status:'确认尚未保存，可明确继续这次保存。'});}
 async function run(intent:Request,target=key){update(target,{busy:true,pending:intent,status:'正在保存',receiptMissing:false});try{await resultFor(target,Result.parse(await send.current(intent)));}catch{update(target,{busy:false,status:'结果暂时无法确认；请检查是否已保存，草稿保留。'});}}
 function submit(){if(!session.opportunity||session.busy||session.pending||composing.current)return;const values=sendingValues(session.form,allCandidates);const parsed=Request.safeParse(session.submission?{operation:'submission.correct-time',commandId:crypto.randomUUID(),opportunityId,expectedOpportunityRevision:session.opportunity.revision,expectedRevision:session.submission.revision,businessTime:values.businessTime,reason:values.reason}:{operation:'submission.record-first',commandId:crypto.randomUUID(),opportunityId,expectedOpportunityRevision:session.opportunity.revision,...values});if(!parsed.success){update(key,{status:'请明确真实材料状态、缺失说明、实际时间和记录说明。'});return;}void run(parsed.data);}
 async function choose(){const target=key;if(!selectActual)return;update(target,{busy:true});try{const item=await selectActual();setSessions(old=>{const state=old[target]??initial();return {...old,[target]:{...state,busy:false,...item?{candidates:[...state.candidates,item],form:{...state.form,resumeKind:'retained',candidateKey:`${item.kind}:${item.id}`},dirty:true,status:'真实文件已准备；仍需确认已经发送。'}:{status:'已取消选取，草稿保留。'}}};});}catch{update(target,{busy:false,status:'实际文件保存失败；不可降级为历史缺失。'});}}
 return <section aria-label="首次投递" onCompositionStart={()=>{composing.current=true;}} onCompositionEnd={()=>{composing.current=false;}}><h2>投递与发送材料</h2><p>只登记本人确认已经发生的首次发送；本工具不替你发送。每个机会最多一次。</p>{session.loaded&&!session.purged?<><button className="opportunity-primary" onClick={()=>setEditing(true)}>{session.submission?'修改投递时间':'记录已投递'}</button>{!session.submission&&<p>只记录现实已经发生的首次正式投递。后续补发在沟通记录中单独登记。</p>}{session.submission?<><p>已登记首次投递；实际材料状态：{session.submission.resume.kind==='retained'?'实际文件已保留':session.submission.resume.kind==='not_used'?'未使用简历':session.submission.resume.kind==='content_unknown'?'当时材料未知':'历史文件缺失'}</p>{session.submission.resume.kind==='retained'&&<p>冻结文件：{session.submission.resume.name}</p>}{session.submission.resume.kind==='file_missing'&&<p>已知当时内容：{session.submission.resume.knownContent}</p>}<p>实际发送时间：{formatSendingTime(session.submission.businessTime)}；录入时间：{session.submission.recordedAt}{session.submission.historical?' · 晚补历史':''}</p><p>沟通文字：{session.submission.greeting.kind==='known'?'当时正文已保留':session.submission.greeting.kind==='not_used'?'未使用':'当时内容未知'}{session.submission.greeting.kind==='known'?` · ${session.submission.greeting.text}`:''}</p><fieldset hidden={!editing} disabled={session.busy||!!session.pending}><legend>仅明确纠正同一次真实发送时间</legend><TimeFields form={session.form} patch={patch}/></fieldset></>:<fieldset hidden={!editing} disabled={session.busy||!!session.pending}><SendingFields form={session.form} patch={patch} candidates={allCandidates} selectActual={selectActual?()=>void choose():undefined}/></fieldset>}<button hidden={!editing} disabled={session.busy||!!session.pending} onClick={submit}>{session.submission?'纠正首次投递时间':'确认真实首次投递'}</button></>:null}<button disabled={session.busy||!!session.pending} onClick={()=>void read(key,true)}>刷新投递记录（保留输入）</button><p role="status">{session.status}{session.dirty?' · 有未保存输入':''}</p>{session.pending&&'commandId'in session.pending&&<><button disabled={session.busy} onClick={async()=>{const target=key;update(target,{busy:true});try{await resultFor(target,Result.parse(await send.current({operation:'submission.receipt',commandId:(session.pending as {commandId:string}).commandId})));}catch{update(target,{busy:false,status:'暂时无法确认是否已保存；不会重新保存。'});}}}>检查是否已保存</button>{session.receiptMissing&&<button onClick={()=>void run(session.pending!)}>继续这次保存</button>}</>}</section>;
}
